HedvigInsurance/racoon

- apps/onboarding/src/components/language-switcher.tsx
Fix 404 links in language switcher.
Avoid rendering link until router is ready.
The next docs recommend not using `asPath` until router is ready:
https://nextjs.org/docs/api-reference/next/router#router-object
> GRW-1239 / Fix / 404 links in language switcher

- apps/store/src/components/CartList/CartList.tsx
- apps/store/src/components/ProductPage/ProductPage.tsx
- apps/store/src/services/mockCartService.ts
- apps/store/src/services/mockCmsService.ts
Read title ☝🏻 
The idea was to get ride of the code that connects info between `product` and `cmsProduct` from a component level. That's because [`getProductByMarketAndProduct`](https://github.com/HedvigInsurance/racoon/compare/refact/cart-list?expand=1#diff-c29933a30df352a916eeeb7754b07a04f2c954421e829fc29f2c0401bf55eb87L45) represents what would be one day asynchronous code and we probably don't want to fetch data from a component level when it's not necessary.
> refact(CartList): removes component level integration between product and cms prodcut

- apps/onboarding/src/components/BodyText.tsx
- apps/onboarding/src/components/FixedFooter.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/HomePage/HomePage.tsx
- apps/store/src/pages/[...slug].tsx
- apps/store/src/pages/_app.tsx
- packages/scripts/.eslintrc.js
- packages/scripts/package.json
- packages/ui/src/components/Button/Button.stories.tsx
- packages/ui/src/components/Heading/Heading.tsx
- packages/ui/src/components/InputStepper/InputStepper.tsx
- packages/ui/src/components/Menu/MenuLink.tsx
- yarn.lock
Improve typescript linting (to warn for unused-vars and such) and fix warnings and errors
Improve code styling
Stuff to improve
- Eslint doesn't seem to highlight warnings in VSCode still. Does that work for you?
> Feat / Improve lint setup

- packages/ui/src/components/Heading/Heading.tsx
- packages/ui/src/components/HeadingNew/HeadingNew.helpers.ts
- packages/ui/src/components/HeadingNew/HeadingNew.stories.tsx
- packages/ui/src/components/HeadingNew/HeadingNew.tsx
New Heading component to support the new fonts. Since the serif font is actually different fonts depending on size and letter-spacing varies between standard and serif, I combined them into variants.
We could split up the `fontSize` (where we pass in the theme fontSize values instead) and `fontFamily` into two props. But all sizes shouldn't be supported in the serif fonts (the serif font is not supposed to be used smaller than 20px). 
https://user-images.githubusercontent.com/6661511/179250740-377acd3a-4b21-4350-8850-a7eb24134f24.mov
Next steps:
- Add media query support
> Add new Heading component with variants

- packages/ui/src/lib/theme/colors.ts
- packages/ui/src/lib/theme/theme.ts
- Make sure theme get inferred color types
- Stop using colors from brand repo - this will be deprecated when we go live with the store
The thought is that we have set of brand colors that we reference for color aliases.
> Infer proper type on colors

- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/TopMenu/TopMenu.tsx
Update layout component to place TopMenu on top of page content.
Remove background + color from TopMenu.
Designers are not 100% ready with the interaction so expect changes to come.
[GRW-1310]: https://hedvig.atlassian.net/browse/GRW-1310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make TopMenu float above page content

- apps/store/src/components/CartNotification/Header.tsx
Even though not describe in the documentation, it seems Dialog title components should be able to accept a ref. Since our custom component used [here](https://github.com/HedvigInsurance/racoon/blob/main/apps/store/src/components/CartNotification/CartToast.tsx#L45) a warning is raised.
> fix(store: CartNotificationHeader): remove missing ref warning

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/ProductPage/PriceCalculatorFooter/PriceCalculatorFooter.tsx
- apps/store/src/components/ProductPage/PriceFooter/PriceFooter.stories.tsx
- apps/store/src/components/ProductPage/PriceFooter/PriceFooter.tsx
- apps/store/src/components/ProductPage/ScrollPast/ScrollPast.tsx
- apps/store/src/components/ProductPage/ScrollToButton/ScrollToButton.tsx
Add PriceCalculatorFooter component.
Integrate price calculator footer in CMS block.
Refactor PriceFooter and ScrollPast components.
[Screen Recording 2022-08-02 at 15.31.53.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/1765789b-70f9-4839-af47-49c7497f9ab5/Screen%20Recording%202022-08-02%20at%2015.31.53.mov)
I think it make sense that everything to do with the price calculator goes along with the CMS block.
[GRW-1304]: https://hedvig.atlassian.net/browse/GRW-1304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add PriceCalculatorFooter to block

- .github/workflows/chromatic.yml
- apps/store/package.json
- apps/store/src/components/CartCard/CartCard.stories.tsx
- apps/store/src/components/CartCard/CartCard.tsx
- package.json
- turbo.json
Integrate with the basic version of Chromatic platform to include Storybook in code review process.
https://www.chromatic.com/docs/
Let's try out this platform. The basic plan is "free forever". It also let's us off load the Storybook deployments from Vercel.
I didn't add "chromatic" as a deployment - better see if we can make it work with just the latest version (using npx).
It's also not a mission critical tool.
[GRW-1312]: https://hedvig.atlassian.net/browse/GRW-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add support for publishing to Chromatic

- apps/market-web/src/blocks/HeadlineBlock/HeadlineBlock.tsx
- apps/market-web/src/blocks/HeroBlock/HeroBlock.tsx
- apps/market-web/src/blocks/PageHeaderBlock/PageHeaderBlock.tsx
- apps/market-web/src/blocks/blockHelpers.tsx
- apps/market-web/src/components/Heading/Heading.tsx
- apps/market-web/src/components/Menu/LanguagePicker.tsx
- apps/market-web/src/components/Menu/Menu.tsx
- apps/onboarding/package.json
- apps/onboarding/public/mockServiceWorker.js
- apps/onboarding/src/pages/_document.tsx
- packages/ui/package.json
- packages/ui/src/components/BurgerButton/BurgerButton.tsx
- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/components/Card/Card.tsx
- packages/ui/src/components/Card/SelectableCard.tsx
- packages/ui/src/components/HeadingNew/HeadingNew.tsx
- packages/ui/src/components/Menu/MenuItem.tsx
- packages/ui/src/components/Menu/MenuItemGroup.tsx
- packages/ui/src/components/Menu/MenuLink.tsx
- packages/ui/src/components/Menu/SubMenu.tsx
- packages/ui/src/components/QuotePriceCard/QuotePriceCard.tsx
- packages/ui/src/index.tsx
- packages/ui/src/lib/globalStyles.ts
- packages/ui/src/lib/theme/colors.ts
- packages/ui/src/lib/theme/theme.test.ts
- packages/ui/src/lib/theme/theme.ts
- packages/ui/src/lib/theme/typography.ts
- yarn.lock
Remove brand from ui + onboarding workspaces.
Refactor font preloading.
Replace use of colorsV3 with getColor utility from ui package.
Add UIColor type.
Refactor @font-face and move to global styles definition.
Refactor getColor utility to not lose type safety.
Move font definitions from brand repo to ui package.
The brand repo is deprecated so we should move stuff to the UI package instead.
I wasn't super careful with the market-web stuff but that should be removed in the future so I think that okey (sorry @gustaveen 🙏)
> Remove brand repo dependency 💅

- packages/ui/src/lib/media-query.test.ts
Remove console.error noise from test where it's expected
Make output cleaner, do not confuse developers with expected error that does not fail test
> Suppress expected console error in media-query test

- apps/store/src/pages/[...slug].tsx
- apps/store/src/pages/index.tsx
Remove revalidation based on time in favor of on-demand ISR.
For pages that entirely driven by CMS we know exactly when to rebuild them - when the CMS content changes.
This is communicated via a webhook to the store app - so no need for these revalidation settings!
https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation
> Turn off timed revalidation for store app

- apps/store/src/blocks/TabsBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
Add Tabs + Tab blocks to CMS setup
Add types module for shared types between blocks.
Used on the product page.
I considered adding it to the product page content type but seems a bit too early - this is more flexible.
[GRW-1320]: https://hedvig.atlassian.net/browse/GRW-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Tabs + Tab blocks to CMS setup

- apps/store/src/blocks/AccordionItemBlock.tsx
- apps/store/src/blocks/ContentBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
Also add Storyblok editor props to AccordionItemBlock.
The rich text field seems to require all embedded components to be rendered as strings (https://www.storyblok.com/docs/richtext-field#javascript-sdk). At least when using the JavaScript SDK. I, therefore, limited the inputs to only text + images. The editors would have to add headings using the `HeadingBlock` etc.
> GRW-1350 / Feature / Add ContentBlock for text

- apps/store/src/services/shopSession/ShopSessionContext.tsx
We may get old session that does not match current country.  In this case new session is created and while we wait, old session data should not be displayed in UI
[GRW-1335]: https://hedvig.atlassian.net/browse/GRW-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ignore shop session when countryCode does not match current locale

- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/Page/Page.tsx
- apps/store/src/services/storyblok/storyblok.ts
Rendering the menu in the `LayoutWithMenu` component. Took me a while to figure out that the `pageProps` were actually accessible in the `Layout` component 😄
```ts
// _app.tsx
{getLayout(<Component {...pageProps} />)}
```
Only need to add the menu in one place. 
Also didn't know about the benefit of Next layouts before reading up on it: https://nextjs.org/docs/basic-features/layouts 🎉
> This layout pattern enables state persistence because the React component tree is maintained between page transitions
https://user-images.githubusercontent.com/6661511/186625495-1553b45c-964c-4b1d-9620-834e20641071.mov
> GRW-1415 / Render HeaderBlock in LayoutWithMenu component

- apps/store/next.config.js
- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
- apps/store/src/components/Page/Page.tsx
- apps/store/src/components/ProductPage/ProductPage.types.ts
- apps/store/src/pages/[...slug].tsx
- apps/store/src/pages/cart/index.tsx
- apps/store/src/pages/confirmation.tsx
- apps/store/src/pages/index.tsx
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/storyblok/storyblok.ts
Fetch global story on all pages that use LayoutWithMenu.
Skip passing key + preview as page props.
Update types for StoryblokPageProps and helper functions.
Avoid swallowing exception when fetching global story.
We get error when rendering the pages that use layout with menu component without loading global story.
See comments below.
> Fix error when rendering pages that require global story

- apps/store/src/components/Timeline/Timeline.tsx
Added right padding to the timeline block to match the other blocks.
Currently the block has no right padding and goes all the way to the right edge. This looks a bit odd since none of the other content works like this.
> Fix Timeline block padding

- apps/store/src/blocks/TopMenuBlock.tsx
- apps/store/src/components/TopMenu/TopMenu.tsx
Made the top menu stick to the top of the page and float over the content under it.
See video below for more context.
https://user-images.githubusercontent.com/50870173/186854034-f6cb40e6-d109-494a-b294-00f7c133cbd2.mov
Previously the top menu was only shown at the top of the page. When the user scrolled away from the top they were no longer able to see the top menu. 
[GRW-1402]: https://hedvig.atlassian.net/browse/GRW-1402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1402 TopMenu floating over content

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/PriceCalculatorForm/PriceCalculatorForm.helpers.ts
- apps/store/src/components/PriceCalculatorForm/PriceCalculatorForm.stories.tsx
- apps/store/src/components/PriceCalculatorForm/PriceCalculatorForm.tsx
- apps/store/src/components/PriceCalculatorForm/useHandleSubmitPriceCalculator.ts
- apps/store/src/lib/PageLink.ts
- apps/store/src/pages/api/price/[productId]/[formTemplateId].ts
- apps/store/src/services/formTemplate/FormTemplate.types.ts
- apps/store/src/services/formTemplate/FormTemplateService.ts
- apps/store/src/services/formTemplate/combineFormTemplate.ts
Refactor price calculator API route
Decide whether to confirm a price intent in the API route.
Pass form template ID to the API route.
Make ID part of FormTemplate interface.
Remove intent form input.
It doesn't make much sense to leave up to the client to decide wether to generate a price or not since we can derive it based on the state.
> Refactor price calculator API route

- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/TopMenu/TopMenu.tsx
See title.
z-index is really hard to work with in a design system -- seems more scalable to rely on HTML order if possible :)
> Use HTML order instead of z-index

- apps/store/src/components/InsurableLimits/InsurableLimits.stories.tsx
- apps/store/src/components/InsurableLimits/InsurableLimits.tsx
- apps/store/src/components/Statistic/Statistic.stories.tsx
- apps/store/src/components/Statistic/Statistic.tsx
* Add a `<Statistics>` component that can display `value` and `label`
* Add a `<InsurableLimits>` component that takes in an array of objects with `value` and `label` and displays a grid of `<Statistics>` components
Ticket https://hedvig.atlassian.net/browse/GRW-1361
https://user-images.githubusercontent.com/1343979/187166483-0f19802b-a441-4a9a-a15b-54bb6cc28a95.mov
(the reason it looks like it's a bit glitchy when resizing the window is because I added a _very_ long value for the travel insurance to see how it behaves. In edge cases it will be like this:
Obviously the user wouldn't see that as they probably do not resize the window.
> Add Statistics and InsurableLimits components

- apps/onboarding/package.json
- apps/store/package.json
- apps/store/src/blocks/FooterBlock.tsx
- package.json
- packages/scripts/package.json
- packages/ui/package.json
- packages/ui/src/components/Menu/SubMenu.tsx
- yarn.lock
Upgrade all packages within Racoon to [React 18](https://reactjs.org/blog/2022/03/29/react-v18.html)
In general some possible concerns are around our major dependencies i.e. [Next](https://nextjs.org/docs/advanced-features/react-18/overview), Apollo Client, Emotion, Storybook
To read more about our motivations, check out the Notion document [here](https://www.notion.so/hedviginsurance/Use-React-18-for-Coverage-Store-a182a7a30cae433dbc075228bf577dda).
- Upgraded the following packages to work with React 18
- `react`
- `react-dom`
- `@react/types`
- `@react-dom/types`
Proactively keeping this repository up to date.
[GRW-1412]: https://hedvig.atlassian.net/browse/GRW-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1412 POC Upgrade to React 18  ⚛️

- apps/store/src/blocks/InsurableLimitsBlock.tsx
- apps/store/src/components/InsurableLimits/InsurableLimits.stories.tsx
- apps/store/src/components/InsurableLimits/InsurableLimits.tsx
- apps/store/src/services/storyblok/storyblok.ts
* Adds `InsurableLimitsBlock` and `InsurableLimitBlock` components
* Refactored `InsurableLimits` component since `InsurableLimitsBlock` loops out `InsurableLimitBlock`
**Question:** 
Should we for clarity's sake keep `InsurableLimits` component? It's pretty meaningless in itself and its styling could just as easily be in the `InsurableLimitsBlock` component. But if we want to use `InsurableLimits` outside of Storyblok's context it could still be useful... What's our stance on this?
[GRW-1366]: https://hedvig.atlassian.net/browse/GRW-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add InsurableLimit(s) bloks

- apps/onboarding/.eslintrc.js
- apps/store/.eslintrc.js
- packages/scripts/.eslintrc.js
- packages/scripts/eslint-preset-next.js
- packages/scripts/package.json
- packages/ui/src/components/Card/Card.tsx
Split up ESLint configs in UI package so that it's easy to see what is Next.js-specific.
As suggested by @alebedev here it is easier to see what has been added for Next.js than to somehow understand that we filter away rules and config in the UI package: https://github.com/HedvigInsurance/racoon/pull/457/files/4afe2632057ef76fd037722fe7e35c81f8c3147b#diff-ad31f895bb498d335c09f2aa7eb18d512c87e8df3bffe91929d0e1506b17ca74
[GRW-1439]: https://hedvig.atlassian.net/browse/GRW-1439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Split up ESLint configs to isolate Next.js rules

- apps/store/src/pages/_app.tsx
- apps/store/src/services/shopSession/ShopSessionContext.tsx
Fix shop session fetching server-side
Pass shopSessionId to provider if we fetch it server side.
Enable ssr for shop session query.
We get hydration error on pages that server render the header.
Not sure why Apollo require us to set `ssr`-option on the query level AND on the client.
Need to pass shop session ID to the provider since we can't read cookies inside React on the server.
> Fix shop session fetching server-side

- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
Co-authored-by: karnell schultz <karnellschultz@gmail.com>
Add a Page config group to Page content type with a `hideMenu` checkbox.
https://user-images.githubusercontent.com/6661511/187471774-44ec1343-7a08-4aba-9114-d8e2eed199df.mov
Add possibility to hide menu/header on some pages.
However, haven't seen in design what pages this option is relevant for. So we might need to tweak the functionality. Do we want to hide the whole header (with Hedvig logo and cart icon) or just the menu in the header?
> GRW-1401 / Add hideMenu option to Page in storyblok

- apps/onboarding/src/pages/_document.tsx
- apps/onboarding/src/pages/index.tsx
- packages/scripts/.eslintrc.js
- packages/scripts/package.json
- packages/ui/.eslintrc.js
- yarn.lock
* Add `jsx-a11y` plugin as was discussed on the tech forum last week
* Fix problems
* Filter out NextJS ESLint options from UI package ESLint config file, to omit this warning:
It seems that even though I remove `packages/**` from `rootDir` option the `'next/core-web-vitals'` rules will try to lint the UI package 🤷 
https://nextjs.org/docs/basic-features/eslint#rootdir
I think it's justified to remove NextJS rules from the UI package since it doesn't have a dependency on NextJS. Perhaps there's a prettier way to achieve it?
> Add jsx-a11y ESLint plugin

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
In Storyblock I've added the `hideFooter` option to the global config and added content to the global footer. 
In code. Changed the name of the footer link field to `linkText`. Added the footerBlock to the global components and remove the static footer from the Next Layout component.
[GRW-1443]: https://hedvig.atlassian.net/browse/GRW-1443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1443 / Feature / 🌐 Add Footer to Global content 🌐

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/SiteFooter/SiteFooter.tsx
- apps/store/src/components/TopMenu/TopMenu.tsx
- Render proper tags for `header` and `footer`
- Put header at start of document
- Remove nested `main` tags
The structure we should aim to follow:
```
<body>
<header>
<nav>…</nav>
</header>
<main>
</main>
<footer>
</footer>
</body>
```
It was a SEO concern from Peter if we would render the header and menu on the bottom of the page. Sorry for adding back `z-index` @robinandeer I feel your pain :D but I think it's nice to keep the low level logical order of the document as well. We have some options to colocate z-index throughout the app, I can make a proposal for it :) 
[GRW-1454]: https://hedvig.atlassian.net/browse/GRW-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix semantic html structure

- apps/store/src/blocks/TopMenuBlock.tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
Refactor TopMenuBlock to fix render issues
Conditionally render NestedNavContainer vs. NavItem blocks.
Remove React state in favor of CSS styles.
Close top menu after route change is complete.
Fix linking with Storyblok LinkField.
I noticed that the TopMenu didn't behave as expected.
When we can avoid React state in favor of built-in solution I like to remove state.
> Refactor TopMenuBlock to fix render issues

- apps/store/src/services/Track/Track.ts
- apps/store/src/services/shopSession/ShopSessionContext.tsx
Centralize Track stuff in a single service.
Then we can add context data to both Datadog/GTM for example.
> Add central Track service (Datadog/GTM)

- apps/onboarding/package.json
- apps/store/package.json
- yarn.lock
Downgrade types/node to 16
We're using node v16. In order to make sure we're not using features we do not have available in future versions of node we're downgrading to the version of types we're on.
> downgrade types/node to V.16 🔙

- apps/store/src/pages/api/preview.ts
- apps/store/src/services/storyblok/storyblok.ts
Map Storyblok default locale to country-specific default locale
Assume Storyblok uses 2-char language codes for other languages
Implement default language logic for localization experiment
[GRW-1471]: https://hedvig.atlassian.net/browse/GRW-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1471 / Feature / Map country default locale to Storyblok default language

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/PriceCalculatorForm/useHandleSubmitPriceCalculator.ts
- apps/store/src/components/ProductPage/useHandleClickAddToCart.ts
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/shopSession/ShopSessionContext.tsx
- apps/store/src/utils/useRefreshData.ts
- apps/store/src/utils/useRouterRefresh.ts
Fix bug on Product Page when revalidating data after a mutation.
Only handle data fetching server-side for Product Page.
Pass ShopSession ID to page to subscribe to query (header).
This should make the page interactions work for now.
In the future we should either commit to making this page SSR or move user-dependent data to client side data fetching.
But in the mean time it's better to handle all data fetching in one place.
> Fix product page revalidate bug

- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/blocks/TopMenuBlock.tsx
- apps/store/src/lib/l10n/locales.ts
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
- apps/store/src/utils/useStroryblokLinkURL.ts
Fix link generation logic
- Use resolve_links=url to ensure we get fresh links from storyblok, cached_url is unsafe
- Handle $lang slug prefix for non-default languages
Ensure we always get correct URLs in menu
[GRW-1471]: https://hedvig.atlassian.net/browse/GRW-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1471 / Fix / Locale-specific URLs

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/CheckoutContactDetailsPage/CheckoutContactDetails.tsx
- apps/store/src/components/CheckoutContactDetailsPage/CheckoutContactDetailsPage.constants.ts
- apps/store/src/components/CheckoutContactDetailsPage/useHandleSubmitContactDetails.ts
- apps/store/src/components/ProductPage/ProductPage.constants.ts
- apps/store/src/components/ProductPage/useHandleClickAddToCart.ts
Introduce enums for form element names.
We use strings to reference form elements both in JSX and in event handlers.
There's a risk that they get out of sync which will cause bugs in the code. Therefore, it's a better idea to use an enum to reference the form element names in both contexts. One source of truth.
> refactor: use enums instead of strings for referencing form elements

- renovate.json
- Automerge `patch`, `pin`, `digest` for `dependencies`
- Automerge `minor`, `patch`, `pin`, `digest` for `devDependencies`
[Renovate docs](https://docs.renovatebot.com/configuration-options/#automerge)
Created a new 'dependencies' label in Github
Decided to get a little more aggressive with devDeps since there is a lower chance of causing issues with those being updated automatically.
[Renovate Notion doc](https://www.notion.so/hedviginsurance/Renovate-in-Racoon-89e0dee39ae74793b9f1ad93216d1a92)
At the moment the limit for how many PRs Renovate is allowed to have open at once is two.
Even with Renovate being run every Monday morning, this is not going to cause a bunch of PRs to be crated on Monday if there are more than two PRs currently open.
> Update Renovate config ⚙️

- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/storyblok/storyblok.ts
Move page type filtering to service layer.  We may need to reuse it for promise catalog in the future
Separate Storyblok mapping from nextjs
> GRW-1492 / Fix / Refactor page link collection

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/ProductPage/useHandleClickAddToCart.ts
- apps/store/src/services/formTemplate/FormTemplateService.ts
- apps/store/src/services/formTemplate/data/NO_TRAVEL.json
- apps/store/src/services/formTemplate/data/NO_TRAVEL_UI.ts
- apps/store/src/services/formTemplate/data/SE_ACCIDENT.json
- apps/store/src/services/formTemplate/data/SE_ACCIDENT_UI.ts
- apps/store/src/services/persister/CookiePersister.ts
- apps/store/src/services/persister/Persister.types.ts
- apps/store/src/services/persister/ServerCookiePersister.ts
- apps/store/src/services/priceIntent/PriceIntent.helpers.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
- apps/store/src/services/priceIntent/priceIntent.types.ts
Support calculating price for multiple products
Allow passing in custom cookie key to SimplePersister.
Construct price intent cookie key based on ShopSession ID + product name.
We want users to be able to move between product pages.
This setup enables us to keep track of multiple price intents (one for each product).
> Support calculating price for multiple products

- apps/store/src/components/ContactSupport/ContactSupport.tsx
- apps/store/src/components/SpaceFlex/SpaceFlex.tsx
- Added a `wrap` prop to the `<SpaceFlex />` component to control the `flex-wrap` of the components children.
On smaller displays the buttons were overflowing outside of the viewport which caused an unwanted horizontal scroll
[GRW-1513]: https://hedvig.atlassian.net/browse/GRW-1513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1513 / fix / contact support block horizontal scroll

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/AppStoreBadge/AppStoreBadge.tsx
- apps/store/src/components/CountrySelectorPage/CountrySelectorPage.tsx
- apps/store/src/lib/PageLink.ts
- apps/store/src/lib/l10n/countries.ts
- apps/store/src/lib/l10n/locales.ts
- apps/store/src/lib/l10n/types.ts
- apps/store/src/middleware.ts
- apps/store/src/services/adyen/Adyen.helpers.ts
- apps/store/src/utils/isLocale.ts
- Add logging on the root middleware (this is for our testing now, _could_ be removed later)
- Changed the routing to use lowercase routing for pretty urls 🍒
- the url preview url is going from `.../sv-SE/` to `.../sv-se/`
- <img width="189" alt="Screenshot 2022-09-22 at 10 03 04" src="https://user-images.githubusercontent.com/50870173/191693115-1b7e6429-918e-4ac9-84df-a4f7a6ef0fca.png">
- Tighten up the types being used by for localisation
- <img width="601" alt="Screenshot 2022-09-22 at 10 02 26" src="https://user-images.githubusercontent.com/50870173/191692507-7e52f2fd-3721-4d96-ac7b-cd54b452c0de.png">
- Creates nicer urls which are lowercase which is inline with how we'd like to show our urls. 
- The types changes prevent users of some of the localisation functions so that users do …
> GRW-1510 / improvements to middleware routing

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/blocks/TopMenuBlock.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/services/storyblok/storyblok.ts
Refactor Global story schema: 
```js
content:  {
header: ExpectedBlockType<HeaderBlockProps>
footer: ExpectedBlockType<FooterBlockProps>
}
```
The header and footer field only allows on block of the corresponding type.
Also create a folder, `Global`, to collect all global stories.
I have not updated the prod space yet, so let me know if you want to view it in my space.
Follow the same pattern as other blocks. Makes it easier to add other settings to the header or footer block, and if we would need to have alternative headers for partnership pages.
https://user-images.githubusercontent.com/6661511/191773034-596c0f01-edf7-4cab-898d-82ee5e470b1f.mov
> GRW-1514 / Refactor global story

- apps/store/package.json
- apps/store/src/components/PriceForm/AutomaticField.tsx
- apps/store/src/components/PriceForm/ExtraBuildingsField.tsx
- apps/store/src/components/PriceForm/InputSwitch.tsx
- apps/store/src/services/PriceForm/data/SE_HOUSE.ts
- yarn.lock
- Implement extra buildings field component
- Add basic Switch component (checkbox).
- Update onSubmit prop to accept async callback function.
- Update label for extra building input.
[Screen Recording 2022-09-27 at 09.56.03.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/4886c887-b69f-4b49-a4ca-70ca2f9e87bd/Screen%20Recording%202022-09-27%20at%2009.56.03.mov)
There's no design for how to display added extra buildings so I just came up with something minimal.
The Switch is not complete/animated but I don't consider that the most critical to work on now.
> Implement extra buildings field component

- apps/store/.env.local.example
- apps/store/src/services/logger/config.ts
- apps/store/src/services/logger/server.ts
Found a way to attach hostname finally! 💡 
When deployed we will use the URL of the preview/actual deployment. See explanation of `VERCEL_URL` here: https://vercel.com/docs/concepts/projects/environment-variables#system-environment-variables
We use `host` (a [Datadog Reserved attribute](https://docs.datadoghq.com/logs/log_configuration/attributes_naming_convention/#reserved-attributes)) and attach it to the [`base` object](https://getpino.io/#/docs/api?id=base-object) which gets sent on every request.
```json
{
"id": "AQAAAYN-y3BtzEJY3wAAAABBWU4teTR4aUFBQUNjaFhSR0Q0c3lRQUE",
"content": {
"timestamp": "2022-09-27T11:53:25.357Z",
"tags": [
"env:dev",
"source:nodejs"
],
"host": "169.254.239.53",
"service": "racoon-store",
"message": "Request failed with status code 404",
"attributes": { …
```
> GRW-1556 / chore / Log hostname to Datadog

- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/PriceForm/PriceForm.helpers.ts
- apps/store/src/services/PriceForm/PriceForm.types.ts
- apps/store/src/services/PriceForm/data/SE_STUDENT_APARTMENT.ts
- apps/store/src/services/priceIntent/PriceIntent.helpers.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
- apps/store/src/services/priceIntent/priceIntent.types.ts
Add form template for SE student home
Add support for initial price form data.
Make API call to update price intent with initial data after creating.
Refactor price intent service a bit.
I considered adding "hidden" input fields but I think this appraoch feel less hacky.
In the future we could update the API to accept "initialData" when creating a new price intent.
[GRW-1555]: https://hedvig.atlassian.net/browse/GRW-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add form template for SE student home

- apps/store/src/pages/[[...slug]].tsx
Always revalidate CMS pages for preview deployments.
Keep using [on-demand revalidation](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation) for production deployments.
It's only possible to setup one webhook in Storyblok that triggers when changes are published. This triggers on-demand revalidation for the production site.
However, all the preview deployments don't get this benefit. Therefore, I think it's best to always revalidate those pages. This means that as soon as you visit a page, Vercel will revalidate it for the next visitor.
This mimics how the production site works while allowing us to see CMS changes ASAP.
> Always revalidate CMS pages in preview deployments

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/PriceForm/PriceForm.types.ts
- apps/store/src/services/PriceForm/data/SE_ACCIDENT.ts
- apps/store/src/services/PriceForm/data/SE_APARTMENT.ts
- apps/store/src/services/PriceForm/data/SE_HOUSE.ts
- apps/store/src/services/PriceForm/data/SE_STUDENT_APARTMENT.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
- apps/store/src/services/priceIntent/priceIntent.types.ts
Use template instead of product name for price intent key
Pass the whole price template when fetching/creating price intent.
Add unique name property to Template.
This is needed to support using the same product on multiple product pages.
We don't want to mix up the price intents in these cases tho so we need a different identifier than shop session + product name.
Since the template will be different for different product pages I decided to use that combo instead.
> Use template instead of product name for price intent key

- apps/store/src/blocks/PerilsBlock.tsx
- apps/store/src/components/Perils/CoverageList.tsx
- apps/store/src/components/Perils/MinusIcon.tsx
- apps/store/src/components/Perils/PlusIcon.tsx
- apps/store/src/components/PriceForm/InputRadio.tsx
- apps/store/src/components/PriceForm/PriceForm.constants.ts
- apps/store/src/components/PriceForm/StepIconValid.tsx
- apps/store/src/components/PriceForm/TickIcon.tsx
- apps/store/src/components/TickIcon/TickIcon.tsx
- apps/store/src/components/TopMenu/MenuIcon.tsx
- apps/store/src/components/TopMenu/ShoppingBagIcon.tsx
Took some inspiration from @guilhermespopolin and ran racoon-store with very large font size, mainly to see where we do not scale elements accordingly. I didn't care about paddings and margins but focused on fixing icons.
https://user-images.githubusercontent.com/1343979/192819134-c17381aa-ce6d-4d6e-a116-9f4f3ccb5dcf.mov
https://user-images.githubusercontent.com/1343979/192819905-48cdf07b-30e6-4cd4-a3e4-427e0f9a8170.mov
The user interaction looks really strange when zoomed in.
> Fix icon sizes on the Product page when zoomed

- apps/store/.eslintrc.js
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceForm/AutomaticField.tsx
- apps/store/src/components/PriceForm/FormGrid.tsx
- apps/store/src/components/PriceForm/InputRadio.tsx
- apps/store/src/components/PriceForm/PriceForm.tsx
- apps/store/src/components/PriceForm/PriceFormAccordion.tsx
Consider this a proposal to solve an a11y issues by using a non-recommended (in terms of a11y) solution
Set `auto-focus` on a PriceForm input when
1. It's any section after the first
2. It's the first input in the section
Otherwise, the user has to tab through the entire page every time they submit the form.
The use of `auto-focus` is [discouraged](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-autofocus.md) since it can cause usability and a11y issues, but as it solves the current issue, which is also a11y, I think it's worth the trade-off.
The user interaction would be (for https://racoon-store.vercel.app/sv-se/products/home):
1. Tab to the form
2. Fill in SSN
3. Enter to submit section
4. Tab to next input (Ownership type)
5. Fill in section
6. Enter to …
> Auto-focus first input when accordion is expanded

- apps/store/package.json
- apps/store/src/components/PriceForm/AutomaticField.tsx
- apps/store/src/components/PriceForm/SsnSeField.tsx
- apps/store/src/services/PriceForm/Field.types.ts
- apps/store/src/services/PriceForm/data/SE_ACCIDENT.ts
- apps/store/src/services/PriceForm/data/SE_APARTMENT.ts
- apps/store/src/services/PriceForm/data/SE_HOUSE.ts
- apps/store/src/services/PriceForm/data/SE_STUDENT_APARTMENT.ts
- yarn.lock
Introduce custom field that formats Swedish SSN to a format that is acceptable by BE. The `personnummer` lib handles validation and formatting in an easy way.
We should allow the user to type in SSN in all different variations and always send it in the correct format to BE. The format that they accept is "long" according to [personnummer docs](https://personnummer.dev/) -> `yyyymmddNNNN`.
Maybe @robinandeer knows some good way to get rid of the `useState`? 🙃 
https://user-images.githubusercontent.com/1343979/192812438-fff5d157-ba17-4063-bb64-f76ef7188509.mov
> feat / Introduce custom field for Swedish SSN

- apps/store/src/components/CheckoutPage/useHandleSubmitStartDates.ts
Avoid calling `onSuccess` if API responds with user errors.
Update to use Datadog logger.
> Checkout start dates: Only call success callback if there are no user errors

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/CountrySelectorPage/CountrySelectorPage.tsx
- apps/store/src/lib/l10n/locales.ts
- apps/store/src/middleware.ts
- apps/store/src/services/persister/CookiePersister.ts
- apps/store/src/services/persister/Persister.types.ts
- apps/store/src/services/persister/ServerCookiePersister.ts
- apps/store/src/services/priceIntent/PriceIntent.helpers.ts
Use it in middleware to redirect to instead of country picker
Store users' preference of language in cookie.
If the user has picked a language preference they shouldn't need to see the Country selector again. And if they picked English in Sweden the country selector page would still route to `/se`, not `/en-se`.
Don't mind the error messages. They appear when clearing cookies.
https://user-images.githubusercontent.com/1343979/193598594-23414fa9-605a-4cbb-9c30-b665758c28af.mov
> Store users language preference in cookie

- apps/store/src/components/CheckoutContactDetailsPage/CheckoutContactDetails.tsx
- apps/store/src/components/CheckoutContactDetailsPage/CheckoutContactDetails.types.tsx
- apps/store/src/components/CheckoutContactDetailsPage/CheckoutContactDetailsPage.helpers.ts
- apps/store/src/components/CheckoutContactDetailsPage/CheckoutSignPage.tsx
- apps/store/src/components/CheckoutContactDetailsPage/useHandleSubmitContactDetailsAndSign.ts
- apps/store/src/graphql/CheckoutSigning.graphql
- apps/store/src/graphql/CheckoutSigningFragment.graphql
- apps/store/src/graphql/CheckoutStartSign.graphql
- apps/store/src/graphql/ShopSession.graphql
- apps/store/src/graphql/ShopSessionCreate.graphql
- apps/store/src/graphql/ShopSessionFragment.graphql
- apps/store/src/pages/checkout/contact-details.tsx
Integrate Checkout signing API on checkout / contact details page.
Move form logic inside checkout details pages.
Keep track of started "checkout signing" in cookie (key = checkoutId).
Flow: update contact details -> start sign -> poll for updates to checkout signing.
Still to be done:
- store the access token in a cookie after it's generated
- update cookie settings to be secure
Needed to support the "after sign" payment flow.
We stored the checkout signing ID in a cookie in case the user reloads the page while a signing is ongoing.
[GRW-1562]: https://hedvig.atlassian.net/browse/GRW-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Integrate checkout signing API

- apps/store/package.json
- apps/store/src/components/CheckoutContactDetailsPage/CheckoutSignPage.tsx
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/contact-details.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/pages/confirmation.tsx
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/apollo/client.ts
- yarn.lock
Store access token in encrypted cookie after successful signing.
Add `cookies-next` as dependency to store app. We already used it.
Pass req + res when initializing apollo to get access token from cookies server side.
Use "auth link" from official example to pick up access token from cookies client side.
We need the authorization header to make authenticated calls to the API.
We want to access the token both client and server-side so best way to store it is in a cookie.
We should probably replace the `js-cookie` dependency and just use `cookies-next`.
[GRW-1564]: https://hedvig.atlassian.net/browse/GRW-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Store access token in cookie

- turbo.json
See title.
Turborepo can't know if the API schema has changed before downloading it. If we cache the output we can end up in strange situations.
Therefore let's turn it off until we figure out a robust way to handle cache of this task.
> Disable Turborepo cache for codegen task

- packages/scripts/.eslintrc.js
- packages/scripts/eslint-preset-next.js
- packages/ui/.eslintrc.js
- packages/ui/jest.transform.js
Overwrite eslint config to recognise JS files as Node environment
Stop complaining about require() calls there
> Fix / Allow require() calls when linting NodeJs files

- apps/store/src/components/ProductCard/ProductCard.tsx
- apps/store/src/components/ProductGrid/ProductGrid.tsx
- Set ProductGrid to 4 columns in desktop
- Set image aspect ratio rather than using hardcoded units
- Add fallback for aspect ratio to support Safari 14
The design should scale to desktop. Start with a set 4 column layout and adjust accordingly when we have determined variants of the ProductGrid and sharp desktop design.
https://user-images.githubusercontent.com/6661511/193932218-1aff3265-723b-4e4b-8a9a-b50ca245a3b4.mov
> Set grid layout for desktop and aspect ratio for image

- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/contact-details.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/apollo/client.ts
Updated `initializeApollo` function signature to accept a configuration object instead of a list of arguments
It simplifies its usage
> GRW-1587 - refact(initializeApollo): updated functions signature to accept a configuration object

- apps/store/.env.local.example
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/services/WebOnboarding/WebOnboarding.helpers.test.ts
- apps/store/src/services/WebOnboarding/WebOnboarding.helpers.ts
Redirect users to web-onboarding to connect payment (AFTER_SIGN).
Add new env var `WEB_ONBOARDING_PAYMENT_URL_AFTER_SIGN`.
Add `WebOnboarding` helpers to hide implementation details from the rest of the app.
> This only solve the AFTER_SIGN payment flow. And assumes we are only using that for SWEDEN. Web Onboarding also needs to support sending the access token in this way. A better solution would be to get an "exchange token" from the API and use that, the same way we do for the HOPE payment link feature.
To be able to reuse Giraffe payment APIs for Hedvig.com.
> Redirect to web onboarding to connect payment after sign

- apps/store/src/blocks/ReusableBlockReference.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/reusable-blocks/[...slug].tsx
- apps/store/src/services/storyblok/storyblok.ts
Add a new route and page template for `/reusable-blocks`
Render Reusable block stories in Storyblok
I get a type error I can't figure out though... 
```js
store:build: Type error: 
Type '(context: GetServerSidePropsContext<StoryblokQueryParams, StoryblokPreviewData>) => 
Promise<{ notFound: true; props?: undefined; } | { ...; }>' is not assignable to type
'GetServerSideProps<ReusableBlockPageProps, StoryblokQueryParams, StoryblokPreviewData>'.
```
> GRW-1604 / feat/  Add page for rendering reusable-blocks stories

- apps/store/package.json
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/services/Auth/Auth.ts
- apps/store/src/services/LocalContext/LocalContext.helpers.ts
- apps/store/src/services/WebOnboarding/WebOnboarding.helpers.ts
- apps/store/src/services/apollo/client.ts
- yarn.lock
Implement the device ID setup that we have on Web Onboarding.
Bascially we create a unique UUID that we store in the browser.
Then we send this as a header with all requests to the backend.
I decided to link this to the Apollo Client setup to ensure that the UUID is created before we send any API requests.
I talked with Aleks about collecting things like this in a `LocalContext` -- let's iterate on exactly how it should work!
The purpose with the header is to link a `ShopSession` with a `PaymentConnection` on the backend.
[GRW-1609]: https://hedvig.atlassian.net/browse/GRW-1609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement device id header

- apps/store/src/blocks/HeroBlock.tsx
- Use Next `Image` instead of background-image in Hero block
- Prioritize loading of Hero block image
Get all benefits with Next image and preload above the fold image
> Switch from bgImage to Next Image in Hero block

- apps/store/src/lib/PageLink.ts
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/pages/checkout/payment/[status].tsx
- apps/store/src/services/WebOnboarding/WebOnboarding.helpers.ts
Add callback URL as query parameter `redirect_url` that is passed to Web Onboarding to connect payments.
We need a way for Web Onboarding to communicate back to Racoon Store after the payment connection flow is complete.
We don't have designs for the fail case where the payment was not connected - will ask for designs for this :)
> Add callback to web-onboarding payment URL

- apps/onboarding/src/components/LandingPage/LandingPage.tsx
Removes intro section from _Landing Page_
We’ve noticed a constant drop on conversion rate since Pentagon related changes added in June. As response it was decided to change the UI a little bit by removing the intro section (for both NO and DK) and keep analysing it so we can better understand if the drop is related with UI/UX.
> GRW-1664 - fix(LandingPage): removed intro section

- apps/onboarding/src/components/Nav/Header.tsx
Fix _Hedvig Logo Link_ so it redirects to the correct place
Currently by clicking on, _Landing Page_'s Hedvig Logo would always redirect to hedvig.com/se which is not correct for other markets like NO and DK.
> GRW-1331 - fix(hedvig-logo-link): consider locale path

- apps/store/src/pages/_app.tsx
Make sure we don't try to initialize Datadog RUM/browser logs when doing SSR.
It's only meant to run in the browser.
> Only initialize Datadog RUM/logs in the browser

- .github/workflows/diagram.yml
Fix `diagram.yml` action
I've noticed that action was [failing](https://github.com/HedvigInsurance/racoon/actions/runs/3329110641/jobs/5505917379). Based on the logs I:
*  Removed `branch` field since it's an unknown field for `EndBug/add-and-commit` 3rd party action. I thought that maybe that was a typo and we wanted to use `new_branch` field, but I realised that config is unnecessary since we're already checking out to the correct branch before executing that job;
* Removed [`pull`](https://github.com/EndBug/add-and-commit#:~:text=pull.%0A%20%20%20%20%23%20Default%3A%20%27%27-,pull,-%3A%20%27%2D%2Drebase) field since not including it means "no pull". Also I'm sure if NO-PULL as a valid value 🤔
I guess that was causing the issue btw
I've tested [running it against this …
> fix(diagram): Add & commit job

- apps/store/src/components/Pillow/Pillow.tsx
- apps/store/src/components/ProductPage/ProductSummary/ProductSummary.tsx
- apps/store/src/components/TopMenu/TopMenu.tsx
- Use x-large Pillow in Product Summary
To make a SVG clip path responsive, you need to reference a path that has the property `clipPathUnits="objectBoundingBox"` and transform the absolute path values to relative values. (Found this little tool to hel me out https://yoksel.github.io/relative-clip-path/)
This should be the "hero" of Product pages
> Product summary with large Pillow

- apps/store/src/components/PriceForm/PriceForm.tsx
- apps/store/src/services/gtm.tsx
Quick and dirty support for offer_created event tracking
- Send event via GTM
- Include very basic metadata
- Some TODOs for future improvement of tracking
Screenshot of event from GTM test page:
We want to track conversion somehow when A/B testing, this adds first conversion event
> GRW-1707 / Feature / Track offer_created event

- apps/store/src/blocks/HeroBlock.tsx
- apps/store/src/blocks/ImageBlock.tsx
- apps/store/src/components/AppStoreBadge/AppStoreBadge.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
- apps/store/src/components/TopPickCard/TopPickCard.tsx
Use the new Image component from Next
The new Image component relies on [native lazy loading](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading) and outputs much less html which makes it easier to style.
You can read more about the Image component here https://nextjs.org/docs/api-reference/next/image
What we need to consider if we have good enough browser support https://caniuse.com/loading-lazy-attr since it's not supported in Safari below 15.4 It does fallback to eager loading. 
Looking at the split between browser version on our site from 1/9 we have 1,4% sitting on version 14.1.2 and with other versions below 15.4 it's a total around 2,4%. Given that we will go live next year the number will decrease so I think we can go ahead and use it. For onboarding it might …
> GRW-1728 / Migrate to new image component

- apps/store/src/blocks/TopMenuBlock.tsx
- apps/store/src/components/ProductPage/Tabs.tsx
- apps/store/src/components/TopMenu/TopMenu.tsx
- apps/store/src/components/TopMenu/useTopMenuStickyOffset.tsx
- apps/store/src/utils/useIsIntersecting.tsx
- apps/store/src/utils/zIndex.tsx
(Third time is the charm)
Implemented a css sticky type interaction between the TopMenu and TabList components. 
In the logs here you can see that the `onScroll` is not running when the TabList is not intersecting on the page.
That said, it'd be even better if we could not run the onScroll after the TabList replaces the TopNav. It's possible, but may take some time to sort that out.
https://user-images.githubusercontent.com/50870173/200874127-7e045f63-574e-4f4a-8b08-8f22bb6962a5.mov
The 🧽 emoji means that the `onScroll` is not running. 
The 🎽 emoji shows when`onScroll` is running
Designs require the TabList be stuck to the top of the page once a user scrolls past it. 
[GRW-1702]: https://hedvig.atlassian.net/browse/GRW-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
> GRW-1702 / Feat  / Sticky TopMenu and Tablist

- apps/store/src/blocks/HeroBlock.tsx
- apps/store/src/blocks/HeroVideoBlock.tsx
- apps/store/src/blocks/ImageBlock.tsx
- apps/store/src/blocks/ProductCardBlock.tsx
- apps/store/src/blocks/TopPickCardBlock.tsx
- apps/store/src/blocks/VideoBlock.tsx
- apps/store/src/components/Video/Video.tsx
- apps/store/src/services/storyblok/storyblok.ts
First step for PDP product video
- Add a simple video block to start with
- Rename asset type to match Storyblok field name
Make it possible to add videos throughout the page. Will add more settings and functionality in upcoming PRs
https://user-images.githubusercontent.com/6661511/201108450-13d34b15-ba77-4ef4-912d-dc7eb47da592.mov
> GRW-1745 / feat / Add standalone video block

- apps/onboarding/package.json
- apps/onboarding/src/lib/fonts.ts
- apps/onboarding/src/pages/_app.tsx
- apps/onboarding/src/pages/_document.tsx
- apps/store/.storybook/preview.js
- packages/ui/.storybook/preview.js
- packages/ui/src/index.tsx
- packages/ui/src/lib/globalStyles.ts
- packages/ui/src/lib/storybookFontStyles.ts
- packages/ui/src/lib/theme/typography.stories.tsx
- packages/ui/src/lib/theme/typography.ts
- yarn.lock
Replace remaining usages of CDN fonts:
- with local fonts for storybook
- with @next/font for onboarding
Stop depending on CDN fonts, unify font loading
> GRW-1766 / Feature / Use @next/font in onboarding and storybook

- apps/store/src/components/PriceForm/CarRegistrationField.tsx
fixed mac length for the car register input field. 
**Before**
**After**
previously you could add as many chars as you'd like. 
[GRW-1759]: https://hedvig.atlassian.net/browse/GRW-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1759 / fix maxLength of car register

- apps/store/src/components/ProductPage/Tabs.tsx
Create separate stacking context for tabs so they don't show up above modals etc.
Let's try out to use this apporach rather than go crazy with z-index values :)
> Fix tabs stacking to show below navigation

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
- apps/store/src/components/PriceForm/SsnSeField.tsx
Create generic `PersonalNumberField` component.
Use new field in `SsnSeField`.
Integrate new field in `CheckoutPage`.
We want to do the same client-side validations whenever we deal with personal numbers.
According to our Hedvig dictionaly with refer to it as Personal Number rather than SSN.
> Add generic personal number field to Checkout

- apps/store/src/services/Auth/Auth.ts
Set the domain option for the auth session cookie.
We need to to be able to share the cookie between different subdomains.
It's not possible to test this locally which is unfortunate.
Perhaps we can consider a similar solution to how the "payment link" in HOPE works? There we inlude the "exchange token" in the URL which web onboarding uses to get an access token...
> Set domain option for auth session cookie

- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/payment.tsx
Reset cookie after successfully signing current `ShopSession`.
Remove code to fetch/validate `ShopSession` on checkout payment page.
A signed `ShopSession` has reached it's "end of life" so we should discard it as the "current `ShopSession`".
We will need to update the payment page code a bit when we implement "payment before sign" but for now this will do it for us.
> Discard ShopSession after successful sign

- apps/store/next.config.js
- apps/store/src/blocks/PerilsBlock.tsx
- apps/store/src/components/Perils/CoverageList.tsx
- apps/store/src/components/ProductPage/ProductPage.helpers.ts
- apps/store/src/components/ProductPage/ProductPage.types.ts
- apps/store/src/graphql/ProductData.graphql
- apps/store/src/pages/products/[product].tsx
- apps/store/src/utils/l10n/localeUtils.ts
Fetch perils from PCMS API.
Map between product page context and perils component in CMS block.
Fix icons in coverage lists.
Add utility to translate between "UI locale" and "API locale".
The CMS block seems the most reasonable place to access page context. Then we can reuse the perils component on other pages (but not the CMS block).
Let's unify how we deal with locales going forward.
I didn't include a selector for product variants since that isn't part of the perils block in the design but rather a different component on the product page.
[GRW-1781]: https://hedvig.atlassian.net/browse/GRW-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fetch perils from PCMS API

- apps/store/src/blocks/InsurableLimitsBlock.tsx
- apps/store/src/graphql/ProductData.graphql
Fetch insurable limits from the API (PCMS).
Show selected product variant or the first item.
We should figure out how this works to also select a product variant before you calculated prices.
[GRW-1783]: https://hedvig.atlassian.net/browse/GRW-1783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fetch insurable limits from PCMS API

- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPageAdyen.tsx
- apps/store/src/pages/api/payment/adyen-callback/[shopSessionId]/[locale].ts
- apps/store/src/pages/checkout/[shopSessionId]/payment/[status].tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/index.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/services/adyen/AdyenCheckout.tsx
- apps/store/src/utils/PageLink.ts
Explicitly define a ShopSession in Checkout for all steps after signing (payment + confirmation).
Use this ShopSession when creating the redirect URL back from Web Onboarding.
Update Adyen implementation just to keep it in line. We should revisit this later tho.
After signing, the life of the shop session is over. However, we don't have any other resource to handle data we need for later steps. Instead I define the ShopSession explicitly in the URL.
> Define explicit ShopSession for Checkout/Payment step

- apps/onboarding/src/pages/new-member/index.tsx
* Fix `getServerSideProps` for Swedish Landing page.
I've recently changed that code to support travel/accident standalone, with that a bug was inserted related with getting the correct props for Swedish Landing Page
> fix: Swedish landing page loading issue

- apps/store/src/components/ProductPage/PriceFormModal/PriceFormModal.tsx
- packages/ui/src/components/Dialog/Dialog.tsx
Add frosted overlay to PriceCalculator Dialog
I added a prop to `Dialog.Content`. We could export the `Overlay` component as well but that would make composition a bit more complex. But happy to hear your thoughts on that!
[Final design](https://www.figma.com/file/8SfzuQEJ4LJ6uKL0l7WKoE/Hedvig.com-%C2%B7-Final-Design?node-id=1048%3A3883&t=RcCopTqckRsg7kKk-1)
https://user-images.githubusercontent.com/6661511/203031394-fafd9033-03af-4caa-b806-275e2f365518.mov
> Add frosted overlay to Dialog

- .github/workflows/cypress.yml
Load `NEXT_PUBLIC_GRAPHQL_ENDPOINT` from Github secrets.
That action was [failing](https://github.com/HedvigInsurance/racoon/actions/runs/3522523785/jobs/5905600143) due the lack of `NEXT_PUBLIC_GRAPHQL_ENDPOINT` during `cypress` action execution.
Tested [here](https://github.com/HedvigInsurance/racoon/actions/runs/3522765456/jobs/5906123348)
> ci(cypress): load NEXT_PUBLIC_GRAPHQL_ENDPOINT secret

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceForm/CurrentInsuranceField/CurrentInsuranceField.stories.tsx
- apps/store/src/components/PriceForm/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/PriceForm/CurrentInsuranceField/CurrentInsuranceField.types.ts
- apps/store/src/components/PriceForm/CurrentInsuranceField/useCurrentInsuranceFieldProps.ts
- apps/store/src/components/PriceForm/InputRadio.tsx
Implement base version of `CurrentInsuranceField`.
Will allow a user to pick their current insurance company.
In the future it will also integrate with Insurely.
For Switching.
The API integration is just placeholder but wanted to add something that resembels what it will look like when the new endpoints are in place!
The look & feel is not according to design but I feel it is too early to implement the new versions of the inputs.
[GRW-1812]: https://hedvig.atlassian.net/browse/GRW-1812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement base CurrentInsuranceField

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.constants.ts
- apps/store/src/utils/date.ts
Create a presentational component for `CancellationForm`.
Support two cancellation options: `NONE` and `IEX`.
Add to Storybook.
NONE:
IEX:
I will open another PR to integrate with the API and in the `OfferSelector`.
[GRW-1818]: https://hedvig.atlassian.net/browse/GRW-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement presentational `CancellationForm` component

- apps/store/.env.local.example
- apps/store/src/pages/[[...slug]].tsx
Add option through env variables to skip static generation.
This should be enabled only for preview deployments.
This will get us faster builds for preview deployments!
The pages will instead be rendered on demand in preview env.
Got the idea from here: https://twitter.com/leeerob/status/1550617876188520452?s=61&t=GPLGqmqmeZRr5jaJeUEe1w
> Add option to skip prerendering in preview environments

- apps/store/src/components/ProductPage/ProductPage.constants.ts
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.constants.ts
- apps/store/src/components/ProductPage/PurchaseForm/TierSelector.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
Integrate `CancellationForm` in `OfferPresenter`.
Lock to "no cancellation" option.
Move form element constants and hook under `PurchaseForm`.
Just added it to the `OfferPresenter`. When the API is in place we can automatically chose which cancellation option to display to the user.
[GRW-1818]: https://hedvig.atlassian.net/browse/GRW-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Integrate `CancellationForm` in `OfferPresenter`

- apps/onboarding/src/services/apollo/index.ts
- apps/store/src/services/apollo/client.ts
Fix integration with ApolloDevTools Chrome extension
It used to work automatically by relying on __DEV__ global variable from React, now it doesn't.  Setting value explicitly is better than relying on React internals
Fix developer experience
> Fix / Connect ApolloDevTools

- apps/store/src/components/CartInventory/CartInventory.stories.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CartPage/useCampaign.ts
- apps/store/src/graphql/CartFragment.graphql
- apps/store/src/graphql/CartRedeemCampaign.graphql
- apps/store/src/graphql/CartUnredeemCampaign.graphql
- apps/store/src/pages/cart.tsx
Integrate API for campaign codes on Cart page.
- Redeem campaign
- Unredeem campaign
- List redeemed campaigns
I haven't paid much attention to the UI - this is only about API integration.
[GRW-1844]: https://hedvig.atlassian.net/browse/GRW-1844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Integrate API for campaign codes in Cart page

- apps/store/src/blocks/ProductPageBlock.tsx
Render different layout for mobile and desktop.
Since there's no straight forward way to "destroy" the tabs we will render different markup on different viewports.
Either we do it by js breakpoints or css breakpoints. Currently we get hydration warnings when doing it with js breakpoints. 
What do we prefer? I kind of favour hiding it with css if it doesn't come with drawbacks rendering more to the DOM
Next steps:
- Possibly break this out in to another component
- Get tab labels from CMS
- Add scroll to links for desktop, but as I understood design might be revised
https://user-images.githubusercontent.com/6661511/203760710-2c4756fb-00df-4e67-bfc7-3f3ad77d0ada.mov
https://user-images.githubusercontent.com/6661511/203760780-39f0eec1-ba13-4dce-a661-05f214782740.mov
Update layout for desktop
> Render different layout for mobile and desktop.

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- packages/ui/src/components/Dialog/Dialog.tsx
- Keep price calculator open until underlying page has loaded all the data
- Fix annoying React warning about frosted prop
Prevent UI flicker when product page becomes visible and then offer is displayed after some delay
> Fix / Don't close price calculator until offer is ready

- apps/store/README.md
- apps/store/src/pages/session/[shopSessionId].tsx
- apps/store/src/utils/PageLink.ts
Add route that can be used to share a shop session using a link.
```url
/se/session/2i1oj3oij12oij12iojwio2j?next=/se/cart
```
This can be very helpful to share shop session with other people to debug. For example in test sessions.
We should probably build a feature that automatically generates the link.
I considered adding this feature to the middleware but I think this will be much easier to maintain.
[GRW-1852]: https://hedvig.atlassian.net/browse/GRW-1852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement option to share a link to a specific shop session

- apps/store/src/blocks/VideoBlock.tsx
- apps/store/src/components/Video/Video.stories.tsx
- apps/store/src/components/Video/Video.tsx
- Add size settings for Video
Make it possible to set aspect ratio in Storyblok for videos.
Default is displaying the video without changing size from the uploaded format.
> Add size settings for Video

- apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/Text/Text.tsx
- apps/store/src/pages/products/[product].tsx
Fix layout issue in `OfferPresenter` when `CancellationForm` is visible.
Avoid controlling checkbox since it leads to strange UX. We should update optimistically and handle errors instead.
Subscribe to `PriceIntent` updates client side so UI is kept up to date.
I refactored a bit to subscribe to `PriceIntent` updates using Apollo Client. Not sure if this is the direction we want to move in generally. Happy to hear feedback on this!
> Fix layout in `OfferPresenter`

- apps/store/src/pages/[[...slug]].tsx
There's no `name` field inside `story.content`. Should we take it from `story.name`? 🤔 
Just faced this while working in another task.
> fix: get page title from correct story field

- .husky/pre-commit
Remove test command from Husky pre-commit hook.
As discussed, we should trust our CI to run this before merge instead.
It will also speed up making commits.
> Remove test command from pre-commit hook

- apps/store/src/components/ProductPage/ProductPage.tsx
- apps/store/src/components/ProductPage/usePriceIntent.ts
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/priceIntent/PriceIntent.helpers.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
- apps/store/src/services/storyblok/storyblok.ts
This is a big one -- make product page statically rendered.
Move management of `PriceIntent` and `ShopSession` client-side.
We want to be able to show the product page no matter the status of the API.
We want to be able to mix and match product pages anywhere in the URL structure.
> Update ProductPage to be statically rendered

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/PersonalNumberField/PersonalNumberField.stories.tsx
- apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/SsnSeField.tsx
- apps/store/src/components/TextField/TextField.stories.tsx
- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/utils/useHighlightAnimation.ts
Update `TextField` to behave like "floating label input" from Material design.
Make `label` prop required.
Update `useHighlightAnimation` to exclude certain key press events.
The input doesn't look/behave like the designs. However, I made some experiments and found that causing layout shifts isn't a very nice experience. It also causes problems when two inputs are placed next to one another and one grows but the other doesn't.
The problem with animating the label on "type" is that we need to animate the input field which also feels jarring -- so I avoided that.
> Update TextField to use floating label

- apps/onboarding/src/components/LandingPage/CoverageDialog.tsx
> fix: coverage dialog style

- apps/store/src/pages/checkout/index.tsx
- apps/store/src/services/apollo/client.ts
`CheckoutPage`: transform API data client side
Fix merge issue when removing campaign codes.
Since we rely on Apollo cache for updating UI data we need to transform it client-side rather than server-side. We could consider memoizing it.
Got a merge issue in the console and this is the recommended solution: https://medium.com/@dexiouz/fix-cache-data-may-be-lost-when-replacing-the-getallposts-field-of-a-query-object-in-apollo-client-7973a87a1b43
[GRW-1927]: https://hedvig.atlassian.net/browse/GRW-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move Checkout data transforms client-side

- apps/store/src/components/Pillow/Pillow.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/graphql/ProductData.graphql
- apps/store/src/services/apollo/client.ts
Integrate product date from API on `ProductPage`.
Update `Pillow` component to accept image props.
Update Apollo client language link to not consider "locale" variables.
We will move away from passing "locale" variables in the API.
[GRW-1925]: https://hedvig.atlassian.net/browse/GRW-1925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use API product data in `ProductPage`

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/pages/cart.tsx
Remove layout + menu from `CartPage`.
Handle closing cart by navigating back to previous route (or store).
I'm always scared to rely on "history.back" since it doesn't always behave predictably. Like if the history has changes because of "#" updates...
The current solution might be a bit overengineered but I think it's okey.
Probably in the future we should just have a dialog instead of treating it as a separate page.
> Remove layout from CartPage

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- packages/ui/.storybook/preview.js
- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/components/Checkbox/Checkbox.tsx
- packages/ui/src/components/InputBase.tsx
- packages/ui/src/components/InputField/InputField.tsx
- packages/ui/src/components/InputStepper/InputStepper.tsx
- packages/ui/src/lib/theme/colors.ts
- packages/ui/src/lib/theme/legacy/legacyColors.ts
- Add theme switcher to Storybook. This way we can see that shared components (as long as we still have them) look good.
- Add semantic colors for text to use in themes. Updated use in UI library 
(just an example where I set `textPrimary` to purple)
https://user-images.githubusercontent.com/6661511/207643727-8e8d8f44-fbb9-45b5-8663-7d8f40724839.mov
Start using semantic colors from theme
> Add theme switcher to Storybook and add text colors

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/graphql/PriceIntentFragment.graphql
- apps/store/src/services/Insurely/Insurely.tsx
- apps/store/src/services/priceIntent/priceIntent.constants.ts
Prefill input to Insurely iframe; company and personal number.
Refactor iframe setup so it can be initialized multiple times.
Update dialog so it's centered on larger screens.
Not happy about how we get personal number from price intent. Perhaps we should expose it differently in the API?
[GRW-1896]: https://hedvig.atlassian.net/browse/GRW-1896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prefill Insurely iframe input

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Add BankSignering option to `CancellationForm`.
Refactor to use option enum from API.
Add BankSignering story to Storybook.
N/A.
[GRW-1863]: https://hedvig.atlassian.net/browse/GRW-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add BankSignering option to `CancellationForm`

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Add BankSignering (invalid start date) option to `CancellationForm`.
[GRW-1863]: https://hedvig.atlassian.net/browse/GRW-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add BankSignering Invalid Start Date option to `CancellationForm`

- apps/store/src/blocks/PerilsBlock.tsx
- apps/store/src/components/Perils/Perils.stories.tsx
- apps/store/src/components/Perils/Perils.tsx
* UI changes: split PerilsBlock content into columns
> GRW-1918 - styles: split perils into columns

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/blocks/ProductSummaryBlock.tsx
- apps/store/src/components/ProductPage/ProductPageContext.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/services/storyblok/storyblok.ts
Allow product display names to be overridden from the CMS.
Translate the button that opens the price calculator.
Decided to do this inside the product page context to keep things DRY - let's see how it scales.
[GRW-1939]: https://hedvig.atlassian.net/browse/GRW-1939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow product display name to be overridden from CMS

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/ProductPage/ScrollPast/ScrollPast.tsx
Make open price calculator button sticky after you scroll down on the product page.
Fix "add to cart" button so it's also sticky (pass ref).
Clear possible floating elements by adding padding to the bottom of footer.
It's unclear how this looks on desktop so for now I just hide the element on desktop.
[GRW-1940]: https://hedvig.atlassian.net/browse/GRW-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make open price calculator button sticky

- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
Change behaviour of `PriceCalculator` to always move to the next section after successfully submitting a section form.
Move active section state out to `PriceCalculator`.
Before we selected the first section that wasn't already "valid". However, we should only to that the first time you open the price calculator. After that we should always move to the next section after successfully submitting a section form.
I moved the state out to `PriceCalculator` since this is where we can respond to successfully submitted forms. Event handlers should be as close to the source as possible.
This also gets rid of the need for `useEffect` + ref logic we had before 🙌 - always a good sign!
[GRW-1946]: https://hedvig.atlassian.net/browse/GRW-1946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> PriceCalculator: Always move to next section after submit

- packages/ui/src/lib/theme/colors/colors.ts
(Sprinkled `as const` all over the place)
Changing the types of the color tokens from `string` to `(property) gray200: "hsl(0, 0%, 92%)"`. 
For me I like this because I can quickly see the hsl value of the token I'm working with. 
_That said_ I don't have the full context of where the design system is going so perhaps there are some forthcoming changes that Idk about.
More specific types
> Create more specific color types

- apps/store/src/components/PriceCalculator/HouseholdSizeField/HouseholdSizeField.tsx
Remove focus styles for household size field.
The designs call for different state for inputs based on what triggered focus: keyboard or mouse.
I've been playing around with `:focus-visible` but can't get it to work as intended.
For now I think we can remove the focus styles for this field and revisit later and try a [polyfill](https://github.com/WICG/focus-visible).
[GRW-1947]: https://hedvig.atlassian.net/browse/GRW-1947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove focus styles for household size field

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Display animation while confirming price intent.
[Screen Recording 2022-12-21 at 09.15.51.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/77cd20be-20ac-4334-87af-97a7d9804175/Screen%20Recording%202022-12-21%20at%2009.15.51.mov)
Move confirm mutation to purchase form.
Make sure to select first incomplete form section OR the last one if all are complete. Before we didn't select any section if all were complete. If all accordions were closed, user would not see the submit button.
We have some small issues but I prefer to show to designers first and iterate on that.
Now we first update price intent and then confirrm + show the animation. However, we should show the animation right away - this would require further refactoring so I left it for now.
We …
> Display animation while calculating price

- apps/store/src/components/CartInventory/CartInventory.stories.tsx
- apps/store/src/components/PriceCalculator/CarMileageField.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/TierSelector/TierSelector.stories.tsx
- apps/store/src/components/TierSelector/TierSelector.tsx
- apps/store/src/components/TierSelector/TierSelectorStyles.tsx
- apps/store/src/graphql/ProductOfferFragment.graphql
Fix a bunch of small bugs related to editing a price intent that already is confirmed.
Keep selected product offer in state rather than deriving it from the ID.
Update `ProductOffer` fragment to fetch and use `displayName` for product variants.
Update `CarMileageField` to use placeholder instead of label.
Bug that didn't allow us to edit a confirmed price intent.
> Allow user to edit after seeing price and confirm again

- apps/store/public/locales/default/cart.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/CartInventory/CartEntryItem.tsx
- apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx
Create a fullscreen dialog that can be reused for confirmation dialogs and error dialogs.
Emerging as a comopnent in the design system.
Didn't give it specific desktop styles since it's a bit unclear in Figma. Error dialogs are fullscreen even on desktop but not sure how other cases will work.
> Update Cart Entry Removal dialog

- packages/ui/src/components/Button/Button.tsx
Make sure we don't change button height when transitioning to loading state.
Was causing layout shift.
> Update Button component to maintain height when loading

- apps/store/src/pages/_app.tsx
- apps/store/src/services/Tracking/newSiteExperimentTracking.ts
Stop using router properties outside of Next
Handle experiment variant param outside next and remove it from URL inside next
When next/router default export it used, it behaves differently depending on whether Next has already initialied
> Fix / Report experiment_impression properly

- apps/store/src/blocks/ProductDocumentsBlock.tsx
- apps/store/src/components/ProductPage/ProductDocuments.tsx
- apps/store/src/components/ProductVariantSelector/ProductVariantSelector.tsx
* Update `ProductDocumentsBlock` so it displays only the documents for the selected variant
> GRW-1904 - fix(ProductDocuments): only show documents of the selected product variant

- apps/store/src/blocks/ProductDocumentsBlock.tsx
- apps/store/src/blocks/ProductPageBlock.tsx
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/ProductPage/ProductDocuments.tsx
- apps/store/src/components/ProductPage/ProductPageContext.tsx
- apps/store/src/components/ProductPage/Tabs.tsx
- apps/store/src/components/ProductVariantSelector/ProductVariantSelector.tsx
- apps/store/src/graphql/ProductData.graphql
* Adds `ProductVariantSelector`
**Disclaimer**:  `ProductVariant.displayName` is currently not being populated by the API. Empty string is returned for each variant, so that's why the select is "empty". So as soon as we get that value, we'll be showing it.
https://user-images.githubusercontent.com/19200662/209939675-27f719f0-3aaa-4773-a6a0-0775b78cf401.mov
> GRW-1904 - feat: added ProductVariantSelector

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/PriceCalculator/PriceCalculatorSection.tsx
- apps/store/src/graphql/InsurelyDataCollectionCreate.graphql
Update Insurely implementation to use new `externalInsuranceProvider.initiateIframeDataCollection` mutation.
It's called as soon as we get the collection ID from Insurely and exchanges it for an internal ID. This is stored in React state until data collection is complete which is when we run the mutation to update the price intent.
This is needed for backwards compatability.
Component is getting pretty complex - should refactor soon.
> Add new mutation to create internal data collection ID

- apps/store/README.md
- apps/store/src/pages/api/session/reset.ts
- apps/store/src/services/persister/CookiePersister.ts
- apps/store/src/services/persister/Persister.types.ts
- apps/store/src/services/persister/ServerCookiePersister.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
Add API route `/api/session/reset` to allow us to quickly reset the current session by removing relevant cookies.
Add a way to setup price intent service server side.
Expose a couple new methods from price intent service and cookie persister.
Very common use case when doing development. We could build more tool on top of this but even this will help out!
[GRW-2001]: https://hedvig.atlassian.net/browse/GRW-2001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add API route to reset current session

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Use intersection observer util from framer-motion to track view_item event when selectedOffer first becomes visible
- Solves double event from responsive rendering of OfferPresenter
- Solves race condition with progress bar and event timing
- Useful example of tracking something being visible, we'll likely need to track more such things in the future
> GRW-2006 / Feature / Track view_item when offer becomes visible

- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/HouseholdSizeField/HouseholdSizeField.tsx
- apps/store/src/services/PriceCalculator/Field.types.ts
- apps/store/src/services/PriceCalculator/formFragments.ts
Update form config to allow configuring input type
Explicitly use type=button for non-submit buttons in `HouseholdSizeField`.
Better to use type=email than inputmode=email
> Use type=email for email input field

- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/HouseholdSizeField/HouseholdSizeField.tsx
- apps/store/src/components/ProductPage/PriceIntentContext.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/services/PriceCalculator/Field.types.ts
- apps/store/src/services/PriceCalculator/formFragments.ts
Refresh price intent after adding an offer to the cart.
We used to just refresh the page but this doesn't work when we have a static page.
I exposed a `setupPriceIntent` function from the context to avoid having to repeat the code that creates price intents.
> Recreate price intent after adding to cart

- apps/store/src/blocks/ContentBlock.tsx
Updated `ContentBlock` so we can use it to display _product description_.
> GRW-1911 - feat(ContentBlock): addded alignment and heading fields

- apps/store/src/components/TextField/TextField.stories.tsx
- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/utils/useHighlightAnimation.ts
Update `TextField` background color and disabled state.
Use Text component inside label-tag.
Add `:focus-visible` styles.
Allow highlight animation to work with any default background.
Keeping it up-to-date with Figma designs.
I used `:has` selector even if it has very poor browser support. Let's see what kind of focus states we will end up with in the end -- this way we can quickly show designers so they get a feel for it.
> Update `TextField` styles

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/TextField/TextField.stories.tsx
- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/utils/useHighlightAnimation.ts
Just a quick refactor for small screens.
> Allow PriceCalculator to use full width on small screens

- packages/ui/src/icons/Icons.stories.tsx
- packages/ui/src/lib/theme/colors/colors.stories.tsx
- Changed the design of the icon page.
- Added the ability to click on the icon and have it's name copied to your clipboard.
Stole a bunch of ideas and code from @gustaveen 's Color story to make this happen. 
_“good artists borrow, great artists steal.”_ - [Pablo Picasso](https://media4.giphy.com/media/l2JhyuVn311Y1RWqA/200.gif) (maybe?? maybe not?? )
_Would be cool to have a little toast show up when you've copied something to your clipboard but I did not want to add it to the project._
Not really needed. Just nice to have.
> Improve Icon story design 

- apps/store/src/components/CartInventory/CartEntryList.tsx
- apps/store/src/components/CartPage/CartPage.tsx
Small ui fixes on the cart page to better match the designs. 
- heading padding left/right
- heading padding with the content on the page
_Should all look very much like the /checkout page._ 
[GRW-2042]: https://hedvig.atlassian.net/browse/GRW-2042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Grw-2042/fix cart heading spacing

- apps/store/src/components/CartInventory/CartEntryList.tsx
- apps/store/src/components/CartPage/CartPage.tsx
Refactor Cart + Checkout page layout to match design.
Move padding from shared `CartInventory` to Cart page.
Layout should be decided by the component that implements it, not by the child component. Therefore it's better to use e.g. `Space` in the parent component rather than pushing content with padding in the child component.
In this case, the added padding in `CartEntryList` didn't work on the Checkout page.
> Refactor Cart + Checkout layout

- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceCalculator/InputRadio.tsx
Update background and other small fixes to align `Input` and `Select` fields with other inputs.
> Tweak inputs to use same design as `TextField`

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/CountrySelectorPage/CountrySelectorPage.tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/pages/country-selector.tsx
- apps/store/src/utils/l10n/localeUtils.ts
- apps/store/src/utils/useReloadOnCountryChange.ts
Add hook to ensure we reload a page if country changes during client side navigation
Make country selector controls and page use full reload when changing country
Ensure our assumptions about never changing country during client lifetime are satisfied, prevent bugs
This gives us simpler app model at expense of small increase in user wait time when country changes (should be rare)
> GRW-1985 / Feat / Ensure we do full page reload on country change

- apps/store/src/components/CartInventory/CartEntryItem.tsx
Created a desktop layout of cart entry items. This component is seen on the /cart and /checkout pages.
Attempted to do this in several ways. Thought this was the least complicated, although I don't _love_ how the show/hide of things like the "title" (`<MobileTitle />` & `<DesktopTitle />`) are done with css. 
Matching the designs in Figma.
[GRW-2016]: https://hedvig.atlassian.net/browse/GRW-2016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2016/Desktop layout - Cart Entry

- apps/store/src/blocks/PerilsBlock.tsx
* Renders `PerilsBlock` heading only it gets provided
`heading` is a optional field in _Storyblok_. By always rendering `PerilsBlock`'s heading we might end up with this "weird" design here only a "small blue pill" is displayed on top of the block.
---
> fix(PerilsBlock): renders heading only when it's provided

- apps/store/package.json
- apps/store/src/middleware.ts
- yarn.lock
Support configurable redirects in middleware
Redirects are configured through [Vercel Config](https://vercel.com/docs/concepts/edge-network/edge-config)
[Design notes](https://www.notion.so/hedviginsurance/Hedvig-com-payments-2f28207e18484bcfb6f2686881a2b76a)
One of launch features, to allow gradual migration between old and new site
> GRW-1586 / Feature / Configurable redirects

- apps/store/src/blocks/ButtonBlock.tsx
* Updated `ButtonBlock` so we can take in `size` from Storyblok
So we can support some of the design requirements, like the one for `ImageTextBock`
[GRW-2054]: https://hedvig.atlassian.net/browse/GRW-2054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2054 - feat(ButtonBlock): enable size configuration

- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/blocks/HeadingBlock.tsx
- apps/store/src/blocks/ImageTextBlock.tsx
- apps/store/src/blocks/TextBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
Update `ImageTextBlock` to match the designs.
Can be tested on `en-se/insurances/car-insurance` storyblok page (overview tab)
---
[GRW-2054]: https://hedvig.atlassian.net/browse/GRW-2054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2054 - feat: update ImageTextBlock

- apps/store/src/pages/api/auth/login/se.ts
- apps/store/src/services/Auth/Auth.ts
- apps/store/src/utils/PageLink.ts
- apps/store/src/utils/auth.ts
Integrate the auth service to be able to use the "member login" endpoint.
Add a new API route to make the request to auth service.
This new API route accepts an SSN + optional "next" parameter to redirect the user after successful login. It also sets the auth session cookie.
This will be useful in the future but more so if we want to handle existing members in the checkout. The idea is to make them login before going through the checkout.
I added an API route beacuse CORS blocks us from calling auth service directly from client.
We don't know what the UX will look like so this PR doesn't contain any UI stuff.
I want to co-locate all auth stuff in the same "service" module -- will do in separate PR.
> Implement login endpoint for Swedish BankID method

- apps/store/src/blocks/ImageTextBlock.tsx
Refactor `ImageTextBlock` to cover edge cases:
* Strictly "horizontal" layout
* Strictly "vertical" layout
* Fluid mode
I've realised didn't cover everything with my most recent [changes](https://hedvig.atlassian.net/browse/GRW-2054) for `ImageTextBlock`. So this PR is about the addition of them.
---
https://user-images.githubusercontent.com/19200662/212347897-cf2842a4-738d-4e73-a2d5-b557e2dea10c.mov
> refact(ImageTextBlock): cover some design edge cases

- apps/store/src/services/storyblok/storyblok.ts
Prevent "You are not in Draft Mode or in the Visual Editor" warning by only enabling Storyblok bridge in iframe
One step closer to zero warnings
> Only initialize Storyblok bridge when inside iframe

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/blocks/AccordionItemBlock.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/Perils/Perils.tsx
* Update `AccordionBlock` so desktop layout matches the proposed design.
---
[GRW-2095]: https://hedvig.atlassian.net/browse/GRW-2095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2095 - fix(AccordionBlock): desktop layout

- apps/store/public/locales/en/cart.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CartPage/RecommendationList.tsx
- apps/store/src/graphql/ProductRecommendationFragment.graphql
- apps/store/src/graphql/ShopSessionFragment.graphql
- apps/store/src/pages/cart.tsx
Integrate list of product recommendations on Cart page.
Add recommendations when fetching `ShopSession`.
Refactor Cart page to not use dynamic theme.
We should probably consider only fetching recommendations on the Cart page and not with every shop session request but don't want to optimize too early.
The API is not 100% working so that's why I didn't include photos.
> Integrate product recommendations on Cart page

- .eslintrc.js
- .husky/pre-commit
- apps/onboarding/package.json
- apps/store/package.json
- package.json
- packages/ui/package.json
- turbo.json
- yarn.lock
Replace `lint-staged` with just running `eslint --fix` for each workspace in the pre-commit hook.
Setup new turbo pipeline.
I've been struggling with the ESLint setup over the last couple of days.
I've tried a bunch of different settings but nothing seems to work and I don't understand why.
Essentially the problem is that `eslint` run from ROOT behaves differently from when it's run from the workspace. This is the case with `lint-staged`. It might have something to do with `eslint + typescript` and how it resolves the `tsconfig.json` file.
> Replace lint-staged with linting across all workspaces

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
* Displays product name as a `h1`
SEO reasons.
[GRW-2089]: https://hedvig.atlassian.net/browse/GRW-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2089 - fix(ProductPage): display product name as a 'h1'

- packages/ui/src/components/Checkbox/Checkbox.tsx
* Update Checkbox styles on Landing Page to this [issue](https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1674143381495789)
* General refactoring by using `theme` outside context
---
> fix(Checkbox): fixed checkbox styles on landing page

- apps/store/src/components/TextField/TextField.tsx
Add ellipsis overflow to label in `TextField`.
Refactor `TextField` to not use dynamic theme.
Use `data-active` prop instead of passing variable to emotion.
Breaks the design if the label overflows the container.
> `TextField`: avoid label overflow

- apps/store/scripts/download-translations.sh
Skip en-* locales when downloading from Lokalise (in "store")
We rely on falling back to the "en" locale across all countries.
We can easily add them back into the script if we see a need for it.
> Skip downloading en-* locales from Lokalise

- apps/store/src/components/CountrySelectorPage/CountrySelectorPage.tsx
Added the wrapper from pages like the cart/confirmation page to the country-selector page. Seems like these should all have the same or similar widths.
Consistant  styles across the app.
> Update country-selector page styles

- apps/store/src/components/TextField/TextField.tsx
Remove focus styles for `TextField`
Not correct, remove now until we have a better solution that only shows up when you use keyboard.
> Remove focus styles for text field

- apps/store/src/components/ProductPage/PurchaseForm/PriceCalculatorDialog.tsx
- apps/store/src/components/TextField/TextField.tsx
Fix issue in price calculator where you can't scroll to the bottom on iOS.
> Fix scroll to bottom on iOS in Price Calculator

- apps/store/src/components/SwitchingAssistantPage/SwitchingAssistantPage.tsx
- apps/store/src/graphql/ProductOfferFragment.graphql
See title.
The API doesn't guarantee that we have an external insurer but it shouldn't happen. That's why I added the datadog logging.
> Switching Assistant: show external insurer display name

- apps/store/src/components/TextField/TextField.stories.tsx
- apps/store/src/components/TextField/TextField.tsx
Add warning state to `TextField`
Add optional message prop to `TextField`
New from UI kit.
Implemented as `data-warning` property to handle all styling in CSS.
Not sure what to do with `:invalid` state - if it should inherit these styles...
> `TextField`: add warning state and message

- packages/ui/src/components/Text/Text.tsx
- packages/ui/src/lib/theme/colors/colors.stories.tsx
- packages/ui/src/lib/theme/colors/colors.ts
Add translucent colors to the theme
Add more text colors
Add semantic gray colors based on translucent values
> Add gray translucent colors to theme

- apps/store/src/blocks/ProductPageBlock.tsx
- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/ProductPage/Tabs.tsx
* Remove one unused CSS declaration from `Header` component
* Update `ProductPageBlock` so it better matches the designs:
* Also display _Overview+Coverage_ tabs on mobile
* Scroll to top when active tab changes
I guess the easiest way to test is running this branch locally and load this [page](http://localhost:8040/se/forsakringar/hemforsakring/hyresratt) and compare it with the proposed [design](https://www.figma.com/file/8SfzuQEJ4LJ6uKL0l7WKoE/Hedvig.com-%C2%B7-Final-Design?node-id=1544%3A6150&t=TCUeMFR0Eb98ROcl-0)
[GRW-2090]: https://hedvig.atlassian.net/browse/GRW-2090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2090 - refact(ProductPage): displays Overview+Coverage tab on desktop layout

- apps/store/src/blocks/AccordionItemBlock.tsx
- apps/store/src/components/RichTextContent/RichTextContent.tsx
* Re-apply styles for text formatting HTML tags (`<b>`, `<i>`, etc). We get the correct HTML from _Storyblok_ but the issue is that we have a CSS reset that remove all of their styles:
So I've thought was to keep the CSS reset as it is and re-apply some of the `initial` styles for RTF based content. In that way we can change how they should look later (if some changes become necessary).
At the moment, I'm just applying those changes for `AccordionItem`. But maybe we should consider on having a `RichTextField` shared component responsible to handle styles whenever we use _Storyblok_'s Rich Text Field. Let me know what you guys think.
Despite being possible to formatting the text with _Storyblok_'s Rich Text Field, the real content wasn't being displayed properly which blocks us to achieve …
> GRW-2135 - fix(AccordionItem): enable rich text formatting

- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/DateInput.tsx
- apps/store/src/components/ToggleCard/Switch.tsx
- apps/store/src/components/ToggleCard/ToggleCard.tsx
Avoid capitalizing "today" when using `fromNow` formatted.
Messes up copy in the UI.
> Don't capitalize 'today' label in date input

- apps/store/src/components/SwitchingAssistantPage/SwitchingAssistantPage.tsx
- apps/store/src/pages/checkout/switching-assistant.tsx
- apps/store/src/utils/PageLink.ts
Move data transforms server-side and pass down to React for switching assistant page.
There was a bug when we were trying to log with datadog from the server.
We only render this page once so we don't need to do any client-side refresh => transform data on the server!
> Refactor Switching Assitant page to avoid SSR issues

- apps/store/src/blocks/AccordionItemBlock.tsx
- apps/store/src/components/RichTextContent/RichTextContent.tsx
* Added support for links and line breaks on `RichTextContent` component
Requested for used on AccordionBlock
> feat(RichtTextContent): added support for links and line breaks

- apps/store/src/blocks/ProductPageBlock.tsx
* Added some SEO meta tags for `ProductPageBlock`. Observe that's not possible to configure _og:title_ and _og:description_ in _Storyblok_ since they should [assume the same value as _meta title_ and _meta description_](https://hedviginsurance.slack.com/archives/C04JND65KPH/p1675086492792989?thread_ts=1675086209.814679&cid=C04JND65KPH).
[GRW-2145]: https://hedvig.atlassian.net/browse/GRW-2145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2145 - feat(ProductPage): added SEO data

- apps/store/src/blocks/ConfirmationPageBlock.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/services/storyblok/storyblok.ts
Looking to create a page where some of the content is hardcoded and the other is managed in Storyblok. 
- Creating a `confirmation` component in Storyblok and in code.
Designers want the ability to changes things around on parts of the confirmation page, these changes would be a step to allowing that to happen.
> Setup Storyblok to be used on the confirmation page

- apps/store/README.md
- apps/store/src/pages/session/[shopSessionId].tsx
Add support for setting a campaign code when resuming a shop session.
We need this to support retargeting emails.
> Add support for setting a campaign code when resuming a shop session

- apps/store/README.md
- apps/store/src/pages/api/campaign/[code].ts
- apps/store/src/pages/session/[shopSessionId].tsx
Add a new endpoint to be able to attatch a campaign code to the current or new shop session.
This will be used in marketting.
We discussed that limiting it to a given endpoint will help us to maintain it rather than supporting a query parameter anywhere on the site. This was okeyed by Simon and Sonny.
> Add endpoint to set default campaign code

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/components/Header/NavigationLink.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/LayoutWithMenu/ProductMetadataContext.tsx
- apps/store/src/components/LayoutWithMenu/fetchProductMetadata.ts
- apps/store/src/graphql/ProductMetadata.graphql
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
Introduce the concept of global product metadata that can be used in places like the layout header/navigation.
Currently implemented as React context around the layout component.
Add pillow image option to nav item in Storyblok to be able to override the default image.
To be able to render product info in global places like the layout header.
I don't want to fetch this on every render but rather fetch onces during build and just pass it down to the layout component like other static CMS-driven data.
> Add global product metadata to layout header

- apps/store/src/blocks/ProductPageBlock.tsx
- packages/ui/src/lib/globalStyles.ts
- packages/ui/src/lib/theme/colors/colors.ts
* Updates _Overview/Coverage_ navigation controls work based on layout applied: Mobile or Desktop
_Overview/Coverage_ navigation should behave differently based on the layout applied:
* Mobile: they should work as tabs where only the content related with the active tab should be displayed;
* Desktop: all of the content should be displayed and the navigation control should behave like internal links to page content sections.
As it can be seen in the attached video below content for product page were being segmented in a tab format the same way mobile layout does; which is wrong:
https://user-images.githubusercontent.com/19200662/215842283-ea3545ba-18eb-47b2-9222-a8bc2fb8cc69.mov
As it can be seen in the attached video below the whole product page content is now being displayed for the …
> GRW-2159 - fix content navigation for desktop layout

- apps/store/src/components/Video/Video.tsx
Keep track whether videos were playing when dialog was opened and resume them when dialog is closed.
Before we resumed videos even if they were not playing when dialog was opened.
> Only resume playing videos after closing modal

- apps/store/src/blocks/ProductPageBlock.tsx
- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
- apps/store/src/components/Pillow/Pillow.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Prevent purchase form on desktop to scroll too early.
Slightly tweak sizes of the pillow to better match design.
> Prevent purchase form from scrolling too early

- apps/store/src/components/CheckoutHeader/CheckoutHeader.tsx
Implement shared `GridLayout` component in `CheckoutHeader`.
We should make sure to use the same primitives across the app to ensure consistency.
> Implement `GridLayout` in `CheckoutHeader`

- apps/store/src/blocks/VideoListBlock.tsx
- apps/store/src/components/Slideshow/Slideshow.tsx
* Update `Slideshow` so it can get a ref;
* Add an event handler for `play` event to each video of `VideoListBlock` that make sure only one video gets played at a time.
https://user-images.githubusercontent.com/19200662/216939688-cc8f2800-2bd4-4c3d-8783-a97cce962385.mov
[GRW-2120]: https://hedvig.atlassian.net/browse/GRW-2120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2120 - feat(VideoListBlock): play only one video at a time

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/components/Header/Header.stories.tsx
- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/TopMenuDesktop/TopMenuDesktop.tsx
- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
- apps/store/src/components/Header/useScrollDirection.ts
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/services/storyblok/storyblok.ts
[Screen Recording 2023-02-07 at 09.36.24.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/ce6fbf9f-e8d5-4e03-8a8c-2fcdbc353e18/Screen%20Recording%202023-02-07%20at%2009.36.24.mov)
1. Show menu on-top of content
- Remove background color from menu, apply background only when mobile menu is open
1. Scroll menu with content
1. When user scrolls up, show menu with animation
- Implement custom hook to determine scroll direction
1. When user scrolls down, hide menu with animation
1. When user scrolls to top, hide overlayed menu to show the static menu
Also remove some webkit tab highlight styles :P
Implemented it according to menu found on [https://www.mindbloom.com/](https://www.mindbloom.com/).
I had to duplicate the menu content and render it twice. …
> Site menu: animate in/out as you scroll

- apps/store/src/blocks/ProductPageBlock.tsx
* Fix styles for ProductVariantSelector on mobile
* Fix bug where ProductVariantSelector wasn't being displayed on Desktop
**Disclaimer(s)**
* Got feedback from Zak about the size of the `ProductVariantSelector` being not proportional with the other controls. That's going to be part of another [ticket](https://hedvig.atlassian.net/browse/GRW-2194).
* If you decide to test it might happen to you that you can't actually see the `ProductVariantSelector` on Desktop because those controls gets hidden when one reaches _Coverage_ section of the page. There's an open request to make those controls available throughout  bot sections: _Overview_ and _Coverage_ so it's something we'll fixed in the future.
I've "forced" their appearance on desktop just so I could get an screenshot.
I've introduced …
> GRW-2191 - fix(ProductPageBlock): display ProductVariantSelector for desktop layout

- apps/store/src/pages/confirmation/[shopSessionId].tsx
Revert changes from https://github.com/HedvigInsurance/racoon/pull/1561
Keeping the check if the story is undefined. 
Added the `/se` confirmation page by copy/pasta 🍝 the page from `en-se` in storyblok. 
After chatting with @robinandeer. I see that we're only not going to be translating slugs for non content pages like the confirmation page.
> Hard code slug for confirmation page.

- apps/store/src/blocks/HeadingBlock.tsx
- apps/store/src/blocks/HeadingLabelBlock.tsx
- apps/store/src/blocks/TextContentBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
- packages/ui/src/components/HeadingLabel/HeadingLabel.tsx
- packages/ui/src/index.ts
New block that we will use for text content
The block can render `Heading`, `HeadingLabel` and `Text`.
`Content` block is still left but this will replace that block once migrated
https://user-images.githubusercontent.com/6661511/217306036-b6fcd659-84cc-48ea-b8ca-87a6f526ed33.mov
Next steps: Add settings for controlling column layout/width and spacing between text.
The plan is to align the content to the 12 column grid.
To work with text heavy pages we need more options to render text
> Update text contnent block

- apps/store/src/components/Animations/Message/Message.tsx
- apps/store/src/components/Animations/NumberPad/NumberPad.tsx
Using next dynamic import to lazy load Lottie animation. https://nextjs.org/docs/advanced-features/dynamic-import
Was unsure what's the best place to do it however. Would it be better to do it in `ContactSupportBlock` 🤔
Decrease initial load time
> Dynamically import Lottie animations

- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/utils/useAllowActiveStylesInSafari.ts
- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/lib/globalStyles.ts
Remove tap highlight globally from the app for webkit browsers.
Add custom hook to make sure active styles work on mobile devices.
Add active styles to at least the buttons.
Annoying tap highlight.
> Disable tap highlight for webkit browsers

- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/TopMenuDesktop/TopMenuDesktop.tsx
- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/utils/useAllowActiveStylesInSafari.ts
- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/lib/globalStyles.ts
Make sure to close the nav menu after clicking nested links.
Use router events to close the nav menu after clicking a link.
This should work out of the box but Next.js does something with the event propagation that makes it not work. This is a workaround. Read more here: https://github.com/radix-ui/primitives/issues/1301
> Close nav menu after clicking link

- apps/store/src/blocks/ImageBlock.tsx
Add wrapper layout div with padding to image block that isn't fullbleed.
When we added padding to the same div as the relative wrapper, it caused the image to ignore the padding. This fixes that.
> Fix padding in non-full-bleed image block

- apps/store/public/locales/dk/purchase-form.json
- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/no/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Update to use the new banksignering invalid renewal date option.
Stop sending both renewal date and start date mutations to the backend.
The API responds incorrectly when sending both mutations.
We should adresss it some other way in the future.
> Update to use new cancellation option from API

- apps/store/src/components/TextField/TextField.tsx
Fix text field disabled state to show label with same color as input.
Refactor text field to use component selectors.
I think it's always nice to make styled components self-contained rather than being referenced from other places. Deletability!
> Fix disabled state for text field

- apps/store/src/components/ProductPage/ProductPageContext.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
1. Group together content for the purchase form inside page context
1. Hide tagline above "calculate price" button if empty
1. Always use display name from product data for purchase notification
We were mixing up when to use which display name for the purchase notification. This PR makes sure we always use the display name from the product data.
Also wanted to avoid overriding content in the page context, so I grouped the content together.
[GRW-2211]: https://hedvig.atlassian.net/browse/GRW-2211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Group together purchase form content in page context

- apps/store/src/blocks/AccordionItemBlock.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/FooterSection.tsx
- apps/store/src/components/ConfirmationPage/Layout.tsx
- apps/store/src/components/ProductPage/ProductDocuments.tsx
Expand content on confirmation page. Keep 6 column layout for xl media query.
Create override layout componentn for confirmation page.
Let's see if we really need a special layout for this page in the future.
> Expand content on confirmation page

- apps/store/src/blocks/VideoBlock.tsx
- apps/store/src/components/Video/Video.tsx
Being able to use the video block full bleed without rounded corners or padding
https://user-images.githubusercontent.com/6661511/217866457-43dc7d7d-c59f-4954-87c9-c690ed0e8f34.mov
Show videos full screen
> Add fullBleed option to video

- apps/store/src/blocks/AccordionItemBlock.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/RichTextContent/RichTextContent.tsx
* Apply hover styles to `AccordionBlock` by changing `Accordion` component
Can be tested by interacting with _Frequent asked questions section_ on this [page](https://hedvig-dot-com-git-grw-2217-refactperils-hedvig.vercel.app/se/forsakringar/hemforsakring/hyresratt)
[GRW-2217]: https://hedvig.atlassian.net/browse/GRW-2217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2217 - Add Accordion hover styles

- apps/store/src/components/Perils/Perils.tsx
* Refact `Perils` so it leverage hover styles from `Accordion` component
Can be tested by interacting with _perils section of_ on this [page](https://hedvig-dot-com-git-grw-2217-refactperils-hedvig.vercel.app/se/forsakringar/hemforsakring/hyresratt)
[GRW-2217]: https://hedvig.atlassian.net/browse/GRW-2217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2217 - Refact Perils so it makes usage of Accordion hover styles

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/GridLayout/GridLayout.tsx
- apps/store/src/components/ProductPage/ProductDocuments.tsx
Unify the layout of accordion and product document blocks.
> Align layout for accordion and document blocks

- packages/ui/src/icons/Root.tsx
Don't pass down size="1rem" to svg DOM nodes via IconRoot
Fixes noisy console errors in Safari
> Fix IconRoot passing invalid size values to svg element

- apps/store/src/components/InputSelect/InputSelect.tsx
* Make icon ignores pointer events
So the whole select input gets clickable
[GRW-2236]: https://hedvig.atlassian.net/browse/GRW-2236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2236 - fix(InputSelect icon): ignore click events

- apps/store/src/components/ProductCard/ProductCard.tsx
- apps/store/src/components/ProductGrid/ProductGrid.tsx
- apps/store/src/components/ProductRecommendationList/ProductRecommendationList.tsx
Fix Safari CSS grid bug in product grid.
CSS grid with `align-items: baseline` isn't working in Safari. This is a known bug: https://stackoverflow.com/questions/52502989/css-grid-align-items-baseline-not-working-in-safari.
> Safari: fix product grid layout

- apps/store/src/blocks/HeaderBlock.tsx
Wrapped the nav items with links to make the whole item clickable. 
[Test the issue in the staging env](https://www.store.dev.hedvigit.com/en-se)
Right now the clickable area is only the text. We'd want to give the user more space to click what they want.
> Wrap navigation items w/ links

- apps/store/src/pages/404.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/api/campaign/[code].ts
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/[status].tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/index.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/switching-assistant.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/pages/session/[shopSessionId].tsx
- apps/store/src/services/apollo/client.ts
Update how to get hedvig-language header on server.
Skip relying on fallback.
We sometimes fail to determine language on the server. Then we fallback to english (SE) which is not good. Half the UI is in english and half in swedish.
I would like to refactor more and get rid of the fallback but I think this is a good first step.
The language should always be derived from the URL.
> SSR: update how to get hedvig-language header

- apps/store/src/blocks/ProductPageBlock.tsx
* Fix a bug introduced while making the tab navigation available through the whole page on desktop layout, where coverage section only occupies half of the screen.
* Makes Overview/Coverage tab visible throughout the whole page on desktop
https://user-images.githubusercontent.com/19200662/218691774-73207557-f9c8-46b8-8829-67c520fffe49.mov
[GRW-2240]: https://hedvig.atlassian.net/browse/GRW-2240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2240 - fix(ProductPage): full width coverage section

- apps/store/src/blocks/ProductPageBlock.tsx
- apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/_document.tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
* Updates `HeadSeoInfo` so it handles more SEO related tags
* Refactor `ProductPageBlock` by leveraging `HeadSeoInfo` in order to add seo related tags into documents `<head>`
[GRW-2241]: https://hedvig.atlassian.net/browse/GRW-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2241 - feat(StoryblokPage): added SEO info

- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Add hover state to edit button in price calculator.
> Add hover state to edit price calculator

- apps/store/src/components/ProductVariantSelector/ProductVariantSelector.tsx
* Takes possible already defined `selectedVariant` into account while configuring a `defaultValue` for `ProductVariantSelector`.
**Before**
https://user-images.githubusercontent.com/19200662/218791396-4fbbe2a7-2551-4491-9520-f8971d117c88.mov
**After**
https://user-images.githubusercontent.com/19200662/218791564-dbaa1b07-c350-4d6d-be1d-d539b979042b.mov
[GRW-2246]: https://hedvig.atlassian.net/browse/GRW-2246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2246 - fix(ProductVariantSelector): proper set default value

- apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/storyblok/storyblok.ts
* Rename ~seoMetaTtile~ --> seoTitle field for _Product_ and _Page_ Storyblok page types;
* Move `<title>` insertion into `HeadSeoInfo` component
There’s no reason to <title> and <meta name=”title”> tags since in that case only <title> will be considered. With that said, we need to update SEO tab for Product and Page strobyblok page types by renaming seoMetaTitle field to seoTitle and use its value only for setting a <title> tag for the page.
[GRW-2255]: https://hedvig.atlassian.net/browse/GRW-2255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> 
> #### What changed
> - Changed property name from `seoMetaTitle` to …
> GRW-2255 - refact(HeadSeoInfo): replace seoMetaTitle --> seoTitle

- apps/store/src/components/PriceCalculator/SsnSeSection.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useOpenPriceCalculatorQueryParam.ts
Allow to open price calculator on product page based on URL query param
We need this for 2 features
- fix for session reset when changing SSN
- ability to show "get a price" link in ProductCart
Could be usefult for cross-sell links in the future
> Support ?openPriceCalculator=1 on product pages

- apps/store/src/components/HeroVideo/HeroVideo.tsx
- apps/store/src/components/Video/Video.tsx
- Fix invalid style when video poster is missing
- Don't preload full videos by default
Reduce initial download size of front page
> Video download size optimizations

- apps/store/src/components/ProductPage/ProductPage.types.ts
- apps/store/src/components/ProductPage/ProductPageContext.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/storyblok/storyblok.ts
* Move 'ProductDataVariant' type definition into ProductPage.types
* Get default product variant from storyblok
[GRW-2257]: https://hedvig.atlassian.net/browse/GRW-2257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2257 - feat(ProductPage): support default product variant definition from Storyblok

- apps/store/src/components/Perils/Perils.stories.tsx
- Reworked the peril story
- Moved the regular accordion together with the peril story
-  Created a little 'peril playground' where you can add and remove them as you like.
A lot of these changes are a  _nice to have_ for sure. 
What's needed is having the 'default' accordion right next to the peril accordion since they share a lot of styles / code. These changes make working on these components easier to work with / troubleshoot.
> Peril Playground: Refactor the Accordion story

- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/services/storyblok/storyblok.ts
Update layout for CMS blocks on the confirmation page.
Expose grid alignment styles and override block styles when rendered on the confirmation page.
Define text + accordion (faq) as CMS blocks.
The layout was not correct. The confirmation page has a different layout than the other pages. We should try to harmonize the layout of the pages. I will discuss with design if this is possible.
Otherwise I feel like this is an explicit way of showing that some blocks should render differently on the confirmation page.
> Fix layout of CMS blocks on confirmation page

- apps/store/src/blocks/HeroVideoBlock.tsx
- apps/store/src/blocks/VideoBlock.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- packages/ui/src/lib/media-query.ts
Use Storyblok image optimization for video posters
This reduces resources dramatically, ~15MB total savings on /se, for example.  I'd love to use Vercel for this optimization, but they don't have a documented API outside of Image component
> Optimize video posters through Storyblok optimization server

- apps/store/src/blocks/ProductPageBlock.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/lib/media-query.ts
- packages/ui/src/lib/theme/theme.ts
- packages/ui/src/lib/theme/transitions.ts
Prevent rerenders from useBreakpoint on every resize - we only care about hook result
Decided not to use external library for now to keep it small
> Optimize useBreakpoint to only rerender when size crosses the threshold

- apps/store/src/components/Video/Video.tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
Use storyblok CDN by applying cv (cacheVersion) value to non-draft pages
First step towards faster Storyblok access on Vercel where in-memory cache is useless
> Use Storyblok CDN for non-draft stories with cache version taken from Vercel config

- apps/store/src/blocks/CardLinkBlock.tsx
- apps/store/src/blocks/CardLinkListBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
* Add `CardLink` and `CardLinkList` blocks
Required for the implementation of _Support_ page.
Can be tested [here](https://hedvig-dot-com-git-grw-2270-featcard-link-hedvig.vercel.app/se/hjalp/support-link-card)
[GRW-2270]: https://hedvig.atlassian.net/browse/GRW-2270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2270 - feat: added CardLink/CardLinkList blocks

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/components/ProductPage/ProductDocuments.tsx
**Disclaimer**: We're not aiming for a _pixel perfect_ implementation on this one for the first lunch. At the end, it was decided to not include the short description and, as a compromise on the document names, the _country based prefix_ will be removed: ~_SE Hyresrätt Villkor_~ --> _Hyresrätt Villkor_. However, nothing will need to be have done on our end in order to get this in place. So as part of this PR I've just updated some spacing styles.
Update spacing as requested by design. The idea was to change _ProductDocuments_ only but I've noticed the same spacing was missing for _Accordion_ as well.
[GRW-2237]: https://hedvig.atlassian.net/browse/GRW-2237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2237 - styles(ProductDocuments): style updates

- apps/store/src/components/CartInventory/CartInventory.helpers.tsx
Fixed the getCrossOut function logic for displaying the crossed out discount information.
Previously not working as intended.
> Fix - discount cross out display amount

- apps/store/package.json
- apps/store/src/pages/_app.tsx
- packages/ui/src/components/Heading/Heading.stories.tsx
- packages/ui/src/components/Heading/Heading.tsx
- yarn.lock
- Added react-wrap-balancer
- Updated the heading component to use the balancer
- updated heading story to show better how the balancer works
I see several places where the balancer could be used. It's up to us to decide if/how much we'd like to use it.
https://user-images.githubusercontent.com/50870173/219662083-c403f6bd-ea5b-411b-ad49-27168108afda.mov
https://user-images.githubusercontent.com/50870173/219661432-9ed6f1bd-9924-4fd1-abb9-9eb8c263a8e4.mov
Help make our titles more readable.
> Add React-wrap-balancer to `<Heading />`

- apps/store/package.json
- apps/store/src/pages/api/campaign/[code].ts
- apps/store/src/pages/api/session/create.ts
- apps/store/src/pages/api/session/reset.ts
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/[status].tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/index.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/switching-assistant.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/pages/session/[shopSessionId].tsx
- apps/store/src/services/apollo/apollo.helpers.ts
- apps/store/src/services/apollo/client.ts
- apps/store/src/services/authApi/oauth.ts
- apps/store/src/services/authApi/persist.ts
- apps/store/src/services/bankId/useBankIdCheckoutSign.ts
- apps/store/src/services/bankId/useBankIdLogin.ts
- apps/store/src/services/shopSession/ShopSessionContext.tsx
- yarn.lock
- Save refresh token in cookie
- Add new function `refreshAccessToken` to perform refresh token request
- Add new function `performTokenRefreshIfNeeded` to evaluate if current access token has expired and if so, refresh it.
- Add new function `initializeApolloServerSide` to initialize Apollo server side and perform token refresh if needed.
- Update `headersLink` to perform token refresh if needed (client side).
The overall goal is to be able to support longer sessions without having to log in again. This is done by saving the refresh token in a cookie and using it to refresh the access token when it expires.
I had to update the apollo initialization a little bit since we need access to cookies to refresh the token and do it async.
Caveat: we only refresh the access token when sending a …
> Add support to refresh expired access tokens

- apps/store/src/components/Perils/Perils.tsx
Perils text overflow on mobile
**Before**
**After**
> fix(Perils): text overlow on mobile

- apps/store/src/components/PriceCalculator/SsnSeSection.tsx
Handle SSN change case when member is not authenticated but SSN still cannot be changed because there're items in the cart
Prevent "SSN cannot be changed" error
[GRW-2129]: https://hedvig.atlassian.net/browse/GRW-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Warn about changing SSN if there're offers in the cart even if customer is not authenticated

- apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
Determine if we should show switching assistant in checkout by looking at cancellation option.
The "banksignering" property isn't filled in until after we sign the shop session so we can't use it to determine if we should show the switching assistant.
> Fix how to determine checkout steps

- apps/store/src/blocks/HeadingBlock.tsx
- apps/store/src/pages/_app.tsx
- packages/ui/src/components/Heading/Heading.tsx
- Added a `balance` prop to the `<Heading /> ` component to allow for the balancer to be adopted in a case by case basis.
- removed the balancer provider from the `_app` dir
- Updated the Heading block in Storyblok to allow the balancer to be toggled. 
- If we decide to use react-wrap-balancer more around the app we'd probably want to use a provider to share the balancing script with all the components. 
- If we start using server components there are some optimisations available as well.
**(Note the 'balance' option in the bottom right of the screenshots)**
Adding the balancer to every heading component caused issues with some of the headings around the app. [Check out this thread from slack](https://hedviginsurance.slack.com/archives/G01MARCFUUW/p1676966424962669)
(screenshot of the …
> Make balancing the header optional

- apps/store/README.md
- apps/store/src/services/apollo/apollo.helpers.ts
- apps/store/src/services/apollo/client.ts
- apps/store/src/services/authApi/persist.ts
- apps/store/src/services/persister/ServerCookiePersister.ts
- apps/store/src/services/shopSession/ShopSession.helpers.ts
- apps/store/src/utils/types.ts
- Add header to all apollo client requests with shop session ID
- Update README with information about HTTP headers
- Make `CookieParams` a global app type
We want this to make it simpler to debug things in the backend/API.
> Add header for shop session id to apollo client

- apps/store/src/blocks/InsurableLimitsBlock.tsx
- apps/store/src/components/GridLayout/GridLayout.tsx
- apps/store/src/components/InsurableLimits/InsurableLimits.tsx
- packages/ui/src/components/HeadingLabel/HeadingLabel.tsx
- Simplify InsurableLimits design
- Add `thirdLeftStyles` to `GridLayout`
[Figma](https://www.figma.com/file/8SfzuQEJ4LJ6uKL0l7WKoE/Hedvig.com-%C2%B7-Final-Design?node-id=4034%3A29573&t=x1Tnaq6QQ69SsBL5-1)
Updated design from Zak, old design was too complex (I agree).
> Update Insurable Limits block design

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/blocks/ProductPageBlock/DesktopLayout.tsx
- apps/store/src/blocks/ProductPageBlock/MobileLayout.tsx
- apps/store/src/blocks/ProductPageBlock/ProductPageBlock.tsx
- apps/store/src/blocks/ProductPageBlock/ProductPageBlockBase.tsx
- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- Make top menu static on PDP pages
- Remove header animation on PDP pages
- Tweak tabs and top content on PDP pages
> :warning: easiest to try out in the preview deployment
Requested from design -- menu takes up too much vertical space on PDP pages.
> Make top menu static on PDP

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/blocks/ProductPageBlock/MobileLayout.tsx
- apps/store/src/blocks/TabsBlock.tsx
- apps/store/src/components/GridLayout/GridLayout.tsx
* Update TabsBlock to match latest designs and support [Support page implementation](https://www.figma.com/file/qUhLjrKl98PAzHov9ilaDH/*NEW*-.com-UI-Kit?node-id=1565%3A7541&t=NWIjsInKHcoEsoQf-4)
**Disclaimer**: Only the vertical Layout was implemented for now. We can iterate over it later
Can be tested [here](https://hedvig-dot-com-git-grw-2271-refacttabs-block-hedvig.vercel.app/se/hjalp/support-link-card)
[GRW-2271]: https://hedvig.atlassian.net/browse/GRW-2271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2271 - refact(TabsBlock): updated to match latest designs

- apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts
- apps/store/src/components/ProductPage/PriceIntentContext.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Refactor `PriceIntentContext` to use active instead of lazy query.
Separate functions:
- Use `useEffect` to setup initial price intent on page load
- Add new function to create new price intent (post add to cart). This just resets cookie and refreshes the page.
We have a bug where we keep the existing price intent after adding to cart.
This has to do with not resetting the cookie because we don't refresh the page after calling "clear" on the price intent service.
I think this setup is slightly more standard and easier to understand.
> Fix issue when creating new price intent (post add to cart)

- apps/store/src/components/TextField/TextField.tsx
Change size of large text field to 72px height
Keep label with secondary text color
Design review
> TextField: change large size/height to 72px

- apps/store/src/components/TextField/TextField.tsx
Allow user to click anywhere in the text field wrapper to focus the input field.
It's generally a bad idea to attach `onClick` to divs but in this case it's just a nice feature for sighted users so we don't need to worry about accessibility I believe.
> `TextField`: allow clicking wrapper to focus input

- apps/store/src/blocks/ProductCardBlock.tsx
Hide Get a Price button for product cards leading to CMS pages like "Home"
We cannot get a price unless target page is "real" product page, not a CMS page for some product group
> Only show Get a Price button for leaf product pages

- apps/store/src/components/CartInventory/CampaignsSection.tsx
- apps/store/src/components/TextField/TextField.tsx
- Fix delete button on Safari by not using `display: none`
- Only run warning animation 1 time (instead of 2)
- Fix label color warning animation
- Make campaign code input required
Safari doesn't like setting display to none on a button. It seems like it just doesn't register the event handlers. Instead I just show/hide the button with opacity which I think works fine. Let me know if you think there are some accessibility issues with this.
> Fix various text field bugs

- apps/store/src/blocks/HeadingBlock.tsx
- apps/store/src/blocks/TextContentBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
Put `nested` prop outside Storyblok data
When using blocks inside other blocks, we don't want to render any padding (meaning no need for a `Wrapper`). So instead of overriding with nested CSS, exporting Wrapper from every component, I'm leaning towards the `ConditionalWrapper` pattern that we can reuse across blocks.
> Put nested prop outside of Storyblok data

- apps/store/src/components/Perils/Perils.stories.tsx
- apps/store/src/components/Perils/Perils.tsx
**The issue**
The Perils grid would push other perils down when expanded because the grid was creating additional rows that would get pushed down.
**My solution**
Decided to create arrays of perils. Each representing a column in the grid. This way each column can expand down without pushing others down. 
**Tradeoffs**
one thing we lose here is when there are 2 or 3 perils they fill the width of the container rather than taking of 1/4th of the container each. Looking around the app it seems like we don't really have any situations where we only show < 4 perils so perhaps not an issue. 
https://user-images.githubusercontent.com/50870173/221164612-08609e32-f38f-4759-bca6-47a32f17fc72.mov
https://user-images.githubusercontent.com/50870173/221165526-fbe890ad-f221-43b2-9196-e10f1c0556d9.mov …
> PerilGrid refactor

- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/blocks/HeadingBlock.tsx
- apps/store/src/blocks/ImageBlock.tsx
- apps/store/src/blocks/ImageTextBlock.tsx
* Update `ImageTextBlock` so it leverages an `ImageBlock` to get an image rendered;
* General updates: Export _wrapper_ components defined inside `ButtonBlock`, `HeadingBlock` and `ImageBlock` components so I can use then to override spacing related styles (E.g: padding) while rendering those blocks inside an `ImageTextBlock`. Due to cycle dependencies, I couldn't achieve the same by doing the inverse as we've done in some places in the codebase; That would mean, import parent container inside children and use it to get children's styles overridden.
What _design team_ requested was a way for editors to configure `ImageTextBlock`'s image aspect ratios based on screen orientation - something that's already supported by `ImageBlock`. So instead of updating `ImageTextBlock` to receive the …
> GRW-2289 - refact(ImageTextBlock): leverage ImageBlock for image rendering

- apps/store/src/blocks/ImageTextBlock.tsx
* Updated `ImageTextBlock`'s `image` field so instead of taking in a _Image Asset_ it takes in an `Image` block
This is part of enabling image format configuration for `ImageTextBlock` - like aspect ratio - as we have for `ImageBlock`
**Before**
**After**
https://github.com/HedvigInsurance/racoon/pull/1754
[GRW-2289]: https://hedvig.atlassian.net/browse/GRW-2289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2289 - refact(ImageTextBlock): updated image field

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/ScrollToButton/ScrollToButton.stories.tsx
- apps/store/src/components/ProductPage/ScrollToButton/ScrollToButton.tsx
Update quick "add to cart" button on the footer of PDP page (mobile only)
Scroll all the way to the top of the page when clicking on the "add to cart" button
Before it just scrolled to the main "add to cart" button, which looks a bit weird.
> Quick add to cart: scroll to top of page

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/services/storyblok/storyblok.ts
- Make top menu item clickable (links to store page)
- Remove "försäkringar" heading from product navigation section
- Render product navigation section outside menu item so it never closes
I couldn't figure out a way to avoid using "useBreakpoint". The more I work with this component, the more I think we should separate it into two components. One for mobile and one for desktop. It's getting too complicated.
Perhaps we can do that as a mob programming session?
> Various menu tweaks

- apps/store/src/blocks/TextContentBlock.tsx
- apps/store/src/components/GridLayout/GridLayout.helper.tsx
- apps/store/src/components/GridLayout/GridLayout.tsx
- Add a plugin that sets how many columns a block should span at different breakpoints and how it should align
- Extend GridLayout to take an array of widths 
- Add Layout options to TextBlock 
https://user-images.githubusercontent.com/6661511/221601809-556b30d0-8712-43ef-8281-ffbcd343d538.mov
Next step:
- Refactor usage of GridLayout so we can get rid of `STYLES` object
- Move plugin code inside repository (post launch)
We want the flexibility to set content widths from Storyblok. We will start with TextContent block and then see what more blocks that we will add it to.
> Create Storyblok plugin for column settings

- apps/store/src/blocks/ImageTextBlock.tsx
Make sure image field of object type doesn't break the page
Issue in datadog: https://app.datadoghq.eu/rum/error-tracking/issue/406e6a8c-b6b9-11ed-bd7e-da7ad0900005?query=%40application.id%3Ad86e86d8-8d9a-4b00-a2cb-10b8d7671fa2&from_ts=1677487249796&start=1677488486454&end=1677574885540&to_ts=1677573649517&live=true&paused=false
While working on the cache issue this could mitigate the error on the page hopefully
> Make sure image field of object type doesn't break the page

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Remount `PriceCalculator` when switching between PDPs.
We need to clear state when switching between PDPs.
We have a bug when you switch between PDP and the price calculator is stuck on a step that doesn't exist for the new PDP.
> Refresh price calculator when switching PDP

- apps/store/package.json
- apps/store/src/services/apollo/client.ts
- yarn.lock
Add 50s timeout to ApolloClient requesta
We want to crash with useful stacktrace if some request takes too long.  Hitting 60s will lead to Vercel function timeout without any debugging info
> Enforce timeout on Apollo requests with ApolloLinkTimeout

- apps/store/src/components/Pillow/Pillow.tsx
Set Pillow image size to largest possible size to avoid blurry image. FIle sizes is still very small
Size was set to 80x80, but largest size option is 208x208 so it sometimes rendered a blurry Pillow image
> Set Pillow image size to largest possible size to avoid blurry image

- apps/store/src/blocks/PerilsBlock.tsx
- apps/store/src/components/Perils/Perils.tsx
Integrate grid layout in perils block.
Fix an issue where perils block doesn't have the same max width as rest of blocks.
> Add grid layout to perils block

- packages/ui/src/lib/globalStyles.ts
When lazy loading images, safari displays a gray border. Known bug referenced in Next.js doc:
https://nextjs.org/docs/api-reference/next/image#known-browser-bugs
> Remove gray border on lazy loading images

- apps/store/src/components/ContactSupport/IntercomChatButton.tsx
Refactored the intercom button to allow it to be lazy loaded. 
Intercom is now loaded after the user clicks on the support button.
Allow the user to click the button to open and close the intercom window.
since we're loading the scrips onclick we may want to have a loading state for this component
Intercom is hurting our page performance and should only be loaded when the user needs it.
When testing this component (sometimes) there is now a while flash the first time the user clicks on the button to open intercom. I tried several ways to fix this but could not get it sorted.
> Intercom - lazy loading 🐡

- apps/store/src/blocks/BannerBlock.tsx
- apps/store/src/blocks/HeroBlock.tsx
- apps/store/src/blocks/ImageBlock.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ImageWithPlaceholder/ImageWithPlaceholder.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
- apps/store/src/components/TopPickCard/TopPickCard.tsx
Show gray placeholder while loading images.
Tested with adding a blurDataURL with a simple gray image but it automatically adds filter blur which looks weird.
So easier to add a background color, but since images can have alpha layers (opacity) we should remove the background color after the image is loaded.
You can test in [preview app](https://hedvig-dot-8wufb0tih-hedvig.vercel.app/se) by using network throttling 
https://user-images.githubusercontent.com/6661511/222730364-fb4368cf-d439-4ff0-b0c3-db62c6c37cb7.mov
Should show a placeholder when loading takes a long time.
> Add gray placeholder while loading images

- apps/store/src/components/Perils/Perils.tsx
tl;dr: There are about a 100px where the cols were borked!
Between specific breakpoints the perils minWidth was too large for them to break out into their proper columns. 
The changes in this PR are to make their minWidth a bit smaller to fix this.
> fix: peril columns bug 🐞

- apps/store/next-csp.config.js
- update csp rules
- removed `https://js.intercomcdn.com` from scripts to see if it's actually being used there. I think it was misconfigured from the beginning.
> update csp rules

- apps/store/src/blocks/ImageBlock.tsx
Add option to set loading priority to Storyblok
Fix LCP warning from Lighthouse. Images rendered above the fold should be loaded with priority.
> Add priority loading option to Imageblock

- apps/store/src/components/Video/Video.tsx
Lazy load autoplaying videos
To do this we add the video src to a  `data-src` attribute, observe when it enters the viewport and then load the video.
Review app: https://hedvig-dot-gb1pjdijv-hedvig.vercel.app/se
**16.9 MB transferred** 🐌
**66 kB transferred** 🚀
Possible improvement:
We treat autoplaying videos above fold the same (like the product pages). It loads slightly slower but barely noticeable. Let's see if we want to add similar functionality as images for above the fold media to preload the video instead.
Since the `autoplay` attribute on videos override the `preload` attribute, we fetch all autoplaying videos on page load.
> GRW-2275 / Lazy load autoplaying videos

- apps/store/src/blocks/ProductPageBlock.tsx
- apps/store/src/blocks/ProductVariantSelectorBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
* Promote `ProductVariantSelect` as its own block
**Disclaimer**: **This PR should not be merged while we don't get all PDP pages updated**.
To support the implementation of new design for _variant selector_ section.
By having only the input select as a block we can use it to compound the the attached design while making it easy to implement _sticky variant selector_ feature.
Can be tested [here](https://hedvig-dot-com-git-grw-2284-refactproduct-variant-7bd542-hedvig.vercel.app/se/forsakringar/bilforsakring/bill-sandbox)
https://user-images.githubusercontent.com/19200662/223766061-512221d9-b470-4a63-a82a-c9bf2bb98269.mov
[GRW-2284]: https://hedvig.atlassian.net/browse/GRW-2284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2284 - add ProductVariantSelectorBlock

- apps/store/package.json
- apps/store/src/components/Combobox/Combobox.stories.tsx
- apps/store/src/components/Combobox/Combobox.tsx
- yarn.lock
Add combobox component (autocomplete).
This will be needed for breed selector to launch PET.
Based on downshift lib. We don't want to implement all the accessibility stuff ourselves.
I investigated Radix but they don't offer a combobox so we would have to do a lot of wiring ourselves. I also tried out Reach UI but it wasn't working 100% they way we wanted. It has has also not been updated in 6 months which is a red flag.
> Add combobox component based on downshift

- apps/store/src/components/InputDate/InputDate.tsx
- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
Use a shared date input component for both purchase form and cancellation form.
Replace the old date input with the new one.
> Update date input component in purchase form

- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/components/ButtonNextLink.tsx
- apps/store/src/services/storyblok/storyblok.ts
* Updates `ButtonBlock` so it supports _open in new window_ storyblok feature
[GRW-2346]: https://hedvig.atlassian.net/browse/GRW-2346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2346 - feat(Button): support 'open in new window' storyblok feature

- apps/store/src/blocks/FooterBlock.tsx
Handles a warning that advises use :first-of-type instead of :first-child 
It seems the order `<style>` tags gets added in the document can affect `:first-child` selectors. That's why `:first-of-type` is referred as a better replacement.
> chore: replace :first-child --> :first-of-type

- apps/store/src/components/TextField/TextField.tsx
Fix 2 React warnings from TextField
- Do not pass onValueChange to DOM
- Do not pass defaultValue since we're using fully controlled component
> Fix TextField warnings

- apps/store/src/blocks/RichTextBlock/RichTextBlock.styles.tsx
- apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
Add new block for longer chunks of text/pages with predefined styles.
[Preview app](https://hedvig-dot-o3reb1df9-hedvig.vercel.app/api/preview?secret=DWafxGrY6M8&slug=se/hedvig/legal-information-copy&_storyblok=266110806&_storyblok_c=page&_storyblok_version=&_storyblok_lang=default&_storyblok_release=0&_storyblok_rl=1678891810691&_storyblok_tk[space_id]=165473&_storyblok_tk[timestamp]=1678891415&_storyblok_tk[token]=016430787dc350c3b8f437003cb8f04bcf62fffd)
https://user-images.githubusercontent.com/6661511/225349859-23702727-7a22-40e5-b640-3c7c468433d1.mov
Easier to add longer chunks of content for editors
> Add RichTextBlock

- apps/store/src/blocks/RichTextBlock/RichTextBlock.styles.tsx
- apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx
- Compose styles a bit cleaner
- Add inline link styling
This styling will be used in more places. So I figure we can import it to whatever blocks/components that need it rather than making it a global style
https://user-images.githubusercontent.com/6661511/225369402-c0ca10bd-f1e9-4319-acf7-5fa1c4f575ae.mov
Highlight links in text
> Add inline link styles to RichText

- apps/store/src/components/Combobox/Combobox.stories.tsx
- apps/store/src/components/Combobox/Combobox.tsx
* Solve an issue where wrong item gets selected with keyboard navigation. Check the video below:
https://user-images.githubusercontent.com/19200662/225616676-b099f9f8-a1d5-45ad-b782-9e9f22c579e1.mov
Basically what is happening is, if we don't update the list of items provided to `useCombobox` with a filtered list based on `inputValue` it will be possible to "navigate" through the whole list with keyboard even though we can't see it. In the video the list is filtered to an single item but I've hit ArrowDow 3 times and then [Enter] which allowed me to select the third item of the list: _Banana_.
* Add a custom behaviour where an item gets selected with [Enter] when there's only one available for selection
* Set `selecteddItem` as `null` when clearing the input - backspace or _clear input_ …
> GRW-2355 - feat(Combobox): solve some issues and make some improvements

- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/InputRadio.tsx
- apps/store/src/services/PriceCalculator/Field.types.ts
- apps/store/src/services/PriceCalculator/data/SE_PET_CAT.ts
- apps/store/src/services/PriceCalculator/data/SE_PET_DOG.ts
Add option to stack radio group input horizontally (without showing the label).
Needed for pet gender field.
Only supports two options (design).
Only supports horizontal option - let's add vertical stacking when we need it.
> Add horizontal stacking option to radio input

- apps/store/src/components/ProductPage/PurchaseForm/DeductibleSelector.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/graphql/ProductOfferFragment.graphql
Add deductible selector to the offer presenter.
Refactor offer presenter to keep track of selected offer rather than selected type of contract.
Infer tiers and deductibles from the API.
Update deductible selector and log if we get unexpected data from API.
Support for pet insurance.
> Integrate deductibles from API

- apps/store/src/components/PriceCalculator/SsnSeSection.tsx
- apps/store/src/services/apollo/client.ts
Reset auth tokens when resetting session after wanting to change SSN.
Otherwise we just create a new *authenticated* shop session so it retains the same SSN 🙃.
> Reset auth when resetting session

- apps/store/src/blocks/ProductPageBlock.tsx
- apps/store/src/components/Header/Header.tsx
- Lock the scroll position of purchase form so it never scrolls with the rest of the content.
- Remove the top padding of the PDP video.
UI improvements from Wille.
> Lock scroll position for purchase form

- apps/store/src/blocks/ProductPillowsBlock/ProductPillowBlock.tsx
- apps/store/src/blocks/ProductPillowsBlock/ProductPillowsBlock.tsx
- apps/store/src/components/ProductPillow/ProductPillow.stories.tsx
- apps/store/src/components/ProductPillow/ProductPillow.tsx
- apps/store/src/services/storyblok/storyblok.ts
Add new block for displaying Pillow navigation
I'm thinking if we should get the product metadata directly from Storyblok so we could statically generate it instead of `useProductMetadata`. I'm thinking if that could get rid of the slower loading for Pillow images when you land on the page 🤔
[Review app](https://hedvig-dot-itnwpfth0-hedvig.vercel.app/api/preview?secret=DWafxGrY6M8&slug=se/forsakringar/&_storyblok=194123251&_storyblok_c=page&_storyblok_version=&_storyblok_lang=default&_storyblok_release=0&_storyblok_rl=1679329399467&_storyblok_tk[space_id]=165473&_storyblok_tk[timestamp]=1679329395&_storyblok_tk[token]=7d76fb44db374ddd26c1d1025a4520f66eef707a)
https://user-images.githubusercontent.com/6661511/226404963-c6394cc9-4122-4f6c-ae98-e448a3473644.mov
Potentially easier/faster …
> Add ProductPillow component

- apps/store/src/components/ProductPage/PriceIntentContext.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useSelectedOffer.ts
Refresh selected offer after editing price intent/offer (start date or re-confirm).
We have a bug now where you don't see the updated start date after you edit. This is because we store the selected offer in local state and don't update it after editing. This PR fixes that.
> Bug: keep track of latest selected offer on PDP

- apps/store/src/blocks/ProductPillowsBlock/ProductPillowsBlock.tsx
- apps/store/src/components/ProductPillow/ProductPillow.tsx
Horisontal scroll for ProductPillowBlock in mobile
Hide scrollbar similar to how apple.com does it
https://user-images.githubusercontent.com/6661511/226702408-942dfce6-015e-469a-a474-709aa7a98816.MP4
[Review app](https://hedvig-dot-2ok6gkvlh-hedvig.vercel.app/se/forsakringar)
William and I weren't happy with how it looked for mobile, so we did this horisontal scroll instead
> Horisontal scroll for ProductPillows

- apps/store/src/components/ContactSupport/IntercomChatButton.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useOpenPriceCalculatorQueryParam.ts
Keep `openPriceCalculator` in URL to avoid issue in production
> Workaround for openPriceCalculator query param corrupting window.location in production

- apps/store/src/components/GridLayout/GridLayout.tsx
Make grid layout take up full width of container.
We have a bug since the layout collapses with `margin-inline: auto` unless we set a 100% width.
> Make sure root layout doesn't collpase

- apps/store/src/components/CartInventory/CartEntryItem.tsx
- apps/store/src/components/CartInventory/RemoveEntryDialog.tsx
- apps/store/src/components/CartInventory/useRemoveCartEntry.ts
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
Redirect the user to the cart page if they remove the last item in the cart on the Checkout page.
This is a bug fix.
It would be nice to avoid prop-drilling. I was considering some Jotai solution but not sure how it would work. I was also considering sending some event you can subscribe to but maybe this is still the easiest.
> Redirect to cart page after removing last entry

- apps/store/src/blocks/ProductPageBlock.tsx
* Updates purchase form wrapper's max height 
https://user-images.githubusercontent.com/19200662/227301790-1b856d26-03cf-4e9d-a623-5e2017c615c2.mov
Container should not discount header's height since we scrollable container can't use that space.
Requested [here](https://hedviginsurance.slack.com/archives/C041SD67G82/p1679587742204349).
> styles(ProductPage): update purchase form wrapper's max height

- apps/store/src/components/Combobox/Combobox.tsx
- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/MixedBreedPicker/MixedBreedPicker.stories.tsx
- apps/store/src/components/PriceCalculator/MixedBreedPicker/MixedBreedPicker.tsx
- apps/store/src/components/PriceCalculator/PetCatBreedsField.tsx
- apps/store/src/components/PriceCalculator/PetDogBreedsField.tsx
- apps/store/src/components/PriceCalculator/PriceCalculatorSection.tsx
- apps/store/src/services/PriceCalculator/Field.types.ts
- apps/store/src/services/PriceCalculator/PriceCalculator.helpers.ts
* `PurchaseForm`
* Deserialize form values based on field type
*  `Pet[Cat|Dog]tBreedsField`
* Update them so `selectedBreed(s)` information keeps store in form controls: `input:hidden`
https://user-images.githubusercontent.com/19200662/227286529-7941e623-6f40-4744-befd-d5abe023a2cd.mov
For fields like `PetCatBreedsField` and `PetDogBreedsField` we don't want to make API requests every time their values are changed. A better user experience is submit them while submitting information for the whole section they are in.
[GRW-2385]: https://hedvig.atlassian.net/browse/GRW-2385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2385 - fix: Submit Pet[Cat|Dog]BreedFields info only when confirming the whole section they are in

- apps/store/src/graphql/ProductRecommendations.graphql
* Update `ProductRecommendations` Query so it also requests `shoppingSession.id`
By not doing so, we get a warning from Apollo notifying that we might be losing some shopping session data from the cache when executing `ProductRecommendations` query. That's because both `ShoppingSession` and `ProductRecommendations` queries refer to same cache object - `shoppingSession` -  but since the later wasn't including the `shoppingSession.id` all of existing `shoppingSession` cached data gets lost.
By including the id, Apollo knows that `ProductRecommendations` query means updating existing `shoppingSession` object in cache by adding a `recommendations` list into it instead of replace the whole thing.
Obs: It was working before because something in code triggers the refetch of `ShoppingSession` …
> chore(ProductRecomendations): handle cache update warning

- packages/ui/src/lib/media-query.test.ts
- packages/ui/src/lib/media-query.ts
Wrap resize callback in request animation frame.
Source: https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded/58701523#58701523
Prevent resize error:
```
ResizeObserver loop limit exceeded
```
> Avoid resize error in media query hook

- apps/store/src/components/ProductCard/ProductCard.tsx
Currently we have two links in the same ProductCard which we should avoid if possible for SEO reasons. Having the "Read more" button as the main link is also bad practise for screenreaders and SEO since it's the same on all cards.
- Make the title of the Card the main link to get a descriptive link text
- Add an `:after` element to the link to cover the card and make it clickable
- Add a focus state to "Read More" button when the main link is focused
- Navigate with router to the product page when "Read More" button is clicked
https://user-images.githubusercontent.com/6661511/229752222-35f818b8-d9aa-41a2-ba36-030989ec85b9.mov
Improve ProductCard SEO and accessibility
Good resource I found on the topic https://inclusive-components.design/cards/
> Improve ProductCard SEO and accessibility

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/blocks/AccordionItemBlock.tsx
- apps/store/src/components/Accordion/Accordion.stories.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/Perils/Perils.tsx
* Keep `AccordionContent`'s content mounted so it can be used for SEO purposes
* Replace Accordion's CSS animations with JS based animations with _framer motion_
https://user-images.githubusercontent.com/19200662/229769745-a4a49b1e-d30b-4f6e-937d-993f822d2e26.mov
As discussed [here](https://github.com/radix-ui/primitives/discussions/1481) the purpose of `forceMount` is to hand over lifecycle to javascript animations libraries. By using it, we solve the SEO issue but as consequence radix built in animation handler will not properly work. With that said, I've replaced the CSS animations with framer motion ones so we can have both. 
[GRW-2420]: https://hedvig.atlassian.net/browse/GRW-2420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2420 - feat(AccordionContent): keep content mounted for SEO purposes

- apps/store/src/blocks/RichTextBlock/RichTextBlock.styles.tsx
Use native underline decoration. Didn't know you could tweak the offset and other settings 🙏
Use `clamp` to make line height a dynamic value between 1px and 2px depending on `font-size`
https://user-images.githubusercontent.com/6661511/230182295-18eccc1c-d022-460e-b86a-a3ac81b577fd.mov
Underline styling was broken when a link spanned over multiple lines.
> Fix broken link decoration

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
See title ☝🏻 
https://user-images.githubusercontent.com/19200662/230374196-838665a6-ff73-437c-a04b-61b5748e2746.mov
Before the following was happening:
https://user-images.githubusercontent.com/19200662/230374060-07a58d0f-3d88-484d-b0ee-7eea2bf4814b.mov
> fix(PurchaseForm): make sure full screen purchase form don't override eventual error dialogs

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/usePurchaseFormState.ts
* Display ApolloError messages while trying to confirm _PriceIntent_
Better guide user on what's going on.
[GRW-2432]: https://hedvig.atlassian.net/browse/GRW-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2432 - feat(PurchaseForm): display error messages form API

- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
1. Only show "inavlid renewal message" if user has requested switching
1. Show regular "start date label" along with "invalid renewal message"
Feedback from Peter.
[GRW-2437]: https://hedvig.atlassian.net/browse/GRW-2437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update BankSignering flow with small tweaks

- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
* Make sure _ProductRecommendations_ query gets refetched after adding a product into the cart.
_ProductRecommendations_ query doesn't get refetched when a product get's added into the cart, which makes Cart Page product recommendations list be built with stale data - the famous cache invalidation issue. One can reproduce it by following the steps described in the video below:
https://user-images.githubusercontent.com/19200662/231446212-4a6e1af3-0726-4bb2-8e54-bce580e47d36.mov
As one might notice, we have code in place with the function of refetching that list when cart gets mutated [adding](https://github.com/HedvigInsurance/racoon/blob/main/apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts#L17)/[removing](https://github.com/HedvigInsurance/racoon/blob/main/ap …
> GRW-2440 - fix(useHandleSubmitAddToCart): refetch recommendations after adding a poduct into cart

- apps/store/codegen.yml
- apps/store/src/components/ProductRecommendationList/useProductRecommendations.ts
Treat UUID scalar as string on graphql types generation.
Then we don't need to cast `shoppingSession.id` type from `any` into `string`
> chore(codegen): treate UUID scalar as string

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Update to show the selected offer in tier selector instead of lowest price option.
Reported as bug when the price doesn't match between tier selector and deductible selector.
> Show correct price for selected offer in tier selector

- apps/store/src/graphql/ShopSessionCreate.graphql
- apps/store/src/pages/api/redirect/recommend.ts
Alternative approach to setting attributed_to - make a special API route to force session creation
More stable solution than relying on query param when starting the app (https://github.com/HedvigInsurance/racoon/pull/2151?no-redirect=1)
> Add /api/redriect/recommend route to force session creation with given attributed_to value

- apps/store/src/components/CartInventory/CampaignsSection.tsx
Add animation when expanding and collapsing the campaign section.
Checkout the preview app.
Testing it out with designers.
> Add reveal animation for campaign section

- apps/store/src/graphql/ShopSessionCreate.graphql
- apps/store/src/pages/api/redirect/recommend.ts
Allow initiated_from to be specificed the same way as attributed_to, so we can do things like
- initiated_from=CROSS_SELL for app cross-sell
- attributed_to=BENIFY for partners
- no use cases for both at the same time, but I allow it to do less work
Properly support car cross-sales with relaxed pricing guidelines in Eir
> Allow initiated_from to be specified via /api/redirect/recommend

- apps/store/.storybook/main.ts
- apps/store/.storybook/preview.tsx
- apps/store/package.json
- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.stories.tsx
- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
- yarn.lock
Add Storybook [Apollo addon](https://storybook.js.org/addons/storybook-addon-apollo-client). This way we can create stories for components thats dependent on Apollo and mock data.
In this case I added a story for `CartEntryItem` with the remove button. 
https://user-images.githubusercontent.com/6661511/232733701-c2ccd788-4ad2-4bc0-9e99-0a0bedd3a898.mov
To enable us to build components in isolation that's dependent on Apollo
> Add Storybook Apollo addon

- apps/store/src/components/SelectInsuranceGrid/ProductItem.tsx
- apps/store/src/components/SelectInsuranceGrid/SelectInsuranceGrid.stories.tsx
- apps/store/src/components/SelectInsuranceGrid/SelectInsuranceGrid.tsx
- Add basic Select Insurance Grid component
- Will be used for `Select Insurance Overlay` block
> Add basic select insurance grid component

- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
- Remove extra padding from `CartEntryItem` in read-only mode
- Refactor layout a bit to reduce some complexity
- The extra padding was causing the `CartEntryItem` to be too tall in read-only mode
> Remove extra padding in `CartEntryItem`

- apps/store/src/utils/PageLink.ts
Went through this the other day. It seems not to be used anywhere but it was wrong before since we don't have `api/campaign/add/<code>` api route.
> fix: campaign api route

- apps/store/src/components/PriceCalculator/Accordion.tsx
- apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
- apps/store/src/components/PriceCalculator/PriceCalculatorAccordionSection.tsx
- apps/store/src/services/PriceCalculator/PriceCalculator.types.ts
- apps/store/src/services/PriceCalculator/data/SE_ACCIDENT.ts
- apps/store/src/services/PriceCalculator/data/SE_CAR.ts
- apps/store/src/services/PriceCalculator/data/SE_HOUSE.ts
- apps/store/src/services/PriceCalculator/data/SE_PET_CAT.ts
- apps/store/src/services/PriceCalculator/data/SE_PET_DOG.ts
- apps/store/src/services/PriceCalculator/formFragments.ts
Add support to show a preview label for each completed section in the price calculator.
Refactor the price calculator accordion slightly.
Improve UX, especially when user needs to edit things about the price intent.
Just supports a single preview label for now. Let's discuss if we should support multiple labels in the future. Another discussion would be if we should move the form template to the backend.
> Show preview in price calculator sections

- apps/store/src/blocks/ImageTextBlock.tsx
- apps/store/src/blocks/QuickPurchaseBlock.tsx
- apps/store/src/components/QuickPurchaseForm/ProductSelector.tsx
- apps/store/src/components/QuickPurchaseForm/QuickPurchaseForm.tsx
* Update `ImageTextBlock` so it became possible to configure horizontal alignment for its body content. This is intended to be used with `QuickPurchaseBlock`
[GRW-2444]: https://hedvig.atlassian.net/browse/GRW-2444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2444  - feat(ImageTextBlock): better integrate with QuickPurchaseBlock

- apps/store/src/components/CartInventory/CartEntryOfferItem.tsx
- Store whether to show cart offer in global jotai atom
[Screen Recording 2023-04-26 at 16.23.44.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/0aea08ca-1aeb-4d8d-9f00-4375f6e1d8dc/Screen%20Recording%202023-04-26%20at%2016.23.44.mov)
- Remember to hide cart offer in cart/checkout after user has dismissed it. Right now you can dismiss it and then it appears after navigating to the checkout page.
- This solution only supports hiding none/all cart offers, not individual ones. When we support that we can come up with a more robust solution perhaps.
> Remember to hide cart offer after user dismisses it

- apps/store/src/blocks/ReusableBlockReference.tsx
See thread here https://hedviginsurance.slack.com/archives/G01MARCFUUW/p1682600497217479
Quick solution proposed by @alebedev 
Couldn't update the `ReusableStory` type since that would cause this error:
```
Property 'content' is optional in type 'ReusableStory' but required in type 
'ISbStoryData<(ISbComponentType<string> & { [index: string]: any; } & { body: SbBlokData[]; }) | undefined>'.
```
This fixes the error in the browser. But the cause is when you edit something on a page in storyblok and enter preview mode, the content from reusable blocks disappear. So I wonder if we need to resolve relations properly when entering preview mode 🧐  https://www.storyblok.com/tp/using-relationship-resolving-to-include-other-content-entries#using-the-storyblok-bridge
Crashes storyblok when editing …
> Update type to catch undefined reusable stories

- apps/store/src/blocks/ContentBlock.tsx
Adds a property to `ContentBlock` where editors could configure the heading level. `h2` will be the one used in case none is provided.
It's necessary for the full merge of hedvig-dot-com.
> feat(ContentBlock): add support for heading level

- .github/PULL_REQUEST_TEMPLATE.md
Disclaimer: Maybe we don't need to get this merged now. We can wait until we actually "pull the plug".
Removes 'Jira Ticket' section from PR Template
We're moving away from Jira.
> chore(pr-template): removes 'Jira Ticket' section.

- apps/onboarding/next.config.js
Include asset prefix for next/image URLs
The global asset prefix doesn't automatically apply to "next/image"
> Include asset prefix for next/image URLs

- apps/store/src/components/ContactSupport/ContactSupport.stories.tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
See title.
1. This should be more accurate than simply falling back to `/`, right?
2. I'm not sure why we are not seeing getting the link in the first place 🤔 we should ask Storyblok so we make sure we understand it correctly.
> Fallback to cached_url if linked story is missing

- apps/store/src/components/GridLayout/GridLayout.helper.tsx
If you pick full width on a larger breakpoint after defining a smaller one, it wouldn't work since we just return an empty object
> Make sure full width works on larger breakpoints

- apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
Subj
SEO fix required for site merge.  Peter should be able to setup alternates without exposing them to users until we're ready to launch English
> Hide English alternate links when ENGLISH_LANGUAGE flag is disabled

- apps/store/src/blocks/GridBlock.tsx
- apps/store/src/blocks/ImageTextBlock.tsx
- apps/store/src/components/GridLayout/GridLayout.helper.tsx
- apps/store/src/services/storyblok/storyblok.ts
A block where you can add a number of blocks in a grid/column layout. 
To start with only ImageTextBlock. 
The layout is defined based on how many items you add to the grid and you can set the max width on the wrapper with the layout settings in Storyblok
[Review app](https://hedvig-dot-com-git-feat-add-grid-block-hedvig.vercel.app/api/preview?secret=DWafxGrY6M8&slug=se/hedvig/legal-information-copy&_storyblok=266110806&_storyblok_c=page&_storyblok_version=&_storyblok_lang=default&_storyblok_release=0&_storyblok_rl=1683276629798&_storyblok_tk[space_id]=165473&_storyblok_tk[timestamp]=1683276629&_storyblok_tk[token]=41ef9b590ea7ddeca679f9b6c3f313d76654e5c1)
https://user-images.githubusercontent.com/6661511/236397454-9e284a29-38d1-4faa-b16c-29a7f0f5ec2e.mov
Needed for hedvig.com to go live
> Add GridBlock component 

- apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
- apps/store/src/pages/checkout/[shopSessionId]/payment/[status].tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/trustly.tsx
- apps/store/src/pages/checkout/[shopSessionId]/switching-assistant.tsx
- apps/store/src/pages/checkout/index.tsx
Ensure we don't redirect payment success -> payment connection when storefront returns unexpected authenticationStatus
This is a workaround for production issue.  Proper fix would involve not relying on shopSession after signing and using shopSessionOutcome instead
> Prevent payment success -> connect payment redirect

- apps/store/src/middleware.ts
- Set 308 status (permanent) for fallback redirect
- Remove SE geo redirect and use the fallback redirect instead (input from Peter)
Default is 307. Needed for crawlers to properly index /se
> Set 308 status on root redirect

- apps/store/src/blocks/AccordionBlock.tsx
Avoid structured data script being rendered twice in <head>. There's seem to be a bug with next/head since it should [not render duplicates if you add a key prop](https://nextjs.org/docs/pages/api-reference/components/head#:~:text=To%20avoid%20duplicate,the%20following%20example%3A)
Seems to be an hydration issue so this makes sure it's only rendered once, validated with [Rich Result Test](https://search.google.com/test/rich-results/result?id=NtRRH13hlxCG3pPyGxsCFg)
Warning from Google Search Console that content is duplicated
> Fix duplicated strucutred data

- apps/store/src/pages/manypets/migration/[shopSessionId].tsx
Reset auth tokens on  Manypets migration page to ensure we sign new member, instead of possibly different member based on previous token
As a side effect, reloading the page will clear token from that same page, but we can probably live with ti
> Reset any previous authToken on Manypets migration page

- apps/store/src/pages/_app.tsx
- apps/store/src/utils/l10n/useForceHtmlLangAttribute.ts
Override i18next html lang to correct format
Since i18next automatically sets html lang based on the locales in `next-i18next.config` (and those are not in the correct format), we need to listen for that change and override the value
> Override i18next html lang to correct format

- apps/store/src/blocks/ManyPetsMigrationPageBlock.tsx
- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- apps/store/src/pages/manypets/[[...slug]].tsx
- apps/store/src/pages/manypets/migration/[shopSessionId].tsx
- apps/store/src/services/storyblok/storyblok.ts
Enables Storyblok preview for Manypets migration page by:
* Adding a block por _Manypets Migtation Page_ Content Type --> `ManyPetsMigrationPageBlock`
* Make sure `migration/[shopSessionId]` and `ManyPetsMigrationPageBlock` renders the same component: `ManyPetsMigrationPage`
Additionally I've also changed `migration/[[...slug]]` file so it supports translations.
Enabling editors to construct the migration will make us move faster and avoid back and forth when it comes about design tweaks.
> feat: enable Storyblok preview for Manypets Migration Page content type

- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
* Does not throw an Error in case shopsession is not available on `ManyPetsMigrationPage`
So we can preview that page on Storyblok and enable editors to build the stack segments of that page.
> fix(ManyPetsMigrationPage): removes dependency on shopsession

- apps/store/src/services/manypets/data/SE_PET_INSURANCE_COMPARISON_TABLE.ts
* Updates Pet Insurance Comparison Table template
* 'Livförsäkring' and 'Tidigare besvär”' attributes should only be displayed when they are present and equals `true`
> fix(pet-insurance-comparison-table): only display 'Livförsäkring' and 'Tidigare besvär”' attributes when they are present and equals true

- apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
- apps/store/src/components/ConfirmationPage/ContractCard.tsx
- apps/store/src/components/ConfirmationPage/SwitchingAssistantSection.tsx
- apps/store/src/components/ConfirmationPage/useSwitchingContracts.ts
- apps/store/src/components/SwitchingAssistantPage/SwitchingAssistantPage.tsx
- apps/store/src/graphql/ShopSessionOutcome.graphql
- apps/store/src/pages/checkout/[shopSessionId]/switching-assistant.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/services/shopSession/ShopSessionService.ts
- apps/store/src/services/storyblok/storyblok.ts
- Move switching assistant module to the confirmation page.
- Skip "switching assistant" step during checkout flow.
- Updates from design.
- I didn't remove all of the code related to switching assistant page in this PR to make it easier to revert if needed.
- I haven't been able to test it out end-2-end since I don't have a car 😛
> Move switching assistant to confirmation page

- apps/store/src/middleware.ts
Use exact path for Edge config redirects
For these types of redirects it makes more sense to use exact paths
An example:
We want `/se-en/forever` to redirect to `se-en/hedvig/discount` but not catch `/se-en/forever/[code]`
Make it easier to add custom redirects in Edge Config. If we want to use wildcard redirects it makes more sense to put it in next config
> Use exact path for Edge config redirects

- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
- apps/store/src/components/CartInventory/CartEntryItem/ShortSummary.tsx
Added product based short summary for cant entries. At the moment, we only show additional information for pet offers.
To match designs. It should also help migrating people to immediately see that their pet data is correct
> feat(CartEntry): added product based short summary

- apps/store/public/locales/en/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/components/PaymentConnectPage/ErrorDialog.tsx
- apps/store/src/components/PaymentConnectPage/IdleState.tsx
- apps/store/src/components/PaymentConnectPage/Layout.tsx
- apps/store/src/components/PaymentConnectPage/ReadyState.tsx
- apps/store/src/components/PaymentConnectPage/SuccessState.tsx
- apps/store/src/pages/payment/connect.tsx
- apps/store/src/services/trustly/TrustlyIframe.tsx
- apps/store/src/services/trustly/createTrustlyUrl.ts
Update payment connect page to require user to explicitly initiate the flow.
This makes it safe to send the payment link and for users to load the page any number of times. The authorization code is not used up until the user initiates the flow.
I'm not really sure what the design of the page should look like.
I'm not really sure if we should use a query parameter or a path parameter for the authorization code.
> Payment Connect: make it safe to reload page

- apps/store/src/utils/useFormatter.ts
Use same date format in CartEntry - summary and details sheet
> feat(CartEntry): use same date format in CartEntry - summary and detaisl sheet

- apps/store/src/components/ManyPetsMigrationPage/LatestAdoptionNote.tsx
- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- apps/store/src/components/ManyPetsMigrationPage/ManypetsLogo.tsx
- apps/store/src/components/ProductPage/PurchaseForm/ComparisonTable/ComparisonTable.tsx
- apps/store/src/services/manypets/data/SE_PET_INSURANCE_COMPARISON_TABLE.ts
Improve _ComparisonTable_ design.
To match designs.
> styles(ComparisonTable): general updates for beter UI

- apps/store/src/pages/api/campaign/[code].ts
- apps/store/src/pages/api/redirect/recommend.ts
- apps/store/src/utils/getPathnameFromUrl.ts
Support passing absolute URLs in the "next" query parameter.
This will be used by AdTraction for affiliate links.
We will still not allow any next redirects to go to a different domain than the current one.
> [GEN-226] Support absolute URLs for the 'next' query param

- apps/store/src/blocks/QuickPurchaseBlock.tsx
- apps/store/src/components/QuickPurchaseForm/ProductSelector.tsx
- apps/store/src/components/QuickPurchaseForm/QuickPurchaseForm.tsx
* Renders a hidden input for `productName` when only one product is available;
By design, we shouldn't render product selector when only one option for product is available. However we still to render an input for it to be able to get that value while submitting the form.
> fix(QuickPurchaseForm): hidden input for product name where only one product is available

- apps/store/src/blocks/QuickPurchaseBlock.tsx
- apps/store/src/components/QuickPurchaseForm/ProductSelector.tsx
- apps/store/src/components/QuickPurchaseForm/QuickPurchaseForm.tsx
Don't render `ProductSelector` if no `productOptions` list is empty.
To avoid "flashing UI"
https://github.com/HedvigInsurance/racoon/assets/19200662/5c6183fc-4dda-4d92-8b5e-8d20d2d9c69d
**Disclaimer**
It will happen when more than one `productOption` is available. But adding UI pieces after something gets loaded seems less disruptive then removing it. 
https://github.com/HedvigInsurance/racoon/assets/19200662/1e23a595-ad49-4573-80b0-87eb024184a7
https://github.com/HedvigInsurance/racoon/pull/2446
> fix(QuickPurchaseForm): avoid flashing UI

- apps/store/src/components/CartInventory/CartEntryItem/DetailsSheet.tsx
'Sanitize' details sheet offer related rows by not showing rows that doesn't contain values associated with it. 
For hedvig-com created pet offers we want to display 'Boyta' (living space) row but for many pets offers we don't have that info and therefore want to hide from the table.
**Before**
**After**
> fix(DetailsSheet): sanitize rows

- apps/store/src/components/GlobalBanner/useGlobalBanner.tsx
* Make usage of SessionStorage to keep banner opened/closed state
When it comes about `atomWithStorage`:
> If not specified, the default storage implementation uses localStorage for storage/retrieval, JSON.stringify()/JSON.parse() for serialization/deserialization, and subscribes to storage events for cross-tab synchronization.
Then Peter mentioned this:
> How is the cache for closed/removed banner configured? I closed a discount banner in my browser two weeks ago. Now it never shows up again, only in incognito. Could we cache it only during the user session.
So I guess it would be better to keep that temporary state into `SessionStorage` despite the tradeoff of not having it shared between multiple tabs.
> GEN-392 - feat(GlobalBanner): make usage of SessionStorage to keep banner opened/closed state

- apps/store/src/blocks/VideoBlock.tsx
- apps/store/src/components/Video/Video.tsx
- Show video controls based on setting in Storyblok
- Fix padding in nested video block
Feedback from Peter
> [GEN-422] Add option to toggle display of video controls

- .vscode/racoon.code-workspace
- apps/store/src/blocks/BlogArticleListBlock.tsx
- apps/store/src/components/ArticleTeaser/ArticleTeaser.stories.tsx
- apps/store/src/components/ArticleTeaser/ArticleTeaser.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/blog/articleTeaser.ts
- apps/store/src/services/blog/blog.helpers.ts
- apps/store/src/services/blog/blogArticleTeaserList.ts
- apps/store/src/services/storyblok/storyblok.ts
- Add a new block to display a list of Blog Article Teasers.
- Check if teaser block is included on page to determine if we should fetch the list of articles.
- Pass down list of teasers to the block through a Jotai atom.
- Support company blog
- Use static site generation for blog pages
- I wanna avoid passing Storyblok data into React world so I create an internal representation for a "blog article teaser" which is converted from Storyblok data. This way we avoid making our solution too tightly coupled to Storyblok.
> Add Blog Article List Block

- apps/store/src/blocks/BlogArticleCategoryListBlock.tsx
- apps/store/src/components/ArticleCategoryList/ArticleCategoryList.stories.tsx
- apps/store/src/components/ArticleCategoryList/ArticleCategoryList.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/blog/articleCategory.ts
- apps/store/src/services/blog/articleTeaser.ts
- apps/store/src/services/blog/blogArticleCategoryList.ts
- apps/store/src/services/storyblok/storyblok.ts
- Add `BlogArticleCategoryListBlock` component
- Update `ArticleCategoryList` visual component
- Fetch blog article categories from Storyblok for relevant pages
- Resolve and parse categories on `blog-article` content type pages (for teaser)
More support for the blog.
> Add `BlogArticleCategory` support

- apps/store/src/blocks/BlogArticleCategoryContentType.tsx
- apps/store/src/blocks/BlogArticleCategoryListBlock.tsx
- apps/store/src/blocks/BlogArticleListBlock.tsx
- apps/store/src/components/ArticleTeaser/ArticleTeaser.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/blog/articleTeaser.ts
- apps/store/src/services/blog/blog.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
- Add support for rendering blog article category pages (content type: `blog-article-category`)
- Use same underlying block as `page` content type
- Add support for filtering blog articles by categories defined in `blogArticleList` block
- Blog support
> Support blog article category *pages*

- apps/store/src/components/Banner/Banner.stories.tsx
- apps/store/src/components/Banner/Banner.tsx
- apps/store/src/components/Banner/Banner.types.ts
* Extract `GlobalBanner` UI into it's own component. Down in the stack I'm gonna reuse that component - `Banner` - within `GlobalBanner` and `AnnouncementBlock`
Changes:
* It supports 4 variants: _info_, _campaign_, _warning_ and _error_ 
* It's content is now perfectly centered in the screen as it's not taking the _close button_ into account while aligning as it was before.
We need to provide a way for editors to render an _announcement_ (I've named it this while lacking a better name - we already have a banner block) by page. Despite looking exactly the same as the `GlobalBanner` it should function differently. That's why I thought about extracting the UI into a separate component and reuse it between `GlobalBanner` and `AnnouncementBlock`.
> feat(Banner): added banner component

- apps/store/src/blocks/RichTextBlock/RichTextBlock.styles.tsx
- apps/store/src/blocks/TextBlock.tsx
- apps/store/src/components/ForeverPage/ForeverPage.tsx
- apps/store/src/components/LayoutWithMenu/BreadcrumbList.tsx
- apps/store/src/components/LayoutWithMenu/Breadcrumbs.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/LayoutWithMenu/fetchBreadcrumbs.ts
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/storyblok/storyblok.ts
- packages/ui/src/components/Text/Text.tsx
- Add Breadcrumb List above the page footer (and option to hide from Storyblok)
- Include structured data based on the breadcrumb list
- Add helper function to generate breadcrumb list
- Add new text color to Text-component: "textSecondaryOnGray"
- Make link styles more re-usable
SEO and site improvements
> Add breadcrumb list above footer

- apps/store/src/blocks/AnnouncementBlock.tsx
- apps/store/src/blocks/ReusableBlockReference.tsx
- apps/store/src/components/Banner/Banner.tsx
- apps/store/src/components/GlobalBanner/GlobalBanner.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/services/storyblok/storyblok.ts
This PR is about integrating `AnnouncementBlock` for `Page` and `Product` content types. Down in the stack I also update `MigrationPage` content type so it does the same.
* Add a new block - `AnnouncementBlock` - which editors can use to display a _banner_ like message by page basis. As `GlobalBanner`, it uses `Banner` component as the UI.
* Multiple pages can share the same _announcement_ by reusing the same block.
* We use `SessionStorage` to keep opened/closed state for announcements.
Editors would like to show a banner on specific pages and that by dismissing that banner in one page would also dismiss it on all pages that renders it.
> feat(AnnouncementBlock): added a new block

- apps/store/src/blocks/HeroBlock.tsx
Add landscape image field to HeroBlock
https://github.com/HedvigInsurance/racoon/assets/6661511/c46160d8-6781-4110-a35b-2c30670d7687
We need support for some art direction, i.e. having a different image for portrait/landscape viewports in some cases
> Add landscape image field to HeroBlock

- apps/store/src/blocks/BlogArticleContentType.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/api/preview.ts
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/pages/manypets/[[...slug]].tsx
- apps/store/src/pages/manypets/migration/[shopSessionId].tsx
- apps/store/src/pages/reusable-blocks/[...slug].tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
- Use [resolved relations](https://www.storyblok.com/tp/using-relationship-resolving-to-include-other-content-entries) to fetch related categories per article
- Remove check if "story" is undefined => pretty sure the API will throw an error if the story doesn't exist
- We need to fetch the resolved categories on Blog Article content type
> Use resolved relations for blog article categories

- apps/store/src/blocks/ManyPetsMigrationPageBlock.tsx
- apps/store/src/pages/manypets/migration/[shopSessionId].tsx
- apps/store/src/services/storyblok/storyblok.ts
Fix an issue while trying to render Many Pets Migration page when no announcements are configured for that page. 
I've forgot to properly type/check for the presence of announcements for Many Pets Migration page so trying to render it without giving it an announcement would break the code - cannot map over underfined.
https://hedviginsurance.slack.com/archives/C054YL76SSU/p1686218003173419
> fix(ManyPetsMigrationPage): make announcements optional

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/PriceCalculator/FetchInsurance.tsx
- apps/store/src/components/PriceCalculator/FetchInsuranceContainer.tsx
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/PriceCalculator/useFetchInsurance.ts
- Show `FetchInsurancePrompt` whenever we have collected enough data (not based on form template)
- Move `FetchInsurance` logic from `CurrentInsuranceField` to `PriceCalculator`
- Remember if user has already seen `FetchInsurancePrompt` and don't show it again
- Make Insurely work also for Car where we don't show `CurrentInsuranceField`
- We will now show the dialog as soon as the price intent is updated with relevant data.
This is more implicit than the previous solution which I don't really like. However, since we don't need to support a lot of different products and markets, I think we are fine.
> [GEN-512] Always prompt Insurely when we have enough data

- apps/store/src/components/Header/Header.tsx
Updates _menu overlay_ implementation so it uses negative margins instead of absolute positioning.
Using absolute positioning to implement _menu overlay_ means to remove the menu from doc's flow which makes everything else on the page be pulled up. However that causes an issue when we have _banners/announcements_ on the screen (see image below). So what we actually want is to pull page's content by the exact menu's height. Negative margins are perfect for that use case since we don't need to do complex calculations for positioning the menu accordingly.
> GEN-527 - fix(Header): update menu overlay implementation so it takes banners/announcements into account

- apps/store/src/services/trustly/TrustlyIframe.tsx
- Show loading state before Trustly iframe has loaded
Indicate to user that something is happening so they don't reload the page
> Trustly Iframe: add initial loading state

- apps/store/src/blocks/MediaListBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
Extend VideoListBlock to support ImageBlock as well. 
Instead of trying to rename existing block I created a new block called MediaListBlock.
Once migrated, we can remove VideoListBlock
https://github.com/HedvigInsurance/racoon/assets/6661511/a377df19-86a4-41bf-a592-f100bd90a15e
We wanted to support images in VideoListBlock
> Feat / Add new MediaListBlock that supports both Image and Video

- apps/store/src/components/PriceCalculator/FetchInsurance.tsx
- packages/ui/src/components/Dialog/Dialog.tsx
Fix issue with Fetch Insurance dialog on small screens where content gets hidden if it's being centered.
Fix the bug
Make sure the content scrolls properly on small screens if there is overflow
> Fix issue in dialog where content was hidden

- apps/store/src/components/Accordion/Accordion.stories.tsx
- apps/store/src/components/Banner/Banner.stories.tsx
- apps/store/src/components/CartNotification/CartNotification.stories.tsx
- apps/store/src/components/CheckList/CheckList.stories.tsx
- apps/store/src/components/Combobox/Combobox.stories.tsx
- apps/store/src/components/ComparisonTable/ComparisonTable.stories.tsx
- apps/store/src/components/ContactSupport/ContactSupport.stories.tsx
- apps/store/src/components/Header/Header.stories.tsx
- apps/store/src/components/HeroVideo/HeroVideo.stories.tsx
- apps/store/src/components/HeroVideoVimeo/HeroVideoVimeo.stories.tsx
- apps/store/src/components/InsurableLimits/InsurableLimits.stories.tsx
- apps/store/src/components/LoadingDots/LoadingDots.stories.tsx
- apps/store/src/components/Perils/Perils.stories.tsx
- apps/store/src/components/ProductCard/ProductCard.stories.tsx
- apps/store/src/components/ProductGrid/ProductGrid.stories.tsx
- apps/store/src/components/QuickPurchaseForm/QuickPurchaseForm.stories.tsx
- apps/store/src/components/SelectInsuranceGrid/SelectInsuranceGrid.stories.tsx
- apps/store/src/components/Slideshow/Slideshow.stories.tsx
- apps/store/src/components/TierSelector/TierSelector.stories.tsx
- apps/store/src/components/Timeline/Timeline.stories.tsx
- apps/store/src/components/TopPickCard/TopPickCard.stories.tsx
- apps/store/src/components/Video/Video.stories.tsx
Storybook automatically groups components based on it's name and folder. So removing the title will group it under `components`. 
Let me know if this is better or not :D 
Before: 
After:
> Group components in Storybook

- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/ProductPage/PurchaseForm/DiscountTooltip/DiscountTooltip.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- Display a custom message when the user gets price matched but with a larger scope than the competitor (e.g. 2 vs 3 co-insured)
- Update `DiscountTooltip` with option to display a gray variant
- Right now we display a confusing message like "You save -20 kr" in these cases
> Display custom message for incomparable price match

- apps/store/package.json
- apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx
- apps/store/src/components/RichText/RichText.styles.tsx
- apps/store/src/components/RichText/RichText.tsx
- apps/store/src/features/blog/BlogArticleBlock.tsx
- yarn.lock
- Add support for using blocks inside RichText
- Being able to use ImageBlock and render with NextImage
We want to have the same image capabilities in RichText and also add support for rendering links as NextLinks (upcoming change)
As [suggested by Storyblok](https://github.com/storyblok/storyblok-react#rendering-rich-text:~:text=We%20also%20recommend%20using%20the%20Storyblok%20Rich%20Text%20Renderer%20for%20React%20by%20Claus%20for%20rendering%20your%20Storyblok%20rich%20text%20content%20to%20React%20elements%20and%20Next.js%20applications.) we can use https://github.com/claus/storyblok-rich-text-react-renderer 
https://github.com/HedvigInsurance/racoon/assets/6661511/a1035234-f122-43b7-ae27-b4a76076f79b
The default Storyblok render function doesn't support rendering React components
> Add support for adding ImageBlock in RichTextBlock

- apps/store/src/components/PriceCalculator/FetchInsurance.tsx
- apps/store/src/services/Insurely/Insurely.tsx
- Use native Insurely close button instead of overlaying our own
- Center Insurely iframe on small devices based on screen height
- The native close button looks more native we don't need to worry about
positioning it correctly
- We can't always center the iframe since the content might be longer than the
screen height. But if the content is shorter than the screen height, we should center it.
> Insurely: use native close button

- apps/store/src/features/blog/BlogArticleBlock.tsx
Blog article updates:
- Skip separate "content" field and render rich text inside "body" blocks field
- Update layout for blog article page header to match rich text blog styles
Requested from Peter
> [GEN-569] Blog Article: render content inside body blocks

- apps/store/public/locales/en/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/blocks/ProductCardBlock.tsx
- apps/store/src/blocks/SelectInsuranceGridBlock.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
- apps/store/src/components/ProductGrid/ProductGrid.stories.tsx
- apps/store/src/graphql/ProductMetadata.graphql
- apps/store/src/utils/getParameterizedLink.ts
* Changes how focus styling is applied to [Read more] button by increasing the specificity of the selector.
Which the specificity we had [before](https://github.com/HedvigInsurance/racoon/pull/2595/files#diff-cb843ebd121aa7a1c934583700ae1d2e7501e359f8c95e0c052d5618c055e3f8L207) pretty much any button rendered as a `ProductCard` _call to action container's_ children would receive focus styling when the link represented by the `ProductCard` get's focused. That caused some issues with the addition of [See your price] button for product categories:
https://github.com/HedvigInsurance/racoon/assets/19200662/6ece83fe-25ec-4b07-a0d9-17de061bf455
> GEN-576 - refact(ProductCard): increase specificity on 'read more' button focus styling

- apps/store/src/blocks/ProductCardBlock.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
Replace `datadogLogs.logger.warn` calls for regular `console.warn`.
> fix(ProductCard): use correct log method

- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/PriceCalculator/PriceCalculatorSection.tsx
- apps/store/src/utils/PageLink.ts
- Show a link to privacy policy in price calculator before showing price
- Only show the link on the last step of the price calculator
- Add PageLink function to get privacy policy link
Be compliant with GDPR
> [GEN-573] Show GDPR link before calculating price

- apps/store/src/blocks/GridBlock.tsx
- apps/store/src/blocks/ImageBlock.tsx
- apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx
- apps/store/src/blocks/TextContentBlock.tsx
- apps/store/src/blocks/USPBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
- Add the grid layout to the USP Block
- Create shared `GridColumnsField` type based on "HedvigGridColumns" storyblok plugin
- Make USP Block match the layout of the rest of the page
> [GEN-571] Add Grid layout to USPBlock

- apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx
* `RichTextBlock`: make sure anchors are append into `href` when provided.
Without it, anchor definitions are being ignored:
> GEN-406: fix(RichTextBlock): append anchor id if provided

- apps/store/package.json
- apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx
- yarn.lock
**Update**: `storyblok-rich-text-react-renderer` got updated so no workaround is required anymore.
Update `RichTextBlock` so link's `custom` attributes like `rel` and `title` get included in the rendered ancho tag.
Before they were being ignored even though we proper get from them _Storyblok_. Observe tho that this solution  has a workaround as the ideal solution would be the one where `[storyblok-rich-text-react-renderer](https://github.com/claus/storyblok-rich-text-react-renderer)` - a library we're using for resolving rich text content into React components - get its types updated. Link's custom attributes are already available for the link resolver function, so it's just about a type mismatch. I've created an [issue](https://github.com/claus/storyblok-rich-text-react-renderer/issues/41 …
> GEN-606 - fix(RichTextBlock): pass down link custom attributes

- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/ProductPage/PriceIntentContext.tsx
- Pre-select offers that have been price matched in the offer presenter
- Update translations for when we are not able to match a competitor price
We intend to control which offers are pre-selected (and/or highlighted) in the API, however, we are not able to do this yet. This is a temporary solution to launch Insurely for Car.
> [GEN-607] Pre-select price matched offers

- apps/store/src/features/blog/ArticleTeaser/ArticleTeaser.tsx
- apps/store/src/features/blog/BlogArticleBlock.tsx
- apps/store/src/features/blog/BlogArticleListBlock.tsx
- apps/store/src/utils/formatter.ts
- packages/ui/src/components/Text/Text.tsx
- Display dates in the same way across the blog pages
- Use localized dates; add new `dateFull` formatter utility
- Add "uppercase" prop to `Text` component
- Peter wants dates to be displayed in the same way across the blog pages
- Uppercasing text is a common design pattern
> Unify date formatting across blog

- apps/store/src/features/blog/ArticleTeaser/ArticleTeaser.stories.tsx
- apps/store/src/features/blog/ArticleTeaser/ArticleTeaser.tsx
- apps/store/src/features/blog/BlogArticleListBlock.tsx
- Align blog title and ingress to start on the same line
- Update aspect ratio for teaser images and fix content fit
- More unified article teaser grid
- Images where being stretched
> Blog: clean up alignment in article teaser layout

- apps/store/src/features/blog/BlogArticleBlock.tsx
- apps/store/src/features/blog/blog.types.ts
Prevent Storyblok editor from crashing when editing blog articles
React crashes when editing since categories are returned as a list of UUIDs instead of being resolved as Story objects.
I show a placeholder when this happens.
> BlogArticle: fix editor crashing

- apps/store/src/blocks/AccordionItemBlock.tsx
* Fix an issue where accordions don't work as they should when they have lists as their content.
I've spent some time trying to understand why exactly the issue just happens with lists and/or why this solves it, but to be honest I actually didn't really understand it 😅 
I mean,  theirs docs mention about composing radix functionalities with custom components with `asChild` prop. So my honest guess is that without it radix can't proper get content's container height which results on the undesirable behaviour. That doesn't explain why it just happens with lists tho 🤷🏻 
https://github.com/HedvigInsurance/racoon/assets/19200662/05778057-e4a9-466e-93e3-36fd7a25f32b
https://github.com/HedvigInsurance/racoon/assets/19200662/477be385-12eb-41c6-9193-ddae052e9125
> GEN-636 - fix(AccordionItemBlock): get proper content height with asChild prop

- apps/store/src/features/blog/BlogArticleBlock.tsx
- apps/store/src/features/blog/BlogArticleListBlock.tsx
Render article page with 0 categories correctly
Remove solution with showing PLACEHOLDER category while editing
It's okey to have articles without categories so no need to show PLACEHOLDER category
> Blog: allow blogs to have 0 categories

- apps/store/src/features/blog/ArticleTeaser/ArticleTeaser.tsx
- apps/store/src/features/blog/BlogArticleBlock.tsx
- apps/store/src/features/blog/BlogArticleListBlock.tsx
- apps/store/src/features/blog/fetchArticleTeasers.ts
Fetch all article teasers instead of first 25
Render ingress as paragraph tag
I make the build fail if we have more than the max number of articles in one locale. This will be our trigger to implement pagination but if we never reach this limit we don't need to implement pagination.
> Blog: fetch all article teasers

- apps/store/public/locales/en/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/blocks/DownloadableContentItemBlock.tsx
- apps/store/src/components/DownloadableContentItem/DownloadableContentItem.stories.tsx
- apps/store/src/components/DownloadableContentItem/DownloadableContentItem.tsx
- apps/store/src/services/storyblok/storyblok.ts
- Add new block for uploading a thumbnail and adding a link to the asset.
- Supports video, image and documents
- Will be used inside `GridBlock` as decided with Peter
https://github.com/HedvigInsurance/racoon/assets/6661511/f6a51239-469e-4799-90e9-1c70e700f00e
Press material
> GEN-610 / Add DownloadableContentItemBlock

- apps/store/scripts/publish-storyblok-cache-version.js
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/api/revalidate.ts
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- apps/store/vercel.json
- Manually manage Storyblok cache version by storing it in Edge Config
- Use only when fetching production content
- Improve logging timing of data fetching for CMS pages
- Improve logging failures when fetching data for CMS pages
We are running into rate-limiting issues with Storyblok. To resolve it we need to fetch data from there CDN but this requires us to us the "cv" (cache version) option.
Usually, the Storyblok client takes care of this - but it doesn't work because of how Vercel runs each page build in a separate process.
> Manually manage Storyblok Cache Version

- apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/storyblok/storyblok.ts
- Add field in Page config to specify A/B test origin Story
- Use `abTestOriginStory` in `HeadSeoInfo` and pass canonical url
- Remove `canonicalUrl` field in Page config and use slug from `abTestOriginStory`
To avoid that Google index the A/B test variants as a new page, we should use the meta data from the origin page and add a canonical tag
> Add field for specifying AB test origin story in Storyblok

- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/storyblok/storyblok.ts
- Fix passing default Storyblok version when fetching story data
- Update logging when building CMS pages
Fix issue in the build pipeline -- we incorrectly default to "draft" mode.
> Correctly pass Storyblok version when fetching story

- apps/store/next-csp.config.js
- apps/store/src/blocks/VideoBlock.tsx
- Add field for `videoUrl` to replace asset field
- Setup new S3 bucket for `hedvig-dot-com` content
- Add deprecation flag in Storyblok for video field
To consider:
We currently only use one video format in sources, mp4. We should probably use webm as well. Should we add another field for that in Storyblok? In market-web we relied on the filename being the same and just added the file format to the path but that leaves for some errors if we wouldn't upload both formats in S3. 
We used around 3TB of traffic last month, most traffic is are due to videos stored in Storyblok. We currently pay $60 per 250GB for Storyblok traffic compared to $5.75 if we store it on S3.
> Use videos from S3 bucket to save traffic usage on Storyblok

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/ForeverPage/ForeverPage.tsx
- apps/store/src/components/TextWithLink.tsx
- apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- Render link instead of placeholder in sign disclaimer text on MP migration page
- Allow consumer to pass text props to `TextWithLink` component
- We are rendering the placeholder instead of the link
> GEN-653 | Render link in sign disclaimer text

- apps/store/src/services/storyblok/storyblok.ts
Exclude product metadata stories from CMS from being prerendered by ISR.
Saw some warnings about this in build logs.
These stories are not meant to be prerendered by ISR.
> GEN-650 | Exclude product metadata stories from ISR

- apps/store/src/features/manyPets/manyPetsService.ts
- apps/store/src/pages/manypets/migration/[shopSessionId].tsx
* Get price data from `cost` field.
I've just released a some changes that removes usage of `ProductOffer.price` field. That breaks ManyPets migration which was still relying on it.
> fix(Manypets): don't rely on ProductOffer type

- apps/store/src/components/CartInventory/CartEntryItem/CartEntryCollapsible.tsx
- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
- apps/store/src/components/CartInventory/CartEntryItem/EditEntryButton.tsx
https://github.com/HedvigInsurance/racoon/assets/1220232/9eeeabb5-8deb-4a30-a1c6-8ef8ea16be24
- Make the "whole" Cart Item card clickable to exapand and collapse the details
- Add hover state to the Cart Item card
- Make the action buttons medium size
- Make the full collapsible "header" clickable
😈
I decided to only make the top part of the card clickable instead of litteraly the whole card. This is to avoid overlapping with the action buttons. Click events propagate so if the whole card is clickable, it will be triggered even if the user clicks on the action buttons e.g.
Instead of trying to work around this, I decided to only make the top part clickable.
I used the `:has` parent selector to only apply the hover state when hovering over the top part of the card. This has surprisingly …
> GEN-666 | CartItem: make the whole card clickable to expand

- apps/store/src/components/CartInventory/CartInventory.helpers.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
Update helper functions used to provide data to `CostSummary` so they rely on `cost` field while identifying if there's some discount being applied to your purchase.
**Before**
**After**
So the Cost summary doesn't look so confusing since it might be some cases where the product you have added into the cart is not covered by the campaign code you've added.
Also going to update the [contingency plan](https://github.com/HedvigInsurance/racoon/pull/2691) by removing these changes after this get's merged.
> fix(CostSummary): define applied discount based on cost field

- apps/store/src/components/CartInventory/CampaignsSection.tsx
- apps/store/src/components/CartInventory/ReadOnlyCampaignCodeList.tsx
- apps/store/src/components/CheckoutHeader/Breadcrumbs.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPaymentTrustlyPage/CheckoutPaymentTrustlyPage.tsx
- apps/store/src/components/ComparisonTable/ComparisonTable.tsx
- apps/store/src/components/ConfirmationPage/CheckList.tsx
- apps/store/src/components/ConfirmationPage/ContractCard.tsx
- apps/store/src/components/FetchInsuranceSuccess/FetchInsuranceSuccess.tsx
- apps/store/src/components/InputSelect/InputSelect.stories.tsx
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceCalculator/FetchInsurance.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/RichText/RichText.styles.tsx
- apps/store/src/components/TierSelector/TierLevelRadioGroup.tsx
- apps/store/src/components/TierSelector/TierSelector.tsx
- packages/ui/src/components/Badge/Badge.tsx
- packages/ui/src/components/Button/Button.helpers.ts
- packages/ui/src/lib/theme/radius.ts
- Update InputSelect size
- Update border radius sizes
- Update story to latest format
> Update InputSelect size and border radius values

- apps/store/package.json
- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
- apps/store/src/components/CartInventory/CartEntryItem/ShortSummary.tsx
- apps/store/src/components/CartInventory/CartEntryItem/Tooltip.tsx
- yarn.lock
- Add tooltip component
- Add tooltip to Cart Item to show info about start date / switching
- Help users switch
> GEN-682 | Add tooltip to Cart Item

- apps/store/src/components/Video/Video.tsx
When videos has ended, re-load it to show the cover of the video.
This doesn't affect autoplaying videos that are looped and simply paused, when you use the controls.
https://github.com/HedvigInsurance/racoon/assets/6661511/ca1851ec-e9a1-425e-beb1-9032f9e4a2ad
https://github.com/HedvigInsurance/racoon/assets/6661511/3b5bc908-7a8d-494a-ba3a-771a63942da5
Non autoplaying videos stops on the last frame. A bit nicer to "rewind" and show the poster instead.
> GEN-668 / Show video cover when video has ended instead of the last frame

- apps/store/.env.local.example
- apps/store/src/services/trustpilot/trustpilot.tsx
- apps/store/src/services/trustpilot/trustpilot.types.ts
* Adds a `TrustpilotBlock` that displays _Trustpilot_ data.
How the whole thing works:
1. Real data is stored in store's [_Edge Config_ storage](https://vercel.com/hedvig/hedvig-dot-com/stores/edge-config/ecfg_viia3ntdquafelygrc3g6lfs3d2a/items#item=trustpilot);
2. This PR will set a cron job that's going to update it every Monday at 8:00 (just picked that number. Gonna double check if that's enough) - check `apps/store/vercel.json` and `apps/store/src/pages/api/cron/trustpilot.ts` files
3. There's a new service - `apps/store/src/services/trustpilot/trustpilot.tsx` - which is responsible to provide a way to retrieve that data from the storage. It also gonna store it in a Jotai's atom so it can be available in the whole app. We then fetch that data and proper hydrate the atom in the …
> GEN-637 - feat: added a service to retrieve Trustpilot data

- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/ProductPage/ProductPage.types.ts
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/storyblok/storyblok.ts
* Fetch _Trustpilot_ data for Storyblok pages and make it available globally.
How the whole thing works:
1. Real data is stored in store's [_Edge Config_ storage](https://vercel.com/hedvig/hedvig-dot-com/stores/edge-config/ecfg_viia3ntdquafelygrc3g6lfs3d2a/items#item=trustpilot);
2. This PR will set a cron job that's going to update it every Monday at 8:00 (just picked that number. Gonna double check if that's enough) - check `apps/store/vercel.json` and `apps/store/src/pages/api/cron/trustpilot.ts` files
3. There's a new service - `apps/store/src/services/trustpilot/trustpilot.tsx` - which is responsible to provide a way to retrieve that data from the storage. It also gonna store it in a Jotai's atom so it can be available in the whole app. We then fetch that data and proper hydrate the …
> GEN-637 - feat: make Trustpilot data available globally

- apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/storyblok/storyblok.ts
Revert change we did for canonical tag. Use the manual field from Storyblok as Peter suggested from his thread. This should fix issue no.1  https://hedviginsurance.slack.com/archives/C02JPS466NS/p1689145200740139
Let's see if we should have canonical automatically matching the page and overwritten by the manual field.
Peter reported some SEO issues after the last change we did for A/B test page
> Revert change and use canonical field instead

- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
- apps/store/src/components/CartInventory/CartEntryItem/DetailsSheet.tsx
- apps/store/src/components/CartInventory/CartEntryItem/ShortSummary.tsx
Refactor CartEntryItem helpers to only accept props they actually use.
Make it possible to reuse them instead. Also avoid making them tightly coupled to the API.
> Refactor CartEntryItem helper components

- apps/store/src/components/LayoutWithMenu/getLayoutWithMenuProps.ts
- apps/store/src/pages/404.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/pages/forever/[code].tsx
- Extract fetching logic required for any page that renders inside `LayoutWithMenu`
- Implement new helper function on relevant pages
Avoid duplication and make it easier to use the layout component.
> Add helper to get props for pages that use LayoutWithMenu component

- apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
- apps/store/src/pages/[[...slug]].tsx
Use robots field from Storyblok for the source page in every case to make sure A/B test pages get noindex. 
This should fix issue no.3  https://hedviginsurance.slack.com/archives/C02JPS466NS/p1689145200740139
Peter reported some SEO issues after the last change we did for A/B test page
> 🚨 Always use robots field from the source story in A/B test cases

- apps/store/src/components/Combobox/Combobox.tsx
- apps/store/src/components/InputDate/InputDate.tsx
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceCalculator/ExtraBuildingsField.tsx
- apps/store/src/components/PriceCalculator/InputRadio.tsx
- apps/store/src/components/PriceCalculator/StepperInput/StepperInput.tsx
- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/components/ToggleCard/ToggleCard.tsx
- apps/store/src/utils/useHighlightAnimation.ts
- packages/ui/src/components/Dialog/Dialog.tsx
- Change background color of input fields to "translucent 1"
- Update `useHighlightAnimation` hook to use JS animations instead of framer motion
- Fix highlight animation for horizontal radio group inputs
- I had to switch from framer motion to JS animations becuase framer motion has difficulties tweening colors with alpha values. I also think the new impolementation is slightly easier to understand.
- The new solution returns a ref which you attatch to the element you want to animate. In the few cases where we already use the ref, I decided to add a wrapper div around it and animate that (e.g. Combobox).
- We want the inputs to be translucent to work better in the price calculator which has a blurred background on mobile.
> Make input fields translucent

- apps/store/src/components/ComparisonTable/DesktopComparisonTable.tsx
* Extracts _Desktop_ version of the Comparison Table into a component to be used on bigger viewports.
We got a new [design](https://www.figma.com/file/qUhLjrKl98PAzHov9ilaDH/Hedvig-UI-Kit?type=design&node-id=3380-13894&mode=design&t=snZZXMBD7zxyZULO-4) for a _mobile_ version of the comparison table:
> GEN-664 - feat: added DesktopComparisonTable

- apps/store/src/components/ComparisonTable/ComparisonTable.stories.tsx
- apps/store/src/components/ComparisonTable/DesktopComparisonTable.stories.tsx
- apps/store/src/components/ComparisonTable/MobileComparisonTable.stories.tsx
* Updates `ComparisonTable` stories so it uses new data structure for table representation.
https://github.com/HedvigInsurance/racoon/assets/19200662/d2e80dfd-b151-4787-bc94-303f2a0d7c25
We got a new [design](https://www.figma.com/file/qUhLjrKl98PAzHov9ilaDH/Hedvig-UI-Kit?type=design&node-id=3380-13894&mode=design&t=snZZXMBD7zxyZULO-4) for a _mobile_ version of the comparison table:
> GEN-664 - chore: update ComparisonTableStories

- apps/store/src/components/TextField/TextField.tsx
- Exclude delete button when tabbing through the form
- It's annoying to tab twice to get to the next field
- Possibly you end up deleting the field text by accident
> TextField: avoid tabbing to delete button

- apps/store/README.md
- apps/store/src/components/DebugDialog/DebugDialog.tsx
- apps/store/src/pages/_app.tsx
- Add hidden debug menu that you can access by pressing `?` on your keyboard
- Show ShopSession ID with option to copy to clipboard
- Allow us to present debug information for internal use
- We can expose things like shop session information or links
- I think we want to make this page specific so we can display information
that is relevant to the page you are on
> GEN-756 | Debugger: add hidden page debugger

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/PageDebugDialog.tsx
- apps/store/src/components/DebugDialog/CopyToClipboard.tsx
- apps/store/src/components/DebugDialog/DebugDialog.tsx
- apps/store/src/components/DebugDialog/DebugShopSessionSection.tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/utils/PageLink.ts
- Implement debug dialog on cart page
- Add section for sharing a link to the cart (and session)
- Remove global debug dialog instance in favor of page specific instances
- Refactor debug dialog to be more composable
- Add session link helper to `PageLink`
- We want to help inbound/outbound support teams to generate offers and share link to the cart
> GEN-736 | Share link to cart from debug dialog

- apps/store/src/utils/l10n/useChangeLocale.ts
Uses _full page reload_ on language switcher
We're having a bug where product cards just disappear while changing languages. Causing a _full page reload_ is probably the best option when it comes about changing app's locale.
> fix language switcher

- apps/store/next.config.js
- apps/store/src/pages/api/campaign/[code].ts
When most common landing page on the old website is used with campaign code - apply the code and redirect to new products page
Drain some traffics from the old site
> GEN-765 Redirect most-visited old landing pages with campaign code to new website

- apps/store/next.config.js
- Add redirects for old car cancellation page to the new one
- No one should be able to access the old page but we still see some traffic on it so let's make sure people end up on the new page
> Redirect Car cancellation from WebOnboarding to Hedvig.com

- apps/store/experiment.json
- apps/store/next.config.js
- apps/store/src/services/Tracking/experiment.constants.ts
> Redirect A/B test variant page to home

- apps/store/src/components/DebugDialog/DebugDialog.tsx
Avoid error when checking shortcut for debug dialog
Source: https://datadoghq.eu/rum/error-tracking?query=@application.id:d86e86d8-8d9a-4b00-a2cb-10b8d7671fa2&issueId=00c44958-2246-11ee-83d3-da7ad0900005&from_ts=1689590266557&to_ts=1689593866557&live=true
- We don't want uncaught exceptions
- I decided to log an error if the code would still contain some issues
> GEN-764 | Catch errors in debug dialog shortcut effect

- apps/store/next.config.js
> GEN-766 - feat: redirect home routes

- apps/store/src/components/DebugDialog/DebugResumeSessionSection.tsx
- apps/store/src/components/DebugDialog/DebugShopSessionSection.tsx
- Add option to resume a shop session from debug dialog
Pretty common action
Styles are a bit off but I address that in the next PR
> Add resume shop session form to debug dialog

- apps/store/src/services/PriceCalculator/PriceCalculator.helpers.ts
Fix stepper field behavior when non-empty initial value was provided.  It took 2 as string ("2") and then button behaved like "2" + 1 = "21"
Fix co-insured field behavior when editing previously entered value
> Fix deserializing stepper input

- apps/store/src/components/ChangeSsnWarningDialog/ChangeSsnWarningDialog.tsx
- apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
- apps/store/src/components/PriceCalculator/SsnSeSection.tsx
* Updates condition for the appearance of `ChangeSsnWarningDialog`
As it can be seen in the video below, the _glitch_ happens because `ChangeSsnWarningDialog` get's shown for a brief moment when we load information for an _authenticated user_. In those situations we need to display BankId Dialog but `ChangeSsnWarningDialog` also get's show because:
*  `ChangeSsnWarningDialog` appearance is based on the [presence of `shopsSession.customer?.ssn`](https://github.com/HedvigInsurance/racoon/blob/main/apps/store/src/components/PriceCalculator/SsnSeSection.tsx#L38).
* In that scenario the active section is still _ssn_; It will be the next one only when Bankid Dialog get's resolved, which makes sense I think. That also means `SsnSeSection` will be re-rendered but this time `shopsSession.customer` …
> GEN-670 - fix: change ssn warning dialog glitch

- apps/store/src/components/CartInventory/CartInventory.helpers.tsx
Don't show "automatic switch" message when cancellation option is "NONE"
But discovered by Sonny
> Fix bug: showing auto switch when option is NONE

- apps/store/src/components/BankIdDialog.tsx
- apps/store/src/components/ChangeSsnWarningDialog/ChangeSsnWarningDialog.tsx
- packages/ui/src/components/Dialog/Dialog.tsx
Disclaimer: William is not here to validate. I guess it's personal preference then 🤷🏻 
* Updates Dialog overlay transition by making it slower. It was too fast before. 
* Add transition for `ChangeSsnWarningDialog`
* Update `BankIdDialog` transition so they match and refactored a little. `AnimationPresence` animations doesn't in that case so I guess we can simplify it?! Let me know what you think.
https://github.com/HedvigInsurance/racoon/assets/19200662/cf252b4e-3696-4c7b-95ab-a8cb84a8c950
https://github.com/HedvigInsurance/racoon/assets/19200662/3c29adce-3ec1-49db-ba9f-81ff0777c940
It was requested by design that we make `ChangeSsnWarningDialog` by applying a smoother transition to it.
> GEN-670 - styles(ChangeSsnWarningDialog): smooth transition

- apps/store/src/components/CartInventory/CartInventory.helpers.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/graphql/CartFragment.graphql
- apps/store/src/pages/cart/index.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/services/Tracking/Tracking.ts
- apps/store/src/utils/useDiscountBanner.ts
- Switch from using `Cart.redeemedCampaigns` field (deprecated) to `Cart.redeemedCampaign` (new field)
- Update related parsing logic
- We parse this field in a lot of places, I think I will refactor it in a future PR
- I decided to keep some of the old logic related to lists of campaigns, but I think we should remove it in a future PR
> GEN-792 | Switch from `Cart.redeemedCampaigns` -> `Cart.redeemedCampaign`

- apps/store/src/components/CartInventory/CampaignSection.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/TextField/TextField.tsx
- packages/ui/src/components/Button/Button.tsx
- Refactor `CampaignSection` to handle a single campaign instead of a list
- Update height of small text field to match UI kit
- We only support a single campaign per session
- Still more refactoring to come
> Refactor `CampaignSection` to accept a single campaign

- apps/store/next.config.js
- Redirect all NO/DK requests to `/new-member` to info page about shut down
- Requires merging: https://github.com/HedvigInsurance/back-office/pull/882
- We still need to support payment connect links but will only support directly using "old.hedvig.com" for that
> NO/DK: redirect all traffic from /new-member to shutdown info page

- apps/store/src/components/ProductPage/PriceIntentContext.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
* Reset `selectedOffer` when a new price intent is created.
We're getting the following warning while adding products into the cart:
Removing those warnings will help clean our logs a little.
> chore: reset selected offer when a new price intent is created

- apps/store/src/pages/api/auth/exchange/[code].ts
- apps/store/src/pages/payment/connect-legacy/start.tsx
- apps/store/src/services/adyen/useAdyenTranslations.ts
- apps/store/src/utils/PageLink.ts
- Add landing page before the payment connect legacy flow
- Fix issue where we return from the API route function
- We want the user to be able to load the page without consuming the authorization code accidentally
> Add landing page before starting payment connect legacy flow

- apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/SwitchingAssistantSection.tsx
- apps/store/src/components/ConfirmationPage/useSwitchingContracts.ts
- apps/store/src/graphql/ShopSessionOutcome.graphql
- apps/store/src/graphql/ShopSessionOutcomeFragment.graphql
- apps/store/src/graphql/ShopSessionOutcomeId.graphql
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/services/shopSession/ShopSessionService.ts
* Updates confirmation page so it relies on `ShopSessionOutcome`.
> GEN-238 - refact(ConfirmationPage): migrate to ShopSessionOutcome query

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/TextWithLink.tsx
Prevent warning by passing down to next/Link only known props
We're currently getting this when loading _Checkout_ page.
> chore(TextWithLink): prevent warning by passing down to next/Link only known props

- apps/store/package.json
- apps/store/src/app/layout.tsx
- apps/store/src/services/apollo/app-router/ApolloWrapper.tsx
- apps/store/src/services/apollo/app-router/client.ts
- apps/store/src/services/apollo/app-router/headersLink.ts
- apps/store/src/services/apollo/client.ts
- apps/store/src/services/apollo/createHeadersLink.ts
- apps/store/src/services/apollo/errorLink.ts
- apps/store/src/services/apollo/httpLink.ts
- apps/store/src/services/apollo/languageLink.ts
- apps/store/src/services/apollo/userErrorLink.ts
- apps/store/src/services/authApi/app-router/persist.ts
- apps/store/src/services/shopSession/app-router/ShopSession.utils.ts
- yarn.lock
- Setup Apollo Client in the App Router to work with RSC and streaming SSR
- Refactor Apollo Client helpers to be more reusable and easier to understand
- Duplicate some utils to make use of new headers/cookies helper functions from Next.js
- So we can start fetching data in the App Router from the API. It will look something like this:
```jsx
const ServerComponent = async () => {
const { data } = await getClient().query({ query: QueryDocument })
return <div>{data}</div>
}
```
- Original article explaining the setup: https://www.apollographql.com/blog/announcement/frontend/using-apollo-client-with-next-js-13-releasing-an-official-library-to-support-the-app-router/
- More up-to-date info: https://github.com/apollographql/apollo-client-nextjs/tree/main/package
> Setup Apollo Client in App Router

- apps/store/src/components/CartInventory/RemoveEntryDialog.tsx
* Add same smoother opening animation for `RemoveEntryDialog` as we already have for `BankIdDialog` and `ChangeSsnWarningDialog`. With this addition we'll have 3 dialogs that share the same animation. I think it's time to try to abstract/share them which I'm gonna do in another PR. 
**Before**
[before.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/ocPE5OGCo5Y6fhJekeDQ/7c13f3c2-0d87-46c7-84d6-518b934b56a1/before.mov)
**After**
[after.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/ocPE5OGCo5Y6fhJekeDQ/2f6fb664-d2e4-47b9-9c91-bf231867a7c8/after.mov)
> GEN-825 - styles(RemoveEntryDialog): make opening animation smoother

- apps/store/src/blocks/ModalBlock.tsx
- apps/store/src/components/BankIdDialog.tsx
- apps/store/src/components/CartInventory/RemoveEntryDialog.tsx
- apps/store/src/components/ChangeSsnWarningDialog/ChangeSsnWarningDialog.tsx
- apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
* Unify opening animations for FullScreenDialog
Following is a list of components that relies on `FullScreenDialog`:
- `ModalBlock`
- `AppErrorDialog`
- `BankIdDialog`
- `RemoveEntryDialog`
- `EditEntryDialog`
- `ChangeSsnWarningDialog`
- `CheckoutPage`
- `ErrorDialog`
- `ProductCard`
- `ComparisonTableModal`
- `PurchaseForm`
From that list the following are the components that have some opening animations defined:
- `ModalBlock`
- `BankIdDialog`
- `RemoveEntryDialog`
- `ChangeSsnWarningDialog`
- `ProductCard`
- `ComparisonTableModal`
This ticket PR about unifying the opening animations for `FullScreenDialog` so they have a consistent UI. As a side effect, the components that were not defining an opening animation will now have one, providing a smoother experience. Take `EditEntryDialog` …
> GEN-824 - refact: unify animations for FullScreenDialog

- apps/store/src/graphql/ProductData.graphql
- apps/store/src/mocks/productData.ts
- apps/store/src/pages/api/partner/init.ts
- apps/store/src/services/partner/createPartnerShopSession.ts
- apps/store/src/services/partner/parseSearchParams.ts
- Pre-fill information passed as query params to the initial price intent
- Refactor API route to not make it too complicated
- Mimic how partner widget works
> GEN-827 | Partner Init: pre-fill information from search params in price intent

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Make sure we display an error message informing that something went wrong while trying to get a price.
While using `msw` I could verify that in any case an error is raised we'll display an error dialog. However, in case we can't get a selected offer due malformed payload (thanks for the suggestions @alebedev) we'd just render `PurchaseForm` on it's _Idle_ state, which was exactly what was happening for the cases that originated the issue.
> GEN-823 - fix(PurchaseForm): handle error other than ApolloErrors by showing a general error message

- apps/store/src/components/GlobalBanner/GlobalBanner.tsx
- apps/store/src/pages/_app.tsx
* Make sure `GlobalBanner` only gets rendered client side as it depends on storage based atom. By doing so we can avoid hydration errors.
We've been getting [hydration error logs](https://app.datadoghq.eu/rum/error-tracking?query=%40application.id%3Ad86e86d8-8d9a-4b00-a2cb-10b8d7671fa2&from_ts=1691154363205&to_ts=1691157963205&live=true) for a while now. I could track them down to a particular [deployment in prod](https://github.com/HedvigInsurance/racoon/commit/481cf34aaf7ef5b049e29a6201f574e08b6c0448) where I've changed `GlobalBanner` atom state to leverage `sessionStorage`. That was causing the hydration errors. Here I'm using the [Jotai's suggested solution](https://jotai.org/docs/utilities/storage#server-side-rendering) to fix the issue.
> fix(GlobalBanner): make sure it only renders client side avoiding hydration errors

- apps/store/src/components/CartInventory/CampaignSection.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- Add support for displaying a campaign code without giving user the option to remove it
- Useful for partner session where we have a pre-defined campaign code
> GEN-833 | Display read only campaign code (can not be removed)

- apps/store/src/components/CartInventory/CartEntryOfferItem.tsx
- Split price and action buttons on two rows on small screens
- Fix layout issue in `CartEntryOfferItem` where price overlaps with action buttons
> Fix `CartEntryOfferItem` layout on small screens

- apps/store/src/blocks/VideoBlock.tsx
- apps/store/src/components/Video/Video.tsx
- Add setting to hide sound controls for videos without audio
- Set `muted` based on autoplaying or hidden sound controls Storyblok setting
Currently we show sound control for some videos that doesn't have any audio track (like "Always with Hedvig"). And there might be use cases we want to disable mute/unmute.
> Add hide sound controls option

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/InputCurrentInsurance.tsx
- apps/store/src/services/slack/slack.types.ts
* Enables [_no-unsafe-enum-comparison_](https://typescript-eslint.io/rules/no-unsafe-enum-comparison) rule
> The TypeScript compiler can be surprisingly lenient when working with enums. For example, it will allow you to compare enum values against numbers even though they might not have any type overlap
> 
> ```
> enum Fruit {
>   Apple,
>   Banana,
> }
> 
> declare let fruit: Fruit;
> 
> fruit === 999; // No error
> ```
This is part of a series of PRs that includes new/updated rules added by typescript-eslint v6. The idea is to use those PRs so we discuss as a team if we want to enable a particular rule or not.
> chore(eslint): enable no-unsafe-enum-comparison rule

- apps/store/src/components/PriceCalculator/FetchInsurance.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useSelectedOffer.ts
- apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- apps/store/src/pages/checkout/index.tsx
- packages/eslint-config-custom/eslint-config-custom.js
* Enable [_prefer-optional-chain_](https://typescript-eslint.io/rules/prefer-optional-chain) rule.
> `?.` optional chain expressions provide `undefined` if an object is `null` or `undefined`. Because the optional chain operator only chains when the property value is `null` or `undefined`, it is much safer than relying upon logical AND operator chaining `&&`; which chains on any truthy value. It is also often less code to use `?.` optional chaining than `&&` truthiness checks.
> 
> This rule reports on code where an && operator can be safely replaced with ?. optional chaining.
This is part of a series of PRs that includes new/updated rules added by typescript-eslint v6. The idea is to use those PRs so we discuss as a team if we want to enable a particular rule or not.
> chore(eslint): enable prefer-optional-chain rule

- apps/store/src/@types/i18next.d.ts
- apps/store/src/emotion.d.ts
- apps/store/src/services/persister/Persister.types.ts
- packages/eslint-config-custom/eslint-config-custom.js
- packages/ui/src/emotion.d.ts
* Enables typescript eslint [_consistent-type-definitions_](https://typescript-eslint.io/rules/consistent-type-definitions) rule
> TypeScript provides two common ways to define an object type: interface and type.
> The two are generally very similar, and can often be used interchangeably. Using the same type declaration style consistently helps with code readability.
Here I'm deciding upon using `type`. With that I had to update the code to disable some edge cases where we need to use `interface`. We could change it to enforce the usage of `interface`,  but that would cause a bigger change since we've been using `type` in our codebase for the majority of the cases.
This is part of a series of PRs that includes new/updated rules added by typescript-eslint v6. The idea is to use those PRs …
> chore(eslint): enable consistent-type-definitions rule

- apps/store/src/components/PriceCalculator/ExtraBuildingsField.tsx
- apps/store/src/components/PriceCalculator/StepperInput/StepperInput.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- apps/store/src/utils/l10n/countryUtils.ts
- packages/eslint-config-custom/eslint-config-custom.js
- packages/ui/src/components/Badge/Badge.tsx
- packages/ui/src/components/Heading/Heading.tsx
* Enable typescript eslint [_prefer-nullish-coalescing_](https://typescript-eslint.io/rules/prefer-nullish-coalescing) rule.
> The `??` nullish coalescing runtime operator allows providing a default value when dealing with `null` or `undefined`. Because the nullish coalescing operator only coalesces when the original value is `null` or `undefined`, it is much safer than relying upon logical OR operator chaining `||`, which coalesces on any falsy value.
I've configure it to ignore conditional cases and `string` and `boolean` primitives.
This is part of a series of PRs that includes new/updated rules added by typescript-eslint v6. The idea is to use those PRs so we discuss as a team if we want to enable a particular rule or not.
> chore(eslint): enable prefer-nullish-coalescing rule

- apps/store/src/components/ComparisonTable/ComparisonTable.types.ts
- apps/store/src/components/ComparisonTable/DesktopComparisonTable.tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/pages/_document.tsx
- apps/store/src/services/CustomerFirst.tsx
- apps/store/src/services/apollo/languageLink.ts
- apps/store/src/utils/l10n/localeUtils.ts
- apps/store/src/utils/l10n/useCurrentCountry.ts
- apps/store/src/utils/l10n/useCurrentLocale.ts
- packages/eslint-config-custom/eslint-config-custom.js
Document why we want to disable typescript eslint [_no-redundant-type-constituents_](https://typescript-eslint.io/rules/no-redundant-type-constituents) rule
This is part of a series of PRs that includes new/updated rules added by typescript-eslint v6. The idea is to use those PRs so we discuss as a team if we want to enable a particular rule or not.
> chore(eslint): document why we want to disable no-redundent-type-constituents-rule

- apps/store/.storybook/decorators.tsx
- apps/store/.storybook/preview.tsx
- apps/store/src/components/Accordion/Accordion.stories.tsx
- Move decorators to separate file
- Add new gridDecorator
I thought it would be neat to better match Figma and Storybook stories in terms of layout. For example, showing Accordions as full screen is a bit misguiding since we will always restrict the width when implemented in the app. The only option we have today is the `layout` parameter that has `centered` or  `fullscreen`. I've added the GridLayout in some story templates but that feels like too much boilerplate when writing stories.
Instead we can have it as a global decorator that you enable by setting a `grid` parameter in the stories you want to use it.
```js
parameters: {
grid: '1/2' or { base: '1', md: '5/6', lg: '2/3', xl: '1/2' },
}, 
```
Make story layouts match Figma/implementation
> Add grid decorator to Storybook

- apps/store/package.json
- yarn.lock
This reverts commit 1ffd2bb5965339ed826a6463efdec57c59aa4f93.
Revert bump to resolve bug in where `selectedOffer` was undefined and hence didn't show offer in price calculator. 
https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1692001712502579
Might be related to this https://github.com/apollographql/apollo-client/issues/11140
> Revert "fix(deps): update dependency @apollo/client to v3.8.1 (#2952)"

- .github/renovate.json5
Restrict renovate automerge to business hours so that we can quickly fix problems if they appear
> Only automerge during business hours

- .github/renovate.json5
- apps/store/package.json
- apps/store/src/components/ProductPage/PriceIntentContext.tsx
- yarn.lock
* Updates `PriceIntentContext` by moving code that should be run whenever `priceIntent` changes from `useQuery`'s `onCompleted` callback to an `useEffect`
* Update `@apollo/client` version `3.7.17` --> `3.8.1`
* Remove `@apollo/client` from _renovate_'s ignore list
We had a [faulty update](https://github.com/HedvigInsurance/racoon/pull/2952)  of `@apollo/client` over the weekend which caused a bug in our app where one [couldn't get a price for any product](https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1692001712502579). The bug was caused by a [fix](https://github.com/apollographql/apollo-client/issues/11140) added by apollo team meaning `3.8.1` implements a more correct behaviour for `onCompleted` callback functions when compared to `3.7.17` - in other terms, our code was working …
> refact(PriceIntentContext): make sure 'synchronyze' code are place inside effects

- apps/store/src/components/ProductPage/PriceIntentContext.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
* Refact `PriceIntentContext` by moving _log BankSignering Offered_ code as a side effect of having successfully completed a price intent instead of run it every time `priceIntent` changes in our app.
I think this represents more when we want to log those.
> refact(PriceIntentContext): log 'BankSignering Offered' when confirming the price intent

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
Fix [issue](https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1692087830953549) in checkout where name fields were none editable for customers with missing name.
Make sure name fields are displayed correctly.
> Bugfix / Make sure name fields in checkout are editable when name is missing

- apps/store/src/pages/_app.tsx
- apps/store/src/pages/_document.tsx
- apps/store/src/services/CustomerFirst.tsx
This stack contains two possible solutions for the problem. Let's discuss on which one we want to move forward with.
* Make sure chat iframe get's added into the document by firing a `load` event for the `window` object.
I've noticed in [datadog](https://app.datadoghq.eu/rum/replay/sessions/b93e474b-8f91-4c57-a39b-ebcebd0d8ba8?highlightedEventId=AgAAAYn4MgH-4ckpEQAAAAAAAAAYAAAAAEFZbjRNZ2RVQUFDVmVwdFYtc19mYndBQgAAACQAAAAAMDE4OWY4MzUtNmNiYS00YjUzLThjN2QtMjFjMjVhZjhlYzQ3&seed=dca237d4-a3a3-420f-b374-6b8fc60b4768&ts=1692086174206&from=1692086174100) that some users were having problems to access the chat feature as nothing happened when chat button got clicked. 
The issue was that chat iframe was not getting added to the DOM at the moment users click on chat button, breaking the app:
There …
> fix(customer-first): make sure get's added into the document

- apps/store/src/components/ProductItem/ProductItem.tsx
- Update `ActionButton`s so they can accept `refs`, solving the error bellow.
Those buttons are being used as custom radix `Dialog` triggers, so they need to be able to accept `ref`s as radix uses them for focus management.
https://github.com/HedvigInsurance/racoon/assets/19200662/8b14a0c1-8a46-4fe0-85b4-de4fa7b45fe3
> feat(ActionButton): update so they accept refs

- apps/store/src/pages/api/session/reset.ts
Make sure we construct `nextURL` with query params correctly. 
`se/forsakringar/hemforsakring/bostadsratt?openPriceCalculator=1` instead of `se/forsakringar/hemforsakring/bostadsratt%3FopenPriceCalculator=1`
Apparently you can't set pathname including query params, but you need to construct a new URL with the path and base URL.
Annoying when reseting a session and you had the price calculator open it would cause a 404 due to misformatted query params in URL
> Make sure we resolve path with query params to valid URL in ShopSession debugger

- .github/renovate.json5
- apps/store/package.json
- apps/store/src/components/ProductPage/PriceIntentContext.tsx
- apps/store/src/services/bankId/useBankIdCheckoutSign.ts
- yarn.lock
* Bump `@apollo/client`: `3.17.1` --> `3.8.1`
* Update  apollo's `useQuery` instances in our code that relies on `onCompleted` callback.
I've went through the code looking for usages of `useQuery`'s `onCompleted` and proper updated them.
There's some occurrences where I think we don't need to do anything:
```
apps/store/src/components/InitiateCarCancellationPage/InitiateCarCancellationPage.tsx:
34:     onCompleted(data) {
apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx:
73:     onCompleted() {
```
More details can be found [here](https://github.com/apollographql/apollo-client/pull/10229) but in summary `@apollo/client@3.8.1` changes the circumstances when `useQuery`'s `onCompleted` callback gets executed. Before:
> writes to the cache (it doesn't matter …
> GEN-860 - chore: bump @apollo/client 3.7.17 - 3.8.1

- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- Update `CancellationForm` so it renders with the correct initial state for `BANKSIGNERING_INVALID_RENEWAL_DATE` cancellation option.
We've beeng displaying it with the incorrect intial state for `BANKSIGNERING_INVALID_RENEWAL_DATE` cancellation option as one could see the "Switch automatically" toggle for scenarios that we can't actually do it.
> fix(CancellationForm): display it with the correct initial state when cancellation option equals BANKSIGNERING_INVALID_RENEWAL_DATE

- apps/store/src/blocks/CookieListBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
- Add CookieListBlock to display cookie list from OneTrust
The OneTrust script fetches and outputs content in the div with the `id`. Styling is handled in OneTrust dashboard.
Needed for GDPR compliance
> Add CookieListBlock to display cookie list from OneTrust

- apps/store/src/features/retargeting/RetargetingBlock.tsx
- apps/store/src/pages/api/draft.ts
- Show skeleton UI on cart resume page while in draft more (in Storyblok editor)
- Add query param after navigating from draft mode API route
- To make it easier to preview how the page will look like for editors
> Cart Resume: show skeleton UI in draft mode

- apps/store/src/blocks/CookieListBlock.tsx
Add OneTrust cookie list styling. Makes it easier to change to override it in the component than having it in OneTrust dashboard, so I migrated it over from there. I kept it in string format to make migration back and forth easier ( and it's a pain to write class name styling with object syntax 😆)
https://github.com/HedvigInsurance/racoon/assets/6661511/f82251a1-5fb9-4ddc-af6c-46762ad52bb9
> Add OneTrust cookie list styling

- apps/store/package.json
- apps/store/src/services/PriceCalculator/data/SE_PET_CAT.ts
- apps/store/src/services/PriceCalculator/data/SE_PET_DOG.ts
- yarn.lock
- Added min/max constraints for 'birthDate' input field for Cat and Dog insurance. They follow their respective underwriter guidelines for [cat](https://github.com/HedvigInsurance/underwriter/blob/master/src/main/kotlin/com/hedvig/underwriter/service/guidelines/SwedishCatGuidelines.kt#L18-L24) and [dog](https://github.com/HedvigInsurance/underwriter/blob/master/src/main/kotlin/com/hedvig/underwriter/service/guidelines/SwedishDogGuidelines.kt#L19-L25) insurances.
[Ticket](https://www.notion.so/hedviginsurance/Price-calculator-missing-validation-for-date-picker-field-birth-date-pet-insurance-b91a57daa5994d938e1e05b2fd901b55?pvs=4)
> GEN-910 - feat(pet-insurance): added min/max constraints for 'birthDate' input

- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- Added 'max' constraint to 'startDate' field based on underwriter [guideline](https://github.com/HedvigInsurance/underwriter/blob/master/src/main/kotlin/com/hedvig/underwriter/model/Quote.kt#L83-L86)
> GEN-910 - fix(CancellationForm): added 'max' constraint to 'startDate' input

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/ProductItem/ProductItemContainer.tsx
- apps/store/src/components/ProductItem/useGetStartDateProps.ts
- apps/store/src/features/retargeting/MultiTierOffer.tsx
- apps/store/src/features/retargeting/ProductPageLink.tsx
- apps/store/src/features/retargeting/SingleTierOffer.tsx
- apps/store/src/features/retargeting/useRetargetingOffers.ts
- Implement product item container in retargeting block
- Move product item container to product item folder to indicate that it is reusable
- Make container accept children instead of rendering predefined action buttons
- I will continue implementing and seeing if this is the right abstractions
> ShopBreakdown: implement product item container in retargeting block

- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
- apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/SwitchingAssistantSection.stories.tsx
- apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/SwitchingAssistantSection.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- Use shop session outcome ID to fetch switching contracts
- Add types to storybook story
- Before we passed shop session ID which just seems like a bug
- Still I can't test it myself
> Fix: use shop session outcome id to fetch switching contracts

- .github/renovate.json5
Ignore updates to Adyen SDK in Rennovate
We are not able to upgrade to the latest version of Adyen SDK
> Rennovate: ignore adyen SDK

- apps/store/src/components/Price.tsx
- apps/store/src/components/ShopBreakdown/QuickAdd.stories.tsx
- apps/store/src/components/ShopBreakdown/QuickAdd.tsx
- Add presentational component for `QuickAdd` (from Figma)
- Will replace existing `CartEntryOfferItem`
> ShopBreakdown: add presentational `QuickAdd` component

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ShopBreakdown/QuickAdd.stories.tsx
- apps/store/src/components/ShopBreakdown/QuickAdd.tsx
- apps/store/src/components/ShopBreakdown/QuickAddAccidentContainer.tsx
- apps/store/src/features/retargeting/SingleTierOffer.tsx
- apps/store/src/utils/useAddToCart.ts
- Refactor `useAddToCart` hook to just return a regular callback function
- Only handle `nextUrl` in `OfferPresenter`
- Remove form in `QuickAdd` component
- The `useAddToCart` hook assumed that we used a form to add to cart but we don't always need to. This change makes it more flexible.
- I also move it to the utility folder to signal that it's used in multiple places.
> ShopBreakdown: simplify `useAddToCart` hook

- apps/store/src/blocks/TrustpilotBlock.tsx
* Updates `TrustpilotBlock` designs.
The idea is to create a component that looks like the image we have today but with real data from _Trustpilot_ API:
It doesn't look exactly alike because some things like gradients is difficult to accomplish only with CSS, but I think it looks good enough.
Can be tested [here](https://hedvig-dot-com-git-gen-918-stylestrustpilot-blok-727cd7-hedvig.vercel.app/se/forsakringar/hemforsakring/jamfor?_storyblok_version=&_storyblok_c=page&_storyblok_lang=default&_storyblok=357425347&_storyblok_rl=1692972742612&_storyblok_tk%5Btoken%5D=a8520f58d10badfecc105fab27c13a8eb7f3d884&_storyblok_tk%5Btimestamp%5D=1692972735&slug=se%2Fforsakringar%2Fhemforsakring%2Fjamfor&_storyblok_tk%5Bspace_id%5D=165473&_storyblok_release=0&draftMode=1)
> GEN-918 - styles(TrustpilotBlock): update due design changes

- apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- Avoid displaying multiple error messages when confirming price intent
- Separate error messages for user errors (UW filters) and system errors (e.g. network error)
- Display generic error dialog when an error occurs while updating price intent data (e.g. network error)
Co-author: @guilhermespopolin 
- We currently first display user error (UW filters) and then quickly switch to a generic error message
> GEN-973 | Fix displaying error messages in purchase form

- apps/store/src/features/retargeting/RetargetingPage.tsx
- apps/store/src/pages/session/resume.tsx
- Create new landing page for CRM Retargeting feature
- Display loading spinner while we determine where to send the user
- The page will communicate with the API and determine where to redirect the user
- The shop session ID will be passed as a query param to make the page static
> GEN-990 | Create new CRM Retargeting Page

- apps/store/src/pages/session/[shopSessionId].tsx
- Avoid forwarding "shopSessionId" query param to the next URL from session resume route
- I think it gets added to the URL by Next.js even if it's not a query param
> GEN-995 | Don't forward shop session query param

- apps/store/src/features/retargeting/retargeting.constants.ts
- apps/store/src/features/retargeting/useRedirectUser.ts
- apps/store/src/features/retargeting/validateUrl.ts
- apps/store/src/pages/session/resume.tsx
- Redirect users with items added to the cart to the cart page
- Check if URL is valid and otherwise redirect to the store page
- Start of logic for where to redirect users in CRM retargeting
- There's a visual bug where we show a white page on the `/se/session/:id` route. I think we want to make this into an API route to make it behave like we want => to use browser loading UI.
> GEN-988 | CRM: redirect users with cart items to the cart

- apps/store/src/features/retargeting/useRedirectUser.ts
- apps/store/src/graphql/ShopSessionRetargeting.graphql
- Retargeting: Redirect users with only one type of price intents to the relevant product details page
- Update to custom shop session query to cover all redirect cases
- We need to get a bit smarter about comparing price intents. E.g. two car price intents for different cars should not result in a redirect to the cart PDP. I want to solve that in a separate PR though.
> GEN-989 | Retargeting: redirect users with one product to PDP

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/ProductItem/RemoveActionButton.tsx
- Checkout page: fix bug so user is redirected to cart if they remove all offers
- Refactor `RemoveActionButton` a little to clean up some mistakes
- The user currently stays on the checkout page even if they remove all offers
> GEN-1037 | Fix: redirect checkout->cart after removing last offer

- apps/store/src/pages/_app.tsx
- apps/store/src/pages/_document.tsx
- apps/store/src/services/CustomerFirst.tsx
This reverts a fix on customer1 load script strategy. The full reasoning behind it can be found in this slack [thread](https://hedviginsurance.slack.com/archives/C041SD67G82/p1693833006219719).
Loading it for all pages is drastically afeting SEO metrics. Let's revert it so customer1 script gets loaded on demand and talk with them aboout solving some issues we're having.
Related with #2973
> Revert "GEN-1078 - fix(customer-first): make sure get's added into the document"

- apps/store/src/components/CartPage/PageDebugDialog.tsx
- apps/store/src/components/ProductPage/PageDebugDialog.tsx
- apps/store/src/features/retargeting/getUserRedirect.test.ts
- apps/store/src/features/retargeting/getUserRedirect.ts
- apps/store/src/pages/api/retargeting/[shopSessionId].ts
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.session` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.session): return an URL instead of a string

- apps/store/src/components/ForeverPage/ForeverPage.tsx
- apps/store/src/features/retargeting/getUserRedirect.ts
- apps/store/src/features/retargeting/useApiRedirectEffect.ts
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.store` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.store): return an URL object instead of a string

- apps/store/src/app/shop-session-debugger/CreateSessionForm.tsx
- apps/store/src/components/CartPage/PageDebugDialog.tsx
- apps/store/src/features/retargeting/getUserRedirect.ts
- apps/store/src/pages/api/session/create.ts
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.cart` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.cart): return an URL object instead of a string

- .github/renovate.json5
- Update automerge schedule in renovate to use am/pm instead of 24h format
- Renovate doesn't seem to understand our current schedule
- This format is more inline with the examples in the [renovate docs](https://docs.renovatebot.com/configuration-options/#schedule)
> Update renovate config to use am/pm

- apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
- apps/store/src/pages/checkout/[shopSessionId]/payment/[status].tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/trustly.tsx
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.confirmation` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.confirmation): return an URL object instead of a string

- apps/store/src/services/trustly/TrustlyIframe.tsx
- apps/store/src/services/trustly/createTrustlyUrl.ts
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.paymentSucess` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.paymentSucess): return an URL object instead of a string

- apps/store/src/services/trustly/TrustlyIframe.tsx
- apps/store/src/services/trustly/createTrustlyUrl.ts
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.paymentFailure` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.paymentFailure): return an URL object instead of a string

- apps/store/src/utils/PageLink.ts
- Changes `PageLink.paymentConnect` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.paymentConnect): return an URL object instead of a string

- apps/store/src/utils/PageLink.ts
- Changes `PageLink.forever` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.forever): return an URL object instead of a string

- apps/store/src/utils/PageLink.ts
- Changes `PageLink.customerService` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.customerService): return an URL object instead of a string

- apps/store/src/utils/PageLink.ts
- Changes `PageLink.deductibleHelp` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.deductibleHelp): return an URL object instead of a string

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.privacyPolicy` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.privacyPolicy): return an URL object instead of a string

- apps/store/src/components/DebugDialog/DebugShopSessionSection.tsx
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.apiSessionReset` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.apiSessionReset): return an URL object instead of a string

- apps/store/src/utils/PageLink.ts
- Changes `PageLink.apiSessionCreate` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.apiSessionCreate): return an URL object instead of a string

- apps/store/src/utils/PageLink.ts
- Changes `PageLink.apiCampaign` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.apiCampaign): return an URl object instead of a string

- apps/store/src/pages/payment/connect-legacy/start.tsx
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.paymentConnectLegacy` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.paymentConnectLegacy): return an URL object instead of a string

- apps/store/src/services/adyen/useTokenizePaymentDetails.ts
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.apiAdyenCallback` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.apiAdyenCallback): return an URL object instead of a string

- apps/store/src/pages/api/adyen-callback/[locale].ts
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.paymentConnectLegacySucess` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.paymentConnectLegacySucess): return an URL object instead of a string

- apps/store/src/pages/payment/connect-legacy/start.tsx
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.apiAuthExchange` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.apiAuthExchange): return an URL object instead of a string

- apps/store/src/features/retargeting/useApiRedirectEffect.ts
- apps/store/src/utils/PageLink.ts
- Changes `PageLink.apiRetargeting` return type: `string` --> `URL`
> GEN-1065 - refact(PageLink.apiRetargeting): return an URL object instead of a string

- apps/store/src/blocks/QuickPurchaseBlock.tsx
- apps/store/src/components/QuickPurchaseForm/QuickPurchaseForm.stories.tsx
- apps/store/src/components/QuickPurchaseForm/QuickPurchaseForm.tsx
- `QuickPurchaseBlock`: add option to attribute shop session to a partner
- Create a new shop session if this option is passed down from the CMS
- This is a bit of a hack -- would be better to have an endpoint to attribtue an existing shop session to a partner (I think...)
- We would like to use this approach for SAS to avoid having to redirect via `/api/recommendation/...`
> GEN-1088 | Add support for 'attributed_to' in `QuickPurchaseBlock`

- apps/store/src/components/QuickAdd/QuickAdd.stories.tsx
- apps/store/src/components/QuickAdd/QuickAdd.tsx
- Revert back to the existing color, better contrast from the actual cart items
> GEN-1085 | QuickAdd: use blue background
