- apps/onboarding/src/pages/_document.tsx
To get the correct Html lang attribute, I had to map over the locale from Next. 
[GRW-1161]: https://hedvig.atlassian.net/browse/GRW-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1161 / Fix SEO bugs in onboarding

- apps/onboarding/src/hooks/useSetupQuoteCartEffect.ts
- apps/onboarding/src/pages/_app.tsx
- apps/onboarding/src/pages/_middleware.ts
Remove code in middleware.
The middleware implementation fails to often. Safer to do it client side.
That will also give us faster loading of the page.
> Fix / Move quote cart creation to client

- apps/store/package.json
- apps/store/src/components/PriceCalculator/FormGroup.tsx
- apps/store/src/components/PriceCalculator/InputDynamic.tsx
- apps/store/src/components/PriceCalculator/InputRadio.tsx
- apps/store/src/components/PriceCalculator/InputSelect.tsx
- apps/store/src/components/PriceCalculator/PriceCalculator.constants.ts
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/PriceCalculator/PriceCalculator.types.ts
- apps/store/src/components/PriceCalculator/TickIcon.tsx
- apps/store/src/components/ProductPage/ProductPage.tsx
- packages/ui/src/components/InputField/InputField.tsx
Add radio button input.
Update styles for select input.
The wireframes show a new direction with less emphasis on the grouping of inputs.
> Update price calculator to match wireframes

- apps/store/src/components/PriceCalculator/FormGroup.tsx
- apps/store/src/components/PriceCalculator/PriceCalculator.constants.ts
- apps/store/src/components/PriceCalculator/PriceCalculator.stories.tsx
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/PriceCalculator/usePriceCalculator.ts
- apps/store/src/components/ProductPage/ProductPage.tsx
- apps/store/src/services/mockPriceCalculatorService.ts
Add hook to initialize price calculator.
I wanna keep the price calculator pretty simple and not add too much complexity in it.
Now it's just responsible for rendering the form, and calling submit.
> Feature / Add mock service for price calculator

- apps/onboarding/package.json
- apps/store/package.json
- apps/store/src/pages/_app.tsx
- apps/store/src/services/apollo/client.ts
- yarn.lock
Upgrade Apollo Client in onboarding.
> Feature / Setup Apollo Client in store

- apps/store/package.json
- apps/store/src/components/PriceCalculator/FormGroup.tsx
- apps/store/src/components/PriceCalculator/InputRadio.tsx
- apps/store/src/components/PriceCalculator/PriceCalculator.constants.ts
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/PriceCalculator/PriceCalculator.types.ts
- apps/store/src/pages/price.tsx
- apps/store/src/services/priceForm/PriceFormService.ts
- yarn.lock
Add radix accordion as dependency.
> Feature / Add support for input groups in price calculator

- apps/store/src/pages/_app.tsx
> Feature / Remove custom Emotion cache setup

- apps/store/package.json
- apps/store/src/components/ProductPage/ProductPage.tsx
- yarn.lock
Adds a basic tabs component into Product Page. I don't know exactly how far should I go about styles/functionality. Please, let me know if there's something missing.
Part of the [design](https://www.figma.com/file/8Y2rd4TZDjTjn8LNy7p83T/Hedvig.com-Wireframes?node-id=1%3A57)
> GRW-1246: product details tab

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPage.tsx
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPage.types.ts
- apps/store/src/pages/checkout/payment.tsx
> Feature / Add view-model for checkout payment page

- apps/store/index.d.ts
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPage.tsx
- apps/store/src/services/trustly/Trustly.constants.ts
- apps/store/src/services/trustly/TrustlyWidget.tsx
- apps/store/src/services/trustly/useTrustly.ts
> Feature / Add Trustly service

- apps/store/package.json
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPage.tsx
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPageAdyen.tsx
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPageTrustly.tsx
- apps/store/src/pages/checkout/payment/adyen.tsx
- apps/store/src/pages/checkout/payment/trustly.tsx
- apps/store/src/services/adyen/AdyenCheckout.tsx
- yarn.lock
> Feature / Add Adyen service (skeleton)

- apps/store/src/components/PriceCard/PriceCard.constants.ts
- apps/store/src/components/PriceCard/PriceCard.stories.tsx
- apps/store/src/components/PriceCard/PriceCard.tsx
- apps/store/src/components/PriceCard/TickIcon.tsx
- apps/store/src/components/SpaceFlex/SpaceFlex.tsx
Add Storybook stories:
Add align prop to SpaceFlex component.
Needed for POC.
> Feature / Add PriceCard component

- apps/store/src/components/PriceCalculator/PriceCalculator.constants.ts
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/PriceCalculator/StepIconDefault.tsx
- apps/store/src/components/PriceCalculator/StepIconValid.tsx
- apps/store/src/components/TestPricePage/TestPricePage.tsx
- apps/store/src/services/formTemplate/data/SWEDISH_APARTMENT_UI.ts
Update status indicator icons.
Add price card to price calculator test page.
Update UI schema according to design.
> Feature / Tweak design of price calculator

- packages/ui/src/lib/theme/theme.ts
- packages/ui/src/lib/theme/typography.ts
Extract typography theme values
Turn font-size scale into object to satisfy TS https://github.com/system-ui/theme-specification/issues/1#issuecomment-480069217
> Extract typography theme values

- apps/store/src/components/PriceCalculator/Accordion.tsx
- apps/store/src/components/TestPricePage/TestPricePage.tsx
- apps/store/src/services/formTemplate/FormTemplateService.ts
Fix template API so it returns null when no template is found.
Fix gradient top to bottom.
Fix layout issue in Accordion.
Update icons used in PriceCard.
> Fix / Small tweaks

- apps/fake-api/public/schema.graphql
Implement changes described here: https://github.com/HedvigInsurance/rfc/pull/14
Would like to try out this API
> Feature / Replace Session with Price Intent schema

- apps/store/next.config.js
- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/blocks/HeroBlock.tsx
- apps/store/src/blocks/PageBlock.tsx
- apps/store/src/components/HomePage/HomePage.tsx
- apps/store/src/services/storyblok/storyblok.ts
- packages/scripts/.eslintrc.js
Add skeleton hero and button block to Storyblok
A Hero have a Content area where you will be able to add headings and text and Buttons where you can add one or more buttons. The hero then renders the nested blocks.
https://user-images.githubusercontent.com/6661511/179958139-a0205ac2-8252-43d3-b4b7-219471407267.mov
To make the POC
> Feat / Add hero and button block

- .gitignore
- apps/store/.env
- apps/store/codegen.yml
- apps/store/graphql/ShopSessionCreate.graphql
- apps/store/package.json
- apps/store/src/services/apollo/generated.ts
- apps/store/src/services/graphql/generated.ts
- apps/store/src/services/graphql/requester.ts
- apps/store/src/services/graphql/sdk.ts
- yarn.lock
Here we go again with all the seemingly irrelevant dev dependencies that we just need to run the codegen 🙄
Setup non-Apollo GraphQL client.
Add .env file with defaults.
Setup is similar to onboarding except:
- The graphql endpoint is referenced by env var in the codegen config. This requires us to use a `.env` file. In Next.js this is the file we should use to set default environment variables so I think it fits pretty well :)
- I put a "graphql" folder outside "src" to group all mutation/query definitions -- good/bad?
Type safety.
> Feature / Setup GraphQL codegen

- apps/store/graphql/PriceIntent.graphql
- apps/store/graphql/PriceIntentCreate.graphql
- apps/store/graphql/PriceIntentDataUpdate.graphql
- apps/store/graphql/PriceIntentFragment.graphql
- apps/store/graphql/ShopSession.graphql
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/TestPricePage/TestPricePage.helpers.ts
- apps/store/src/components/TestPricePage/TestPricePage.tsx
- apps/store/src/components/TestPricePage/TestPricePage.types.ts
- apps/store/src/pages/api/price/[productId].ts
- apps/store/src/pages/price/[id].tsx
- apps/store/src/services/apollo/generated.ts
- apps/store/src/services/graphql/generated.ts
- apps/store/src/services/priceIntent/CookiePersister.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
- apps/store/src/services/priceIntent/ServerCookiePersister.ts
- apps/store/src/services/priceIntent/ShopSessionService.ts
- apps/store/src/services/priceIntent/priceIntent.constants.ts
- apps/store/src/services/priceIntent/priceIntent.types.ts
- Handle mutation call in API route.
- Pass product data to price page (test).
- Update Price Intent service.
- Add service for Shop Session.
To enable us to test and mock responses for the price calculator.
> Feature / Integrate Price Intent API

- apps/store/package.json
- apps/store/src/components/CartNotification/CartNotification.stories.tsx
- apps/store/src/components/CartNotification/Dialog.tsx
- apps/store/src/components/CartNotification/Header.tsx
- apps/store/src/components/CartNotification/Main.tsx
- apps/store/src/components/CartNotification/ProductItem.tsx
- yarn.lock
Add purchase notification (replaces mini cart).
Add dependency on radix dialog.
I used a dialog / modal since I think that's what it really is. I was considering a toast but I think this is more accurate.
I didn't add the close button/icon just since the designs are very early stage and it works to "click outside".
I also didn't setup a very component to pull everything together in favor of a more flexible approach with individual components. When we notice we have a stable component that's well defined we can build one.
[GRW-1265]: https://hedvig.atlassian.net/browse/GRW-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature / Add cart notification component

- apps/store/src/pages/api/checkout.ts
- apps/store/src/pages/cart/review.tsx
- apps/store/src/utils/isLocale.test.ts
- apps/store/src/utils/isLocale.ts
Add isLocale utility function.
> Feature / Keep locale when redirecting from API route

- apps/fake-api/public/schema.graphql
See title
See discussion: https://hedviginsurance.slack.com/archives/C03D6G9FKCH/p1658473440322219
[GRW-1277]: https://hedvig.atlassian.net/browse/GRW-1277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature / Make shop session link explicit in API

- apps/store/src/components/ProductCard/ProductCard.stories.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
- packages/ui/src/components/HeadingNew/HeadingNew.tsx
- packages/ui/src/index.tsx
- turbo.json
[Screen Recording 2022-07-22 at 14.05.26.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/80f44755-5a59-460d-b2c9-8fc949a261fc/Screen%20Recording%202022-07-22%20at%2014.05.26.mov)
Also fixed some issues I found in the HeadingNew component.
And exported it from the UI lib => or is it too early @gustaveen?
Aslo added build dependency for storybook script.
For PoC
> Feature / Add visual product card component

- apps/store/src/blocks/ProductCardBlock.tsx
- apps/store/src/blocks/ProductGridBlock.tsx
- apps/store/src/components/ProductCard/ProductCard.stories.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
- apps/store/src/components/ProductGrid/ProductGrid.stories.tsx
- apps/store/src/components/ProductGrid/ProductGrid.tsx
- apps/store/src/services/storyblok/storyblok.ts
- packages/ui/src/components/HeadingNew/HeadingNew.tsx
- packages/ui/src/index.tsx
- turbo.json
Add product grid component.
Add product card + grid blocks.
Integrate with Storyblok.
Display on home page.
I wasn't sure how general purpose to make the grid component so I just went with the specific version for now.
Also wasn't sure how we will work with layouts in the CMS. Therefore there's no spacing between the components.
Perhaps we should add some Spacer block? I'll let you decide @gustaveen!
> Feature / Add Product Grid component

- apps/fake-api/public/schema.graphql
Update Price Intent schema to avoid nesting mutation as much.
Add buyers identity input to create shop session mutation.
Remove create cart mutation (will be done lazily).
See discussion here: https://hedviginsurance.slack.com/archives/C03CCKQPZTR/p1658758510550689
> Feature / Refactor Price Intent schema

- apps/store/src/blocks/SpacerBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
Add spacer block to the CMS setup.
To be able to separate content with empty space.
Let's discuss more when @gustaveen is back. I know he's been thinking about this - but just so we can make things look good :)
> Feature / Add Spacer block to CMS

- apps/fake-api/public/schema.graphql
We want to move this logic to the API.
We will basically always want to make sure that we have a fresh session for the relevant market.
> Feature / Add find or create query for Shop Session

- apps/store/src/graphql/PriceIntent.graphql
- apps/store/src/graphql/PriceIntentConfirm.graphql
- apps/store/src/graphql/PriceIntentCreate.graphql
- apps/store/src/graphql/PriceIntentDataUpdate.graphql
- apps/store/src/mocks/PriceIntentMock/PriceIntentMock.constants.ts
- apps/store/src/mocks/PriceIntentMock/PriceIntentMock.helpers.ts
- apps/store/src/mocks/PriceIntentMock/PriceIntentMock.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.constants.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.helpers.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.ts
- apps/store/src/mocks/handlers.ts
- apps/store/src/mocks/helpers.ts
- apps/store/src/services/apollo/generated.ts
- apps/store/src/services/graphql/generated.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
- apps/store/src/services/priceIntent/priceIntent.types.ts
- package.json
Update requests and mocks to include the global session nesting.
Make it more explicit in the API that we always need to know which session we act on.
> Feature / Update GraphQL requests to use global shop session

- apps/store/src/graphql/Cart.graphql
- apps/store/src/graphql/CartFragment.graphql
- apps/store/src/graphql/CartLinesAdd.graphql
- apps/store/src/graphql/CartLinesRemove.graphql
- apps/store/src/mocks/CartMock/CartMock.constants.ts
- apps/store/src/mocks/CartMock/CartMock.helpers.ts
- apps/store/src/mocks/CartMock/CartMock.ts
- apps/store/src/mocks/PriceIntentMock/PriceIntentMock.helpers.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.helpers.ts
- apps/store/src/mocks/db.ts
- apps/store/src/mocks/helpers.ts
- apps/store/src/services/apollo/generated.ts
- apps/store/src/services/graphql/generated.ts
Add mocks for shopping cart API.
Refactor other mocks to use a shared database.
Update to use shared line items.
Line items exist both for price intent and cart so I find it easiest to put them in a shared DB.
Will make it a little less maintainable but I think it's worth the tradeoff to have a more realistic setup.
> Feature / Add mocks for cart API

- apps/fake-api/public/schema.graphql
> Sync fake-api schema to match implementation

- apps/store/src/graphql/CartLinesAdd.graphql
- apps/store/src/graphql/CartLinesRemove.graphql
- apps/store/src/graphql/PriceIntentConfirm.graphql
- apps/store/src/graphql/PriceIntentCreate.graphql
- apps/store/src/graphql/PriceIntentDataUpdate.graphql
- apps/store/src/mocks/PriceIntentMock/PriceIntentMock.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.ts
- apps/store/src/services/apollo/generated.ts
- apps/store/src/services/cart/CartService.ts
- apps/store/src/services/graphql/generated.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
> Update implementation to match nested schema

- apps/store/public/mockServiceWorker.js
- apps/store/src/lib/l10n/locales.ts
- apps/store/src/lib/l10n/types.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.helpers.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.ts
- apps/store/src/services/cart/useCart.ts
- apps/store/src/services/shopSession/ShopSessionService.ts
Update MSW file.
Add CountryCode to locales setup.
Add typename for Cart in mocks.
Add client side setup for ShopSessionService.
> GRW-1291 / Feature / Add useCart hook

- apps/store/src/blocks/PriceCalculator.tsx
- apps/store/src/blocks/ProductSummary.tsx
- apps/store/src/components/CartNotification/Dialog.tsx
- apps/store/src/components/PriceCard/PriceCard.tsx
- apps/store/src/components/ProductPage/ProductPage.tsx
- apps/store/src/components/ProductPage/ProductPage.types.ts
- apps/store/src/components/ProductPage/ProductSummary/ProductSummary.tsx
- apps/store/src/components/ProductPage/Tabs.tsx
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/priceIntent/priceIntent.types.ts
- apps/store/src/services/storyblok/storyblok.ts
- Add PriceCalculator block.
- Add ProductSummary block.
- Extract Tabs and remove from ProductPage.
- Add StoryblokBlockName enum.
- Calculate 'extra props' based on ProductPage context.
> Feature / Integrate CMS on Product Page

- apps/store/src/components/PriceCalculator/useTranslateTextLabel.ts
- apps/store/src/pages/[...slug].tsx
> Fix / Exclude product links from content pages

- apps/fake-api/public/schema.graphql
> Update ShopSession schema

- apps/store/src/blocks/PriceCalculator.tsx
- apps/store/src/blocks/ProductSummary.tsx
- apps/store/src/components/CartList/CartList.tsx
- apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts
- apps/store/src/components/ProductPage/ProductPage.helpers.ts
- apps/store/src/components/ProductPage/ProductPage.tsx
- apps/store/src/components/SiteFooter/SiteFooter.stories.tsx
- apps/store/src/components/StorePage/StorePage.tsx
- apps/store/src/lib/PageLink.ts
- apps/store/src/pages/api/price/[productId].ts
Fix bug in price form API redirect.
Trying to make it more type-safe to derive the block context props.
> Refactor / Calculate explicit block context props

- apps/store/src/components/PriceCalculatorForm/PriceCalculatorForm.helpers.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.helpers.ts
- apps/store/src/pages/api/cart/[lineId]/add.ts
- apps/store/src/pages/api/cart/[lineId]/remove.ts
- apps/store/src/pages/api/price/[productId].ts
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/cart/useCart.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
- apps/store/src/services/shopSession/ShopSession.helpers.ts
- apps/store/src/services/shopSession/ShopSessionService.ts
Use Apollo Client in ShopSessionService.
Refactor ShopSessionService helpers.
We already fetch the ShopSession server-side so we should also update the ApolloCache.
This way we can get it client-side without fetching from the network.
> Feature / Prefetch ShopSession server-side

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/CartNotification/CartNotification.stories.tsx
- apps/store/src/components/CartNotification/CartNotification.tsx
- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/CartNotification/ProductItem.tsx
- apps/store/src/components/PriceCalculatorForm/PriceCalculatorForm.helpers.ts
- apps/store/src/components/PriceCard/PriceCard.stories.tsx
- apps/store/src/components/PriceCard/PriceCard.tsx
- apps/store/src/components/ProductPage/ProductPage.helpers.ts
- apps/store/src/components/ProductPage/useHandleClickAddToCart.ts
- apps/store/src/lib/l10n/getLocale.ts
- apps/store/src/lib/l10n/locales.ts
- apps/store/src/pages/api/price/[productId].ts
- apps/store/src/services/priceIntent/PriceIntent.helpers.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
- apps/store/src/services/shopSession/ShopSession.helpers.ts
- apps/store/src/utils/useCurrencyFormatter.ts
Refactor CartNotification component.
Refactor PriceIntent service helpers.
Add currency code to locales (will be moved to API).
Add onSuccess handler to add to cart hook.
Reset price intent after adding to cart.
Make ShopSession optional in PriceIntent session.
> Implement cart notification after add to cart

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/PriceCard/PriceCard.stories.tsx
- apps/store/src/components/PriceCard/PriceCard.tsx
- apps/store/src/components/ProductPage/ProductPage.helpers.ts
- apps/store/src/components/ProductPage/ProductPage.tsx
- apps/store/src/components/ProductPage/ProductPage.types.ts
- apps/store/src/graphql/CartFragment.graphql
- apps/store/src/graphql/ShopSessionFindOrCreate.graphql
- apps/store/src/lib/l10n/locales.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.helpers.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.ts
- apps/store/src/mocks/db.ts
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/apollo/generated.ts
- apps/store/src/services/graphql/generated.ts
- apps/store/src/utils/useCurrencyFormatter.ts
Remove currency code from locales.
Pass shop session to client to use for storyblok bloks.
> Feature / Access currency code from ShopSession

- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/TopMenu/ShoppingCartMenuItem.tsx
Add cart query to TopMenu.
Refactor ShoppingCartMenuItem to display notification on top-right.
We should get the items in the cart from the API.
The design updates are according to Figma.
[GRW-1309]: https://hedvig.atlassian.net/browse/GRW-1309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show number of items in cart in TopMenu

- apps/fake-api/package.json
- apps/market-web/package.json
- apps/onboarding/package.json
- packages/ui/package.json
> Add support for caching ESLint across all packages

- apps/store/package.json
- package.json
- turbo.json
Add build pipeline for Storybook.
Now we can deploy storybook with Vercel so we can preview changes in every PR.
There's also another option, the official Storybook deploy platform: https://www.chromatic.com/features/publish
We could look into it since it's offered for free but perhaps we start with this.
> Add support for building and deploying Storybook

- apps/store/src/components/ProductPage/PriceFooter/PriceFooter.stories.tsx
- apps/store/src/components/ProductPage/PriceFooter/PriceFooter.tsx
- apps/store/src/components/ProductPage/ProductSummary/ProductSummary.stories.tsx
Group product page components in Storybook.
Make it clear in Storybook which components should be used only on certain pages.
[GRW-1301]: https://hedvig.atlassian.net/browse/GRW-1301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add visual component for sticky price footer

- apps/store/package.json
- apps/store/src/components/ProductPage/PriceFooter/PriceFooter.stories.tsx
- apps/store/src/components/ProductPage/PriceFooter/PriceFooter.tsx
- apps/store/src/components/ProductPage/ProductSummary/ProductSummary.stories.tsx
- apps/store/src/components/ProductPage/ScrollPast/ScrollPast.stories.tsx
- apps/store/src/components/ProductPage/ScrollPast/ScrollPast.tsx
- apps/store/src/components/ProductPage/ScrollToButton/ScrollToButton.stories.tsx
- apps/store/src/components/ProductPage/ScrollToButton/ScrollToButton.tsx
- yarn.lock
Add framer-motion as dependency to store app.
Add basic pill button component.
Add example usage in Storybook.
[Screen Recording 2022-08-01 at 17.24.01.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/fea3ecb4-7d05-4507-9acc-75718d36a687/Screen%20Recording%202022-08-01%20at%2017.24.01.mov)
I wanted to create an intuitive API. Please check the Storybook example.
We will probably have to update this since we need to display either the price footer or this scroll-to-button based on if there is a calculated price or not. But at least it shows how I think it could work.
[GRW-1302]: https://hedvig.atlassian.net/browse/GRW-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add visual scroll to button component for ProductPage

- apps/store/src/blocks/ProductSlideshowBlock.tsx
- apps/store/src/blocks/TopPickCardBlock.tsx
- apps/store/src/components/Slideshow/Slideshow.stories.tsx
- apps/store/src/components/Slideshow/Slideshow.tsx
- apps/store/src/services/storyblok/storyblok.ts
Adds Slideshow Storyblok block
> feat(GRW-1307): added product slideshow block

- apps/market-web/Procfile
- apps/onboarding/Procfile
> Remove Heroku Procfile(s)

- .github/workflows/ci.yml
- .github/workflows/cypress.yml
- package.json
- turbo.json
- yarn.lock
Split CI and cypress workflows.
Setup remote caching in ci workflow.
Add inputs to store#codegen pipeline.
I split up the gh workflows since it should be enough to run e2e tests on every push to main branch (not every PR).
I updated the ci workflow according to: https://turborepo.org/docs/ci/github-actions
I added turborepo inputs according to new features described here: https://turborepo.org/blog/turbo-1-3-0
I setup remote caching to speed up our CI pipeline.
[GRW-1315]: https://hedvig.atlassian.net/browse/GRW-1315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update to turborepo 1.4

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/blocks/AccordionItemBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
Link Accordion and AccordionItem to CMS
This is base block for things like FAQ, menus, etc.  No design yet.  No markdown rendering for content yet
[GRW-1281]: https://hedvig.atlassian.net/browse/GRW-1281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1281 Feature/add accordion block

- apps/fake-api/public/schema.graphql
> Add start date mutation to fake api

- apps/fake-api/public/schema.graphql
> Remove get or create shop session mutation

- CONTRIBUTING.md
Removed the mention of not using react version 17 and the reason for importing react. 
Looks like we've been on react 17 for some time now.
> Remove old info from CONTRIBUTING.md

- apps/store/src/components/CartReviewPage/CartReviewPage.tsx
- apps/store/src/components/CartReviewPage/CartReviewPage.types.ts
- apps/store/src/components/CartReviewPage/useResizeObserver.ts
- apps/store/src/components/PriceBreakdown.tsx/PriceBreakdown.tsx
- apps/store/src/components/SpaceFlex/SpaceFlex.tsx
- apps/store/src/pages/cart/review.tsx
Add visual components for cart review page.
> Add visual components for Cart Review Page

- apps/store/src/components/CartReviewPage/CartReviewPage.tsx
- apps/store/src/components/CartReviewPage/CartReviewPage.types.ts
- apps/store/src/components/CartReviewPage/useResizeObserver.ts
- apps/store/src/components/PriceBreakdown.tsx/PriceBreakdown.tsx
- apps/store/src/components/SpaceFlex/SpaceFlex.tsx
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.constants.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.ts
- apps/store/src/pages/cart/review.tsx
- apps/store/src/services/shopSession/ShopSession.helpers.ts
- apps/store/src/services/shopSession/ShopSessionService.ts
Add ShopSession query.
Update mocks to cover the new query.
Update ShopSessionService to use the new query.
The new query will be used in places where we expect a ShopSession to already exist.
For example in the checkout.
[GRW-1322]: https://hedvig.atlassian.net/browse/GRW-1322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add ShopSession query

- .github/workflows/cypress.yml
- apps/onboarding/package.json
- apps/store/package.json
- yarn.lock
After upgrade yarn is stricter with env variables and never-existing $PORT became an error.  We can work without it
[GRW-1330]: https://hedvig.atlassian.net/browse/GRW-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1330/fix/update cypress scripts for yarn3

- .github/workflows/cypress.yml
- apps/onboarding/package.json
- apps/store/package.json
> Grw 1330/fix/update cypress scripts for yarn3

- apps/store/src/components/CartReviewPage/CartReviewPage.constants.ts
- apps/store/src/components/CartReviewPage/CartReviewPage.tsx
- apps/store/src/components/CartReviewPage/CartReviewPage.types.ts
- apps/store/src/components/CartReviewPage/useHandleSubmitCartReview.ts
- apps/store/src/lib/PageLink.ts
- apps/store/src/pages/api/cart/review.ts
- apps/store/src/pages/cart/review.tsx
- apps/store/src/services/cart/CartService.ts
Add API endpoint for cart review form
Add skeleton start date update function in cart service.
Ability to update start dates.
> Add API endpoint for cart review form

- apps/store/src/components/CartReviewPage/useHandleSubmitCartReview.ts
- apps/store/src/graphql/CartFragment.graphql
- apps/store/src/graphql/StartDateUpdate.graphql
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.constants.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.helpers.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.ts
- apps/store/src/mocks/db.ts
- apps/store/src/pages/api/cart/review.ts
- apps/store/src/pages/cart/review.tsx
- apps/store/src/services/cart/CartService.ts
- apps/store/src/services/shopSession/ShopSessionService.ts
Integrate StartDateUpdate mutation for the cart review page
Only redirect from cart review on successful form submission.
Add mocks for start date mutation.
Implement server side fetching for cart review page.
Now we can really test the cart review page as if it was using the real API!
[GRW-1322]: https://hedvig.atlassian.net/browse/GRW-1322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Integrate StartDateUpdate mutation for the cart review page

- apps/store/src/blocks/ButtonBlock.tsx
Center button horizontally.
Add variant option to CMS.
> GRW-1348 / Feature / Update button block to match design

- apps/store/src/components/SiteFooter/SiteFooter.constants.ts
- apps/store/src/components/SiteFooter/SiteFooter.tsx
See title.
I decided to hard code the values just so we can get an idea how it will look/work.
I believe @gustaveen will have more input on how we can get this information from the CMS.
[GRW-1341]: https://hedvig.atlassian.net/browse/GRW-1341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1341 / Feature / Add navigation accordion to site footer

- apps/store/src/components/CartReviewPage/CartReviewPage.tsx
Fix link element on Cart Review page
Disable button to continue unless there's items in the cart.
> Fix link element on Cart Review page

- README.md
> Update yarn version in README 

- apps/store/src/blocks/ImageBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
Primitive component.
I'm starting to realize that adding padding to each primitive block makes it harder to nest inside each other. Perhaps we can discuss how to handle various layout concerns @gustaveen?
> Add ImageBlock to CMS setup

- apps/store/src/components/ProductPage/ProductPage.helpers.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.helpers.ts
- apps/store/src/pages/cart/review.tsx
- apps/store/src/services/priceIntent/PriceIntentService.ts
- turbo.json
Fix code as needed after updating to use the Storefront API schema.
> Update transforms after API schema update

- apps/store/src/components/Timeline/CheckCircleIcon.tsx
- apps/store/src/components/Timeline/Timeline.stories.tsx
- apps/store/src/components/Timeline/Timeline.tsx
Based on: https://mui.com/material-ui/react-timeline/
We deviated slightly from the Figma designs but it should be good enough for the prototype.
Co-authored with @simonauner.
[GRW-1351]: https://hedvig.atlassian.net/browse/GRW-1351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1351 / Add Timeline component

- apps/store/src/components/Table/Table.stories.tsx
- apps/store/src/components/Table/Table.tsx
> Add base Table component

- apps/store/src/pages/api/cart/[lineId]/add.ts
- apps/store/src/pages/api/cart/[lineId]/remove.ts
- apps/store/src/pages/api/cart/review.ts
- apps/store/src/services/cart/CartService.ts
Replace graphql SDK with Apollo Client server side.
I want to remove graphql SDK so we just end up with one way to query graphql.
> Use Apollo Client in CartService

- apps/store/src/components/PriceCalculatorForm/PriceCalculatorForm.helpers.ts
- apps/store/src/pages/api/cart/[lineId]/add.ts
- apps/store/src/pages/api/cart/[lineId]/remove.ts
- apps/store/src/pages/api/cart/review.ts
- apps/store/src/pages/api/price/[productId].ts
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/cart/CartService.ts
- apps/store/src/services/priceIntent/PriceIntent.helpers.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
Replace GraphQL SDK in PriceIntentService with Apollo Client.
This is the last place we use the GraphQL => then we can remove in and just use Apollo Client for all GraphQL requests.
> Use Apollo Client for PriceIntentService

- apps/store/src/services/priceIntent/PriceIntentService.ts
> Handle failing mutations

- apps/store/src/components/ProductPage/Tabs.tsx
Also fix colors so they match the theme.
This is how it looks even on iPhone SE now:
...and for very small devices:
> Update Tabs styling to be more compact

- apps/store/src/components/Page/Page.tsx
- apps/store/src/pages/[...slug].tsx
- apps/store/src/pages/index.tsx
- apps/store/src/services/storyblok/storyblok.ts
Add global story data to pages
To be able to fetch content from a the content type we call `global` where we will store header, menus, footer etc
Let me know if you have other ideas how to handle it :)
> GRW-1359 / Add global story

- apps/store/src/components/ContactSupport/ContactSupport.tsx
Before:
After:
I removed the styling based on viewport since I think that should be taken care of by the component. We shouldn't control it with JS. It also causes issues with SSR so not a good idea.
> Tweak design of ContactSupport block

- apps/store/src/components/ConfirmationPage/ConfirmationPage.helpers.ts
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
- apps/store/src/pages/confirmation.tsx
Update design according to Figma.
Parse user-agent header to select relevant app store.
Just another update.
Still need to implement proper app store download buttons but will do that in a separate PR.
Will also integrate the CMS so editors can customize the page but in another PR.
> Implement confirmation page

- apps/store/src/graphql/CartLinesAdd.graphql
- apps/store/src/graphql/CartLinesRemove.graphql
- apps/store/src/graphql/PriceIntentConfirm.graphql
- apps/store/src/graphql/PriceIntentCreate.graphql
- apps/store/src/graphql/PriceIntentDataUpdate.graphql
- apps/store/src/graphql/StartDateUpdate.graphql
- apps/store/src/mocks/PriceIntentMock/PriceIntentMock.ts
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.ts
- apps/store/src/services/cart/CartService.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
Update following mutations
- cartLinesAdd
- cartLinesRemove
- cardLineStartDateUpdate
- priceIntentCreate
- priceIntentConfirm
This fixes build error in main
[GRW-1393]: https://hedvig.atlassian.net/browse/GRW-1393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update graphQL schema for recently changed cart operations

- .github/PULL_REQUEST_TEMPLATE.md
This isn't really needed now that we deploy from PR to production.
> Remove product update checklist item

- apps/onboarding/src/middleware.ts
Remove async keyword from sync function.
Add log message.
Bug.
> Fix campaign code middleware bug

- apps/store/src/components/PriceCalculatorForm/DynamicField.tsx
- apps/store/src/components/PriceCalculatorForm/PriceCalculatorForm.helpers.ts
- apps/store/src/components/PriceCalculatorForm/PriceCalculatorForm.stories.tsx
- apps/store/src/services/formTemplate/FormTemplate.types.ts
- apps/store/src/services/formTemplate/combineFormTemplate.ts
- apps/store/src/services/formTemplate/data/SWEDISH_APARTMENT_UI.ts
- apps/store/src/services/persister/ServerCookiePersister.ts
Add hidden input field option.
Restrict default form value to string (for now).
Refactor combineFormTemplate to avoid ts-ignore comments.
Update form template for Swedish apartment.
Fix bug in ServerCookiePersister to allow calling save multiple times.
Make calculating and adding home insurance to the cart possible!
> Fix calculating price for Swedish apartment

- apps/store/src/services/formTemplate/combineFormTemplate.ts
> Fix bug in combineFormTemplate

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/blocks/AccordionItemBlock.tsx
- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/blocks/CheckListBlock.tsx
- apps/store/src/blocks/ContactSupportBlock.tsx
- apps/store/src/blocks/ContentBlock.tsx
- apps/store/src/blocks/HeadingBlock.tsx
- apps/store/src/blocks/HeroBlock.tsx
- apps/store/src/blocks/ImageBlock.tsx
- apps/store/src/blocks/PageBlock.tsx
- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/blocks/ProductCardBlock.tsx
- apps/store/src/blocks/ProductGridBlock.tsx
- apps/store/src/blocks/ProductSlideshowBlock.tsx
- apps/store/src/blocks/ProductSummaryBlock.tsx
- apps/store/src/blocks/SpacerBlock.tsx
- apps/store/src/blocks/TabsBlock.tsx
- apps/store/src/blocks/TextBlock.tsx
- apps/store/src/blocks/TopMenuBlock.tsx
- apps/store/src/blocks/TopPickCardBlock.tsx
- apps/store/src/components/ProductPage/ProductPage.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
- Less boilerplate
- Block declarations are more self-contained now
[GRW-1403]: https://hedvig.atlassian.net/browse/GRW-1403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Simplify block name mapping, put block names into block component files

- apps/store/src/components/CartCard/CartCard.tsx
- apps/store/src/components/CartNotification/CartNotification.stories.tsx
- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/CartPage/CartList.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/Dialog/Dialog.tsx
- apps/store/src/pages/cart/index.tsx
Add Dialog base component.
Refactor CartNotification.
Update CartPage to match figma design.
Mostly design updates.
We have two slightly different Dialog so I thought it made sense to extract a base Dialog component.
> Tweak Cart Page design

- apps/store/src/blocks/TimelineBlock.tsx
- apps/store/src/blocks/TimelineItemBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
Similar design to Accordion block - overall block with items field and item block with title and body
[GRW-1378]: https://hedvig.atlassian.net/browse/GRW-1378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1378/feat/timeline block

- CONTRIBUTING.md
Discussed and agreed in daily.
> Add Storyblok conventions about specific nested blocks

- apps/store/.env.development
> Remove development environment variables

- apps/store/src/pages/cart/index.tsx
I think it makes sense that we don't fail the page just because there's no shop session.
> Cart page: get or create shop session

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/pages/cart/index.tsx
> Implement Cart Page empty state

- apps/store/src/components/CartCard/CartCard.tsx
- apps/store/src/components/CartCard/useForm.ts
- apps/store/src/pages/api/cart/[lineId]/remove.ts
Add useForm hook to override default form submit behavior.
Setup basic state in CartCard for pending UI.
Skip Dialog.Close since it requires button to forward ref.
Update remove line item API route to handle errors.
I want to add this without breaking how things work without JS. Just progressive enhancement :)
> Implement pending UI for remove from cart

- apps/store/src/pages/cart/index.tsx
- apps/store/src/pages/products/[product].tsx
No need to convert between marketLabel and countryCode anymore 🥳
[GRW-1416]: https://hedvig.atlassian.net/browse/GRW-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Get CountryCode directly from locale

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/SiteFooter/SiteFooter.tsx
- apps/store/src/services/storyblok/storyblok.ts
Adding a footerblock component to storyblock.
[GRW-1360]: https://hedvig.atlassian.net/browse/GRW-1360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> grw-1360 add SB footerblock component

- apps/store/next.config.js
- apps/store/src/components/CartNotification/CartToast.tsx
Continue shopping should link to store page.
Fix to correctly provide type to next config.
> Link to store when choosing continue shopping

- apps/store/src/components/CartCard/CartCard.tsx
- apps/store/src/components/PriceBreakdown.tsx/PriceBreakdown.tsx
See title.
And: Refactor PriceBreakdown to avoid :first-child selector (doesn't work with SSR).
Hopefully obvious.
> Refresh cart data after removing line item

- apps/store/src/components/CartPage/CartPage.tsx
> Add spacing between items in cart

- apps/store/src/components/PriceCalculatorForm/PriceCalculatorForm.helpers.ts
- apps/store/src/graphql/PriceIntentCreate.graphql
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/priceIntent/PriceIntentService.ts
Update to latest price intent schema
Split up product name for (price form) template ID.
Update priceIntentCreate mutation to match new schema.
Schema is updated.
> Update to latest price intent schema

- apps/onboarding/src/components/forever/usePrintCodeEffect.ts
Update implementation.
With async rendering we can't be sure about the order anymore so we got unpredictable behavior with "setInterval".
I've tested this approach and seems to work fine.
> Fix print effect on forever page

- apps/store/src/graphql/CartFragment.graphql
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.helpers.ts
- apps/store/src/pages/cart/index.tsx
- apps/store/src/pages/cart/review.tsx
Use cost from API on cart pages
We should continue discussing with BE team if amount should be string / number.
And should we decide cross out?
> Update CartFragment to include cost

- packages/ui/src/components/HeadingNew/HeadingNew.tsx
[GRW-1441]: https://hedvig.atlassian.net/browse/GRW-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Safely handle empty string as header variant

- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
Handle when LayoutWithMenu is rendered on pages without connected CMS page.
The cart page fails to load atm.
I'm not too happy that we lose the typing here -- let's discuss how we can work that out!
Perhaps this is what you looked at @KarnellSchultz?
> Support layout for non-CMS pages

- apps/store/src/components/CartReviewPage/CartReviewPage.tsx
- apps/store/src/components/CartReviewPage/CartReviewPage.types.ts
- apps/store/src/components/CartReviewPage/useHandleSubmitStartDates.ts
- apps/store/src/graphql/StartDateUpdate.graphql
- apps/store/src/pages/cart/review.tsx
- apps/store/src/services/cart/CartService.ts
Update to send a single mutation instead of one per item in the cart.
> Use new start date update mutation

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.tsx
- apps/store/src/components/CheckoutPage/CheckoutPageLayout.tsx
- apps/store/src/components/CheckoutPage/CheckoutSignPage.tsx
- apps/store/src/components/CheckoutPage/useHandleSubmitContactDetails.ts
- apps/store/src/graphql/CheckoutFragment.graphql
- apps/store/src/graphql/ShopSession.graphql
- apps/store/src/graphql/ShopSessionCreate.graphql
- apps/store/src/graphql/UpdateContactDetails.graphql
- apps/store/src/mocks/ShopSessionMock/ShopSessionMock.helpers.ts
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/sign.tsx
- apps/store/src/utils/getOrThrowFormValue.ts
Refactor CheckoutPage to separate based on payments flow.
Add new to handle form to update contact details.
Update ShopSession query to include checkout information.
Refactor getOrThrowFormValue to not use formidable dependency.
We need to update this implementation to also trigger the start of signing for countries that use the `AFTER_SIGN` payment flow.
> Implement API for updating contact details

- apps/onboarding/src/components/DebuggerPage/forms/swedenApartment.ts
Change to a `isStudent` field instead of using `subType`
We are changing the UW quote API
> Switch to isStudent for SwedishApartment in the debugger

- apps/store/src/blocks/FooterBlock.tsx
> Support language change from footer selector

- apps/store/src/blocks/PerilsBlock.tsx
- apps/store/src/components/Perils/Perils.stories.tsx
- apps/store/src/components/Perils/Perils.tsx
- apps/store/src/components/Perils/Perils.types.ts
- apps/store/src/services/mockProductService.ts
- apps/store/src/services/mockProductService.tsx
- apps/store/src/services/storyblok/storyblok.ts
Let the perils component get a product and display that products perils. So far the data is only mocked. Also created a storyblok block for the perils. 
[GRW-1324]: https://hedvig.atlassian.net/browse/GRW-1324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1324 / smart perils component

- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPage.constants.ts
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPage.types.ts
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPageAdyen.tsx
- apps/store/src/lib/PageLink.ts
- apps/store/src/pages/api/payment/adyen-callback/[locale].ts
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/services/adyen/AdyenCheckout.tsx
Create new API route.
Add page prop to payment page to show success state.
Add query param to payment page to communicate success 3DS redirection.
Add Adyen return URL to the configuration.
Just moving pieces from web-onboarding setup.
> Add API route to handle Adyen 3DS redirection callback

- apps/store/src/pages/_document.tsx
Preload fonts in Head-element.
Set HTML lang.
Copied from "onboarding" app.
> Preload fonts in Head

- apps/store/package.json
- apps/store/src/components/CheckoutPage/useHandleSubmitStartDates.ts
- apps/store/src/pages/_app.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/services/datadog.ts
- apps/store/src/services/shopSession/ShopSessionContext.tsx
- yarn.lock
Add Datadog client logs
Log each message to console in dev env.
Add shop session ID to logger context.
This seems to be the official solution to log from the client.
https://docs.datadoghq.com/logs/log_collection/javascript/
Or is there another way to accomplish this?
> Add Datadog client logs

- apps/onboarding/package.json
- apps/store/package.json
- yarn.lock
Upgrade framer motion a major version. [Upgrade guide](https://www.framer.com/docs/guide-upgrade/)
From the upgrade guide:
> Framer Motion 7 makes react@18 the minimum supported version.
> Framer Motion 3D users should also [upgrade React Three Fiber](https://docs.pmnd.rs/react-three-fiber/tutorials/v8-migration-guide) to ^8.2.2.
our project was behind a major version.
> Upgrade Framer Motion

- packages/ui/package.json
- yarn.lock
Upgrade react animate height [v3](https://www.npmjs.com/package/react-animate-height)
We were behind a major version.
> Upgrade react animate height

- apps/store/package.json
- yarn.lock
See title.
Get rid of those yarn warnings!
> Update to latest Storyblok React lib

- apps/store/next-i18next.config.js
- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/lib/l10n/countries.ts
- apps/store/src/lib/l10n/locales.ts
- apps/store/src/lib/l10n/types.ts
- apps/store/src/lib/l10n/useCurrentLocale.ts
- apps/store/src/pages/_document.tsx
- apps/store/src/services/adyen/Adyen.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
- apps/store/src/utils/isLocale.test.ts
Remove non-standard locale variants
Less fields, less normalization, easier to use external APIs
[GRW-1470]: https://hedvig.atlassian.net/browse/GRW-1470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1470 / Feature / Unify locale format to xx-XX

- apps/store/src/pages/[[...slug]].tsx
- Extract locale from slug, let nextjs handle it
- Return /home => / normalization, lost it accidentaly in recent routing changes
Fix 404 for all top-level routes
> Fix / Store static paths 

- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/storyblok/storyblok.ts
Convert raw storybook links into page data in service layer
Extract mappding logic from next-specific code
[GRW-1485]: https://hedvig.atlassian.net/browse/GRW-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1485 / Feature / Move storybook page logic to service layer

- apps/store/src/graphql/PriceIntent.graphql
Include ShopSession ID in query so Apollo can resolve it in the cache.
> Fix ShopSession cache merge issue

- apps/store/package.json
- apps/store/src/mocks/index.ts
- renovate.json
- yarn.lock
Rollback MSW, was breaking local development
Prevent renovate from updating MSW, we should update manually in the future
Replace import path in mocks/index to relative, safer to use
> Fix / rollback msw update

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/PriceCardForm/PriceCardForm.tsx
- apps/store/src/components/ProductPage/PriceCalculatorFooterForm/PriceCalculatorFooterForm.tsx
- apps/store/src/components/ProductPage/PriceFooter/PriceFooter.stories.tsx
- apps/store/src/components/ProductPage/PriceFooter/PriceFooter.tsx
Fix layout issue -- keep footer centered.
Remove duplicate form-element around footer-form.
Move hidden inputs into the form components.
I think it makes more sense to collect everything to do with the form in one component.
> Refactor PriceCalculatorBlock

- apps/store/public/robots.txt
- Add robots.txt file
We don't want the forever codes to appear in google search results 🚫
[GRW-824]: https://hedvig.atlassian.net/browse/GRW-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore / Add robot.txt file > noindex forever pages

- apps/onboarding/src/components/forever/PageLayout.tsx
- apps/store/public/robots.txt
- remove robots.txt
- add `<meta />` tag to forever page layout
🔎 SEO 🔎
[GRW-824]: https://hedvig.atlassian.net/browse/GRW-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Grw-824 / chore / forever page meta tags for robots 🦾

- apps/store/src/pages/api/preview.ts
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
Add resolve_links to api/preview
Extract fetchStory helper
[GRW-1492]: https://hedvig.atlassian.net/browse/GRW-1492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1492 / Fix / Product preview

- apps/store/src/services/formTemplate/FormTemplateService.ts
- apps/store/src/services/formTemplate/data/NO_HOME_CONTENT.json
- apps/store/src/services/formTemplate/data/NO_HOME_CONTENT_UI.ts
See title.
[GRW-1500]: https://hedvig.atlassian.net/browse/GRW-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add form template for NO_HOME_CONTENT product

- apps/store/.env
- apps/store/src/lib/gtm.tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/pages/_document.tsx
Setup GTM in the store project. 
Have added the new env variable in vercel.
[GRW-1466]: https://hedvig.atlassian.net/browse/GRW-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1466 / Setup GTM coverage store

- apps/store/src/services/formTemplate/FormTemplateService.ts
- apps/store/src/services/formTemplate/data/NO_TRAVEL.json
- apps/store/src/services/formTemplate/data/NO_TRAVEL_UI.ts
[GRW-1502]: https://hedvig.atlassian.net/browse/GRW-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add form template for NO_TRAVEL product

- apps/store/src/services/formTemplate/FormTemplateService.ts
- apps/store/src/services/formTemplate/data/SE_ACCIDENT.json
- apps/store/src/services/formTemplate/data/SE_ACCIDENT_UI.ts
> Add form template for SE_ACCIDENT

- apps/store/src/components/PriceCalculatorForm/DynamicField.tsx
- apps/store/src/services/formTemplate/FormTemplate.types.ts
- apps/store/src/services/formTemplate/FormTemplateService.ts
- apps/store/src/services/formTemplate/combineFormTemplate.ts
- apps/store/src/services/formTemplate/data/NO_ACCIDENT.json
- apps/store/src/services/formTemplate/data/NO_ACCIDENT_UI.ts
Add form template for NO accident
Add support for minLength/maxLength in text-input.
[GRW-1507]: https://hedvig.atlassian.net/browse/GRW-1507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add form template for NO accident

- apps/store/src/services/formTemplate/FormTemplateService.ts
- apps/store/src/services/formTemplate/data/NO_HOUSE.json
- apps/store/src/services/formTemplate/data/NO_HOUSE_UI.ts
> GRW-1503 - feat: added NO house form

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/components/CheckoutPage/useHandleSubmitStartDates.ts
- apps/store/src/graphql/StartDateUpdate.graphql
- apps/store/src/pages/checkout/index.tsx
Update start date mutation
Change line item id -> priced variant id.
Match updated schema, switch from deprecated endpoints.
> Update start date mutation

- apps/store/src/services/formTemplate/data/SE_HOUSE_UI.ts
> Add SE House price form

- apps/store/src/components/CountrySelectorPage/CountrySelectorPage.tsx
- add design to country-selector page
- [Figma doc](https://www.figma.com/file/XFYNg7y7quhTZGC9cHzEt3/Hedvig.com---MVP-Wireframes?node-id=534%3A87051&viewport=-1843%2C7064%2C0.55)
- 🧽
[GRW-1518]: https://hedvig.atlassian.net/browse/GRW-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1518 / design / add country selector page design

- apps/store/src/middleware.ts
Redirect users instead of rewriting the URL in middleware.
Keep rewriting URL when we want to show country selector page.
We want the URL to always match the locale.
> Redirect users to locale instead of rewriting.

- apps/store/src/components/PriceForm/PriceForm.tsx
- apps/store/src/services/PriceForm/PriceForm.helpers.ts
- apps/store/src/services/PriceForm/data/SE_APARTMENT.ts
Add form template for SE apartment
Show loading UI while confirming price intent.
> Add form template for SE apartment

- apps/store/src/services/PriceForm/PriceForm.helpers.ts
- apps/store/src/services/PriceForm/data/SE_ACCIDENT.ts
> Add form template for SE accident

- apps/store/src/middleware.ts
> Use Next.js locale from request in middleware

- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/blocks/ProductCardBlock.tsx
- apps/store/src/blocks/TopMenuBlock.tsx
- apps/store/src/blocks/TopPickCardBlock.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/lib/PageLink.ts
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/pages/confirmation.tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
- apps/store/src/utils/useStroryblokLinkURL.ts
Update implementation to allow going through full flow
Use LinkButton on CartPage.
Lowercase URL parameter.
Add temporary redirect from Payment page if After Sign flow.
Temporary comment out check if checkout is completed on confirmation page.
It's time to get the POC together!
This is an attempt to enable us to show off as much as possible of the new experience and share it with the rest of the org.
> Update implementation to allow going through full flow

- apps/store/src/services/PriceForm/PriceForm.helpers.ts
- apps/store/src/services/PriceForm/data/NO_HOME.ts
- apps/store/src/services/PriceForm/data/NO_HOME_CONTENT.ts
Add form template for NO Home contents. 
[GRW-1548]: https://hedvig.atlassian.net/browse/GRW-1548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1548 / Form template no home

- apps/store/src/graphql/PriceIntent.graphql
- apps/store/src/services/priceIntent/PriceIntentService.ts
- apps/store/src/services/priceIntent/priceIntent.types.ts
see title.
The old query is deprecated.
> Switch to using root-level priceIntent query

- apps/store/src/blocks/HeadingBlock.tsx
- apps/store/src/blocks/HeroVideoBlock.tsx
- apps/store/src/components/HeroVideo/HeroVideo.stories.tsx
- apps/store/src/components/HeroVideo/HeroVideo.tsx
- apps/store/src/services/storyblok/storyblok.ts
Basically the same PR as https://github.com/HedvigInsurance/racoon/pull/576 but with uploading video assets to Storyblok instead of S3.
[GRW-1493]: https://hedvig.atlassian.net/browse/GRW-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1494 / feat / Add HeroVideoBlock via Storyblok

- apps/store/src/blocks/HeroVideoBlock.tsx
* Make `blok.poster` optional
The editor might chose not to add a Poster image.
> Don't assume that poster is defined

- apps/store/src/components/HeroVideo/HeroVideo.tsx
See title
Otherwise React complains about non-unique keys in looped items.
> Fall back to using video URL as key if format is not set

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/AppStoreBadge/AppStoreBadge.tsx
- apps/store/src/components/CountrySelectorPage/CountrySelectorPage.tsx
- apps/store/src/lib/PageLink.ts
- apps/store/src/lib/l10n/countries.ts
- apps/store/src/lib/l10n/locales.ts
- apps/store/src/lib/l10n/types.ts
- apps/store/src/lib/l10n/useCurrentCountry.ts
- apps/store/src/middleware.ts
- apps/store/src/pages/api/payment/adyen-callback/[locale].ts
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/pages/confirmation.tsx
- apps/store/src/pages/country-selector/index.tsx
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/adyen/Adyen.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
- apps/store/src/utils/isLocale.ts
- apps/store/src/utils/isSupportedLocale.test.ts
- apps/store/src/utils/isSupportedLocale.ts
- Renamed some locale-related types to express their intended use
- Make most locale-specific code agnostic to type of input locale
Our locale-handling code is a mess, hard to understand and easy to use incorrectly. See discussion in #hedvig-dot-com for details
[GRW-1564]: https://hedvig.atlassian.net/browse/GRW-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1564 / Feature / Type-safe handling of different locales

- apps/store/src/services/PriceForm/data/NO_HOME_CONTENT.ts
- apps/store/src/services/PriceForm/data/SE_ACCIDENT.ts
- apps/store/src/services/PriceForm/data/SE_APARTMENT.ts
- apps/store/src/services/PriceForm/data/SE_HOUSE.ts
- apps/store/src/services/PriceForm/data/SE_STUDENT_APARTMENT.ts
> Add 0 as default value for number of co-insured

- apps/store/src/services/PriceForm/PriceForm.helpers.ts
- apps/store/src/services/PriceForm/data/NO_ACCIDENT.ts
Added NO accident form template
> GRW-1550 - feat: added NO accident form template

- apps/store/.eslintrc.js
Ignore eslint for generated types
Eslint was failing
> Ignore eslint for generated types

- apps/store/src/services/gtm.tsx
Conditionally setup GTM scripts if GTM ID is provided.
Avoid crashing the app if neither GTM ID or environment is provided.
Not setting up GTM locally is a valid use case. Don't think it should crash the app.
> Conditionally load GTM script if setup correctly

- apps/store/next.config.js
Setup static NextJs config to handle /sv-se and other default locales
Prevent 404s from clients that have old URL cached.  Happens in preview app from time to time
> Fix / redirect old default locales

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/ProductPage/TierSelector/TierSelector.tsx
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/payment.tsx
Refactor to expect `Money.amount` to be a number/float.
See: https://hedviginsurance.slack.com/archives/C03CCKQPZTR/p1664787807337189
> Refactor to match new type for `Money.amount`

- apps/store/src/components/CheckoutContactDetailsPage/CheckoutContactDetails.tsx
- apps/store/src/components/CheckoutContactDetailsPage/CheckoutContactDetails.types.tsx
- apps/store/src/components/CheckoutContactDetailsPage/CheckoutContactDetailsPage.helpers.ts
- apps/store/src/components/CheckoutContactDetailsPage/CheckoutContactDetailsPageLayout.tsx
- apps/store/src/components/CheckoutContactDetailsPage/CheckoutSignPage.tsx
- apps/store/src/components/CheckoutContactDetailsPage/useHandleSubmitContactDetailsAndSign.ts
- apps/store/src/graphql/CheckoutSigning.graphql
- apps/store/src/graphql/CheckoutSigningFragment.graphql
- apps/store/src/graphql/CheckoutStartSign.graphql
- apps/store/src/graphql/ShopSession.graphql
- apps/store/src/graphql/ShopSessionCreate.graphql
- apps/store/src/graphql/ShopSessionFragment.graphql
- apps/store/src/pages/checkout/contact-details.tsx
Fix link back to review/start date screen on Checkout Contact Details page.
Tweak layout of same page to match the review/start date screen.
[GRW-1569]: https://hedvig.atlassian.net/browse/GRW-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update to fix layout on checkout contact details page

- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/api/preview.ts
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- apps/store/src/services/storyblok/storyblok.ts
There's "Open published" button in storyblok that works through preview API.  Support it by detecting what version we're looking at from query params
- Fix crash in Storyblok
- Improve editor experience, no need to delete cookies to preview published version
> Fix / Support published version preview

- apps/store/src/services/apollo/client.ts
We can't send empty string if we don't have an auth token.
> Conditionally set Authorization header in Apollo Client

- apps/store/src/services/apollo/client.ts
> Fix updating Apollo Client headers

- apps/store/src/pages/checkout/contact-details.tsx
- apps/store/src/services/Checkout/Checkout.helpers.ts
- apps/store/src/services/Checkout/useHandleSignCheckout.ts
Wait for status to change to SIGNED in checkout.
Catch errors when fetching existing checkout signing sessions.
Don't redirect from server in signing step.
> Wait for signing status to update to SIGNED

- apps/store/src/services/Checkout/useHandleSignCheckout.ts
> Use new enum for CheckoutSigning status

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/components/CheckoutPage/useHandleSubmitStartDates.ts
- apps/store/src/components/PriceCardForm/PriceCardForm.tsx
- apps/store/src/components/ProductPage/PriceCalculatorFooterForm/PriceCalculatorFooterForm.tsx
- apps/store/src/components/ProductPage/ProductPage.constants.ts
- apps/store/src/components/ProductPage/TierSelector/TierSelector.tsx
- apps/store/src/components/ProductPage/useHandleSubmitAddToCart.ts
- apps/store/src/graphql/CartEntryAdd.graphql
- apps/store/src/graphql/CartEntryRemove.graphql
- apps/store/src/graphql/CartFragment.graphql
- apps/store/src/graphql/PriceIntentFragment.graphql
- apps/store/src/graphql/StartDateUpdate.graphql
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
> Update GraphQL stuff to match the recent schema updates: `ProductOffer`

- apps/store/src/components/PriceForm/Accordion.tsx
It adds focus ring for `Accordion` trigger
> styles(Accordion): added focus ring

- .vscode/racoon.code-workspace
- .vscode/settings.json
Add multi-root VSCode workspace: https://code.visualstudio.com/docs/editor/multi-root-workspaces
Add setup to make vscode-jest work as expected!
Move settings inside workspace file.
To make vscode-test work.
> Add multi-root VSCode workspace

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/PriceCardForm/PriceCardForm.tsx
- apps/store/src/components/ProductPage/PriceCalculatorFooterForm/PriceCalculatorFooterForm.tsx
- apps/store/src/components/ProductPage/TierSelector/TierSelector.tsx
- apps/store/src/graphql/CartFragment.graphql
- apps/store/src/graphql/PriceIntentFragment.graphql
- apps/store/src/graphql/ProductOfferFragment.graphql
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
See title.
Also created a fragment for `ProductOffer` since we use it in both `Cart` and `PriceIntent`.
> Update ProductVariant to match schema

- apps/store/src/graphql/ProductOfferFragment.graphql
> Remove id from ProductVariant to match new schema

- .vscode/racoon.code-workspace
- apps/store/src/pages/_app.tsx
Add globs to exclude from VSCode search.
Improve editor experience.
> Update files to exclude from VSCode search

- .vscode/racoon.code-workspace
- apps/store/index.d.ts
- apps/store/src/pages/_app.tsx
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/contact-details.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/shopSession/ShopSession.constants.ts
Add constant for global ShopSession prop name.
Similar to the Apollo client prop name -- avoid using strings!
> Add constant for global ShopSession ID prop name

- .vscode/racoon.code-workspace
- apps/store/index.d.ts
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/contact-details.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/checkout/payment.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/pages/country-selector/index.tsx
- apps/store/src/pages/products/[product].tsx
- apps/store/src/pages/reusable-blocks/[...slug].tsx
- apps/store/src/services/shopSession/ShopSession.constants.ts
- apps/store/src/services/storyblok/Storyblok.constant.ts
- apps/store/src/services/storyblok/storyblok.ts
Quick fix to unify how we check we have a valid locale in the URL.
> Unify page locale check with `isRoutingLocale`

- apps/store/src/components/ProductCard/ProductCard.tsx
You need to set a value for the supports query to work
Wasn't applied
> Make sure supports rule is applied

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/blocks/ProductSummaryBlock.tsx
- apps/store/src/components/Pillow/Pillow.tsx
- apps/store/src/components/ProductPage/ProductSummary/ProductSummary.stories.tsx
- apps/store/src/components/ProductPage/ProductSummary/ProductSummary.tsx
Update Product Summary block 
To match final wireframe design
> GRW-1678 / Update product summary

- apps/store/src/services/gtm.tsx
Quick fix - refactor, add type assertion function.
Cleaner.
> GTM module, add type assertion function

- apps/store/src/components/CheckoutPage/CheckoutPage.helpers.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/useHandleSubmitStartDates.ts
- apps/store/src/services/gtm.tsx
> Add helper function to format API date

- apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/api/revalidate.ts
- apps/store/src/pages/products/[product].tsx
- apps/store/src/utils/PageLink.ts
Add CMS-defined page metadata
- link rel=canonical for A/B testing
- link rel=alternate for localized variants
SEO, make Google happy
[GRW-1693]: https://hedvig.atlassian.net/browse/GRW-1693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1693 / Feature / Canonical link and alternates

- apps/store/src/services/PriceForm/PriceForm.helpers.ts
- apps/store/src/services/PriceForm/data/SE_CAR.ts
See title.
We need some specialized inputs but this does the trick of getting you a price :)
> Add price form for SE_CAR

- apps/store/src/components/CartInventory/CartInventory.stories.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/CartInventory/InventoryItem.tsx
- apps/store/src/components/CartInventory/OfferInventoryItem.stories.tsx
- apps/store/src/components/CartInventory/OfferInventoryItem.tsx
Add updates inventory items to display products related to the cart.
These base components could be reused in the cart, the cart notification, the checkout, etc.
> Add cart inventory components

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/PriceCardForm/PriceCardForm.stories.tsx
- apps/store/src/components/PriceCardForm/PriceCardForm.tsx
- apps/store/src/components/PriceCardForm/ProductOfferPicker.tsx
- apps/store/src/components/PriceForm/PriceForm.tsx
- apps/store/src/components/ProductPage/PriceCalculatorFooterForm/PriceCalculatorFooterForm.tsx
- apps/store/src/components/ProductPage/TierSelector/TierSelector.tsx
Implement selecting tier when we get multiple product offers from backend.
Refactor the components to better match the final wireframes.
We should revisit this setup soon but didn't want to create an even larger PR.
[GRW-1701]: https://hedvig.atlassian.net/browse/GRW-1701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement tier selector on product page

- apps/store/src/pages/_app.tsx
- apps/store/src/services/gtm.tsx
- apps/store/src/utils/abRedirects.ts
Send experiment_impression events so that AB redirects are visible in Google Optimize and Analytics
Our first ever redirect data in Optimize:
First step to conversion tracking between old and new sites
> GRW-1695 / Feature / Track AB redirects

- apps/store/src/pages/_app.tsx
- apps/store/src/services/gtm.tsx
- apps/store/src/utils/abRedirects.ts
- Fix inital virtual_page_view tracking
- Change the way we provide metadata so Google Tag Manager can process it correctly
- Add siteVersion context for future A/B testing data
> GRW-1695 / Feature / GTM metadata fixes

- apps/store/src/components/PriceForm/SsnSeField.tsx
See title.
I think I accidentally broke this when fixing a warning to not use "defaultValue" for controlled inputs.
> Fix support for default value in SSN field

- apps/store/src/components/PriceCardForm/PriceCardForm.tsx
Include hidden input field with the product offer ID to add to cart.
When selecting a tier this is part of the form from the radio group input.
> Fix add to cart form, add product offer ID

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/pages/checkout/index.tsx
Include updated cart inventory component in Checkout.
Hopefully, this component can be reused where it makes sense to display a breakdown of what you have in your cart.
> Include cart inventory in Checkout

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/Text/Text.tsx
- packages/ui/src/index.tsx
The Price Calculator update will be split up in multiple PRs
- Update Text component with some utility props
- Rearrange content in Price Calculator
Updating layout and design to new wireframes/prototyp
https://user-images.githubusercontent.com/6661511/199042178-e8a22213-d54f-44b2-bd1d-b4bd0dcffc84.mov
> GRW-1704 / Price Calculator updates part 1

- apps/onboarding/package.json
- apps/onboarding/src/components/LandingPage/AdditionalCoverageCard.tsx
- apps/onboarding/src/components/LandingPage/BaseCard.tsx
- apps/onboarding/src/components/LandingPage/MainCoverageCard.tsx
- apps/onboarding/src/components/SwedishLandingPage/ClickableCard.tsx
- apps/onboarding/src/components/language-switcher.tsx
- packages/scripts/package.json
- yarn.lock
upgrade onboarding to next 13
[GRW-1705]: https://hedvig.atlassian.net/browse/GRW-1705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Grw-1705 - Next 13 upgrade `onboarding`

- apps/store/src/components/Dialog/Dialog.tsx
- apps/store/src/components/ProductPage/PriceCalculator/PriceCalculator.tsx
Open PriceForm in a Dialog
Trying out the concept from the prototype of opening the form in a modal
https://www.figma.com/proto/LvU4ntV5hpDTdueWbafpro/Calculator-Prototype?page-id=0%3A1&node-id=4%3A5471&starting-point-node-id=4%3A4744
https://user-images.githubusercontent.com/6661511/199452580-0203eae3-e8cf-44ca-81c0-0003d5daf9eb.mov
> Open PriceForm in a Dialog

- apps/store/src/components/ProductPage/PriceFormModal/PriceFormModal.tsx
Add close button to PriceForm Modal
Being able to close the dialog
https://user-images.githubusercontent.com/6661511/199751626-774d1149-5e8b-47b4-b8df-4ea7b915d757.mov
> Add close button to Dialog

- apps/onboarding/.gitignore
- apps/onboarding/vercel.json
- apps/store/.gitignore
- apps/store/vercel.json
Moved some of vercel overrides to vercel.json
This should make our config version-controlled, no need to go to Vercel UI to change stuff
> Feature / vercel.json config

- apps/store/src/components/ProductPage/PriceFooter/PriceFooter.tsx
- apps/store/src/components/ProductPage/ScrollPast/ScrollPast.tsx
- apps/store/src/components/ProductPage/TierSelector/TierSelector.tsx
Floating add to cart button
Updated design 
https://user-images.githubusercontent.com/6661511/200544404-1ef22d7d-1979-4628-bb2f-e588a9b3d4e9.mov
> Floating add to cart button

- apps/store/src/components/PriceForm/Accordion.tsx
- apps/store/src/components/PriceForm/PriceFormAccordion.tsx
- apps/store/src/components/PriceForm/SsnSeField.tsx
- Allow to open valid sections of purchase form manually
- Go back to next section when current one becomes valid
Allow to correct ealier entered data
> GRW-1748 / Feature / Purchase form navigation

- apps/store/src/components/ProductPage/PriceFooter/PriceFooter.tsx
> Add correct button box-shadow

- apps/store/next-i18next.config.js
- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/se/purchase-form.json
- apps/store/scripts/download-translations.sh
- apps/store/src/components/PriceForm/AutomaticField.tsx
- apps/store/src/components/PriceForm/HouseholdSize.tsx
- apps/store/src/services/PriceForm/Field.types.ts
- apps/store/src/services/PriceForm/data/SE_APARTMENT.ts
- Nice custom field for household size
- Fixes for value interpolation in i18n
Alternative approach to dynamic fields PR here: https://github.com/HedvigInsurance/racoon/pull/651
To be closer to design vision for purchase forms
> GRW-1746 / Feature / Household size input

- apps/store/src/components/PriceCardForm/PriceCardForm.tsx
Tiny fix, remove p > p nesting
> Fix / PriceCardForm text nesting

- apps/store/src/middleware.ts
Extract countrySelectorMiddleware
Prepare to put redirect logic into middleware
> GRW-1686 / Fix / Refactor middleware

- apps/store/src/middleware.ts
Apply workaround for Vercel middleware matching static paths despite config saying not to
> Fix / middleware-redirects

- apps/store/src/pages/_document.tsx
- apps/store/src/services/PriceForm/data/SE_HOUSE.ts
- apps/store/src/services/PriceForm/data/SE_STUDENT_APARTMENT.ts
- Use good-looking householdSize field in home and student apartment insurance
- Ignoring accident for now, field is likely not needed there
> Fix / householSize field everywhere

- apps/store/package.json
- packages/ui/package.json
- yarn.lock
> Fix / @next/font dependency should be direct in apps

- apps/store/src/components/CheckoutPage/useUpdateContactDetails.ts
- apps/store/src/graphql/CheckoutSigningFragment.graphql
- apps/store/src/services/Checkout/useHandleSignCheckout.ts
- Integrate checkout signing up to completion
- More PRs to follow with payment connection, contact details, etc
> GRW-1776 / Feature / Basic signing integration

- apps/store/src/services/storyblok/Storyblok.helpers.ts
Make CMS-defined URLs absolute
Fixes se/products/home link on /se/products/car page becoming /se/products/car/se/products/home
> Fix / Absolute URLs in CMS links

- apps/store/.storybook/main.js
- apps/store/public/locales/default/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/components/CartCard/CartCard.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/CartInventory/OfferInventoryItem.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/PriceBreakdown/PriceBreakdown.tsx
- apps/store/src/components/PriceCardForm/ProductOfferPicker.tsx
- apps/store/src/components/ProductPage/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/ProductPage/PriceCalculatorFooterForm/PriceCalculatorFooterForm.tsx
- apps/store/src/services/PriceForm/data/SE_CAR.ts
Use i18n to format monthly price in locale-aware way
> Feature / Localize monthly price

- apps/store/src/graphql/CheckoutSigningFragment.graphql
- apps/store/src/graphql/CheckoutStartSign.graphql
- apps/store/src/services/Checkout/useHandleSignCheckout.ts
Update GraphQL definitions to latest backend changes, fixes codegen
> GRW-1776 / Fix / Update checkout sign GraphQL

- apps/store/src/components/PriceForm/SsnSeField.tsx
Remove InputField.defaultValue from SSN field since it's fully controllable and we're using value
> Fix / SSN field defaultValue

- apps/store/src/components/CheckoutPage/CheckoutPage.constants.ts
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/components/CheckoutPage/useUpdateContactDetails.ts
Add required fields for signing
- first + last name
- SSN
- phone
> GRW-1775 / Feature / Add contact info for signing

- apps/store/src/pages/checkout/index.tsx
Prefill input values in contact details form in Checkout.
Use values from previous input. Let's discuss if we need to separate suggested values based on what you have input in the price calculator.
Otherwise it looks like we didn't save your inputs.
> Prefill input values in Checkout / contact details form

- apps/store/src/blocks/PriceCalculatorBlock.tsx
- apps/store/src/components/ProductPage/PriceCalculator/PriceCalculator.tsx
> Remove price calculator title

- apps/store/.env
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/services/Auth/Auth.ts
- apps/store/src/services/Checkout/useHandleSignCheckout.ts
- apps/store/src/utils/oauth.ts
Exchange authorizationCode to accessToken when checkout is signed, redirect to web-onboarding to connect payment
> GRW-1777 / Feature / Integrate payment connection

- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/Auth/Auth.ts
- apps/store/src/utils/PageLink.ts
Fix origin detection based on env variables so that we actually use env.NEXT_PUBLIC_ORIGIN_URL when it's available
Fixes payment connection flow on staging
> GRW-1777 / Fix / Payment connection origin

- apps/store/src/blocks/InsurableLimitsBlock.tsx
- apps/store/src/components/InsurableLimits/InsurableLimits.stories.tsx
- apps/store/src/components/InsurableLimits/InsurableLimits.tsx
- apps/store/src/components/Statistic/Statistic.stories.tsx
- apps/store/src/components/Statistic/Statistic.tsx
Update design of insurable limits component to match final designs.
Implement block as swipeable slideshow.
Update implementation of `Statistic` component to be more flexible.
Add media query to make it scale to desktop.
Match final designs.
[GRW-1784]: https://hedvig.atlassian.net/browse/GRW-1784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update insurable limit component to match design

- apps/store/src/components/CartCard/CartCard.tsx
- apps/store/src/components/CartInventory/OfferInventoryItem.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/Perils/Perils.tsx
- apps/store/src/components/PriceForm/HouseholdSize.tsx
- apps/store/src/components/ProductPage/PriceFormModal/PriceFormModal.tsx
- apps/store/src/components/TopMenu/TopMenu.tsx
Lots of small changes, see commit messages
Makes the site look better
> Feature / Design improvements for demo

- packages/ui/src/lib/theme/radius.ts
- packages/ui/src/lib/theme/theme.ts
Add a scale of radius values to theme
Consistency
> Add radius values to theme

- apps/store/src/components/CarTierSelector/CarTierSelector.stories.tsx
- apps/store/src/components/CarTierSelector/CarTierSelector.tsx
Created a Price tier component and a story for it. 
Decided not to add the light grey text you'll see in the designs as it did not have an acceptable contrast ratio.
---
**Coming later** ---> storyblok component
https://user-images.githubusercontent.com/50870173/202681276-1f10b5a2-5f7e-442d-aefd-6b4be6bd7cdb.mov
[Designs](https://www.figma.com/file/8SfzuQEJ4LJ6uKL0l7WKoE/Hedvig.com-%C2%B7-Final-Design?node-id=1289%3A5130&t=bhuRzFExMDbssqDC-0)
Users want to select the tier of car insurance. 
[GRW-1743]: https://hedvig.atlassian.net/browse/GRW-1743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1743 /Story for Car Price tier accordion

- apps/store/src/components/CartInventory/CartInventory.stories.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPageAdyen.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.helpers.ts
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
- apps/store/src/pages/api/payment/adyen-callback/[shopSessionId]/[locale].ts
- apps/store/src/pages/checkout/[shopSessionId]/payment/[status].tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/index.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/services/adyen/AdyenCheckout.tsx
- apps/store/src/utils/PageLink.ts
See title.
Use the `CartInventory` component to display purchase summary.
Refactor the reusable component a bit to be more flexible, use render props.
Would be nice to have a single way to display the inventory of a cart.
This is far from done but brings us closer to where we want to be.
> Update confirmation page to better match design

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/components/Accordion/Accordion.stories.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/CartInventory/CartInventory.stories.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPageAdyen.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.helpers.ts
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
- apps/store/src/components/Perils/PlusIcon.tsx
- apps/store/src/pages/api/payment/adyen-callback/[shopSessionId]/[locale].ts
- apps/store/src/pages/checkout/[shopSessionId]/payment/[status].tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/index.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/services/adyen/AdyenCheckout.tsx
- apps/store/src/utils/PageLink.ts
Update Accordion component to better match design from Figma.
> Update Accordion component to match design

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/components/Accordion/Accordion.stories.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/CartInventory/CartInventory.stories.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPageAdyen.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.helpers.ts
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
- apps/store/src/components/InsurableLimits/InsurableLimits.tsx
- apps/store/src/components/Perils/PlusIcon.tsx
- apps/store/src/components/Statistic/Statistic.tsx
- apps/store/src/pages/api/payment/adyen-callback/[shopSessionId]/[locale].ts
- apps/store/src/pages/checkout/[shopSessionId]/payment/[status].tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/index.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/services/adyen/AdyenCheckout.tsx
- apps/store/src/utils/PageLink.ts
- packages/ui/src/lib/theme/radius.ts
Tweak the design of `InsurableLimits` component to better match design.
Improve typing of "radius" theme helper.
> Update design of `InsurableLimits` component

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
- apps/store/src/components/PriceForm/AutomaticField.tsx
- apps/store/src/services/PriceForm/Field.types.ts
- apps/store/src/services/PriceForm/data/SE_ACCIDENT.ts
- apps/store/src/services/PriceForm/data/SE_APARTMENT.ts
- apps/store/src/services/PriceForm/data/SE_CAR.ts
- apps/store/src/services/PriceForm/data/SE_HOUSE.ts
- apps/store/src/services/PriceForm/data/SE_STUDENT_APARTMENT.ts
Display relevant keyboard for form fields
Wrong keyboard was showing on mobile devices
> Display relevant keyboard for form fields

- turbo.json
Add explicit dependency dev -> ui#build to fix broken development build when ui cache is stale
> Fix / Make dev script depend on ui#build

- apps/onboarding/public/locales/default/common.json
- apps/onboarding/public/locales/dk-en/common.json
- apps/onboarding/public/locales/dk/common.json
- apps/onboarding/public/locales/no-en/common.json
- apps/onboarding/public/locales/no/common.json
> GRW-1716 - chore: updated translations

- apps/store/src/components/CartInventory/CartInventory.stories.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPage.types.ts
- apps/store/src/components/PriceBreakdown/PriceBreakdown.tsx
- apps/store/src/graphql/CartFragment.graphql
- apps/store/src/pages/cart.tsx
Replace `CartCost.total` with `CartCost.net`
Replace `CartCost.subTotal` with `CartCost.gross`
Match the rest of our system.
> Update to match new `CartCost` schema

- apps/store/README.md
- apps/store/src/pages/_app.tsx
- apps/store/src/utils/l10n/useDebugTranslationKeys.ts
Support option to show translation keys
Reuse same solution as in "onboarding" app
[GRW-1800]: https://hedvig.atlassian.net/browse/GRW-1800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add ability to debug text keys using query param

- .prettierignore
- apps/store/public/mockServiceWorker.js
Apply prettier formatting (1 file affected)
Make prettier ignore storybook-static
We've got prettier update from renovate - let's make sure it don't reformat untouched files until we make meaningful changes there
> Chore / Apply prettier (1 file)

- apps/store/src/blocks/ProductPageBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
First step in towards new layout
Create fields for Overview and Coverage on PDP and inline PurchaseForm
Too support updated layout for PDP
https://user-images.githubusercontent.com/6661511/203581427-c6524252-6fa7-414a-9b6a-6ba2d10ba3c0.mov
> Create fields for Overview and Coverage on PDP and inline PurchaseForm

- apps/store/.gitignore
- apps/store/.graphqlconfig
- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/InputCurrentInsurance.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
- apps/store/src/components/ProductPage/PurchaseForm/useUpdateCancellation.ts
- apps/store/src/components/ProductPage/PurchaseForm/useUpdateStartDate.ts
- apps/store/src/graphql/ExternalInsurerUpdate.graphql
- apps/store/src/graphql/ExternalInsurers.graphql
- apps/store/src/graphql/PriceIntentCancellationRequestedUpdate.graphql
- apps/store/src/graphql/PriceIntentFragment.graphql
- apps/store/src/graphql/StartDateUpdate.graphql
> Integrate API for cancellation

- apps/onboarding/src/components/LandingPage/NewLandingPage.tsx
See title.
Visual bug.
[GRW-1848]: https://hedvig.atlassian.net/browse/GRW-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Landing page: Fix margin between sticky footer and cards

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/useCampaign.ts
- apps/store/src/graphql/CartRedeemCampaign.graphql
> Fix accessing user error from redeem campaign mutation

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Restrict PurchaseForm button max-width
Pending layout fixes
> Restrict button max-width

- apps/store/src/components/Pillow/Pillow.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Adjust white space in PurchaseForm
PurchaseForm should take up most of the viewport in mobile. Use responsive padding to scale across different mobile sizes.
> Adjust white space in PurchaseForm

- CONTRIBUTING.md
> Add section about responsive design

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CartPage/useStartCheckout.ts
- apps/store/src/graphql/CheckoutStart.graphql
- apps/store/src/pages/cart.tsx
> Add checkout start mutation in cart

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CartPage/useStartCheckout.ts
- apps/store/src/graphql/CheckoutStart.graphql
- apps/store/src/pages/cart.tsx
- apps/store/src/services/apollo/client.ts
Pass correct parameter name to `initializeApollo` to setup cache.
Update types for Apollo client utilities.
Use utility `addApolloState` on cart page.
It was broken...
> Fix Apollo SSR setup

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CartPage/useStartCheckout.ts
- apps/store/src/graphql/CheckoutStart.graphql
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/pages/products/[product].tsx
- apps/store/src/services/apollo/client.ts
> Implement `addApolloState` for SSR pages

- apps/store/src/services/apollo/client.ts
Send Hedvig-Language header with Apollo requests
Allows to localize userError.message
> GRW-1851 / Feature / Add Hedvig-Language header to Apollo requests

- apps/store/src/blocks/VideoBlock.tsx
- apps/store/src/components/Video/Video.stories.tsx
- apps/store/src/components/Video/Video.tsx
- Update video block to change aspect-ratio based on orientation
- Add Video to Storybook
Responsive videos
For screen recordings check: https://hedviginsurance.slack.com/archives/C041SD67G82/p1669802733469749
**Next steps**
- Add settings for setting aspect-ratio and height in Storyblok
- Add autoplay settings to Storyblok
> Set responive aspect-ratio based on orientation and add Video to Storybook

- apps/store/src/blocks/VideoBlock.tsx
- apps/store/src/components/Video/Video.stories.tsx
- apps/store/src/components/Video/Video.tsx
Add autoplay setting to Video component and to Storyblok
Make it optional to have autoplay
> Add autoplay setting to Video component and to Storyblok

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/InputCurrentInsurance.tsx
- apps/store/src/graphql/ExternalInsurerUpdate.graphql
Refactor `CancellationForm`.
Allow resetting external insurer.
User expectations.
> Allow resetting external insurer in ´PriceIntent´

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/InputCurrentInsurance.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/Checkbox.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CheckboxInput.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/DateInput.tsx
- apps/store/src/graphql/ExternalInsurerUpdate.graphql
Update design of `CancellationForm` to match Figma.
Add updated inputs matching Figma.
So we can show that some parts of the UI is ready!
[GRW-1822]: https://hedvig.atlassian.net/browse/GRW-1822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update design of `CancellationForm`

- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Read start date from `PriceIntent` API and use it in `CancellationForm`.
It is controlled by the server.
> Use start date from API in `CancellationForm`

- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/Checkbox.tsx
Update design of checkbox component to match Figma.
Update to gray description text in `CancellationForm`.
> Update checkbox design to match Figma

- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Pass `requested` data from API to `CancellationForm`.
Should be handled by server.
> Pass cancellation `requested` from API to component

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/PersonalNumberField/PersonalNumberField.stories.tsx
- apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/InputCurrentInsurance.tsx
- apps/store/src/components/PriceCalculator/SsnSeField.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/Checkbox.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CheckboxInput.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/DateInput.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/graphql/ExternalInsurerUpdate.graphql
Update `PersonalNumberField` to match design in Figma.
Animate background to flash green on every keystroke.
> Update personal number field to match design

- apps/store/src/components/TextField/TextField.stories.tsx
- apps/store/src/components/TextField/TextField.tsx
- Create a Textfield component with typing animation
> Create a Textfield component with typing animation

- apps/onboarding/public/locales/default/common.json
- apps/onboarding/public/locales/dk-en/common.json
- apps/onboarding/public/locales/dk/common.json
- apps/onboarding/public/locales/no-en/common.json
- apps/onboarding/public/locales/no/common.json
- apps/onboarding/public/locales/se-en/common.json
- apps/onboarding/public/locales/se/common.json
- apps/onboarding/scripts/download-translations.sh
Subj.  Should go on production ASAP
Fixes bug report
> Fix / Denmark translation of Onboarding start page header

- apps/store/src/components/PersonalNumberField/PersonalNumberField.stories.tsx
- apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/InputCurrentInsurance.stories.tsx
- apps/store/src/components/TextField/TextField.stories.tsx
Using the textfield component in the personal number component so there is no duplication of the input animations.
improved the storybook for the textfield component. Moved it into the input section in storybook. 
only one implementation of the inputs animations. laying the groundwork for future input work.
> Personal number field using the textfield component

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- Add translations for switching ui
focusing on the below screenshot
[GRW-1828]: https://hedvig.atlassian.net/browse/GRW-1828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1828/ Add translations switching-ui

- apps/store/src/components/ContactCard/ContactCard.stories.tsx
- apps/store/src/components/ContactCard/ContactCard.tsx
- Create Contact Card component 
[_not super sure where this is going to be used_](https://www.figma.com/file/8SfzuQEJ4LJ6uKL0l7WKoE/Hedvig.com-%C2%B7-Final-Design?node-id=1%3A197&t=PO376QB5mp4WGEof-0)
The component is in the design files
> Create Contact Card component

- apps/store/src/services/PriceCalculator/PriceCalculator.helpers.ts
- apps/store/src/services/PriceCalculator/data/SE_APARTMENT_BRF.ts
- apps/store/src/services/PriceCalculator/data/SE_APARTMENT_RENT.ts
Add separate forms for SE Apartment Rent & BRF
Remove ownership question from both new forms and add to initial data
Update copy to match Figma
Support separate rent and BRF PDPs
I kept `SE_APARTMENT` form since we use it on some test pages
[GRW-1876]: https://hedvig.atlassian.net/browse/GRW-1876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add separate forms for SE Apartment Rent / BRF

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/PriceCalculator/useTranslateTextLabel.ts
- apps/store/src/services/PriceCalculator/data/SE_APARTMENT_BRF.ts
- apps/store/src/services/PriceCalculator/data/SE_APARTMENT_RENT.ts
Translate different parts of the SE apartment forms.
Update translation hook to get keys from "purchase-form" namespace.
[GRW-1877]: https://hedvig.atlassian.net/browse/GRW-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Translate SE apartment forms

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/graphql/StartDateUpdate.graphql
- Make priceIntent.startDate required
- Rely on default value from backend
API updatem move logic to backend to be more flexible with start date depending on insurance info we may have
> Fix / Update priceIntent.startDate in API

- apps/store/src/blocks/ImageBlock.tsx
- apps/store/src/graphql/PriceIntentDataUpdate.graphql
- packages/ui/src/lib/media-query.ts
Update schema for `PriceIntentDataUpdate` mutation.
Exclude React props from being passed to DOM in `ImageBlock`.
Add `useIsomorphicLayoutEffect` for `useBreakpoint` hook.
Fix a bunch of warnings in the console.
> Fix schema for price intent update mutation

- apps/store/.storybook/i18next.js
- apps/store/.storybook/preview.js
- apps/store/src/components/PriceCalculator/HouseholdSizeField/HouseholdSizeField.stories.tsx
Load translation files for storybook @ apps/store by providing small custom backend to i18next
See price per month on screenshot:
- Better developer experience
> GRW-1861 / Feature / Show real translations in hedvig-com storybook

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
Make sure personal number field remembers input value. 
[GRW-1910]: https://hedvig.atlassian.net/browse/GRW-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1910 / Personal number field remember input

- apps/store/src/components/Video/Video.tsx
See title
Smaller border-radius and padding on mobile
> Adjust padding and border-radius on Video

- .prettierignore
- apps/onboarding/package.json
- apps/store/package.json
- turbo.json
- Remove prettier and eslint steps from
- Simplify turbo config by lifting up common settings
Codegen time on my machine (median of 3 runs)
before: 9.1s
after: 3.8s 
Better developer experience
> GRW-1641 / Fix / Faster codegen

- apps/onboarding/package.json
- apps/store/package.json
- package.json
- packages/ui/package.json
- turbo.json
Remove all configs for lint:fix as distinct script
Simpler configs.  There should be one consisten way to run lint and it accepts --fix flag
> Fix / remove lint:fix script

- apps/onboarding/src/components/language-switcher.tsx
Migrate `Link` to Next.js 13 standard.
Remove anchor tag child (not needed).
Refactor language picker component a bit.
Keep up-to-date.
> Onboarding: update `Link` to not use a-child

- apps/onboarding/src/components/language-switcher.tsx
- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/blocks/ProductCardBlock.tsx
- apps/store/src/blocks/TopPickCardBlock.tsx
- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CountrySelectorPage/CountrySelectorPage.tsx
- apps/store/src/components/Header/Header.stories.tsx
- apps/store/src/components/Header/NavigationLink.tsx
- apps/store/src/components/Header/ShoppingCartMenuItem.tsx
Migrate to new default Link component in Next.js 13
Keep up to date
> Store: update `Link` to not use a-child

- apps/store/src/components/Header/NavigationLink.tsx
Fix a > a DOM nesting in NavigationLink component
Properly wrap styled link as describe in https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag
FIx DOM structure and remove console warning
> Fix / Fix DOM nesting in NavigationLink

- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/graphql/PriceIntentFragment.graphql
Update schema to access "externalInsurer" directly on `PriceIntent` instead of under "cancellation".
N/A
> Update fragment `PriceIntent.externalInsurer`

- apps/store/src/blocks/HeadingBlock.tsx
- packages/ui/src/components/HeadingNew/HeadingNew.tsx
Add text alignment setting to Heading component and block
Not all headings are aligned center
> Add text alignment setting to Heading component and block

- apps/store/src/blocks/ProductSummaryBlock.tsx
- apps/store/src/components/CartCard/CartCard.tsx
- apps/store/src/components/CartInventory/OfferInventoryItem.tsx
- apps/store/src/components/CartNotification/CartNotification.stories.tsx
- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/CartNotification/ProductItem.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/Header/NavigationLink.tsx
- apps/store/src/components/Pillow/Pillow.tsx
- apps/store/src/components/ProductPage/ProductSummary/ProductSummary.stories.tsx
- apps/store/src/components/ProductPage/ProductSummary/ProductSummary.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CircledHSuperscript.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PriceCalculatorDialog.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Refactor `Pillow` component to render and image instead of SVG.
The first iteration of the site will use images for pillows.
> Update Pillow component to use Image instead of SVG

- apps/store/src/blocks/ProductDocumentsBlock.tsx
- apps/store/src/components/ProductPage/ProductDocuments.tsx
- apps/store/src/graphql/ProductData.graphql
- apps/store/src/services/storyblok/storyblok.ts
- packages/ui/src/lib/theme/colors.ts
Support Product Documents block with current design
List document for all variants - we may want to change it in the future for Car and Pet
Required block for Product pages
> GRW-1905 / Feature / Product Documents block

- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/TopMenuDesktop/TopMenuDesktop.tsx
Made Desktop Header sticky (Designs not completely set yet so will have to get back to it later) and fixed problem I created in my previous PR (https://github.com/HedvigInsurance/racoon/pull/1030)  by adding back the wrapper around the navigation as the dropdown list didn't align correctly. 
[GRW-1923]: https://hedvig.atlassian.net/browse/GRW-1923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1923 / fix / Desktop header small fixes

- apps/store/src/blocks/HeadingBlock.tsx
- apps/store/src/blocks/ImageTextBlock.tsx
- Remove predefined text alignment for Heading
- Remove extra spacing on nested blocks
- Make ImageTextBlock fluid width
Align with design
> Adjust spacing for nested headings

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/graphql/PriceIntentInsurelyUpdate.graphql
Update PriceIntent with Insurely data collection ID in the form.
As discussed we hold on to the collection ID until the iframe send the "completed" event.
[GRW-1913]: https://hedvig.atlassian.net/browse/GRW-1913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Send Insurely data collection ID to API

- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/TextField/TextField.tsx
Restrict input label to one line (no wrapping).
Update number input to to follow a11y best pracises: https://www.magentaa11y.com/checklist-web/number-input/.
> Fix text field accessibility issues

- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/CartInventory/CartInventory.types.ts
- apps/store/src/components/CartInventory/CostSummary.tsx
- apps/store/src/components/CartInventory/OfferInventoryItem.tsx
- apps/store/src/components/CartNotification/CartNotification.stories.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CheckoutPage/CartCollapsible/CartCollapsible.stories.tsx
- apps/store/src/components/CheckoutPage/CartCollapsible/CartCollapsible.tsx
- apps/store/src/components/CheckoutPaymentPage/CheckoutPaymentPage.types.ts
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/PriceBreakdown/PriceBreakdown.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/TierSelector.tsx
- apps/store/src/components/TierSelector/TierSelector.tsx
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/utils/formatter.ts
- apps/store/src/utils/l10n/countries.ts
- apps/store/src/utils/useFormatter.ts
Always take currency from money object instead of some context
Explicit is better than implicit.  Use same data shape or our GraphQL API - less transform code, lower mental load
> GRW-1838 / Feature / Use Money object for price data and formatting

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useUpdateStartDate.ts
- apps/store/src/graphql/PriceIntentFragment.graphql
- apps/store/src/graphql/StartDateUpdate.graphql
Update to use new `productOffersStartDateUpdate` mutation.
The price intent mutation is deprecated as discussed.
> Update to use new start date mutation on `ProductOffer`

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/Header/Header.stories.tsx
- apps/store/src/components/Header/ShoppingBagIcon.tsx
- apps/store/src/components/Header/ShoppingCartMenuItem.tsx
- apps/store/src/pages/cart.tsx
Update to the new "icon".
I used an SVG since the border is 1.5px and we can't render that in CSS.
> Update cart icon to match figma

- apps/store/public/locales/default/common.json
- apps/store/public/locales/dk/common.json
- apps/store/public/locales/no/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/CountrySelectorPage/CountrySelectorPage.tsx
- apps/store/src/pages/country-selector.tsx
- apps/store/src/utils/l10n/locales.ts
Localize country selector page and footer selector block
> Feature / Localize country and language labels

- apps/store/src/components/TextField/TextField.tsx
Update prop name and `shouldForwardProp` function to avoid errors/warnings.
Accidentally used a styled component feature (prefix: $) 😅
> Fix TextField warning and animation props

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/graphql/ExternalInsurerUpdate.graphql
> Update param in `ExternalInsurerUpdate` mutation

- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/graphql/ExternalInsurerUpdate.graphql
- apps/store/src/graphql/ProductData.graphql
Fetch insurely client id from API
N/A
[GRW-1930]: https://hedvig.atlassian.net/browse/GRW-1930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fetch Insurely client id from API

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/graphql/ExternalInsurerUpdate.graphql
- apps/store/src/graphql/PriceIntentFragment.graphql
- apps/store/src/graphql/ProductData.graphql
- apps/store/src/graphql/ProductOfferFragment.graphql
- apps/store/src/services/Insurely/Insurely.tsx
- apps/store/src/services/priceIntent/priceIntent.constants.ts
Include `PriceMatchBubble` in `OfferPresenter`.
Fetch possible price match from the API.
It looks kind of shitty now because the the background color is too dark. The updated color palette will fix this.
[GRW-1899]: https://hedvig.atlassian.net/browse/GRW-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add price match component to offer presenter

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/PriceCalculator/Accordion.tsx
- apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
Simple styling stuff + translate label
[GRW-1945]: https://hedvig.atlassian.net/browse/GRW-1945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PriceCalculator: style edit button like a button

- apps/store/public/locales/default/cart.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/CartInventory/CampaignCodeList.tsx
- apps/store/src/components/TextField/TextField.tsx
- Added a "add" button to the discount code form
updated designs
[GRW-1943]: https://hedvig.atlassian.net/browse/GRW-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1943 Discount code w/ button

- apps/store/src/components/ProductPage/usePriceIntent.ts
Avoid causing infinite loop when getting API error after creating new price intents.
We didn't consider the case where the API would return an error after creating a new price intent. This would cause an infinite loop.
We still have the problem that we run the mutation twice, but that's a separate issue.
> Avoid infinite loop of creating price intents after API error

- apps/store/src/components/CartInventory/CartInventory.stories.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/InputCurrentInsurance.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useUpdateCancellation.ts
- apps/store/src/components/ProductPage/usePriceIntent.ts
- apps/store/src/components/TierSelector/TierSelector.stories.tsx
- apps/store/src/graphql/PriceIntentCancellationRequestedUpdate.graphql
- apps/store/src/graphql/PriceIntentFragment.graphql
- apps/store/src/graphql/ProductOfferFragment.graphql
Update cancellation requested mutation since it's moved from `PriceIntent` to `ProductOffer`.
Remove unused label from current insurance field.
Remove console.log statement.
API changes.
> Update cancellation mutation from PriceIntent -> ProductOffer

- apps/store/public/locales/default/cart.json
- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/en-se/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/services/Insurely/Insurely.tsx
See title.
Some code scouting in the `CurrentInsuranceField` component.
This is not 100% according to design but it's a start. We don't have all the data to show the correct information yet.
[GRW-1958]: https://hedvig.atlassian.net/browse/GRW-1958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show message after successfully going through Insurely flow

- apps/store/src/components/TextField/TextField.stories.tsx
- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/services/PriceCalculator/Field.types.ts
- apps/store/src/services/PriceCalculator/formFragments.ts
Add option to text field to show a suffix like "34 m2".
Add example to storybook.
It's not 100% matching the design but I took some inspiration from [Material Design](https://mui.com/material-ui/react-text-field/).
[GRW-1957]: https://hedvig.atlassian.net/browse/GRW-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add option to display suffix in text field

- apps/store/src/components/ProductPage/ScrollToButton/ScrollToButton.tsx
Update sticky add to cart button and hide on desktop.
Should look the same as sticky "calculate price" button.
> Update sticky add to cart button

- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.constants.ts
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Increase width of modal (insurely confirmation) to match design.
Update select input to show placeholder also when opened.
> Increase width of modal to match design

- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/DateInput.tsx
Tweak date input to better fit into the design (webkit).
> Clean up date input design (webkit)

- apps/store/public/locales/default/cart.json
- apps/store/public/locales/default/checkout.json
- apps/store/public/locales/no/checkout.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/public/locales/sv-se/checkout.json
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CountrySelectorPage/CountrySelectorPage.tsx
Update checkout page to use new design.
Fix issue passing onClick to next link.
> Update checkout page to match design

- apps/onboarding/next.config.js
- apps/onboarding/package.json
- apps/store/next.config.js
- apps/store/package.json
- yarn.lock
Switch to built-in module transpilation that comes wiht Next 13.1
Newer recommended way of doing the same thing
> Fix / Transpile modules without plugin

- apps/store/package.json
- yarn.lock
Remove dependency
Can't find it being used or being a peer dependency.
> Remove unused dependency graphql-sse

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
Update checkout page for desktop to match designs.
There are only designs for the cart page on desktop but they are pretty similar.
> Update checkout page for desktop

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/services/PriceCalculator/data/SE_CAR.ts
Add current insurance field to SE Car form.
[GRW-1982]: https://hedvig.atlassian.net/browse/GRW-1982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add current insurance field to SE CAR form

- packages/ui/src/lib/fontSizes.ts
- Fix bug when non-reponsive text styles weren't calculated
- Fix default+override case, was always default before
- Simplify font style calculation code
Remove annoying error logs.  Correctness
> Fix / Responsive font style calculation

- apps/store/src/components/ButtonNextLink.tsx
Add utility component to be able to use UI/Button with Next.js Link
We are already using it in many places - this will reduce boilerplate!
> Add ButtonLink component which uses Next.js Link

- apps/store/src/blocks/SpacerBlock.tsx
- apps/store/src/components/ButtonNextLink.tsx
- packages/ui/src/lib/theme/space.ts
- packages/ui/src/lib/theme/theme.ts
Add t-shirt sizes for space property in Emotion theme.
This should work the same as for other properties I think.
> Improve types for Emotion theme.space property

- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/HouseholdSizeField/HouseholdSizeField.tsx
Support autofocus for HouseholdSize field.
It's a bit unclear how this field works with assitive devices so let's talk about that later.
> Add autofocus support for HouseholdSize field

- apps/store/public/locales/default/checkout.json
- apps/store/public/locales/sv-se/checkout.json
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/services/Checkout/useHandleSignCheckout.ts
Display take over diaglog when we get an error during signing.
Display an specific user error message under the form.
Better error handling.
> Display error dialog when signing fails

- apps/store/src/components/ProductPage/ProductPageContext.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/services/Tracking/Tracking.ts
- apps/store/src/services/logger/client.ts
Tracking service reports events to Datadog as well
This is how offer_created log looks like in Datadog:
More debugging info for Analytics, we may need it in the future
> GRW-1981 / Feature / Report tracking events to datadog

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/ScrollToButton/ScrollToButton.tsx
> Fix scroll to add to cart button

- apps/store/src/components/CheckoutPage/useUpdateContactDetails.ts
- apps/store/src/graphql/CheckoutFragment.graphql
- apps/store/src/pages/checkout/index.tsx
Update checkout fragment to match new schema (personalNumber -> ssn).
Skip optional params in update contact details mutation.
> Update contact details object from Checkout schema

- apps/store/src/components/PriceCalculator/PriceCalculatorSection.tsx
> Show button loading state in PriceCalculator

- apps/store/src/components/ProductPage/PurchaseForm/ComparisonTable/ComparisonTable.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/ComparisonTable/ComparisonTable.tsx
Add visual `ComparisonTable` to display in purchase form to show the difference between tiers.
Just stuck with a basic HTML table. It's only possible to make all columns the same width so that's why I added `min-width` property to the data cells to mimic the design. I think it works well enough.
[GRW-1996]: https://hedvig.atlassian.net/browse/GRW-1996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add visual comparison table component

- apps/store/src/services/PriceCalculator/PriceCalculator.types.ts
- apps/store/src/services/PriceCalculator/data/SE_APARTMENT_BRF.ts
- apps/store/src/services/PriceCalculator/data/SE_APARTMENT_RENT.ts
- apps/store/src/services/PriceCalculator/data/SE_STUDENT_APARTMENT.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
Remove initial data from purchase forms.
Handled by the backend.
[GRW-1989]: https://hedvig.atlassian.net/browse/GRW-1989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove initial data from purchase forms

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Fix an issue with StartDate input where the value wasn't being updated
https://user-images.githubusercontent.com/19200662/210255656-3468433e-92ad-4df9-acde-a0f12b7ff962.mov
> fix(StartDate): persisit value changes

- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/blocks/ProductCardBlock.tsx
- apps/store/src/blocks/TopPickCardBlock.tsx
- apps/store/src/services/storyblok/Storyblok.helpers.ts
- Only log broken link message once per link
- Make it info to remove stacktrack
- Add link title to simplify troubleshooting
Better developer and CMS editor experience
> Fix / Reduct log noise for broken CMS links

- apps/store/src/blocks/ProductPageBlock.tsx
See title.
[Screen Recording 2023-01-03 at 10.32.38.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/f32ee03d-55ad-425b-8768-5c3c622a4e59/Screen%20Recording%202023-01-03%20at%2010.32.38.mov)
When displaying tier selector, the content is overflowing so you can't scroll down to the "add to cart" button.
> Enable overflow scroll in offer presenter

- packages/ui/src/components/Button/Button.tsx
Update button styles - should have fixed height according to design
Update focus styles to be more visible
> Set fixed button height

- apps/store/public/locales/default/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
> Add missing translations to purchase form

- apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
Update styles to match design.
> Update price calculator styles

- apps/store/src/components/CartInventory/CartEntryItem.tsx
- apps/store/src/components/CartInventory/useRemoveCartEntry.ts
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/useStartCheckout.ts
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
- apps/store/src/services/Tracking/Tracking.ts
- apps/store/src/services/gtm.tsx
Track view_cart, add_to_cart, remove_from_cart, begin_checkout
Report ecommerce events to Google Analytics
> GRW-2009 / Feature / Track cart and checkout analytics events

- apps/store/public/locales/default/checkout.json
- apps/store/public/locales/dk/common.json
- apps/store/public/locales/no/common.json
- apps/store/public/locales/sv-se/checkout.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/components/CheckoutPage/useUpdateContactDetails.ts
- apps/store/src/pages/checkout/index.tsx
Show first name and last name input in Checkout if they are missing.
First and last name are required to sign insurance. If the lookup based on SSN fails it makes sense to allow users to add their own name instead.
> Show name inputs in Checkout if missing

- apps/store/src/components/CartInventory/useRemoveCartEntry.ts
Don't refetch queries after removing cart entry - we get updated cart in response and it's automatically used to update Apollo cache
- Faster UI, one less network roundtrip
- Less code
> Fix / Optimize cart refresh on item remove

- apps/store/public/locales/default/cart.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/CartPage/CartPage.tsx
Add styles for cart page desktop layout. The styles are the same as the checkout page since these two pages have a lot in common. 
[GRW-2011]: https://hedvig.atlassian.net/browse/GRW-2011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2011Add cart page desktop layout

- apps/store/next.config.js
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/pages/_document.tsx
Implement Content Security Policy headers.
Fix bug in `InputSelect` where both value and default value were defined.
Add writing direction prop to html tag.
Enable minification using SWC.
Add more security headers based on: https://nextjs.org/docs/advanced-features/security-headers
We are using CSP in Web Onboarding and we should aim to at least maintain the same level of security of the new site.
I didn't copy over all the values since there are many scripts we are not going to use in this new setup.
If this config grows we should probably move it to another module.
> Implement CSP headers and other small fixes

- apps/store/next.config.js
- apps/store/src/components/CartInventory/CampaignCodeList.tsx
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/pages/_document.tsx
- apps/store/src/utils/useHighlightAnimation.ts
Use UI Button in `CampaignCodeList`.
Update `TextField` height to match UI Button + code scouting.
Add some excluded keys to highlight animation hook.
Input and button height should align.
> Use UI Button in `CampaignCodeList`

- apps/store/next.config.js
- apps/store/src/components/TextField/TextField.tsx
Add new CSP rules to allow styles from own domain and Vercel live comments.
Update focus styles for input fields.
> Add additional CSP rules (style)

- apps/store/src/pages/_app.tsx
Include message for developers that checkout the console on the website.
Hiring opportunity for people that show interest in the code.
> Include developer message in console

- apps/store/src/components/PriceCalculator/HouseholdSizeField/HouseholdSizeField.tsx
> Align `HouseholdSizeField` with `TextField`

- apps/store/README.md
- apps/store/src/pages/api/session/create.ts
- apps/store/src/services/priceIntent/PriceIntentService.ts
- apps/store/src/services/shopSession/ShopSessionService.ts
Add new dev API endpoint to setup a new shop session with a couple products added to the cart 😍
Makes it very simple to setup a new session and get to the cart / checkout flow.
> Add dev endpoint to create filled shop session

- apps/store/src/pages/_app.tsx
- apps/store/src/pages/_document.tsx
Add twitter and theme meta tags.
When we add more og tags etc. we should think more about how to organize this. I think we should have a separate file for each type of meta tag, and then import them into the head component. But I think we can do that later.
> Add twitter + theme meta tags

- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/pages/_app.tsx
- apps/store/src/pages/_document.tsx
Use wrapper component for links that look like buttons.
Centralize Next.js specific logic.
> Use `ButtonNextLink` wrapper component

- apps/store/next.config.js
Subj.  Fixes Google Analytics integration
> Fix CSP connect-src to allow Google Analytics

- apps/store/public/locales/en/cart.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/CartInventory/CartEntryItem.tsx
- apps/store/src/components/CartInventory/CartInventory.stories.tsx
- apps/store/src/components/CartInventory/CartInventory.types.ts
- apps/store/src/components/CartInventory/DetailsSheet.ts
- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
- apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx
- apps/store/src/components/TierSelector/TierSelector.stories.tsx
- apps/store/src/graphql/ProductOfferFragment.graphql
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/checkout/index.tsx
- packages/ui/src/components/Button/Button.tsx
Implement Details Sheet for Cart and Checkout (part of Cart Inventory).
Add documents to Cart query to show in new Details Sheet.
Make changes to `FullscreenDialog` to be more flexible.
Add extra properties to UI Button to work as a link.
I'm using some placeholders for the data rows since we don't have it exposed in the API yet.
We should move out also the "confirm remove" dialog to a similar component but we can do that in the next step.
> Implement Cart details sheet

- apps/store/src/components/CartInventory/CartEntryItem.tsx
- apps/store/src/components/CartInventory/RemoveEntryDialog.tsx
Separate out a `RemoveEntryDialog` component from `CartInventory`.
Avoid nesting Dialog root components.
> Separate out `EntryRemoveDialog` component

- README.md
Sync README with Vercel config
> Fix / Update Vercel env names

- packages/ui/src/components/Space.tsx
> Avoid passing incorrect props to HTML

- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceCalculator/InputRadio.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- packages/ui/src/components/Button/Button.tsx
Skip disabled styles if button is also loading.
Show purchase form dialog button as loading while in pending state.
The shift was a bit jarring. We mainly want to disable the button after submitting a form e.g. but we don't need to show it as disabled.
> Skip disabled styles if button is loading

- apps/store/src/components/CartInventory/CampaignCodeList.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- Use `Text` component in-favor manually styling text
- Make sure add campaign button doesn't shrink when in "loading" state
- Add focus styles to remove campaign button
- Use a form to start checkout
- Without a form, there's no way for assitive devices to know what actions can be performed on a page.
> Refactor Cart + Campaign Code stuff

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
> Center text in Checkout error

- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/pages/checkout/index.tsx
> Ensure `TextField` takes up the full width of containers

- apps/store/.env.local.example
- apps/store/README.md
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/Slideshow/Slideshow.tsx
- apps/store/src/pages/api/session/reset.ts
- apps/store/src/services/Auth/Auth.ts
- apps/store/src/services/Flags/Flags.ts
Reset-endpoint: also reset auth session if there's an auth token saved in cookies.
Fix style issue that isn't safe in SSR mode.
I didn't reset the auth session in the create endpoint - let's see after using it for awhile if we want to do the same there.
> Reset auth session in /api/session/reset endpoint

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Add focus state to the button.
> Offer Presenter: Add focus state to edit button

- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/DateInput.tsx
Improve the design of the input data field to better match design and other input fields.
> Update InputDate design to match Figma

- apps/store/next.config.js
* Added CSP rules for google fonts and storyblok
So their resources don't get block
> fix(csp): added google fonts and storyblok

- apps/store/src/pages/api/session/create.ts
- Renamed a few variables to clarify them. Reworked how the `promise` is handled. 
- Added a 3rd item to the cart when this endpoint is used. 
Make this code easier to change in the future.
> api / session / create small refactor

- apps/store/src/components/CountrySelectorPage/CountrySelectorPage.tsx
Noticed there was some layout shift on this page 🔀
- Removed a redundant `Section` element and added a `min-height` to the page.
CLS is no good for users or our web-vitals score
> Fix CLS on `country-select` page

- apps/store/src/pages/api/csp-reports.ts
> Fix / move yarn cache to make Vercel see it

- apps/store/next.config.js
- apps/store/src/pages/api/csp-reports.ts
Send CSP violations to /api/csp-reports
Log those reports so we can see them in Datadog
Ability to detect CSP errors out of development
> GRW-2023 / Feature / Log CSP violations

- apps/store/next.config.js
Fix CSP violations from Vercel preview comments
> Fix CSP violations from Vercel widget

- apps/store/next.config.js
* Added basic documentation that explain the reasoning behind some rules
So we remember their purpose
> chore(csp): added basic documentation

- apps/store/next.config.js
- apps/store/src/pages/api/csp-reports.ts
- apps/store/src/services/Checkout/Checkout.helpers.ts
Use console built-in formatting for objects and JSON
Less code, less things to break
> Use builtin console formatting for objects instead of JSON.stringify

- apps/store/next.config.js
Adjust CSP rules to fix latest errors
- Allow vimeo
- Allow all pusher.com - seems to be shared between Storyblok and Vercel preview
> Update CSP rules, allow Vimeo and Vercel preview -> pusher.com

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
- apps/store/src/components/CheckoutPage/useUpdateCustomer.ts
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/graphql/CheckoutFragment.graphql
- apps/store/src/graphql/ShopSessionFragment.graphql
- apps/store/src/graphql/UpdateContactDetails.graphql
- apps/store/src/pages/api/session/create.ts
- apps/store/src/pages/checkout/index.tsx
Integrate new `ShopSession.customer` property in UI.
Replace `checkoutContactDetailsUpdate` with `shopSessionCustomerUpdate`.
Use data from `ShopSession.customer` to populate `PurchaseForm`.
Update `ssn` from `PurchaseForm` to `ShopSession.customer` instead of `PriceIntent.data`.
To support new `ShopSession.customer` property.
[GRW-2067]: https://hedvig.atlassian.net/browse/GRW-2067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use `ShopSession.Customer` property in `PurchaseForm`

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/InputSelect/InputSelect.tsx
Update footer block design to match latest Figma design.
We might want to do some refactoring of the Storyblok setup but we can do that later.
> Update design of Footer block component

- apps/onboarding/src/components/QuotePriceCard/QuotePriceCard.stories.tsx
- apps/onboarding/src/components/QuotePriceCard/QuotePriceCard.tsx
- package.json
- packages/scripts/.eslintrc.js
- yarn.lock
- Remove another source of eslint-plugin-resolve-typescript which may conflic with next preset
- Fix import/order violations in onboarding
- Fix eslint config in ui, was broken
> Fix eslint config for ui, fix import order in onboarding, remove unused dependency

- apps/store/src/services/Tracking/Tracking.ts
Report ecommerce events as Datadog actions
Might be useful for analysing user behavior
> Report ecommerce events as Datadog custom actions

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/services/Tracking/Tracking.ts
- apps/store/src/services/Tracking/TrackingContext.tsx
Add hashed userData to legacy analytics events
- web-onboarding compatibility
> Add userData to legacy analytics events

- apps/store/next.config.js
> Update CSP directives for Vercel Live

- apps/store/src/components/InputSelect/InputSelect.tsx
Subj
Fixes console error and restores animation
> Fix select animation since we're highlighting wrapper, not native input

- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- Prefill prica calculator with customer data
- Take info from context instead of prop-drilling
- Fix calculator section navigation
Restore price calculator prefill experience
> Prefill priceIntent based on shopSession.customer data

- apps/store/src/blocks/AccordionBlock.tsx
* Added [FAQ structured data](https://developers.google.com/search/docs/appearance/structured-data/faqpage) for `AccordionBlock`. It was based on `market-web`'s [implementation](https://github.com/HedvigInsurance/market-web/blob/master/src/utils/structuredData.ts).
[Add Google Rich Results preview here]
Requested by Peter for SEO purposes.
[GRW-2098]: https://hedvig.atlassian.net/browse/GRW-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2098 - feat(AccordionBlock): added support for FAQ structured data

- apps/store/src/pages/cart.tsx
Navigate to store if clicking Checkout -> Back -> Cart -> Back -> Store :)
Otherwise there's no way to "close" cart.
[GRW-2104]: https://hedvig.atlassian.net/browse/GRW-2104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Avoid navigating Cart -> Back -> Checkout

- apps/onboarding/vercel.json
- apps/store/vercel.json
> Make yarn install on Vercel immutable, may help with cache ENOENT errors

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/utils/l10n/useChangeLocale.ts
Smarter navigation when changing language
- Do full reload on country change
- Try to find alternate in current language otherwise
- Fallback to home page
- Prevent 404 when changing language in nested pages
- Improve user experience
> Navigate to alternate page when changing language with fallback to home page

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/pages/_document.tsx
- apps/store/src/utils/l10n/useChangeLocale.ts
Subj
Make sure we don't get indexed by Google until we're ready
> Forbid search indexing

- apps/store/src/components/CartInventory/CampaignCodeList.tsx
- apps/store/src/components/CartInventory/CartEntryItem.tsx
- apps/store/src/components/CartInventory/CostSummary.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/RecommendationList.tsx
- packages/ui/src/components/Button/Button.tsx
Update typography and font sizes across cart page to match design
Accidentally mixed up "md" and "lg" sizes :P
> Update text sizes across cart page

- apps/store/src/components/CartInventory/CampaignCodeList.tsx
- apps/store/src/components/CartInventory/CartEntryItem.tsx
- apps/store/src/components/CartInventory/CostSummary.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/RecommendationList.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- packages/ui/src/components/Button/Button.tsx
> Update text sizes across checkout page

- apps/store/src/app/debugger/page.tsx
- apps/store/src/app/head.tsx
Fix responsiveness issue on debugger page
Fix access to localstorage value in debugger page
> Fix small issues on debugger page

- apps/store/src/app/debugger/page.tsx
- apps/store/src/app/head.tsx
- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
- apps/store/src/components/CartNotification/ProductItem.tsx
- apps/store/src/components/PriceCalculator/ExtraBuildingsField.tsx
> Fix font size for cart toast and details sheet

- apps/store/src/app/debugger/page.tsx
- apps/store/src/app/head.tsx
- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
- apps/store/src/components/CartNotification/ProductItem.tsx
- apps/store/src/components/PriceCalculator/ExtraBuildingsField.tsx
- apps/store/src/components/TextField/TextField.tsx
Skip `Text` component inside `Label` since it causes the text to clip due to `overflow: hidden`.
> TextField: fix text clipping of letter 'g'

- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
Update bg color to be same as rest of the page
> Fix background color on header

- apps/store/src/blocks/ImageTextBlock.tsx
> Set default image ratio to 3/2

- apps/store/src/components/CartInventory/CartEntryItem.tsx
- apps/store/src/components/CartInventory/DetailsSheet.ts
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/RecommendationList.tsx
Update Cart page layout to match current Figma designs
The content should take up 1/3 of the width of the page according to Zak
I added a min width of 28rem to avoid strange layouts
Let's maybe extract this layout to a separate reusable component...
> Update to new cart page layout

- .vscode/racoon.code-workspace
Fix the VSCode workspace setup and update to use shorter folder names.
Emojis make everything better ✨
Jest settings were broken.
> Fix VSCode workspace setup

- apps/store/src/components/CartInventory/DataTable/DataTable.ts
- apps/store/src/components/CartInventory/DetailsSheet.ts
- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
Update cart item details sheet to match the new design.
Move documents to top of page.
> Update details sheet

- .husky/pre-commit
- apps/store/src/components/CartInventory/DataTable/DataTable.ts
- apps/store/src/components/CartInventory/DetailsSheet.ts
- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
- package.json
Run eslint as part of lint-staged.
Remove eslint directly from pre-commit hook.
Not sure why this is still here, I thought Aleks had removed it.
> Restore lint-staged settings

- .husky/pre-commit
- apps/store/public/locales/dk/checkout.json
- apps/store/public/locales/en/checkout.json
- apps/store/public/locales/sv-se/checkout.json
- apps/store/src/components/CartInventory/DataTable/DataTable.ts
- apps/store/src/components/CartInventory/DetailsSheet.ts
- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
- apps/store/src/components/CheckoutPage/Breadcrumbs.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- package.json
Update Checkout page with breadcrumbs from Figma.
> Add Checkout breadcrumbs

- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
Fix onCompleted event processing on addToCart
- Restores tracking add_to_cart event
> Fix useHandleSubmitAddToCart.onCompleted being overwriten instead of merged

- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
- apps/store/src/services/Tracking/Tracking.ts
- apps/store/src/services/gtm.tsx
Add shopSession.id to analytic events
We're going to use shopSessionId in analytics instead of quote_cart_id in old web
> Add shopSession.id to tracking events

- apps/store/src/services/logger/client.ts
Subj
Make verion filter in Datadog RUM Application human-readable.  See current state in screenshot, we want to see branch without cross-referencing git log
> Add branch name to datadog app version

- apps/store/src/services/Tracking/Tracking.ts
> Fix typo: showSessionId -> shopSessionId

- apps/store/src/services/logger/client.ts
- Fix Datadog app version (must use NEXT_PUBLIC_* vars)
- Replace deprecated config options with recommended alternatives
> Fix Datadog client config

- apps/store/src/pages/_app.tsx
- apps/store/src/services/Tracking/Tracking.ts
- apps/store/src/services/gtm.tsx
Reorder analytics reporting to ensure initiate_gtm is the first event to report
Prevent missing context when processing events in GTM
> Ensure initiate_gtm is the first event we report

- apps/store/next.config.js
> Add gstatic to img-src CSP, 4 violations yesterday

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/ConfirmationPage/CheckList.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- Created a `<CheckList />` component to be used on the confirmation page. This component is presentational with 'checkboxes' that are not interactive.
The Component will also show users the google play / apple app store button based on which platform the user is on. Or show both to let the user make the decision on which is best for them.
TODO: Translations coming in future PR. 
Per latest designs for the confirmation page.
> Confirmation page step content ✅

- apps/store/src/blocks/ProductCardBlock.tsx
- apps/store/src/blocks/ProductGridBlock.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
- apps/store/src/components/ProductGrid/ProductGrid.tsx
- Add image ratio settings to block
- Adjust layout and font size
Design review with Zak
> Update ProductGridBlock design

- apps/store/src/components/SwitchingAssistantPage/SwitchingAssistantPage.tsx
- apps/store/src/graphql/ProductOfferFragment.graphql
- packages/ui/src/components/Button/Button.tsx
Remove hover styles on touch devices
Transition background-color changes (hover)
Update product offer query to skip banksignering url
Discussed with design team
> Remove button hover on touch devices

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/services/Tracking/Tracking.ts
Subj.
- Track when editing initial priceIntent (may happen multiple times on close/reopen)
- Ignore editing info for already created offer
Another step in conversion tracking
> Report open_price_calculator event

- apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
- apps/store/src/components/PriceCalculator/StepIcon.tsx
- apps/store/src/components/SwitchingAssistantPage/SwitchingAssistantPage.tsx
- apps/store/src/graphql/ProductOfferFragment.graphql
> Show valid section step color as green when valid

- apps/store/next.config.js
> Add sgtm.hedvig.com to CSP, we use it for data collection

- apps/store/src/components/TextField/TextField.stories.tsx
- apps/store/src/components/TextField/TextField.tsx
- packages/ui/src/lib/theme/colors/colors.stories.tsx
- packages/ui/src/lib/theme/colors/colors.ts
Add more colors to the theme
Update storybook
> Add signal and highlight colors to theme

- apps/store/src/blocks/ContentBlock.tsx
* Added a `max-width` to `ContentBlock` - `37.5rem ~600px`
[GRW-2134]: https://hedvig.atlassian.net/browse/GRW-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2134 - feat(ContentBlock): added max width

- apps/store/src/blocks/ImageBlock.tsx
* Added storyblok datasource for aspect ratios
* Added support for design system based aspect ratio
[GRW-2091]: https://hedvig.atlassian.net/browse/GRW-2091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2091 - feat(ImageBlock): added support for design system based aspect ratio

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
- apps/store/src/components/CheckoutPage/useUpdateCustomer.ts
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/graphql/ShopSessionAuthenticate.graphql
- apps/store/src/graphql/ShopSessionFragment.graphql
- apps/store/src/pages/checkout/index.tsx
Require login before checkout
This is the first step with very quick and dirty implementation to unblock signing
Handle returning members
> Require authentication of returning member before checkout

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
- apps/store/src/components/CheckoutPage/useUpdateCustomer.ts
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/ProductPage/ProductPage.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/graphql/ShopSessionAuthenticate.graphql
- apps/store/src/graphql/ShopSessionFragment.graphql
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/services/Tracking/Tracking.ts
Subj
Make sure reported values are consistent between conversion steps
> Report product.name as item_id, product.displayNameFull as item_name and variant.typeOfContract as variant

- apps/store/next.config.js
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
- apps/store/src/components/CheckoutPage/useUpdateCustomer.ts
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/ProductPage/ProductPage.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/graphql/ShopSessionAuthenticate.graphql
- apps/store/src/graphql/ShopSessionFragment.graphql
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/services/Tracking/Tracking.ts
> Extend CSP whitelist (solve the latest reports from staging)

- apps/store/next.config.js
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
- apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
- apps/store/src/components/CheckoutPage/useUpdateCustomer.ts
- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/CarMileageField.tsx
- apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- apps/store/src/components/ProductPage/ProductPage.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/graphql/ShopSessionAuthenticate.graphql
- apps/store/src/graphql/ShopSessionFragment.graphql
- apps/store/src/pages/checkout/index.tsx
- apps/store/src/services/Tracking/Tracking.ts
Fix some field types not using initial value
Make sure we show previously entered data when going back to submitted sections of price calculator
> Fix default value for car mileage, select and radio fields

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/pages/cart.tsx
Update cart page layout to match Figma
> Update layout on cart page

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/pages/cart.tsx
Implement the 12 column grid from Figma in the footer block.
Let's experiment with this in more places and maybe come up with a reusable component/styles.
> Implement 12 column grid in footer

- apps/store/src/blocks/ImageTextBlock.tsx
* Update possible values for orientation: 'vertical' and 'fluid' --> ~'horizontal'~;
* Whenever stacked (using 'vertical' or 'fluid' orientation) image should be displayed first;
* Changed Storyblok field so it became more clear:
* ~'alignment'~ --> 'textAlignment'
* ~'reverse'~ --> 'imagePlacement'
Those changes came from discussions with the design team about how ImageTextBlock should work.
> refact(ImageTextBlock): design iteration

- apps/store/src/components/ToggleCard/Switch.tsx
- apps/store/src/components/ToggleCard/ToggleCard.tsx
Update ToggleCard to use theme values
> Use theme values in ToggleCard

- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/ToggleCard/Switch.tsx
- apps/store/src/components/ToggleCard/ToggleCard.tsx
> Add missing translation to cart page

- apps/store/src/components/CheckoutPage/CartCollapsible/CartCollapsible.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
Implement the 12 column grid layout on checkout page.
[Screen Recording 2023-01-27 at 16.34.39.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/f42710e7-a039-45f6-998e-ffd9642ff1e0/Screen%20Recording%202023-01-27%20at%2016.34.39.mov)
Better visual consistency
I had to introduce some additional breakpoints that we should confirm with design team before implemeting this on more pages.
> Implement 12 column grid on Checkout page

- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/DateInput.tsx
- apps/store/src/components/ToggleCard/Switch.tsx
- apps/store/src/components/ToggleCard/ToggleCard.tsx
Tighthen up elements on cart page according to design.
> Tighten up layout of cart page

- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/SwitchingAssistantPage/SwitchingAssistantPage.tsx
- apps/store/src/pages/checkout/switching-assistant.tsx
- apps/store/src/utils/PageLink.ts
Update design of accordion block (desktop) to match Figma design.
> Update accordion block desktop design

- apps/store/src/blocks/USPBlock.tsx
- apps/store/src/services/storyblok/storyblok.ts
* Added `USPBlock`
Requested by [design](https://www.figma.com/file/qUhLjrKl98PAzHov9ilaDH/*NEW*-.com-UI-Kit?node-id=271%3A5591&t=jSMRqtFcWIX9E53O-4):
Can be tested [here](https://hedvig-dot-com-git-grw-2140-featusp-block-hedvig.vercel.app/se/forsakringar/hemforsakring/hyresratt)
[GRW-2140]: https://hedvig.atlassian.net/browse/GRW-2140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2140 - feat: added USPBlock

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/RecommendationList.tsx
Hide recommendation list if the list of recommendations is empty
Otherwise you only see the heading which is odd.
> Cart: hide recommendations if list is empty

- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
> Fix displaying car details sheet

- apps/store/src/components/ProductPage/PurchaseForm/PriceCalculatorDialog.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/Video/Video.tsx
- apps/store/src/utils/dialogEvent.ts
See title.
Refactor purchase form dialog a little bit.
We don't want video to be playing in the background.
Wanted to come up with a solution that doesn't cause coupling between components so went with sending custom events.
> Pause video when purchase form is open (mobile)

- apps/store/src/components/CheckoutPage/Breadcrumbs.tsx
- apps/store/src/components/SwitchingAssistantPage/SwitchingAssistantPage.tsx
- apps/store/src/graphql/ProductOfferFragment.graphql
- apps/store/src/pages/checkout/switching-assistant.tsx
Integrate updated API for banksignering in Switching Assistant
> SwitchingAssistant: integrate updated API

- apps/store/src/components/ProductCard/ProductCard.tsx
Make sure to use next/link instead of regular links.
Otherwise we do a full page reload.
> Use next/link in ProductCardBlock

- apps/store/README.md
- apps/store/next.config.js
- apps/store/package.json
- yarn.lock
Add next bundle analyzer to store
Get some stats on our bundle size
> Add next bundle analyzer to store

- apps/store/src/utils/PageLink.ts
See title.
Before the returned link would be empty string which just links to the current page.
> Fix page link home when not providing a locale

- apps/store/src/pages/api/campaign/[code].ts
Pass through all additional query params in the campaign code link endpoint to the destination url.
Now this will work:
`/api/campaigns/KARNELL?next=/en-se/store&utm=hello`
Needed to maintain e.g. utm parameters in the redirect.
> Campaign code link: pass through extra query params

- apps/store/src/components/CartInventory/CampaignCodeList.tsx
- apps/store/src/pages/api/campaign/[code].ts
> Add pointer cursor to chip button (campaign code)

- apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/FooterSection.tsx
- apps/store/src/components/ConfirmationPage/Layout.tsx
- apps/store/src/services/storyblok/storyblok.ts
Integrate CMS on confirmation page.
Get all content from the CMS.
This is 90% a content page so the source should be the CMS.
This is a first implementation, we will need to update this to support rearranging the content blocks in the future.
> Update confirmation page to fetch CMS content

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/FooterSection.tsx
- apps/store/src/components/GridLayout/GridLayout.tsx
Implement shared component for the 12 column grid.
Include a content wrapper that makes sure main content is centered and takes up the correct amount of horizontal space.
We are starting to see this pattern across the site. Having a shared component will lead to a more consistent experience.
Didn't want to go too far with this PR. However, let's start to thing about what other utility layout components we might need.
> Implement shared 12 column grid layout

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/RecommendationList.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/FooterSection.tsx
- apps/store/src/components/GridLayout/GridLayout.tsx
- apps/store/src/graphql/ProductRecommendationFragment.graphql
- apps/store/src/services/storyblok/Storyblok.helpers.ts
Use new `featuredImage` from API in recommendations.
Add utility function to get the image size from the filename from Storyblok.
Keeping the fallback image for now.
> Use featured product image for recommendations

- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
Tweak paddings on navigation menu after feedback from Design. 
Also improved ability to hover across to secondary menu without the menu closing.
> GRW-2165 / Navigation-design-comments

- apps/store/public/locales/en/cart.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/CartPage/CartPage.tsx
See title.
Discussed with Zak in Figma.
> Cart Page: remove page heading

- apps/store/src/blocks/VideoBlock.tsx
- apps/store/src/components/Video/Video.tsx
- packages/ui/src/components/Button/Button.tsx
Update video controls design
https://user-images.githubusercontent.com/6661511/216582417-0c0c89aa-7b0b-4122-b2e0-12005015d197.mov
Should be aligned in corner and look different
> Update video controls

- apps/store/src/components/CartInventory/CampaignsSection.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx
- apps/store/src/graphql/CartFragment.graphql
- apps/store/src/pages/cart.tsx
Subj
Do not show something member cannot use - less confusion
> Hide campaigns section for returning members which cannot use them

- apps/store/src/blocks/ProductPageBlock.tsx
* Updates Desktop Layout so coverage section of the page take full width;
* Update Overview/Coverage _Table Of Contents_* so it reflects scrolling state;
_Table Of Contents_ was the name the I've found online referring to that web widget that can be used to quickly transverse the content of a page. One can click on its items to jump into specific sections of a page. Additionally, it should reflect scrolling of the page. Eg:
So even though that _ Overview/Coverage navigation thingy_ is a _Tab_ on mobile, for desktop it should behave like a _Table of Contents_ (TOC for short).
Please help me test it :)
So it matches the proposed design.
https://user-images.githubusercontent.com/19200662/216333408-c6d13aaf-8e0a-4f7b-b1a0-34c9e000414a.mov
[GRW-2159]: …
> GRW-2159 - feat(ProductPage): update page table of contents based on scroll

- apps/store/src/components/CartInventory/RemoveEntryDialog.tsx
Fix bug cuasing wrong cart entry to be removed.
Use uniuqe ID for the delete form to avoid the bug.
> Fix bug causing wrong cart entry to be removed

- apps/store/src/components/Video/Video.tsx
> Increase spacing for controls

- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
Make buttons take up full width of the menu.
> fix / button-styles-nav-menu-mobile

- apps/store/src/components/CartInventory/useRemoveCartEntry.ts
- apps/store/src/components/PriceCalculator/ExtraBuildingsField.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
Refetch shop session after adding/removing entries to/from cart.
We want to show the correct recommendations.
> Refetch shop session when adding/removing cart entries

- apps/store/src/graphql/CartEntryAdd.graphql
- apps/store/src/graphql/CartEntryRemove.graphql
- apps/store/src/graphql/CartRedeemCampaign.graphql
- apps/store/src/graphql/CartUnredeemCampaign.graphql
- apps/store/src/graphql/ExternalInsurerUpdate.graphql
- apps/store/src/graphql/PriceIntent.graphql
- apps/store/src/graphql/PriceIntentCancellationRequestedUpdate.graphql
- apps/store/src/graphql/PriceIntentConfirm.graphql
- apps/store/src/graphql/PriceIntentCreate.graphql
- apps/store/src/graphql/PriceIntentDataUpdate.graphql
- apps/store/src/graphql/PriceIntentInsurelyUpdate.graphql
- apps/store/src/graphql/RenewalDateUpdate.graphql
- apps/store/src/graphql/ShopSession.graphql
- apps/store/src/graphql/ShopSessionAuthenticate.graphql
- apps/store/src/graphql/ShopSessionSigning.graphql
- apps/store/src/graphql/ShopSessionStartSign.graphql
- apps/store/src/graphql/StartDateUpdate.graphql
> Update ID -> UUID type in schema

- apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
Fixing small mistake in calculating checkout steps.
> Show checkout step payment by default

- apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
> CheckoutPage: fix small spacing issue

- apps/store/src/pages/confirmation/[shopSessionId].tsx
Using the url to get the slug for the page confirmation page. If the page does not have a slug then it throws a 404.
I decided to split the url rather than crate a data structure with the list of accepted slugs because this solution requires less maintenance. If we want to change the names of the slugs in StoryBlok for any reason, we don't need to also update this code. 
We need to support other languages and markets.
> Confirmation-Page: Dynamic page slugs 

- apps/store/src/services/apollo/client.ts
SSR ApolloClient never sent authentication header, fixed this
> Fix ApolloClient authorization header during SSR

- packages/ui/src/lib/theme/typography.ts
> Add 48px font size as defined in the styleguide

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/Perils/Perils.tsx
> Update gap between perils to match design

- apps/store/src/blocks/ProductDocumentsBlock.tsx
- apps/store/src/components/ProductPage/ProductDocuments.tsx
Update product document block design.
Add description field to CMS.
Use grid layout.
Match design.
> Update product document block design

- apps/store/src/blocks/TextBlock.tsx
Bug fix: Apply desktop font size to the correct breakpoint
> fix(TextBlock): apply desktop font size to the correct breakpoint

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Move tagline down and update space to match design
> Fix / move tagline below button

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
> Fix / Typography tweaks promise modifyer

- apps/store/src/blocks/AccordionItemBlock.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
- apps/store/src/components/ProductPage/ProductDocuments.tsx
> Avoid capitalizing 'today'

- apps/store/src/components/ProductPage/ProductDocuments.tsx
> Update styles for product doc links

- apps/store/src/blocks/SpacerBlock.tsx
> Update space block sizes and breakpoint

- apps/store/src/blocks/ContactSupportBlock.tsx
- apps/store/src/components/ContactCard/ContactCard.tsx
- apps/store/src/components/ContactSupport/ContactSupport.stories.tsx
- apps/store/src/components/ContactSupport/ContactSupport.tsx
Slight adjustment to SupportBlock
- Adjust padding and width
- Remove Title from block
Request from Zak
> Update support block

- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/Perils/Perils.tsx
Added open/close keyframe animations to the accordion.
Tried several ways to do this with some issues around the padding the `<Content />` component had. Decided to remove the padding since the block itself has padding. However, going forward I'd like to move the padding into the accordion rather than having it on the block.
[Before demo fixes](https://www.notion.so/hedviginsurance/Before-Demo-Fixes-0f8755117f6e4092b16ae0743dc7bcec?pvs=4)
> Accordion Animations

- apps/store/src/blocks/ButtonBlock.tsx
- apps/store/src/blocks/HeadingBlock.tsx
- apps/store/src/blocks/ImageTextBlock.tsx
Updated styles as requested by design
[GRW-2185]: https://hedvig.atlassian.net/browse/GRW-2185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2185 - styles(ImageTextBlock): updates responsive styles

- apps/store/src/blocks/AccordionBlock.tsx
* Set AccordionBlock spacing according to design.
[GRW-2217]: https://hedvig.atlassian.net/browse/GRW-2217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2217 - Update AccordionBlock so it uses grid layout system

- apps/store/src/components/Header/HeaderStyles.tsx
> fix / header-font-sizes

- apps/store/src/components/CartPage/RecommendationList.tsx
> Update cart recommendations to look like product grid

- apps/store/next-csp.config.js
- apps/store/next.config.js
- Extract CSP config to own module
- Allow vercel.com connect-src
> Extract CSP config to its own module

- apps/store/src/components/ProductCard/ProductCard.tsx
- Make ProductCard image a link
- Add opacity hover effect
Better UX
> Make ProductCard images clickable

- apps/store/src/pages/checkout/index.tsx
Make sure to log errors on Checkout page with relevant context.
So it's easier to debug errors.
> Log errors when rendering Checkout page

- apps/store/public/locales/en/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/FourOhFourPage/FourOhFourPage.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/ProductRecommendationList/ProductRecommendationList.tsx
- apps/store/src/components/ProductRecommendationList/useProductRecommendations.ts
- apps/store/src/graphql/ProductRecommendations.graphql
- apps/store/src/pages/404.tsx
- packages/ui/src/components/Button/Button.helpers.ts
- packages/ui/src/components/Button/Button.tsx
Implement custom 404 page.
Update button component to support responsive size prop.
Update layout with menu component to use "overlay" setting on non-CMS pages.
Refactor prodcut recommendation list to be able to reuse it on 404 page.
To have a custom 404 page.
> Custom 404 page

- apps/store/src/blocks/PerilsBlock.tsx
Update side desktop side margins as requested by design
[GRW-2238]: https://hedvig.atlassian.net/browse/GRW-2238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2238 - styles(Perils): update desktop side margins

- apps/store/src/blocks/ProductPageBlock.tsx
☝🏻 
[GRW-2240]: https://hedvig.atlassian.net/browse/GRW-2240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2240 - fix(ProductPage): desktop layout - display tab bar while scrolling trough Overview and Coverage sections

- apps/store/src/components/BankIdDialog.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
- apps/store/src/services/bankId/BankIdContext.tsx
- apps/store/src/services/bankId/bankId.types.ts
- apps/store/src/services/bankId/bankId.utils.ts
- apps/store/src/services/bankId/bankIdReducer.ts
- apps/store/src/services/bankId/useBankIdCheckoutSign.ts
- apps/store/src/services/bankId/useBankIdLogin.ts
- Make bankIdReducer pure, move side effects into hooks
- Refactor and clean up bankId hooks
Make core more clear, improve maintainability
> Refactor bankId implementation

- apps/store/src/components/Accordion/Accordion.tsx
> Remove double hover effect

- apps/store/src/components/ProductCard/ProductCard.stories.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
Wrapped the title and subtitle text in a link.
Improved the Product card story.
[Notion page](https://www.notion.so/hedviginsurance/Make-the-headline-text-in-Product-grid-as-the-link-text-inside-a-a-not-L-s-mer-OK-if-the-d0e2b5f78a6a473693834d73a43b9c79?pvs=4)
> ProductCard title link

- apps/store/public/locales/en/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/components/ErrorPage/ErrorPage.tsx
- apps/store/src/pages/404.tsx
- apps/store/src/pages/500.tsx
- Add custom error 500 page
- Refactor 404 error page and create reusable error page component
They are basically the same page.
Caveat: it's not 100% clear what should happen when user clicks "try again".
> Add custom 500 error page

- apps/store/src/components/CartInventory/DetailsSheet.ts
- apps/store/src/components/CartInventory/DetailsSheetDialog.tsx
Use grid layout for cart details sheet.
Clear the modal footer inside the dialog.
> Update details sheet layout

- apps/store/public/locales/dk/purchase-form.json
- apps/store/public/locales/en/common.json
- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/no/purchase-form.json
- apps/store/public/locales/sv-se/common.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/Header/ShoppingBagIcon.tsx
> Update labels related to seeing your price

- apps/store/src/blocks/ProductPageBlock.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/lib/theme/theme.ts
- packages/ui/src/lib/theme/transitions.ts
Apply same transition rules to hover effects
Perhaps we should use Button more liberally instead, but it feels like too big refactoring for now
Design consistency
> Extract theme.transitions.hover, apply hover styles to section triggers on product page

- apps/store/src/blocks/HeroVideoBlock.tsx
- apps/store/src/blocks/ProductPageBlock.tsx
- apps/store/src/blocks/VideoBlock.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/ProductCard/ProductCard.tsx
- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/lib/media-query.ts
- packages/ui/src/lib/theme/theme.ts
- packages/ui/src/lib/theme/transitions.ts
Subj
Better experience on slow networks and in Mac Firefox
> Fix video poster quality issue by making maxWidth larger and removing height calculation since it was percentage, not px value

- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/Perils/Perils.tsx
Fix perils text overflow
**Before**
**After**
[GRW-2256]: https://hedvig.atlassian.net/browse/GRW-2256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2256 - fix(Perils): text overflow

- apps/store/src/components/Video/Video.tsx
Add missing poster warning similar to broken link one
Simplify CMS misconfiguration detection.  I've changed poster field to required, but it won't help with already added videos
> Warn about video blocks without poster image

- apps/store/src/pages/api/revalidate.ts
- apps/store/src/services/authApi/fetchJson.ts
- apps/store/src/services/storyblok/Storyblok.helpers.ts
When we get revalidate webhook (Storyblok content has changed), check storyblokCacheVersion and update if needed
This is next step to make sure we use Storyblok CDN instead of central API as much as possible
> Update storyblokCacheVersion in edge config based on Storyblok webhooks

- apps/store/next-csp.config.js
- apps/store/src/pages/api/revalidate.ts
- apps/store/src/services/authApi/fetchJson.ts
- apps/store/src/services/storyblok/Storyblok.helpers.ts
Yet another CSP error from Datadog logs
> Add frame-src rule for hotjar.com

- apps/store/src/components/ContactCard/ContactCard.tsx
- apps/store/src/components/ContactSupport/ContactSupport.tsx
Updated Customer card pdding
[GRW-2261]: https://hedvig.atlassian.net/browse/GRW-2261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2261 - styles(CustomerSupportBlock): updated padding

- apps/store/src/services/storyblok/storyblok.ts
Some debug logging in Storyblok init.  Trying to fix editing experience for Peter
> Fix Storyblok bridge check, add log to make it clear if it initialized or not

- apps/store/.env.local.example
- apps/store/src/services/storyblok/storyblok.ts
Forgot to document and configure env variables in previous PR related to Storyblok cache
> Document env variables for Storyblok cache management

- apps/store/src/components/Video/Video.tsx
Make sure video get specified aspect ratio
> Make sure video get specified aspect ratio

- apps/store/src/pages/api/session/create.ts
> Fix: add default locale to api create endpoint

- apps/store/next-csp.config.js
Fix CSP to make /editor.html storyblok asset manager work
> Add CSP rules for Storyblok asset manager

- apps/store/src/pages/session/[shopSessionId].tsx
Fix session resume redirect so the locale is preserved.
> Fix redirect with locale in session resume feature

- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/graphql/StartDateUpdate.graphql
- Update both start and renewal date if you are in "invalid renewal" state in cancellation form
- Update date label translation
> Update both start and renewal date in cancellation form

- apps/store/src/components/BankIdDialog.tsx
- apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
- packages/ui/src/lib/theme/transitions.ts
- Animate the BankID logo while in "pending" state.
- Show "open app on phone" text also in "starting" state.
- Animate transition between "pending" and "success" states.
[Untitled.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/91c19c8b-a543-47a6-8d36-0eea5e5d4b58/Untitled.mov)
> ✨Animate BankID modal

- apps/store/next-csp.config.js
- apps/store/next.config.js
- apps/store/src/components/PriceCalculator/SsnSeSection.tsx
Apply "allow all" CSP for Storyblok editor
Prevent problems with Storyblok features blocked by CSP
Save our time by not managing another whitelist
> Allow all CSP for Storyblok editor, remove storyblok-only rules from site CSP

- apps/store/next-csp.config.js
- apps/store/next.config.js
- apps/store/src/components/PriceCalculator/SsnSeSection.tsx
- apps/store/src/services/PriceCalculator/data/SE_CAR.ts
Experimental change, needed to make it possible to reproduce backend issue here: https://hedviginsurance.slack.com/archives/C041SD67G82/p1676885892117709
> Remove externalInsuser field from SE_CAR form since it should be read-only

- apps/store/public/locales/sv-se/common.json
> Update country label translations

- apps/store/src/components/InsurableLimits/InsurableLimits.tsx
> InsurableLimits: avoid shriking plus icon

- apps/store/src/blocks/ProductPageBlock/ProductPageBlockBase.tsx
- apps/store/src/components/CheckoutPage/CartCollapsible/CartCollapsible.tsx
> Use theme transition

- apps/store/src/blocks/ProductPageBlock/ProductPageBlockBase.tsx
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceCalculator/StepIcon.tsx
- apps/store/src/components/ProductPage/PurchaseForm/ComparisonTableContainer.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
- apps/store/src/components/ProductPage/Tabs.tsx
- apps/store/src/components/ProductVariantSelector/ProductVariantSelector.tsx
- apps/store/src/components/Video/Video.tsx
- apps/store/src/pages/_document.tsx
- apps/store/src/services/priceIntent/PriceIntentService.ts
- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/components/HeadingLabel/HeadingLabel.tsx
Fix various small todos in the codebase.
See inline comments.
> Fix small todos across codebase

- apps/store/src/blocks/ButtonBlock.tsx
Align multiple buttons with space between them
Design feedback
> Align multiple buttons with space between them

- packages/ui/src/components/Heading/Heading.helpers.ts
> Use Hedvig Letters Big for serif48

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
- Open product nav by default in mobile top menu
- Fix so that it's possible to scroll the mobile top menu when it's open
> Open product nav by default & add scroll

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/blocks/ProductPageBlock/DesktopLayout.tsx
- apps/store/src/blocks/ProductPageBlock/MobileLayout.tsx
- apps/store/src/blocks/ProductPageBlock/ProductPageBlock.tsx
- apps/store/src/blocks/ProductPageBlock/ProductPageBlockBase.tsx
- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Use ref to scroll specifically to top of tab content on PDP page.
We scroll all the way to the top of the page which is confusing since you don't see the tab content.
> PDP: fix tab to not scroll too far

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/blocks/ProductPageBlock/DesktopLayout.tsx
- apps/store/src/blocks/ProductPageBlock/MobileLayout.tsx
- apps/store/src/blocks/ProductPageBlock/ProductPageBlock.tsx
- apps/store/src/blocks/ProductPageBlock/ProductPageBlockBase.tsx
- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/services/PriceCalculator/formFragments.ts
> Add input mode to email field

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/blocks/ProductPageBlock/DesktopLayout.tsx
- apps/store/src/blocks/ProductPageBlock/MobileLayout.tsx
- apps/store/src/blocks/ProductPageBlock/ProductPageBlock.tsx
- apps/store/src/blocks/ProductPageBlock/ProductPageBlockBase.tsx
- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/Header/Header.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
- apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/services/PriceCalculator/formFragments.ts
Show cart toast on top of the page (over content and menu).
The top menu is static on PDP so there's no clear way to show it below the header.
> Show cart toast on top of page (menu is static)

- apps/store/src/components/Header/HeaderStyles.tsx
> Add padding to bottom of mobile top menu

- apps/store/src/components/CheckoutHeader/Breadcrumbs.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
Check the screenshot below for list of what changed.
Designers said so
> Update checkout page styles 💅

- apps/store/next-csp.config.js
> Update CSP config to fix latest errors from staging

- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/utils/useHighlightAnimation.ts
- Tweak timing of the hightlight animation after feedback from design.
- `TextField`: update text color while the animation is running.
Design feedback.
> Tweak timing for highlight animation

- apps/store/src/components/PriceCalculator/HouseholdSizeField/HouseholdSizeField.tsx
- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/utils/useHighlightAnimation.ts
- Update icons in stepper input / household size field
- Make it always 48px height
Design review.
> Update design of household size field

- apps/store/src/components/PriceCalculator/HouseholdSizeField/HouseholdSizeField.tsx
- apps/store/src/components/PriceCalculator/InputRadio.tsx
- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/utils/useHighlightAnimation.ts
Update input radio component to match latest design.
> Update design for `InputRadio` component

- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceCalculator/HouseholdSizeField/HouseholdSizeField.tsx
- apps/store/src/components/PriceCalculator/InputRadio.tsx
- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/utils/useHighlightAnimation.ts
Update design of `InputSelect` to match the new design.
Remove hover/focus state until we figure out how we want it to work.
Make height explicit 48px.
Design review.
> Update design for `InputSelect`

- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceCalculator/HouseholdSizeField/HouseholdSizeField.tsx
- apps/store/src/components/PriceCalculator/InputRadio.tsx
- apps/store/src/components/TextField/TextField.tsx
- apps/store/src/utils/useHighlightAnimation.ts
Fix alignment in small variant of text field.
It was messed up with the recent changes.
> Fix alignment in small text field

- apps/store/apollo.config.js
Point to the staging variant of the Apollo Studio graph.
This was recently updated by backend.
> Update apollo config to point to staging variant

- apps/store/src/components/CartInventory/CampaignsSection.tsx
- apps/store/src/components/CartInventory/useCampaign.ts
- apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
- apps/store/src/components/PriceCalculator/SsnSeSection.tsx
- apps/store/src/services/apollo/client.ts
- apps/store/src/utils/useErrorMessage.ts
- apps/store/src/utils/useGetMutationError.ts
- Convert success responses with userError into ApolloErrors
- Provide a way to extract error message or provide default
- Show inline error message for SSN field
- Reduce boilerplate around error handling
- Make sure unhandled errors are reported (they now result in unhandled exceptions)
[GRW-2229]: https://hedvig.atlassian.net/browse/GRW-2229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Transform userError from response into ApolloError then handle it

- apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
- apps/store/src/components/PriceCalculator/CarRegistrationField.tsx
- apps/store/src/components/TextField/TextField.tsx
- Add button to delete all text in `TextField` component
- Replace `onChange` prop with simpler `onValueChange` in `TextField`
- Slight refactor
Design review.
> `TextField`: add delete text button

- packages/ui/package.json
- yarn.lock
> Remove react-animate-height dependency

- apps/store/src/blocks/InsurableLimitsBlock.tsx
- apps/store/src/components/InsurableLimits/InsurableLimits.tsx
See title
No longer need it, and if we do we can add a HeadingBlock above
> Remove heading from Insurable Limits block

- apps/store/next-csp.config.js
- apps/store/public/locales/en/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/components/AppErrorDialog.tsx
- apps/store/src/components/CartInventory/useRemoveCartEntry.ts
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
- apps/store/src/pages/_app.tsx
- apps/store/src/services/appErrors/AppErrorContext.tsx
- apps/store/src/utils/useErrorMessage.ts
Provide API for handling Apollo errors by showing generic full-screen dialog
Specific error messages will be handled in next PRs
> Add AppErrorDialog and AppErrorHandleContext for showing generic errors

- apps/store/next-csp.config.js
- apps/store/public/locales/en/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/components/AppErrorDialog.tsx
- apps/store/src/components/CartInventory/useRemoveCartEntry.ts
- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
- apps/store/src/pages/_app.tsx
- apps/store/src/services/appErrors/AppErrorContext.tsx
- apps/store/src/utils/PageLink.ts
- apps/store/src/utils/useErrorMessage.ts
Quick and dirty solution for showing /se/forsakringar but /en-se/store
> Make store link use locale-specific slug for Swedish

- apps/store/public/locales/dk/common.json
- apps/store/public/locales/en/common.json
- apps/store/public/locales/no/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/DateInput.tsx
Update the date input field to match new designs. 
https://user-images.githubusercontent.com/59652803/220919606-04179d3b-f792-440a-a3d5-a0516c2986cb.mov
[GRW-2280]: https://hedvig.atlassian.net/browse/GRW-2280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2280 / Date-input-design-updates

- apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
- apps/store/src/components/PriceCalculator/StepIcon.tsx
Update indicator in PriceCalcualtor for upcoming sections filled instead of outlined.
Design request.
> PriceCalculator: update design of section indicator

- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
- apps/store/src/components/PriceCalculator/StepIcon.tsx
> Show cart toast under menu on desktop

- apps/store/src/blocks/AccordionBlock.tsx
See title
On mobile especially, you will end up with a long scroll when opening multiple accordions. Design request.
> Contract accordion item when opening another

- packages/ui/src/icons/LockIcon.tsx
> Fix LockIcon properties

- apps/store/src/components/CartInventory/CampaignsSection.tsx
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/TextField/TextField.tsx
> Fix color for placeholder in select input

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/graphql/ShopSessionFragment.graphql
- apps/store/src/pages/cart.tsx
Skip fetching product recommendations with every shop session.
Fetch product recommendations on demand after loading the rest of the page (cart).
Try to speed up loading of the cart page.
> Skip fetching recommendations with shop session

- apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/services/storyblok/storyblok.ts
Provide `<title>` for confirmation page controlled from CMS.
> Add head/title for confirmation page from CMS

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
> Remove (H) symbol from product names

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/components/Accordion/Accordion.stories.tsx
See title
Couldn't collapse by default when type is single
> Make accordions collapsible when single

- apps/store/next-i18next.config.js
- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/services/Flags/Flags.ts
- apps/store/src/services/storyblok/storyblok.ts
Add feature flag for enabling/disabling the english locale.
Hide language selector if English locale is not available.
For the launch.
> Add feature flag for english locale

- apps/store/src/components/Perils/Perils.tsx
> fix(Perils): key warning

- apps/store/src/pages/api/revalidate.ts
- apps/store/src/services/storyblok/Storyblok.helpers.ts
Disable manual cache version handling temporarily.
We are seeing some strange issues were some people are not able to view the site but others are.
> Disable cache version handling in Storyblok

- apps/store/src/blocks/AccordionBlock.tsx
See title.
Needed to make it fit into confirmation page.
Will not be needed after we allow block layout customizations.
> Add option to center layout in AccordionBlock

- apps/store/src/blocks/HeaderBlock.tsx
Use CSS media queries to handle elements that should only show on mobile or desktop.
`useBreakpoint` was causing flickering on initial render.
> Fix flashing submenu in header block

- apps/store/next-csp.config.js
- apps/store/package.json
- apps/store/src/components/ContactSupport/ContactSupport.tsx
- apps/store/src/components/ContactSupport/IntercomChatButton.tsx
- yarn.lock
Related to https://github.com/HedvigInsurance/racoon/pull/1647
- Adding intercom integration
- (in vercel) added a `NEXT_PUBLIC_INTERCOM_APP_ID` .env variable for production / dev / preview
[GRW-2323]: https://hedvig.atlassian.net/browse/GRW-2323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Grw-2323 / Add intercom

- apps/store/src/blocks/TextBlock.tsx
Add text alignment setting to text block
No possibility to change text alignment currently
> Add text alignment setting to text block

- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/CartNotification/ProductItem.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
> Cart toast: show pillow image from API

- apps/store/src/graphql/ExternalInsurerUpdate.graphql
* Update due schema changes
https://github.com/HedvigInsurance/storefront/pull/296/files
> chore: updated graphql schema

- apps/store/src/blocks/AccordionBlock.tsx
- apps/store/src/blocks/TabsBlock.tsx
- apps/store/src/components/GridLayout/GridLayout.helper.tsx
* Update TabList width
* Update spacing between tags and accordion items: 4px
Requested by Zak
> styles(Tabs): updates accordion styles when it gets rendered inside tabs

- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/services/Flags/Flags.ts
Add feature toggle for success animation on confirmation page.
We don't have the final video yet.
> Add feature toggle for success animation

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/services/Tracking/Tracking.ts
Add `memberId` to signed customer event
Tracking request
> Add memberId to signed customer event

- apps/store/src/components/ContactSupport/IntercomChatButton.tsx
- apps/store/src/services/Flags/Flags.ts
- Added env var to Vercel 
- impl feature flag in the intercom component
We want to be able to turn this feature off and on when needed.
> GRW-2327 / Feature Flag 🎏 : Intercom

- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
> Fix layout issue on mobile for app links

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/TierSelector/TierSelector.stories.tsx
- apps/store/src/components/TierSelector/TierSelector.tsx
- apps/store/src/components/TierSelector/TierSelectorStyles.tsx
Update styles for tier selector to match design.
[Screen Recording 2023-02-28 at 14.00.44.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/615ea2ea-10ed-4199-8c1f-d46da9d4d72f/Screen%20Recording%202023-02-28%20at%2014.00.44.mov)
Launch is soooooooooooooooooooooon!
> Update styles for tier selector

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/components/Header/Header.tsx
Make the primary menu item clickable - link to the first page of the current section.
Requested from design.
Do we think this implicit solution is good enough? Or should we add a new field to the CMS for this?
> Make main menu item clickable/link

- apps/store/src/components/Header/ShoppingBagIcon.tsx
> Update shopping cart icon to match pillow radius

- apps/store/src/components/Pillow/Pillow.tsx
> Update pillow placeholder image

- apps/store/next-csp.config.js
> Add sgtm origin to CSP img rule

- apps/store/src/blocks/ProductPageBlock/DesktopLayout.tsx
- apps/store/src/blocks/ProductPageBlock/MobileLayout.tsx
- apps/store/src/blocks/ProductPageBlock/ProductPageBlockBase.tsx
Fix issue where chevron icon was being rendered outside selector
> styles(ProductVariantSelector): render chevron icon on the correct place

- apps/store/src/components/CartInventory/useCampaign.ts
Remove custom apollo cache options.
Force refetch shop session after adding campaign code.
We don't understand why the page isn't updating like we expect. The Apollo cache is correctly updated but it doesn't get propagated through the custom shop session hook/context.
> Make sure to refresh cart after adding campaign code

- packages/ui/src/components/Heading/Heading.helpers.ts
> Update heading styles

- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/DateInput.tsx
Make the native value text hidden.
> Fix/ ios date picker

- package.json
- yarn.lock
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> 
> #### What changed
> - Package.json: turbo version changed from 1.7.4 to 1.8.3
> - Yarn.lock: turbo version changed from 1.7.4 to 1.8.3 in multiple entries
> 
> #### Impact
> The diff updates the version of turbo from 1.7.4 to 1.8.3.
> 
> #### Testing
> This diff can be tested by running the application and verifying that the new version of turbo is being used. Additionally, unit tests should be run to ensure that the changes do not break existing functionality.
</details>
Didn't find any changes from the changelog that we need to adopt in code.
---
> Update turborepo 1.8

- apps/onboarding/package.json
- apps/store/package.json
- yarn.lock
Updating MSW. We've been ignoring it for a long while now. Let's test it out to see if it works.
Keeping up to date with our deps.
> Major Version Update msw 1.1.0 

- .github/renovate.json
- Automerge all dev deps, including major versions.
- Remove pr creation limit to test how that works for us.
> Renovate: Update config

- apps/store/src/pages/api/redirect/appstore.ts
Log more from QR code API route so we can see it's working.
> Add some logs to QR code API route

- apps/store/src/components/CartInventory/DetailsSheet.ts
> Increase padding to clear dialog footer

- apps/store/src/pages/cart.tsx
See title.
Accesibility issue.
> Add title tag to cart page

- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
- apps/store/src/pages/api/redirect/appstore.ts
- apps/store/src/utils/appStoreLinks.ts
Refactor app store links utility
Merge app store link utility into one file
One source of truth.
> Refactor app store links

- apps/store/src/components/ProductPage/PurchaseForm/PriceCalculatorDialog.tsx
> Fix / Price calculator cross icon size

- apps/store/src/components/ConfirmationPage/SuccessAnimation.tsx
Try out the state reducer pattern for `SuccessAnimation` component.
I think it clarifies things and cleanly separates logic from presentation.
Read more here: https://kentcdodds.com/blog/the-state-reducer-pattern-with-react-hooks
> SuccessAnimation: use state reducer pattern

- apps/store/src/pages/api/campaign/[code].ts
Always redirect to the user defined path after attaching campaign code.
Before we used the fallback path if something went wrong but this is unexpected behaviour.
> Campaign API route: always redirect to user defined URL

- apps/store/next-csp.config.js
See title
Intercom cannot be loaded at the moment without allowing this connection.
> add js.intercomcdn.com back to script-src

- apps/store/src/components/Pillow/Pillow.tsx
Update decoding for pillow images.
Avoid seeing them load after you open the menu.
> Update image decoding for pillows to avoid 'popping'

- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/pages/cart.tsx
> Make cart page static

- apps/store/src/middleware.ts
> Update middleware config

- apps/store/src/graphql/Product.graphql
> Remove unused query

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/ProductTierSelector.tsx
- apps/store/src/components/TierSelector/TierSelector.tsx
- apps/store/src/graphql/Product.graphql
Fix how tier selector works so we forward the correct product offer id to the cart mutation.
Also make sure tier selector is open by default.
I broke it in a previous PR.
> Fix add to cart for car

- apps/store/src/components/ProductGrid/ProductGrid.tsx
Set max-width on ProductGrid
Make sure ProductGrid aligns to the rest of the page
> Set max-width on ProductGrid

- apps/store/src/components/CartInventory/CartEntryItem.tsx
- apps/store/src/components/CartInventory/CartEntryOfferItem.tsx
Refactored the cart entry item layout based on new designs. 
**before**
**After**
(figma left / after right)
**keyboard focused**
updated designs
[GRW-2362]: https://hedvig.atlassian.net/browse/GRW-2362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2362 / Update Cart Entry Item Layout v.2

- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/ProductPage/PurchaseForm/ComparisonTable/ComparisonTable.tsx
- apps/store/src/components/ProductPage/PurchaseForm/ComparisonTableContainer.tsx
- apps/store/src/components/ProductPage/PurchaseForm/ComparisonTableModal.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Open comparison table in modal
https://user-images.githubusercontent.com/6661511/224150480-0f013107-1a9e-400c-811a-263e4bee482d.mov
https://user-images.githubusercontent.com/6661511/224150581-ba31d295-13cc-4265-b020-bcb9b6e60e65.mov
[Updated design](https://www.figma.com/file/8SfzuQEJ4LJ6uKL0l7WKoE/Hedvig.com-%C2%B7-Final-Design?node-id=5952%3A71242&t=wMdwR8RDFaUTPLg3-1)
> Open comparison table in modal

- apps/store/next-csp.config.js
Apply CSP child-src properly.  Fixes production issue
> Fix CSP syntaxt for child-src

- apps/store/src/utils/isDisabledPetLink.ts
> Update disabled pet urls

- apps/store/src/services/bankId/useBankIdCheckoutSign.ts
Authenticate shopSession for new member before redirecting to next step
Fixes a bug where after payment connection we still had "payment connection required" and redirected to payment connection in endless loop
> Authenticate shopSession after signing new member

- apps/store/src/blocks/RichTextBlock/RichTextBlock.styles.tsx
- apps/store/src/blocks/TextBlock.tsx
Add link stying to TextBlock
https://user-images.githubusercontent.com/6661511/225639912-61b99ae8-10c5-4e54-a5dd-e970b4398532.mov
Currently no styling for links in TextBlock
> Add link stying to TextBlock

- apps/store/src/services/PriceCalculator/data/SE_PET_CAT.ts
- apps/store/src/services/PriceCalculator/data/SE_PET_DOG.ts
- apps/store/src/services/PriceCalculator/formFragments.ts
> Add livingSpace field to pet form

- apps/store/src/services/bankId/useBankIdLogin.ts
Subj
We would be able to track how popular is early login flow
> Add Datadog actions to bankIdLogin flow: prompt, start, complete, cancel

- apps/store/src/components/CartInventory/CartEntryOfferItem.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
Keep loading state until all data in the cart is refreshed.
Refactor "cart offer entry item" component, clean up.
Add some more logging for related events.
Avoid "UI popping".
> Improve UX of adding priced recommendation

- apps/store/src/components/Combobox/Combobox.tsx
- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/PetBreedField.tsx
- apps/store/src/graphql/PriceIntentAvailableBreeds.graphql
- apps/store/src/services/PriceCalculator/Field.types.ts
- apps/store/src/services/PriceCalculator/data/SE_PET_CAT.ts
- apps/store/src/services/PriceCalculator/data/SE_PET_DOG.ts
* Adds loading UI form `Combobox`
* Added PetBreedInput
https://user-images.githubusercontent.com/19200662/225735575-6a08a023-aaa0-48a9-a3be-02f67655f7e5.mov
<br/>
Testing Links:
* [🐕  Dog Insurance](https://hedvig-dot-com-git-grw-2354-featpet-breed-field-hedvig.vercel.app/se/forsakringar/djurforsakring/hundforsakring)
* [🐱 Cat Insurance](https://hedvig-dot-com-git-grw-2354-featpet-breed-field-hedvig.vercel.app/se/forsakringar/djurforsakring/kattforsakring) 
**Disclaimer 1**: Please note this doesn't support mixed breed for dogs yet.
**Disclaimer 2**: It's not possible to create a offer with this setup yet because BE expects a different field for breeds: `breed` instead of `breeds`. However, this will change. More info [here](https://hedviginsurance.slack.com/archives/C04SUH8E61K/p16789821 …
> GRW-2354-feat: added PetBreedField

- apps/store/src/services/apollo/client.ts
Fix bug in parsing user error messages from backend.
We didn't account for the fact that "result" variable can be `null` / `undefined` so we got a runtime error.
> Fix bug in parsing user errors

- apps/store/src/services/PriceCalculator/data/SE_PET_CAT.ts
- apps/store/src/services/PriceCalculator/data/SE_PET_DOG.ts
> Update to correct pet field names

- apps/store/src/components/CheckoutPage/CartCollapsible/CartCollapsible.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
> Add bottom border to cart collapsible

- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
> Add datadog actions to track quick checkout usage

- packages/ui/src/lib/globalStyles.ts
> Remove clip-path hack since it clips the loaded image as well

- apps/store/src/blocks/RichTextBlock/RichTextBlock.styles.tsx
- apps/store/src/pages/_app.tsx
Randomize hover color on links. A new color on every page load but the same for all links on the page
https://user-images.githubusercontent.com/6661511/226832633-3a8c3839-649b-485b-82ac-f63eb1bae3bd.mov
[Preview app](https://hedvig-dot-3t8gu3gex-hedvig.vercel.app/api/preview?secret=DWafxGrY6M8&slug=se/hedvig/legal-information-copy&_storyblok=266110806&_storyblok_c=page&_storyblok_version=&_storyblok_lang=default&_storyblok_release=0&_storyblok_rl=1679470530315&_storyblok_tk[space_id]=165473&_storyblok_tk[timestamp]=1679470530&_storyblok_tk[token]=b2221ff34357f849bc92b527a80b33d9f9bdb387)
Nice touch, see figma [spec ](https://www.figma.com/file/qUhLjrKl98PAzHov9ilaDH/New-Web-UI-Kit?node-id=2035%3A12007&t=dOuORAt9hzZlM6Xe-1)
> Randomize hover color on link

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/NavigationLink.tsx
Update Product menu layout
https://user-images.githubusercontent.com/6661511/227118194-2a6996ed-6153-48ab-ac4b-9a8ba78f8c43.MP4
https://user-images.githubusercontent.com/6661511/227118878-462169fc-df8d-4717-ba20-d0941cbb01a4.mov
Better layout for multiple items and more consistent design
> Update product navigation in menu

- apps/store/src/components/CartInventory/CampaignsSection.tsx
- apps/store/src/components/ProductPage/PurchaseForm/ComparisonTable/ComparisonTable.tsx
- apps/store/src/services/adyen/Adyen.helpers.ts
> Remove useTheme emotion hook

- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useOpenPriceCalculatorQueryParam.ts
> Report open price calculator event on 'see your price' click

- apps/store/src/components/CartInventory/CartEntryOfferItem.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
- apps/store/src/components/ProductPage/PurchaseForm/useOpenPriceCalculatorQueryParam.ts
- apps/store/src/graphql/OfferRecommendationFragment.graphql
- apps/store/src/graphql/ProductOfferFragment.graphql
- apps/store/src/services/Tracking/Tracking.ts
- apps/store/src/services/gtm.tsx
Let e-com know if a new customer made a purchase or not.
> Ecom: distinguish new from returning members

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
See title.
Missed sending this event when adding the new feature.
> Ecom: report begin checkout for quick checkout

- apps/store/src/components/Combobox/Combobox.tsx
- apps/store/src/components/PriceCalculator/MixedBreedPicker/MixedBreedPicker.tsx
- apps/store/src/services/PriceCalculator/data/SE_PET_CAT.ts
- apps/store/src/services/PriceCalculator/data/SE_PET_DOG.ts
- Add shadow to combobox when expanded
- Add z-index to combobox when expanded
- Increase font size of combobox
- Update padding in mixed breed picker
- Move up breed picker for dog (and cat?)
Improve UX and match design.
> Update combobox design with shadow/zindex

- apps/store/src/pages/checkout/[shopSessionId]/payment/[status].tsx
Redirect to confirmation page if any error occurs during payment status page.
> Always redirect if payment status page gets error

- apps/store/src/components/PriceCalculator/AutomaticField.tsx
- apps/store/src/components/PriceCalculator/CarRegistrationField.tsx
> Add autofocus support for car registration field

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/components/Header/Header.stories.tsx
- apps/store/src/components/Header/NavigationLink.tsx
- packages/ui/src/components/HeadingLabel/HeadingLabel.tsx
Support for adding label to Product menu items
Update Header storybook to better match current design
Highlight products
> Add label to Product items in menu

- apps/store/src/blocks/HeaderBlock.tsx
- apps/store/src/blocks/RichTextBlock/RichTextBlock.styles.tsx
- apps/store/src/components/CartInventory/DetailsSheet.ts
- apps/store/src/components/Header/Header.stories.tsx
- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/NavigationLink.tsx
- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
- apps/store/src/components/TierSelector/TierSelector.tsx
- packages/ui/src/components/HeadingLabel/HeadingLabel.tsx
- packages/ui/src/lib/theme/colors/colors.ts
- Adjust gap between app buttons
- Update border colors
> Minor mobile menu fixes

- apps/store/public/locales/en/checkout.json
- apps/store/public/locales/sv-se/checkout.json
- apps/store/src/components/PriceCalculator/CarRegistrationField.tsx
- apps/store/src/components/SwitchingAssistantPage/ContractCard.tsx
- apps/store/src/components/SwitchingAssistantPage/SwitchingAssistantPage.tsx
- apps/store/src/components/SwitchingAssistantPage/useSwitchingContracts.ts
- apps/store/src/graphql/ContractBankSigneringCancellationInitiate.graphql
- apps/store/src/graphql/ContractExternalInsuranceCancellation.graphql
- apps/store/src/graphql/ShopSessionOutcome.graphql
- apps/store/src/pages/checkout/[shopSessionId]/switching-assistant.tsx
- Use new BankSignering API.
- Always send registration number without whitespace to PriceIntent API.
Switch to the API powered by Storefront.
> Use new API for BankSignering Switching

- apps/store/src/components/PriceCalculator/SsnSeSection.tsx
- apps/store/src/components/TextField/TextField.tsx
- Show warning icon in text field alongside message.
- Increase space between text field and button in SSN input.
UI feedback from Wille.
> Show warning icon + message in text field

- apps/store/src/components/PriceCalculator/PetDogBreedsField.tsx
- apps/store/src/graphql/PriceIntentAvailableBreeds.graphql
Show pure breeds in mixed breed picker.
We should only show named mixed breeds in the top level selector.
> Only show pure breeds in mixed breed picker

- apps/store/src/components/Header/NavigationLink.tsx
- packages/ui/src/components/Badge/Badge.helper.ts
- packages/ui/src/components/Badge/Badge.stories.tsx
- packages/ui/src/components/Badge/Badge.tsx
Add size prop to Badge component
It needs at least two sizes
> Add size prop to Badge component

- apps/store/src/components/Header/HeaderStyles.tsx
- apps/store/src/components/Header/NavigationLink.tsx
- packages/ui/src/components/Badge/Badge.helper.ts
- packages/ui/src/components/Badge/Badge.stories.tsx
- packages/ui/src/components/Badge/Badge.tsx
> Adjust padding in mobile menu

- apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
* Keep loading state while page is transitioning
https://user-images.githubusercontent.com/19200662/228395689-4f881a6d-f743-4e76-bb30-f31a42a737f9.mov
[GRW-2216]: https://hedvig.atlassian.net/browse/GRW-2216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> styles(CheckoutPage): keep loading state while page transition doesn't get into place

- packages/ui/src/lib/media-query.ts
Revert optimization to `useMediaQuery` hook.
Was causing visual bugs in Perils component.
It also didn't resolve the original issue.
> Revert media query hook optimization

- apps/store/src/graphql/ProductData.graphql
> Stop fetching peril icons (unused)

- apps/store/src/components/ProductPage/PurchaseForm/DeductibleSelector.tsx
> Sort deductibles based on monthly total

- apps/store/src/components/PriceCalculator/InputRadio.tsx
An alternative solution for #2069
> GRW-2425 - option 2

- apps/store/src/components/Perils/Perils.tsx
> Add peril colors for pet

- apps/store/next.config.js
> Fix invalid next config rewrites option

- apps/store/src/components/PriceCalculator/InputRadio.tsx
* Make whole `HorizontalItem` area clickable
Requested by Willian - better UX
[GRW-2425]: https://hedvig.atlassian.net/browse/GRW-2425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2425 - feat(HorizontalRadioButton): make whole area clickable

- apps/store/src/components/ProductPage/PriceIntentContext.tsx
- apps/store/src/components/ProductPage/PurchaseForm/DeductibleSelector.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/getOffersByPrice.ts
- Pre-select cheapest offer in the offer presenter
- Handle deductibles when remembering which option was selected after updating info
Better UX.
> Pre-select cheapest offer

- apps/store/src/components/PriceCalculator/InputRadio.tsx
* Refactor "whole item clickable" implementation with `<label>s`
* Add missing cursor to `HorizontalItem`
I've forgotten about adding the cursor
[GRW-2425]: https://hedvig.atlassian.net/browse/GRW-2425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2425 - styles: add cursor to input radio button horizontal item

- apps/store/src/components/Combobox/Combobox.tsx
- apps/store/src/components/PriceCalculator/MixedBreedPicker/MixedBreedPicker.tsx
- Add size option to combobox according to design system
- Make nested mixed breed picker a small combobox
> Add size option to combobox

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/services/priceIntent/priceIntent.constants.ts
Fetch SSN from customer to pass to Insurely.
Before it was stored in the price intent data.
> Update how to get SSN to pass to Insurely

- apps/store/src/components/AppErrorDialog.tsx
- apps/store/src/components/BankIdDialog.tsx
- apps/store/src/components/CartInventory/RemoveEntryDialog.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/PriceCalculator/SsnSeSection.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/services/priceIntent/priceIntent.constants.ts
- Fix centering of content in full screen modals
- Update boolean JSX props to be more explicit
Noticed that content was no longer centered in bank ID modals.
Boolean props in JSX will likely be deprecated in the future. This PR makes it more explicit what the props are doing.
> Fix content centering in fullscreen modal

- apps/store/src/pages/api/preview.ts
- Pass along query params from the API preview route
- Refactor cookie override to look the same as recommended by Storyblok
The visual editor is broken.
> Fix Storyblok visual editor setup

- apps/store/src/services/Insurely/Insurely.tsx
Update Insurely iFrame URL.
Feedback from Insurely.
> Update Insurely iFrame setup

- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
Refactor BankSignering option in Cancellation Form.
Merge the two BankSignering options into one.
Step 1:
Step 2:
Step 3:
We want to allow the user to opt out of switching before we "force" them to look up their renewal date at the current company.
> Refactor BankSignering cancellation option

- apps/store/public/robots.txt
Fix robots.txt, comments must use # prefix
> Tiny: fix comment syntax in robots.txt

- packages/ui/src/components/Button/Button.stories.tsx
- packages/ui/src/components/Button/Button.tsx
Add new "secondary-alt" button variant
Needed for cart design updates
> Add white button variant

- apps/store/src/services/Tracking/Tracking.ts
Our Adtraction program isn't based on order amount, total should be set to 0
Request by Adtraction
> Set transactionTotal to 0

- apps/store/src/pages/_app.tsx
- apps/store/src/services/OneTrust.tsx
> Prevent OneTrust banner from overlapping dialogs

- apps/store/public/locales/dk/checkout.json
- apps/store/public/locales/dk/common.json
- apps/store/public/locales/no/checkout.json
- apps/store/public/locales/no/common.json
- apps/store/public/locales/sv-se/cart.json
> Update translations for recommendation card

- apps/store/public/locales/dk/checkout.json
- apps/store/public/locales/dk/common.json
- apps/store/public/locales/en/cart.json
- apps/store/public/locales/no/cart.json
- apps/store/public/locales/no/checkout.json
- apps/store/public/locales/no/common.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/CartInventory/CampaignsSection.tsx
- apps/store/src/components/Switch.tsx
- apps/store/src/components/ToggleCard/ToggleCard.tsx
Add animation to "Switch" component
Make Switch component global
Add toggle for campaign section in cart
Design updates for the cart from Wille
> Add toggle for campaign section in cart

- apps/store/src/components/BankIdLoginForm.tsx
> fix(BankIdButton): fix spacing between icon and text

- apps/store/src/components/PriceCalculator/PetDogBreedsField.tsx
Removes one line from comment that shouldn't be there.
Spotted while working on something else.
> chore(PetDogBreedsField): remove undesired line of code

- apps/store/public/locales/dk/cart.json
- apps/store/public/locales/en/cart.json
- apps/store/public/locales/no/cart.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/Accordion/Accordion.tsx
- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.stories.tsx
- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
- apps/store/src/components/CartInventory/CartEntryItem/DetailsSheet.tsx
- apps/store/src/components/CartInventory/CartEntryList.tsx
- apps/store/src/components/CartPage/CartPage.tsx
Updated CartEntryItem
- Remove details modal and replace with an accordion
- Switch the cross icon to remove cart entry to a remove button
- Update design to look like a Card
https://user-images.githubusercontent.com/6661511/232728359-23e19886-fb5a-4780-8255-fc7a00db0c3f.mov
[Figma](https://www.figma.com/file/8SfzuQEJ4LJ6uKL0l7WKoE/Hedvig.com-%C2%B7-Final-Design?node-id=7009%3A25857&t=6kHlSv9Cy3iBPcz8-1)
CRO ticket
> New CartEntryItem

- apps/store/src/components/CartInventory/CartEntryItem/CartEntryCollapsible.tsx
- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
- Switch to Collapsible instead of Accordion component
- Break out to new file
https://user-images.githubusercontent.com/6661511/232848608-99caf019-1bd4-4358-84a3-0df13e29a800.mov
A Collapsible is better for this use case
> Use Collapsible component instead of Accordion for CartEntryItem

- apps/store/src/components/CartPage/useEditProductOffer.ts
- apps/store/src/components/ProductPage/PriceIntentContext.tsx
- apps/store/src/components/ProductPage/ProductPage.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
Allow users to replace an entry in the cart.
Pick up the offer ID from the URL and use it to replace the entry in the cart.
Also use it to prefill some data in the form.
To be able to add an "edit" button in the cart.
> Add ability to replace a cart item

- apps/store/src/components/PriceCalculator/InputRadio.tsx
> Style radio label as clickable

- apps/store/src/components/CartInventory/useRemoveCartEntry.ts
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
- apps/store/src/components/SwitchingAssistantPage/ContractCard.tsx
- apps/store/src/services/appErrors/AppErrorContext.tsx
- apps/store/src/utils/useErrorMessage.ts
- Allow any Error to be passed to the AppError dialog
- Makes it more useful for cases outside of failed GraphQL requests
> Accept any Error in App Error dialog

- apps/store/src/blocks/SelectInsuranceGridBlock.tsx
- apps/store/src/components/SelectInsuranceGrid/ProductItem.tsx
- apps/store/src/components/SelectInsuranceGrid/SelectInsuranceGrid.stories.tsx
- apps/store/src/components/SelectInsuranceGrid/SelectInsuranceGrid.tsx
- apps/store/src/graphql/ProductMetadata.graphql
- apps/store/src/services/storyblok/storyblok.ts
Implement Select Insurance Grid as a CMS block
Allow user to add a title and show grid inline
Another version of this component will open in an overlay/dialog
> Add Select Insurance Grid Block to CMS

- apps/store/public/locales/en/cart.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
- apps/store/src/components/CartPage/useEditProductOffer.ts
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
- apps/store/src/graphql/CartEntryReplace.graphql
- Allow users to edit cart items by pressing a button in the cart
- Makes it easier to edit items in the cart
[GRW-2451]: https://hedvig.atlassian.net/browse/GRW-2451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add edit button to `CartEntryItem`

- apps/store/src/components/Perils/Perils.stories.tsx
- apps/store/src/components/Perils/Perils.tsx
- apps/store/src/graphql/ProductData.graphql
We've got colorCode values from PCMS now, use them instead of fallback
Added logs to track and missing values once we deploy this
> Use Peril.colorCode everywhere, warn about missing colors (should not happen in production, we would be able to check the logs now)

- apps/store/src/components/GlobalBanner/GlobalBanner.tsx
> Update campaign banner color

- apps/store/src/components/GlobalBanner/GlobalBanner.tsx
- apps/store/src/components/TierSelector/TierLevelRadioGroup.tsx
- packages/ui/src/lib/theme/colors/colors.ts
Update colors in tier and deductible selectors
Update semantic border color value to match design system
Design update
> Update tier selector colors

- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
> Set same width as cart page

- apps/store/package.json
- apps/store/src/components/Header/NavigationLink.tsx
- apps/store/src/components/InputSelect/InputSelect.tsx
- apps/store/src/components/Pillow/Pillow.tsx
- apps/store/src/components/QuickPurchaseForm/QuickPurchaseForm.stories.tsx
- apps/store/src/components/QuickPurchaseForm/QuickPurchaseForm.tsx
- yarn.lock
Supports the addition of a quick way to get a price out of the context of a PDP.
[GRW-2444]: https://hedvig.atlassian.net/browse/GRW-2444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-2444 - feat: added QuickPurchaseForm component

- apps/store/.env.local.example
- apps/store/next-csp.config.js
- apps/store/next.config.js
Support rendering Market Web pages as a fallback to those that are not yet found in the CMS.
Caveat #1: we need to use Market Web 404 page.
Caveat #2: we either need to setup custom rewrites for English locale or use the same format as Market Web.
> Support rendering Market Web pages as fallback

- apps/store/public/locales/en/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/utils/formatter.ts
- Use Lokalise translation when displaying "same day dates"
- Use consistent formatting of dates otherwise: `YYYY.MM.DD` (same for all locales)
Design feedback.
> Update date formatting

- apps/store/src/components/CartInventory/CartInventory.helpers.tsx
> Fix bug when to show automatic switching message

- apps/store/src/components/QuickPurchaseForm/ProductSelector.tsx
- apps/store/src/components/QuickPurchaseForm/QuickPurchaseForm.tsx
Small design changes on `QuickPurchaseForm`
> styles(QuickPurchaseForm): change form controls order

- apps/store/src/blocks/ImageTextBlock.tsx
> fix(ImageTextBlock): max width on textual content

- apps/store/src/blocks/RichTextBlock/RichTextBlock.styles.tsx
- apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx
- apps/store/src/components/Accordion/Accordion.tsx
- packages/ui/src/lib/theme/colors/colors.ts
Update RichTextBlock according to new design
Needed to migrate content from market-web
> Updates RichTextBlock

- apps/store/src/components/ProductPage/PurchaseForm/DiscountTooltip/DiscountTooltip.stories.tsx
- apps/store/src/components/ProductPage/PurchaseForm/DiscountTooltip/DiscountTooltip.tsx
Add visual "Discount Tooltip" component
Will be used inside offer presenter
> Add visual discount tooltip component

- apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
Fix app button styling in top menu (mobile)
They were stacking on top of one another
> Fix alignment in top menu app buttons

- apps/onboarding/next.config.js
- apps/store/next-csp.config.js
Allow adding a asset prefix to onboarding app
Allow serving the onboarding app behind store app (proxy)
> Support serving onboarding app under prefix

- apps/store/src/components/Header/NavigationLink.tsx
> Increase size of pillow in top menu mobile

- apps/store/src/blocks/QuickPurchaseBlock.tsx
- apps/store/src/components/CartInventory/CampaignsSection.tsx
- apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
- apps/store/src/components/CartInventory/CartEntryOfferItem.tsx
- apps/store/src/components/CartInventory/CartInventory.tsx
- apps/store/src/components/CartInventory/RemoveEntryDialog.tsx
- apps/store/src/components/CartInventory/useCampaign.ts
- apps/store/src/components/CartInventory/useRemoveCartEntry.ts
- apps/store/src/components/CartPage/CartPage.tsx
- apps/store/src/components/CartPage/CartPageProps.types.ts
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
- apps/store/src/components/ForeverPage/ForeverPage.tsx
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useHandleSubmitAddToCart.ts
- apps/store/src/graphql/CartEntryAdd.graphql
- apps/store/src/graphql/CartEntryRemove.graphql
- apps/store/src/graphql/CartEntryReplace.graphql
- apps/store/src/graphql/CartRedeemCampaign.graphql
- apps/store/src/graphql/CartUnredeemCampaign.graphql
- apps/store/src/pages/api/campaign/[code].ts
- apps/store/src/pages/api/session/create.ts
- apps/store/src/pages/cart.tsx
- apps/store/src/pages/session/[shopSessionId].tsx
Update to use new API for managing the cart
Get rid of "cartId"
> Update Cart mutations to use new API

- apps/store/next.config.js
Forward all Next.js specific requests to onboarding-app
Serving a Next.js app behind another Next.js app is not possible without using a custom asset prefix. This PR sets up another rewrite rule to forward all requests to the onboarding app.
> Forward all Next.js requests to onboarding app

- apps/store/src/components/CartInventory/CartEntryItem/DetailsSheet.tsx
- apps/store/src/components/CartInventory/DataTable/DataTable.ts
- apps/store/src/components/PriceCalculator/PriceCalculatorAccordionSection.tsx
- apps/store/src/utils/formatter.ts
- apps/store/src/utils/useFormatter.ts
- Create utility function to autoformat values based on data field name
- Support ssn, registrationNumber, zipCode
- Consistent formatting of values without having to manually format them in every component
> Add utility to auto format based on data field name

- apps/store/next.config.js
> Rewrite storyblok proxy URLs

- apps/onboarding/next.config.js
Causes a bug when ASSET_PREFIX env variable is not set.
> Avoid undefined image asset prefix

- apps/store/next.config.js
Prevent redirect to /default when URL locale is missing
> Fix correct locale redirect with merged domain setup

- apps/store/src/components/PetMigrationPage/PetMigrationPage.tsx
- apps/store/src/graphql/PetMigrationSign.graphql
- apps/store/src/graphql/ShopSessionPetMigration.graphql
- apps/store/src/pages/pet-migration/[shopSessionId].tsx
Show Pet migration offers and allow to sign them
First working prototype of Leif signing
> Quick and dirty migration offers display and sign

- apps/store/public/robots.txt
> Refer to sitemap in robots.txt

- apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
- apps/store/src/components/HeadSeoInfo/StructuredDataOrganization.tsx
> Add structured data / organization

- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- apps/store/src/pages/manypets-migration/[shopSessionId].tsx
- apps/store/src/services/Flags/Flags.ts
New migration URL as agreed in project channel
> Rename pet-migration -> manypets-migration

- apps/store/src/blocks/FooterBlock.tsx
- apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/pages/confirmation/[shopSessionId].tsx
- apps/store/src/pages/manypets-migration/[shopSessionId].tsx
- apps/store/src/services/Features.ts
- apps/store/src/services/storyblok/storyblok.ts
- apps/store/src/utils/Features.ts
- apps/store/src/utils/isDisabledPetLink.ts
Rename Flags -> Features
Make names reflect actual usage
> Rename Flags.getFeature() -> Features.isEnabled()

- apps/onboarding/vercel.json
- apps/store/vercel.json
Cancel Vercel deployments when there's newer commit on the same branch
For some reason we didn't have it in our vercel.json - I think I just pasted some example from the docs without noticing this setting
- Prevent risk of older commit landing in production when merging stack of changes
- Reduce build queues on Vercel
> Cancel Vercel deployments when newer commit exists on the same branch

- apps/onboarding/vercel.json
- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- apps/store/src/graphql/ManyPetsMigrationOffers.graphql
- apps/store/src/graphql/ShopSessionPetMigration.graphql
- apps/store/vercel.json
Subj
- Stop relying on deprecated shopSession.priceIntents
- Allows to send backend analytics events automatically when migration page is opened
> Use manypets-specific query for migration page

- apps/store/src/blocks/GridBlock.tsx
> Clamp number of columns

- apps/store/src/utils/PageLink.ts
> Fix broken pet detuctible link

- apps/store/src/utils/PageLink.ts
> Fix broken store -> insurances link

- apps/store/.env.local.example
- apps/store/src/services/CustomerFirst.tsx
- apps/store/src/utils/l10n/locales.ts
- Set Customer First chat widget src based on locale
- Add english src
Chat should be in correct language on english page
> Customer First in english

- apps/store/src/utils/l10n/locales.ts
Change FALLBACK_LOCALE to sv-SE.  This is what we probably want by default for most visitors
> Change FALLBACK_LOCALE to sv-SE since this is what most visitors would want

- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/components/Button/DotPulse.tsx
- Only render loading dots when loading
- Use spans instead of divs as anchor text
Feedback from Peter to cleanup anchor text a bit
> Refactor button markup

- apps/store/next-csp.config.js
> Allow Trustpilot widget in CSP

- apps/store/src/pages/_document.tsx
- apps/store/src/utils/l10n/locales.ts
> Set correct html lang

- apps/store/src/blocks/AccordionBlock.tsx
Structured data had syntax error
> Fix parsing error for structured data

- apps/store/src/blocks/ButtonBlock.tsx
Checked linktype at the wrong level
> Check proper field for linktype

- apps/store/src/blocks/ConfirmationPageBlock.tsx
- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- apps/store/src/pages/manypets/migration/[shopSessionId].tsx
Support pre-offers and post-offers CMS content on Manypets migration page
Should allow us to put custom content from CMS instead of hardcoding it
> Support CMS-defined content on migration page

- apps/store/src/blocks/ImageBlock.tsx
Add layout settings to ImageBlock
Improved layout capabilities for images
> Add layout settings to ImageBlock

- apps/store/src/blocks/ModalBlock.tsx
- apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx
- apps/store/src/services/storyblok/storyblok.ts
Add new ModalBlock to be able to wrap other blocks in a Modal
Will talk with William and Peter to decide what blocks we want to be able to use in the modal
https://github.com/HedvigInsurance/racoon/assets/6661511/e60a83df-22df-449b-824f-defd815dc23a
Enable SelectInsuranceGridBlock on startpage
> Add new ModalBlock

- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
Use CartEntries component to present Manypets migration offers
> Reuse CartEntry to show Manypets offers

- apps/store/src/blocks/ModalBlock.tsx
Add fade in animation for Modal content
Make it smoooth
> Add fade in animation for Modal content

- apps/store/src/blocks/ImageTextBlock.tsx
- apps/store/src/blocks/QuickPurchaseBlock.tsx
> Remove excess padding

- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
Handle errors in Manypets migration
> Catch and display errors in manypets migration

- apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- apps/store/src/pages/checkout/[shopSessionId]/payment/[status].tsx
- apps/store/src/pages/manypets/migration/[shopSessionId].tsx
- Redirect to connect payment or confirmation page when Manypets migration is signed
- Handle signing errors originating in BankID flow
> Redirect to next page after Manypets migration sign

- apps/store/src/pages/forever/[code].tsx
Make sure we don't index forever pages with codes
> Make sure we don't index forever page

- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- apps/store/src/pages/manypets/migration/[shopSessionId].tsx
Enable CMS based SEO configuration for Migration Page
> feat(ManyPetsMigrationPage): support SEO config from CMS

- apps/store/src/components/ProductPage/PurchaseForm/ComparisonTable/ComparisonTable.tsx
* ComparsionTable UI changes to match design. Basically I've added mode padding to table data cells.
> styles(ComparisonTable): general updates

- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Update design of error dialog in Purchase Form.
Avoid text taking up too much horizontal space.
> Update purchase form error dialog design

- apps/store/src/components/ContactSupport/ContactSupport.tsx
- apps/store/src/pages/_app.tsx
Load C1 script globally
Make sure we initialise the Customer 1 script not only on pages where we have the SupportBlock
> Load C1 script globally

- apps/store/src/components/BankIdDialog.tsx
- apps/store/src/graphql/ShopSessionAuthenticate.graphql
- apps/store/src/services/bankId/useBankIdCheckoutSign.ts
- apps/store/src/services/bankId/useBankIdLogin.ts
See title.
This method is no longer needed in the API.
> Remove no-op `shopSessionAuthenticate` mutation

- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
* Added sign disclaimer to match design.
> feat(MigrationPage): added sign disclaimer note

- apps/store/src/components/CheckoutHeader/Breadcrumbs.tsx
- apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
- apps/store/src/components/CheckoutHeader/CheckoutHeaderBreadcrumbs.stories.tsx
- apps/store/src/components/CheckoutPage/CheckoutPage.tsx
- apps/store/src/components/SwitchingAssistantPage/SwitchingAssistantPage.tsx
- Update design of checkout header breadcrumbs
- Add SB story for breadcrumbs
- Add more padding to bottom of checkout signing page
Design updates
> Checkout Header Breadcrumbs: Update design

- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/lib/theme/colors/colors.ts
See title.
Add off white semantic colors.
More contrast needed when used on light gray background.
> Button: update secondary alt colors

- apps/store/public/locales/en/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/pages/payment/connect.tsx
- apps/store/src/utils/PageLink.ts
Add separate page to connect payment (existing members).
We will use this page to connect payment for existing members. The flow will begin in HOPE and will be redirected to this page.
> Add payment connect page (HOPE)

- apps/store/public/locales/en/common.json
- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/sv-se/common.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/AppErrorDialog.tsx
- apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Fix layout inside `AppErrorDialog`
Show extra title as in design
Update to match design
> Fix layout in `AppErrorDialog`

- apps/store/src/blocks/ImageTextBlock.tsx
- Add capability for VideoBlock in ImageTextBlock
- Prepare for content migration of field in Storyblok (rename field from image -> media)
https://github.com/HedvigInsurance/racoon/assets/6661511/b34606e4-b27e-478e-bfa7-04b90722ccc0
Design update
> Add video capability to ImageTextBlock

- apps/store/src/blocks/ImageTextBlock.tsx
Add option to position media in mobile
> Add option to position media in mobile

- apps/store/public/locales/dk/checkout.json
- apps/store/public/locales/en/checkout.json
- apps/store/public/locales/en/common.json
- apps/store/public/locales/no/checkout.json
- apps/store/public/locales/sv-se/checkout.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
Lokalized hardcoded header in Migration page
> Localize heading above Manypets coverage comparison table

- apps/store/public/locales/en/common.json
- apps/store/public/locales/sv-se/common.json
- apps/store/src/components/CartNotification/CartToast.tsx
Cart toast: replace checkout link with a simple close button
Design update
> Cart toast: add close button

- apps/store/public/locales/en/cart.json
- apps/store/public/locales/en/common.json
- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/no/cart.json
- apps/store/public/locales/no/purchase-form.json
- apps/store/public/locales/sv-se/cart.json
- apps/store/public/locales/sv-se/common.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/CartNotification/CartToast.tsx
- apps/store/src/components/PriceCalculator/CarMileageField.tsx
Display "miles/year" instead of "km/year" for car milage.
This is the standard in Sweden so we translate both Swedish and English to "mil" instead of "km".
> [GEN-246] Car milage: display miles/year

- apps/store/src/components/ManyPetsMigrationPage/LatestAdoptionNote.tsx
Style updates on `LatestAdoptionNote` component - _Manypets Migration Page_
To match designs.
[Figma file](https://www.figma.com/file/PwleCFje2uJsezojM6bTxs/Hedvig.com---Leif-Exploration?type=design&node-id=580-9971&t=iChiDWfmTMqCi7Wh-4)
> styles(LastesAdoptionNote): background changes and icon optical alignment

- apps/store/src/blocks/FooterBlock.tsx
> Footer: add line break in org info

- apps/store/src/components/CartPage/CartPage.tsx
> [GEN-278] Cart page: open checkout with expanded details

- apps/store/src/components/CartNotification/CartToast.tsx
> Cart toast: take up full width in mobile

- apps/store/src/blocks/AccordionItemBlock.tsx
> [GEN-274] Accordion block: update text color

- apps/store/src/components/PriceCalculator/SsnSeSection.tsx
This is not an error -- we only need to log it for debugging purposes. For example we get this if the user enters an invalid SSN.
> Skip logging non-error

- apps/store/next.config.js
> Remove unused image domain

- apps/store/.env.local.example
- apps/store/README.md
- apps/store/next-csp.config.js
- apps/store/src/middleware.ts
- apps/store/src/pages/_app.tsx
- apps/store/src/services/Tracking/Tracking.ts
- apps/store/src/services/Tracking/experiment.constants.ts
- apps/store/src/services/Tracking/experiment.helpers.ts
- apps/store/src/services/Tracking/experimentMiddleware.ts
- apps/store/src/services/Tracking/newSiteExperimentTracking.ts
- apps/store/src/services/Tracking/trackExperimentImpression.ts
- apps/store/src/services/Tracking/trackPageViews.ts
Add setup to support basic experiments / A/B testing.
See README for more information.
We should remove the "new site" experiment in a follow-up PR.
This will allow us to run experiments on the same page/slug.
> [GEN-339] Add support for basic experiments (A/B testing)

- apps/store/src/services/Tracking/experiment.constants.ts
- apps/store/src/services/Tracking/experiment.helpers.ts
- apps/store/src/services/Tracking/trackExperimentImpression.ts
Send correct variant ID to experiment impression event
Bug fix
> Send correct experiment impression variant ID

- apps/store/src/components/ArticleTeaser/ArticleTeaser.stories.tsx
- apps/store/src/components/ArticleTeaser/ArticleTeaser.tsx
See title.
Will be used in the Blog.
> [GEN-402] Add article teaser component

- apps/store/src/components/ArticleCategoryList/ArticleCategoryList.stories.tsx
- apps/store/src/components/ArticleCategoryList/ArticleCategoryList.tsx
Build article category list component
Will be used on blog page to list the links to individual categoy pages
> [GEN-412] Add Article Category List component

- apps/store/src/blocks/FooterBlock.tsx
> Add hover state to footer links

- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
- apps/store/src/components/ProductPage/PurchaseForm/useUpdateStartDate.ts
Subj.  Minor cleanup around startDateUpdate
> Remove deprecated error handling from useUpdateStartDate

- apps/store/src/blocks/RichTextBlock/RichTextBlock.styles.tsx
Accidentally underlined all text instead of just links.
> Fix rich text styles

- apps/store/src/blocks/HeroBlock.tsx
> Add support for more blocks as content and add height settings

- apps/store/src/components/LayoutWithMenu/fetchBreadcrumbs.ts
Breadcrumbs: remove trailing slash from hrefs
Match our current site URL structure
> [GEN-439] Breadcrumbs: remove trailing slash from hrefs

- apps/store/src/pages/[[...slug]].tsx
- apps/store/src/services/blog/articleCategory.ts
- apps/store/src/services/blog/articleTeaser.ts
- apps/store/src/services/storyblok/storyblok.ts
Fetch draft content for blog meta data in Storyblok Editor
Doesn't respected preview mode version currently
> Storyblok Editor: respect version when fetching blog articles

- apps/store/src/blocks/SelectInsuranceGridBlock.tsx
- apps/store/src/components/SelectInsuranceGrid/ProductItem.tsx
- apps/store/src/components/SelectInsuranceGrid/SelectInsuranceGrid.stories.tsx
- apps/store/src/graphql/ProductMetadata.graphql
- Use headline/title as link text but make whole product item clickable
- Use full display name as title for product item link
Improve UX and SEO for product item links
> [GEN-486] SelectInsuranceGrid: improve links for SEO

- apps/store/src/blocks/SelectInsuranceGridBlock.tsx
Add CMS option to decide if links in "Select Insurance Grid" go to open price calculator or not.
More flexibility for the CMS editor.
> [GEN-464] SelectInsuranceGrid: add option to open price calculator

- apps/store/src/components/Banner/Banner.types.ts
- apps/store/src/components/ForeverPage/ForeverPage.tsx
- apps/store/src/components/GlobalBanner/GlobalBanner.tsx
- apps/store/src/components/GlobalBanner/useGlobalBanner.tsx
- apps/store/src/utils/useDebugShopSession.ts
- apps/store/src/utils/useDiscountBanner.ts
* Updates `GlobalBanner` so it makes usage `Banner` component.
`GlobalBanner` is only responsible for displaying a `Banner` globally - UI is managed by `Banner` which down the stack will also be used by `AnnouncementBlock`
> refact(GlobalBanner): integrate new Banner UI componnet

- apps/store/src/blocks/HeroBlock.tsx
Add vertical alignment settings to HeroBlock 
More layout settings
> Add vertical alignment settings to HeroBlock

- apps/store/src/blocks/ManyPetsMigrationPageBlock.tsx
- apps/store/src/components/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
- apps/store/src/pages/manypets/migration/[shopSessionId].tsx
- apps/store/src/services/storyblok/storyblok.ts
* Updates _ManyPetsMigrationPage_ content type so it also supports _Announcements_ (`AnnouncementBlock`)
> feat(MigrationPageBlock): support announcements

- apps/store/src/blocks/HeroBlock.tsx
We need to check both if the field exist and if the filename is not null
Build is failing
> Catch undefined hero backgroundLandscape field

- apps/store/src/blocks/ImageTextBlock.tsx
- apps/store/src/components/Video/Video.tsx
> Add settings to ImageTextBlock to fill viewport in mobile

- apps/store/src/blocks/HeroBlock.tsx
> Make background optional in HeroBlock

- apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
- apps/store/src/features/sas/SasEurobonusSection.tsx
- apps/store/src/graphql/CurrentMember.graphql
- apps/store/src/graphql/MemberFragment.graphql
- apps/store/src/graphql/SasEurobonusNumberUpdate.graphql
- apps/store/src/pages/confirmation/[shopSessionId].tsx
Show SAS section on confirmation page if currentMember is eligible
Allow to save SAS Eurobonus number
[Screen Recording 2023-06-08 at 14.11.16.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/GLY3tSM85RFBvAf6lFNA/a06876dc-88ff-4fd5-a4c9-4c65ad769c67/Screen%20Recording%202023-06-08%20at%2014.11.16.mov)
> Support saving SAS Eurobonus number on purchase success page

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- Add a new step in `CurrentInsuranceField` to show `FetchInsurancePromot` dialog
- Use Insurely feature flag to control the visibility of the new step
- Slightly refactor dialog window styles
- Catching up to Figma design
> [GEN-511] Show prompt before launching Insurely iframe

- apps/store/src/services/CustomerFirst.tsx
Disable C1 script on Connect Payment page
It applies global styles to the page that hides iframes
> Disable C1 script on connect payment page

- apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx
Allow to toggle SAS block in ConfirmationPage story
Reusable debugging tool
> Support SAS arg in ConfirmationPage story

- apps/store/src/features/blog/README.md
- See title.
Provide more context for the maintainers.
> Add README to the blog-feature

- apps/store/src/services/CustomerFirst.tsx
> Revert hack to prevent c1 from hiding iframes

- apps/store/public/locales/en/purchase-form.json
- apps/store/public/locales/sv-se/purchase-form.json
- apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
> Update price match subtitle

- apps/store/src/components/ProductPage/PurchaseForm/DiscountTooltip/DiscountTooltip.tsx
> Fix shadow bleed issue in discount tooltip

- apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
- apps/store/src/components/PriceCalculator/FetchInsurance.tsx
- apps/store/src/components/PriceCalculator/useFetchInsurance.ts
Add additional information to logs from Insurely integration
Make it easier to see that it works as expected
> Improve logging with Insurely

- CONTRIBUTING.md
- See file
- So we can share an idea of what a feature should be
> [GEN-556] Add CONTRIBUTING docs about feature folders

- apps/store/src/components/RichText/RichText.stories.tsx
> Add story for RichText

- apps/store/src/components/ConfirmationPage/ContractCard.tsx
- apps/store/src/components/ConfirmationPage/useSwitchingContracts.ts
- apps/store/src/components/InitiateCarCancellationPage/InitiateCarCancellationPage.tsx
- apps/store/src/pages/cancellation/car/initiate/[contractId].tsx
- Create new landing page for BankSignering (CRM)
- To initiate car cancellation
- Replace Web Onboarding page
- There's no API to fetch a single contract yet
> [GEN-564] Create CRM landing page for BankSignering
