HedvigInsurance/racoon

apps/store/src/blocks/PerilsBlock.tsx
apps/store/src/components/Perils/Perils.tsx

- Show missing persils for a tier as disabled
- Add option to turn this off on the block

[GEN-276] Add option to display disabled perils

---

apps/store/src/components/ProductPage/PurchaseForm/useSelectedOffer.ts

- Add log to Datadog when selecting a price matched offer
- Wrapped select hook so we don't need to care about this in more than a single place
- Make it easier to track/debug price matching

[GEN-579] Log when selecting a price matched offer

---

apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx

Faster navigation for internal routes with next/link

Render NextLink for internal links

---

apps/store/src/blocks/ImageTextBlock.tsx

Update viewport setting to taka a dynamic height value

---

apps/store/src/features/blog/BlogArticleBlock.tsx

Update design and layout of blog article page header.

Update blog article page header layout

---

apps/store/src/components/PriceCalculator/FetchInsurance.tsx
apps/store/src/components/PriceCalculator/useFetchInsurance.ts
apps/store/src/services/Tracking/Tracking.ts
apps/store/src/services/gtm.tsx

- Implement several tracking events for Insurely/Price Matching
- `insurely_prompted` | `insurely_accepted` | `insurely_correctly_fetched` | `insurely_price_matched`
- Better tracking of the feature

[GEN-589] Implement GTM tracking for Insurely

---

apps/store/src/components/PriceCalculator/AutomaticField.tsx
apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx
apps/store/src/components/PriceCalculator/FetchInsurance.tsx
apps/store/src/components/PriceCalculator/FetchInsuranceContainer.tsx
apps/store/src/graphql/PriceIntentFragment.graphql
apps/store/src/services/Insurely/Insurely.constants.tsx

- Use new Insurely schema field to configure integration/price matching
- Remove unsued `insurelyConfigName` prop from `CurrentInsuranceField`
- Enable Car Insurance integration for Insurely

[GEN-398] Use new Insurely API schema

---

apps/store/src/blocks/HeroBlock.tsx

If it's the first block on a page it should have priority loading, but make it optional

GEN-570 / Add image priority setting to HeroBlock

---

apps/store/scripts/download-translations.sh

- Only download en and sv translations from Lokalise
- Homecoming
- We should do a bigger PR and remove the locales from the rest of the code base as well

Only download SE/EN locales from Lokalise

---

apps/store/public/locales/en/checkout.json
apps/store/public/locales/sv-se/checkout.json
apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/ForeverPage/ForeverPage.tsx
apps/store/src/components/TextWithLink.tsx

- Add link to SIGN_DISCLAIMER text on the checkout page
- Create a helper component to parse text strings with link idenfifiers (used also on Forever page)
GDPR compliance

[GEN-574] Add link to privacy policy on checkout page

---

apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/TextWithLink.tsx

- Open disclaimer link in new tab
Avoid navigating from Checkout

Checkout: open privacy policy link in new tab

---

apps/store/src/components/RichText/RichText.styles.tsx

Update RichText line-height

---

apps/store/src/blocks/ProductVariantSelectorBlock.tsx
apps/store/src/components/BankIdDialog.tsx
apps/store/src/components/Banner/Banner.tsx
apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
apps/store/src/components/CheckoutHeader/Breadcrumbs.tsx
apps/store/src/components/CheckoutPaymentTrustlyPage/SuccessState.tsx
apps/store/src/components/Combobox/Combobox.tsx
apps/store/src/components/ConfirmationPage/ContractCard.tsx
apps/store/src/components/ErrorPage/ErrorPage.tsx
apps/store/src/components/PaymentConnectPage/ErrorDialog.tsx
apps/store/src/components/PaymentConnectPage/SuccessState.tsx
apps/store/src/components/PriceCalculator/StepIcon.tsx
apps/store/src/components/ProductPage/PurchaseForm/DiscountTooltip/DiscountTooltip.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
apps/store/src/components/Switch.tsx
apps/store/src/components/TextField/TextField.tsx
apps/store/src/features/sas/SasEurobonusSection.tsx
apps/store/src/pages/payment-failure.tsx
apps/store/src/pages/payment-success.tsx
packages/ui/src/lib/theme/colors/colors.stories.tsx
packages/ui/src/lib/theme/colors/colors.ts

- Update color theme
- Organize colors in story
https://github.com/HedvigInsurance/racoon/assets/6661511/919fdee7-6c6c-4ba1-8be4-3dbe84af7f05
💅

Update color theme

---

apps/store/next.config.js
apps/store/public/locales/en/checkout.json
apps/store/public/locales/sv-se/checkout.json
apps/store/scripts/download-translations.sh

We want to still use connect payment page to update payment methods

Avoid redirecting all web-onboarding pages to info

---

apps/store/public/locales/en/checkout.json
apps/store/public/locales/sv-se/checkout.json
apps/store/src/components/ConfirmationPage/ContractCard.tsx
apps/store/src/components/ConfirmationPage/useSwitchingContracts.ts
apps/store/src/components/InitiateCarCancellationPage/InitiateCarCancellationPage.tsx
apps/store/src/graphql/Contract.graphql
apps/store/src/graphql/ShopSessionOutcome.graphql
apps/store/src/graphql/SwitchingContractFragment.graphql
apps/store/src/pages/cancellation/car/initiate/[contractId].tsx
apps/store/src/services/bankId/bankId.types.ts
apps/store/src/services/bankId/useBankIdLogin.ts
apps/store/src/utils/i18n.ts

- Implement new Contract query on BankSignering page
- Extract reusable hook to convert API contract to "BankSigneringContract"
- Implement different states for BankSignering page
- Pass authentication status from server to avoid hydration errors
- Complete the feature

BankSignering: implement contract query

---

apps/store/src/components/Pillow/Pillow.tsx
apps/store/src/components/ProductPage/PurchaseForm/ProductHero/ProductHero.stories.tsx
apps/store/src/components/ProductPage/PurchaseForm/ProductHero/ProductHero.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx

- Extract separate Product Hero component from Purchase Form
- Based on Product Hero from Figma
- Integrate new component in Purchase Form
- Add Storybook stories for different variants
The Purchase Form is probably the most complex part of the code base and could use some refactoring. This is the first step in that direction. I plan to break it up more and more into smaller components.

Extract Product Hero component from Purchase Form

---

apps/store/src/features/blog/BlogArticleBlock.tsx

General style updates on blog pages
Requested by editors.
**Disclaimer**: This only includes UI changes referred in the [ticket](https://www.notion.so/Small-fixes-for-Article-Page-ef09ccc3dc264038a7b11c0e063e745f?pvs=8&n=github_linkback). It also includes a bugfix but that one can be tricky to solve so I though we can get this merged first.

GEN-609 - styles(BlogArticleBlock): UI updates

---

apps/store/src/features/blog/ArticleTeaser/ArticleTeaser.stories.tsx
apps/store/src/features/blog/ArticleTeaser/ArticleTeaser.tsx
apps/store/src/features/blog/BlogArticleBlock.tsx
apps/store/src/features/blog/BlogArticleListBlock.tsx

- Hide tags in the blog category list block
- Remove tags from `ArticleTeaser` component
- Design update from Peter

Blog: hide tags on category list pages

---

apps/store/src/components/InitiateCarCancellationPage/InitiateCarCancellationPage.tsx

BankSignering: Fix spacing in login form

---

apps/store/src/features/blog/ArticleTeaser/ArticleTeaser.tsx

Update blog article teaser to max 5 lines

---

apps/store/src/pages/[[...slug]].tsx
apps/store/src/pages/api/disable-draft.ts
apps/store/src/pages/api/draft.ts
apps/store/src/pages/manypets/[[...slug]].tsx
apps/store/src/pages/reusable-blocks/[...slug].tsx
apps/store/src/services/storyblok/storyblok.ts

Implement Next.js Draft Mode
Remove Preview Mode
Draft Mode has replaced Preview Mode in Next.js

Use Next.js Draft Mode in favor of Preview Mode

---

apps/store/src/services/Tracking/Tracking.ts
apps/store/src/services/gtm.tsx

- Update price match GTM data for "ViewItem" event
- Include a flag if there's an exposure match
- Update "price_matched" flag to only be true if price is lower than competitor
- Request from Sonny

Update price match GTM data

---

apps/store/next.config.js
apps/store/package.json
apps/store/src/instrumentation.ts
yarn.lock

Instrument store app with tracing through OpenTelemetry
So we can see traces from requests initiated by Node.js

Instrument Open Telemetry tracing

---

apps/store/src/components/ProductPage/PriceIntentContext.tsx

- Update Price Intent on page navigation
- Check if completed Price Intent belongs to the current product
The price intent is not synced with the current product when navigating to a new page.
Instead you see the price of the previous product after you navigate.

GEN-652 | Make sure price intent is synced to current product

---

apps/store/src/components/Video/Video.tsx

Help browsers determine compability

Add mime type to videos

---

packages/ui/src/index.ts

Remove unused export from UI kit

---

.github/workflows/download-translations.yml
apps/store/scripts/download-translations.sh

Skip download translation for onboarding app in workflow
Add check if there's any reason to source env file
Focus on store app

Update download translation workflow

---

.github/workflows/download-translations.yml
apps/store/src/pages/api/slack/update-translations-work.ts
apps/store/src/pages/api/slack/update-translations.ts

Add endpoint to respond to Slack command `/update-translations` which triggers the workflow on GH with the same name.
So Peter can trigger updated translations (PR) from Slack

Slack command: update translations

---

apps/store/README.md

Update Readme with Storyblok section

---

apps/store/src/components/ProductPage/PriceIntentContext.tsx

chore(PriceIntentContext): rely on ProductOfferFragment since it's safier

---

apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
apps/store/src/components/ConfirmationPage/SwitchingAssistantSection.tsx
apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/SwitchingAssistantSection.stories.tsx
apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/SwitchingAssistantSection.tsx

Add SwitchingAssistantSection by using Apollo mock
https://github.com/HedvigInsurance/racoon/assets/6661511/424d5f63-5a6d-44fe-93d4-14c0d9dee588
Make it possible to view the component i Storybook

Add SwitchingAssistantSection story

---

apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx

- Update story structure
- Add story with SwitchingAssistant
https://github.com/HedvigInsurance/racoon/assets/6661511/841de775-85c3-4352-b07d-1a27e61a263f

Update ConfirmationPage story with SwitchingAssistant

---

apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.stories.tsx
apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
packages/ui/src/lib/theme/space.ts

Fix CartEntryItem story props

---

packages/ui/src/components/Button/Button.helpers.ts
packages/ui/src/lib/theme/radius.ts

- Update height
- Add new border radius

Update button sizes

---

apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
apps/store/src/pages/manypets/migration/[shopSessionId].tsx
apps/store/src/services/bankId/useBankIdCheckoutSign.ts
apps/store/src/services/bankId/useBankIdLogin.ts

chore(manypets): add logs for signing flow

---

apps/store/src/components/Banner/Banner.tsx

- Increase minimum height of notification banner
- Add bottom border to notification banner
- Design updates

GEN-681 | Update global banner styles

---

apps/store/src/pages/manypets/migration/[shopSessionId].tsx

Update that comment so I don't forget why we're calculating total price on FE for ManyPets migration page.

chore: update misleading comment

---

apps/store/src/components/RichText/RichText.stories.tsx

Forgot to update the story when component changed

Fix RichText component story

---

apps/store/src/components/FetchInsurancePrompt/FetchInsurancePrompt.stories.tsx
apps/store/src/components/FetchInsuranceSuccess/FetchInsuranceSuccess.stories.tsx
apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
apps/store/src/components/ProductPage/PurchaseForm/DiscountTooltip/DiscountTooltip.stories.tsx
apps/store/src/components/ProductPage/PurchaseForm/ProductHero/ProductHero.stories.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.stories.tsx
apps/store/src/mocks/productData.ts
apps/store/src/mocks/storyblok.ts
apps/store/src/services/storyblok/storyblok.ts

- Add PurchaseForm to Storybook
- Extract mocks for Storybook
- Group PurchaseForm stories
https://github.com/HedvigInsurance/racoon/assets/6661511/1d3745f7-7b6c-48d8-8dce-d9deebacc4fa

Add PurchaseForm to Storybook

---

apps/store/public/locales/en/common.json
apps/store/public/locales/sv-se/common.json
apps/store/src/components/RetargetingPage/MultiTierOffer.tsx
apps/store/src/components/RetargetingPage/ProductPageLink.tsx
apps/store/src/components/RetargetingPage/RetargetingPage.tsx
apps/store/src/components/RetargetingPage/SingleTierOffer.tsx
apps/store/src/graphql/PriceIntents.graphql
apps/store/src/graphql/ProductOfferFragment.graphql
apps/store/src/pages/session/resume/[shopSessionId].tsx

- Implement a draft version of the CRM landing page to be used for re-targeting
- List all price intents that have been confirmed but not yet added to cart
Design is just a draft but this is necessary to understand if we need to make any changes to the overall idea and/or API.

GEN-748 | Add CRM Retargeting Landing Page

---

apps/store/src/components/ProductPage/PurchaseForm/ComparisonTableModal.tsx

* Updates `<ComparisonTableModal />` (product page) so it renders the correct version of _Comparison Table_ based on viewport size.
We got a new [design](https://www.figma.com/file/qUhLjrKl98PAzHov9ilaDH/Hedvig-UI-Kit?type=design&node-id=3380-13894&mode=design&t=snZZXMBD7zxyZULO-4) for a _mobile_ version of the comparison table:

GEN-664 - refact(ComparisonTableModal): make usage of Mobile/Desktop comparison table components

---

apps/store/src/blocks/ComparisonTableBlock.tsx

* Updates `<ComparisonTableBlock />` (CMS) so it renders the correct version of _Comparison Table_ based on viewport size. Please don't mind the '*' that get's shown before each table attribute. It's a side effect of how _Desktop_  Comparison Table get's built. I gonna need to change cat/dog insurance pages a little bit when this get's released so maybe it would be better to feature flag this? 🤔  
We got a new [design](https://www.figma.com/file/qUhLjrKl98PAzHov9ilaDH/Hedvig-UI-Kit?type=design&node-id=3380-13894&mode=design&t=snZZXMBD7zxyZULO-4) for a _mobile_ version of the comparison table:

GEN-664 - refact(ComparisonTableBlock): makes usage of Mobile/Desktop comparison table components

---

apps/store/src/components/Combobox/Combobox.tsx
apps/store/src/components/PriceCalculator/MixedBreedPicker/MixedBreedPicker.tsx

- Fix issue in mixed breed selector where we were not showing correct border radius
- Fix issue in combobox where input text was not being trucated enough
Visual bugs

Fix style issue in mixed breed selector

---

apps/store/src/components/ProductPage/PageDebugDialog.tsx
apps/store/src/components/ProductPage/ProductPage.tsx

- Implement page debug dialog on product pages
- Expose link to share an offer
- Needed for inbound/outbound sales team to share offers with customers

GEN-747 | Share link to offer from debug dialog

---

apps/store/src/components/PriceCalculator/StepIcon.tsx

GEN-684 | Fix Form section heading color

---

apps/store/src/components/Video/Video.tsx

Add toggle sound button to videos
TODO: add correct icon
https://github.com/HedvigInsurance/racoon/assets/6661511/3b9c0423-d3b7-43ee-8c2a-978280f13b5a

GEN-667 - Add mute/unmute button to videos

---

apps/store/src/components/Video/Video.tsx

Add animation to mute button
[Demo](https://hedvig-dot-com-git-feat-add-animated-mute-button-hedvig.vercel.app/se/forsakringar/olycksfallsforsakring)
https://github.com/HedvigInsurance/racoon/assets/6661511/88c860cb-0570-4536-97ee-8b988e6367db

Add animation to mute button

---

apps/store/next.config.js

Redirect new-member page without code to products page
Continue draining traffic from old site

Redirect /new-member page without campaign code

---

.github/CODEOWNERS

Update CODEOWNERS with new team name

---

apps/store/src/components/ButtonNextLink.tsx
apps/store/src/components/CartPage/PageDebugDialog.tsx
apps/store/src/components/DebugDialog/CopyToClipboard.tsx
apps/store/src/components/DebugDialog/DebugShopSessionSection.tsx
apps/store/src/components/TextField/TextField.tsx
apps/store/src/pages/api/session/reset.ts
apps/store/src/utils/PageLink.ts

- Add button (link) to reset current session from Debug Dialog
- Include alongside shop session ID
- One of the common operations

Add reset sesion button to debug dialog

---

apps/store/next.config.js

Include se-en locale in the OLD site redirects
Refactor code to make it more readable
They were missing

Add redirects for se-en locale

---

apps/store/src/components/TextField/TextField.tsx

- Fix warning animation
We need to avoid animations between translucent and opaque colors.

TextField: Fix warning animation

---

apps/store/src/components/DebugDialog/DebugResumeSessionSection.tsx
apps/store/src/components/DebugDialog/DebugShopSessionSection.tsx
apps/store/src/utils/PageLink.ts

- Fix links in DebugDialog
- Skip passing locale when we don't need to
- A little broken right now

DebugDialog: fix redirect links

---

apps/store/src/graphql/BankSigneringApprovalCreate.graphql

Remove unused mutation so we can remove it from schema in storefront

Remove bankSigneringApprovalCreate mutation, never used

---

apps/store/src/components/CartInventory/CartInventory.helpers.tsx
apps/store/src/components/CartInventory/CartInventory.tsx
apps/store/src/pages/cart/index.tsx
apps/store/src/pages/checkout/index.tsx

- Extract helper hook to parse redeemed camapign to internal cart campaign type
- Nice to not spread out the parsing of this type too much (single source of truth)

GEN-799 | Extract `useGetCartEntry` helper hook

---

apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/CartPage/CartPageProps.types.ts
apps/store/src/pages/cart/index.tsx

Refactor cart page props to handle a single campaign

---

apps/store/src/components/CartInventory/CartInventory.tsx
apps/store/src/components/CartInventory/CostSummary.tsx
apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.stories.tsx
apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
apps/store/src/services/apollo/client.ts
apps/store/tsconfig.json

- Refactor `CostSummary` component to only handle single campaign
- Remove old references to `redeemedCampaigns` that are no longer needed

Refactor `CostSummary` to handle a single campaign

---

apps/store/src/components/CartInventory/CartInventory.tsx
apps/store/src/components/CartInventory/ReadOnlyCampaignSection.tsx

Refactor `ReadOnlyCampaignSection` to handle a single campaign

---

apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
apps/store/src/pages/checkout/index.tsx

Refactor `CheckoutPageProps` type to handle a single campaign

---

packages/ui/src/components/Button/Button.helpers.ts
packages/ui/src/lib/theme/radius.ts

Update border radius levels based on [latest design changes](https://www.figma.com/file/qUhLjrKl98PAzHov9ilaDH/Hedvig-UI-Kit?type=design&node-id=890-4923&mode=design&t=I2G0tL8ZlDWFBXlj-4)
Requested by William.

GEN-665 - styles: update border radius values

---

apps/store/src/utils/formatter.ts

- Handle exception when failing to parse SSN
- Saw this happen locally, not sure how a ShopSession could have an invalid SSN but at least we should not crash

Handle error when parsing SSN

---

apps/store/src/app/GlobalStyles.tsx
apps/store/src/app/layout.tsx

Include Global Emotion styles in App Router pages
Resets etc.

App Router: include global styles

---

apps/store/src/app/layout.tsx

Migrate document meta tags to app router

App Router: add site-wide metadata

---

apps/store/package.json
yarn.lock

Revert to stable version of apollo client
Caused issues with how onComplete is called when price intent is updated

Revert apollo client to stable version

---

apps/store/src/components/ComparisonTable/ComparisonTable.tsx

See title ☝️ 
Requested by William

GEN-663 - styles(ComparisonTabl): align text with icons when text wraps

---

apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx

Updates animation for dialog's content
[Requested by Willian](https://hedviginsurance.slack.com/archives/C021PN7G7MJ/p1691055000316149?thread_ts=1691052862.613309&cid=C021PN7G7MJ)

styles(FullScreenDialog): updates animation for dialog's content

---

apps/store/src/components/CartItem/CartItem.tsx

Fix layout in read only cart item

---

apps/store/src/components/CartInventory/CartEntryItem/CartEntryItem.tsx
apps/store/src/components/CartInventory/CartInventory.helpers.tsx
apps/store/src/components/CartInventory/CartInventory.tsx
apps/store/src/components/CartInventory/CartInventory.types.ts
apps/store/src/components/CartItem/CartItem.stories.tsx
apps/store/src/components/CartItem/CartItem.tsx
apps/store/src/components/CartItem/DetailsSheet.tsx
apps/store/src/features/retargeting/MultiTierOffer.tsx
apps/store/src/features/retargeting/SingleTierOffer.tsx

* Updates `CartItem` API
Simplify how `CartItem` get it's props.

GEN-821: refact(CartItem): consolidate CantEntry type 

---

apps/store/next.config.js

- Add all embark entry points for home insurance flows to be redirected to the new site
- Saw some traffic still in Datadog which was not being redirected to the new site

Web Onboarding Redirects: add more home insurance sources

---

turbo.json

- Include storyblok cache version env var in turbo repo pipeline hash
- Otherwise turbo will just reply existing hash even if the cache version has changed

Add cache version env var to turbo config

---

apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts
apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
apps/store/src/pages/debugger/index.tsx
apps/store/src/services/Insurely/Insurely.tsx

chore(eslint): enable non-nullable-type-assertion-style rule

---

apps/store/src/pages/[[...slug]].tsx

fix: update SEOData.abTestOrigin type definition

---

apps/store/src/app/api/trials/route.ts

Set the start date in Trials debugger to today
Otherwise we don't see the expected Trials extension information when navigating to the Widget

Trials debugger: set start date to today

---

apps/store/src/components/Price.tsx
apps/store/src/components/ProductItem/ProductDetailsHeader.tsx

- Add reusable `Price` component
- Will be used in "total amount" and "product item" components
- It's both doing formatting and layout/styling so but I've still seen this pattern repeated in many places in the UI.

Add reusable Price component

---

apps/store/src/components/ShopBreakdown/TotalAmount.stories.tsx
apps/store/src/components/ShopBreakdown/TotalAmount.tsx

- Add `TotalAmount` component based on Figma design (part of Shop Breakdown)
- Will be used inside new Shop Breakdown component (to come)

Add `TotalAmount` component

---

apps/store/src/components/ShopBreakdown/AddCampaignForm.tsx
apps/store/src/components/ShopBreakdown/AddedCampaignForm.tsx
apps/store/src/components/ShopBreakdown/DiscountField.stories.tsx
apps/store/src/components/ShopBreakdown/DiscountField.tsx

- Add new `DiscountField` component to be used in "shop breakdown"
- Based on Figma UI kit
- Make sure the component is not API dependent

Add `DiscountField` component

---

apps/store/src/components/ShopBreakdown/ShopBreakdown.stories.tsx
apps/store/src/components/ShopBreakdown/ShopBreakdown.tsx

- Add helpers for the full `ShopBreakdown` component
- Based on Figma components
- I didn't want to compose it from 100 props so just passing children in this case

Add full `ShopBreakdown` component/helpers

---

apps/store/src/components/ProductPage/PriceIntentContext.tsx
apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx

- Add a few more DD actions to better track BankSignering feature
- Be able to setup a proper funnel in DD

Add additional BankSignering actions

---

apps/store/src/pages/[[...slug]].tsx
apps/store/src/pages/cart/index.tsx
apps/store/src/pages/manypets/[[...slug]].tsx
apps/store/src/services/storyblok/storyblok.ts

Extract getRevalidate() function for ISR revalidate setting
Check for production instead of "!= preview" to avoid returning false in development environment

Use revalidate: 1 in development environment

---

.github/renovate.json5

Pause apollo/client bumps until issue is resolved

---

.github/renovate.json5
apps/store/package.json
yarn.lock

* Downgrade `@apollo/client` since `3.8.1` changed some introduces some changes that makes our bank id sign to break.

hotfix(apollo-client): downgrade 3.8.1 - 3.7.17

---

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx

Add purchase form desktop fade in animation
https://github.com/HedvigInsurance/racoon/assets/6661511/1c0a6def-82c9-4d11-af99-923e4b084cb7

Add purchase form desktop fade in animation

---

apps/store/next-csp.config.js

Request from Simon to enhance affiliate tracking

Allow addrevenue.io in CSP

---

apps/store/next-csp.config.js

Add addrevenue to connect-src

---

apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/ShopBreakdown/ShopBreakdown.stories.tsx

- Separate out a custom hook that tracks views of the cart page
- Part of implementing ShopBreakdown component

ShopBreakdown: break out custom tracking hook

---

apps/store/src/components/CartPage/DiscountFieldContainer.tsx
apps/store/src/components/ShopBreakdown/DiscountField.tsx

- Add a container for `DiscountField` component to connect it with the API
- Co-locate related logic with the presentational component

ShopBreakdown: add `DiscountFieldContainer`

---

apps/store/src/components/CartPage/TotalAmountContainer.tsx

- Add container for `TotalAmount` component
- Co-locate API logic related to the presentational component

ShopBreakdown: add `TotalAmountContainer`

---

apps/store/src/components/CartPage/CartPage.tsx

- Refactor the empty state component for the cart page
- Use `ShopBreakdown` component
- Simplify the code that renders the page by only focusing on one state at a time

ShopBreakdown: refactor cart page empty state

---

apps/store/public/locales/en/cart.json
apps/store/public/locales/sv-se/cart.json
apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/ProductRecommendationList/ProductRecommendationList.tsx

- Update product recommendation list header to match Figma design

ShopBreakdown: update cart page layout

---

apps/store/src/components/CartPage/RemoveActionButton.tsx

- Add container component for the "remove offer from cart"-button
- Co-locate logic

ShopBreakdown: add remove action button (container)

---

apps/store/src/components/CartPage/EditActionButton.tsx

- Add edit product offer action button component with related logic
- Co-location

ShopBreakdown: add edit action button (container)

---

apps/store/src/components/Video/Video.tsx

Update the mute state and when it animates. Also moved the sound controls next to the play button
- Muted (first load): soundbars animate once and then stops
- Muted or paused: static soundbars
- Unmuted: looping animating soundbars 
Talked with William regarding the sound controls and we thought the mute state was a bit unclear currently.

Update video controls animation and position

---

apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/CheckoutPage/PageDebugDialog.tsx

- Add page debug dialog to the checkout page
- better DX

Checkout page: add debug dialog

---

apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
apps/store/src/components/ProductItem/ProductItemContainer.tsx

- Implement new `ShopBreakdown` and `ProductItemContainer` on Confirmation page
- Unify setup

ShopBreakdown: implement on Confirmation page

---

apps/store/src/services/bankId/useBankIdCheckoutSign.ts

While debugging an [issue with singning](https://hedviginsurance.slack.com/archives/C054YL76SSU/p1692800181104929) I've noticed we probably missed to log one scenario in our signing process.
Can helps us with debugging.

chore: log error when calling startSign mutation

---

.github/renovate.json5

Renovate was complaining about previous schedule as invalid
Updated and checked here: https://codepen.io/rationaltiger24/pen/ZExQEgK

Fix renovate schedule

---

apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx

- Implement shop breakdown on many pets migration page
- Add comment about why we don't show discount
- Last place we are using the old components!
- ~I can't preview this locally so let's verify in the preview app~ Testing in staging 🙂

ShopBreakdown: implement on `ManyPetsMigrationPage`

---

apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/CartPage/QuickAddAccidentContainer.tsx
apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/ProductRecommendationList/useProductRecommendations.ts
apps/store/src/components/ShopBreakdown/QuickAdd.tsx

- Implement new `QuickAdd` component on Cart page
- Add container for `QuickAdd` component
- Add form to add offer from `QuickAdd` component (match add to cart hook)
- Replace the old setup

ShopBreakdown: implement `QuickAdd` component on Cart Page

---

apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/ShopBreakdown/QuickAddAccidentContainer.tsx

- Implement `QuickAdd` component on Checkout page
- Make container a reusable component
- Refactor

ShopBreakdown: implement `QuickAdd` component on Checkout Page

---

apps/store/src/components/ConfirmationPage/ContractCard.tsx
apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
apps/store/src/services/bankSignering.ts

- Add a new DD action to track which users are elligible for BankSignering when they add to cart
- Centralize all BankSignering events in a single BankSignering service file
- Improve options for tracking BankSignering conversion funnel
- Centralize all events for it's easy to get an overview

Improve BankSignering tracking

---

apps/store/public/robots.txt
apps/store/src/app/shop-session-debugger/page.tsx
apps/store/src/pages/cart/index.tsx
apps/store/src/pages/forever/[code].tsx

- Add noindex meta tag to Cart page
- Update Robots.txt to include locales in rules
- Include nofollow on debugger page
- The cart page is currently indexed on Google and we don't want that
- It seems like the robots.txt rules are not working as expected, so we need to include the locales in the rules

Exclude cart page from search indexing

---

apps/store/src/features/retargeting/retargeting.constants.ts
apps/store/src/features/retargeting/useRedirectUser.ts

- Optionally redeem campaign code on CRM retargeting page
- Refactor fetching query params for the page
- Reuse the functionality from the resume session route

GEN-993 | Retargeting: redeem optional campaign code

---

apps/store/src/features/retargeting/RedirectUser.tsx
apps/store/src/features/retargeting/retargeting.types.ts
apps/store/src/features/retargeting/useQueryParams.ts
apps/store/src/features/retargeting/useRedirectUser.ts
apps/store/src/pages/session/resume.tsx

- Add `RedirectUser` component which can be conditionally rendered
- I want to handle not having shop session ID in a single place
- We could potentially do this also by throwing an error but that will leave some race conditions unaccounted for...
- Let me know what you think of this approach!

Retargeting: refactor redirect user composition

---

apps/store/src/features/retargeting/useApiRedirectEffect.ts
apps/store/src/pages/session/resume.tsx
apps/store/src/utils/PageLink.ts

- Create a custom hook to perform the API call on the retargeting page
- Make it more readable

Retargeting: refactor client side redirect to API route

---

apps/store/jest.config.mjs

- Update jest config to match Next.js recommended setup
- Reference: https://nextjs.org/docs/pages/building-your-application/optimizing/testing#jest-and-react-testing-library

Testing: update Jest config setup

---

apps/store/src/blocks/TrustpilotBlock.tsx

- Proper handle internal links

GEN-999  - fix(TrustpilotBlock): proper handle internal links

---

apps/store/src/components/CartPage/CartPage.constants.ts
apps/store/src/components/CartPage/CartPage.tsx

CheckoutPage: added option to load with all entries expanded
We're gonna use this addition in _Retargeting_ feature.

GEN-1002 - feat(CartPage): added option to load with all entries expanded

---

apps/store/src/features/retargeting/getUserRedirect.test.ts
apps/store/src/features/retargeting/getUserRedirect.ts
apps/store/src/features/retargeting/parseQueryParams.test.ts
apps/store/src/features/retargeting/parseQueryParams.ts
apps/store/src/pages/api/retargeting/[shopSessionId].ts

- Add tests for helper functions related to retargeting feature
- Refactor `parseQueryParams` into a helper function
- Make sure we test the logic of the helper functions

Retargeting: add tests for helper functions

---

apps/store/src/features/retargeting/useApiRedirectEffect.test.ts
apps/store/src/features/retargeting/useApiRedirectEffect.ts

- Refactor api redirect hook for retargeting feature
- Add test for the logic of the hook
- So we can ensure it works as expected

Retargeting: add test for api redirect hook

---

apps/store/src/features/retargeting/useApiRedirectEffect.ts
apps/store/src/pages/api/retargeting/[shopSessionId].ts

- Add additional log messages to be able to track retargeting feature
- Add some debug logs that can be useful during development
- Feature tracking in DD

GEN-994 | Retargeting: update logging to track the feature

---

apps/store/src/components/CartPage/PageDebugDialog.tsx
apps/store/src/utils/PageLink.ts

- Add a section to cart page debug tool to copy re-targeting link
- Make it easier to debug the feature

GEN-1056 | Retargeting: add debug section to copy link

---

apps/store/.eslintrc.js
apps/store/public/mockServiceWorker.js
apps/store/src/blocks/FooterBlock.tsx
apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
apps/store/src/utils/jsonSchema.ts

- Update postal address in footer + JSON schema
- Refactor address information to come from a single source of truth
- Update MSW helper file
- Exclude ".js" filed from ESLint
- We have moved!
- Need to exclude JS files from ESLint to avoid errors like this:
```text
Error: Error while loading rule '@typescript-eslint/no-unnecessary-condition': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

GEN-921 | Update postal address to Tulegatan

---

apps/store/README.md

- Add information about retargeting feature to the README.md file
- Provide brief feature documentation
- Should we co-locate this information to the feature/code as well? 🤔

Retargeting: add information about feature in README

---

apps/store/src/features/blog/BlogArticleListBlock.tsx

- Allow editors to customize how many posts are show in "Blog Article List" block
- Request from Peter to make the block more reusable

GEN-1048 | Blog Article List: allow custom visibility count from CMS

---

apps/store/src/features/blog/BlogArticleListBlock.tsx

[Screen Recording 2023-09-01 at 15.01.51.mov](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/8958f3cb-dfab-4b3d-92d2-7ed5e07fb4b7/Screen%20Recording%202023-09-01%20at%2015.01.51.mov)
- Disable scroll when clicking link to load all blog articles
- Better UX, request from Peter

GEN-1047 | Blog Article List: disable scrolling when showing all articles

---

apps/store/src/components/ProductItem/ProductItem.tsx
apps/store/src/components/QuickAdd/QuickAdd.stories.tsx
apps/store/src/components/QuickAdd/QuickAdd.tsx

- ~Update `QuickAdd` component styles to match design from cross-sell project~
- Add alternative/global `QuickAdd` component that matches styles from cross-sell project
- Add link to product page from new `QuickAdd` component
- Fix padding for `ProductItem` component (small screens)
- Needed for the cross-sell project

GEN-1057 | Update `QuickAdd` component styles

---

apps/store/public/locales/en/cart.json
apps/store/public/locales/sv-se/cart.json
apps/store/src/components/QuickAdd/QuickAdd.stories.tsx
apps/store/src/components/QuickAdd/QuickAdd.tsx
apps/store/src/components/QuickAdd/QuickAddCompleteContainer.tsx
apps/store/src/graphql/OfferRecommendationFragment.graphql

- Create a container component for Quick Add Complete component
- Represents a complete offer with a price and a button to add it to the cart
- Part of the cross-sell project
- The API is not 100% worked out but I explored what kind of information we want to expose to be able to support this use case.

GEN-1058 | Create `QuickAddComplete` container

---

apps/store/public/robots.txt

- Remove cart page from robots.txt
- Remove `/new-member` routes from robots.txt
- We already have meta-tags for the cart pages and Google doesn't like to see
pages in robots.txt that have meta-tags.
- We no longer have any routes that start with `/new-member` so we don't need to block them in robots.txt.
More information: https://hedviginsurance.slack.com/archives/D034QE3KB34/p1693931674677809

GEN-1087 | Remove cart from robots.txt

---

.github/renovate.json5

- Update Renovate to automerge dependency PRs before office hours
- So it doesn't conflict with our own work
- So we don't risk breaking things after we stop working

Renovate: automerge dependencies before office hours

---

apps/store/src/components/ProductItem/useGetStartDateProps.ts

- Display exposure in the `ProductItem` header (registration number)
- Make it easier to differentiate if you added more than one car in the cart

GEN-1083 | ProductItem: display exposure for car products

---

apps/store/src/blocks/CookieListBlock.tsx

Add cookie settings button in CookieListBlock
https://github.com/HedvigInsurance/racoon/assets/6661511/0359bf20-5369-4da3-a8d4-b3413e34f201
Compliance

Add cookie settings button in CookieListBlock

---

apps/store/src/blocks/FooterBlock.tsx
apps/store/src/services/storyblok/storyblok.ts

- Support custom attributes from Storyblok in FooterLink component
- Request from Peter to use for social links

GEN-1086 | FooterLink: support custom attributes from CMS

---

.github/renovate.json5

Update renovate config to preset (mornings)

---

apps/store/src/components/InputDate/InputStartDate.tsx
apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.tsx

- Create reusable `InputStartDate` component
- Include shared logic for start dates
- Will be used in the incomplete `QuickAdd` component

Create reusable `InputStartDate` component

---

apps/store/src/components/QuickAdd/DismissButton.tsx
apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx
apps/store/src/components/QuickAdd/useShowQuickAdd.ts

- `QuickAdd`: create reusable `DismissButton` component
- Will be used in incomplete quick add component

Create reusable `DismissButton`

---

apps/store/src/components/QuickAdd/QuickAddIncompleteContainer.tsx

- Add container to represent an incomplete quick add card!
- This is an exploration to understand what kind of data we need from the API to represent an incomplete quick add card. Therefore a lot of things are missing or contain placeholder data.
- Not yet in use.

GEN-1059 | Create `QuickAdd` component for incomplete quotes

---

apps/store/src/components/QuickAdd/QuickAddIncompleteContainer.tsx

- Add an input for number of co-insured in incomplete quick add component
- Allow users to edit this value (only meant to support home insurance)

GEN-1061 | QuickAdd: input for number of co-insured

---

apps/store/src/components/ProductItem/ProductItemContainer.tsx
apps/store/src/components/QuickAdd/QuickAdd.stories.tsx
apps/store/src/components/QuickAdd/QuickAdd.tsx
apps/store/src/components/QuickAdd/QuickAddCompleteContainer.tsx
apps/store/src/components/QuickAdd/QuickAddIncompleteContainer.tsx
apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx
apps/store/src/utils/getOfferPrice.ts

- Extract a utility function to calculate price (for `<Price>`) based on API product offer
- Avoid duplication of code, make it easier to read

Add utility for getting price from offer

---

apps/store/src/components/Pillow/Pillow.tsx
apps/store/src/features/retargeting/README.md
apps/store/src/features/retargeting/RetargetingPage.tsx
apps/store/src/features/retargeting/addOffersToCart.ts
apps/store/src/features/retargeting/fetchRetargetingData.ts
apps/store/src/features/retargeting/getUserRedirect.test.ts
apps/store/src/features/retargeting/getUserRedirect.ts
apps/store/src/features/retargeting/parseQueryParams.test.ts
apps/store/src/features/retargeting/parseQueryParams.ts
apps/store/src/features/retargeting/retargeting.types.ts
apps/store/src/features/retargeting/useApiRedirectEffect.test.ts
apps/store/src/features/retargeting/useApiRedirectEffect.ts
apps/store/src/pages/api/retargeting/[shopSessionId].ts
apps/store/src/utils/PageLink.ts

- Refactor re-targeting module files
- Add "priority" prop to Pillow component
- Add README file to introduce re-targeting
- Pass through unknown query params from original re-targeting link
- Just some cleanup before we go live
- We want to pass through query params that might be used in CRM for tracking purposes

GEN-1097 | Refactor re-targeting modules

---

apps/store/src/components/QuickAdd/AddToCartButton.tsx
apps/store/src/components/QuickAdd/QuickAdd.stories.tsx
apps/store/src/components/QuickAdd/QuickAddCompleteContainer.tsx
apps/store/src/components/QuickAdd/QuickAddIncompleteContainer.tsx
apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx

- Refactor `QuickAdd` components
- Add more logs and action tracking
- Comment where API data should come from
- Make it more production ready

GEN-1098 | Refactor `QuickAdd` components

---

apps/store/src/middleware.ts

- Redirect "default" locale by cookie preference OR use fallback (se)
- Apply to ALL routes (not just /)
- Remove geo redirect
- Let unknown locales render 404
- We noticed that we don't redirect `/cart` to `/se/cart`. This is better UX compared to just rendering 404.
- We don't need to support other markets so I removed the geo redirect
- I couldn't reproduce the issue where Next.js doesn't filter out API routes etc. so trying it out for all routes instead of just /.

GEN-1103 | Fix: correctly redirect 'default' locale

---

apps/store/src/middleware.ts

- Locale redirect: make it permanent if we perform default redirect
- Locale redirect: make it temporary if we perform user (cookie) redirect
- Match how it has been done in the past

Fix: make locale redirect permanent unless you have a cookie

---

apps/store/next-csp.config.js
apps/store/next.config.js
apps/store/src/blocks/BannerBlock.tsx
apps/store/src/blocks/ImageBlock.tsx
apps/store/src/blocks/ProductCardBlock.tsx
apps/store/src/blocks/TopPickCardBlock.tsx
apps/store/src/blocks/VideoBlock.tsx
apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
apps/store/src/components/ConfirmationPage/ImageSection.tsx
apps/store/src/components/DownloadableContentItem/DownloadableContentItem.tsx
apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
apps/store/src/components/Pillow/Pillow.tsx
apps/store/src/features/blog/BlogArticleListBlock.tsx
apps/store/src/features/blog/fetchArticleTeasers.ts

Use assets.hedvig.com as domain for assets, update according to this guide in CloudFront and Route 53 https://www.storyblok.com/docs/custom-assets-domain
- Use img src function to use Hedvig domain for images 
SEO and enable instant downloads of images

Update asset domain for images

---

apps/store/src/components/Video/Video.tsx

* Lazy load poster images for non autoplay videos.
A Lighthouse report raised an opportunity for improvement by delaying offscreen images:
Those are video poster images and currently there's no built in way to lazy load them (people are [working on it tho](https://github.com/whatwg/html/pull/8428)). Until the native solution is not available we can use a custom implementation for handling it.

GEN-1112 - perf(Video): implement a way of lazy load video posters

---

apps/store/src/components/DownloadableContentItem/DownloadableContentItem.tsx

To make download link work as expected

Use Hedvig domain for download link

---

apps/store/next.config.js

- Remove rewrites related to old Web Onboarding
- Bazooka clean-up

Remove Web Onboarding rewrites

---

apps/store/src/components/ConfirmationPage/ContractCard.tsx
apps/store/src/utils/date.ts

- Explicit logging of bank signering open action
- ~I can't find the action in DD, so I'm guessing the "data" attribute doesn't work as expected~
- Datadog doesn't automatically track clicks that lead to a new page being loaded (https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/?tab=npm#track-user-interactions)

GEN-1138 | BankSignering: fix logging opening link

---

apps/store/src/components/ProductItem/EditActionButton.tsx
apps/store/src/components/ProductItem/useEditProductOffer.ts

- Improve logging in edit product offer hook
- Show error modal if edit fails
- We got the error in prod but no way to really debug further

Edit offer: improve error logging + show error

---

apps/store/src/services/shopSession/ShopSession.helpers.ts

Log cookies when we are not able to find the current shop session (checkout).
This happens surprisingly often but not sure why so trying to collect more context around the issue.

Log context when shop session is not found

---

apps/store/src/components/Header/NavigationLink.tsx
packages/ui/src/components/Badge/Badge.helper.ts
packages/ui/src/components/Badge/Badge.stories.tsx
packages/ui/src/components/Badge/Badge.tsx

- Add new color option to the Badge
- Rename Badge sizes to "small" and "big"
- Match the design system in the Figma file

Badge: align props with Figma

---

apps/store/src/components/ProductItem/ProductItem.stories.tsx
apps/store/src/components/ProductItem/ProductItem.tsx

- Update `ProductItem` to optionally show a badge
- Support the new design for "active contract" product item

ProductItem: support displaying active contracts

---

apps/store/src/components/ProductItem/ProductItemContractContainer.tsx

- Create new product item container for displaying a Car contract
- This will be used for the car dealership offer page
- We need to expose more information about contracts in the API. Therefore I have added some fixture data pending the API changes.
- I didn't include the new translations since the design is still pending

GEN-1140 | ProductItemContractContainer: create draft for car contract

---

apps/store/next.config.js

- Enable experimental flag in next config: strict next head
- We have a problem with duplicated meta tags. This new setting seems to resolve it. However, can't find any other documentation on it.

Fix: remove duplicate meta tags

---

apps/store/next-csp.config.js

To enable CLoudFront distribution for the S3 origin

Add hedvig cdn to CSP

---

apps/store/src/components/ProductCard/ProductCard.tsx

Improve contrast and align with Figma

Improve text contrast in ProductCard

---

apps/store/src/components/InputSelect/InputSelect.tsx
apps/store/src/components/PriceCalculator/CarMileageField.tsx

- `InputSelect`: add support for custom background color
- Needed since we want to render input on gray background

InputSelect: Support custom background

---

apps/store/src/features/carDealership/ActionButtonsCar.tsx
apps/store/src/features/carDealership/RemoveCarOfferActionButton.tsx

chore: move RemoveCarOfferActionButton to carDealership feature folder

---

apps/store/src/components/ProductItem/ProductItemContractContainer.tsx
apps/store/src/features/carDealership/TrialExtensionBlock.tsx

- Implement draft of car trial extension block (car dealership)
- Narrow type in `ProductItemContractContainer`
- This is still a WIP, let's see if it makes sense to merge now

GEN-1143 | TrialExtensionBlock: draft implementation

---

apps/store/src/components/InfoCard/InfoCard.stories.tsx
apps/store/src/components/InfoCard/InfoCard.tsx
apps/store/src/features/manyPets/ManyPetsMigrationPage/LatestAdoptionNote.tsx
packages/ui/src/components/Text/Text.tsx

- Add new component: InfoCard + AttentionCard + ErrorCard
- Implement InfoCard instead of custom solution in `LatestAdoptionNote`
- This component will be used in car dealership project
- There are a bunch of other variations of this component but I suggest we add them when we need them
- I also skipped the "CampaignCard" because it's not used anywhere
- I skipped the special formatting inside `LatestAdoptionNote` since it doesn't really work with the design

GEN-1165 | InfoCard: new component 🎉

---

apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/ProductItem/ProductItem.tsx
apps/store/src/components/Skeleton.tsx
apps/store/src/features/carDealership/LoadingSkeleton.stories.tsx
apps/store/src/features/carDealership/LoadingSkeleton.tsx

- Add simple skeleton UI for showing loading state of car dealership offer
- Break out reusable skeleton UI component
- I kept it super simple for now instead of exactly matching the loaded UI

GEN-1169 | CarDealership: add loading skeleton UI

---

apps/store/src/blocks/TextBlock.tsx
apps/store/src/components/RichText/RichText.styles.tsx

- Fix margin for `p` elements added by rich text rendering.

fix(TextBlock): fix paragraphs margins

---

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx
apps/store/src/features/carDealership/TrialExtensionForm.stories.tsx
apps/store/src/features/carDealership/TrialExtensionForm.tsx
apps/store/src/features/carDealership/carDealershipFixtures.ts

- Car dealership: implement sign for new/existing members
Co-authored: @robinandeer

GEN-1177 - feat(TrialExtensionForm): sign new/existing members

---

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx
apps/store/src/features/carDealership/TrialExtensionForm.stories.tsx
apps/store/src/features/carDealership/TrialExtensionForm.tsx

- Implement signing flow for members that has payment connected
Car dealership feature.
Co-authored: @robinandeer

GEN-1180 - feat(TrialExtensionForm): added sining flow for members that don't required payment connection

---

apps/store/src/features/carDealership/TrialExtensionForm.tsx
apps/store/src/features/carDealership/useSignAndPay.ts

- Extract `useSignAndPay` into its own module
Easier to work with.
Co-authored: @robinandeer

GEN-1180 - refact(TrialExtensionForm): extract useSignAndPay into its own module

---

apps/store/src/features/carDealership/README.md
apps/store/src/pages/api/car-trials.ts

- Implement a way to test car dealership features
We'd be nice to be able to test the feature even before the API is fully finished.
Co-authored: @robinandeer

GEN-1187 - feat: implement a API route for car dealership testing purposes.

---

apps/store/src/features/carDealership/ProductItemContractContainer.tsx
apps/store/src/features/carDealership/README.md
apps/store/src/features/carDealership/carDealershipFixtures.ts
apps/store/src/pages/api/car-trials.ts

- Update fixtures to better match future queries
- Expose URL to the car dealership offer page in API route
- Easier to develop against

Car dealership: improve manual testing flow

---

apps/store/src/features/carDealership/carDealershipFixtures.ts

Car dealership: fix types in fixtures

---

apps/store/src/features/carDealership/useEditAndConfirm.tsx

- Car dealership: show error dialog with possible user error message when confirming price fails
- UX improvement

GEN-1196 | Car dealership: show dialog when confirming price fails

---

apps/store/src/features/carDealership/ActionButtonsCar.tsx
apps/store/src/features/carDealership/ActionStateEdit.tsx

- Use type of contract to determine which tier level is selected
- Pass default tier level from current offer
- We had a bug where the tier level value was based on the offer ID instead of the type of contract

GEN-1199 | Car dealership: fix selecting tier level in the form

---

apps/store/.storybook/main.ts
packages/ui/.storybook/main.ts

Colocate UI package and store storybook stories locally and in Chromatic
Make it easier to view all stories 🙏

Colocate stories from UI package with store Storybook

---

apps/store/.storybook/preview.tsx
apps/store/src/components/Accordion/Accordion.stories.tsx
apps/store/src/components/Banner/Banner.stories.tsx
apps/store/src/components/ComparisonTable/ComparisonTable.stories.tsx
apps/store/src/components/ComparisonTable/DesktopComparisonTable.stories.tsx
apps/store/src/components/ComparisonTable/MobileComparisonTable.stories.tsx
apps/store/src/components/ContactSupport/ContactSupport.stories.tsx

- Make sure design addon isn't displaying empty state
- Start adding Figma designs to stories

Make sure design addon isn't displaying empty state

---

apps/store/src/features/carDealership/useSignAndPay.ts

- Convert onSuccess to async function to prevent dialog from closing before navigation
- We don't want page to show before navigation is complete

GEN-1201 | Avoid closing BankID dialog before navigating

---

apps/store/src/components/InputSelect/InputSelect.tsx
apps/store/src/features/carDealership/ActionStateEdit.tsx

- Fix getting mileage from price intent data and use as default value for input
- Correctly handle custom default color in `InputSelect`
- Backend can return both number and string for mileage, so we need to handle both cases

GEN-1206 | Fix showing default mileage

---

apps/store/package.json
yarn.lock

fix(deps): update dependency downshift to v8.2.0

---

apps/store/package.json
yarn.lock

chore(deps): update dependency @datadog/datadog-ci to v2.20.0

---

apps/store/src/components/DownloadableContentItem/DownloadableContentItem.tsx

Add nofollow to downloadable links

---

apps/store/src/features/carDealership/useSignAndPay.ts
apps/store/src/services/bankId/useBankIdCheckoutSign.ts

- `useSignAndPay` - Show error dialog if somethings goes wrong while signing
Better UX

GEN-1200  - fix(useSignAndPay): show error dialog if something goes wrong while signing

---

apps/store/src/features/carDealership/TrialExtensionForm.tsx

- Display `TotalAmount` on car trial offer page
- Tweak the layout of the page (spacing)
- Updates from design

GEN-1213 | Display total amount on trial offer page

---

apps/store/src/features/carDealership/TrialExtensionForm.tsx

GEN-1211 | Update headings in the trial extension form

---

apps/store/src/services/apollo/client.ts

- Include version name when creating Apollo Client
- So we can differentiate stats from different versions/deployments of the app in Apollo Studio

Apollo Client: send version name to Apollo Studio

---

apps/store/src/components/ProductItem/ProductItem.stories.tsx
apps/store/src/components/ProductItem/ProductItem.tsx
apps/store/src/components/ProductItem/StartDate.tsx

- ProductItem: add option to show subtitle above accordion trigger
- Will be used in car dealership project

GEN-1215 | Add option to display subtitle in ProductItem

---

apps/store/src/features/carDealership/ProductItemContractContainer.tsx

- Use new `ProductItem.subtitle` for active contract card

GEN-1215 | Display exposure in car trial product item

---

apps/store/src/components/ProductItem/ProductItem.stories.tsx
apps/store/src/components/ProductItem/ProductItem.tsx
apps/store/src/features/carDealership/ProductItemContractContainer.tsx

- ProductItem: Remove unused "badge" option
- ProductItem: Add option to display icon in top right corner
- Integrate new icon option in car dealership contract card

GEN-1223 | ProductItem: add option to show icon in top right corner

---

apps/store/src/components/ToastBar/ToastBar.stories.tsx
apps/store/src/components/ToastBar/ToastBar.tsx

- Add new `ToastBar` component from design system
- It's very similar to the `InfoCard`, however, they are different in Figma so I feel like we should separate them in code as well.

GEN-1218 | Add new `ToastBar` component

---

apps/store/src/components/ToastBar/ToastBar.tsx
apps/store/src/features/carDealership/TrialExtensionForm.tsx

- Car dealership: replace `InfoCard` with `ToastBar`

GEN-1218 | Car dealership: replace InfoCard with ToastBar

---

packages/ui/src/components/Badge/Badge.stories.tsx

- Update storyformat to version 3
- Add Figma design

Update Badge story

---

apps/store/src/features/carDealership/TrialExtensionForm.tsx

- Added a sign disclaimer - as we already have for CheckoutPage and ManyPets offer page

GEN-1233 - feat(TrialExtensionForm): added a sign disclaimer

---

apps/store/src/pages/api/redirect/appstore.ts

- When redirecting to app store, use iOS as fallback/default
- It hurts but it makes more sense then fallback to home page.
- Most members are on iOS

Use App Store as default redirect

---

apps/store/src/components/TextWithLink.tsx

- Expose new `WithLink` component that doesn't wrap children inside a `Text` component

Add `WithLink` component (without `Text`)

---

apps/store/src/features/carDealership/TrialExtensionForm.tsx
apps/store/src/utils/PageLink.ts

Add appstore redirect URL to PageLink utility

---

apps/store/src/components/SpaceFlex/SpaceFlex.tsx
apps/store/src/features/carDealership/RemoveCarOfferActionButton.tsx
apps/store/src/features/carDealership/TrialExtensionForm.tsx

* Updated design for "decline extension" warning dialog

GEN-1238 - styles(RemoveCarOfferActionButton): updated design

---

apps/store/README.md
apps/store/src/features/retargeting/README.md

Update store + retargeting READMEs

---

apps/store/src/components/InitiateCarCancellationPage/InitiateCarCancellationPage.tsx

Update conditional to match new GraphQL schema

---

apps/store/next-csp.config.js

- Add Clearbits partnership tracking
Request from Sonny

Add Clearbits partnership tracking

---

apps/store/src/pages/api/redirect/appstore.ts

Update fallback link for appstore redirect

---

apps/store/src/features/carDealership/TrialExtensionForm.tsx

- Car dealership: always show the same total amount component/info
- Updates from Figma

Car dealership: always show the same total amount

---

apps/store/next-csp.config.js

Add another Clearbits domain

---

apps/store/src/features/memberArea/LoginPage.tsx
apps/store/src/features/memberArea/MemberPage.tsx

Subj
- Can login from login page
- Can logout from member page
- Support ?next on login page client-side

Ugly but functional login and logout

---

apps/store/src/features/memberArea/LoginPage.tsx

Allow to pre-fill SSN from URL
Could be useful for generating links from Hope in member context

Accept ssn query param for login page as pre-filled default

---

apps/store/src/features/memberArea/MemberPage.tsx

Add basic, responsive layout and navigation to member page 
Based of first layout sketched https://excalidraw.com/#json=ItdKOGnTB88HbDOqObzz_,vqcGBFqoOC3yVPCOvzkSgA
https://github.com/HedvigInsurance/racoon/assets/6661511/dbf8d3e2-b30e-4dac-a5b3-7a80df305d5d

Add basic layout and navigation to member page

---

apps/store/src/features/memberArea/MemberAreaMemberInfo.graphql
apps/store/src/features/memberArea/MemberPage.tsx
apps/store/src/features/memberArea/PaymentsSection.tsx

Crude way to see payment connection status and open a payment connection link.  Definitely can use workflow improvements

Payment connection info and link

---

apps/store/src/features/memberArea/MemberPage.tsx

Add content wrapper

---

apps/store/graphql.config.yml
apps/store/src/features/memberArea/Insurances.tsx
apps/store/src/features/memberArea/MemberAreaMemberInfo.graphql
apps/store/src/features/memberArea/MemberPage.tsx
apps/store/src/features/memberArea/components/InsuranceCard.tsx

- Add Insurances screen (not connected to navigation yet)
- Add basic InsuranceCard (info is a bit wrong and we need pillow image to match current contract)

Add first iteration of Insurances screen and InsuranceCard component

---

apps/store/src/pages/member/index.tsx
apps/store/src/pages/member/login.tsx

Add translations to member area pages so we can show translated texts where we reuse elements

Add translation data to member area pages

---

apps/store/src/features/memberArea/MemberPage.tsx
apps/store/src/features/memberArea/components/Header.tsx
apps/store/src/features/memberArea/components/Menu.tsx

- Breakout menu and header component

Breakout menu and header components

---

apps/store/src/features/memberArea/MemberPage.tsx
apps/store/src/features/memberArea/components/LayoutWithMenu.tsx

Create Next layout for header and menu
Let's just create pages for all screens we want

Create next layout

---

apps/store/src/features/memberArea/LoginPage.tsx
apps/store/src/features/memberArea/components/Insurances.tsx
apps/store/src/features/memberArea/pages/InsurancePage.tsx
apps/store/src/pages/member/insurances.tsx

- Make `/insurances` the default route when you login
- Refactor `MemberPage` -> `InsurancePage`
next step create payment page and fix proper navigation between pages

Start creating routes for different pages we need

---

apps/store/src/features/memberArea/components/InsurancesSection.tsx
apps/store/src/features/memberArea/components/Menu.tsx
apps/store/src/features/memberArea/pages/InsurancePage.tsx
apps/store/src/features/memberArea/pages/PaymentsPage.tsx
apps/store/src/pages/member/payments.tsx

Feel free to refactor how we distribute the data, didn't touch it now @alebedev

Create payments page and refactor

---

apps/store/src/features/memberArea/pages/LoginPage.tsx
apps/store/src/pages/member/login.tsx

Add temp animal images to login screen
@gustaveen please pick your image for the second slot
Let's have some fun at demo

Seally animal images on login screen

---

apps/store/src/features/memberArea/pages/LoginPage.tsx
apps/store/src/features/memberArea/pages/protectedPageServerSideProps.ts
apps/store/src/pages/member/insurances.tsx
apps/store/src/pages/member/login.tsx
apps/store/src/pages/member/payments.tsx

Extract repeated code for getServerSideProps of protected pages
DRY

Extract protectedPageServerSideProps to make creating page routes easy

---

apps/store/src/features/memberArea/components/Header.tsx
apps/store/src/features/memberArea/components/InsuranceCard.tsx
apps/store/src/features/memberArea/components/InsurancesSection.tsx
apps/store/src/features/memberArea/components/LayoutWithMenu.tsx
apps/store/src/features/memberArea/components/Menu.tsx

Adjust layout and menu items

---

apps/store/src/features/memberArea/components/InsuranceCard.tsx
packages/ui/src/components/HedvigSymbol/HedvigSymbol.tsx
packages/ui/src/index.ts

Add Hedvig Symbol and add to InsuranceCard

---

apps/store/src/features/memberArea/InsuranceSection/InsuranceCard.tsx
apps/store/src/features/memberArea/InsuranceSection/InsuranceDetails.tsx
apps/store/src/features/memberArea/InsuranceSection/InsurancesSection.tsx

- Add InsuranceDetails component
- Make InsuranceCard clickable and open details view
Simple solution without router support. I started to make it a proper route at first but wasn't sure how to handle it properly so please see if you can improve it @alebedev 
https://github.com/HedvigInsurance/racoon/assets/6661511/899740db-3065-4699-be93-9c44c0fe672a

Add InsuranceDetails component

---

apps/store/src/features/memberArea/InsuranceSection/InsuranceCard.tsx

Add all pillow variants for insurances

---

apps/store/src/features/memberArea/MemberAreaMemberInfo.graphql
apps/store/src/features/memberArea/PaymentsSection/PaymentsSection.tsx

Payments section
- Add general payment info and payment FAQ link
- Show monthly total, old gross if there's a discount and a free period if any
- Make Trustly UI disappear when connection is complete

Payments section design

---

apps/store/next.config.js

Subj
It's nice to have shorted default route.  We'll probably have a separate page there later, so using temporary redirect

Redirect /member -> /member/insurances

---

apps/store/src/features/memberArea/ClaimSection.tsx
apps/store/src/features/memberArea/components/LayoutWithMenu.tsx
apps/store/src/features/memberArea/components/Menu.tsx
apps/store/src/features/memberArea/pages/ClaimPage.tsx
apps/store/src/pages/member/claim.tsx

https://github.com/HedvigInsurance/racoon/assets/6661511/d00733da-a2f1-46da-ac1f-a435cfa9defb

Add Claim page

---

apps/store/src/features/memberArea/pages/LoginPage.tsx

Layout pushed out login form on desktop so I made a side by side layout in desktop and stacked in mobile :)

Fix login page layout

---

apps/store/src/features/memberArea/InsuranceSection/InsuranceCard.tsx
apps/store/src/features/memberArea/InsuranceSection/InsurancesSection.tsx
apps/store/src/features/memberArea/components/Menu.tsx

Add link to FAQ and adjust layout of insurances

---

apps/store/src/features/memberArea/PaymentsSection/PaymentsSection.tsx

Tweak payments page

---

packages/eslint-config-custom/package.json
yarn.lock

Update dependency eslint-plugin-jest to v27.4.2

---

apps/store/package.json
yarn.lock

Update dependency tss-react to v4.9.2

---

packages/eslint-config-custom/package.json
yarn.lock

Update typescript-eslint monorepo to v6.7.4

---

apps/store/package.json
package.json
packages/ui/package.json
yarn.lock

Update dependency eslint to v8.51.0

---

apps/store/package.json
yarn.lock

Update dependency @datadog/datadog-ci to v2.22.0

---

packages/eslint-config-custom/package.json
yarn.lock

Update dependency eslint-plugin-testing-library to v6.0.2

---

apps/store/src/features/carDealership/TrialExtensionForm.stories.tsx

- Add Grid parameter to adjust width
- Add story for not connected payment

Update story for TrialExtensionForm

---

apps/store/public/locales/en/carDealership.json
apps/store/public/locales/sv-se/carDealership.json
apps/store/src/features/carDealership/TrialExtensionForm.tsx

- Add ToggleCard to toggle extension offer 
- Add translations
https://github.com/HedvigInsurance/racoon/assets/6661511/baf063fb-393c-45db-89fa-14d1eb604d19
Next step: add icon and adjust styling
Extension offer won't be displayed per default

GEN-1236 / Add toggle for car dealership extension

---

apps/store/src/features/memberArea/InsuranceSection/InsuranceDetailsSection.tsx
apps/store/src/features/memberArea/InsuranceSection/TravelCertificateButton.tsx

Remove demo link to get travel certificate
Not suitable for production yet, added implementing in production-ready form to our post-launch TODO list

Hide demo version of travel certificate request

---

apps/store/src/features/memberArea/pages/LoginPage.tsx

- Add video to login screen (same video used on apps login screen)

Add video to login screen

---

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx

- Factor out "render banner" logic in a hook.
Makes `CarTrialExtensionBlock` easier to understand/maintain.

GEN-1267 - refact(CarTrialExtensionBlock): factor out "render banner"

---

apps/store/src/features/carDealership/EditActionButton.tsx
apps/store/src/features/carDealership/EditExtensionOfferForm.tsx
apps/store/src/features/carDealership/TrialExtensionForm.tsx

- Rename `ActionButtonsCar` --> `EditActionButton`
- Rename `ActionStateEdit` --> `EditExtensionOfferForm`
Makers easier to understand the in code, the represented UI

GEN-1268 - refact(TrialExtensionForm): be clear about the single action possible: edit

---

apps/store/src/components/ToggleCard/ToggleCard.tsx
apps/store/src/features/carDealership/TrialExtensionForm.tsx

- Add option to show icon inside toggle card
- Tweak padding to match design
- Used in car dealership feature

GEN-1272 | Update ToggleCard design

---

apps/store/src/features/carDealership/TrialExtensionForm.tsx
apps/store/src/features/carDealership/useAcceptExtension.ts

- Rename hook "useSignAndPay" to "useAcceptExtension"
- Better reflect what is actually going on in the hook

GEN-1270 | Update hook "useAcceptExtension"

---

.gitignore
.vscode/racoon.code-workspace
README.md

Update README with installations steps for VS Code SDK
Holler if you think there's a better way to set this up :) 
Needed to make VS Code work with Yarn PnP

Update README with installations steps for VS Code SDK

---

apps/store/public/locales/en/memberArea.json
apps/store/public/locales/sv-se/memberArea.json
apps/store/src/@types/i18next.d.ts
apps/store/src/features/memberArea/components/Menu.tsx

Add translation file to memberArea

---

.github/renovate.json5

Ignore webpack in auto-updates and comment why

---

.vscode/extensions.json
.vscode/racoon.code-workspace

- Update prettier path in VSCode workspace
- Add additional VSCode extension recommendation
- Prettier path didn't work for me. Please check if it works for you.

Make Prettier work inside VSCode workspace

---

apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/SwitchingAssistantSection.stories.tsx
apps/store/src/components/ConfirmationPage/useSwitchingContracts.ts
apps/store/src/features/carDealership/ProductItemContractContainer.tsx
apps/store/src/graphql/SwitchingContractFragment.graphql

See title.
- `Contract.variant` is deprecated and will be removed in the future.

Migrate from `Contract.variant` to `Contract.currentAgreement.productVariant`

---

apps/store/public/locales/en/carDealership.json
apps/store/public/locales/sv-se/carDealership.json
apps/store/src/components/ProductItem/ProductItem.stories.tsx
apps/store/src/components/ProductItem/ProductItem.tsx
apps/store/src/components/ToggleCard/ToggleCard.tsx
apps/store/src/features/carDealership/ProductItemContractContainer.tsx
packages/ui/src/components/Badge/Badge.tsx

- Update design of contract card on car dealership offer page
- Add option to display badge in `ProductItem` component
- Remove option to display icon in `ProductItem` component (no longer needed)
- Fix border radius of toggle card component
- Figma updates
- I'm a little bothered that `ProductItem` keeps growing in complexity with a bunch of props. However there's also a lot of logic in there that I don't want to repeat.

GEN-1282 | Update trial contract card design

---

apps/store/package.json

Subj, hopefully we can save time on running link during Vercel build - we're doing it on github anyway

Skip lint during Vercel build

---

apps/store/src/components/PaymentConnectPage/IdleState.tsx

Small refactor of Payment Connect page to log warnings instead of errors
These are not client errors so we should only log warnings since we handle them gracefully

Payment Link: convert error -> warning logs

---

apps/store/src/features/memberArea/components/Menu.tsx
apps/store/src/utils/PageLink.ts

- Localize FAQ link so Swedish variant in Member area nav does not lead to 404
- Move member area links to PageLink to keep them central

Localize member area FAQ link, move other links to PageLink

---

apps/store/public/locales/en/memberArea.json
apps/store/public/locales/sv-se/memberArea.json
apps/store/src/features/memberArea/PaymentsSection/PaymentsSection.tsx

Add Lokalise to payments page

---

apps/store/src/components/PaymentConnectPage/ErrorDialog.tsx
apps/store/src/pages/payment/connect.tsx
apps/store/src/pages/payment/connect/ready.tsx
apps/store/src/pages/payment/connect/start.tsx
apps/store/src/pages/payment/connect/success.tsx
apps/store/src/services/trustly/TrustlyIframe.tsx
apps/store/src/utils/PageLink.ts

- Refactor Payment Link feature
- Create unique endpoints for the different steps (start, ready, success)
- Create Trustly URL server-side
- Allow fallback to login if authorization code has expired
- Make the feature more robust so members can retry and login themselves instead of having to wait for IEX to send them a new link.
- I left the old implementation in place so we can test this new one in parallel.

GEN-1302 | Refactor Payment Link flow

---

.prettierignore
apps/store/package.json
apps/store/src/blocks/ProductAverageRatingBlock.tsx
apps/store/src/components/ProductPage/ProductPage.types.ts
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.stories.tsx
apps/store/src/pages/[[...slug]].tsx
apps/store/src/services/averageRating/averageRating.ts
apps/store/src/services/storyblok/storyblok.ts
yarn.lock

GEN-1277 - feat: added AverageRatingBlock

---

apps/store/src/pages/payment/connect/start.tsx

- Stop using authorization code in Payment Link flow
- It has been identified as a security risk
- FYI: This doesn't affect the currently used implementation

Payment Link: remove magic authorization code flow

---

apps/store/src/components/CartNotification/CartToast.tsx
apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/Header/ShoppingCartMenuItem.tsx

GEN-1296 | Let Next.js fill in missing locale for cart links

---

apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
apps/store/src/utils/PageLink.ts

- Let nextjs handle locale for checkout links
- Extend URL class with `toRelative` method
- Make it easy to get the relative URL without origin

GEN-1296 | Let Next.js fill in missing locale for checkout links

---

apps/store/src/features/carDealership/useAcceptExtension.ts
apps/store/src/features/memberArea/components/Menu.tsx

GEN-1296 | Let Next.js fill in missing locale for confirmation + member area links

---

apps/store/src/pages/new-sitemap-pending.xml.js

Refactor sitemap generation
Since the `link` endpoint unfortunately don't support the [filter queries](https://www.storyblok.com/docs/api/content-delivery/v2#filter-queries/overview) or contain story information, we need to use the `stories` endpoint.
So what we filter on is excluding all stories with `robots: noindex`
Only concern is if we would hit the API rate limit
We need to exclude `noindex` pages from the sitemap

Make sure sitemap exludes pages with noindex

---

apps/store/next.config.js

- Remove old web-onboarding redirects
- Add generic redirects for the few remaining deep-links but just to home page
- Checked with Peter

Clean up old web-onboarding redirects

---

apps/store/src/pages/new-sitemap-pending.xml.js

Set cache version to avoid rate limit on requests
Does this look valid to you? :)

Set cache version on sitemap request

---

apps/store/next.config.js

- Unless `FEATURE_OLD_SITE_REDIRECTS`, redirect all NO/DK URLs to home page
- Exclude home page and customer service pages from redirects
- So we can shut down the old site

GEN-1274 | Optionally enable generic NO/DK redirects

---

.github/renovate.json5

Replace renovate's stabilityDays with minimunReleaseAge

---

apps/store/src/components/ContactUs/ContactUsButton.tsx
apps/store/src/components/ContactUs/Content.tsx
packages/ui/src/components/Button/Button.stories.tsx
packages/ui/src/components/Button/Button.tsx

- Button now accepts an icon that's rendered on the left. I use that for the buttons implemented by _ContactUs_ component.

GEN-1301 - refact(Button): accept icon

---

.yarnrc.yml
apps/store/vercel.json

Move yarn cache outside node_modules, see https://github.com/vercel/turbo/issues/785

Try moving yarn cache to ./.next/cache/yarn-cache when building on Vercel

---

apps/store/src/features/retargeting/ShopSessionRetargeting.graphql
apps/store/src/features/retargeting/getUserRedirect.test.ts
apps/store/src/features/retargeting/getUserRedirect.ts

Rely on storefront logic to pick up default offer
Consistency with CRM

Use priceIntent.defaultOffer to replace client-side logic

---

apps/store/src/features/retargeting/getUserRedirect.test.ts

Style changes for getUserRedirect.test
- Remove top-level describe, file name is enough
- it -> test
Code style consistency

Update test definition style in getUserRedirect.test to match the rest of the project

---

apps/store/next-csp.config.js

Add additional domain for clearbits

---

apps/store/src/pages/sitemap.xml.js

Remove trailing slash from sitemap urls

Remove trailing slash for folder URLs

---

apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
apps/store/src/graphql/CartFragment.graphql
apps/store/src/utils/useDiscountExplanation.ts

Fix type errors after schema changes, added note about CampaignDiscountType.VisibleNoDiscount

---

apps/store/next.config.js

Hard to see on the diff....
- Remove feature flag `FEATURE_OLD_SITE_REDIRECTS`
- Remove `shutDownMarketsInfo`, it will be handled by `noDkRedirects`
- Put back `oldSiteRedirects` to redirect any `/new-member` URL to root
Shut down market-web

Re-enable oldSiteRedirects and remove feature flag

---

apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
apps/store/src/pages/sitemap.xml.js
apps/store/src/services/storyblok/Storyblok.helpers.ts

Remove trailling slashes for all Storyblok URLs since it causes redirects

---

apps/store/src/components/Header/NavigationLink.tsx

😆 that was what you tried to point out @robinandeer and I didn't catch yesterday haha

Switcheded to regular link by mistake, revert

---

apps/store/next-csp.config.js

Remove market-web specific CSP rules

---

apps/store/next-csp.config.js

Accidental removal, we use it in Trustpilot block

Put back CSP rules for Trustpilot widget since it's being used

---

apps/store/src/blocks/WidgetFlowBlock.tsx
apps/store/src/features/widget/widget.constants.ts
apps/store/src/pages/sitemap.xml.js
apps/store/src/pages/widget/[[...slug]].tsx
apps/store/src/services/storyblok/Storyblok.helpers.ts
apps/store/src/services/storyblok/storyblok.ts

* Added a `widget-flow` Content type so editors can configure some aspects of a widget flow.

GEN-1384 - feat: added widgetFlow content type

---

apps/store/next-csp.config.js

Fix CSP for Linkedin

---

apps/store/src/components/ProductPage/PriceIntentContext.tsx
apps/store/src/features/carDealership/PriceIntentDataUpdateCar.graphql
apps/store/src/graphql/ExternalInsurerUpdate.graphql
apps/store/src/graphql/PriceIntent.graphql
apps/store/src/graphql/PriceIntentConfirm.graphql
apps/store/src/graphql/PriceIntentCreate.graphql
apps/store/src/graphql/PriceIntentDataUpdate.graphql
apps/store/src/graphql/PriceIntentFragment.graphql
apps/store/src/graphql/PriceIntentInsurelyUpdate.graphql

"Fragemnt" gets duplicated when importing type

Rename Fragment to match other fragment names

---

apps/store/public/locales/en/purchase-form.json
apps/store/public/locales/sv-se/purchase-form.json
apps/store/src/services/PriceCalculator/PriceCalculator.helpers.ts
apps/store/src/services/PriceCalculator/data/SE_WIDGET_APARTMENT_BRF.ts
apps/store/src/services/PriceCalculator/formFragments.ts

Add new template for Widget + Apartment BRF product
Allow selecting weather you are a student in the form

GEN-1390 | Add new price template for Widget Apartment BRF

---

apps/store/src/services/PriceCalculator/PriceCalculator.helpers.ts
apps/store/src/services/PriceCalculator/data/SE_APARTMENT_RENT.ts
apps/store/src/services/PriceCalculator/data/SE_WIDGET_APARTMENT.ts
apps/store/src/services/PriceCalculator/data/SE_WIDGET_APARTMENT_BRF.ts
apps/store/src/services/PriceCalculator/formFragments.ts

- Use one price form template for widget apartment (RENT/BRF)
- Inline apartment + student section
- I realized there will be no differences in the form between BRF and RENT so why not use one template for both

GEN-1390 | Refactor widget apartment price template

---

apps/store/src/features/widget/SelectProductPage.tsx
apps/store/src/pages/widget/[flow]/[shopSessionId]/select.tsx

- Integrate product metadata from API into the widget select product page
- Fetch and hydrate product metadata from API
- Next step will be to filter the products based on the CMS configuration

GEN-1385 | Widget select product - integrate product metadata

---

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx
apps/store/src/features/carDealership/PayForTrial.tsx

Add PriceBreakdown to PayForTrial component

Add PriceBreakdown to PayForTrial component

---

apps/store/src/features/carDealership/PayForTrial.tsx
apps/store/src/features/carDealership/ProductItemContractContainer.tsx
apps/store/src/features/carDealership/TrialContractFragment.graphql
apps/store/src/features/carDealership/TrialExtensionForm.tsx

Update due car dealership [API schema changes](https://hedviginsurance.slack.com/archives/C0481RNNR8V/p1699521301552909).

fix(carDealership): update due API schema changes

---

apps/store/src/components/ProductPage/ProductPageContext.tsx

See title
Just ran through it while checking other stuff.

chore(ProductPageProps): remove redundant code

---

apps/store/src/features/memberArea/InsuranceSection/InsuranceDetailsSection.tsx
apps/store/src/features/memberArea/pages/LoginPage.tsx
apps/store/src/utils/singleQueryParam.ts

Support specifying default section in insurance details via URL
Part of Car Trial CRM flow, generally useful for link thab brings user close to insurance certificate

[CAR-29] Support specifying default open tab via ?section=overview|coverage|documents in member insurance details

---

apps/store/src/features/carDealership/PayForTrial.tsx
apps/store/src/features/carDealership/ProductItemContractContainer.tsx
apps/store/src/features/carDealership/TrialExtensionForm.tsx

Show reduced price for trial ProductItem
Show same discount as in PriceBreakdown

Show reduced price in ProductItemContractContainer

---

apps/store/src/components/CheckoutPaymentTrustlyPage/CheckoutPaymentTrustlyPage constants.ts
apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx
apps/store/src/features/carDealership/PayForTrial.tsx
apps/store/src/features/carDealership/TrialExtensionForm.tsx
apps/store/src/features/carDealership/useAcceptExtension.ts
apps/store/src/pages/checkout/[shopSessionId]/payment/trustly.tsx
apps/store/src/utils/PageLink.ts

Wire confirmation pages up for car dealership:
- With extension flow --> with extension confirmation page
- Without extension flow --> without extension confirmation page

GEN-1413 - refact(carDealership): wire confirmation pages up

---

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx

Use heading from CMS instead to be able to differ between pages

Remove heading and add it in the CMS since it differs between pages

---

apps/store/src/features/widget/CalculatePricePage.tsx
apps/store/src/features/widget/WidgetPriceIntent.graphql
apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx

Adds the foundation for the addition of Widget Calculate Price page. 
Part of Widget feature. Observe that rendering PriceCalculator outside PDP is a trick task which will be tackled on subsequent PRs.

GEN-1386 - feat(widget): added foundation for CalculatePricePage

---

apps/store/src/components/PriceCalculator/PriceCalculator.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx

- See title.
- Remove dependency on `PriceCalculator` to be rendered on the PDP

GEN-1440 | Pass price template as prop to `PriceCalculator`

---

apps/store/src/components/PriceCalculator/PriceCalculator.tsx
apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts

- Forward Shop Session from prop in `useHandleSubmitPriceCalculator` hook
- Make it possible to call price calculator from outside PDP

GEN-1443 | Use Shop Session from prop in `useHandleSubmitPriceCalculator`

---

apps/store/src/components/PriceCalculator/PriceCalculator.tsx
apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts

- See title
- Make price calculator reusable outside the PDP

GEN-1445 | Use Price Intent from props in `useHandleSubmitPriceCalculator`

---

apps/store/src/features/widget/SelectProductPage.tsx
apps/store/src/features/widget/widget.helpers.ts
apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx
apps/store/src/utils/PageLink.ts

- Allow any price template / product in Widget flow
- This will make things much easier to develop and test
- We can consider reintroducing the check later and maybe log a warning to DD

Accept any price template in widget flow

---

apps/store/src/features/widget/CalculatePricePage.tsx
apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx

- Integrate price calculator into the Widget flow 🙌🏻
- Pass down SS/PI from Next page that subscribes to updates from the API
- Progress!

GEN-1446 | Integrate Price Calculator in Widget flow

---

apps/store/src/features/widget/CalculatePricePage.tsx
apps/store/src/graphql/PriceIntentConfirm.graphql
apps/store/src/utils/PageLink.ts

- After completing price calculator; confirm price intent + add default offer to cart
- Then navigate to the sign page in the flow
- Progress!
- I skipped all the tracking for now -- let's discuss how we want to handle that

GEN-1447 | Confirm price intent + add to cart in Widget

---

apps/store/src/features/widget/SignPage.tsx
apps/store/src/pages/widget/[flow]/[shopSessionId]/sign.tsx

- Added Widget Checkout page
Foundation for Widget Checkout page. Other aspects of it like localisation and rendering CMS content will be addressed on subsequent PRs.

GEN-1397 - feat(widget): added checkout page

---

apps/store/public/locales/en/carDealership.json
apps/store/public/locales/sv-se/carDealership.json
apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx

- Update days until cancelation
- Translations for banner was mixed up, update it

Update days until we cancel unpaid trial and update translations

---

apps/store/src/components/PriceLoader.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx

- Extract `PriceLoader` from `PurchaseForm`
- We want to use it in the Widget

Make `PriceLoader` a reusable component

---

apps/store/src/utils/useAddToCart.ts

- Expose callback for when adding to cart fails
- We want to use this in the Widget

Expose `useAddToCart.onError` callback

---

apps/store/src/features/widget/CalculatePricePage.tsx

- Display the price loader as the price is loading
- Make sure we hide the loader if anything fails along the way
- Implement more of the Figma design

GEN-1448 | Display price loader in Widget flow

---

apps/store/public/locales/en/checkout.json
apps/store/public/locales/sv-se/checkout.json
apps/store/src/features/widget/SignPage.tsx

- Added translation keys for Widget Checkout Page

GEN-1397 - feat(widget-checkout): added localisation

---

apps/store/src/features/widget/SignPage.tsx
apps/store/src/pages/widget/[flow]/[shopSessionId]/sign.tsx
apps/store/src/utils/PageLink.ts

- Redirect to payment page after checking out

GEN-1397 - feat(widget-checkout): redirect to payment page after checkout

---

apps/store/src/components/ProductItem/useGetStartDateProps.ts

Use full date format according to updated design

Use full date format according to updated design

---

apps/store/src/features/carDealership/PayForTrial.tsx
apps/store/src/features/carDealership/useAcceptExtension.ts

fix(car-dealership): redirect accordantly

---

apps/store/public/locales/en/checkout.json
apps/store/public/locales/sv-se/checkout.json
apps/store/src/features/widget/Header.tsx

- Show check icon next to completed steps in the widget progress bar
- Figma design

GEN-1463 | Check-off completed widget steps

---

apps/store/src/features/widget/ConfirmationPage.tsx
apps/store/src/pages/widget/[flow]/[shopSessionId]/confirmation.tsx

- Create basic version of the confirmation page for the widget flow
- I skipped the CMS content for another PR

GEN-1395 | Create basic Widget Confirmation page

---

apps/store/src/utils/PageLink.ts

Fix bug in widget sign URL

---

apps/store/src/components/ConfirmationPage/fetchConfirmationStory.ts
apps/store/src/pages/confirmation/[shopSessionId].tsx

- Create a function to fetch the confirmation story from Storyblok
- We need to fetch it on the widget confirmation route

Extract function to fetch confirmation story

---

apps/store/public/locales/en/checkout.json
apps/store/public/locales/en/widget.json
apps/store/public/locales/sv-se/checkout.json
apps/store/public/locales/sv-se/widget.json
apps/store/src/@types/i18next.d.ts
apps/store/src/features/widget/Header.tsx
apps/store/src/features/widget/PaymentPage.tsx
apps/store/src/features/widget/SignPage.tsx

- Create separate namespace for widget translations
- Makes sense that every feature has a separate namespace for translations

GEN-1465 | Create Widget translation namespace

---

apps/store/src/features/widget/CalculatePricePage.tsx
apps/store/src/features/widget/ConfirmationPage.tsx
apps/store/src/features/widget/PaymentPage.tsx
apps/store/src/features/widget/SelectProductPage.tsx
apps/store/src/features/widget/SignPage.tsx

- Add padding to bottom of pages in Widget flow
- Needed to be able to scroll past the bottom of the page
- I duplicated the code to avoid coming up with a layout abstraction for something so simple

Widget | Add bottom padding to pages

---

apps/store/public/mockServiceWorker.js
apps/store/src/blocks/ImageBlock.tsx
apps/store/src/components/ConfirmationPage/ImageSection.tsx
apps/store/src/components/ImageWithPlaceholder/ImageWithPlaceholder.tsx
packages/ui/src/index.ts
packages/ui/src/lib/theme/theme.ts

Use non-default quality to bust Vercel image cache

Change default image quality on Vercel 75 -> 74 to flush image cache

---

packages/ui/src/lib/theme/theme.ts

Change default quality to 73 to flush images that got stuck on 74 quality

---

apps/store/src/features/widget/README.md

First draft of technical documentation of the Widget

---

apps/store/src/features/widget/widget.helpers.ts

- Use existing products in widget flow but different price template
- The existing products now support student question so we can reuse them

GEN-1471 | Use regular products in widget

---

apps/store/src/features/widget/parseSearchParams.ts
apps/store/src/features/widget/usePublishWidgetInitEvent.ts
apps/store/src/features/widget/widget.constants.ts
apps/store/src/pages/widget/flows/[...slug].tsx

- Parse URL and extract optional `shopSessionCreatePartner` params
- We currently don't accept "external member ID" but the plan is to do so in the future

GEN-1462 | Parse optional shop session create partner params from URL

---

apps/store/src/features/widget/StartFlow.helpers.ts
apps/store/src/pages/widget/flows/[...slug].tsx

This refactoring breaks down the large function into smaller, more manageable functions, each with a single responsibility.
It makes the code easier to understand and maintain.

Refactor Widget flow start route

---

apps/store/src/services/PriceCalculator/formFragments.ts

Widget | Add default value to student field

---

apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
apps/store/src/utils/useAddToCart.ts

- pass in offer ID to replace before adding item to cart
- make it more explicit what offer is being replaced
- make it possible to use this feature in other places than the product page. The previous solution assumed that we were using the global shop session.

Pass in offer id to replace when adding to cart

---

apps/store/src/features/widget/CalculatePricePage.tsx
apps/store/src/features/widget/SignPage.tsx

- add edit button for the offer added to cart in the widget flow
- according to figma design

GEN-1480 | Add link to edit offer from Widget sign page

---

apps/store/public/locales/en/carDealership.json
apps/store/public/locales/sv-se/carDealership.json
apps/store/src/components/ProductItem/StartDate.tsx
apps/store/src/features/carDealership/ProductItemContractContainer.tsx

- Remove tooltip for Trial Product Item

CAR-42 - styles(carDealership): remove tooltip from ProductItemContractContainer

---

apps/store/src/components/Switch.tsx
apps/store/src/components/ToggleCard/ToggleCard.tsx

- `ToggleCard`: change background to green when checked

CAR-42 - styles(ToggleCard): green background when checked

---

apps/store/src/components/Banner/Banner.tsx

- `Banner`: align icon at top on mobile

styles(Banner): align icon at top

---

apps/store/src/components/InputDate/InputDate.tsx

- Add a light colored variant of `InputDate` component
- Needed for widget feature

Add support for light colored date input

---

apps/store/public/locales/en/widget.json
apps/store/public/locales/sv-se/widget.json
apps/store/src/features/widget/SelectProductPage.tsx

Translate labels on Widget Select Page

---

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx

CAR-42 - fix(carDealership): change days until termination to 14 days

---

apps/store/src/components/ComparisonTable/ComparisonTable.tsx

- ComparisonTable: update border color to match design

CAR-42 - styles(ComparisonTable): update border color to match design

---

apps/store/src/features/carDealership/TrialExtensionForm.tsx

- `TrialExtensionForm`: changed spacing between `PriceBreakdown` items and sign button

CAR-42 - styles(TrialExtensionForm): change spacing between price breakdown and sing button

---

apps/store/src/blocks/InsurableLimitsBlock.tsx
apps/store/src/blocks/PerilsBlock.tsx
apps/store/src/blocks/ProductAverageRatingBlock.tsx
apps/store/src/blocks/ProductDocumentsBlock.tsx
apps/store/src/components/ProductData/ProductDataProvider.tsx
apps/store/src/components/ProductPage/ProductPage.tsx
apps/store/src/components/ProductPage/ProductPage.types.ts
apps/store/src/components/ProductPage/ProductPageContext.tsx
apps/store/src/components/ProductVariantSelector/ProductVariantSelector.tsx
apps/store/src/pages/[[...slug]].tsx

- Add a jotai hook/atom for managing selected product variant
- Replace solution from product page context
- We want to use it outside of the product page

Add separate atom for selected product variant

---

apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx
apps/store/src/pages/widget/preview/[[...slug]].tsx

- Add the product data context to widget pages (sign + preview)
- This allows us to use CMS blocks that depend on this context inside the widget!

Add product data context to Widget pages

---

apps/store/src/features/widget/CalculatePricePage.tsx
apps/store/src/features/widget/ConfirmationPage.tsx
apps/store/src/features/widget/SelectProductPage.tsx
apps/store/src/features/widget/SignPage.tsx
apps/store/src/features/widget/StartFlow.helpers.ts
apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx
apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx
apps/store/src/pages/widget/[flow]/[shopSessionId]/payment.tsx
apps/store/src/pages/widget/[flow]/[shopSessionId]/select.tsx
apps/store/src/pages/widget/flows/[...slug].tsx

- Add datadog logging for the widget flow
- So we can setup dashboard and debug the flow

GEN-1494 | Add logging to Widget flow

---

apps/store/src/features/widget/SignPage.tsx

- Skip payment step in widget flow for members with an active payment connection
- These users should not be asked to pay again
- I wanted to do it on the sign page so we can always go directly to the payment page even if the user has a payment connection

GEN-1495 | Skip payment step for members with active connection

---

apps/store/src/features/widget/README.md

Widget | Update testing docs

---

apps/store/public/locales/en/widget.json
apps/store/public/locales/sv-se/widget.json
apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx

- Add page title to the calculate price page (widget)
- Production readiness preparation

Widget | Add page title for calculate price page

---

apps/store/src/pages/widget/[flow]/[shopSessionId]/select.tsx

- Add page title to select product page (widget)
- Production readiness

Widget | Add page title for select page

---

apps/store/src/features/widget/SelectProductPage.tsx
apps/store/src/services/Tracking/Tracking.ts

- Report "select_item" tracking event when a user selects a product in the widget
- Expose a more generic tracking method for "selectItem" events
- Widget tracking needs

Widget | Report 'select_item' event after selecting product

---

apps/store/next.config.js

See title
Request from Peter. We have quite a few backlinks so it would be better to point it to the insurance page instead.

Update new-member redirect to insurance page

---

apps/store/src/features/widget/SignPage.tsx

- See title.
- Widget tracking

Widget | Report 'delete_from_cart' when removing cart item

---

apps/store/src/features/widget/StartFlow.helpers.ts

- Set "initiatedFrom" to "WIDGET" when creating new shop sessions
- Based on Slack discussion here: https://hedviginsurance.slack.com/archives/C9K7XRQ0G/p1701100699061039

GEN-1509 | Initiate shop session from WIDGET

---

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
apps/store/src/services/Tracking/Tracking.ts
apps/store/src/services/Tracking/TrackingContext.tsx

- Derive customer data for tracking context based on shop session in provider
- Now customer data is always up-to-date and can be overwritten

Derive customer tracking data from context

---

apps/store/src/components/ProductPage/PriceIntentContext.tsx
apps/store/src/components/ProductPage/ProductPage.tsx
apps/store/src/services/Tracking/Tracking.ts
apps/store/src/services/Tracking/TrackingContext.tsx

- Pass in product data to tracking provider
- Derive tracking context data from product data
- Always up-to-date and able to override

Derive tracking product data from context

---

apps/store/src/pages/_app.tsx
apps/store/src/services/Tracking/Tracking.ts
apps/store/src/services/Tracking/TrackingContext.tsx
apps/store/src/services/gtm.tsx

- Pass in country code from hook to tracking provider
- I think this is one of the truly global concepts in the app, so it makes sense to pick it up directly inside the provider. No need to override country code.

Derive tracking country from context

---

apps/store/src/services/Tracking/Tracking.ts
apps/store/src/services/Tracking/TrackingContext.tsx

- Refactor tracking context to specify the types explicitly
- This makes it easier to use the values from the context without having to cast them to the correct type. It's also more type safe.

Add strict types to tracking context

---

apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx
apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx
apps/store/src/pages/widget/[flow]/[shopSessionId]/select.tsx

- Add tracking providers for select, calculate price, and sign widget pages
- Makes sure that we are using the correct information for tracking

Add tracking providers to widget pages

---

apps/store/src/services/Tracking/Tracking.ts

- Add factory function to generate the shop session tracking property
- Avoid duplication and make it eaiser to extend the object with additional properties

Add factory function for tracking shop session

---

apps/store/src/components/Tooltip/Tooltip.tsx

- Open Tooltip on click
- Fix issue on mobile where the tooltip would not open when tapping on the icon
- Reference: https://github.com/radix-ui/primitives/issues/955#issuecomment-1698976935

GEN-1515 | Fix tooltip on mobile

---

apps/store/src/components/QuickAdd/QuickAdd.tsx

- Decrease spacing under header
- Align price in row on smaller viewports

GEN-1517 Widget UI Fix - Offer page

---

apps/store/src/components/Ticker/Ticker.stories.tsx
apps/store/src/components/Ticker/Ticker.tsx

<a href="https://app.graphite.dev/media/video/OgXegTwxM9IeuXHZyw5h/ac7adf2f-ddfd-4e75-a49a-9c34645f8f0e.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/ac7adf2f-ddfd-4e75-a49a-9c34645f8f0e.mov">Screen Recording 2023-11-30 at 11.19.56.mov</video> 
- Add basic ticker component
- Will be used as a CMS block as well as in the widget flows
- We might need to customize the icon in the future but for now I think it is enough

GEN-1511 | Add basic Ticker component

---

apps/store/src/pages/car-buyer/validation/[dealerId].tsx

- Check if username + password are provided as any string
- Allow empty password for car trial validation page

Allow empty password

---

apps/store/src/components/Header/Header.tsx
apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
packages/ui/src/lib/globalStyles.ts

Use CSS variables to set transparent header background color based on dark/light page
New campaign page going live today at 16.00

Set correct colors on animating header background

---

apps/store/src/features/carDealership/validateCarDealershipTrial.ts

Add additional logging for the car dealership trial validation form

Car dealership trial validation | Improve logging

---

apps/store/src/features/widget/ConfirmationPage.tsx
apps/store/src/features/widget/PaymentPage.tsx
apps/store/src/features/widget/publishWidgetEvent.ts
apps/store/src/features/widget/usePublishWidgetInitEvent.ts
apps/store/src/pages/debugger/iframe.tsx

- Fix iframe debugger so it shows all widget events
Cleaner API :)

GEN-1545 | Refactor publish widget event helper

---

apps/store/src/components/CartNotification/CartNotification.stories.tsx
apps/store/src/components/CheckoutHeader/CheckoutHeaderBreadcrumbs.stories.tsx
apps/store/src/components/Combobox/Combobox.stories.tsx
apps/store/src/components/InputDate/InputDate.stories.tsx
apps/store/src/components/InputSelect/InputSelect.stories.tsx
apps/store/src/components/PersonalNumberField/PersonalNumberField.stories.tsx
apps/store/src/components/PriceCalculator/CurrentInsuranceField/InputCurrentInsurance.stories.tsx
apps/store/src/components/PriceCalculator/MixedBreedPicker/MixedBreedPicker.stories.tsx
apps/store/src/components/ProductPage/PurchaseForm/CancellationForm/CancellationForm.stories.tsx
apps/store/src/components/ProductPage/PurchaseForm/ProductHero/ProductHero.stories.tsx
apps/store/src/components/StepperInput/StepperInput.stories.tsx
apps/store/src/components/TextField/TextField.stories.tsx
apps/store/src/components/TierSelector/TierSelector.stories.tsx
apps/store/src/components/ToggleCard/ToggleCard.stories.tsx
apps/store/src/features/blog/ArticleTeaser/ArticleTeaser.stories.tsx
apps/store/src/features/carDealership/LoadingSkeleton.stories.tsx
apps/store/src/features/sas/SasEurobonusSection.stories.tsx

Update grid settings in Storybook part 2

---

apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx

- Align the language between HTML lang and hreflang
- Keep the country code in the hreflang
- I missunderstood Peter. He wanted to keep the country code in the hreflang. The important thing is that the language is the same in the HTML lang and the hreflang.

GEN-1525 | Align hreflang and HTML lang attributes (redo)

---

apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
apps/store/src/features/carDealership/useAcceptExtension.ts
apps/store/src/features/memberArea/MemberAreaMemberInfo.graphql
apps/store/src/features/memberArea/PaymentsSection/PaymentsSection.tsx
apps/store/src/features/widget/SignPage.tsx
apps/store/src/graphql/MemberFragment.graphql

- Remove deprecated field `Member.hasActivePaymentConnection`
- Adopt new field `Member.paymentInformation.status`
- Noticed that we are using a deprecated field

GEN-1567 | Adopt `Member.paymentInformation.status` field

---

packages/ui/src/lib/globalStyles.ts

Fix typo in color variable
Remove error

Fix header transparent color typo

---

apps/store/src/components/PriceCalculator/FetchInsurance.tsx

More debug logs for Insurely to help with debugging

More logs around Insurely flow

---

apps/store/src/blocks/ProductReviewCommentsBlock.tsx
apps/store/src/components/ReviewComment/ReviewComment.tsx

- Extract `Comment` component defined inside `ProductReviewCommentsBlock` into its own file;
- Rename it to `ReviewComment` to match _Figma_
**Mobile**
**Desktop**
Preparation for `ReviewComment` redesign (next PR)

GEN-1571 - refact(ProductReviewCommentsBlock - Comment): rename to ReviewComment

---

apps/store/public/locales/en/common.json
apps/store/public/locales/sv-se/common.json
apps/store/src/components/ReviewComment/ReviewComment.tsx
apps/store/src/components/ReviewComment/VerifiedIcon.tsx
packages/ui/src/icons/index.tsx

- Redesign of `ReviewComment` component
Part of _ProductReviews_ feature

GEN-1571 - styles(ReviewComment): redesign

---

apps/store/src/features/widget/ProductItem.tsx

Set a minimim start of today in the start date input.
I feel like we discussed this before but it seems very reasonable

Don't allow picking a start date in the past

---

apps/store/public/locales/en/common.json
apps/store/public/locales/sv-se/common.json
apps/store/src/components/Rating/Rating.stories.tsx
apps/store/src/components/Rating/Rating.tsx

- Added `Rating` component
**Mobile**
**Desktop**
Part of _Product Reviews_ project

GEN-1574 - feat: added Rating component

---

apps/store/src/pages/widget/[[...slug]].tsx

- Render 404 instead of failing build
- Update how to generate widget landing page paths
- The build should not fail if the page is not found
- Fix issue where we tried to render "widget/widget" slugs

Widget | Render 404 if story is not found in Storyblok

---

apps/store/src/features/widget/debuggerTrialCreate.ts
apps/store/src/pages/api/debugger/trial.ts

- Use the URL from the API to perform a redirect and kick off the extension widget flow
- Less copy pasting
- Requires API to be updated first

Trial debugger | redirect to URL from API

---

apps/store/src/components/QuickAdd/QuickAdd.stories.tsx
apps/store/src/components/QuickAdd/QuickAdd.tsx

- Add support for Badge component
Update accident x-sell project

GEN-1528 / Add Badge to QuickAdd component

---

apps/store/src/components/QuickAdd/QuickAdd.stories.tsx
apps/store/src/components/QuickAdd/QuickAdd.tsx

- Add USP list to QuickAdd component
Update accident x-sell project

Add USPs to QuickAdd component

---

apps/store/src/pages/forever/[code].tsx
apps/store/src/utils/PageLink.ts

- See title.
- Even though these pages are noindex Google visit them often via backlinks and recognise them as duplicate content. Goggle then sets their own canonical for the page, which often is wrong.

GEN-1416 | Add canonical to Forever code input pages

---

apps/store/src/pages/forever/[code].tsx

- Add space between the values in the robots meta tag
- It's [not strictly necessary](https://developers.google.com/search/blog/2007/03/using-robots-meta-tag#casing-and-spacing), but it makes it easier to read and it follows the examples from Google. Peter pointed it out.

Clean up robots meta-tag on forever page

---

apps/store/src/pages/forever/[code].tsx

N/A
- I missunderstood Peter, these are the correct URLs

Update canonical URL for forever pages

---

apps/store/public/locales/en/cart.json
apps/store/public/locales/sv-se/cart.json
apps/store/src/components/QuickAdd/QuickAddBundleView.stories.tsx
apps/store/src/components/QuickAdd/QuickAddInfoDialog.tsx

- Add QuickAddInfoDialog component 
Next PR: Add Perils
https://github.com/HedvigInsurance/racoon/assets/6661511/af5566f4-31a1-467c-9675-f7ca29931f7e

GEN-1529 / Add QuickAddInfoDialog component

---

apps/store/src/components/Accordion/Accordion.tsx
apps/store/src/components/QuickAdd/QuickAddBundleView.stories.tsx
apps/store/src/components/QuickAdd/QuickAddInfoDialog.tsx
apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx
apps/store/src/graphql/OfferRecommendationFragment.graphql

- Implement QuickAddinfoDialog
- Add Perils and adjust layout
https://github.com/HedvigInsurance/racoon/assets/6661511/a8523c59-6e0a-45bd-89d2-ac7f29dd963e
Next PR: Design tweaks (Perils are unevenly spaced it looks like)

GEN-1529 / Add Perils to QuickAddinfoDialog

---

apps/store/src/components/Accordion/Accordion.tsx

- Show focus state on the accordion item triggers
- Better accessibility for keyboard users

GEN-1613 | Add focus state for accordion items

---

apps/store/src/components/InputDay/InputDay.tsx

- See title
- feedback from design critique

Update design of day input field

---

apps/store/src/components/Perils/Perils.tsx

Make even row gap when layout is single column

Fix Perils gap when layout is single column

---

apps/store/src/components/QuickAdd/QuickAddInfoDialog.tsx
packages/ui/src/components/Dialog/Dialog.stories.tsx
packages/ui/src/components/Dialog/Dialog.tsx

Update Dialog story

---

apps/store/public/locales/sv-se/cart.json

Feedback from William and Peter

Update translations QuickAdd

---

apps/store/src/blocks/ButtonBlock.tsx

- Add option to button block to show loading state while loading new page
- We want to use this for page transitions that take a while to load

GEN-1621 | Add option to show loading state in button block

---

apps/store/src/blocks/ProductReviewsBlock.tsx
apps/store/src/services/storyblok/storyblok.ts

* Rename `ProductReviewCommentsBlock` --> `ProductReviewsBlock`
I think new name's better.

GEN-1570 - rename ProductReviewCommentsBlock to ProductReviewsBlock

---

apps/store/src/components/CartPage/CartPage.tsx

Spacing was off on Cart page
Comment on how we use `Space`. For me it get's a bit hard to follow the spacing on a page when using multiple levels of nested `Space` components 🙃 

GEN-1630 / Adjust spacing on cart page

---

apps/store/public/locales/en/cart.json
apps/store/public/locales/sv-se/cart.json
apps/store/src/components/QuickAdd/QuickAddInfoDialog.tsx
apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx

Add dismiss button and and inline read more text button
https://github.com/HedvigInsurance/racoon/assets/6661511/ce4a2b1c-720f-44eb-8158-9d49b53ea6ee

GEN-1630 / Add dismiss button and and inline read more text button

---

apps/store/src/components/QuickAdd/QuickAddInfoDialog.tsx

Hide scrollbar in Dialog
https://github.com/HedvigInsurance/racoon/assets/6661511/08b897e4-65e6-4923-adb3-d5cb29dae489
Not something we generally should do, but in this context it works fine

GEN-1630 / Hide scrollbar in dialog

---

apps/store/next-csp.config.js

- Allow connect-src for Linkedin
- Allow frame-src Google Doubleclick

Update CSP policy

---

apps/store/public/locales/en/common.json
apps/store/public/locales/sv-se/common.json
apps/store/src/components/ProductReviews/ProductReviews.tsx
apps/store/src/services/productReviews/productReviews.utils.ts

* Add translation for _view reviews_ button
* Make sure each comment has an unique id: that solves a React issue with duplicate keys
https://github.com/HedvigInsurance/racoon/assets/19200662/18ff2dcf-c97a-465d-89f7-0f9759141d3b
Can be tested [here](https://hedvig-dot-com-git-gen-1570-refactreview-comments-hedvig.vercel.app/se/forsakringar/olycksfallsforsakring/av)
Part of _Product Reviews_ feature.

GEN-1570 - identify comments by id

---

.github/renovate.json5
apps/store/next.config.js
apps/store/package.json
apps/store/scripts/storyblok-cache-version.js
apps/store/src/pages/api/draft.ts
apps/store/src/pages/api/revalidate.ts
apps/store/src/pages/sitemap.xml.js
apps/store/src/services/storyblok/api.ts
yarn.lock

- Use `@storyblok/js` over the underlying lib
- There's no reason for us to use both libs and the `@storyblok/js` lib has improved UX

Prefer @storyblok/js over storyblok-js-client

---

apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx

- Add popular badge to QuickAdd component 

GEN-1630 / Add popular badge to QuickAdd component

---

apps/store/src/components/QuickAdd/QuickAddInfoDialog.tsx

- Add background blur to close button

GEN-1630 / Add background blur to close button

---

apps/store/src/components/QuickAdd/AddToCartButton.tsx

- Scroll to top after adding accident x-sell
https://github.com/HedvigInsurance/racoon/assets/6661511/d6d39a7c-feeb-4cf1-91a4-d45b5cef158e

GEN-1630 / Scroll to top after adding accident x-sell

---

apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/QuickAdd/AddToCartButton.tsx
apps/store/src/components/QuickAdd/DismissButton.tsx

- Adjust spacing on `CartPage`
- Add scroll to top after dismissing x-sell accident

Add scroll to top after dismissing accident x-sell

---

apps/store/src/blocks/AccordionItemBlock.tsx
apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx

- Use custom `renderRichText` function in `Accordion` component
- Solve issue and remove ending backslash (/) for links in Accordion

GEN-1642 | Use custom rich text converter in Accordion

---

apps/store/src/components/ButtonNextLink.tsx
apps/store/src/components/ConfirmationPage/ContractCard.tsx
apps/store/src/components/ContactUs/ContactUs.tsx
apps/store/src/components/ProductPage/PurchaseForm/DeductibleSelector.tsx

Update rel attributes for target _blank links. 
Updated hardcoded rel values with Peter

Update rel attributes for target _blank links

---

apps/store/src/components/Cancellation/CancellationForm.tsx
apps/store/src/components/Cancellation/IEXCancellation.tsx
apps/store/src/features/widget/SwitchPage.tsx

- Refactor cancellation form to be easier to reuse
- Preparing to implement it in the widget and offer presenter

Refactor CancellationForm to be reusable

---

apps/store/src/components/InsuranceDocumentLink.tsx
apps/store/src/components/PDFViewer.tsx
apps/store/src/components/ProductItem/ProductDetails.tsx
apps/store/src/pages/debugger/iframe.tsx
apps/store/src/utils/useIsEmbedded.ts

- Conditionally use the PDF viewer if the site is embedded in an iframe or a WebView
- I played with the idea of enabling the PDF viewer by passing a prop but I think this is a more straightforward approach

Display inline PDF when iframe/WebView is detected

---

apps/store/src/services/adyen/useGetAdyenCheckout.ts
apps/store/src/utils/l10n/countries.ts

- Store currency code by country
- Send correct currency code to Adyen
- For some reason we sent locale and this caused errors

Bug: send correct currency code to Adyen

---

apps/store/src/services/PriceCalculator/formFragments.ts

- Add validation for postal code field to only allow numbers (no spaces)
- See discussion here: https://hedviginsurance.slack.com/archives/C02JPS466NS/p1704372892277979

Add stricter validation for postal code field

---

apps/store/package.json
yarn.lock

Update @storyblok/js to 3.0.1, this fixes editor live preview
Comments here:
https://github.com/storyblok/storyblok-react/issues/876
Solution:
https://github.com/storyblok/storyblok-react/pull/883

Update @storyblok/react, fixed editor experience

---

apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx
apps/store/src/blocks/TrustpilotBlock.tsx
apps/store/src/components/TextWithLink.tsx
apps/store/src/services/storyblok/Storyblok.helpers.ts

Create utility for rel attributes from Storyblok link field to centralise logic. 
The logic is requested from Peter

Create utility for rel attributes from Storyblok link field

---

.github/renovate.json5
apps/store/package.json
apps/store/public/mockServiceWorker.js
yarn.lock

Updat with upstream bugfix for navigation between stories

Updated @storyblok/react to 3.0.2, fixes CMS editor experience (now without navigation bug)

---

apps/store/public/locales/en/common.json
apps/store/public/locales/sv-se/common.json
apps/store/src/components/ProductReviews/ProductReviews.tsx
apps/store/src/components/ProductReviews/ReviewComment.tsx
apps/store/src/components/ProductReviews/ReviewsDistributionByScore.tsx
apps/store/src/components/ProductReviews/ReviewsFilter.tsx

* Update width
* Add space between reviews filter options
* Truncate the size of review comments by 3 at maximum
Requested by Peter/William

GEN-1686 - styles(ProductReviews): tweaks

---

apps/store/src/features/memberArea/MemberAreaMemberInfo.graphql
apps/store/src/features/memberArea/components/Menu.tsx

- Add name and SSN at the top of the sidebar menu
I have asked William for mobile design, currently we hide it

Show member info in menu

---

apps/store/src/features/memberArea/components/MemberAreaLayout.tsx
apps/store/src/features/memberArea/components/Menu.tsx

- Add loading state for Menu and Content 
https://github.com/HedvigInsurance/racoon/assets/6661511/c1c88cf7-c634-4873-831f-d3f02f1da61d

Add loading state for Menu and Content

---

apps/store/src/features/memberArea/components/Menu.tsx

- Mask SSN so we don't display the last 4 digits
Don't display full SSN

Add mask to SSN last 4 digits

---

apps/store/src/services/Tracking/Tracking.ts

- Added `userData` to `purchase` and `view_item` events. We also need to add it to `open_price_calculator` event so basically we're taking about adding it to all ecommerce events.
Requested by Sonny

GEN-1700 - tracking: added user data to all ecommerce events (purchase and view_item)

---

apps/store/src/components/ProductReviews/ProductAverageRating.tsx

* Include more information on product average rating structured data.
* Code scouting in a `console.log` statement.

GEN-1696 - chore(ProductAverageRating): include information on structured data

---

apps/store/src/components/ProductReviews/ReviewComment.tsx

GEN-1696 - styles(ReviewComment): reduce date font size

---

CONTRIBUTING.md

Subj.  I did not try to add anything new, just documenting some of our current agreements

Remove obsolete coding conventions; Add/update some relevant ones

---

apps/store/src/components/ProductReviews/ProductAverageRating.tsx
apps/store/src/components/ProductReviews/ReviewsDialog.tsx

- Pause video when opening product reviews dialog
(Removed background blur in screen recording for showcase)
https://github.com/HedvigInsurance/racoon/assets/6661511/a9c8caa9-968a-4940-9391-eee8dc7fa7c6
Potential performance boost and decrease distraction

Pause product video when opening product reviews dialog

---

apps/store/src/components/PriceCalculator/PriceCalculator.tsx
apps/store/src/components/PriceCalculator/Warning/Warning.tsx
apps/store/src/components/PriceCalculator/Warning/showPriceIntentWarningAtom.ts

Use jotai atom to control when to show PriceIntentWarning
Make sure we show potential warning after user go back and edit reg nr

GEN-1692 / Use atom to toggle PriceIntentWarning state

---

.vscode/racoon.code-workspace
apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
apps/store/src/utils/jsonSchema.ts

Added more information for _Organization_ structured data.
"The goal is to exaggerate that we are  a real insurance company, not just at website"

GEN-1524 - chore(structured-data): update organization sctructured data

---

apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx

* `ImageTextBlock` now can nest `RichTextBlock`
* Added styles customisations for when `RichTextBlock` as rendered as others block children

GEN-1736 - feat(ImageTextBloc): support RichTextBlock

---

apps/store/src/components/PriceCalculator/PriceCalculator.tsx

Add Datadog action for showPriceIntentWarning
Track feature

Add datadog action for showPriceIntentWarning

---

apps/store/next-csp.config.js

- Allow _Google Translate_ in our `connect-src` policy.
Cleanup [CSP violations](https://app.datadoghq.eu/dashboard/tft-qsw-5iu/vercel-hedvig-com?fullscreen_end_ts=1706696251347&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=overview&fullscreen_start_ts=1706091451347&fullscreen_widget=1271882006666618&refresh_mode=sliding&view=spans&from_ts=1706694450075&to_ts=1706695350075&live=true)

GEN-1739 - chore(csp): allow google translate for connect-src policy

---

apps/store/next-csp.config.js

- Include `'https://translate.googleapis.com'` to `connect-src`
I had enable the wrong domain before 😢

GEN-1739 - chore(csp): enable google translate

---

apps/store/next-csp.config.js

- Added 'data:' to `font-ssrc`

GEN-1739 - chore(csp): added 'data:' to font-src

---

apps/store/package.json
yarn.lock

fix(open-telemetry): add missing dependencies

---

apps/store/src/components/ComparisonTable/ComparisonTable.tsx

See title
Request from PeteRequest from Peter

Use span inside table cell

---

apps/store/next-csp.config.js

GEN-1739 - fix(csp): linkedin

---

apps/store/next-csp.config.mjs
apps/store/next.config.mjs
package.json

Convert NextJS config to EMS
Prerequisite for using ESM by default

Convert NextJs config to ESM

---

apps/store/src/components/BankIdV6Dialog.stories.tsx
apps/store/src/components/BankIdV6Dialog.tsx
apps/store/src/graphql/ShopSessionSigningFragment.graphql
apps/store/src/services/apollo/client.ts
apps/store/src/services/authApi/fetchJson.ts
apps/store/src/services/authApi/login.ts
apps/store/src/services/bankId/bankId.types.ts
apps/store/src/services/bankId/bankIdReducer.ts
apps/store/src/services/bankId/useBankIdCheckoutSign.ts
apps/store/src/services/bankId/useBankIdLogin.ts

* Integrate with BE and enable BankID login/sign with QR code

GEN-1776 - feat(BankIdV6Dialog): add support for BankId QR code

---

apps/store/.storybook/i18next.mjs
apps/store/next-i18next.config.cjs
apps/store/next.config.mjs
apps/store/package.json
package.json
packages/ui/package.json

Subj, convert to ESM package
So that we consume smaller, ESM versions of external dependencies

Set type: module for using ESM by default

---

apps/store/package.json
apps/store/src/components/BankIdV6Dialog.tsx
apps/store/src/graphql/ShopSessionSigningFragment.graphql
apps/store/src/services/authApi/login.ts
apps/store/src/services/bankId/bankId.types.ts
apps/store/src/services/bankId/bankIdReducer.ts
apps/store/src/services/bankId/useBankIdCheckoutSign.ts
apps/store/src/services/bankId/useBankIdLogin.ts
yarn.lock

feat(bankid-v6): support for opening bankid app on the same device

---

apps/store/src/pages/_app.tsx
packages/ui/src/global.css.ts
packages/ui/src/theme/globalStyles.ts

Move most of ui/theme/globalStyles to vanilla-extract global.css.ts
- Showcase of `globalStyle` API
- Compile-time styles are faster

Move global styles to vanilla-extract

---

apps/store/src/components/ComparisonTable/ComparisonTable.tsx

Update table cell elements

---

apps/store/public/mockServiceWorker.js
apps/store/src/components/Header/Header.tsx

Fix navigation styles by replacing last usage of --body-bg-color literal with Vanilla CSS var reference

Fix last remaining --body-bg-color CSS var usage

---

apps/store/src/features/blog/ArticleTeaser/ArticleTeaser.tsx
apps/store/src/features/blog/BlogArticleCategoryListBlock.tsx
apps/store/src/services/storyblok/Storyblok.helpers.ts

Convert CMS href to absolute paths for blog categories

Fix blog category links

---

apps/store/src/pages/sitemap.xml.ts

Convert sitemap generation to typescript

Convert sitemap generation to typescript

---

apps/store/src/features/blog/BlogArticleBlock.tsx
apps/store/src/features/blog/BlogArticleListBlock.tsx

Fix another place where we use CMS links as non-absolute URLs

Fix blog category link from article page

---

apps/store/src/pages/[locale]/manypets/migration/[shopSessionId].tsx

* Handle error cases for _ManyPets MIgration_ pages by logging and return 404.
We saw an opportunity to handle error cases for _ManyPets Migration_ pages in a better way. More information in this [slack thread](https://hedviginsurance.slack.com/archives/C041SD67G82/p1707899575331819).

chore(manypets-migration-page): handle error cases by logging and return 404

---

apps/store/src/pages/_document.tsx

Fix html lang during server rendering, it needs to be using router variable instead of next i18n one

Fix html lang during static rendering

---

packages/ui/src/global.css.ts

Make sure smooth scrolling is enabled by defaulkt

Fix smooth scrolling on ProductPage

---

apps/store/src/components/ProductData/ProductDataProvider.tsx

Use jotai atomFamily to store current product data instead of creating new store to reset data for new context
Next step would be unifying Jotai atoms to single providers, this would be needed for app router

Refactor ProductDataProvider to use atomFamily and default jotai store instead of per-product stores

---

apps/store/.storybook/decorators.tsx
apps/store/.storybook/preview.tsx
apps/store/src/services/apollo/client.ts

Add ApolloProvider to Storybook preview for the stories that rely on GraphQL mocks

---

apps/store/src/components/ProductReviews/ReviewCommentV2.css.ts
apps/store/src/components/ProductReviews/ReviewCommentV2.tsx
apps/store/src/components/ProductReviews/ReviewsDialogV2.tsx
apps/store/src/components/ProductReviews/Stars.css.ts
apps/store/src/components/ProductReviews/Stars.tsx

* Added `ReviewCommentV2` with some UI changes.

feat(ProductReviewsV2): added new review comment component - ReviewCommentV2

---

apps/store/src/features/memberReviews/productReviews.ts

* Had update the data structure we use in vercel kv to hold average rating and reviews. This is a preparatory changing for adding more data there: _company average rating_ and _latest reviews_ despite the associated product (down in the stack).
We're gonna use _company average rating_ and _latest reviews_ for displaying general review information as shown below:

GEN-1835 - refact(productReviews): get averageRating and reviews from a different field on redis

---

apps/store/src/middleware.ts

Make sure locales redirect is permanent (308)
See details in thread https://hedviginsurance.slack.com/archives/C041SD67G82/p1708609848522859

Set 308 (permanent redirect) status on locale redirect

---

apps/store/next-i18next.config.cjs
apps/store/src/app/[locale]/TranslationsProvider.tsx
apps/store/src/app/[locale]/i18n.ts
apps/store/src/app/[locale]/layout.tsx
apps/store/src/app/[locale]/test/ClientComponent.tsx
apps/store/src/app/[locale]/test/page.tsx
apps/store/src/app/[locale]/test/styles.css.ts
apps/store/src/app/layout.tsx
apps/store/src/features/memberArea/pages/protectedPageServerSideProps.ts

Support app router i18n
Server-side translations (test/page) and client-side (test/ClientComponent)
Based on https://i18nexus.com/tutorials/nextjs/react-i18next
To simplify the setup, we always load all namespaces without picking only needed ones

App router localization

---

apps/store/package.json
apps/store/public/locales/en/carDealership.json
apps/store/public/locales/sv-se/carDealership.json
apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsent.css.ts
apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsent.stories.tsx
apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsent.tsx
yarn.lock

Add MyMoneyConsent component with radix checkbox
https://github.com/HedvigInsurance/racoon/assets/6661511/66807a16-4a81-42e7-802b-daf9d3137497
My Money porject

Add MyMoneyConsent component with radix checkbox

---

apps/store/src/components/Animations/LottieAnimation.tsx
apps/store/src/components/PriceCalculator/PriceCalculatorDynamic.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
apps/store/src/features/widget/CalculatePricePage.tsx

Load PriceCalculator with next/dynamic. 327KB uncompressed code split

Dynamically load PriceCalculator

---

apps/store/src/components/DebugDialog/DebugShopSessionSection.tsx

Fix Debug > Reset session from prepending extra locale prefix to current url (/se/path -> /se/se/path)

Fix session reset URL in debug menu

---

apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/InputDay/InputDay.tsx
apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts

Wrap some of expensive React updates during purhcase process into startTransition
Responsiveness optimization

Wrap expensive tree updates during purhcase process into startTransition

---

apps/store/src/components/CheckoutPage/CheckoutPage.tsx

Optimize full-page rerenders of checkout page every time we poll BankID status by extracting CheckoutForm component
Separated frequently rerendered CheckoutForm from other parts of checkout page that change less frequently
~4x rerender cost improvement

Prevent frequent full-page rerenders during checkout

---

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx

Make OfferPresenter component use next/dynamic to reduce app bundle size

Make OfferPresenter dynamic to reduce app budle size (-20KB)

---

apps/store/src/components/ChangeSsnWarningDialog/ChangeSsnWarningDialog.css.ts
apps/store/src/components/ChangeSsnWarningDialog/ChangeSsnWarningDialog.tsx
apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx

Fix DOM in ChangeSsnWarningDialog (remove invalid p > p nesting)

---

apps/store/src/components/DebugDialog/DebugTextKeys.tsx
apps/store/src/components/ProductPage/PurchaseForm/useOpenPriceCalculatorQueryParam.ts
apps/store/src/components/ProductPage/PurchaseForm/usePreloadedPriceIntentId.ts
apps/store/src/utils/useDebugShopSession.ts

Use next/navigation for routing in few more places
Small standalone change extracted from supporting product pages in app router

Migrate some hooks from next/router to next/navigation

---

apps/store/src/components/ProductPage/ProductPageContext.tsx

Make value of ProductPageContext match actual usage
I'll see if we can/should convert this to jotai atoms.  Removing dead code first to make it easier

Make ProductPageContext smaller, we did not use most of the data there

---

packages/ui/src/components/Text/Text.tsx

Make sure we set correct default size for Text component
Forgot to add it when refctoring Text component

Set default size for Text component

---

apps/store/public/locales/en/bankid.json
apps/store/public/locales/sv-se/bankid.json
apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.stories.tsx
apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx
apps/store/src/services/authApi/login.ts
apps/store/src/services/bankId/bankId.types.ts
apps/store/src/services/bankId/bankIdReducer.ts
apps/store/src/services/bankId/useBankIdLogin.ts

* Adds UI Feedback for when QR get's scanned during _login_ flow.
https://github.com/HedvigInsurance/racoon/assets/19200662/077c5b14-98c7-4983-8691-db9f02490cb7
Part of BankId v6 feture.

GEN-1871 - feat(bankId - login): added UI feedback for when QR code is scanned

---

apps/store/src/components/BankIdDialogDynamic.tsx
apps/store/src/components/BankIdV6Dialog/BankIdV6DialogDynamic.tsx
apps/store/src/pages/_app.tsx

* Defer the loading of BankId's dialogs.
Better initial performance by not including JS for those modals in the initial bundle.

perf(bankid-dialog): defer BankIdDialog/BankIdV6Dialog loading

---

apps/store/src/features/carDealership/CarBuyerValidationPage.helpers.tsx
apps/store/src/features/carDealership/CarBuyerValidationPage.tsx
apps/store/src/features/carDealership/validateCarDealershipTrial.ts
apps/store/src/pages/api/car-buyer/validation/[dealerId].ts

Display trial price in car trial validation tool
Some refactoring
- Safer types
- Reuse response type between API route and UI components
- Catch every error in API route, before we had nothing if error happened before fetch (ex. missing env variable)
Dealership request - more info is always better, I guess

Add trial price to car trial validation tool

---

apps/store/src/pages/_app.tsx

Load GTM right away when cookie banner feature is disabled
Allow GTM debugging in staging and preview branches

Load GTM immediately when cookie banner is disabled

---

apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
apps/store/src/components/CheckoutPage/useUpdateCustomer.ts
apps/store/src/features/widget/SignPage.tsx
apps/store/src/graphql/ShopSessionCustomerFragment.graphql
apps/store/src/graphql/ShopSessionFragment.graphql
apps/store/src/pages/[locale]/checkout/index.tsx
apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx
apps/store/src/services/Tracking/TrackingContext.tsx
apps/store/src/utils/customer.ts
apps/store/src/utils/getOrThrowFormValue.ts

- Switch to new API for server-driven decision on what customer contact info we should collect
- Stop using contact info from shopSession.customer as it will be removed soon 
Reduce amount of personal info that travels through unauthenticated API

Use server logic for shouldCollectEmail / Name and stop using customer contact info from server

---

apps/store/src/services/bankId/bankId.utils.ts

**Before**
https://github.com/HedvigInsurance/racoon/assets/19200662/4205e860-b2d2-4659-9d87-bb0cdf40c55a
**After**
https://github.com/HedvigInsurance/racoon/assets/19200662/89bfac2d-e9d3-48c9-b6a6-98b6ada6c0b0

fix(bankid): keep "signed sucessfully" state when signing after login

---

apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
apps/store/src/features/widget/SignPage.tsx
apps/store/src/graphql/MemberFragment.graphql
apps/store/src/services/Tracking/Tracking.ts

- Remove legacy events `offer_created` and `signed_customer`
- Pass email, first_name and last_name of signed member to `purchase.userData` (hashed values as in https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/customer-information-parameters)
Cleanup

Update purchase reporting for customer data API changes

---

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx
apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsent.tsx

Add Datadog actions for MyMoney consent
Monitor usage of new feature

Add Datadog actions for MyMoney consent

---

CONTRIBUTING.md

Updated code style guide
- Remove mentions of obsolete solutions
- Add vanilla-extract recommendations
- Add app router dir structure
More to come

Update style guide

---

apps/store/src/app/debugger/components/CreateSessionForm/CreateSessionForm.css.ts
apps/store/src/app/debugger/components/CreateSessionForm/CreateSessionForm.tsx
apps/store/src/app/debugger/components/CreateSessionForm/SubmitButton.tsx
apps/store/src/app/debugger/page.tsx

Fix styling of the session debugger form and handle submission pending state.
Extracting client components into own files and handling pending state for better UX.

fix: [RND-542] Fix session debugger styling and pending state

---

apps/store/src/components/BankIdDialogDynamic.tsx
apps/store/src/components/BankIdV6Dialog/BankIdV6DialogDynamic.tsx
apps/store/src/components/PriceCalculator/PriceCalculatorDynamic.tsx

There's a bug in `next/dynamic` which leads to `loader` function never being called when component is rendered inside app router.  Passing it as first positional argument solves the issue

Fix next/dynamic calls to be compatible with app router

---

apps/store/src/app/[locale]/StoryblokLayout.tsx
apps/store/src/app/[locale]/appDebug/[[...slug]]/ProductCmsPage.tsx
apps/store/src/app/[locale]/appDebug/[[...slug]]/page.tsx
apps/store/src/app/[locale]/error.tsx
apps/store/src/app/[locale]/layout.tsx
apps/store/src/app/[locale]/test/page.tsx
apps/store/src/appComponents/RootLayout/RootLayout.tsx
apps/store/src/appComponents/providers/StoryblokProvider.tsx
apps/store/src/components/AppErrorDialog.tsx
apps/store/src/components/BankIdDialog.tsx
apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx
apps/store/src/components/DebugDialog/DebugResumeSessionSection.tsx
apps/store/src/components/GlobalBanner/GlobalBanner.tsx
apps/store/src/components/GlobalBanner/GlobalBannerDynamic.tsx
apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
apps/store/src/components/ProductData/ProductDataProvider.tsx
apps/store/src/components/ProductPage/PriceIntentContext.tsx
apps/store/src/components/ProductPage/ProductPage.tsx
apps/store/src/components/ProductPage/ProductPageContext.tsx
apps/store/src/components/ProductPage/ProductPageTrackingProvider.tsx
apps/store/src/components/ProductPage/ProductPageViewTrack.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
apps/store/src/features/memberReviews/CompanyReviewsMetadataProvider.tsx
apps/store/src/features/memberReviews/ProductReviewsMetadataProvider.tsx
apps/store/src/pages/_app.tsx
apps/store/src/services/appErrors/AppErrorContext.tsx
apps/store/src/services/bankId/BankIdContext.tsx

CMS pages in app router prototype

---

apps/store/public/locales/en/bankid.json
apps/store/public/locales/sv-se/bankid.json
apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx

* Bankid v6 - Update copy used for signing flow 
**Before**
**After**

GEN-1933 - fix(bankid-v6): update sign flow copy

---

apps/store/src/features/carDealership/DebuggerCarTrial/DebuggerCarTrialPage.tsx

Can't use notFound in pages router

Fix broken build

---

apps/store/src/pages/debugger/car-trial.tsx

Return 404 in production for Car trial debugger

---

apps/store/src/features/widget/README.md

Code scout: Links for debugger tools included locale. They shouldn't anymore.

chore(debugger): updated debugger tools links

---

.vscode/racoon.code-workspace

- Update prettier path. For some reason `.yarn/sdks/prettier/index.js` doesn't exist for me.
It's only for me?!

chore: update prettier path

---

apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx

Improves a little bit the experience for IOS users that **open up hedvig-com in another browser other than safari**. For the case you've open it on Safari while having another browser as the default one, _Bankid App_ will redirect to your default browser and I'm afraid there's nothing we can do about it. At least the Safari tab that will be on the current state so although not perfect, the user can still go back to hevig-com manually. 
Raised as an issue during a testing session. We can't solve the actual issue but we can at least make things a little bit better for other cases.

GEN-1937 - fix(bankid): launching on IOS

---

apps/store/src/components/ProductReviews/ReviewsDialog.tsx

- Temporarely remove review comments caching mechanism as it's work intended
The hotfix is to fetch reviews comments every time reviews dialog gets opened until caching
get's properly implemented

GEN-1950 - fix(ReviewsDialog): temporarily remove reviews comments caching

---

apps/store/src/features/memberReviews/ProductReviewsMetadataProvider.tsx

GEN-1950 - refact(ProductReviewsMetadataProvider): remove unused variables

---

apps/store/src/blocks/FooterBlock.tsx

- Display current year on footer
2023 was being hardcoded before.

fix(FooterBlock): display current year in footer

---

apps/store/src/app/debugger/car-trial/CarTrialDebuggerForm.tsx
apps/store/src/app/debugger/car-trial/actions.tsx
apps/store/src/features/carDealership/DebuggerCarTrial/createCarDealershipTrial.ts
apps/store/src/features/carDealership/DebuggerCarTrial/debuggerCarTrial.types.ts

Add MyMoney consent checkbox to car trial debugger to test MyMoney flow

Add MyMoney consent checkbox to car trial debugger

---

apps/store/src/app/debugger/car-trial/CarTrialDebuggerForm.tsx
apps/store/src/app/debugger/trial/components/TrialContractForm.tsx
apps/store/src/components/FormErrors/ErrorMessages.tsx
apps/store/src/components/InfoCard/InfoCard.tsx

Update ErrorMessage component UI

---

apps/store/.storybook/decorators.tsx

Fix broken Grid decorator in storybook

Fix broken Grid decorator in Storybook

---

apps/store/src/appComponents/DebuggerMenu/DebuggerMenu.tsx

Add car trial to debugger menu

---

apps/store/src/app/debugger/components/CreateSessionForm/CreateSessionForm.tsx

Use personal number field in session debugger to be able to use SSN short format and frontend validation

Use personal number field in session debugger

---

apps/store/src/features/carDealership/CarBuyerValidationPage.tsx
packages/ui/src/components/Dialog/Dialog.tsx
packages/ui/src/components/Text/Text.css.ts
packages/ui/src/components/Text/Text.tsx
packages/ui/src/theme/media.ts
packages/ui/src/theme/sprinkles.css.ts

Extract text sprinkles to global sprinkles since they are reusable 
Using sprinkles for commonly used properties reduces the output of CSS

Make sprinkles global

---

apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx
apps/store/src/services/bankId/bankIdReducer.ts

Add a custom action for when QRCode get scanned sign/login
We can use that to easy stop "abandoned" sessions.

chore(bankid): qr code scanned custom action

---

apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx

* Log when sign/login operations are cancelled by the user
So it becomes even clear what happened while checking the logs. That ofc can be verified while checking the session replay. However I though it would be also nice to have in a log form.

chore(bankid): log when sign/login operation is cancelled by user

---

apps/store/src/services/Tracking/Tracking.ts
apps/store/src/services/Tracking/tracking.test.ts

Make sure we format email properly in user properties and don't strip away punctuations or `@`
We format it incorrectly

Fix email formatting in user properties

---

packages/ui/src/components/Button/Button.tsx

Make sure we pass classNames to Button component to not break styles in some Storyblok blocks
Bug

Make sure we pass classNames to Button component

---

apps/store/scripts/storyblok-analyze-stories.cjs
apps/store/scripts/storyblok-fetch-stories.cjs

Add scrips for dumping and analyzing CMS stories
For now I need them to deprecate and remove some of page flags, but could be useful in the future as well

Storyblok story analysis scripts

---

packages/ui/src/components/Button/Button.css.ts
packages/ui/src/components/Button/Button.helpers.ts

Refactor responsive styles for button into one object
Idea from @Youakeem

Refactor responsive styles for button

---

apps/store/src/graphql/MemberFragment.graphql

First and lastname was missing in on MemberFragment
First name and lastname was missing in user data tracking

Add missing first and lastname to user data

---

apps/store/src/services/Tracking/Tracking.ts

We can't derive zipcode from the tracking context. So take it from `priceIntentData` in the cart instead. 
Ensure proper tracking

Make sure we send zipcode in userData

---

apps/store/src/app/[locale]/StoryblokLayout.tsx
apps/store/src/blocks/FooterBlock.tsx
apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
apps/store/src/utils/l10n/useChangeLocale.ts

Make language change implementation work without prop-drilling `story` - we have enough info in the DOM
Same theme as previous PRs - making layout work without using `story` data

Refactor change language logic to use alternate path from DOM

---

apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx
apps/store/src/components/ButtonNextLink.tsx
apps/store/src/components/ProductItem/ProductItem.tsx
apps/store/src/features/widget/ProductItem.tsx
packages/ui/src/components/Button/Button.tsx
packages/ui/src/components/TypeUtils.ts
packages/ui/src/index.ts

Transform the `Button` component to a polymorphic component with the `as` prop.
Support using different elements with the Button component such as `a` and `Link`.

tech: Support using different elements for the Button component

---

apps/store/src/components/Banner/Banner.css.ts
apps/store/src/components/Banner/Banner.tsx

Subj
Refactor before changing banner-related logic in next PR

Convert Banner styles to vanilla-extract

---

apps/store/src/components/InputDay/InputDay.css.ts
apps/store/src/components/InputDay/InputDay.tsx

* Migrate `InputDay` styles to use `vanilla-extract/css`
Gonna need it for adjusting some stuff for Accident Cross Sell.

styles(InputDay): migrate InputDate to vanilla css

---

apps/store/src/components/Banner/Banner.css.ts

Add :focus-outline style to banner close button

---

apps/store/src/pages/_document.tsx

Use OneTrust test script in non production env
Better debugging

Use OneTrust test script in non production env

---

apps/store/src/services/PriceCalculator/data/SE_PET_CAT.ts

That was raised during a testing session
now / before
Code scout.

ui(cat-insurance): unify the way Yes/No questions are presented

---

apps/store/src/services/adyen/useAdyenTranslations.ts
apps/store/src/utils/l10n/countries.ts
apps/store/src/utils/l10n/locales.ts
apps/store/src/utils/l10n/types.ts

Set correct no lang - currently a missmatch, should be no-NO

Set correct no lang

---

apps/store/src/components/QuickAdd/QuickAddEditableView.css.ts

GEN-1893 - styles(QuickAddEditableView): update background color

---

apps/store/src/components/StepperInput/StepperInput.css.ts
apps/store/src/components/StepperInput/StepperInput.tsx

styles(StepperInput): vertically centralize increase/decrease controls

---

apps/store/src/components/InputDay/InputDay.css.ts
apps/store/src/components/InputDay/InputDay.tsx

* Vertically center `InputDay` icon
https://github.com/HedvigInsurance/racoon/assets/19200662/6ab57517-edb8-40e1-8380-d3c823616edd

styles(InputDay): vertically center icon

---

apps/store/src/blocks/AccordionBlock.tsx
apps/store/src/blocks/VideoBlock.tsx
apps/store/src/components/ProductReviews/ProductAverageRating.tsx

Stop using next/head from reusable components (#4166)

---

apps/store/src/components/QuickAdd/QuickAddBundleView.css.ts
apps/store/src/components/QuickAdd/QuickAddBundleView.tsx
apps/store/src/components/QuickAdd/QuickAddEditableView.css.ts
apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx

* Update bundle view to match new design

GEN-2032 - styles(QuickAddBundleView): match new design

---

apps/store/src/app/AppInitTriggers.tsx
apps/store/src/app/layout.tsx

Subj.  Another small step towards app router

Init datadog client in app router

---

apps/store/src/blocks/HeadingBlock.tsx
apps/store/src/blocks/TickerBlock.tsx
packages/ui/src/components/Heading/Heading.tsx

- Cleanup TickerBlock
- Add support to render HeadingBlock as a p tag due to SEO reasons (request from Peter)

Cleanup TickerBlock

---

apps/store/src/pages/[locale]/widget/flows/[...slug].tsx

- Enable draft mode for widget flows.
Just found this thing missing while working on widget stuff

fix(widget): enable draft mode for flows

---

apps/store/src/components/Ticker/Ticker.tsx
packages/ui/src/theme/transitions.ts

Adjust animation timing and easing
Feedback from William and Ermir

Adjust animation timing and easing

---

apps/store/src/blocks/ProductCardBlock.tsx
apps/store/src/components/ProductCard/ProductCard.tsx
apps/store/src/pages/[locale]/[[...slug]].tsx

Support `priority` prop for ProductCard image
- SEO improvement
- More important for app router migration where lazy loaded images are sometimes delayed longer

Support ProductCardBlock.priority prop

---

apps/store/src/blocks/ButtonBlock.css.ts
apps/store/src/blocks/ButtonBlock.tsx
apps/store/src/blocks/HeroBlock.tsx

- Convert ButtonBlock wrapper style to vanilla-extract
- Removed ConditionalWrapper, code is easier to read without it

Convert ButtonBlock styles to vanilla-extract and clean code a little

---

apps/store/src/components/ProductPage/PriceIntentContext.tsx
apps/store/src/components/ProductPage/ProductPage.tsx
apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
apps/store/src/components/ProductPage/useCartEntryToReplace.tsx

Minor refactoring: move hooks we use elsewhere out of ProductPage

Move useCartEntryToReplace to its own module

---

apps/store/src/components/CookieConsent/CookieConsent.tsx
packages/ui/src/components/Button/Button.css.ts
packages/ui/src/components/Button/Button.tsx

Add ghost-alt button variant
https://github.com/HedvigInsurance/racoon/assets/6661511/b88cf505-b00b-4aa1-9818-8479cb2f5f05
Used in cookie consent, it was previously styled in OneTrust

Add ghost-alt button variant

---

apps/store/src/components/CookieConsent/CookieConsent.css.ts
apps/store/src/components/CookieConsent/CookieConsent.tsx

Add mobile styling for cookie consent

Add mobile styling for cookie consent

---

apps/store/src/components/ImageWithPlaceholder/ImageWithPlaceholder.css.ts
apps/store/src/components/ImageWithPlaceholder/ImageWithPlaceholder.tsx

Subj
This was part of debugging NextJs issue that looks useful on its own

Convert ImageWithPlaceholder styles to vanilla-extract

---

apps/store/src/components/ProductItem/ProductDetails.tsx
apps/store/src/components/ProductItem/ProductDetailsHeader.tsx
apps/store/src/features/widget/ProductItem.css.ts
apps/store/src/features/widget/ProductItem.tsx
apps/store/src/features/widget/ProductItemContainer.tsx

* Refact: migrate widget `ProducItem` styles into `vanilla-extract`.

GEN-2063 - refact(ProductItem): migrate to vanilla extract css

---

apps/store/next.config.mjs
apps/store/src/app/[locale]/appDebug/[[...slug]]/ProductCmsPage.tsx
apps/store/src/app/[locale]/appDebug/[[...slug]]/StoryBreadcrumbs.tsx
apps/store/src/app/[locale]/appDebug/[[...slug]]/page.tsx
apps/store/src/app/[locale]/layout.tsx
apps/store/src/app/layout.tsx
apps/store/src/pages/[locale]/widget/[[...slug]].tsx
apps/store/src/services/shopSession/ShopSessionService.ts
apps/store/src/services/storyblok/Storyblok.constant.ts
apps/store/src/services/storyblok/Storyblok.helpers.ts
apps/store/src/services/storyblok/storyblok.serverOnly.ts
apps/store/src/services/storyblok/storyblok.ts

Support stagic page generation in app router

---

apps/store/src/components/InputDay/InputDay.css.ts
apps/store/src/components/ToggleCard/ToggleCard.css.ts
apps/store/src/features/widget/ProductItem.css.ts
apps/store/src/features/widget/ProductItem.tsx
packages/ui/src/theme/vars.css.ts

* Update widgets ProductItem controls background color setting implementation by using CSS variables.
Better implementation

GEN-2063 - styles(ProductItem): change how ProductItem controls background color is configured

---

apps/store/src/components/TierSelector/TierSelector.css.ts
apps/store/src/components/TierSelector/TierSelector.tsx

* Migrate `TierSelector` to vanilla extract
First step through `TierSelector` redisign

GEN-2065 - refact(TierSelector): migrate to vanilla extract css

---

apps/store/src/app/api/draft_app/route.ts
apps/store/src/services/storyblok/storyblok.serverOnly.ts

Support Storyblok preview mode for app router CMS pages

Support Storyblok preview mode for app router

---

apps/store/src/app/[locale]/cms/[[...slug]]/ProductCmsPage.tsx
apps/store/src/app/[locale]/cms/[[...slug]]/page.tsx
apps/store/src/app/[locale]/layout.tsx
apps/store/src/app/api/draft_app/route.ts
apps/store/src/appComponents/providers/StoryblokProvider.tsx
apps/store/src/appComponents/storyblokBridgeOptions.ts
apps/store/src/blocks/PageBlock.tsx

Support Storyblok live editing for app router
We want to keep current editing experience after migration
Use cases
- click on content -> open block
- live update of edited blocks

Support Storyblok live editing

---

apps/store/src/components/Video/Video.css.ts
apps/store/src/components/Video/Video.stories.tsx
apps/store/src/components/Video/Video.tsx

Migrate Video component to vanilla-extract
https://github.com/HedvigInsurance/racoon/assets/6661511/774141b6-ca33-45e9-86d2-9bfb2397a724
Migrate to vanilla-extract and get rid of visual button bug

Migrate Video component to vanilla-extract

---

apps/store/src/services/storyblok/storyblok.serverOnly.ts

Update storyblok cacheVersion management to match latest documentation

---

apps/store/src/app/[locale]/NavigationTracker.tsx
apps/store/src/app/[locale]/layout.tsx
apps/store/src/services/Tracking/TrackingContext.tsx

- Support page view tracking in app router
- Report app init event in app router

Report app init and page views in app router

---

apps/store/public/locales/en/memberArea.json
apps/store/public/locales/sv-se/memberArea.json
apps/store/src/features/memberArea/pages/LoginPage.tsx

Add missing translations for member login page

Add missing translations for member login page

---

apps/store/src/blocks/ProductPillowsBlock/ProductPillowBlock.tsx
apps/store/src/components/ProductPillow/ProductPillow.tsx

Add priority setting to ProductPillowBlock to set priority loading on pillow image
Performance

Add priority setting to ProductPillowBlock

---

apps/store/src/blocks/HeaderBlock.tsx
apps/store/src/components/Header/Header.css.ts
apps/store/src/components/Header/Header.stories.tsx
apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx

Improve INP for opening `TopMenuMobile`
1. Modal and header renders
2. Menu content renders
Also replaced menu triggers with standard Button component, this simplifies styling
This leads to ~2x better INP on our top slow interaction for mobile users

Optimize UI update delay when opening TopMenuMobile

---

apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.css.ts
apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx

Subj
One less emotion component

Convert TopMenuMobile styles to vanilla-extract

---

apps/store/src/components/FullscreenDialog/FullscreenDialog.css.ts
apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx

Subj.
Made this as performance experiment. No measurable difference where I measured, but still nice to have

Conver FullscreenDialog styles to vanilla-extract

---

apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx

Only include a self-referring hreflang if there is an alternate page, which is controlled in Storyblok.
https://www.notion.so/hedviginsurance/Remove-self-referring-hreflang-if-only-one-version-of-the-page-exists-448cb3b2e885490d9a3815e4c07e1c84

[RND-720] - Remove self-referring hreflang if only one version of the page exists

---

apps/store/src/features/widget/ProductItem.tsx
apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx

* Make perils block aware of tier selection
* Code scout: lokalise a missed out copy
https://github.com/HedvigInsurance/racoon/assets/19200662/44fbc264-e06d-4eed-a11f-c7b9787dc0a3

GEN-2074 - fix(widget-sign): make perils aware of tier selection

---

apps/store/src/blocks/HeaderBlock.tsx

Simplify JSX of `ProductNavContainerBlock` by removing CSS switching between mobile and desktop variants and rendering only one that's actually used
- It was useless for responsiveness (since full menu is replaced with other version when switching between desktop and mobile)
- Simplifying JSX saves ~50% of time when rendering mobile menu content
Our `Header` implementation still looks overly complex, but one step at a time

Simplify TopMenu JSX by rendering only desktop or mobile items instead of all

---

apps/store/src/components/InputDay/InputDay.css.ts
apps/store/src/components/TierSelector/TierSelector.css.ts
apps/store/src/components/ToggleCard/ToggleCard.css.ts
apps/store/src/features/widget/ProductItem.css.ts
apps/store/src/features/widget/ProductItem.tsx
packages/ui/src/global.css.ts
packages/ui/src/theme/theme.css.ts
packages/ui/src/theme/theme.ts
packages/ui/src/theme/utils.ts
packages/ui/src/theme/vars.css.ts

Use component specific theme tokens instead of standalone variables.

tech: Use input component theme tokens

---

apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
apps/store/src/features/carDealership/carDealershipFixtures.ts
apps/store/src/pages/[locale]/checkout/index.tsx

Subj. Clean up mentions unused field that we're no longer using for few weeks

Remove last mentions of unused ShopSessionCustomer.authenticationStatus

---

apps/store/src/components/Banner/PageBannerTriggers.tsx
apps/store/src/components/CheckoutHeader/CheckoutHeader.helpers.ts
apps/store/src/features/bundleDiscount/bundleDiscount.ts
apps/store/src/features/carDealership/carDealershipFixtures.ts
apps/store/src/graphql/ShopSessionFragment.graphql
apps/store/src/pages/[locale]/checkout/index.tsx

Hide default "you have a discount code applied" banner if current code is a bundle discount

Remove default campaign banner if active campaign is a bundle discount

---

apps/store/public/locales/en/cart.json
apps/store/public/locales/sv-se/cart.json
apps/store/src/components/ShopBreakdown/DiscountFieldContainer.tsx
apps/store/src/features/bundleDiscount/BundleDiscountSummary.css.ts
apps/store/src/features/bundleDiscount/BundleDiscountSummary.tsx
packages/ui/src/theme/sprinkles.css.ts

Add bundle discount summary to cart and checkout if there's a bundle discount

Add bundle discount summary to cart and checkout pages

---

apps/store/public/locales/en/cart.json
apps/store/public/locales/en/purchase-form.json
apps/store/public/locales/sv-se/cart.json
apps/store/public/locales/sv-se/purchase-form.json
apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
apps/store/src/components/ShopBreakdown/DiscountFieldContainer.tsx
apps/store/src/features/bundleDiscount/BundleDiscountOfferTooltip.tsx
apps/store/src/features/bundleDiscount/BundleDiscountSummary.css.ts
apps/store/src/features/bundleDiscount/BundleDiscountSummary.tsx
apps/store/src/features/bundleDiscount/bundleDiscount.ts
apps/store/src/features/carDealership/PriceIntentCarTrialExtensionFragment.graphql
apps/store/src/graphql/PriceIntentFragment.graphql
apps/store/src/utils/PageLink.ts
packages/ui/src/theme/sprinkles.css.ts

Show bundle discount tooltip when presenting a price in price calculator if current product is eligible (not Accident)

Add bundle discount tooltip to OfferPresenter when priceIntent qualifies for bundle discount

---

apps/store/src/components/ComparisonTable/ComparisonTable.css.ts
apps/store/src/components/ComparisonTable/ComparisonTable.tsx
packages/ui/src/theme/theme.ts

* Migrate ComparisonTable styles to vanilla extract
First step towards new design

GEN-2069 - chore(ComparisonTable): migrate to vanilla extract

---

apps/store/src/blocks/ComparisonTableBlock.tsx
apps/store/src/components/ComparisonTable/ComparisonTable.css.ts
apps/store/src/components/ComparisonTable/ComparisonTable.helpers.tsx
apps/store/src/components/ComparisonTable/ComparisonTable.stories.tsx
apps/store/src/components/ComparisonTable/ComparisonTable.tsx
apps/store/src/components/ComparisonTable/ComparisonTable.types.ts
apps/store/src/components/ComparisonTable/DesktopComparisonTable.stories.tsx
apps/store/src/components/ComparisonTable/DesktopComparisonTable.tsx
apps/store/src/components/ComparisonTable/MobileComparisonTable.stories.tsx
apps/store/src/components/ComparisonTable/MobileComparisonTable.tsx
apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx
apps/store/src/components/ProductPage/PurchaseForm/ComparisonTableModal.tsx
apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx

* Updated Desktop comparison table UI/UX
https://github.com/HedvigInsurance/racoon/assets/19200662/6cc43b81-924e-4972-b693-9d5b1a6e9045
Part of Widget + Car project.

GEN-2069 - styles(desktop-comparison-table): updated designs for desktop comparison table

---

apps/store/src/components/ComparisonTable/ComparisonTable.css.ts
apps/store/src/components/ComparisonTable/ComparisonTable.tsx
apps/store/src/components/ComparisonTable/MobileComparisonTable.css.ts
apps/store/src/components/ComparisonTable/MobileComparisonTable.tsx

* Updated Mobile Comparison Table UI/UX
Part of Widget + Car project

GEN-2069 -styles(mobile-comparison-table): update design

---

apps/store/src/app/[locale]/layout.tsx
apps/store/src/app/i18n.ts

Load latest version of cookie banner in app router
Support cookie consent and tracking in app router

Add cookie banner to app router pages

---

apps/store/src/app/[locale]/AppTrackingTriggers.tsx
apps/store/src/app/[locale]/layout.tsx
apps/store/src/app/i18n.ts
apps/store/src/services/Tracking/Tracking.ts

Subj. Less confusing name, since the component is responsible for multiple events, not just navigation

Rename NavigationTracker -> AppTrackingTriggers to better reflect usage

---

apps/store/src/components/CookieConsent/CookieConsent.tsx

Omit loading OneTrust script after updated consent. 
https://github.com/HedvigInsurance/racoon/assets/6661511/557c4195-1203-48d8-b014-e5841042ce78
Skip loading unused script

Omit loading OneTrust script after updated consent

---

.github/renovate.json5

Subj. Don't update the package until it's fixed

Disable Renovate for storybook-addon-apollo-client

---

apps/store/src/features/memberArea/pages/LoginPage/LoginPage.css.ts
apps/store/src/features/memberArea/pages/LoginPage/LoginPage.tsx
apps/store/src/pages/[locale]/member/login.tsx

Fix height bug in loginpage and refactor to vanilla css

---

apps/store/src/app/[locale]/cms/[[...slug]]/page.tsx
apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
apps/store/src/utils/l10n/localeUtils.ts

1. When available add as alternate link with `hreflang="x-default"` to the Swedish version.
2. Only show self-referring alternate links when alternates are available
Improve multi-language SEO support

tech: [RND-738] Adjust document alternate links

---

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx

Simplify PurchaseForm structure
- Merge `Layout` with top-level `PurchaseForm`
- Pass cart notification callback as regular prop instead of using render prop pattern
- Cleaner code
- Potential for better performance thanks to not creating huge render function every time

PurchaseForm: inline Layout component into parent

---

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.css.ts
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx

Conver PurchaseForm styles to vanilla-extract

---

apps/store/src/app/[locale]/cms/[[...slug]]/ProductCmsPage.tsx
apps/store/src/app/[locale]/cms/[[...slug]]/page.tsx
apps/store/src/components/DebugDialog/DefaultDebugDialog.tsx
apps/store/src/components/ProductPage/ProductPage.tsx
apps/store/src/components/ProductPage/ProductPageDebugDialog.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx

Fix debug dialogs in app router for
- regular pages (was missing)
- product pages (was relying on context provided deeper in component tree)

Support debug dialogs in app router pages

---

apps/store/src/components/ProductPage/PurchaseForm/DeductibleSelector.tsx
apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
apps/store/src/components/ProductPage/PurchaseForm/ProductTierSelector.tsx
apps/store/src/features/widget/ProductItem.tsx
apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx
apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/select.tsx

Enable deductible selection for PET insurance in the widget

feature: Enable deductible selection for PET in widget

---

apps/store/public/locales/en/contractSwitchConfirmationForm.json
apps/store/public/locales/sv-se/contractSwitchConfirmationForm.json
apps/store/src/@types/i18next.d.ts
apps/store/src/app/[locale]/switcher/[token]/InsuranceSwitchExpirationDateForm.tsx
apps/store/src/app/[locale]/switcher/[token]/InsuranceSwitcherExpirationDateForm.css.ts
apps/store/src/app/[locale]/switcher/[token]/page.tsx
apps/store/src/app/[locale]/switcher/[token]/submitSwitchConfirmation.ts
apps/store/src/app/debugger/components/CreateSessionForm/CreateSessionForm.tsx
apps/store/src/app/i18n.ts
apps/store/src/app/types/formStateTypes.ts
apps/store/src/graphql/SwitchConfirmation.graphql
packages/eslint-config-custom/eslint-config-custom.cjs

Create a form where other insurance company can report the insurance expiry date and confirm termination.
Reduce switching manual work

feature: [Maker days 2024] Add company switch form

---

apps/store/src/components/BankIdDialog/BankIdDialog.stories.tsx

Found while code scouting. 
Stories needed to be wrapped in a ShopSessionProvider

Fix broken BankID story

---

apps/store/.storybook/decorators.tsx

Apply vanilla-extract theme classname to story previews.
Set theme tokens values

Tech: Use Vanilla-Extract theme classname in Storyblook

---

apps/store/src/services/storyblok/storyblok.rsc.ts

Explicitly specify cache policies for all Storyblok fetch requests
Preparing for default changes in Next 15: https://nextjs.org/blog/next-15-rc#caching-updates

Explicitly specify cache policy for all Storyblok fetch requests

---

apps/store/public/locales/dk/common.json
apps/store/public/locales/dk/cookieConsent.json
apps/store/public/locales/no/common.json
apps/store/public/locales/no/cookieConsent.json

Add DK and NO translations for cookie consent

---

apps/store/src/components/CheckoutPage/CheckoutPage.types.ts
apps/store/src/pages/[locale]/checkout/index.tsx

Fix crash when trying to use "Edit" button from checkout page. We were missing product metadata in page context, added it
Found in app router testing, but happens in current `main` too

Fix Edit offer interaction on checkout page

---

apps/store/src/components/ProductPage/PriceIntentContext.tsx
apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx

Trying to reduce complexity of adding offer to cart
- Remove form and local "redirect target" state, make submit a simple `onClick` handler instead
- Wait until transition to cart completes before cleaning up old price intent
- Less prop-drilling and indirection
Video below shows how "go to checkout" looks after these changes. Note that loading state sticks right until checkout page opens
<a href="https://app.graphite.dev/media/video/GLY3tSM85RFBvAf6lFNA/515b7d84-ac77-4bca-adb4-929be3f12c97.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/GLY3tSM85RFBvAf6lFNA/515b7d84-ac77-4bca-adb4-929be3f12c97.mov">Screen Recording 2024-05-31 at 11.39.01.mov</video>
This hopefully fixes …

Refactor addToCart and goToCheckout actions

---

apps/store/src/app/[locale]/cms/[[...slug]]/page.tsx

Fix alternate metadata for app router
- Remove trailing slashes
- Replace URL for /se

Port meta alternate fixes to app router

---

packages/ui/src/components/Alert/Alert.css.ts
packages/ui/src/components/Alert/Alert.stories.tsx
packages/ui/src/components/Alert/Alert.tsx
packages/ui/src/components/Button/Button.tsx
packages/ui/src/index.ts

Create a composable Alert component which supports different variants and icons.
To be used to create the InfoCard component with more flexibility with composition.

tech: Create Alert component

---

apps/store/src/components/InfoCard/InfoCard.tsx
packages/ui/src/index.ts

Build the InfoCard components on top of Alert.
Remove duplication and streamline common usecase.

tech: Use Alert in InfoCard

---

apps/store/src/components/GridLayout/GridLayout.constants.ts
apps/store/src/components/Header/Header.css.ts
apps/store/src/components/Header/Header.tsx

Update site max-width and adjust header content to it
We don't want the site to be too wide on larger screens and align with the new UI kit updates

Update max-width for site grid

---

apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx

See title
Reported by Peter, should be open by default

Set TierSelector defaultOpen to true in OfferPresenter

---

apps/store/experiment.json
apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx

Add A/B test for QuickAdd component with 50/50 weight
New A/B test setup

Setup A/B test for QuickAdd component

---

packages/ui/src/index.ts
packages/ui/src/patterns/index.ts
packages/ui/src/patterns/stack.ts
packages/ui/src/theme/patterns.ts
packages/ui/src/theme/sprinkles.css.ts

Added new utility functions (`stack`, `hStack`, `vStack`) to the theme patterns for managing flexbox layouts with ease.
- Created a new file `patterns.ts` in the `src/theme` directory.
- Added `stack`, `hStack`, `vStack` functions for flexbox layout configurations.
- Updated `sprinkles.css.ts` to include `gap` property in responsive properties.
To simplify the implementation of flexbox layouts in UI components by providing reusable utility functions.

tech: Add stack layout patterns

---

apps/store/src/blocks/HeaderBlock.tsx
apps/store/src/components/Header/Header.tsx
apps/store/src/components/Header/TopMenuDesktop/TopMenuDesktop.tsx

* Navigation menu logic code scout changes.
Took the opportunity while working with something else.

chore(TopMenu): code scout

---

apps/store/experiments/quickAdd.json
apps/store/src/services/Tracking/experiment.constants.ts
apps/store/src/services/Tracking/experiment.helpers.ts
apps/store/src/services/Tracking/experimentMiddleware.ts

- Refactor experiments into an object with `id` as key
- Better logging of assigned experiment

Refactor experiment config

---

apps/store/src/app/[locale]/AppTrackingTriggers.tsx
apps/store/src/appComponents/StoreLayout.tsx
apps/store/src/appComponents/providers/ShopSessionTrackingProvider.tsx
apps/store/src/services/Tracking/Tracking.ts
apps/store/src/services/Tracking/trackExperimentImpression.ts
apps/store/src/services/Tracking/useReportShopSessionExperiments.ts
apps/store/src/services/Tracking/useTracking.ts
apps/store/src/services/gtm.tsx

- Report whether shop session is eligible for bundle discounts
- Fix shopSession tracking context not being provided outside of product pages
Part of tracking bundle discount performance

Report shop_session_experiments event when we get the data from GraphQL

---

packages/ui/src/components/Button/Button.css.ts
packages/ui/src/theme/colors/colors.ts

Update button component with:
- Update colors (green button now have better contrast)
- Use semantic tokens for backgrounds
- Remove shadow on all buttons
The green swatches have a slight update but checked that all usage looked good. 
Updated design system

Update button component and theme colors to gollow new UI kit

---

apps/store/src/components/CartPage/CartPage.tsx
apps/store/src/components/ProductPage/PurchaseForm/DiscountTooltip/DiscountTooltip.tsx
apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
apps/store/src/features/bundleDiscount/BundleDiscountOfferTooltip.tsx
apps/store/src/services/Tracking/Tracking.ts

Report when we show bundle discount promotion to user
Part of bundle discount performance tracking

Report view_promotion for bundle discount for 1st and 2nd offers in price calculator and from cart page

---

apps/store/src/app/[locale]/StoryblokLayout.tsx
apps/store/src/app/not-found.tsx
apps/store/src/appComponents/StoreLayout.tsx

- Make store layout a server component
- Remove layout from default 404 page - it's generally unreachable (I had to disable middleware to test it) and keeping it simple reduces our HTML size ~15% for SE_APARTMENT_RENT page

Minor optimizations to store layout

---

apps/store/public/locales/en/common.json
apps/store/public/locales/sv-se/common.json
apps/store/src/components/StoryCarousel/StoryCarousel.css.ts
apps/store/src/components/StoryCarousel/StoryCarousel.stories.tsx
apps/store/src/components/StoryCarousel/StoryCarousel.tsx

* Added `StoryCarousel` component. It should work like an _Instagram_'s story component.
https://github.com/HedvigInsurance/racoon/assets/19200662/3e12cb28-4321-4d20-9563-c324eb7de64b
Part of Hedvig new designs project. [Figma file](https://www.figma.com/design/vylWsbAVqZTuG8fUEIf0zs/Tiers-%26-Addons?node-id=888-18580&t=JZ49xRvbJWCNrvQj-0)

GEN-2254 - feat(StoryCarousel): add StoryCarousel component

---

apps/store/src/components/CartNotification/CartToast.tsx
apps/store/src/components/CheckoutPage/CheckoutPage.tsx
apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts
apps/store/src/components/ProductItem/RemoveActionButton.tsx
apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx
apps/store/src/features/bundleDiscount/BundleDiscountCartSummary.tsx
apps/store/src/graphql/CartFragment.graphql
apps/store/src/graphql/ShopSessionFragment.graphql
apps/store/src/services/Tracking/Tracking.ts
apps/store/src/services/Tracking/adtraction.ts

Fix last GraphQL fragment that had duplicate `Fragment` suffix.  `CartFragmentFragment` was stupid

Rename CartFragmentFragment type to CartFragment

---

apps/store/src/components/ProductPage/PurchaseForm/PriceCalculatorDialog.css.ts
apps/store/src/components/ProductPage/PurchaseForm/PriceCalculatorDialog.tsx

Convert PurchaseFormDialog styles to vanilla-extract

---

apps/store/src/components/PriceCalculator/PriceCalculatorAccordionSection.css.ts
apps/store/src/components/PriceCalculator/PriceCalculatorAccordionSection.tsx

Subj. Clean up before future refactoring

Convert PriceCalculatorAccordionSection to vanilla-extract

---

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.stories.tsx

Add nextjs app config to PurchaseForm story

---

apps/store/src/features/widget/StartFlow.helpers.ts

Really small addition. Thought abound adding it while debugging other things

chore(widget): log when customer data gets updated

---

apps/store/src/components/CartPage/PageDebugDialog.tsx
apps/store/src/components/DebugDialog/DebugDialog.tsx
apps/store/src/components/DebugDialog/DebugShopSessionSection.tsx
apps/store/src/components/DebugDialog/DefaultDebugDialog.tsx
apps/store/src/components/PriceCalculator/FormGrid/FormGrid.tsx
apps/store/src/components/ProductPage/ProductPageDebugDialog.tsx

- Fix "missing title" warning for debug dialogs - because it distracts from real warnings
- Make debug dialog content use gap-based spacing and make it 1 step larger - it looks better

Add hidden title to DebugDialog and use gap-based spacing for content

---

apps/store/src/blocks/HeaderBlockNew/HeaderBlock.tsx
apps/store/src/components/HeaderNew/Header.constants.ts
apps/store/src/components/HeaderNew/Header.css.ts
apps/store/src/components/HeaderNew/Header.tsx
apps/store/src/components/HeaderNew/HeaderMenuMobile/HeaderMenuMobile.css.ts

- Update design for desktop menu
- Delete header.constants.ts and move values to css files
https://github.com/HedvigInsurance/racoon/assets/6661511/a5815644-e6ee-4d3d-9a91-da8f82212fa2
[Figma](https://www.figma.com/design/p1TEzLLVqJB9gKDNTDVGU4/Hedvig.com?m=dev&node-id=3-503)
Next step: 
- Mobile sub menu design
- First menu item should be a hamburger in desktop
Considering if we should change the schema in Storyblok to be less flexible (we rarely make updates to the menu with new sub menus) to make it easier to add custom behaviour and styles

Update desktop menu to new design

---

apps/store/src/components/CartNotification/CartToast.css.ts
apps/store/src/components/CartNotification/CartToast.tsx

Update design on CartToast and refactor to vanilla-extract

Update design on CartToast and refactor to vanilla-extract

---

apps/store/src/components/HeaderNew/HeaderMenuMobile/HeaderMenuMobile.tsx

Fix svg attributes warning

---

apps/store/src/app/[locale]/[[...slug]]/PriceCalculatorCmsPage.tsx
apps/store/src/app/[locale]/[[...slug]]/page.tsx
apps/store/src/services/storyblok/Storyblok.helpers.ts
apps/store/src/services/storyblok/storyblok.ts

Start new price calculator prototype by adding feature flag and placeholder `noindex` page

Add PRICE_CALCULATOR_PAGE feature flag and placeholder component

---

apps/store/src/utils/url.ts

Fix bug where product cards that had a folder link was missing

Fix bug where product cards that had a folder link was missing

---

apps/store/src/app/[locale]/[[...slug]]/PriceCalculatorCmsPage.tsx
apps/store/src/app/[locale]/[[...slug]]/page.tsx
apps/store/src/components/PriceCalculatorPage/PriceCalculatorPage.tsx
apps/store/src/components/PriceCalculatorPage/PurchaseFormNew.tsx
apps/store/src/services/PriceCalculator/data/SE_PET_DOG_NEW.ts

Happy path for new price calculator: filling the form
- Temporary layout of the page with sticky left panel
- Create new SE_PET_DOG purchase form with 2 sections - SSN and everything else
- Use `PriceLoader` to indicate wait period while price intent is being confirmed
- Show JSON dump of offers if any
- Start with offers step if price intent was already confirmed
TODO: Video

Fill form step for new price calculator

---

apps/store/src/components/PriceCalculatorPage/PriceCalculatorPage.tsx
apps/store/src/components/PriceCalculatorPage/PurchaseFormNew.tsx

Subj. Small change to reuse existing Offer Presenter. Should be replaced by new variant later

Integrate old offer presenter into new price calculator page

---

apps/store/src/components/PriceCalculatorPage/PriceCalculatorPage.tsx
apps/store/src/components/ProductPage/ProductPageDebugDialog.tsx

Add debug dialog to new Price Calculator page

---

apps/store/src/app/[locale]/new/checkout/page.tsx
apps/store/src/services/persister/app-router/AppRouterCookiePersister.ts

Added foundation for new checkout page which will be a merge between cart and checkout pages we have today.
First steps torwards the merge.

GEN-2432 - feat(checkout v2): added foundation for new checkout page (cart + checkout)

---

apps/store/src/components/PriceCalculatorPage/FormGridNew.css.ts
apps/store/src/components/PriceCalculatorPage/FormGridNew.tsx
apps/store/src/components/PriceCalculatorPage/InsuranceDataForm.tsx
apps/store/src/components/PriceCalculatorPage/PurchaseFormNew.tsx
apps/store/src/components/PriceCalculatorPage/SectionPreview.tsx
apps/store/src/components/PriceCalculatorPage/useConfirmPriceIntent.tsx
packages/ui/src/theme/sprinkles.css.ts

New, mostly independent implementation of edit step
We're only reusing `priceIntentAtoms` and `AutomaticField` from previous implementation, other things are either copied (`FormGridNew`) or newly written

New InsuranceDataForm for fillForm step

---

apps/store/src/features/priceCalculator/OfferPresenterNew.tsx
apps/store/src/features/priceCalculator/PurchaseFormNew.tsx

Subj. No changes to copied code to keep review simple

Copy OfferPresenter to features/priceCalculator/OfferPresenterNew

---

apps/store/src/components/ProductPage/PurchaseForm/DiscountTooltip/useDiscountTooltipProps.tsx
apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx
apps/store/src/features/priceCalculator/OfferPresenterNew.tsx
apps/store/src/features/priceCalculator/PurchaseFormNew.tsx

Modernize and simplify `OfferPresenterNew`
- Remove `Space` and `SpaceFlex` components, use `yStack` instead
- Remove floating "add to cart" block, we might not need it
- Extract `useDiscountTooltipProps` hook and reuse between old and new design
Makes it easier to apply new look and feel when we will have it

Simplify OfferPresenterNew

---

apps/store/src/blocks/HeaderBlockNew/ProductMenuBlock.tsx
apps/store/src/blocks/HeaderBlockNew/ProductNavContainerBlock.css.ts
apps/store/src/components/HeaderNew/NavigationLink/NavigationLink.css.ts

- Fix border-radius on navigation link

fix border-radius on navigation link

---

apps/store/src/features/priceCalculator/PriceCalculatorPage.tsx
apps/store/src/features/priceCalculator/priceTemplates/SE_PET_DOG_V2.ts

Update SE_PET_DOG_V2 template to match figma
- rename _NEW to _V2
- Separate dog info from generic info
- put gender after breed

Update new SE_PET_DOG template to match Figma

---

apps/store/src/components/HeaderNew/HeaderMenuMobile/HeaderMenuMobile.css.ts

Remove focus styling when opening mobile menu in mobile

Remove focus styling when opening menu in mobile

---

apps/store/src/components/TextField/TextField.css.ts
apps/store/src/components/TextField/TextField.stories.tsx
apps/store/src/components/TextField/TextField.tsx

Add medium size to TextField
Update UI kit

Add medium size to TextField

---

apps/store/src/features/priceCalculator/CardRadioGroup.css.ts
apps/store/src/features/priceCalculator/CardRadioGroup.tsx
apps/store/src/features/priceCalculator/DeductibleSelectorV2.tsx
apps/store/src/features/priceCalculator/OfferPresenterV2.tsx
apps/store/src/features/priceCalculator/PriceCalculatorPage.tsx
apps/store/src/features/priceCalculator/ProductTierSelectorV2.tsx
apps/store/src/features/priceCalculator/PurchaseFormV2.tsx
packages/ui/src/theme/sprinkles.css.ts

- Create new `CardRadioGroup` component as a base for tier and deductible selectors
- Implement first version of new selectors

Add CardRadioGroup and use it for new tier and deductible selectors

---

apps/store/src/blocks/HeaderBlockNew/ProductMenuBlock.tsx
apps/store/src/blocks/HeaderBlockNew/SubMenuBlock.tsx
apps/store/src/components/HeaderNew/HeaderMenuMobile/HeaderMenuMobile.tsx
apps/store/src/components/HeaderNew/NavigationLink/NavigationLink.css.ts
apps/store/src/components/HeaderNew/NavigationTrigger/NavigationTrigger.css.ts
apps/store/src/components/HeaderNew/NavigationTrigger/NavigationTrigger.tsx
apps/store/src/components/HeaderNew/NavigationTrigger/NavigationTriggerGeneralMenu.tsx
packages/ui/src/components/Button/Button.css.ts
packages/ui/src/components/Button/Button.tsx

- Use ButtonNextLink in NavigationTrigger
- Update text alignment in Button to be more visually centered according to new UI kit

Adjust Button spacing and use ButtonLink in menu

---

apps/store/src/components/Video/Video.tsx
packages/ui/src/components/Button/Button.tsx
packages/ui/src/index.ts
packages/ui/src/utils/visuallyHidden.css.ts

- Pass icons properly to Video control buttons
- Add `visuallyHidden` class to global css
- Add prop to pass hidden text to buttons for accesibility
Icons for the video controls were not passed as Icons so it got a slight offset.

Fix video control buttons and handle visually hidden label properly

---

apps/store/src/features/priceCalculator/EditSsnWarningContainer.tsx
apps/store/src/features/priceCalculator/InsuranceDataForm.tsx
apps/store/src/features/priceCalculator/PurchaseFormV2.tsx
apps/store/src/features/priceCalculator/SectionPreview.tsx
apps/store/src/features/priceCalculator/priceCalculatorAtoms.ts

Integrate change SSN warning into Price Calculator page
Went with simpler solution of full page reload and commented why

<Are you sure to change SSN> warning dialog for Price Calculator Page

---

apps/store/src/components/ProductPage/PurchaseForm/ProductHero/ProductHero.tsx
apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.tsx

Add product pillow to left panel of Price Calculator

Add product pillow to left panel of Price Calculator page

---

apps/store/src/app/[locale]/new/checkout/BonusOffer.tsx
apps/store/src/app/[locale]/new/checkout/CartEntries.tsx
apps/store/src/app/[locale]/new/checkout/page.tsx
apps/store/src/app/[locale]/new/checkout/styles.css.ts

* Addes offer recommendation to checkout v2 page
[Figma file](https://www.figma.com/design/p1TEzLLVqJB9gKDNTDVGU4/Hedvig.com?node-id=472-12230&t=yFgWz55AmO4Ug3ql-4)

GEN-2432 - feat(checkout v2): added offer recommendation

---

apps/store/src/components/HeaderNew/Header.css.ts
apps/store/src/components/HeaderNew/NavigationLink/NavigationLink.css.ts

- Adjusted padding styles to match page layout
- Fix focus styles on ProductNavigationLink, it got unwanted focus styles when clicking the item
https://github.com/user-attachments/assets/ca4c7641-142b-4276-a4fd-dc46c98aa09a
https://github.com/user-attachments/assets/59aced56-e057-466b-8498-5e9a3636b3fb

Fix header menu width alignment and padding

---

apps/store/public/locales/en/cart.json
apps/store/public/locales/sv-se/cart.json
apps/store/src/components/QuickAdd/ProductUsp.tsx
apps/store/src/components/QuickAdd/QuickAddBundleView.stories.tsx
apps/store/src/components/QuickAdd/QuickAddEditableView.tsx
apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx

Added description to accident cross-sell offer
It gives more context when viewed alongside car or pet insurance

Add description to Accident Quick Offer

---

apps/store/src/app/[locale]/new/checkout/CheckoutForm.css.ts
apps/store/src/app/[locale]/new/checkout/CheckoutForm.tsx
apps/store/src/app/[locale]/new/checkout/CheckoutPage.constants.ts
apps/store/src/app/[locale]/new/checkout/CheckoutPage.helpers.ts
apps/store/src/app/[locale]/new/checkout/page.tsx
apps/store/src/utils/PageLink.ts

* Added checkout sign form to new checkout page
[Figma file](https://www.figma.com/design/p1TEzLLVqJB9gKDNTDVGU4/Hedvig.com?node-id=472-12230&t=yFgWz55AmO4Ug3ql-4)

GEN-2432 - feat(checkout v2): added checkout form

---

apps/store/src/app/[locale]/[[...slug]]/ProductCmsPageV2.tsx
apps/store/src/app/[locale]/[[...slug]]/page.tsx
apps/store/src/blocks/ProductPageBlockV2.tsx
apps/store/src/components/ProductPage/getProductPageData.tsx
apps/store/src/services/storyblok/Storyblok.helpers.ts
apps/store/src/services/storyblok/commonStoryblokComponents.ts
apps/store/src/services/storyblok/storyblok.ts

Create new Storyblok content type for ProductPage V2

Create new Storyblok content type for ProductPage V2

---

apps/store/src/app/[locale]/new/checkout/CheckoutPage.helpers.ts
apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/CheckoutPaymentTrustlyPage.constants.ts
apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/CheckoutPaymentTrustlyPage.css.ts
apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/CheckoutPaymentTrustlyPage.tsx
apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/page.tsx
apps/store/src/services/trustly/TrustlyIframe.tsx
apps/store/src/utils/PageLink.ts

Based on [design](https://www.figma.com/design/p1TEzLLVqJB9gKDNTDVGU4/Hedvig.com?node-id=470-2211&t=yFgWz55AmO4Ug3ql-4):
[Figma file](https://www.figma.com/design/p1TEzLLVqJB9gKDNTDVGU4/Hedvig.com?node-id=472-12230&t=yFgWz55AmO4Ug3ql-4)

GEN-2432 - feat(checkout v2): added payment page

---

apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/CheckoutPaymentTrustlyPage.css.ts
apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/CheckoutPaymentTrustlyPage.tsx
apps/store/src/services/trustly/TrustlyIframe.tsx

GEN-2432 - styles(TrustlyIframe): minor changes on checkoutv2 connect payment page

---

apps/store/src/services/logger/client.ts

Hopefully fix warning about multiple initialization of Datadog browser SDK
*Upd* - did not help, our problem is elsewhere and is related to dynamic imports from NextJs server-side. I still think this is marginally useful refactoring and would rather merge it
- Make sure we don't init several times with Datadog API instead of React state which may get thrown away with unmounting app component
- If we do try to init multiple times, pass a flag to ignore this. Datadog handles it correctly inside anyway

Silence Datadog error about multiple intializations

---

apps/store/src/features/priceCalculator/priceTemplates/SE_APARTMENT_STUDENT_V2.ts

- Price Calculator page template for Apartment Student
- Also, published CMS page (https://hedvig-dot-com-git-07-22-addseapartmentstudentv2p-8916dd-hedvig.vercel.app/se-en/insurances/home-insurance/student-price-calculator)
Configuration change was enough. Even interacts in expected way with "use registration address" field

Add SE_APARTMENT_STUDENT_V2 price template

---

apps/store/public/locales/en/purchase-form.json
apps/store/public/locales/sv-se/purchase-form.json
apps/store/src/components/PriceCalculator/CarRegistrationField.tsx
apps/store/src/features/priceCalculator/FormGridNew.tsx
apps/store/src/features/priceCalculator/InsuranceDataForm.tsx
apps/store/src/features/priceCalculator/priceTemplates/SE_CAR_V2.ts
apps/store/src/services/PriceCalculator/formFragments.ts

- Add Car price template and CMS page
- Fix Registration Number field not showing previous value when going back to edit form section

Add SE_CAR_V2 price calculator template

---

apps/store/src/features/priceCalculator/InsuranceDataForm.tsx

Integrate priceIntent.warning support into Price Calculator page

Show priceIntent.warning in Price Calculator page

---

apps/store/src/components/ButtonNextLink.tsx
apps/store/src/components/HeaderNew/HeaderMenuMobile/HeaderMenuMobile.tsx

Fix warnings from new header menu
- missing dialog a11y props
- missing forwardRef on ButtonNextLink

Fix warnings from new header menu (accessibility and missing forwardRef)

---

apps/store/src/features/priceCalculator/InsuranceDataForm.css.ts
apps/store/src/features/priceCalculator/InsuranceDataForm.tsx

Add personal data / GDPR notice before calculating a price in Price Calculator page

Add personal data notice to Price Calculator page

---

apps/store/src/components/TextLink/TextLink.css.ts
apps/store/src/components/TextLink/TextLink.stories.tsx
apps/store/src/components/TextLink/TextLink.tsx
apps/store/src/features/priceCalculator/InsuranceDataForm.tsx

Add `TextLink` component and Storybook for it
We're consistently reimplementing it as one-off styles in different places, it's better to have reusable component

TextLink component

---

apps/store/src/app/[locale]/new/checkout/CartEntries.tsx
apps/store/src/app/[locale]/new/checkout/CheckoutForm.tsx
apps/store/src/app/[locale]/new/checkout/CheckoutPage.constants.ts
apps/store/src/app/[locale]/new/checkout/CheckoutPage.helpers.ts
apps/store/src/utils/Features.ts
apps/store/src/utils/PageLink.ts

* Make new checkout page available under a feature flag
* fix: Enable default expanding product item cards via URL (as we already do today)

GEN-2432 - chore(checkout-v2): hide it under a feature flag

---

apps/store/src/features/priceCalculator/CardRadioGroup.css.ts
apps/store/src/features/priceCalculator/CardRadioGroup.tsx
apps/store/src/features/priceCalculator/DeductibleSelectorV2.css.ts
apps/store/src/features/priceCalculator/DeductibleSelectorV2.tsx
apps/store/src/features/priceCalculator/ProductTierSelectorV2.tsx
apps/store/src/features/priceCalculator/RadioIndicatorIcon.tsx

Apply intended design to deductible selector in Price Calculator page
- Add radio indicator
- Use smaller gaps and front size

Apply new deisgn to TierSelectorV2

---

apps/store/src/app/[locale]/new/checkout/CheckoutForm.tsx

* Add an alternative solution for transitioning between `BankIdDialog` success state and _CheckoutPage_.
`router` function from `next/navigation` package doesn't return a `Promise` as its counterpart from `next/router` does. That causes some issues with orchestrating the closing of `BankidDialog` at the correct time:
https://github.com/user-attachments/assets/f80160e2-cfdc-4ff3-8f9a-8a7ada5a6781
There's an open [discussion](https://github.com/vercel/next.js/discussions/41934#discussioncomment-8996669) about some limitations of `next/navigation` `useRouter` vs `next/router` `useRouter`. `router` from `next/navigation` package doesn't expose events as the old implementation does and `push` method doesn't return a `Promise` that we can `await` for in order to close `BankidDialog` at the …

GEN-2432 -fix(checkout-v2): make sure "signed" bank id dialog disappears after redirecting to new URL

---

apps/store/src/features/priceCalculator/OfferPresenterV2.tsx

First version of offer summary in Price Calculator Page
- Split tier and deductible selector from offer summary
- Planned next steps
Limitations
- "Show details" is a placeholder, there's no details inside
- Price and discount still use old design

Extract OfferSummary component inside OfferPresenterV2 and start implementing new design for it

---

apps/store/src/features/priceCalculator/OfferPresenterV2.tsx
apps/store/src/features/priceCalculator/OfferPriceDetails.tsx

Add discount code input to `OfferSummary` if campaigns are enabled

Add discount field to OfferSummary

---

apps/store/src/components/InputRadio/InputRadio.css.ts
apps/store/src/components/InputRadio/InputRadio.tsx
apps/store/src/features/priceCalculator/CardRadioGroup.css.ts
apps/store/src/features/priceCalculator/CardRadioGroup.tsx
apps/store/src/features/priceCalculator/RadioIndicatorIcon.css.ts
apps/store/src/features/priceCalculator/RadioIndicatorIcon.tsx
packages/ui/src/icons/Root.tsx

* InputRadio: migrate to vanilla extract CSS.
Input radio [redesign](https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=15719-7408&t=eLRSUCHpUg8O8uWx-4)

GEN-2463 - styles(InputRadio): migrate to vanilla extract css

---

apps/store/src/components/ProductPage/PurchaseForm/priceIntentAtoms.ts

Handle the case where we add accident bonus offer to cart then use "Edit" button to open it in price calculator
Bonus offer originally does not have `priceIntentId`, so we need to create price intent for it.
Old edit flow did it every time we edited a cart item, leading to more priceIntents being created than neccessary

Support editing bonus offers in Price Calculator page

---

apps/store/src/blocks/ModalBlock.tsx
apps/store/src/components/ProductCard/ProductCard.tsx
apps/store/src/components/ProductData/ProductData.graphql
apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
apps/store/src/components/SelectInsuranceGrid/SelectInsuranceGrid.stories.tsx
apps/store/src/components/SelectInsuranceGrid/SelectInsuranceGrid.tsx
apps/store/src/graphql/ProductMetadata.graphql

"See your price" links now point to new price calculator page if feature flag is enabled and link is configured in product metadata
Affected places
- "Open price calculator" on product page
- "See your price" in product grid
- "Select product" dialog that opens when you click "see your price" on category

Point <See your price> links to Price Calculator page when feature flag is enabled

---

apps/store/src/features/carDealership/CarBuyerValidationPage.tsx

* Car buyer validation tool: changed default selected tier
Requested [here](https://hedviginsurance.slack.com/archives/C0481RNNR8V/p1723112446732339)

chore(car-buyer-validation-tool): change default default selected tier option

---

apps/store/src/components/Combobox/Combobox.css.ts
apps/store/src/components/Combobox/Combobox.stories.tsx
apps/store/src/components/Combobox/Combobox.tsx

* Combobox: migrate styles to vanilla extract CSS.
First step towards breed selector [redesign](https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=15404-12523).

GEN-2470 - styles(Combobox): migrate to vanilla extract css

---

apps/store/src/components/Combobox/Combobox.css.ts
apps/store/src/components/Combobox/Combobox.tsx

* Add border styles and other minor changes.
https://github.com/user-attachments/assets/2e430be7-26f0-4d68-9d90-9d22f3810209
Combobox redesign

GEN-2470 - styles(combobox): add border styles for combobox

---

apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx

Remove A/B test for QuickAdd component
We concluded we should go with variant 0

Remove A/b test for QuickAdd component

---

apps/store/src/app/[locale]/new/checkout/CheckoutDebugDialog.tsx
apps/store/src/app/[locale]/new/checkout/CheckoutPage.tsx

* Include default debug dialog (that one that shows session information) for app router based checkout page.
Forgot to include that while implementing app router based checkout page.

GEN-2432 - chore(checkout-v2): added default debug dialog

---

apps/store/src/components/TextField/TextField.css.ts

- TextField: remove "jumping" when adding "focused" borders to TextField

styles(TextField): avoid jumps while adding "focused" borders

---

apps/store/src/components/Combobox/Combobox.css.ts
apps/store/src/components/Combobox/Combobox.stories.tsx
apps/store/src/components/Combobox/Combobox.tsx
apps/store/src/components/PriceCalculator/PetCatBreedsField.tsx
apps/store/src/components/PriceCalculator/PetDogBreedsField.tsx

* Combobox: added support for floating label
https://github.com/user-attachments/assets/a81ee57f-7fc4-43d1-8ec9-dbb6f8d0209e
Necessary for new price calculator page design.

GEN-2470 - styles(combobox): added floating label support

---

apps/store/src/components/Combobox/Combobox.tsx
apps/store/src/components/PriceCalculator/MixedBreedPicker/MixedBreedPicker.css.ts
apps/store/src/components/PriceCalculator/MixedBreedPicker/MixedBreedPicker.stories.tsx
apps/store/src/components/PriceCalculator/MixedBreedPicker/MixedBreedPicker.tsx
apps/store/src/components/PriceCalculator/PetDogBreedsField.tsx

MixedBreedPicker: migrate styles to vanilla extract css

GEN-2470 - refact(MixedBreedPicker): migrate to vanilla extract css

---

apps/store/public/locales/en/cart.json
apps/store/public/locales/sv-se/cart.json

This PR was created automatically by the "Download translations from Lokalise" action.

Update / New translations from Lokalise

---

apps/store/src/app/[locale]/[[...slug]]/page.tsx

Remove terms-hub workaround since original issue is solved now

---

apps/store/src/components/Perils/Perils.css.ts
apps/store/src/components/Perils/Perils.tsx

Sub.j Straightforward conversion

Convert Perils styles to vanilla-extract

---

apps/store/src/features/memberArea/InsuranceSection/InsuranceDetailsSection.css.ts
apps/store/src/features/memberArea/InsuranceSection/InsuranceSection.constants.ts
apps/store/src/features/memberArea/InsuranceSection/InsurancesSection.tsx
apps/store/src/features/memberArea/PaymentsSection/PaymentsSection.css.ts
apps/store/src/features/memberArea/components/MemberAreaLayout.css.ts
apps/store/src/features/memberArea/components/MemberAreaLayout.tsx
packages/ui/src/theme/media.ts
packages/ui/src/theme/typography.ts
packages/ui/src/theme/utilTypes.ts

- Subj.
- Also, moved `CONTENT_WIDTH` constant from InsuranceSection to layout, makes more sense
- Extracted `responsiveStyles` utility to make writing such styles less verbose

Convert MemberAreaLayout to vanilla-extract

---

apps/store/src/app/[locale]/[[...slug]]/ProductCmsPageV2.tsx

Added DefaultDebugDialog to ProductPage

Add debug dialog to ProductPage

---

apps/store/src/app/[locale]/confirmation/[shopSessionId]/page.tsx

Subj.
Generate less GraphQL errors by avoiding making auth required queries when auth tokens are not present.

chore(confirmation page): only make auth required requests when auth tokens is present

---

apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx

* Fetch `productData` for widget calculate price page as we do for sign page.
The issue happens because during the flow we initialize productDataAtom without variants data for calculate price page and, while sign page fetches productData containing variants, productDataAtom never gets initialized with variants again. The issue goes away if we refresh the page because in that case productDataAtom is proper initialized. [Before](https://github.com/HedvigInsurance/racoon/pull/4592/files#diff-651670b13cc543b64b1e9754b49c434b56d73c21fa42e89788daa637b23cc225L45-L48) we're using `dangerouslyForceHydrate` option from Jotai so that's why it was working.
This solves it but it's still fragile as even though we're talking about different pages, the fact they share the same data dependency and that …

RND-855 - fix(widget quote creation): proper initialize product data atom for sign page

---

apps/store/src/blocks/QuickPurchaseBlock.tsx
apps/store/src/components/QuickPurchaseV2/QuickPurchase.tsx
apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/ProductSelector.tsx
apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/QuickPurchaseForm.tsx

Add option in Storyblok to make first option in dropdown pre selected

Add option to make first product pre selected in dropdown

---

apps/store/public/locales/en/purchase-form.json
apps/store/public/locales/sv-se/purchase-form.json
apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.css.ts
apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.tsx
apps/store/src/features/priceCalculator/ProductHeroV2.css.ts
apps/store/src/features/priceCalculator/ProductHeroV2.tsx
packages/ui/src/icons/ArrowIcon.tsx

- Make Price Calculator page layout responsive and match Figma for initial state (offer presenter still needs work)
- Convert all inline styles into vanilla-extract styles in `PriceCalculatorCmsPage`
- Simplify data fetching by moving providers higher in tree and removing parallel fetching of product data
Responsiveness in action
<a href="https://app.graphite.dev/media/video/GLY3tSM85RFBvAf6lFNA/46ef9514-958a-4304-98c3-d7aebd15d57b.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/GLY3tSM85RFBvAf6lFNA/46ef9514-958a-4304-98c3-d7aebd15d57b.mov">Screen Recording 2024-08-21 at 13.48.24.mov</video>

Responsive design for price calculator page

---

apps/store/src/app/[locale]/[[...slug]]/page.tsx

Disable building CMS pages in app router based on env.SKIP_BUILD_STATIC_GENERATION

---

apps/store/src/appComponents/StoreLayout.tsx
apps/store/src/appComponents/TranslationKeysDebugger.tsx
apps/store/src/utils/l10n/useDebugTranslationKeys.ts

Enable translation keys debugger for app router

chore(translation keys debugger): enable it for app router

---

apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/QuickPurchaseForm.stories.tsx

Add storybook story for QuickPurchaseV2

---

apps/store/src/app/[locale]/new/checkout/page.tsx

- Remove new checkout page from indexing

fix(checkoutv2): don't index the checkout page

---

apps/store/src/app/debugger/terms/[productName]/page.tsx
apps/store/src/components/ProductData/ProductData.graphql
apps/store/src/mocks/productData.ts

Show `termsVersion` in terms-hub debugger since it does not match document name from PCMS and cannot be seen in any other way

Add termsVersion to terms debugger

---

apps/store/src/features/bundleDiscount/useBundleDiscountExtraProductLinks.ts

Subj, just 2 lines of text has changed

Tiny: slightly shorten bundle discount subtitles for Cat and Pet

---

apps/store/public/robots.txt

- Added a couple more entries for widget in `robots.txt` file
[Requested](https://hedviginsurance.slack.com/archives/C041SD67G82/p1724754115106129?thread_ts=1724744544.490779&cid=C041SD67G82) by Peter

chore(robots): added two more entries for widget routes

---

apps/store/src/components/ProductPage/PurchaseForm/priceIntentAtoms.ts
apps/store/src/features/priceCalculator/BonusOfferPresenter.tsx
apps/store/src/features/priceCalculator/OfferPresenterV2.tsx
apps/store/src/features/priceCalculator/PurchaseFormV2.tsx
apps/store/src/features/priceCalculator/priceCalculatorAtoms.ts

* Added foundation for bonus offer for the new price calculator page.
First step towards supporting bonus offer.

GEN-2430 - feat(price-calculator-page): added foundation for bonus offers

---

apps/store/src/components/QuickAdd/ProductRecommendations.graphql
apps/store/src/features/priceCalculator/BonusOfferPresenter.css.ts
apps/store/src/features/priceCalculator/BonusOfferPresenter.tsx
apps/store/src/features/priceCalculator/OfferPresenterV2.tsx
apps/store/src/features/priceCalculator/ProductCardSmall.tsx

- Added basic recommendation card. Right now it only links to product page. More to come.
Price calculator v2 bonus offer feature

GEN-2430 - feat(priceCalculatorv2): added basic recommendation card

---

apps/store/src/features/bundleDiscount/useBundleDiscountExtraProductLinks.ts

Subj. Make texts smaller as requested by Peter - they currently overflow on mobile

Shorten bundle discount subtitles once more

---

apps/store/src/features/bundleDiscount/bundleDiscount.ts

Subj. We're testing 15% off during September

Change bundle discount to 15% to match configuration change in storefront

---

packages/ui/package.json
packages/ui/src/components/Tabs/Tabs.css.ts
packages/ui/src/components/Tabs/Tabs.stories.tsx
packages/ui/src/components/Tabs/Tabs.tsx
packages/ui/src/index.ts
packages/ui/src/theme/colors/colors.ts
yarn.lock

- Add Tabs component to UI kit according to updated design
https://github.com/user-attachments/assets/a705f3ae-5764-4327-aa1d-03a1bd0e6a13
New design and better reuse

Create Tabs component in UI kit

---

apps/store/src/blocks/PerilsTableBlock.tsx
apps/store/src/components/Perils/PerilsTable/PerilsTable.tsx
apps/store/src/components/Perils/PerilsTable/PerilsTabs.tsx
apps/store/src/services/storyblok/commonStoryblokComponents.ts

- Create PerilsTableBlock to be used in new ProductPage
- Create PerilsTabs component that will be used on smaller screens 
https://github.com/user-attachments/assets/59d5b587-9078-439b-bc06-d832aee9a977
ProductPage v2

Create PerilsTableBlock and PerilsTabs component

---

apps/store/src/components/Perils/Perils.tsx
apps/store/src/components/Perils/PerilsTable/PerilsTable.tsx
apps/store/src/components/Perils/PerilsTable/PerilsTableDesktop.tsx
apps/store/src/components/Perils/PerilsTable/PerilsTabs.tsx

- Create PerilsTableDesktop component
- Refactor PerilsTable, create object with variants perils and missing perils to be used in child components
https://github.com/user-attachments/assets/b92eab91-4421-4a2a-96a6-df19b35106f0
New PerilsTable block

Create PerilsTableDesktop component

---

apps/store/src/components/ComparisonTable/ComparisonTable.css.ts
apps/store/src/components/ComparisonTable/ComparisonTable.tsx
apps/store/src/components/ComparisonTable/ComparisonTable.types.ts
apps/store/src/components/ComparisonTable/DesktopComparisonTable.tsx
apps/store/src/components/Perils/Perils.tsx
apps/store/src/components/Perils/PerilsTable/PerilsTable.tsx
apps/store/src/components/Perils/PerilsTable/PerilsTableDesktop/PerilsTableDesktop.css.ts
apps/store/src/components/Perils/PerilsTable/PerilsTableDesktop/PerilsTableDesktop.tsx
packages/ui/src/theme/colors/colors.ts

- Add support for showing Peril color next to title
- Move accordion arrow to the right of title
https://github.com/user-attachments/assets/f545f9d6-4e47-4166-b0e9-17f7f57fda1d

Update design for DesktopComparisonTable

---

apps/store/src/blocks/PerilsTableBlock.tsx
apps/store/src/components/ComparisonTable/ComparisonTable.css.ts
apps/store/src/components/ComparisonTable/ComparisonTable.tsx
apps/store/src/components/ComparisonTable/DesktopComparisonTable.tsx
apps/store/src/components/Perils/PerilsTable/PerilsTable.tsx
apps/store/src/components/Perils/PerilsTable/PerilsTableDesktop/PerilsTableDesktop.tsx
apps/store/src/components/Perils/PerilsTable/PerilsTabs.tsx

Add title and description to PerilsTable

---

apps/store/src/app/debugger/seb-leads/CreateWidgetSessionForm.tsx
apps/store/src/app/debugger/seb-leads/constants.ts
apps/store/src/app/debugger/seb-leads/createWidgetSession.ts
apps/store/src/app/debugger/seb-leads/page.tsx
apps/store/src/app/debugger/seb-leads/storefrontLeadsApiRequest.ts
apps/store/src/utils/getEnvOrThrow.ts

- Debugger tool for creating widget session from SEB lead
- Extracted `storefrontLeadsApiRequest ` utility to reduce `fetch` boilerplate

SEB lead debugger - create widget session

---

apps/store/next-csp.config.mjs
apps/store/package.json
apps/store/public/mockServiceWorker.js
apps/store/src/appComponents/StoreLayout.tsx
yarn.lock

Add [Vercel Speed Insights](https://vercel.com/docs/speed-insights) to evaluate how useful it is for us. Runtime overhead is very small compared to Datadog, 4KB script

Add Vercel Speed Insights

---

apps/store/public/locales/en/common.json
apps/store/public/locales/sv-se/common.json
apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/QuickPurchaseForm.tsx
apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/SsnField/SsnField.css.ts
apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/SsnField/SsnField.tsx
apps/store/src/components/TextField/TextField.css.ts

Add edit state for QuickPurchaseFormV2
https://github.com/user-attachments/assets/39ac8736-ae48-4d28-a3b8-8dfddad08b9e
Let's see if we should add some loading state on for the input on page load and when submitting
Being able to change SSN on ProductPage

Add edit state for QuickPurchaseFormV2

---

apps/store/public/mockServiceWorker.js
apps/store/src/components/QuickAdd/ProductRecommendations.graphql
apps/store/src/features/priceCalculator/BonusOfferPresenter.tsx

- Added basic recommendation card designs
Obseve tho that "See your price" links are not working due an issue related with 'priceIntentAtoms'.
Gonna be addressing that in the next PR
Bonus offer.

GEN-2430 - styles(bonnus-offer): added basic recommendation card

---

apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/SsnField/SsnField.tsx

Forgot to add the input value to be able to submit the form

fix: Add hidden input value to QuickPurchaseForm edit state

---

apps/store/src/services/apollo/productDataFetchOptions.ts

Subj. Going to see if it improved production speed metrics on rarely visited pages like `/se/partner/benify`

Increase product metadata TTL in production from 10m to 12h

---

apps/store/src/app/debugger/seb-leads/GenerateAndSendOfferButton.tsx
apps/store/src/app/debugger/seb-leads/createSebLead.tsx
apps/store/src/app/debugger/seb-leads/generateAndSendOffer.ts
apps/store/src/app/debugger/seb-leads/page.tsx

- Added button to generate and send offer for seb leads
I have it is super ugly but works

debugger-tool/generate and send offer from seb lead

---

apps/store/next.config.mjs

Subj. Should speed up build process a little
We used to have this setting as a fix to failing build. Looks like it's no longer needed

Remove transpilePackages: i18next, builds without it now

---

apps/store/next.config.mjs
apps/store/src/components/LogoHomeLink.css.ts
apps/store/src/components/LogoHomeLink.tsx

Convert LogoHomeLink to vanilla-extract and remove prefetch

---

apps/store/next.config.mjs

Set experimental.webpackBuildWorker=true to reduce build memory consumption ~10x

---

apps/store/next.config.mjs

Restore default settings for webpack infrastructure logs, there are no build errors now

---

packages/ui/src/components/Card/Card.css.ts
packages/ui/src/components/Card/Card.stories.tsx
packages/ui/src/components/Card/Card.tsx

Add the ability to have aside content in Card components for buttons, badges or any other components.
Align with design requirements.

tech: Add Card aside

---

packages/eslint-config-custom/eslint-config-custom.cjs
packages/ui/package.json
packages/ui/src/components/Tooltip.tsx
packages/ui/src/components/Tooltip/Tooltip.stories.tsx
packages/ui/src/components/Tooltip/Tooltip.tsx
packages/ui/src/index.ts
yarn.lock

Add a composable version of the Tooltip component in the `ui` package
- Works with composed components
- Needed for components in the `ui` package

tech: Add Tooltip UI component

---

packages/ui/src/components/Tooltip/Tooltip.css.ts
packages/ui/src/components/Tooltip/Tooltip.tsx

tech: Move Tooltip to vanilla-extract

---

packages/ui/src/components/Card/Card.css.ts
packages/ui/src/components/Card/Card.tsx
packages/ui/src/index.ts

- Export the card component from the `ui` package
- Fix a `z-index` issue with the Card aside
Enable using `Card` in the `store` app

tech: export Card component from UI

---

apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
apps/store/src/components/ConfirmationPage/fetchMemberPartnerData.ts
apps/store/src/utils/Features.ts

Subj. We can disable SAS eurobonus flow in backend if needed

Remove SAS_PARTNERSHIP feature flag, always enabled

---

apps/store/src/components/DetailsList/DetailsList.css.ts
apps/store/src/components/DetailsList/DetailsList.tsx

Create the `DetailsList` ui component
Building block for `ProductCard`

tech: Add DetailsList component

---

apps/store/src/components/DetailsList/DetailsList.css.ts
apps/store/src/components/DetailsList/DetailsList.tsx
packages/ui/src/components/Button/Button.css.ts
packages/ui/src/components/Button/Button.stories.tsx
packages/ui/src/components/Button/Button.tsx

Create an "outline" variant for the button component
Align with design

tech: Create Button outline variant

---

apps/store/src/components/ProductReviews/ProductAverageRating.tsx
apps/store/src/utils/Features.ts

Remove HIDE_REVIEWS_FROM_PRODUCT_AVERAGE_RATING feature flag, always enabled

---

apps/store/src/components/Price.tsx

tech: Update Price component to Vanilla-Extract

---

apps/store/src/components/ProductCard/ProductCard.stories.tsx

tech: ProductCard info variant

---

apps/store/public/locales/en/purchase-form.json
apps/store/public/locales/sv-se/purchase-form.json
apps/store/src/components/PriceCalculator/SsnSeSection.tsx
apps/store/src/features/priceCalculator/InsuranceDataForm.tsx
apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.css.ts
apps/store/src/features/priceCalculator/priceTemplates/SE_ACCIDENT_V2.ts
apps/store/src/features/priceCalculator/priceTemplates/SE_APARTMENT_BRF_V2.ts
apps/store/src/features/priceCalculator/priceTemplates/SE_APARTMENT_RENT_V2.ts
apps/store/src/features/priceCalculator/priceTemplates/SE_APARTMENT_STUDENT_V2.ts
apps/store/src/features/priceCalculator/priceTemplates/SE_CAR_V2.ts
apps/store/src/features/priceCalculator/priceTemplates/SE_HOUSE_V2.ts
apps/store/src/features/priceCalculator/priceTemplates/SE_PET_CAT_V2.ts
apps/store/src/features/priceCalculator/priceTemplates/SE_PET_DOG_V2.ts
apps/store/src/services/PriceCalculator/formFragments.ts

Centralizes SSN section for the new price calculator
Requested by [design](https://www.figma.com/design/p1TEzLLVqJB9gKDNTDVGU4/Hedvig.com?node-id=2063-30766&t=CpWfo7Eg4xhkEYIy-4)

GEN-2516 - styles(price-calculator-ssn-section): changed title and subtitle

---

apps/store/src/components/ProductCard/Discount/Discount.tsx
apps/store/src/components/ProductCard/ProductCard.stories.tsx

Subj
<a href="https://app.graphite.dev/media/video/RV4Oucd6mLf2QBBMAjRa/73e80b5b-91df-413d-a458-51083d63f9fb.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/RV4Oucd6mLf2QBBMAjRa/73e80b5b-91df-413d-a458-51083d63f9fb.mov">Screen Recording 2024-09-19 at 12.04.22.mov</video>

tech: Add ProductCard variant with discount code

---

apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/QuickPurchaseForm.css.ts
apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/QuickPurchaseForm.tsx

Add Sticky **See your price** button to ProductPageV2 for mobile
https://github.com/user-attachments/assets/d5efd6b0-7b1b-40d8-918d-5d51a929ea7a

Sticky QuickPurchase form

---

apps/store/src/app/[locale]/[[...slug]]/page.tsx
apps/store/src/blocks/FooterBlock/FooterBlock.tsx

Remove footer and breadcrumbs from price calc page
Updated design

Remove footer and breadcrumbs from price calc page

---

apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.css.ts

- Fix spacing and layout of product hero
- Update background color on calculator section
Updated design

Ajdust layout on ProductHero and update background color on calculator section

---

apps/store/src/app/debugger/seb-leads/CreateSebLeadsForm.tsx
apps/store/src/app/debugger/seb-leads/constants.ts
apps/store/src/app/debugger/seb-leads/createSebLead.tsx

add product multi select

---

apps/store/src/app/debugger/terms/versions/[termsVersion]/ProductVariant.graphql
apps/store/src/app/debugger/terms/versions/[termsVersion]/page.tsx
apps/store/src/components/Perils/Perils.tsx

Another debugger page for terms-hub, this one takes termsVersion as URL path segment, ex. `/debugger/terms/versions/SE_DOG_BASIC-20230330-HEDVIG-null`

TermsVersion debugger

---

apps/store/src/features/priceCalculator/ProductHeroV2.css.ts
apps/store/src/features/priceCalculator/ProductHeroV2.tsx

See title
https://github.com/user-attachments/assets/a445b03a-e765-4534-9b6b-71dd3c9da3c9
https://github.com/user-attachments/assets/237e24f4-e6b9-42a3-bf2b-c4cfc409019f

Display sub type in ProductHero for mobile and desktop

---

apps/store/src/components/InsuranceDocumentLink.tsx
apps/store/src/components/Perils/Perils.tsx
apps/store/src/components/ProductPage/ProductDocuments.tsx
apps/store/src/components/ProductReviews/ReviewsDialog.tsx
apps/store/src/graphql/InsuranceDocumentFragment.graphql
apps/store/src/mocks/productData.ts
apps/store/src/services/Tracking/Tracking.ts
apps/store/src/services/Tracking/useReportDeviceInfo.ts

Add new tracking events and link them to UI
- `expandPeril`
- `clickTermsAndConditions`
- `openProductReviews`
For now the only thing tracking does is logging events to browser console. Sending events to backend is to follow
Part of behavior-based pricing

Prototype new internal analytics events: clickTermsAndConditions, expandPeril, openProductReviews

---

packages/ui/src/components/Card/Card.css.ts

fix: Reduce card padding on mobile

---

apps/store/src/components/ProductCard/DetailsList/DetailsList.stories.tsx
apps/store/src/components/ProductCard/ProductCard.stories.tsx
apps/store/src/components/ProductCard/TotalPrice/TotalPrice.stories.tsx
apps/store/src/components/ProductCard/TotalPrice/TotalPrice.tsx

"Cherry pick" `TotalPrice` component from [here](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4793/tech-GEN-2609-Create-TotalPrice-component)
Gonna need something similar so it's nice to use the same components. I'm cherry picking it here so we don't get blocked by _new checkout_ release.

GEN-2651 - feat(TotalPrice): "cherry pick" TotalPrice component

---

apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.css.ts
apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.tsx
apps/store/src/features/priceCalculator/ProductHeroV2/StickyProductHeader/StickyProductHeader.css.ts
apps/store/src/features/priceCalculator/ProductHeroV2/StickyProductHeader/StickyProductHeader.tsx

Breakout StickyProductHeader to it's own component. No changes to component itself

Refactor StickyProductHeader

---

packages/ui/src/components/SupText/SupText.css.ts
packages/ui/src/components/SupText/SupText.tsx
packages/ui/src/components/Text/Text.tsx
packages/ui/src/index.ts

Creates a component for the `sup` element
Needed for product document type

tech: [GEN-2609] Create SubText component

---

apps/store/src/app/[locale]/checkout/components/CartItem/CartItem.tsx
apps/store/src/components/ProductCard/TotalPrice/TotalPrice.stories.tsx
apps/store/src/components/ProductCard/TotalPrice/TotalPrice.tsx

Create a component for the recurring product total pattern.

tech: [GEN-2609] Create TotalPrice component

---

apps/store/src/features/CartTotal/CartTotal.tsx
apps/store/src/features/CartTotal/hooks/useCartTotal.tsx

Get cart total price with discounts and provide it to `TotalPrice`.
Co-location

tech: [GEN-2609] Create CartTotal feature

---

apps/store/src/app/[locale]/checkout/CheckoutPage.css.ts
apps/store/src/components/ProductCard/Discount/Discount.css.ts
apps/store/src/components/ProductCard/Discount/Discount.tsx
apps/store/src/features/CartDiscount/CartDiscount.tsx
apps/store/src/features/CartDiscount/hooks/useDiscount.ts
apps/store/src/features/CartDiscount/hooks/useGetCodeExplanation.ts

Create a `CartDiscount` feature for adding, removing and displaying cart discounts.
Simplify cart campaign/discount management.

tech: [GEN-2609] Create Cart Discount feature

---

apps/store/src/app/[locale]/checkout/CheckoutPage.tsx
apps/store/src/app/[locale]/checkout/components/CartEntries.tsx
apps/store/src/app/[locale]/checkout/components/CartItem/CartItem.tsx
apps/store/src/app/[locale]/checkout/components/CheckoutForm/CheckoutForm.tsx
apps/store/src/app/[locale]/checkout/components/OrderBreakdown.tsx
apps/store/src/components/ProductCard/Discount/Discount.tsx
apps/store/src/features/CartDiscount/CartDiscount.tsx
apps/store/src/features/CartDiscount/CartDiscount.utils.ts
apps/store/src/features/CartDiscount/hooks/useCartDiscount.ts
apps/store/src/features/CrossSell/components/AccidentCrossSellForm.tsx
packages/ui/src/components/Badge/Badge.tsx
packages/ui/src/components/Card/Card.css.ts

Implement the new design for checkout order summary

feat: [GEN-2609] Checkout order summary

---

apps/store/src/app/[locale]/checkout/CheckoutPage.tsx
apps/store/src/app/[locale]/checkout/components/CartItem/CartItem.tsx
apps/store/src/features/CrossSell/CrossSell.tsx
apps/store/src/features/CrossSell/components/AccidentCrossSellForm.tsx
packages/ui/src/components/Badge/Badge.css.ts
packages/ui/src/components/Badge/Badge.tsx
packages/ui/src/components/Heading/Heading.css.ts
packages/ui/src/components/Heading/Heading.tsx

<a href="https://app.graphite.dev/media/video/RV4Oucd6mLf2QBBMAjRa/4a825363-c7fd-42a0-8547-f661a09dd56e.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/RV4Oucd6mLf2QBBMAjRa/4a825363-c7fd-42a0-8547-f661a09dd56e.mov">Screen Recording 2024-09-30 at 10.23.33.mov</video>

feat: [GEN-2609] Checkout style adjustments

---

apps/store/src/features/carDealership/ProductItemContractContainer.tsx

Use new card design for the car trial items.

feat: [GEN-2610] Update cart trial item design in confirmation page

---

apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.tsx

Speed up price animation, was a bit out of sync

fix: Adjust price animation

---

apps/store/src/components/Banner/Banner.css.ts
apps/store/src/components/Banner/Banner.stories.tsx

Subj.
Underline decoration was missing for banner links

styles(banner): added underline decoration for banner links

---

apps/store/public/locales/en/purchase-form.json
apps/store/public/locales/sv-se/purchase-form.json
apps/store/src/features/priceCalculator/CartToast.tsx

chore(cart-toast-notification): increase number of seconds it get's displayed to 5,5 seconds

---

apps/store/src/features/priceCalculator/InsuranceDataForm.tsx
apps/store/src/features/priceCalculator/OfferPresenterV2.tsx
apps/store/src/features/priceCalculator/SectionHeading.tsx

Add SectionHeading component
Reuse in purchase form

Add SectionHeading component

---

apps/store/src/features/priceCalculator/PriceCalculatorCmsPage/PriceCalculatorCmsPage.tsx

fix: pricetemplate path

---

packages/ui/src/icons/Root.css.ts
packages/ui/src/icons/Root.tsx

Add direction prop to Icon to make it easy to use icons like arrows with different directions

Add direction prop to Icon

---

apps/store/public/locales/en/purchase-form.json
apps/store/public/locales/sv-se/purchase-form.json
apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/InsuranceDataForm.tsx
apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/SectionNavigation.tsx

Add SectionNavigation component and remove preview of sections
- Consist of a back button and step indicator
Updated design with new section navigation

Add SectionNavigation component

---

apps/store/src/components/ProductPage/ProductDocuments.tsx

Fix a bug where we failed to report T&C click on single tier products

Fix reporting click on terms for single tier products

---

apps/store/src/features/priceCalculator/PurchaseFormV2/PurchaseSummary/PurchaseSummary.tsx

Small detail: lower case insurance name. E.g ~~"Add another Dog"~~ --> "Add another dog"

nit(new-price-calculator-add-another-item): lower case

---

apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/OfferPresenterV2.css.ts
apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/OfferPresenterV2.tsx

Adjust spacing in mobile and desktop
Match design

fix: update OfferPresenter layout

---

apps/store/src/features/priceCalculator/PurchaseFormV2/PurchaseSummary/PurchaseSummary.tsx

chore: updated copy used by "Price" label

chore(purchase-summary): updated "price" copy

---

apps/store/src/components/PriceCalculator/SsnSeSection.tsx

Layout was broken, revert change
Noticed by @guilhermespopolin 👑

hotfix: make sure SsnSection submit button is displayed correctly in current purchase form

---

apps/store/src/features/bundleDiscount/bundleDiscount.constants.ts
apps/store/src/features/bundleDiscount/components/BundleDiscountCartSummary.tsx
apps/store/src/features/priceCalculator/PurchaseFormV2/PurchaseSummary/PurchaseSummary.tsx
apps/store/src/utils/PageLink.ts

- Added localized links for "bundle discount" page
We have a english version as well no.

chore(bundle-discount-link): localize it

---

apps/store/src/features/priceCalculator/PriceCalculatorCmsPage/PriceCalculatorCmsPageContent/PriceCalculatorCmsPageContent.css.ts
apps/store/src/features/priceCalculator/PriceCalculatorCmsPage/PriceCalculatorCmsPageContent/PriceCalculatorCmsPageContent.tsx
apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.css.ts
apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.tsx

Colocate `ProductHero` specific styles
Colocation

Refactor ProductHeroV2 layout

---

apps/store/src/app/[locale]/checkout/components/CheckoutForm/CheckoutForm.tsx

Subj.
Code scouting/reduce noise from datadog logs

chore(checkout-form-error-dialog): solves radix "dialog without title" error

---

apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.css.ts

Set correct pillow size in desktop

---

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx

- PurchaseForm: proper space "calculate price" button and "average rating" link

fix(purchase-form): proper space "calculate price" button and "average rating" link

---

apps/store/src/components/Header/HeaderMenu/HeaderMenu.css.ts

Fix close button size for price calculator

---

apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/InsuranceDataForm.tsx
apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/SsnSeSectionV2.tsx

Create a V2 of SsnSection, just like for the other components to be able to modify it in new PriceCalculator
This PR only duplicates file, changes come in next PR
To be able to modify SSN section without breaking current implementation

Add SsnSectionV2 component
