HedvigInsurance/racoon

apps/store/src/features/retargeting/ShopSessionRetargeting.graphql, apps/store/src/features/retargeting/getUserRedirect.test.ts, apps/store/src/features/retargeting/getUserRedirect.ts
- Retargeting: redirect based on unique exposures
- If a user has multiple price intents for e.g. different cars we want to add all to cart and redirect to cart page
- Refactor logic in helper function and update tests
- This works for now, but it makes more and more sense to move this logic to the backend
=> GEN-1084 | Retargeting: redirect based on unique exposure

apps/store/src/components/QuickAdd/QuickAdd.tsx
- `QuickAdd`: make the cost-prop optional
- Required to support the incomplete quick add card where we might not have an offer yet
=> QuickAdd: make cost-prop optional

apps/store/src/features/retargeting/useApiRedirectEffect.ts, apps/store/src/middleware.ts
- Use browser API to navigate on to API route
- Update middleware matching to exclude paths that contain a dot/period (.)
- Next.js router navigation triggers the middleware for some unknown reason
- We have an issue where we add locale to static files in the public folder. Excluding paths with a dot/period (.) will prevent this.
=> Fix: locale redirect matching stuff it shouldn't

apps/store/src/components/Accordion/Accordion.tsx
- Tweak the padding inside accordion item so text doesn't get to close to the edge of the container
- Also make the body text align with the heading
=> GEN-1118 | Fix: padding inside accordion item

apps/store/src/pages/payment/connect-legacy/index.tsx
- PaymentConnectLegacy: redirect to error with explicit status code
- Next.js forwards the request method from the form submission which results in HTTP ERROR 405 (method not supported). This fixes that.
=> PaymentConnectLegacy: fix redirect to error page

apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
- Treat global story as nullable in layout with menu component
- We've noticed client-side runtime errors where we try to render the component with global story as undefined
- Not sure what a good loading state would be since this is some sort of race condition
=> LayoutWithMenu: prevent runtime error

apps/store/src/services/storyblok/Storyblok.helpers.ts, apps/store/src/services/storyblok/storyblok.ts
Enable anchor links for `ButtonBlock`.
**Before**
**After**
=> GEN-1155 - fix(ButtonBlock): enable anchor links

apps/store/index.d.ts, apps/store/src/components/ProductPage/ProductPage.types.ts, apps/store/src/pages/[[...slug]].tsx, apps/store/src/pages/_app.tsx, apps/store/src/services/CustomerFirst.tsx, apps/store/src/services/storyblok/storyblok.ts
* Hide _customer1_ chat based on a CMS page config (`hideChat`)
The following is how it works:
* If user navigates to a "hide chat" page **and** chat is closed then we hide it. Otherwise it get's displayed.
Observe that doesn't cover the whole thing though because users can start a chat on a "show chat" page, send some messages and minimize it (in other words, close it) while they await for a response. In the meantime they can navigate to a "hide chat page" and then we'd be hiding the whole thing. Peter knows about this and he thinks it's a good enough solution for now.
https://github.com/HedvigInsurance/racoon/assets/19200662/4fb251c0-4ac7-4050-aef0-c9bf0c8683d8
Desired by Peter.
=> GEN-1115 - feat: hide chat based on CMS config

apps/store/public/locales/en/cart.json, apps/store/public/locales/sv-se/cart.json, apps/store/src/components/ProductItem/CartDealershipRemoveButton.tsx
- Adds `RemoveContractActionButton` that users will click on in case they want to remove the extension car offer.
Required for _Car Dealership_ feature
=> GEN-1144 - feat: added remove contract modal

apps/store/index.d.ts, apps/store/src/services/CustomerFirst.tsx
Make usage of `createWidget` API to append _customer1_ chat iframe into the DOM. With it we can better control when to load it, in contrast with the current setup where its loading process was being done on an _onload_ event handler they attach when _c1_ script get's parsed.
**Disclaimers**
1. With this change we're appending the chat iframe into the DOM after _c1_ gets loaded with `next/Script` `onLoad` prop. That's because right now we just want fix the issue that originated this ticket where chat iframe might not get loaded with lazy loading approach. However we have different plans for the future where we'd condition chat iframe addition into the DOM as a result of a button click. (check [here](https://www.notion.so/hedviginsurance/Customer1-create-launch-button-desktop-114e9f7239dc4b3 …
=> GEN-1081 - fix(c1): make it work with lazy load strategy

apps/store/src/features/carDealership/ActionButtonsCar.tsx, apps/store/src/features/carDealership/ActionStateEdit.tsx, apps/store/src/features/carDealership/useEditAndConfirm.tsx
- Add `ActionButtonCar` component that handles editing car price intent inline
- Start new "carDealership" feature module to group files
Usage:
```
<ActionButtonsCar
shopSessionId="123"
priceIntent={{
id: '123',
data: {},
offers: [
{
id: '1234',
variant: { typeOfContract: 'test', displayName: 'Full insurance' },
},
{
id: '1235',
variant: { typeOfContract: 'test1', displayName: 'Half insurance' },
},
{
id: '1236',
variant: { typeOfContract: 'test2', displayName: 'Traffic insurance' },
},
],
}}
offer={{ id: '1234', variant: { typeOfContract: 'test', displayName: 'Full insurance' } }}
onRemove={() => {}}
onUpdateOffer={() => {}}
/>
```
- Support car dealership features
- I left some translations hard coded for now since the UI is still pending
- I will add tests once we are happy with adding …
=> GEN-1141 | Add `ActionButtonCar` component

apps/store/src/components/ProductItem/ProductItem.tsx
- Avoid expecting exactly two children (action buttons) in `ProductItem`
- We have a need for a single child that handles its own layout (car dealership)
=> ProductItem: don't expect two action buttons

apps/store/src/features/carDealership/ActionButtonsCar.tsx, apps/store/src/features/carDealership/PriceIntentDataUpdateCar.graphql, apps/store/src/features/carDealership/TrialExtensionBlock.tsx, apps/store/src/features/carDealership/useEditAndConfirm.tsx
- Use a car dealership specific mutation to update price intent data
- The one we use in price calculator also updates customer data so it needs shop session ID. We don't do that in this feature so passing shop session ID just becomes confusing.
=> Use car-specific price intent update mutation

apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx, apps/store/src/blocks/TextBlock.tsx, apps/store/src/components/RichText/RichText.tsx
- Fix text formatting for `TextBlock`'s rich text field - `body`
`TextBlock` was accepting a rich text field but none formatting was being applied. Now the same one we use for `RichTextBlock` is being applied for `TextBlock` as well.
=> GEN-975 - fix(TextBlock): proper render rich text content

apps/store/src/features/carDealership/ActionButtonsCar.tsx, apps/store/src/features/carDealership/TrialExtensionBlock.tsx, apps/store/src/features/carDealership/useEditAndConfirm.tsx
- Store selected tier level in React state and derive the selected offer based on that
- The first iteration stored the offer itself in React state. However, then we need to update it every time we confirm the price intent which is error prone. This way we only update state when someone changes the tier level.
=> GEN-1171 | CarDealership: derive selected offer based on tier level

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx, apps/store/src/features/carDealership/TrialExtensionForm.stories.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx, apps/store/src/features/carDealership/carDealershipBlocks.ts, apps/store/src/services/storyblok/storyblok.ts
- Build `CarTrialExtensionBlock` component
- Register new block in Storyblok
- Remove `onUndo` prop from `TrialExtensionForm`
- Based on new architecture for car dealership project
- `TrialExtensionForm` should handle removing and re-adding extension offer (no need for callback)
=> GEN-1168 | Build CarTrialExtensionBlock (draft)

apps/store/src/components/CartPage/CartPage.tsx, apps/store/src/components/CheckoutPage/CheckoutPage.tsx, apps/store/src/components/ProductItem/EditActionButton.tsx, apps/store/src/components/ProductItem/ProductItemContainer.tsx, apps/store/src/components/ProductPage/PurchaseForm/useSelectedOffer.ts, apps/store/src/components/QuickAdd/QuickAddCompleteContainer.tsx, apps/store/src/features/carDealership/carDealershipFixtures.ts, apps/store/src/graphql/OfferRecommendationFragment.graphql, apps/store/src/graphql/ProductOfferFragment.graphql, apps/store/src/services/Tracking/Tracking.ts
Align product field with updated [schema](https://studio.apollographql.com/graph/Octopus-fxevz/variant/production/changelog/version/f3d56844-0602-4c25-9251-daf4a75a5d1a)
`product` is being removed from `ProductVariant` type and added to `ProductOffer` instead
`ProductVariant.product` is deprecated, get it through offer or intent instead.
=> GEN-1182 / Replace ProductVariant.product with Offer.product in schema

apps/store/src/features/carDealership/ActionButtonsCar.tsx, apps/store/src/features/carDealership/CarTrialExtension.graphql, apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx, apps/store/src/features/carDealership/TrialExtensionForm.stories.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx, apps/store/src/features/carDealership/carDealershipFixtures.ts, apps/store/src/features/carDealership/useSignAndPay.ts, apps/store/src/pages/api/car-trials.ts
* Adds a `CarTrialExtension` query: at the moment it only fetches info about `shopSession` and `priceIntent`. TrialExtension information is still mocked;
* Update fixtures so it satisfied data request data format;
Get closer to the real feature while we don't have the API configured.
=> GEN-1189 - refact(CarTrialExtensionBlock): query real data from shopSession and priceItent

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- Unmount `EditingState` component (`PurchaseForm`) when we display an error dialog
- Currently, if you get and error and then press "try again" you just see the calculate loading state. This is because the `EditingState` component depends on being re-mounted to reset internal state. This works for mobile but not for desktop. This PR fixes that.
=> Price Calculator: reset state of `EditingState` after error

apps/store/apollo.config.js, apps/store/src/components/ProductItem/ProductItem.stories.tsx, apps/store/src/components/ProductItem/ProductItemContainer.tsx, apps/store/src/components/ProductItem/StartDate.tsx, apps/store/src/components/ProductItem/useGetStartDateProps.ts, apps/store/src/features/carDealership/CarTrialExtension.graphql, apps/store/src/features/carDealership/carDealershipFixtures.ts, apps/store/src/graphql/ProductOfferFragment.graphql, packages/ui/src/components/Text/Text.tsx
- Query new exposure from the API
- Display exposure in the `ProductItem` card
- Remove old logic based on product name
- Update `StartDate` component layout to handle longer text
- This logic belongs in the backend since it's product specific
=> GEN-1181 | Use new exposure display name in `ProductItem` card

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx, apps/store/src/features/carDealership/ProductItemContractContainer.tsx, apps/store/src/pages/api/car-trials.ts
- Set the start date of car trial extension to end date of trial
- Add grid layout to CMS block
- Closer to how we imagine it working
=> GEN-1208 | Sync start date of extension with end of trial

apps/store/index.d.ts, apps/store/src/blocks/InsurelyBlock.tsx, apps/store/src/services/Insurely/Insurely.tsx
- Add option to enable selecting multiple companies in Insurely config
- Enable option in `InsurelyBlock` (used by sales support tool)
- New feature from Insurely
=> GEN-1230 | Enable multi company select in `InsurelyBlock`

apps/store/src/features/carDealership/TrialExtensionForm.tsx, apps/store/src/utils/PageLink.ts
- Car dealership: when a user doesn't want to sign an extension, we should let them sign in and then navigate to connect payment
- Everyone who lands on this page will be a member, so we don't need to handle non-members
- Users that have already connected payment will not have the option to remove extension offer (not yet implemented)
- I added the logic inline since it's not a lot of code and will make it easier to refactor later
=> GEN-1219 | Car dealership: login and navigate to payment

apps/store/src/components/InputSelect/InputSelect.tsx, apps/store/src/components/ProductItem/ProductItem.stories.tsx, apps/store/src/components/ProductItem/ProductItem.tsx, apps/store/src/components/ProductItem/ProductItemContainer.tsx, apps/store/src/features/carDealership/ActionButtonsCar.tsx, apps/store/src/features/carDealership/ActionStateEdit.tsx, apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx, apps/store/src/features/carDealership/RemoveCarOfferActionButton.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx, packages/ui/src/lib/theme/colors/colors.ts
- Add variant of `ProductItem` with a green background
- Add new variant of `InputSelect` with frosted glass background
- Update frosted glass background color to match Figma (not used anywhere else)
- Wrap LoadingState for trial extension block inside the grid layout
- Adopt new design from Figma
=> GEN-1217 | Adapt extension offer ProductItem to use a green background

apps/store/src/features/carDealership/ActionButtonsCar.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx
- Removes 'edit' button for users that have payment connected
UI changed
=> GEN-1231 - feat(ActionButtonsCar): remove 'edit' button for users with payment connected

apps/store/public/locales/en/carDealership.json, apps/store/public/locales/sv-se/carDealership.json, apps/store/src/features/carDealership/TrialExtensionForm.tsx
- Hide "Trial Offer" for users that **have payment connected**;
- Update sign button copy: extend insurance
- Display extend offer in green variant only for members that **don't have payment connected**
Design has changed
=> GEN-1239 - styles(TrialExtensionForm): hide trial offer for users with payment connected

apps/store/src/features/carDealership/ActionButtonsCar.tsx, apps/store/src/features/carDealership/RemoveCarOfferActionButton.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx, packages/ui/src/components/Button/Button.tsx
- Make edit button full size and secondary-alt variant
- Update secondary-alt button hover state
- Delete "remove" button
- I kept the start date title the same (asked about it in Figma)
- The hover state for the secondary-alt button doesn't work on green background
- I left the remove button component since we will use the warning dialog
=> GEN-1237 | Update `ProductItemContainer` in trial form

apps/store/public/locales/en/carDealership.json, apps/store/public/locales/sv-se/carDealership.json, apps/store/src/features/carDealership/ConfirmPayWithoutExtensionButton.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx
- Display dialog with warning message when user continues without extension offer
- Remove unused translations and components (no longer part of the design)
- Adpat to the new design
=> GEN-1245 | Show a warning dialog when user proceeds without extension

apps/store/src/components/GlobalBanner/GlobalBanner.tsx, apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx
- Banner: avoid truncating content and wrap it into multiple lines
- Make sure banner get's shown for car dealership extension offer page
=> styles(car-dealership-banner): wrap content into multiple lines

apps/store/src/components/CartPage/PageDebugDialog.tsx, apps/store/src/components/CheckoutPage/PageDebugDialog.tsx, apps/store/src/components/DebugDialog/DebugDialog.tsx, apps/store/src/components/DebugDialog/DebugTextKeys.tsx, apps/store/src/components/DebugDialog/DefaultDebugDialog.tsx, apps/store/src/components/ProductPage/PageDebugDialog.tsx
- Add button to page debugger to toggle showing text keys / translations
- Add option to press ctrl+shift+d to toggle showing page debugger
- Expose more useful debug features
- Add page debugger shortcut that doesn't conflict with browser (Arc)
=> GEN-1244 | Add option to toggle debug text keys to page debugger

apps/store/src/components/PaymentConnectPage/ReadyState.tsx, apps/store/src/features/memberArea/MemberPage.tsx, apps/store/src/features/memberArea/PaymentsSection.tsx, apps/store/src/pages/payment/connect.tsx
Integrate Trustly iframe inline into PaymentsSection
Make section fetch its own data to be able to refresh when connection is updated
=> Inline payment connection UI

apps/store/src/components/ButtonNextLink.tsx, apps/store/src/features/memberArea/TravelCertificateCreate.graphql, apps/store/src/features/memberArea/components/InsuranceCard.tsx, apps/store/src/features/memberArea/components/TravelCertificateButton.tsx
- Add insurance certificate links
- Add travel certificate integration that uses default data and blows up for non-Home contracts
=> Ability to get travel and insurance certificates

apps/store/src/features/memberArea/PaymentsSection.tsx, apps/store/src/features/memberArea/components/InsuranceCard.tsx, apps/store/src/features/memberArea/components/InsurancesSection.tsx, apps/store/src/features/memberArea/components/TravelCertificateButton.tsx, apps/store/src/features/memberArea/pages/InsurancePage.tsx, apps/store/src/features/memberArea/pages/PaymentsPage.tsx, apps/store/src/features/memberArea/useMemberAreaInfo.ts, apps/store/src/pages/member/payments.tsx
Add type-safe useMemberAreInfo hook that relies on Apollo to provide fresh data without making same query multiple times
It will crash if used before member data is loaded, which makes deep component simpler - just don't use them until you have the data
=> Add useMemberAreaInfo to use Apollo as context provider

apps/store/src/features/memberArea/pages/LoginPage.tsx, apps/store/src/pages/member/login.tsx, apps/store/src/services/bankId/bankId.types.ts, apps/store/src/services/bankId/useBankIdLogin.ts
Improve login flow
- Post-login redirect is now server-side to make sure it works for people going to login page while being authenticated
- Keep BankID dialog open until next page loads, prevents flash of login form before redirect
=> Move post-login redirect to server side, keep BankID dialog open until onSuccess resolves

apps/store/src/features/memberArea/pages/protectedPageServerSideProps.ts
Subj
Non-authenticated users should end up on their original target page after authenticating since we keep target in `next` query param
=> Keep original target page as ?next when redirecting non-authenticated user

apps/store/src/features/memberArea/InsuranceSection/InsuranceDetailsSection.tsx
- Add tabs and split up insurance content
Next: add coverage content
https://github.com/HedvigInsurance/racoon/assets/6661511/426be252-2944-450f-aeb7-1c2177cf917c
=> Add tabs to InsuranceDetails

apps/store/src/features/memberArea/pages/protectedPageServerSideProps.ts, apps/store/src/pages/member/login.tsx, packages/ui/src/components/HedvigSymbol/HedvigSymbol.tsx
Fix /se-en/member/* redirecting to /se/... during login flow
NextJs does not include locale in `resovledUrl`, but expects it to be present ti redirect.destination to work correctly.  This is odd and perhaps worth investigating some time in the future.  For now just adding locale explicitly to path
=> Keep locale during login flow

.github/renovate.json5
Raise hourly limit on Renovate PR creation.  This seems to be a bottleneck in current setup.  See comment in config for more details
=> Raise Renovate rate limit

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx, apps/store/src/features/carDealership/ExtensionOfferToggle.tsx, apps/store/src/features/carDealership/PayForTrial.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx, apps/store/src/features/carDealership/carDealershipFixtures.ts
- Break out a "PayForTrial" component from the "TrialExtensionForm"
- Add a reusable "ExtensionOfferToggle" based on jotai
- These components don't have much to do with one another so it makes sense to break them out into their own components
- Using jotai to avoid prop drilling
=> GEN-1271 | Separate PayForTrial from ExtensionForm component

apps/store/src/components/ProductItem/ProductDetails.tsx, apps/store/src/components/ProductItem/ProductItem.tsx, packages/ui/src/components/Heading/Heading.tsx
- See title (very subtle change but William could spot it on the screen)
- Needs to work better on the colored (green) background
- Simpler to just use translucent text also for grey background
=> GEN-1294 | Use translucent text inside `ProductItem`

apps/store/public/locales/en/carDealership.json, apps/store/public/locales/sv-se/carDealership.json, apps/store/src/features/carDealership/TrialExtensionForm.tsx
- Add USP text under sign button in trial extension form
- Remove unused info toast bar
- Make disclaimer text smaller
- Figma design updates
=> GEN-1293 + GEN-1292 | Car dealership: add USP text under sign button

apps/store/src/features/carDealership/EditExtensionOfferForm.tsx
- Log cases where users modify extension offers by only changing the tier level.
We can use that metric to decide upon a performance optimization where we only confirm the price intent (API call) when the milieage changes.
=> GEN-1269 - log(TrialExtensionForm): log when only tier level is changed

.github/renovate.json5
Making Renovate great again
- Run checks before automerge window to increase throughput
- Try to not create PRs for automerge branches with passing tests
=> Renovate: separate schedule and automergeSchedule, try PR-less flow for automerges

apps/store/public/locales/en/purchase-form.json, apps/store/public/locales/sv-se/purchase-form.json, apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx, apps/store/src/components/PriceCalculator/PriceCalculatorAccordionSection.tsx, apps/store/src/services/PriceCalculator/PriceCalculator.types.ts, apps/store/src/services/PriceCalculator/data/SE_CAR.ts
- Add tooltip with info about car ownership in car purchase form
https://github.com/HedvigInsurance/racoon/assets/6661511/5f06132a-a15a-44bb-aa6b-af926216eb8e
We need to inform that you need to be the owner of the car to sign insurance
=> Add tooltip with info about car ownership

apps/store/public/locales/en/cart.json, apps/store/public/locales/sv-se/cart.json, apps/store/src/components/ProductItem/ProductItem.stories.tsx, apps/store/src/components/ProductItem/ProductItem.tsx, apps/store/src/components/ProductItem/ProductItemContainer.tsx, apps/store/src/components/ProductItem/useGetStartDateProps.ts, apps/store/src/features/carDealership/ProductItemContractContainer.tsx
- Changes how product item association are displayed: close to details table.
Being on the same line as start date was causing issues when there was no enough space to render all info without truncating text.
More info [here](https://hedviginsurance.slack.com/archives/C02JPS466NS/p1697445802184469)
=> GEN-1313 - fix(ProductItem): show product item association according to design

apps/store/public/locales/en/memberArea.json, apps/store/public/locales/sv-se/memberArea.json, apps/store/src/features/memberArea/InsuranceSection/InsuranceCard.tsx, apps/store/src/features/memberArea/PaymentsSection/InsuranceCost.tsx, apps/store/src/features/memberArea/PaymentsSection/PaymentsSection.tsx
Improve payments section
- List insurances
- Refactor cost breakdown (discounts and totalt)
I noticed that I wouldn't get any discounts on `CurrentMember` though (the image is a hardcoded example). I signed up with a valid staging discount code (percentage for 12 months) but `insuranceCost` just gets the full price i.e. discount is 0, net and gross the same amount. 
Improve visibility on what the member pays for
=> Improve layout for cost breakdown

.vscode/racoon.code-workspace
- Make "import/order" plugin work for vscode workspace.
Sorting import statements wasn't working for me in workspace mode. Turns out it couldn't find eslint.
=> fix(vscode-workspace): make import/order eslint plugin work properly

apps/store/src/components/CheckoutPaymentTrustlyPage/CheckoutPaymentTrustlyPage.tsx, apps/store/src/components/PaymentConnectPage/IdleState.tsx, apps/store/src/components/PaymentConnectPage/ReadyState.tsx, apps/store/src/components/PaymentConnectPage/SuccessState.tsx, apps/store/src/features/memberArea/PaymentsSection/PaymentConnection.tsx, apps/store/src/features/memberArea/PaymentsSection/PaymentsSection.tsx, apps/store/src/services/trustly/TrustlyIframe.tsx, apps/store/src/services/trustly/createTrustlyUrl.ts
- Open Trustly iFrame in a dialog instead of inline
- Refactor to be able to center the iFrame-Dialog on the screen
- Match how we handle payment connection in the mobile app
- Improve error handling and user experience
=> Payment Config: open Trustly in Dialog

apps/store/src/components/CheckoutPage/CheckoutPage.tsx, apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts, apps/store/src/services/bankId/bankId.types.ts, apps/store/src/services/bankId/useBankIdCheckoutSign.ts
I've noticed we keep pooling sign status and did not display an error message when signing failed due some member creation error.
This pass down `onError` cb to `startSign` function so we can use it to change the state of "error modal", making it appear.
**Before**
https://github.com/HedvigInsurance/racoon/assets/19200662/e969716b-d7a6-4162-b5e0-327dfdc7ede6
**After**
https://github.com/HedvigInsurance/racoon/assets/19200662/eb1f698a-211b-4850-a482-1e9f4d5a0154
=> GEN-1357 - fix(sign): display "failed" to sign modal

apps/store/package.json, apps/store/src/blocks/ProductReviewCommentsBlock.tsx, apps/store/src/services/productReviews/productReviews.ts, apps/store/src/services/productReviews/productReviews.types.ts, apps/store/src/services/productReviews/productReviews.utils.ts, yarn.lock
- Update `productReviews` service by validate average rating / review comments data, logging an error when they are invalid;
- Makes `ProductReviewCommentsBlock` simplier by removing some safe verifications as we've increased the the trust on getting data in the right format.
After some discussions we thought that would make `ProductReviewCommentsBlock` simplier. Another approach would be to make sure nothing fish get's written into the database (vercel/kv), but I guess we can start with this as it's easier to implement and also easier to let us now when something is wrong with the data.
=> refact(productReviews): validate average ratings/review comments data

apps/store/src/components/ComparisonTable/MobileComparisonTable.tsx
- Add horizontal scrolling when tabs overflow on mobile
- Reported by Peter
=> GEN-1161 | ComparisonTable: horizontally scroll tabs on mobile

apps/store/src/services/priceIntent/PriceIntentService.ts
- Reuse existing price intent service instance instead of creating new ones
- Update how to compare input params when creating new price intents
- We deduplicate requests to create price intents, however, we store the promise on the class instance. We also create new instances of the class for each request. This means that we never reuse the saved promise. This PR fixes that by reusing the existing instance.
- We also compare the input params to determine if we should create a new price intent. However, the compare method was quite crude so I changed it to be more specific and only compare the fields that are relevant to the price intent.
=> GEN-1369 | Fix bug causing us to create duplicated price intents

apps/store/package.json, apps/store/public/locales/en/contact-us.json, apps/store/public/locales/sv-se/contact-us.json, apps/store/src/@types/i18next.d.ts, apps/store/src/components/ContactUs/ContactUs.tsx, apps/store/src/components/ContactUs/ContactUsButton.tsx, apps/store/src/components/ContactUs/Content.tsx, apps/store/src/components/ContactUs/Header.tsx, apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx, apps/store/src/pages/_app.tsx, apps/store/src/utils/PageLink.ts, apps/store/src/utils/zIndex.tsx, packages/ui/src/lib/globalStyles.ts, packages/ui/src/lib/theme/transitions.ts, yarn.lock
Adds a custom "contact us" button.
https://github.com/HedvigInsurance/racoon/assets/19200662/bc6812ef-0dca-4dc6-9335-8954e2f6ca19
It takes a long time to get something updated from c1 and we want better support for lazy loading. This can be used while chat is unavailable while makes the app perform better.
=> GEN-1301 - chore: added a custom 'contact us' button until we wait for c1

apps/store/src/blocks/ConfirmationPageBlock.tsx
- Fix `Confirmation` Content Type in Storyblok
Just noticed `Confirmation` content type couldn't be previewed in Storyblok because we name it differently in our code: `confirmationPage` instead of `confirmation`.
=> fix(ConfirmationPage): storyblok preview

apps/store/src/pages/sitemap.xml.js
Using storyblok client `getAll` handles pagination and rate limiting automagically 👌
=> Refactor sitemap to use Sotryblok client instead

apps/store/src/pages/_app.tsx, apps/store/src/services/CustomerFirst.tsx
- Hide/Show "Contact US" chat launched based on CSM setting (for Page content type)
Just realize that wasn't work as it suppose to while doing something else.
=> fix: hide chat for CMS pages based on setting

apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx, apps/store/src/pages/sitemap.xml.js, apps/store/src/services/storyblok/Storyblok.helpers.ts
Reverts HedvigInsurance/racoon#3494
Broke ProductCardBlock when comparing `const isProductLink = productMetadata?.some((product) => isSameLink(link, product.pageLink))`
Let's see if we should remove trailing slash everywhere or keep it as we had it, let's revert to start with
=> Revert "Remove trailling slashes for all Storyblok URLs since it causes redirects"

apps/store/src/components/ShopBreakdown/TotalAmountContainer.tsx
CheckoutPage: display 'free months' discounts properly by getting reduce cost from `cost.discount` field.
**Before**
**After**
We're getting the reduced cost from `cost.net` field which is not correct.
=> fix(TotalAmountContainer): get reduced cost from 'discount' field

apps/store/src/components/ConfirmationPage/ImageSection.tsx
Make sure image section doesn't override other content.
**Before**
**After**
Noticed an issue with Confirmation Page image section as it was override app links.
=> fix(ConfirmationPage): make sure image section doesn't override other content

apps/store/src/components/GridLayout/GridLayout.helper.tsx, apps/store/src/pages/widget/[flow]/[shopSessionId]/select.tsx
- See title.
- I implemented it inline but it will likely end up as some sort of layout we can reuse on other pages in the flow.
- Exported grid layout styles so we can use them for more complex layouts
=> GEN-1385 | Implement header for Widget Product Selector page

apps/store/src/components/RadioOptionList/RadioOptionList.stories.tsx, apps/store/src/components/RadioOptionList/RadioOptionList.tsx
- Create a reusable Radio Option List component (based on design system)
- Support the product option item
- Add storybook story
- Needed for the hedvig widget implementation
- We already use it in the price calculator. We should extract it from there and make it reusable. However, I thought this would be an easier first step to review.
=> Create reusable Radio Option List component

apps/store/src/features/widget/SelectProductPage.tsx, apps/store/src/features/widget/widget.helpers.ts, apps/store/src/pages/widget/[flow]/[shopSessionId]/select.tsx, apps/store/src/utils/PageLink.ts
- Add radio input for selecting product in widget flow
- Break out page and put inside feature folder
- Add link to next step in widget flow (calculate price)
- Add helpers to fetch correct price template based on product name
- We can't test it quite yet since we don't have the widget products in the backend yet, but we can test the UI. Just go to: `/se/widget/test/test/select`.
- I will continue to work on this in the next PRs and hook up to get correct product data from backend.
=> GEN-1385 | Add radio input to widget select product page

apps/store/src/features/widget/fetchProductMetadata.ts, apps/store/src/pages/widget/[flow]/[shopSessionId]/select.tsx, apps/store/src/services/storyblok/storyblok.ts
- Widget product select: filter products to display based on CMS config
- Add new Storyblok helper to get story by ID
- I decided to filter products on the backend so we can reduce page load. Let's see if it causes problems since we are reusing the same Jotai atom for the product list as we are for the menu.
=> GEN-1385 | Widget select product - filter based on CMS config

apps/store/src/features/widget/Header.tsx, apps/store/src/features/widget/SelectProductPage.tsx
- Widget: break out a reusable Header component
- Implement on the select product page
- We will need to use this component on other pages in the flow
- We could have implemented a shared layout but this is a more flexible approach and get the job done (for now)
=> Widget: break out reusable header component

apps/store/src/pages/widget/[[...slug]].tsx
Just realised that part was missing.
So we visualize widget draft content pages locally
=> fix(widget-content-pages): make it work with draft content

apps/store/public/locales/en/carDealership.json, apps/store/public/locales/sv-se/carDealership.json, apps/store/src/features/carDealership/PriceBreakdown.tsx, apps/store/src/features/carDealership/ProductItemContractContainer.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx
A new component for explaining the cost for trial and extension separately.  
I didn't want to use the `Price` component where we send in a reduced price. The logic is the other way around in this case. The trial price is the fixed price (`amount`) and the default price that we want to strike through is the price for the same tier in full price (`defaultAmount`). 
It doesn't make sense to show a total price for explaining the price the member will pay for 2 months trial and then the extension
=> Add new PriceBreakdown component for car dealership

apps/store/src/features/carDealership/PayForTrial.tsx, apps/store/src/features/carDealership/PriceBreakdown.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx
Make sure we never show crossed over price that's cheaper than the trial amount. Fred mentioned rare cases where offer would be cheaper than trial and this also would happen if default offer was not set to match trial tier.
Alos adressed comments from first PR
Avoid this case:
=> Add check for crossed over price to catch cases where offer would be cheaper than trial

apps/store/src/components/InsuranceDocumentLink.tsx, apps/store/src/components/ProductPage/ProductDocuments.tsx, apps/store/src/features/memberArea/InsuranceSection/InsuranceDetailsSection.tsx, apps/store/src/features/memberArea/MemberAreaMemberInfo.graphql, apps/store/src/graphql/InsuranceDocumentFragment.graphql, apps/store/src/graphql/ProductData.graphql, apps/store/src/mocks/productData.ts
Show insurance documents in member area after insurance certificate
Extract InsuranceDocumentLink as reusable component and make it separate from GraphQL model
Part of Car Trial flow
=> [CAR-30] Show productVariant documents in MemberArea > Insurance > Documents section

apps/store/src/blocks/TextBlock.tsx, apps/store/src/features/memberArea/InsuranceSection/InsuranceDetailsSection.tsx
Replaces `:first-child` to `:first-of-type`
We've getting some warning about this as `:first-child` selector can be problematic while using emotion during SSR. More info can be found [here](https://infinum.com/handbook/frontend/react/common-ssr-errors).
=> chore: replace :first-child for :first-of-type

apps/store/src/features/memberArea/InsuranceSection/InsuranceDetailsSection.tsx
Implement Robin's idea that active tab in insurance details should be reflected in URL
So that user would stay on the same tab after reloading the page
=> Track active insurance details tab as query param

apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx, apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts, apps/store/src/pages/confirmation/[shopSessionId].tsx
* Make outcome/switching data fetching optional. That way we can use same `ConfirmationPage` component for car dealership feature, where we don't need to fetch those.
Foundation changes for supporting _Car Dealership_ confirmation pages.
=> GEN-1413 - refact(ConfirmationPage): update data requirements

apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx, apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts, apps/store/src/pages/car-buyer/confirmation-with-extension/[contractId].tsx, apps/store/src/utils/PageLink.ts
* `ConfirmationPage`
* 🆕 Adds _Total_ section under `ShopBreakdown` - For all _Confirmation_ pages
* 🚘 Adds `carTrialContract` prop: When present it should render your current Car Trial Contract as a product item: Car Dealership feature.
* 🚘 Adds _Confirmation Page With Extension_ for car dealership: It uses `ConfirmationPage` for the UI but it fetches CMS settings for _Car Dealership Confirmation Page With Extension_ along with car trial info.
* `PageLink`
* 🚘 Adds a page link for the mentioned confirmation page. 
Car dealership feature.
=> GEN-1413 - feat(car-dealership): added confirmation page with extension

apps/store/src/blocks/ConfirmationPageBlock.tsx, apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx, apps/store/src/pages/car-buyer/confirmation-without-extension/[contractId].tsx, apps/store/src/services/storyblok/storyblok.ts, apps/store/src/utils/PageLink.ts
* `ConfirmationPage`
* 🆕 Adds `ctaSecion` prop: It should include CMS content to be rendered right below `ShopBreakdown`. We need to render some CMS content there for _Confirmation Without Extension_ 
* 🚘 Adds _Confirmation Page Without Extension_ for car dealership: It uses everything implemented in its counterpart - _Confirmation With Extension_. The only difference is from which Storyblok story it get's its settings.
* `PageLink`
* 🚘 Adds a page link for the mentioned confirmation page. 
Car dealership feature.
=> GEN-1413 - feat(car-dealership): added confirmation page without extension

apps/store/src/components/PriceCalculator/useFetchInsurance.ts, apps/store/src/components/ProductPage/PriceIntentContext.tsx, apps/store/src/services/Tracking/Tracking.ts
- Update tracking context when we receive a new price intent
- Use product data from context when submitting Insurely events
- Make `PriceCalculator` reusable outside PDP
- I realize that we use product data for other events as well. This opens up the question of when to update the tracking context. It would make sense that it would be done as we load the PDP but there's no easy hook for that in Next.js (unfortunately). I would say we start with this update and discuss the way forward in a separate ticket.
=> GEN-1441 | Get product data from context when tracking Insurely events

apps/store/src/components/PriceCalculator/FetchInsurance.tsx, apps/store/src/components/PriceCalculator/FetchInsuranceContainer.tsx, apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- Use Shop Session from props instead of context in `FetchInsurance` component
- Refactor `FetchInsuranceContainer` into using render-props
- I decided to refactor `FetchInsuranceContainer` to avoid prop drilling
=> GEN-1444 | Use Shop Session from prop in `FetchInsurance`

apps/store/src/features/widget/ShopSessionCreatePartner.graphql, apps/store/src/pages/widget/flows/[...slug].tsx, apps/store/src/services/storyblok/Storyblok.helpers.ts
Co-authored by @alebedev
- Setup new route to initialize widget from a CMS "widgetFlow" story
- Use new "shopSessionCreatePartner" mutation
- Fix `isWidgetFlowStory` helper
- Define single entry point for widget initialization
- Landing pages will link to this route to initialize the widget
- This overrides the other slug-route but we will address that in the next PR
=> GEN-1455 | Initialize Widget from flow route

apps/store/src/pages/widget/flows/[...slug].tsx, apps/store/src/pages/widget/preview/[[...slug]].tsx
- Bring back support for previewing the widget sign/checkout page in Storyblok
- Check if widget flow route is loaded in Storyblok editor and redirect to preview route
- Make it possible to preview the widget sign/checkout page in Storyblok
=> GEN-1458 | Preview Widget Checkout in Storyblok

apps/store/src/features/widget/parseSearchParams.ts, apps/store/src/features/widget/shopSessionCustomerUpdate.ts, apps/store/src/pages/widget/flows/[...slug].tsx
- Pick up customer data from URL and update shop session
- Pass along remaining search params to the next route
- Support for the partner to pass along customer data in the URL when starting the flow
=> GEN-1459 | Pre-fill customer data from search params

apps/store/src/features/carDealership/TrialExtensionForm.tsx
Display total amount when displaying only the extension
=> Don't show price breakdown for only extension page

apps/store/src/pages/car-buyer/confirmation-with-extension/[contractId].tsx
- Update confirmation pages slug
Confirmation pages were moved in Storyblok so we need to update accordantly.
=> fix(carDealership): use the correct slug for the car buyer confirmation page

apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx
- Show `<TotalAmmountContainer>` only for confirmation pages about shop sessions that actually has something included into the chat.
That would avoid this issue:
I know this is a workaround. Been talking with William and ideally we want confirmation page as a totaly CMS driven page. If we get that it would be just about not adding that "TotalBlock" for Car Dealership confirmation pages. Until we're not there, I thought that could be enough.
=> CAR-37 - fix(ConfirmationPage): show total only when cart is not empty

apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx, apps/store/src/components/ConfirmationPage/StaticContent.tsx
- Extract all CMS/static content from the Confirmation page into it's own component
- We want to reuse it on the widget confirmation page
=> Extract CMS content from Confirmation Page into component

apps/store/src/features/widget/ConfirmationPage.tsx, apps/store/src/pages/widget/[flow]/[shopSessionId]/confirmation.tsx
- Fetch confirmation story in the widget flow
- Include static content on the widget confirmation page
- Match figma design
- Let's discuss if the design of the widget confirmation page is suppose to evolve separately from the regular confirmation page - then we need to rethink this.
=> GEN-1464 | Include CMS content on widget confirmation page

apps/store/src/pages/widget/flows/[...slug].tsx
- Reset auth state before widget flow
- This is supposed to be a standalone flow so to avoid strange states, let's reset the auth state before starting the flow
=> Reset auth tokens before Widget Flow

apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx, apps/store/src/services/storyblok/storyblok.ts
- `ConfirmationStory`: removes `ctaSection` field
That field was added to `ConfirmationStory` [here](https://github.com/HedvigInsurance/racoon/pull/3513) for covering an specific use case of _Car Dealership Confirmation Page Without Extension_, where a CMS content driven section needed to be displayed:
We don't need to cover that use case anymore, therefore it's better that we remove that field.
=> chore(ConfirmationStory): removes 'ctaSection' field

apps/store/src/features/carDealership/useAcceptExtension.ts
- `useAcceptExtension`: changed loading state definition by including BankId state
We did the same thing for ManyPets. We we're having an issue where there's no proper loading state for authenticated users that sign an car trial extension.
=> CAR-38 - fix(useAcceptExtension): consider BankId state while determining loading state

apps/store/src/features/widget/SignPage.tsx
- Allow headings on widget sign page to span the whole parent container
- We should add some way in the CMS to decide where to break the heading text into multiple lines if that is a concern I think. If we do it in CSS we will have to keep it in sync when the text updates...
=> Widget Sign | Adjust padding around headings

apps/store/src/features/widget/SignPage.tsx
- Await navigation from sign -> payment in widget flow
- Remove logic to reset shop session
- We want to keep the modal open until navigation is complete
- The shop session context doesn't have anything to do with widget flow so I removed it -- or am I missing something?
=> Widget Sign | Keep BankID modal open during navigation

apps/store/src/blocks/ButtonBlock.tsx, apps/store/src/utils/mergeSearchParams.test.ts, apps/store/src/utils/mergeSearchParams.ts
- Add option to ButtonBlock in CMS to forward query string in the link
- Needed for Widget landing page where partner wants to initialize the flow with custom parameters like address, product, etc.
- Not thrilled about the implementation, especially having to use `ORIGIN_URL` and then replacing it but did it so that we maintain the same behaviour as before.
=> GEN-1466 | ButtonBlock option to forward query string

apps/store/src/features/widget/SelectProductPage.tsx, apps/store/src/features/widget/fetchFlowProducts.ts, apps/store/src/features/widget/widget.helpers.ts, apps/store/src/pages/widget/[flow]/[shopSessionId]/select.tsx
- Skip the select product step in widget flow if there's only one product configured
- Throw an error if there's no product configured
- Refactor some other data fetching code to reuse apollo client instance
- FYI: I will refactor this code in the next PR
- I made a function to create price intent since it is used in multiple places and we might want to change the implementation in the future so it is good to have a single place to change it
=> Widget | Skip select product if only one is configured

apps/store/src/features/widget/parseSearchParams.ts, apps/store/src/pages/widget/[flow]/[shopSessionId]/select.tsx
- Parse URL search params and detect if we have a pre-selected product, then skip product selection screen
- I refactored the server-side code a bit to make it easier to read the code
=> GEN-1469 | Detect pre-selected product from URL in widget flow

apps/store/src/features/widget/SelectProductPage.tsx, apps/store/src/features/widget/parseSearchParams.test.ts, apps/store/src/features/widget/parseSearchParams.ts, apps/store/src/features/widget/widget.helpers.ts, apps/store/src/pages/widget/[flow]/[shopSessionId]/select.tsx
- Make it possible to pass query params to pre-fill price intent data in Widget
- Pass along query params from select product step to the next step
- Support the same functionality as the old widget
=> GEN-1456 | Parse URL and pre-fill price intent data for widget

apps/store/src/features/widget/SignPage.tsx, apps/store/src/features/widget/fetchSignPageContent.ts
- Remove resolve relations setting from widget CMS fetcher function
- Move CMS content outside of grid layout container
- Enable showing CMS content on the sign page in the widget
=> Widget | Fix showing CMS content on sign page

apps/store/src/components/LayoutWithMenu/getLayoutWithMenuProps.ts, apps/store/src/pages/404.tsx, apps/store/src/pages/car-buyer/confirmation/[contractId].tsx, apps/store/src/pages/cart/index.tsx, apps/store/src/pages/cart/resume/[shopSessionId].tsx, apps/store/src/pages/confirmation/[shopSessionId].tsx, apps/store/src/pages/forever/[code].tsx
- Update `getLayoutWithMenuProps` function so it throws an Error instead of returning null when it fails to execute.
That simplifies it usage when it comes about types
=> CAR-41 - refact(getLayoutWithMenuProps): throw an error when something goes off

apps/store/src/components/ShopBreakdown/Discount.tsx, apps/store/src/components/ShopBreakdown/DiscountFieldContainer.tsx, apps/store/src/features/widget/SignPage.tsx
- Hide campaign add/remove buttons if they are disabled for the session
1. We must've accidentally removed a similar solution - unclear when/why
1. We have a problem where we render the divider even if campaigns are disabled AND there's no campaign added to the session. However, that would require many more changes so let's start with this.
=> GEN-1475 | Hide campaign controls if they are disabled for the session

apps/store/src/features/widget/Header.tsx, apps/store/src/pages/widget/[[...slug]].tsx
- Create a widget-specific slug-route for landing pages
- (re)-implement CMS/static page setup with a limited set of features
- This implementation does duplicate code but it makes it very flexible to evolve the widget
- It also makes the widget feature more independent from the rest of the site (self-contained)
=> GEN-1467 | Show Widget specific header on landing pages

apps/store/src/pages/widget/[[...slug]].tsx, apps/store/src/services/storyblok/storyblok.ts
- Only pre-render static pages under the "widget" folder
- Add optional prop to "getPageLinks" to filter by path prefix
- Remove unused function "getFilteredProductLinks"
- Fix bug when pre-rendering static widget landing pages
- Before it was trying to render all the static pages although it should be restricted to pages under the "widget" folder
=> Fix pre-rendering widget landing pages

apps/store/src/services/storyblok/Storyblok.helpers.ts, apps/store/src/services/storyblok/storyblok.ts
- Consider cache version when fetching published page links
- This should avoid some rate limiting issues
=> Use cache version when fetching page links from Storyblok

apps/store/src/components/ShopBreakdown/DiscountField.stories.tsx, apps/store/src/components/ShopBreakdown/DiscountField.tsx, apps/store/src/components/ShopBreakdown/DiscountFieldContainer.tsx, apps/store/src/components/ShopBreakdown/useDiscountExplanation.ts, apps/store/src/features/widget/ConfirmationPage.tsx
- Add component to widget confirmation page to show included discount
- Add new hook to get discount from redeemed campaign field in API
- Implement figma design
- I saw an opportunity to avoid some code duplication
=> Widget | Display campaign on confirmation page

apps/store/src/features/widget/CalculatePricePage.tsx, apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx, apps/store/src/utils/PageLink.ts
- include price intent ID in the URL for the sign page (widget)
- we need this information to be able to navigate back to the price caluclator step
=> Widget | Include price intent ID in sign page URL

apps/store/public/locales/en/carDealership.json, apps/store/public/locales/sv-se/carDealership.json, apps/store/src/features/carDealership/ProductItemContractContainer.tsx
- Removes "60 dagar" badge for Trial Product Item
Requested by Willian. It turned out being redundant as the product is called "Bilförsäkring 60 dagar".
=> CAR-42 - styles(carDealership): remove badge from product item

apps/store/src/pages/api/draft.ts, apps/store/src/services/storyblok/Storyblok.helpers.ts, apps/store/src/services/storyblok/storyblok.ts
- Centralize Storyblok cache version handling
- Storyblok cache version handling is currently spread across multiple files and is not consistent
- Now we will use it for all calls to Storyblok consistently which should avoid rate limiting and speed up the calls
=> GEN-1485 | Centralize Storyblok cache version handling

apps/store/src/components/InputSelect/InputSelect.tsx
- Truncate select text when there's not enough space
=> CAR-42 - styles(InputSelect): truncate long text in select

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx, apps/store/src/features/carDealership/PayForTrial.tsx, apps/store/src/features/carDealership/PriceIntentCarTrialExtensionFragment.graphql, apps/store/src/features/carDealership/ProductItemContractContainer.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx, apps/store/src/features/carDealership/carDealership.types.ts
- Adds pillow image for Trial Product Item
Observe tho that this implementation is a work around as that info is not exposed in `TrialContract` type.
=> CAR-42 - feat(ProductItemContractContainer): added pillow image

apps/store/src/features/widget/ProductItem.tsx, apps/store/src/features/widget/ProductItemContainer.tsx, apps/store/src/features/widget/SignPage.tsx, apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx, packages/ui/src/lib/theme/colors/colors.ts
<a href="https://app.graphite.dev/media/video/OgXegTwxM9IeuXHZyw5h/3e485c1d-93fc-4e2e-903b-f3a495d6eb5d.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/3e485c1d-93fc-4e2e-903b-f3a495d6eb5d.mov">Screen Recording 2023-11-22 at 14.11.38.mov</video>
- Add delete button to `ProductItem` based on design
- Differentiate main product from cross-sell products in the Widget Sign page
- Animate adding/removing products from the Widget Sign page
- Add semantic button colors from Figma
- Match Figma design
=> GEN-1488 | Add support to remove cross-sell in widget

apps/store/src/features/carDealership/PayForTrial.tsx, apps/store/src/features/carDealership/PriceBreakdown.tsx, apps/store/src/features/carDealership/ProductItemContractContainer.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx
- Display "crossed out amount" for Trial Product Item (when user doesn't want extension)
Requested by design under the name of consistency.
=> CAR-42 - styles(PayForTrial): display crossed out ammount

apps/store/src/features/widget/CalculatePricePage.tsx, apps/store/src/features/widget/SignPage.tsx
- Detect if we are about to add a product that is already in the cart
- If so: first remove the existing cart item and add the new one
- This is a more robust solution than relying on URL parameters and makes sure we support users that would press the back-button from the sign page.
=> GEN-1481 | Widget | Automatically detect cart entries to replace

apps/store/src/pages/widget/[[...slug]].tsx
- Call Storyblok API in sequence to get page links
- We are hitting Storyblok API rate limit even if we are sending cache version in the request
- I also tried sending a single request using the `by_slugs` option but couldn't get it to work as expected
=> Make calls to Storyblok in sequence to avoid rate limit

apps/store/src/blocks/InsurableLimitsBlock.tsx, apps/store/src/blocks/PerilsBlock.tsx, apps/store/src/blocks/ProductAverageRatingBlock.tsx, apps/store/src/blocks/ProductDocumentsBlock.tsx, apps/store/src/blocks/ProductVariantSelectorBlock.tsx, apps/store/src/components/ProductData/ProductDataProvider.tsx, apps/store/src/components/ProductPage/PriceIntentContext.tsx, apps/store/src/components/ProductPage/ProductPage.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/components/ProductVariantSelector/ProductVariantSelector.tsx
- Use Jotai to setup a "product data context"
- Use this context to access product data on the PDP
- Use a separate Jotai store for each product to make sure that the data is
updated correctly
- This implementation will make it possible to reuse it outside of the PDP
- I opted for Jotai instead of React Context because it is easier to use. I still ended up with a little more boilerplate than I would have liked; mostly to make sure we always have the latest data.
- I considered "dangerouslyForceHydrate" but decided against it since the behavior can be inconsistent with concurrent rendering
=> Create `ProductDataContext` based on Jotai

apps/store/src/components/ProductItem/ProductItem.tsx
- `ProductItem`: updated spacing between Exposure and Divider
**Before**
**After**
Requested by design. It's a subtle difference. Before the spacing was a sum of the added `margin-top: 1rem` + some magical spacing added naturally by the characters. The solution was to take that magical space into account while setting the margin.
=> CAR-42 - styles(ProductItem): changed divider spacing

apps/store/src/features/carDealership/PayForTrial.tsx, apps/store/src/features/carDealership/useAcceptExtension.ts
- Hide banner after accepting extension or connecting a payment method.
I've tried other ways but without success. I guess it's not perfect but at least it works.
=> CAR-39 - fix(carDealership): hide banner after accepting extension/connecting payment

apps/store/src/pages/widget/[flow]/[shopSessionId]/confirmation.tsx
- Show success animation before confirmation page in widget flow
- Add page title for confirmation page in widget flow
- I kept the success animation inside the confirmation page folder since it still kind of belongs to the confirmation page.
=> GEN-1500 | Show success animation before confirmation page

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx, apps/store/src/pages/car-buyer/extension/[[...contractId]].tsx
This was the most logical way to solve it I think to make both preview and extension with a `contractId` work.
The route will be `car-buyer/extension/[contractId]` instead, but that's the route already setup in CRM so that's fine I think.
https://hedvig-dot-nl4bnz3gb-hedvig.vercel.app/se/car-buyer/extension
https://hedvig-dot-nl4bnz3gb-hedvig.vercel.app/se/car-buyer/extension/bdcd75d6-f396-4ff1-838f-079d7d75d09b
Replaces https://github.com/HedvigInsurance/racoon/pull/3649
Needed for retargeting
=> Create separate route for car dealership /extension

apps/store/src/pages/_app.tsx, apps/store/src/pages/widget/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx, apps/store/src/services/Tracking/TrackingContext.tsx, apps/store/src/services/Tracking/trackPageViews.ts, apps/store/src/services/Tracking/useTracking.ts
- Use react context to provide shop session as context to `useTracking` hook for all child components
- Use multiple tracking contexts based on which shop session is relevant
- We need to keep track of different shop sessions to correctly track events. It started getting really hard to keep track of this with the widget. This is a more explicit approach that still allows us to nest different tracking providers.
- There's some things missing from this implementation but I open it as a PR to get feedback on the approach.
=> Provide Tracking context via React.Context

apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx, apps/store/src/services/Tracking/Tracking.ts
- Setup separate tracking context for many pets migration page
- Remove separate (unused) migration session tracking key
- Now any events sent from the migration page will use the correct shop session data
=> Derive tracking migration shop session from context

apps/store/src/services/Tracking/Tracking.ts, apps/store/src/services/gtm.tsx
- Set "user_id" for GA after completing a purchase
- I feel like this should be done after successful login/signup but let's try it here and see if it works at least
- Required to be able to move away from custom GA events
=> Set GTM user ID after purchase

apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx, apps/store/src/features/widget/CalculatePricePage.tsx
- Refactor fullscreen modal to be able to override the header
- In the fullscreen price loader dialog, hide the header
- User can't close this dialog, so the header is not needed
=> Widget | Hide close button in loading price dialog

apps/store/src/blocks/TickerBlock.tsx, apps/store/src/services/storyblok/storyblok.ts
- New CMS block: Ticker
- Will be used on widget landing pages
- Will often be used below CTA buttons with a small margin; hence the extra CMS property to handle this
=> Add Ticker CMS block

apps/store/public/locales/en/widget.json, apps/store/public/locales/sv-se/widget.json, packages/ui/src/components/Heading/Heading.tsx, packages/ui/src/components/Text/Text.tsx
Make sure line breaks in Lokalise are rendered to better control text output. This is useable for texts that should have the same line break for all viewport sizes. If they will differ, we should adjust it with balance and width settings instead.
Better control of setting text in the app
=> Add support for line breaks in Lokalise

apps/store/src/components/Tooltip/Tooltip.tsx
* Tooltip: increase trigger tap area for coarse pointers (e.g: finger)
The solution is presented in a CSS which I can't link here. However it was inspired by this [codepen](https://codepen.io/third774/pen/XWgXZRY)
**Desktop**
**Mobile**
Makes it more "accessible" for mobile users since it's hard to be precise while clicking on such small button as the tooltip (16px x 16px). Got this trick from a CSS course. Apple recommends at tapbable areas of at least 44px x 44px.
Ideally we wan't that included into design system, as it might influence on the designs.
=> feat(Tooltip): increase tapable area on mobile

apps/store/src/components/LayoutWithMenu/ProductMetadataContext.tsx, apps/store/src/pages/_app.tsx, apps/store/src/services/trustpilot/trustpilot.tsx, apps/store/src/utils/globalStore.ts
- Add an explicit global Jotai store to the app
- Hydrate global data to the global store
- We have an issue where global product metadata is not available on PDP
- This is because the atom loads data from a different store (provider) than the one that is used to hydrate the global data
- With this approach, we can hydrate the global data to the global store and use it in the atom
- I didn't change anything about atoms that are never hydrated but we might see similar issues there in the future - let's discuss this!
=> Hydrate all atoms to explicit stores

apps/store/src/pages/widget/[[...slug]].tsx
- Fetch Trustpilot reviews from the Trustpilot API on Widget landing pages
- Hydrate data into Jotai
- We might want to make these landing pages behave even more similar to regular static pages but for now this is easy enough to maintain
- We want to use the trustpilot block on the landing pages
=> Fetch Trustpilot data on Widget landing pages

apps/store/index.d.ts, apps/store/src/components/ProductPage/ProductPage.types.ts, apps/store/src/pages/_app.tsx, apps/store/src/pages/car-buyer/validation/[dealerId].tsx, apps/store/src/pages/widget/[[...slug]].tsx, apps/store/src/pages/widget/run/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx, apps/store/src/pages/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx, apps/store/src/pages/widget/run/[flow]/[shopSessionId]/confirmation.tsx, apps/store/src/pages/widget/run/[flow]/[shopSessionId]/payment.tsx, apps/store/src/pages/widget/run/[flow]/[shopSessionId]/select.tsx, apps/store/src/services/CustomerFirst.tsx, apps/store/src/services/storyblok/getStoryblokPageProps.ts, apps/store/src/services/storyblok/storyblok.ts
- Hide customer first chat on all widget pages
- Refactor "hide chat" page prop
- Rename page prop to `_hideChat` to avoid naming collisions
- Wrap reading and "writing" of page prop in utility functions
- Remove explicit page prop typing of "hide chat"
- This logic was starting to get spread out all over the code base so I wanted to consolidate it into a single place
- Since the page prop can be added to any page, I think it is not necessary to explicitly type it
=> GEN-1538 | Hide chat on all Widget pages

apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx, apps/store/src/components/PriceCalculator/PriceCalculatorAccordionSection.tsx, apps/store/src/services/PriceCalculator/PriceCalculator.types.ts, apps/store/src/services/PriceCalculator/data/SE_WIDGET_APARTMENT.ts
* Lock editing SSN section for Widget flows
It's not clear what we should do for such cases so we decided to lock editing for SSN section so we can launch Widget.
=> GEN-1540 - fix(widget): make ssn section non editable

apps/store/src/components/ProductRecommendationList/useProductRecommendations.ts, apps/store/src/utils/useAddToCart.ts
- Update fetch policy for recommendations query to `cache-and-network`
- Remove unnecessary recommendation query from add to cart hook
- When "refetchQueries" is used in combination with "cache-and-network" fetch policy, the query is first fetched from cache and then executed in the background to check for new results.
- I found this solution in this [Medium article](https://medium.com/nexl-engineering/react-apollo-cache-set-up-refetch-refetchqueries-and-fetchpolicy-explained-with-examples-80cae6573401).
=> GEN-1544 | Refresh recommendations after adding to cart

apps/store/src/features/widget/Header.tsx, apps/store/src/features/widget/SelectProductPage.tsx
- Apply fixed header height only when header is single line
- Fix title and subtitle layout on mobile
- We introduced this issue when always showing the logo in the header
=> GEN-1542 | Fix spacing between header and title in mobile

apps/store/.storybook/decorators.tsx, apps/store/src/components/Accordion/Accordion.stories.tsx, apps/store/src/components/ComparisonTable/ComparisonTable.stories.tsx, apps/store/src/components/ComparisonTable/DesktopComparisonTable.stories.tsx, apps/store/src/components/InfoCard/InfoCard.stories.tsx, apps/store/src/components/ProductCard/ProductCard.stories.tsx, apps/store/src/components/ProductItem/ProductDetails.stories.tsx, apps/store/src/components/ProductItem/ProductDetailsHeader.stories.tsx, apps/store/src/components/ProductItem/ProductItem.stories.tsx, apps/store/src/components/ProgressIndicator/ProgressIndicator.stories.tsx, apps/store/src/components/QuickAdd/QuickAdd.stories.tsx, apps/store/src/components/QuickPurchaseForm/QuickPurchaseForm.stories.tsx, apps/store/src/components/RadioOptionList/RadioOptionList.stories.tsx, apps/store/src/components/ShopBreakdown/DiscountField.stories.tsx, apps/store/src/components/ShopBreakdown/ShopBreakdown.stories.tsx, apps/store/src/components/ShopBreakdown/TotalAmount.stories.tsx, apps/store/src/components/ToastBar/ToastBar.stories.tsx, apps/store/src/components/Video/Video.stories.tsx, apps/store/src/features/carDealership/TrialExtensionForm.stories.tsx
Add `align` prop to the grid decorator and update stories with grid settings.
This avoids components being super wide which makes it hard to compare the component with the design.
Render the components in a more suitable size and closer to implementation
=> Refactor Storybook grid decorator and set grid with on multiple stories

apps/store/src/features/widget/parseSearchParams.test.ts, apps/store/src/features/widget/parseSearchParams.ts, apps/store/src/services/PriceCalculator/PriceCalculator.helpers.ts
- Parse "student" query parameter from the URL
- Deserialize data value into a string for all radio inputs
- Remove unused query parameters like city, firstName, lastName, etc.
- Update tests
- We want to be able to pre-fill the "is student" input
=> GEN-1559 | Parse student pre-fill query parameter

apps/store/src/components/ProductData/ProductData.graphql, apps/store/src/components/ProductData/fetchProductData.ts, apps/store/src/pages/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx
- Pass partner name from widget flow story when fetching product data
- We want to display the partner specific product data in the widget (for AVY)
=> GEN-1541 | Show partner specific product data in widget flow

apps/store/src/features/widget/parseSearchParams.test.ts, apps/store/src/features/widget/parseSearchParams.ts
- Update widget URL parsing to expect parameter names that align with our API
- coInsured -> numberCoInsured
- student -> isStudent
- productType -> productName
- Deprecate the legacy parameter names
- Update tests to reflect the new parameter names
- The legacy parameter names are not aligned with our API. This causes confusion for new developers and makes it difficult to maintain the code. The integrating partners don't really care about the names.
=> GEN-1577 | Align optional Widget parameters with our API

apps/store/src/utils/date.ts
- Use date-fns to convert between Date and API date string
- We noticed issues earlier where someone would pick a day in the date picker only to see the previous day selected.
- Previously we converted using `toISOString` which means that JS would convert the date to UTC and then convert it to a string. This is not what we want, we want to convert the date to a string in the local timezone.
=> Parse API date without converting between time zones

apps/store/src/components/RatingCount/RatingCount.tsx
- Added `RatingCount` component
Gonna handle "selected" state later.
Part of _Product Reviews_ feature
=> GEN - 1573 - feat: added RatingCount component

apps/store/package.json, apps/store/src/components/InputDay/InputDay.stories.tsx, apps/store/src/components/InputDay/InputDay.tsx, yarn.lock
- Implement a custom date picker
- Update API for `InputDate` to use a change callback that returns a Date object
- Using the native date picker is problematic, especially on desktop where the behavior is hard to customize and sometimes doesn't work as intended.
- This is just an experiment, let's see if we want to merge it
- I was considering using the native picker on iOS but I think this might be easier to maintain
=> GEN-968 | Add custom date input

apps/store/src/utils/formatter.ts
* Update `fromNow` and `dateFull` formatters so they use dates in UTC representation
We were getting an issue with date field where the selected date wasn't the one displayed in the field when accessing the app in a different timezone:
https://github.com/HedvigInsurance/racoon/assets/19200662/e73bb391-c1a6-4ee0-9667-c770b27c373e
**Why was that happening**
_Extract from a AI tool_
> The behavior you're observing is due to how JavaScript handles date and time data. JavaScript's Date object is based on a timestamp, which is the number of milliseconds since the Unix Epoch (January 1, 1970 00:00:00 UTC). This timestamp is always in UTC.
> When you create a Date object using the ISO 8601 date format (e.g., 'YYYY-mm-dd'), JavaScript interprets the date as being in UTC. This is because the ISO …
=> GEN-1602 - use Swedish timezone for date visualization

apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
- Add "og:type" and "og:url" meta tags
- Always add canonical meta tags, default to page URL
- Request by Peter
- OG:URL Tag: This tag is part of the Open Graph protocol, mainly used for social media platforms like Facebook. It ensures that when a link is shared, the correct page information (like title, description, and image) is displayed. The OG:URL tag should point to the URL you want to be associated with your content when it is shared on social media.
=> GEN-1581, GEN-856 | Add og:type and og:url meta tags

apps/store/src/components/Pillow/Pillow.tsx, apps/store/src/components/QuickAdd/QuickAdd.stories.tsx, apps/store/src/components/QuickAdd/QuickAdd.tsx
- Add new size for Pillow component
- Add prop for passing main offer pillow and display multiple pillows
Update accident x-sell project
=> GEN-1528 / Display main offer title and pillow on QuickAdd component

apps/store/public/locales/en/cart.json, apps/store/public/locales/sv-se/cart.json, apps/store/src/components/CartPage/CartPage.tsx, apps/store/src/components/CheckoutPage/CheckoutPage.tsx, apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx, apps/store/src/features/widget/SignPage.tsx
Show "Home + Accident" title and double pillows when we have a home insurance in the cart. I realised that we would still show the QuickAdd component if you remove your home from the cart and have some other product left since I suppose we don't remove the offer recommendation. So in that case, we should display it without home.
=> GEN-1528 / Implement bundle title and pillows for QuickAdd component

apps/store/src/components/PriceCalculator/AutomaticField.tsx, apps/store/src/services/PriceCalculator/data/SE_PET_CAT.ts, apps/store/src/services/PriceCalculator/data/SE_PET_DOG.ts
- See title.
- This is needed to display dropdowns for year/month in the date picker. The values are somewhat arbitrary, but should work for 99% of all cases.
=> GEN-1610 | Set min/max value for pet birth date fields

apps/store/src/components/ProductItem/ProductDetails.tsx
- Add focus outline to the document links inside the `ProductItem` component
- Better accessibility for keyboard users
=> GEN-1611 | Add focus state for document links in `ProductItem`

apps/store/src/components/ProductItem/ProductDetailsHeader.tsx
- Show focus state for the expand button inside `ProductItem`
- Better accessibility for keyboard users
=> Add focus state to `ProductItem` expand trigger

apps/store/src/components/InputDay/InputDay.tsx
- Refactor `DayInput` to allow for keyboard use
- Toggle the expand-icon based on open state
- Better accessibility for keyboard users
=> GEN-1612 | Fix tab navigation in `DayInput`

apps/store/src/features/widget/CalculatePricePage.tsx, apps/store/src/features/widget/Header.tsx, apps/store/src/features/widget/SelectProductPage.tsx, apps/store/src/features/widget/SignPage.tsx, apps/store/src/pages/widget/run/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx, apps/store/src/pages/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx, apps/store/src/pages/widget/run/[flow]/[shopSessionId]/select.tsx, apps/store/src/services/storyblok/storyblok.ts
- Add "show back button" option in the CMS story
- Optionally show back button in the Widget header
- When loaded in a WebView without browser chrome, the user has no way to go back to the previous page.
- This is an experiment - let's see what we think of the design.
=> GEN-1616 | Show optional back button in Widget

apps/store/src/components/QuickAdd/QuickAddInfoDialog.tsx
Make sure `Dialog.Content` isn't covering the whole screen
https://github.com/HedvigInsurance/racoon/assets/6661511/9c68a796-4e34-4ce7-9b76-1d454c2b4550
=> Make sure click outside dialog content closes the dialog

apps/store/src/components/QuickAdd/QuickAddInfoDialog.tsx
- Remove inline padding in mobile
- Use dynamic viewport height to avoid dialog being to tall when browser ui is visible in mobile browsers
https://github.com/HedvigInsurance/racoon/assets/6661511/7386aa65-2b7d-4f31-881a-ad428a3ea54d
=> QuickAddInfoDialog / Mobile fixes

apps/store/src/features/widget/usePublishWidgetInitEvent.ts
- Send widget event with request ID but don't remove from URL
- We need to pick this up after the redirect to the start of the widget flow and send when creating the shop session.
=> Don't remove request ID from URL after sending widget event

apps/store/src/utils/formatter.ts
- Remove log to datadog in render function, just log to console
- We run the code on the server, which mean we can't reliably send the log to datadog (document doesn't exist)
=> Don't log to Datadog in render function

apps/store/src/components/InputDay/InputDay.tsx
- Add hidden element that gets focus when the popover is opened
- Solve the issue where the month dropdown is autofocused and not initially tappable on iOS Safari
- I couldn't find any option in radix to be able to override this behavior
=> GEN-1624 | Fix not being able to tap month dropdown (iOS)

apps/store/public/locales/en/cart.json, apps/store/public/locales/sv-se/cart.json, apps/store/src/components/QuickAdd/QuickAddInfoDialog.tsx
- Remove spacing before read more button to align properly
=> Remove spacing before read more button to align properly

apps/store/src/pages/[[...slug]].tsx, apps/store/src/pages/cart/resume/[shopSessionId].tsx, apps/store/src/pages/manypets/[[...slug]].tsx, apps/store/src/pages/reusable-blocks/[...slug].tsx, apps/store/src/pages/widget/[[...slug]].tsx, apps/store/src/pages/widget/preview/[[...slug]].tsx, apps/store/src/services/storyblok/useEditableStory.ts
Fix live preview when editing Storyblok content
There's a bug in built-in solution, found it and provided our own correct implementation
Restores editing experience
=> Replace useStoryblokState with our own useEditableStory hook which does not have revert-to-original bug

apps/store/src/blocks/ButtonBlock.tsx, apps/store/src/blocks/TrustpilotBlock.tsx, apps/store/src/components/TextWithLink.tsx, packages/ui/src/components/Button/Button.tsx
- Add support for rel attribute on Button, TexWithLink and ButtonBlock
When we have `target=_blank"` Peter wants the default `rel` value to be `noopener` and if he adds custom attributs from Storyblok he wants to override that value. 
Updated behaviour requested by Peter
=> Add support for rel attribute on Button and TextWithLink

apps/store/src/components/ProductReviews/ProductReviews.tsx, apps/store/src/services/productReviews/productReviews.types.ts, apps/store/src/services/productReviews/productReviews.utils.ts
* Adds tab for _Trustpilot_ reviews; When clicked we'll shown _Trustpilot Widget_. _Trustpilot_ reviews will be enabled down in the stack.
First step to get _Trustpilot_ reviews into _ProductReviews_ feature.
=> GEN-1645 - feat(ProductReviews): add truspilot tab

apps/store/src/blocks/TrustpilotReviewsBlock.tsx, apps/store/src/components/ProductReviews/ProductReviews.tsx, apps/store/src/services/trustpilot/TruspilotWidget.tsx
* Show _Trustpilot widget_ when _Trustpilot_ tab is clicked
Part of adding _Trustpilot_ reviews into _ProductReviews_ block.
=> GEN-1645 - feat(ProductReviews): add trustpilot widget

apps/store/src/components/ProductReviews/ProductReviews.tsx, apps/store/src/components/ProductReviews/ReviewTabs.tsx
* Extract tabs into its own component: `ReviewTabs`. As we show it twice, for `ProductReviews` component and reviews dialog, it makes sense to reuse it.
Can be tested [here](https://hedvig-dot-com-git-gen-1645-refactreview-tabs-hedvig.vercel.app/se/forsakringar/olycksfallsforsakring/av)
Avoid code duplication.
=> GEN-1645 - refact(ProductReviews): extract ReviewTabs component

apps/store/src/components/ProductReviews/ProductReviews.tsx, apps/store/src/components/ProductReviews/ReviewsDialog.tsx
* Refactoring: extract `ReviewsDialog` into its own component.
Can be tested [here](https://hedvig-dot-com-git-gen-1645-refactreviews-dialog-hedvig.vercel.app/se/forsakringar/olycksfallsforsakring/av)
Makes `ProductReviews` component cleaner.
=> GEN-1645 - refact(ProductReviews): move dialog to separate component

apps/store/src/blocks/TrustpilotBlock.tsx, apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx, apps/store/src/components/ProductPage/ProductPage.tsx, apps/store/src/components/ProductPage/ProductPage.types.ts, apps/store/src/components/ProductPage/ProductPageContext.tsx, apps/store/src/components/ProductReviews/ProductReviews.tsx, apps/store/src/components/ProductReviews/ReviewTabs.tsx, apps/store/src/features/memberReviews/TrustpilotDataProvider.tsx, apps/store/src/features/memberReviews/trustpilot.tsx, apps/store/src/pages/[[...slug]].tsx, apps/store/src/pages/widget/[[...slug]].tsx, apps/store/src/pages/widget/preview/[[...slug]].tsx, apps/store/src/services/storyblok/getStoryblokPageProps.ts, apps/store/src/services/storyblok/storyblok.ts
* 🙅🏻 Stop using _Jotai_ for storing Trustpilot data (I was having an issue with multiple stores). _Trustpilot_ data is now served via its own _React Context_
Easier to work with. In order to make _Trustpilot_ data available one just need to call `fetchTrustpilotData` (`memberReviews/trustpilot.ts` file) server side and pass the result to `TrustpilotDataProvider`.
=> GEN-1673 - refact(trustpilot): provider Trustpilot data from a context provider

apps/store/src/blocks/ProductPageBlock.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/components/ProductReviews/ProductAverageRating.tsx, apps/store/src/services/storyblok/storyblok.ts
* Transform `ProductAverageRatingBlock` into a component: `ProductAverageRating`. It's placement is defined by code so it doesn't need to be a block anymore.
* Add **showAverageRating** setting to `ProductPage`. When toggled on, we'll be showing `ProductAverageRating` bellow "Get your price button"
=> GEN-1686 - refact(ProductAverageRating): make it availbe on purchase form

apps/store/src/blocks/ProductReviewsBlock.tsx, apps/store/src/components/ProductReviews/ProductReviews.tsx, apps/store/src/components/ProductReviews/useReviews.ts
* `useReviews`: refact _initial selected score_ logic. It's simpler now.
* `ProductReviewsBlock`: adds a `productAverageRatingThreshold` setting that's being used for setting initial selected tab.
=> GEN-1686 - feat(ProductReviews): set default tab based on product average rating threshold

apps/store/src/pages/widget/run/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx, apps/store/src/pages/widget/run/[flow]/[shopSessionId]/select.tsx, apps/store/src/services/Tracking/Tracking.ts, apps/store/src/services/Tracking/TrackingContext.tsx
- Added `sessionData` field which includes information about `channel` and `partner`
```
{ sessionData: { channel: 'store' } | { channel: 'widget', partner: string } }
```
Requested by Sonny.
=> GEN-1691 - chore(widget-tracking): added session data to tracking

apps/store/src/components/ProductReviews/ReviewsDialog.tsx
Customise scrollbar so they appear roughly the same in all browsers.
Note: CSS specification includes two properties that can be used for that purpose: `scrollbar-width` and `scrollbar-color` but at the time only _Firefox_ implements it. That's why we need declarations for `-webkit` based browsers like _Chrome_ and _Safari_. 
**Chrome**
https://github.com/HedvigInsurance/racoon/assets/19200662/24e4df7e-42ed-4e70-8afe-6b1e5d73c14e
**Safari**
https://github.com/HedvigInsurance/racoon/assets/19200662/69ca0cc0-9cbd-4e24-9d3b-d473668faab4
**Firefox**
https://github.com/HedvigInsurance/racoon/assets/19200662/fd7b75ec-4948-4877-ae9d-2ce42e04ade9
Please, give it a try :)
We wanted to move away from how PC scrollbar looks like, while customising into something that blends in more naturally in our …
=> GEN-1696 - styles: custom styles for scrollbar. Make appear roughly the same on all browsers.

apps/store/src/components/ProductReviews/ReviewsDialog.tsx
* Updated `Dialog` overlay `background` color so it looks more like into its frosted counterpart.
* Minor style changes on `ReviewsDialog`
Frosted overlay was causing issues with `Dialog`, at least when used in `ReviewsDialog`. I could find some mentions about [performance issues](https://github.com/tailwindlabs/headlessui/issues/690) involving `backdrop-filter: blur`. Removing frosted overlay from `ReviewsDialog` made it work smoothly so we decide to move forward without it.
=> GEN-1696 - styles(ReviewsDialog): remove frosted overlay

apps/store/public/locales/en/common.json, apps/store/public/locales/sv-se/common.json, apps/store/src/components/ProductReviews/ReviewsDialog.tsx
* Added a disclaimer copy about _Trustpilot_ reviews. It should be shown on top when _Trustpilot_ tab is active.
* Reduce font size of "Shows latest reviews with comments" text shown after last review - only when _Product_ tab is active.
**Trustpilot**
---
**Product**
Design changes requested by Peter.
=> GEN-1696 - styles(ReviewsDialog): added reviews disclaimers on different places

apps/store/src/components/ProductReviews/ProductReviews.tsx
* Set hight for `ProductReviews` tab content.
https://github.com/HedvigInsurance/racoon/assets/19200662/5bbec2b8-4454-4a81-a0e1-da6ed36f205f
The idea behind it is to avoid layout shifts between tabs. Observe "View Reviews" button.
=> GEN-1696 - styles(ProductReviews): fix tab content height (avoiding layout shift between tabs)

apps/store/src/blocks/ProductReviewsBlock.tsx, apps/store/src/components/ProductReviews/ProductReviews.tsx
* Added a _Default Active Tab_ setting for `ProductReviews`. Deprecated setting - _Product Average Rating Threshold_ - will be removed after this get's merged.
https://github.com/HedvigInsurance/racoon/assets/19200662/fe4402dd-b3ef-4170-9b78-8aaf2f5cc311
The idea is to replace the _Product Average Rating Threshold_ setting for a simpler one.
=> GEN-1696 - refact(ProductReviewsBlock): get default tab as a CMS setting

apps/store/src/blocks/ProductPageBlock.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/components/ProductReviews/ProductAverageRating.tsx
* Update `ProductPage` block so it supports different sources for the average rating to be shown: product or trustpilot.
https://github.com/HedvigInsurance/racoon/assets/19200662/bfa480d1-a35c-4829-b10d-0dd80e7a555e
Peter want to be able to configure which average rate - product or trustpilot - that should be render. Despite of that, we always generate structured data about product average rating.
=> GEN-1696 - feat(ProductAverageRating): support average rating source

apps/store/src/components/LayoutWithMenu/ProductMetadataContext.tsx
* Make sure we hydrate   _product metadata atom_ during build/SSR, avoiding wrong HTML being generated as a result of the wrong data being stored in _product metadata atom_.
**Context**
I've noticed some hydration errors involving `ProductCardBlock` and the English version of the landing page (`se-en`).
https://github.com/HedvigInsurance/racoon/assets/19200662/cbb9ebb9-016a-4c3d-9c1d-e21381aed5fc
The reason we get hydration errors here is because, on the server, we end up entering in an `if` statement that avoids rendering `ProductCardBlock` while linking into a story that doesn't belong to a product or a product category.
**The reason why that happens is because the `productMetada` used for `getLinkType` function holds the swedish product metadata, despite the fact we're loading the …
=> GEN-1715 - fix(ProductCardBlock): hydration errors on landing page (se-en)

apps/store/src/components/PriceCalculator/WarningPrompt/WarningPrompt.stories.tsx, apps/store/src/components/PriceCalculator/WarningPrompt/WarningPrompt.tsx
- Add new WarningPrompt that we can use in PurchaseForm to display warnings from a PriceIntent
To be able to display decomisioned/not owner of car warning
=> GEN-1690 / Add WarningPromt to be used inside PurchaseForm

apps/store/src/components/PriceCalculator/PriceCalculator.tsx, apps/store/src/components/PriceCalculator/Warning/Warning.tsx, apps/store/src/components/PriceCalculator/Warning/WarningPrompt/WarningPrompt.tsx
When clicking "Edit" button, the logic is that you will go back to the previous step in the price form where you can edit reg number.
It made more sense to go back rather then block continuing to the next step since the happy path is smoother that way when you click "I understand".
https://github.com/HedvigInsurance/racoon/assets/6661511/e58b7f88-f70a-4f7b-bbdb-1197debc927d
User shoulkd be able to go back and edit reg number
=> GEN-1692 / Go back to previous step to edit reg nr when clicking edit in warning dialog

apps/store/src/blocks/USPBlock.tsx, apps/store/src/components/ProductPage/ProductDocuments.tsx, packages/ui/src/components/Text/Text.tsx
- Set `<p>` as default element to render for `Text` component (default was a div before)
- Update some heading levels in different blocks
Request by Peter, improve markup semantics
=> GEN-1703 / Update what tags we render for text elements

apps/store/src/components/PriceCalculator/PriceCalculator.tsx, apps/store/src/components/PriceCalculator/Warning/Warning.tsx
Prevent going to the next form section when showing the warning dialog. Add a click handler for going to next section when clicking "I understand". This fixes the bug where you sometimes couldn't close the the dialog because we set autofocus on the on the next form section, as reported from the test session.
- Remove `goBackToPreviousSection` since we will default to not proceeding when showing the warning dialog
- Add `goToNextSection` and pass it to `Warning` 
https://github.com/HedvigInsurance/racoon/assets/6661511/e03adf4d-1483-47bf-883e-be2b9e226bf5
https://github.com/HedvigInsurance/racoon/assets/6661511/a106f5a9-c09d-4be4-bce9-6d75b9de7f11
Fix the bug reported from test session https://www.notion.so/hedviginsurance/On-mobile-when-getting-prompted-the-I-understand-I-can-t-click-I-und …
=> Prevent going to the next step in PriceCalculator when showing warning

apps/store/src/blocks/AccordionItemBlock.tsx
Render Accordion trigger text as span instead of p
Shouldn't nest a p tag inside a heading
=> Render Accordion trigger text as span

apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx
* Avoid structured data being added twice to the same document.
Same fix was used [here](https://github.com/HedvigInsurance/racoon/pull/2330)
Tried to abstract it into a shred component but it doesn't work as `next/head` has some restrictions about what can be used as its children.
Also spent some time trying to figure it out why is that happening but could not find any explanation. It works fine locally but it's possible to reproduce on staging.
=> GEN-1750 - fix: added organization structured data for landing pages only

apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx
* Update `renderRichText` function setting so it avoids hydration errors while rendering rich text's text style markers.
More info on this slack [thread](https://hedviginsurance.slack.com/archives/C041SD67G82/p1706628411035529?thread_ts=1706619155.314889&cid=C041SD67G82)
=> GEN-1764 - fix(renderRichText): avoid hydration errors for rich text's text style markers

apps/store/next-csp.config.js
- Allow linkedin in our `script-src` CSP config
Cleanup [CSP violations](https://app.datadoghq.eu/dashboard/tft-qsw-5iu/vercel-hedvig-com?fullscreen_end_ts=1706696251347&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=overview&fullscreen_start_ts=1706091451347&fullscreen_widget=1271882006666618&refresh_mode=sliding&view=spans&from_ts=1706694450075&to_ts=1706695350075&live=true)
=> GEN-1739 - chore(csp): allow linkedin (tracking) for sript-src

apps/store/src/blocks/HeaderBlock.tsx, apps/store/src/components/CartPage/CartPage.tsx, apps/store/src/components/CartPage/PageDebugDialog.tsx, apps/store/src/components/CheckoutPage/CheckoutPage.tsx, apps/store/src/components/ConfirmationPage/StaticContent.tsx, apps/store/src/components/ContactUs/ContactUs.tsx, apps/store/src/components/DebugDialog/DebugShopSessionSection.tsx, apps/store/src/components/ForeverPage/ForeverPage.tsx, apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx, apps/store/src/components/LayoutWithMenu/ProductMetadataContext.tsx, apps/store/src/components/PaymentConnectPage/IdleState.tsx, apps/store/src/components/PriceCalculator/PriceCalculatorSection.tsx, apps/store/src/components/ProductPage/PageDebugDialog.tsx, apps/store/src/components/ProductPage/PurchaseForm/DeductibleSelector.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx, apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx, apps/store/src/features/memberArea/PaymentsSection/PaymentConnection.tsx, apps/store/src/features/memberArea/components/Menu.tsx, apps/store/src/features/retargeting/useApiRedirectEffect.ts, apps/store/src/features/widget/SignPage.tsx, apps/store/src/pages/payment/connect-legacy/error.tsx, apps/store/src/pages/payment/connect-legacy/start.tsx, apps/store/src/services/adyen/useTokenizePaymentDetails.ts, apps/store/src/services/trustly/TrustlyIframe.tsx, apps/store/src/utils/l10n/useRoutingLocale.ts
Convert very common pattern of getting current routing locale into separate hook
```
- const { routingLocale: locale } = useCurrentLocale()
+ const locale = useRoutingLocale()
```
Would simplify moving away from next routing i18n - we're going to need a lot more `useRoutingLocale()` calls
=> Simplify locale usage with useRoutingLocale() hook

apps/store/src/features/blog/ArticleTeaser/ArticleTeaser.tsx, apps/store/src/services/storyblok/Storyblok.helpers.ts
Fix links to blog articles
We were passing `href='se/blogg/...'` to link where absolute path or full URL object were expected
=> Fix links in blog category

apps/store/.storybook/preview.tsx
* Added `vanilla-extract-css` global styles to `storybook`
Without it storybook stories look a little bit off as it would be missing some style definitions.
=> fix(storybook): make sure global styles (vanilla extract) are included

apps/store/src/components/LayoutWithMenu/ProductMetadataContext.tsx, apps/store/src/pages/_app.tsx, apps/store/src/utils/globalStore.ts
Remove custom globalStore we were using for productMetadata atom - default one works just as well
This is a step towards correct usage of jotai with app router
=> Use default jotai store for globalProduceMetadata

apps/store/public/locales/en/reviews.json, apps/store/public/locales/sv-se/reviews.json, apps/store/src/components/ProductReviews/ProductAverageRatingV2.tsx, apps/store/src/components/ProductReviews/ProductReviewsV2.css.ts, apps/store/src/components/ProductReviews/ProductReviewsV2.tsx, apps/store/src/components/ProductReviews/ReviewsDialogV2.tsx
* Update `ReviewsDialog` so it takes a `Header` section so it can be used in different contexts: When opening the Dialog through `ProductReviewsBlock` we should should the _pillow_ version; When opening it via `ProductAverageRating` we should shown the _average rating_ one.
=> GEN-1835 - feat(ReviewsDialog): accept a Header section so it can be used in different contexts - ProductAverageRating and ProductReviews

apps/store/src/components/ProductReviews/ProductAverageRatingV2.css.ts, apps/store/src/components/ProductReviews/ProductAverageRatingV2.tsx
* `ProductAverageRating ` UI changes.
* Migrate to `@vanilla-extract/css`
=> GEN-1835 - styles(ProductAverageRating): product reviews v2 UI changes

apps/store/public/locales/en/reviews.json, apps/store/public/locales/sv-se/reviews.json, apps/store/src/components/ProductReviews/ReviewCommentV2.css.ts, apps/store/src/components/ProductReviews/ReviewCommentV2.tsx, apps/store/src/features/memberReviews/memberReviews.types.ts, apps/store/src/features/memberReviews/productReviews.ts, apps/store/src/features/memberReviews/productReviews.utils.ts
* Added a _tag_ for review comments that identifies which product they're associated with. That's gonna be more relevant later.
=> GEN-1835 - feat(ReviewComment): added a tag for the review comment

apps/store/src/blocks/AverageRatingBanner.css.ts, apps/store/src/blocks/AverageRatingBanner.tsx, apps/store/src/services/storyblok/storyblok.ts
* Added `AverageRatingBanner` which will be used to replace `TrustpilotBlock`
Next step is use actual data from `productReviews` service (next PR).
=> GEN-1835 - feat: added AverageRatingBanner which will replace TrustpilotBlock

apps/store/src/blocks/HeaderBlock.tsx, apps/store/src/components/Header/Header.stories.tsx, apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
Use React's `startTransition` for opening mobile main menu
I've seen "Menu" button in list of elements responsible for long INP, this should fix it
=> Use transition for opening mobile main menu (faster INP)

apps/store/src/blocks/PageBlock.tsx, apps/store/src/components/ProductPage/ProductPage.tsx
Price calculator was particularly slow after SSN section submit
I tracked root cause to the way we subscribed to session change for tracking and discount banner display
We've run `useEffect` on top level of `ProductPageBlock` which led to full rerender every time customer or session changed even if it had nothing to do with direct children on a block.  I've isolated those effects into childless components.  Rerender after updating customer is not ~3x cheaper
Optimize slow interaction
=> Prevent full page rerender after initial shopSessionCustomerUpdate

apps/store/src/blocks/HeaderBlock.tsx
Prevent rerendes of desktop top menu when mobile menu opens/closes
=> Prevent rerendering TopMenuDesktop when mobile menu is opened or closed

apps/store/src/features/carDealership/CarTrialExtension.graphql, apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx, apps/store/src/features/carDealership/PayForTrial.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx, apps/store/src/utils/Features.ts
Add MyMoney consent component to `TrialExtensionForm` och `PayForTrial` since we want to make it possible to accept or change consent at any point.
Next PR: add update consent mutation
MyMoney project
=> Add MyMoney consent to car trial extension

apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx, apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsent.tsx, apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsentAtom.ts, apps/store/src/features/carDealership/PayForTrial.tsx, apps/store/src/features/carDealership/TrialExtensionForm.tsx
For compliance we can't update the user consent when a user ticks the checkbox. Instead we should send consent state once the user clicks either the sign or connect payment button.
Also persist the `checked` state in an atom if a user closes the browser or reloads the page
https://github.com/HedvigInsurance/racoon/assets/6661511/42fdb05f-bf3b-4277-a4a5-272adf9fc2a7
For compliance
=> Only send UpdateConsent mutation on sign/connect payment button click

apps/store/src/components/ProductData/ProductDataProvider.tsx
Instead of hydrate + effects used to sync product data atoms with current page eventially simply set new value on every render
- It's stable (jotai skips update if values are equal, meaning atom dependencies will be updated only once)
- It's immediate, no lag between provider being rendered and atoms taking new value (unlike previous useEffect solution)
=> Use direct jotai writes in ProductData provider

apps/store/.storybook/decorators.tsx, apps/store/.storybook/preview.tsx, apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx, apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/SwitchingAssistantSection.stories.tsx, apps/store/src/components/ProductPage/ProductPageContext.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.stories.tsx, apps/store/src/features/carDealership/TrialExtensionForm.stories.tsx
- Another simplification of `ProductPageContext` - rely on `productData` from outer context instead of re-providing it
-  Update usage in Storyblok, fix some broken stories, move default providers around
=> Remove productData from ProductPageContext, use productDataAtom instead

apps/store/src/components/PriceCalculator/PriceCalculatorDynamic.css.ts, apps/store/src/components/PriceCalculator/PriceCalculatorDynamic.tsx
Added loading indicator for PriceCalculator.  See attached video (loading speed artifically slowed down)
<a href="https://app.graphite.dev/media/video/GLY3tSM85RFBvAf6lFNA/a3107499-4988-4e60-b340-874725ba6250.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/GLY3tSM85RFBvAf6lFNA/a3107499-4988-4e60-b340-874725ba6250.mov">Screen Recording 2024-02-29 at 15.01.38.mov</video>
=> Add loading skeleton for price calculator

apps/store/src/components/ProductReviews/PillowHeader.tsx
* Fix an issue with "pillow header" disclaimer text.
That translation key held a link placeholder before but not it doesn't so instead of render with `TextWithLink` component we should use regular `Text` component.
=> fix(PillowHeader): disclaimer text

apps/store/src/components/TextWithLink.tsx
* Provide a better default for the case no link placeholder was given
Before we're rendering `<>props.children</>` on such cases and that's probably a mistake. What I think we want is to render `<>{props.children}</>` so `TextWithLink` is still able to render a some text that doesn't include a link placeholder ([[link placeholder]])). I'm also adding a log for such cases as using `Text` is better suitable for such cases.
=> fix(TextWithLink): provide a better default for the case no link placeholder was given

apps/store/src/components/Pillow/Pillow.tsx, apps/store/src/components/ProductPage/PurchaseForm/ProductHero/ProductHero.css.ts, apps/store/src/components/ProductPage/PurchaseForm/ProductHero/ProductHero.tsx, packages/ui/src/index.ts
- Make ProductHero image a priority
- Reduce pillow image quality 73 -> 50
- Reduce default image block quality 73 -> 70
Optimize LCP metric for product pages
=> Optimize product pillow image size

apps/store/src/components/Animations/LottieAnimation.tsx, apps/store/src/components/PriceCalculator/PriceCalculatorDynamic.css.ts, apps/store/src/components/PriceCalculator/PriceCalculatorDynamic.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseFormErrorDialog.tsx
<a href="https://app.graphite.dev/media/video/GLY3tSM85RFBvAf6lFNA/fc16fe3c-82a6-429b-a192-1a594bcb8a2e.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/GLY3tSM85RFBvAf6lFNA/fc16fe3c-82a6-429b-a192-1a594bcb8a2e.mov">Screen Recording 2024-03-01 at 11.16.24.mov</video>
Better UX:
- Show product review summary when purchase form is in loading state to avoid layout shift
Refactoring:
- Refactor purchase form render control flow to be more linear and readable
- Extract PurchaseFormErrorDialog into separate module
=> Show product review summary in loading state to avoid layout shift

apps/store/src/services/priceIntent/PriceIntentService.ts
Fix resetting priceIntent after adding to cart.  Allows to buy to 2+ cat/dog/car items in the same session
Not clear when it broke, but the fix is trivial - reset cached priceIntent creation promise when resetting corresponding cookie
=> Fix resetting purchase form after adding item to cart

apps/store/src/components/CheckoutPage/CheckoutPage.tsx, apps/store/src/components/TextField/TextField.tsx, apps/store/src/features/widget/SignPage.tsx, apps/store/src/utils/customer.ts
* Fix an issue where users with associated email couldn't proceed with signing flow. More info [here]([url](https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1709630294967369))
We simplified the logic used to collect email during signing flow [here](  // Collect emails of new customers as well as returning customers with no email
return !customer?.email). Basically we want to collect email whenever we don't have that info at the moment one’s trying to sign. However the data used for signing comes from HTML `form`s so even when we don't need to collect email we still want to mount email form field in a hidden format.
=> fix: should collect email logic

apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx, apps/store/src/components/CheckoutPage/CheckoutPage.tsx, apps/store/src/constants/sign.constants.ts, apps/store/src/features/widget/SignPage.tsx, apps/store/src/graphql/ShopSessionSigningFragment.graphql, apps/store/src/services/bankId/bankId.types.ts, apps/store/src/services/bankId/useBankIdCheckoutSign.ts, apps/store/tsconfig.json
* Update _StartSigning_mutation / _Signing_ query so it users new API schema
* Update `startSign` function so it passes down `bankidAppOpened` information. That flag is gonna be used to provide UI feedback when QR were scanned during sign flow.
* `BankIdV6Dialog` update: Make sure _try again_ button works (shown in case of errors) works for both flows: _login_ and _sign_
https://github.com/HedvigInsurance/racoon/assets/19200662/1ca1e279-54dd-4fa4-91b9-32130e98d912
Part of UI changes requested for a better error handling during _sign_ flow.
=> GEN-1871 - feat(bankid-sign): added UI form when qr code is scanned

apps/store/public/mockServiceWorker.js, apps/store/src/components/CookieConsentLoader.tsx, apps/store/src/pages/_app.tsx
- Load OneTrust (cookie banner) directly instead of relying on GTM to load it
- Load GTM after cookie consent has been given (or previous setting has been loaded)
Performance optimization, INP and initial load size
=> Load OneTrust before GTM

apps/store/public/locales/en/bankid.json, apps/store/public/locales/sv-se/bankid.json, apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.css.ts, apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.stories.tsx, apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx
* Added a "open BankId App on the same device" link. It's going to be rendered only on desktop and it can be used to trigger BankdId app.
As requested by design.
=> GEN-1871 - feat(bankid): added "open on the same device" link

apps/store/src/blocks/VideoBlock.tsx, apps/store/src/services/storyblok/Storyblok.helpers.ts
Preload and load video poster images from next instead of Storyblok.
A step to improve the LCP core web vital. By using `getImageProps` the images are now served from next server which reduces the TTFB and load delay of poster images.
To further improve LCP, we preload the images to improve load times.
=> tech: [RND-531] Preload and move video poster image to vercel 

apps/store/src/blocks/ProductPageBlock.tsx
Render coverage block of product page after it first comes into view
Optimization: smaller DOM and faster page load
- 30% less DOM elements
- ~15% smaller document size
- ~10% faster hydration
=> Lazy render coverage block on Product Page (30% smaller DOM)

apps/store/src/blocks/ComparisonTableBlock.tsx, apps/store/src/blocks/HeaderBlock.tsx, apps/store/src/components/ContactUs/ContactUs.tsx, apps/store/src/components/Header/TopMenuDesktop/TopMenuDesktop.tsx, apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx, apps/store/src/components/ProductPage/PurchaseForm/ComparisonTableModal.tsx, apps/store/src/services/CustomerFirst.tsx, apps/store/src/utils/useResponsiveVariant.ts
Replace most usages of `useBreakpoint` with `useResponsiveVariant`
Main use case if hydration-compatible selection of mobile vs desktop variant
Main driving goal was to make page header smaller - we don't want to keep desktop menu in DOM on mobile and we don't want to render it either
=> Add useResponsiveVariant as hydration-safe way to select desktop or mobile

apps/store/src/pages/_app.tsx, apps/store/src/utils/Features.ts
Only load cookie banner and GTM when feature flag is enabled.  We're going to have it on in production and for debugging when needed and disabled otherwise.  Before it was controlled by GTM
Do you love cookie banners when debugging?  I don't :)
=> Toggle cookie banner and GTM behind feature flag

apps/store/src/pages/_app.tsx, apps/store/src/services/logger/client.ts
Delat Datadog client initialization.  It's safe (logs written before init are buffered) and improves scripting time before page is interactive
=> Delay Datadog client init until after page is interactive

apps/store/src/blocks/VideoBlock.tsx
Make sure video poster images aspect ration is calculated
It's required to have both width and height in order for `getImageProps` to work correctly
=> fix: Set aspect ratio for video posters

apps/store/src/components/BankIdDialogDynamic.tsx, apps/store/src/components/BankIdV6Dialog/BankIdV6DialogDynamic.tsx
I've noticed an unexpected loading dialog while loading home page. I've accidentally added that..
https://github.com/HedvigInsurance/racoon/assets/19200662/366988b9-f7f5-4a32-86b3-cfcb81a47401
What I was trying to do is having a loading state for bankid dialog in case it gets used before being loaded (it's been lazy loaded right now). The issue tho is that those dialogs doesn't get opened directly by a user interaction so it's hard to load it only when it's needed. So I removed the loading state as I think it will probably be always loaded/cached by the time it gets used so no issues here. Worst case scenario is some delay between clicking on login/sign and getting that dialog opened but I think that's gonna be rare as we trigger the loading of those dialogs code right after any page …
=> fix(bankid): avoid showing an unexpected loading state while the dialog gets lazy loaded

apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx, packages/ui/src/components/Dialog/Dialog.tsx
Make Dialog open/close change a transition
This should improve responsiveness (INP) for most dialogs.  We still have 3 places where we use  '@radix-ui/react-dialog' directly, 1 already uses startTransition
=> Wrap ui/Dialog.Root open/close change into startTransition (performance)

apps/store/package.json, apps/store/src/blocks/RichTextBlock/RichTextBlock.tsx, yarn.lock
* Bumps `storyblok-rich-text-react-renderer@2.9.2` and removed unecessary sanitization
I've added some sanitiazation code to avoid hydration errors #3881 as a workaround while a fix was not included in the library itself. The fix is merged and available on version 2.9.2 (more info [here](https://github.com/claus/storyblok-rich-text-react-renderer/pull/46)) so I'm bumping the package and removing my workaround.
=> chore(storyblok-rich-text-react-renderer): bump version to 2.9.2

apps/store/next-csp.config.mjs, apps/store/next.config.mjs
We used to pass `cv: undefined` to storyblok API when loading redirects unless env variable with cache version was defined
Storyblok returned some old data for that case, while not passing `cv` correctly fetched latest data
=> Fix loading Storyblok redirects

apps/store/src/app/api/member-reviews/route.ts, apps/store/src/components/ProductReviews/ProductAverageRating.tsx, apps/store/src/components/ProductReviews/ProductReviews.tsx, apps/store/src/components/ProductReviews/ReviewsDialog.tsx, apps/store/src/features/memberReviews/memberReviews.ts, apps/store/src/features/memberReviews/memberReviews.types.ts
* `features/member-reviews`: Added `fetchReviewsByScore` function which will be used to get reviews information - _reviews by score_ - given `productId`(s). When no `productId` is provided it will get it for all the products.
* `api/member-reviews/index.tsx`: Small _api route_ to make `fetchReviewsByScore` accessible client side. We're gonna be able to remove this step when we migrate to RSC.
* `ReviewsDialog`: It now fetches reviews client side, which will reduce the payload we send to our users. Consumers of `ReviewsDialog` can now give the `productId`(s) which should be used while fetching reviews.
This is a series of PRs that's gonna be used as the foundation for getting the following request done by the usage of RSC:
* Being able to render `AverageRatingBanner` block with data about …
=> GEN-1860 - refac(ReviewsDialog): fetch reviews client side

apps/store/src/components/ProductReviews/ReviewComment.tsx, apps/store/src/features/memberReviews/memberReviews.utils.ts
* Update the way _review tags_ are obtained. There is a translation key for each product type that follows the patter: `[productId]__REVIEW_COMMENT_TAG`. E.g: `SE_CAT_REVIEW_COMMENT_TAG`. Before I was storing this for each comment on _redis_ which it seems wrong. Now I have a `attributedTo` field for each comment which indicates which product it's connected to. I then build that translation key at the UI level inside `ReviewComment` comment.
It feels better this way.
**Not to myself**: Remember to remove `tag` deprecated field from comments stored on _redis_.
=> GEN-1860 - refact(ReviewComment): move tag logic to component level

apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx, apps/store/src/services/bankId/useBankIdCheckoutSign.ts
* Added custom actions for baknid sign flow
The idea is to keep an eye on signing sessions after bankid v6 changes get released.
More info [here](https://hedviginsurance.slack.com/archives/C06GPLWA8FM/p1710335651415919?thread_ts=1710270579.975809&cid=C06GPLWA8FM)
=> GEN-1930 - track(bankid-sign): add custom actions for better discoverability

apps/store/src/components/CookieConsentLoader.tsx, apps/store/src/services/gtm.tsx
Send OneTrust consent settings to GTM via native API instead of relying on GTM tags and triggers to load consent settings
Previous mechanism broke down when we started loading GTM after OneTrust.  Using this as a chance to simplify our setup
=> Forward OneTrust consent settings directly to GTM

apps/store/src/app/debugger/actions.ts, apps/store/src/app/debugger/components/CreateSessionForm/CreateSessionForm.tsx, apps/store/src/pages/api/session/create.ts, apps/store/src/services/persister/Persister.types.ts, apps/store/src/services/persister/app-router/AppRouterCookiePersister.ts, apps/store/src/services/priceIntent/app-router/PriceIntentService.utils.ts, apps/store/src/services/shopSession/app-router/ShopSession.utils.ts
Implement the session debugging logic in a server action.
Used services relied on the `req` and `res` objects to handle cookies, which isn't working in app router. The app router cookie persister is created in order to reuse the same services but with the `cookies` util from next.
=> refactor: [RND-542] Implement customer session debugging logic in server actions

apps/store/src/app/debugger/actions.ts, apps/store/src/app/debugger/components/CreateSessionForm/CreateSessionForm.tsx
Remove the fallback test SSN and validate input on the server side.
We agreed to not fallback to a test SSN for this feature and handle missing input on the server.
=> fix: Validate debug session SSN server side

apps/store/src/features/memberReviews/ProductReviewsMetadataProvider.tsx
- Fix an issue where the same average rating data were being used for multiple products
https://github.com/HedvigInsurance/racoon/assets/19200662/3b7fbf87-7c38-4199-b6e9-ab4689e6f5eb
That happen becuase product reviews atom were being hydrated only once. We need to make sure we have a product reviews
atom per product.
=> GEN-1950 - fix(ProductReviewsMetadataProvider): make sure we have one atom for product

apps/store/src/app/debugger/iframe/page.tsx
Use the current page `host` for the iframe debugger default URL instead of hardcoded localhost.
Set the iframe default URL dynamically so it works in all environments.
=> fix: Use current page host for default iframe debugger URL

apps/store/src/components/GTMLoader.tsx, apps/store/src/pages/_app.tsx, apps/store/src/pages/_document.tsx
* Make sure cookie banner consent doesn't get in into the way of our dialogs.
Sometimes, cookie banner get's into the way of our dialogs which can be anoying:
https://github.com/HedvigInsurance/racoon/assets/19200662/9ad982bb-a2d2-420a-bb67-274a7f6ddd08
An easy way to reproduce this is load a product page with price calculator opened on mobile (`?openPriceCalculator=1`) while having disabled the cache.
That happens for the cases our dialog gets added into the DOM before the cookie consent. Since both are positioned elements in the same stacking context, DOM order is used to determine should should be on top. In this case, cookie banner will be on top which can be annoying.
[Nextjs recommends](https://shorturl.at/gkAQ8) to have cookie consent scripts loaded with `beforeInteractive` …
=> RND-524 - fix(cookie-banner): make sure it doesn't get in the way of our dialogs

apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx
- Remove close button (X) for _BankIdDialog_ success state
That can avoid reaching an inconsistent state inside the app.
=> GEN-1978 - bug(BankIdV6Dialog): remove close button from sucess state

apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx, apps/store/src/services/bankId/useBankIdCheckoutSign.ts
- Add `shop session id` on sign with bankid logs
Better debugging experience in Datadog
=> chore(bankId): include shop session id on sign logs

apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx
I noticed while checking a bunch of ManyPets [sessions](https://www.notion.so/hedviginsurance/90c3e914c86d4d09a000a015fdee61fc?v=c58a688827354418a90e74d4d16319ab) that we've been showing 2 error dialogs.
https://github.com/HedvigInsurance/racoon/assets/19200662/3234586e-7043-4269-9349-27b6faa2d28a
That's unnecessary single we're already handling errors during sign.
Better UX
=> GEN-1970 - fix(ManyPets): unify error handling during signing

apps/store/public/locales/en/bankid.json, apps/store/public/locales/sv-se/bankid.json, apps/store/src/components/BankIdV6Dialog/BankIdV6Dialog.tsx
- Added missing "fail to sign" copy
I forgot to add add and as I was showing "fail to login" for every case.
=> fix(BankIdV6Dialog): added missing "fail to sign" copy

apps/store/src/pages/api/revalidate.ts
- Update revalidate api router so it proper handle "unplubshed" actions
- Take `getStory()` error status into consideration while returning from api route
We've found some logs about missing record. It turned out they're happening as a side effect of unplubishing stories.
=> fix(revalidate): handles "unplubshed" action

packages/ui/package.json, packages/ui/src/components/Button/Button.css.ts, packages/ui/src/components/Button/Button.helpers.ts, packages/ui/src/components/Button/Button.stories.tsx, packages/ui/src/components/Button/Button.tsx, yarn.lock
The goal is to keep the same API for button component as before:
```js
<Button variant="secondary" size={{ base: 'small', lg: 'medium' }} />
```
Did a lot of digging on different approaches. The main challenge is the responsive variants. 
With `sprinkles` it's easy to have single css rules responsive but that would be to verbose in this case. For creating multi variants you could use `recipes`, but they don't provide a way for creating responsive variants. 
So for creating the the responsive styles I looked at the use cases we have, and we only used breakpoint `lg` for responsive styles. So instead of creating styles for all breakpoints we can start with just supporting `base` and `lg`.
I found `recipes` to be a bit overkill for variants so I used …
=> Migrate Button component to vanilla-extract

apps/store/src/app/[locale]/StoryblokLayout.tsx, apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx, apps/store/src/components/StoryblokPage.tsx, apps/store/src/features/carDealership/CarBuyerCmsPage.tsx, apps/store/src/pages/[locale]/[[...slug]].tsx, apps/store/src/pages/[locale]/car-buyer/[contractId]/index.tsx, apps/store/src/pages/[locale]/car-buyer/extension/[[...contractId]].tsx, apps/store/src/services/storyblok/storyblok.ts
Instead of taking `hideMenu` and `hideFooter` from CMS, hardcode it for car-buyer pages.  The only other place where we don't want footer and menu is widget and there we don't use default layout at all
- Final step before removing hideMenu and hideFooter from CMS-controller properties
- Part of making global layout independent of a page that's inside - this is required for supporting CMS pages in app router
- Generate new trial in preview branch
- Go through trial and extension pages, make sure layout is right
- Check navigation between CMS pages under `/se/appDebug`
=> Ignore hideMenu and hideFooter flags from CMS pages, use directly for car-buyer pages

apps/store/src/app/[locale]/StoryblokLayout.tsx, apps/store/src/components/Header/Header.css.ts, apps/store/src/components/Header/TopMenuDesktop/TopMenuDesktop.tsx, apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx, apps/store/src/components/StoryblokPage.tsx, apps/store/src/features/carDealership/CarBuyerCmsPage.tsx, apps/store/src/pages/[locale]/[[...slug]].tsx, apps/store/src/pages/[locale]/car-buyer/[contractId]/index.tsx, apps/store/src/pages/[locale]/car-buyer/extension/[[...contractId]].tsx, apps/store/src/services/storyblok/storyblok.ts
Prevent cart menu item from jumping on desktop when page loads
It was aligned centrally before this PR and jumped to the right when desktop menu variant appeared
=> Prevent layout shift of cart item while loading desktop menu

packages/ui/src/components/Button/Button.tsx
When a ui button component is wrapped in a link (as in `ButtonNextLink` component), we should output an a tag instead of a button tag as specified in [Next docs ](https://nextjs.org/docs/pages/api-reference/components/link#if-the-child-is-a-functional-component)
Before when we used emotion we could use the as prop to let emotion either render and `<a>` or a `<button>` and the typing was not actually not matching the behaviour, but it didn't complain. But now we need to check if a href is provided and either render an `<a>` or a `<button>`
~~I can't find the right way to type this, since forwardRef could either be the an `HTMLAnchorElement` passed from `ButtonNextLink` or a `HTMLButtonElement` passed from a component where we need to pass a ref to a button (see …
=> Make sure Button renders <a> tag when href is passed

apps/store/src/components/LayoutWithMenu/Breadcrumbs.tsx, apps/store/src/components/LayoutWithMenu/Breadcumbs.css.ts
Convert Breadcrumbs styling to vanilla-extract
In the next PR I plan to handle `hideBreadcrumbs` page property with pure CSS, which makes it compatible with app router
=> Convert Breadcrumbs styles to vanilla-extract

apps/store/scripts/storyblok-analyze-stories.cjs, apps/store/src/app/[locale]/StoryblokLayout.tsx, apps/store/src/blocks/PageBlock.tsx, apps/store/src/components/LayoutWithMenu/Breadcumbs.css.ts, apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
Refactor breadcrumbs display to rely on main[data-hide-breadcrumbs] DOM attribute
This way we can make layout independent from story data.  Required for app router where we want to keep layout during navigation instead of rerendering it
=> Refactor page.hideBreadcrumbs to work on CSS, without layout knowing about page info

apps/store/src/services/Tracking/Tracking.ts, apps/store/src/services/Tracking/tracking.test.ts
Add a conditional field to user data, `gem`, that passes a gmail address formatted according to Googles documentation https://developers.google.com/google-ads/api/docs/conversions/enhanced-conversions/web#python
> Remove all periods (.) that precede the domain name in gmail.com and googlemail.com email addresses
Fix user data tracking
=> Add special case for normalizing gmail addresses

apps/store/src/components/StepperInput/StepperInput.css.ts, apps/store/src/components/StepperInput/StepperInput.stories.tsx, apps/store/src/components/StepperInput/StepperInput.tsx
* Update `StepperInput` so it supports label rendering
Gonna use that for implementing new cross sell card
=> GEN-1893 - feat(StepperInput): support label

apps/store/src/components/InputDate/InputDate.tsx, apps/store/src/components/InputDay/InputDay.tsx, apps/store/src/components/InputSelect/InputSelect.tsx, apps/store/src/utils/useHighlightAnimation.ts
* Update `useHightlightAnimation` implementation so it relies on JS to determine the background that should be used during the animation.
Gonna use that to easily implement that variant of `StepperInput`. With the new implementation of `useHightlightAnimation`, I can get that input animation working by just setting `StepperInput` `backgroud-color` via CSS, instead of making it accept a `backgroundColor` prop  just get it down into `useHIghtlightAnimation`
=> GEN-1893 - refact(useHighlightAnimation): use JS to get element's background color

apps/store/src/components/PageBreadcrumbs/PageBreadcrumbs.tsx
Fix duplication of `structured-data-breadcrumb-list` element during navigation by moving it from `head` to `body`
=> Move breadcrumbs structured data from head to body (prevents duplication)

apps/store/src/components/ConfirmationPage/StaticContent.tsx, apps/store/src/components/ContactUs/ContactUs.tsx, apps/store/src/components/DebugDialog/DebugShopSessionSection.tsx, apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx, packages/ui/src/components/Button/Button.tsx
- Set the default element type for the `Button` component to `button`
- Update anchor buttons to use the `a` element.
Fix broken anchor buttons and provide better TS support.
=> fix: Use `button` props for `Button` by default

apps/store/src/components/Banner/Banner.css.ts, apps/store/src/components/Banner/Banner.stories.tsx, apps/store/src/components/GlobalBanner/GlobalBanner.tsx
Move styles for bold text from `Globalbanner` to generic `Banner`
It's useful presentation logic, no reason for it to live in component that's primarily responsible for state management
=> Move bold style from GlobalBanner (emotion) to Banner (vanilla)

apps/store/public/locales/en/cart.json, apps/store/public/locales/sv-se/cart.json, apps/store/src/components/InputDay/InputDay.tsx, apps/store/src/components/QuickAdd/AddToCartButton.tsx, apps/store/src/components/QuickAdd/DismissButton.tsx, apps/store/src/components/QuickAdd/ProductUsp.css.ts, apps/store/src/components/QuickAdd/ProductUsp.tsx, apps/store/src/components/QuickAdd/QuickAddBundleView.stories.tsx, apps/store/src/components/QuickAdd/QuickAddBundleView.tsx, apps/store/src/components/QuickAdd/QuickAddEditableView.css.ts, apps/store/src/components/QuickAdd/QuickAddEditableView.tsx, apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx, packages/ui/src/components/Badge/Badge.tsx
* Implement the UI for the new _Accident Cross Sell Card_. At the moment one can _decline_ and _add_ the form. Editing it will be added next, the changes that will make for _start date_ and _number of insured people_ will not be considered when adding the offer to the cart.
It's not exactly the same as described [in figma](https://www.figma.com/file/8SfzuQEJ4LJ6uKL0l7WKoE/Hedvig.com?type=design&node-id=11183-2675&mode=dev). Card blue color is off but we have some changes on UI kit planned that's going to enable the new hue.
Accident cross sell new card.
=> GEN-1893 - feat(QuickAddEditableView): added foundation for quick add editable card (cross sell)

apps/store/src/blocks/ProductReviewsBlock.tsx, apps/store/src/components/ProductReviews/ProductReviews.tsx
* `ProductReviewsBlock`: Enable review comments to be hidden based on storyblok setting.
https://github.com/HedvigInsurance/racoon/assets/19200662/9e4b820a-b7a1-40b1-8c63-ee630d66acc1
Requested by Peter [here](https://www.notion.so/hedviginsurance/Hide-comments-in-product-reviews-0aa9a5ae162e4f07965461e0b193ebf9?pvs=4)
=> GEN-2011 - feat(ProductReviewsBlock): enable review comments to be hidden via storyblok config 

apps/store/src/features/widget/SignPage.tsx, apps/store/src/features/widget/publishWidgetEvent.ts
In the widget we currently have these events:
1. `success` - The user has successfully signed the insurance and connected payment.
2. `close` - The user pressed one of our close buttons. The partner should close e.g. the WebView upon receiving this event.
3. `event` - An unspecified event is sent to the partner including a second parameter “message” that includes the request ID (see below).
However, a few partners has asked about a signed event or was confused when the `success` event was sent, thinking it was sent at sign. 
Improve widget events
=> Add signed event to widget

apps/store/src/app/api/member-reviews/route.ts
I've noticed the following error during build: 
It seems we need to notify NextJS that it's a dynamic route handler. By doing that the error goes away.
Code scout.
=> chore: handle DYNAMIC_SERVER_USAGE error thrown during build

apps/store/src/features/widget/publishWidgetEvent.ts, apps/store/src/features/widget/usePublishWidgetInitEvent.ts
Send an event when the widget has loaded.
Currently it will send it 2 times if the partner loads the initial widget page and then proceeds to the flow page. But it doesn't hurt I suppose. Or do you think we should make sure to only send it once? I'm thinking using an atom to check if it's been sent on a previous screen.
Request from partners to have an init event
=> Add widget loaded event

apps/store/src/components/QuickAdd/QuickAddEditableView.css.ts, apps/store/src/components/QuickAdd/QuickAddEditableView.tsx
* Make sure Accident Cross Sell form fields get white background color
In summary, it seems the issue is that `@vanilla-extract/next-plugin` is being shipped to the client as part of JS bundle. That package is a dependency of `@vanilla-extract/next-plugin`, which we use to integrate Nextjs with vanilla extract css.
As a result styles are being applied twice. Once by classes defined inside CSS file and then for classes that came from a virtual css file:
It's a hack to avoid an issue we're currently having with vanilla extract css.
More info [here](https://hedviginsurance.slack.com/archives/C041SD67G82/p1713531586956579)
=> GEN-1893 - styles(QuickAddEditableView): ensure form fields get white background

apps/store/src/app/[locale]/StoryblokLayout.tsx, apps/store/src/blocks/PageBlock.tsx, apps/store/src/components/Header/Header.tsx, apps/store/src/components/LayoutWithMenu/LayoutWithMenu.tsx
Make sticky header logic DOM-driven
Regular CMS pages now opt-in to sticky header with `data-supports-sticky-header=true` on `main` element. 
It felt safer to make it opt-in rather than opt-out
That was the last place where layout depended on page data
We don't want to use sticky header on product pages since we have multiple other sticky elements there.  All other pages normally have it
=> Make sticky header DOM-driven instead of prop-driven

apps/store/src/blocks/InsurelyBlock.tsx, apps/store/src/blocks/QuickPurchaseBlock.tsx, apps/store/src/features/blog/BlogArticleListBlock.tsx
Subj
App router compatibility. Any blocks except car dealership ones can be used in app router, therefore they should use `next/navigation` instead of `next/router`
=> Replace all remaining usages of next/router in CMS blocks. Car dealership blocks untouched since we don't use them in app router yet

apps/store/src/blocks/VideoBlock.tsx
Add layout plugin to VideoBlock to be able to align videos along the grid in different viewports
Request from William and Peter
=> Add layout plugin to VideoBlock

apps/store/src/components/QuickAdd/QuickAddEditableView.css.ts, apps/store/src/components/QuickAdd/QuickAddEditableView.tsx
* Reduces inline padding and gap to avoid badge overflowing.
https://github.com/HedvigInsurance/racoon/assets/19200662/ef80a2ac-7f93-4ea0-9052-89439ada25fa
https://github.com/HedvigInsurance/racoon/assets/19200662/ee7086e0-e1c4-4684-a1e5-b30bf7270a41
=> GEN-1893 - styles(QuickAddEditableView): avoid badge overflowing

apps/store/src/components/BankIdDialog/BankIdDialog.tsx, apps/store/src/components/CheckoutPage/CheckoutPage.tsx, apps/store/src/components/CheckoutPage/CheckoutPage.types.ts, apps/store/src/components/CheckoutPage/useHandleSubmitCheckout.ts, apps/store/src/components/CheckoutPage/useUpdateCustomer.ts, apps/store/src/components/PriceCalculator/SsnSeSection.tsx, apps/store/src/features/carDealership/useAcceptExtension.ts, apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx, apps/store/src/features/widget/SignPage.tsx, apps/store/src/graphql/ShopSessionCustomerFragment.graphql, apps/store/src/pages/[locale]/checkout/index.tsx, apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx, apps/store/src/services/PriceCalculator/PriceCalculator.helpers.ts, apps/store/src/services/Tracking/Tracking.ts, apps/store/src/services/bankId/bankId.types.ts, apps/store/src/services/bankId/bankIdReducer.ts, apps/store/src/services/bankId/useBankIdCheckoutSign.ts
Remove usage of shopSession.customer.authenticationStatus
Logic changes
- Rely on checkout form fields to decide if we need to call `shopSessionCustomerUpdate` with email and/or names before signing.  This is backed by `shopSession.customer.missingFields`
- Always show BankID icon on sign button
- We've lost `new_customer` value of purchase events, waiting for a discussion to either remove it or address in separate PR
After recent signing changes we always require BankID sign during purchase, there's no need for separate returning member flow
=> Stop using shopSession.customer.authenticationStatus

apps/store/src/blocks/TickerBlock.tsx, apps/store/src/components/Ticker/Ticker.css.ts, apps/store/src/components/Ticker/Ticker.stories.tsx, apps/store/src/components/Ticker/Ticker.tsx
Add support for adding Heading block and Text Block to allow different fonts and sizes for the ticker.
In order to for the animation to work, we need a height to calculate the animation from. We can't derive it from the nested blocks so the best way I found was to add a setting for it Storyblok. 
After deploy we need to migrate the content in Storyblok before we remove the deprecated fields in code
https://github.com/HedvigInsurance/racoon/assets/6661511/83fc23ed-40b1-495c-80e7-5432c36359d3
https://github.com/HedvigInsurance/racoon/assets/6661511/9be0eb3d-96b5-43c9-8778-8c2bdda0e871
For the new Home campaign we what to have a ticker animation of headings
=> Add support for Heading in TickerBlock

apps/store/src/features/widget/StartFlow.helpers.ts, apps/store/src/pages/[locale]/widget/flows/[...slug].tsx
* Fix previewing of _Widget Flow_ content type. Locale is part of the URL now so we need to change how preview URL get's contructed.
https://github.com/HedvigInsurance/racoon/assets/19200662/758f9f59-20c2-4d84-9ab3-51af20c1b74b
Redirect URLs are being malformed.
=> fix(storyblok): previwing widget flow content type

apps/store/.env.local.example, apps/store/src/pages/[locale]/[[...slug]].tsx, apps/store/src/services/storyblok/Storyblok.constant.ts
Manually list most popular pages and only pre-build those instead of all CMS pages
Makes build faster. Would be more important for app router since builds are slower there right now
Also would allow us to detect errors that break static rendering of product pages before merging into `main`
=> Statically render only most popular pages

README.md, apps/store/next.config.mjs, apps/store/vercel.json
Update our Vercel install command to make yarn cache reusable between builds
Previous solution stopped working some time ago. I guess matching `.next` dir outside app dir was not intended and Vercel fixed it
=> Fix yarn cache path on Vercel

apps/store/src/app/[locale]/appDebug/[[...slug]]/ProductCmsPage.tsx, apps/store/src/app/[locale]/appDebug/[[...slug]]/page.tsx, apps/store/src/app/[locale]/layout.tsx, apps/store/src/app/[locale]/test/page.tsx, apps/store/src/app/debugger/actions.ts, apps/store/src/app/layout.tsx, apps/store/src/appComponents/RootLayout/RootLayout.tsx, apps/store/src/appComponents/providers/ApolloProvider.tsx, apps/store/src/services/apollo/app-router/rscClient.ts
App router
- pass locale to `ApolloClient` creation function explicitly
- move Apollo provider so that it's in locale-aware part of layout
- show available product titles on test app router page
We broke language link in app router during some previous refactorings - client always used default language, which resulted in a mix of languages when showing content
=> Explicitly pass locale to ApolloClient in app router

apps/store/src/components/Ticker/Ticker.tsx, apps/store/src/utils/useInterval.ts
Fix setInterval bug by saving callback in a ref. Great article by Dan the man on the subject https://overreacted.io/making-setinterval-declarative-with-react-hooks/
Hopefully solves the bug with overlapping animation. Will see if we can add `requestAnimationFrame` as an improvement as well
=> Add useInterval hook

apps/store/src/blocks/ButtonBlock.tsx
Subj.  We've replaced all usages of widget specific props with WidgetFlowStartButton
=> Remove widget-specific props from generic ButtonBlock

apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx, apps/store/src/components/ProductPage/PurchaseForm/ProductTierSelector.tsx, apps/store/src/components/ProductPage/PurchaseForm/useTiersAndDeductibles.ts, apps/store/src/features/widget/ConfirmationPage.tsx, apps/store/src/features/widget/ProductItem.tsx, apps/store/src/features/widget/ProductItemContainer.tsx, apps/store/src/features/widget/SignPage.tsx, apps/store/src/features/widget/widget.types.ts, apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx
* Extract tiers/deductibles definition into a hook: `useTiersAndDeductibles`; `OfferPresenter` and widget's `ProductItemContainer` now uses it to get tiers and deductibles.
* `ProductItemContainer`/`ProductItem` refactoring: move presentational logic from the container to the item
* `ProductItem`/`ProductItemContainer`: updated so they support tiers selection 
https://github.com/HedvigInsurance/racoon/assets/19200662/3cdb8a72-6afe-49ec-9d25-44ecf2d717ee
Discussion points
1. We probably need some sort of loading state for when changing tiers/deductibles. Checking with WIlliam.
2. Observe that we're using current implementation/design for _Tier Selector_. The idea is to modify the UI to match latest designs later.
3. Observe that other parts of the page - like perils - doesn't get update …
=> GEN-2050 - feat(widget): enable tier selector for car

apps/store/src/components/ProductPage/PurchaseForm/useTiersAndDeductibles.ts
* Fix an issue with `useTiersAndDeductibles` hook
I've introduced an issue with where we'd be showing tier selector even for cases tiers/deductibles are not applicable
=> GEN-2050 - fix(useTiersAndDeductibles): handle case where no tiers/deductibles are present

apps/store/src/components/ContactUs/ContactUs.tsx
- Remove "web chat" from _contact us_ widget.
**Before**
**After**
Requested from Sonny. More information [here](https://hedviginsurance.slack.com/archives/CMRN3MU07/p1714332040511579)
=> chore: disable chat (contact us) for all pages

apps/store/src/components/ProductPage/PurchaseForm/useTiersAndDeductibles.ts, apps/store/src/features/widget/ProductItem.tsx
- Solve "unknow tier" warning.
Other parts of our app solve cases only one tier is available by now showing tier selector (OfferPresenter for example), so I've updated `useTiersAndDeductibles` hook by not returning early when only one offer is provided and, instead, did the same for widget.
=> chore: resolve unknow tier warning

apps/store/src/features/widget/ConfirmationPage.tsx, apps/store/src/features/widget/ProductItem.tsx, apps/store/src/features/widget/ProductItemContainer.tsx
* Feat: add "presentation modes" for widget `ProductItem`: `edit` and `view`.
That component is currently being used on two contexts:
1. In the _sign page_, where some editing should be possible like start date, tier and deductible selector and auto switching request.
2. In the _confirmation page_, where most of the UI and information displayed equals the one used in the _sign page_ with the exception of not being able to editing stuff.
This change is a about a API addition to toggle between the two modes.
=> GEN-2063 - refact(ProductItem): add presentation modes

apps/store/src/components/Cancellation/CancellationForm.tsx, apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx, apps/store/src/features/widget/ProductItem.tsx, apps/store/src/features/widget/SwitchPage.tsx
* Widget: Enable switching for car in the sign page.
https://github.com/HedvigInsurance/racoon/assets/19200662/8141cbb9-cd90-44f2-9d12-86d8f285545b
For start, we're using the same `CancellationForm` we have for `OfferPresenter` today. Later on I'll be changing the styles to match the design.
=> GEN-2063 - feat(widget): enable switching for car in sign page

packages/ui/src/components/Text/Text.css.ts, packages/ui/src/components/Text/Text.tsx
The workaround is to only set color `inherit` when no color is passed in props
Fix color being overridden in Text component due to vanilla extract bug
=> Fix color being overridden in Text component due to vanilla extract bug

apps/store/src/components/HeadSeoInfo/HeadSeoInfo.tsx, apps/store/src/components/PageBreadcrumbs/PageBreadcrumbs.tsx, apps/store/src/middleware.ts, apps/store/src/pages/sitemap.xml.ts, apps/store/src/utils/PageLink.ts
Serve the Swedish homepage under hedvig.com instead of hedvig.com/se.
All internal pages still use the `/se` URL segment.
Requested by Peter for branding and SEO reasons.
=> feature: [RND-704] Move Swedish homepage to hedvig.com root

apps/store/src/app/[locale]/appDebug/[[...slug]]/ProductCmsPage.tsx, apps/store/src/blocks/ProductPageBlock.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/mocks/storyblok.ts, apps/store/src/services/storyblok/storyblok.ts
Reorganize `PurchaseForm` parent contexts so that they are placed inside as-small-as-possible `Suspense` block.  This fixes search params access in context providers
PriceIntentContext is still a mess and should be eventually refactored to use jotai atom families instead of React state + effects to sync - but that's for the future
Allows to render most of product page content statically, without layout shift
=> Reorganize PurchaseForm so that its context providers wrap only form instead of full page

apps/store/src/components/ProductPage/PurchaseForm/DeductibleSelector.tsx, apps/store/src/components/ProductPage/PurchaseForm/ProductTierSelector.tsx, apps/store/src/components/TierSelector/TierLevelRadioGroup.tsx, apps/store/src/components/TierSelector/TierSelector.css.ts, apps/store/src/components/TierSelector/TierSelector.tsx
* Redesign `TierSelector` and `ProductTierSelector`/`DeductableTierSelector`
**New Design**
---
**Notes**
Observe we're still showing tier option description even though that was removed from the new design. I think they're quite important so I decided to keep it as it is until I double check it.
Gonna use those new designs as part of _Car + Pet on Widget_ project
[Figma file](https://www.figma.com/file/zXJCE6JlNdnVWW99PmIqfG/Widget?type=design&node-id=956-4485&mode=design&t=YmmGjDcgnvOLOZi7-0)
=> GEN-2065 - styles(TierSelector): new design

apps/store/src/components/InputDay/InputDay.css.ts, apps/store/src/components/InputDay/InputDay.tsx
* Make some small style changes to `InputDay` component
With the redesign of TIerSelector (previous PR on the stack), InputDay end up being a little bit off.
This PR is about adjusting it.
=> GEN-2065 - styles(InputDay): update styles

apps/store/src/components/Video/Video.tsx
- We accidentally used both background image and poster on video 
- This also solves hydration missmatch error
=> Remove poster as background image since we use poster attribute on video element

apps/store/src/components/Video/Video.stories.tsx, apps/store/src/components/Video/Video.tsx
Fix hydration issue where css variables was set to empty string
=> Don't set video css variables to empty value

apps/store/src/appComponents/RootLayout/NavigationProgressIndicator.css.ts, apps/store/src/appComponents/RootLayout/NavigationProgressIndicator.tsx, apps/store/src/appComponents/RootLayout/RootLayout.tsx
Implementation of nav progress indicator for app router
We no longer have router events to rely on.
Search for existing libraries
- Found almost-good-enough solution in https://github.com/tomcru/holy-loader lib, but unfortunately it does not support changing progress bar color after initial load.
- There's also https://github.com/TheSGJ/nextjs-toploader, but is has unsolved issues in tracker that make it probably not very good option
This PR combines navigation detection logic from holy-loader with our original solution for styling nprogress with random color
=> Navigation progress indicator for app router

apps/store/src/blocks/CookieListBlock.tsx
On /hedvig/cookies page, the list of cookies along with descriptions is fetched via the OneTrsut script. Make sure we load the script on page load to display the content and make sure user an update cookie preferences 
Ensure we comply with GDPR
=> Make sure we load cookie list from OneTrust on /cookies page

apps/store/src/app/[locale]/StoryblokLayout.css.ts, apps/store/src/blocks/HeaderBlock.tsx, apps/store/src/components/Header/Header.tsx, apps/store/src/components/LayoutWithMenu/LayoutWithMenu.css.ts, packages/ui/src/global.css.ts, packages/ui/src/theme/vars.css.ts
Simplify our theme vars since `headerBgTransparentColor` was always the same as `bodyBgColor`
This allows to simplify state management for `TopMenuMobile` (next PR)
=> Remove 'headerBgTransparentColor' CSS var, it was always the same as 'bodyBgColor'

apps/store/src/components/ProductPage/PurchaseForm/ComparisonTableModal.tsx, apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx, apps/store/src/components/ProductPage/PurchaseForm/ProductTierSelector.tsx, apps/store/src/features/widget/ProductItem.css.ts, apps/store/src/features/widget/ProductItem.tsx
* Add _Comparison Table Modal_ for Widget's Product Item tier selector.
https://github.com/HedvigInsurance/racoon/assets/19200662/147bfe45-b743-4953-bac7-cdaf507168bb
Observe that the new design for comparison table will be added later, while here I'm just using the implementation we have today.
=> GEN-2070  -  feat(widget-tier-selector): enable comparison table modal

apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.css.ts, apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
Just noticed when toggling on the phone, active/hover state cause the trigger button to flicker. 
So I'd say either remove it for that button or make it permanent when open
https://github.com/HedvigInsurance/racoon/assets/6661511/d1e9746a-12b3-406f-908c-63503d299880
https://github.com/HedvigInsurance/racoon/assets/6661511/8f0b575c-f728-4ff9-a7ea-5a1c487e70dd
=> Remove flickering background color on mobile menu trigger

apps/store/src/features/widget/ProductItem.tsx
Code scout: found a small spacing issue with Widget Product item "Hide details" button
**Before**
**After**
=> styles(widget-productItem): fix small spacing issue with "hide details" button

apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/SwitchingAssistantSection.tsx, apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/SwitchingAssistantSection.types.ts, apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/fetchSwitchingData.ts, apps/store/src/features/widget/ConfirmationPage.tsx, apps/store/src/pages/[locale]/confirmation/[shopSessionId].tsx, apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/confirmation.tsx
* Adds _Switching Assistant_ section for Widget Confirmation pages
Part of enabling car into Widget flows.
=> GEN-2072 - feat(widget-confirmation): add switching assistant section

apps/store/src/features/retargeting/ShopSessionRetargeting.graphql, apps/store/src/features/retargeting/getUserRedirect.test.ts, apps/store/src/features/retargeting/getUserRedirect.ts
Ignore campaign code during retargeting if campaigns are currently disabled. Known cases
- Partner session
- Active bundle discount
This fixes potential problem with CRM retargeting links for sessions with active bundle discounts.  We want to keep bundle campaign code and ignore discount code in query params in this case
=> Prevent overwriting campaign code during retargeting

apps/store/src/services/Tracking/useReportDeviceInfo.ts
Subj
Few of "crypto.randomUUID is not a function" errors appeared in Datadog, we want to prevent them
=> Prevent errors from browsers without crypto.randomUUID when reporting internal events

apps/store/src/components/Cancellation/CancellationForm.tsx
Show InfoCard with a message about manual switching cancellation
Remind customer to check current insurance expiration date and cancel it.
=> feature: [Maker Days 24] Show manual switch cancellation info

apps/store/src/features/bundleDiscount/BundleDiscountOfferTooltip.tsx
Fix off-by-one error when we counted current offer twice while editing cart item. Now bundle discount shows correct tooltip when the only eligible cart item is being edited - "Buy more and get X% off your entire purchase"
=> Fix bundle size calculation when editing cart item

apps/store/public/locales/en/cart.json, apps/store/public/locales/en/purchase-form.json, apps/store/public/locales/sv-se/cart.json, apps/store/src/components/CartPage/CartPage.tsx, apps/store/src/features/bundleDiscount/BundleDiscountOfferTooltip.tsx
Add header to quick add block, this improves content separation between bundle links and cross-sell
=> Add header to quick add block on cart page

apps/store/public/locales/en/cart.json, apps/store/public/locales/en/purchase-form.json, apps/store/public/locales/sv-se/cart.json, apps/store/src/components/CartPage/CartPage.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/features/bundleDiscount/BundleDiscountOfferTooltip.tsx
Automatically hide cart toast when we follow bundle discount product link from cart toast or change current page in any other way
Fixes bug described here: https://hedviginsurance.slack.com/archives/C0738V9GV9S/p1715961003502579
=> Close CartToast on page change, for example, following bundle extra product link

apps/store/src/components/CookieConsent/CookieConsent.tsx
We have a bug with the consent/tracking feature released last week.
- For some reason consent is not update correctly in GTM when we defer loading the script. Might be a timing issue, we try to send update before script is fully loaded
- Affiliate tracking is dropped when consent aren't updated properly
Immediate fix is to load GTM on page load as we did before. Let's see if we can find a way around it. But if it's too flaky I see the risk of loosing tracking and affiliate tracking is more significant than the savings in first page load. 
We will still omit loading OneTrust script other than strictly necessary which is the biggest win 
We have a bug with the consent/tracking feature released last week.
=> fix/load GTM at initial page load to avoid dropped affiliate tracking and fix bug where consent isn't updated correctly after consent is given

apps/store/src/components/CookieConsent/CookieConsent.tsx
Not loading OneTrust after consent was given caused our Consent tag in Google Tag Manager to set the all categories as `denied`. That's because the tag was looking at categories from the `OneTrustGroupsUpdated` event that's being sent by the OneTrust script. 
Rollback for now. We will need to go over the tags in GTM listen at consent mode categories instead next week
GTM tracking is currently not working as expected
=> Keep on loading OneTrust to ensure consent is not dropped

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Prevent render delay of PurchaseForm in app router by providing default initial state as Suspense fallback
Fixes big layout shift when purchase form loading state appeared only after initial render
=> Provide early fallback UI for PurchaseForm without waiting for Suspense to resolve

apps/store/src/features/widget/StartFlow.helpers.ts, apps/store/src/features/widget/createPartnerShopSession.ts, apps/store/src/pages/[locale]/widget/flows/[...slug].tsx
If Storyblok specifies campaignCode for widget flow, pass it to create session mutation
Part of supporting multiple campaign codes for Avy
=> Support custom campaign codes in widget flow

apps/store/src/blocks/ProductGridBlock.tsx, apps/store/src/components/ProductGrid/ProductGrid.css.ts, apps/store/src/components/ProductGrid/ProductGrid.stories.tsx, apps/store/src/components/ProductGrid/ProductGrid.tsx, apps/store/src/components/ProductRecommendationList/ProductRecommendationList.tsx
- Align ProductGrid with the rest of the site
- Use ProductGrid styles in ProductRecommendations 
Design update, we don't want the site to be too wide on larger screens and align with the new UI kit updates
=> Update ProductGrid to follow main site grid

apps/store/src/components/ProductPage/PurchaseForm/ProductHero/ProductHero.css.ts, apps/store/src/components/ProductPage/PurchaseForm/ProductHero/ProductHero.tsx, packages/ui/src/theme/sprinkles.css.ts
- Get rid of `Space` and `SpaceFlex` in `ProductHero` block
- Support `alignItems` in sprinkles
This fixes layout shift shown on attached video below
<a href="https://app.graphite.dev/media/video/GLY3tSM85RFBvAf6lFNA/d0323d37-e2ac-404f-bead-b84c977108c1.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/GLY3tSM85RFBvAf6lFNA/d0323d37-e2ac-404f-bead-b84c977108c1.mov">Screen Recording 2024-06-03 at 12.53.00.mov</video>
=> Fix layout shift in mobile version of ProductHero by replacing Space and SpaceFlex with vanilla-extract styles

apps/store/src/blocks/ProductPageBlock.tsx, apps/store/src/utils/useIdleCallback.ts
Improve rendering speed of product pages by rendering general content (below "Coverage") lazily when it comes into view
Before
After
"See your price" is one of known slow elements and this optimization makes it faster thanks to rendering much smaller tree when opening just top part of product page
=> Optimize ProductPageBlock rendering by making lower content area render lazily

apps/store/src/services/gtm.tsx
Make sure we send necessary cookie category on app init to trigger necessary script tags in GTM.
This fixes issue were Addrevenue utm values wasn't stored in localStorage
Necessary category wasn't sent until OneTrust script was loaded after the user interacts with the cookie consent banner
Reported by Simon
=> Send necessary cookie category on app init

apps/store/src/components/CartPage/CartPage.tsx, apps/store/src/components/QuickAdd/QuickAddOfferContainer.css.ts, apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx
Fixes a bug when hiding cross-sale offer did not hide a heading "Popular add-on" that was related to it
Before fix:
After fix: no extract header
=> Hide quick add section header when section is hidden

apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx, apps/store/src/components/Pillow/Pillow.tsx, apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx, apps/store/src/components/PriceCalculator/SsnSeSection.tsx, apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Collection of low-risk optimizations for purchase form rendering
- memo, useCallback, etc to prevent rerenders
- only pass relevant props to `SsnSeSection` to avoid rerendrers on every change in `shopSession`
Results:
Scripting time for submitting SSN and Address sections in SE_APARTMENT_RENT reduced ~20% (239ms -> 197ms)
Purchase form section buttons are among the slowest elements on the site right now
=> Optimize PurchaseForm rendering performance when submitting a section

apps/store/next.config.mjs, apps/store/src/services/Tracking/experiment.constants.ts, apps/store/src/services/Tracking/experiment.helpers.ts, apps/store/src/services/Tracking/experimentMiddleware.ts, apps/store/src/services/Tracking/trackExperimentImpression.ts
In the previous A/B test setup we only run page level experiments where we rewrote the url to another page for experiment variants.  
To add support for component level experiments, make slug optional but still support page A/B tests
New A/B test setup
=> Update A/B test setup to work with component experiments

apps/store/src/app/[locale]/[[...slug]]/BlogStoryContainer.tsx, apps/store/src/features/blog/BlogContextProvider.tsx, apps/store/src/features/blog/BlogStoryblokProvider.tsx
- Make sure we load blog blocks for Blog Article and Blog Category content types, fixing previewing then on Storyblok
Issue caught by Peter and mentioned [here](https://hedviginsurance.slack.com/archives/C02JPS466NS/p1718020297897609)
=> fix(blog): make storyblok preview work again

apps/store/src/app/[locale]/test/page.tsx, apps/store/src/app/i18n.ts, apps/store/src/app/switcher/[id]/submitSwitchConfirmation.ts, apps/store/src/appComponents/RootLayout/RootLayout.tsx, apps/store/src/appComponents/providers/TranslationsProvider.tsx
- Fix JSON import usage when loading translation files and documented original problem
- Refactor `initTranslations` for better naming and ease of future optimization
This saves 27KB from HTML size of every page in app router. Actually, x2 that until another source of duplication is fixed in next PR
=> Fix i18next resource duplication (translation loader)

apps/store/src/app/[locale]/layout.tsx, apps/store/src/app/not-found.tsx, apps/store/src/appComponents/RootLayout/RootLayout.tsx, apps/store/src/appComponents/StoreLayout.tsx
Make root 404 page much smaller by only providing `common` translation namespace.  This page is added to HTML of every page on the site.
Before: /se - 255 KB uncompressed
After: /se - 227 KB uncompressed
=> Make app router pages smaller by reducing translations size in global 404 page

apps/store/src/blocks/HeaderBlock.tsx, apps/store/src/components/Header/Header.css.ts, apps/store/src/components/Header/NavigationContent.tsx, apps/store/src/components/Header/TopMenuDesktop/TopMenuDesktop.tsx, apps/store/src/components/Header/TopMenuMobile/TopMenuMobile.tsx
* Get navigation links back to SSR markup 
* We always render 'desktop' navigation markup on the server
* For mobile, we hide 'desktop' navigation via CSS and then render 'mobile' version.
More info on this slack [thread](https://hedviginsurance.slack.com/archives/C041SD67G82/p1718117670710749).
For SEO reasons, it's important navigation links be present in the SSR markup.
=> seo(navigation-header): make sure navigations links are available in the DOM

apps/store/experiments/quickAdd.json, apps/store/src/components/QuickAdd/QuickAddOfferContainer.tsx, apps/store/src/pages/_app.tsx, apps/store/src/services/Tracking/experiment.constants.ts, apps/store/src/services/Tracking/experiment.helpers.ts, apps/store/src/services/Tracking/experimentMiddleware.ts, apps/store/src/services/Tracking/trackExperimentImpression.ts, apps/store/src/services/Tracking/trackPageViews.ts
Add support for multiple experiments
To make it a smaller change I removed support for page experiment, will add it back. 
- Make `CURRENT_EXPERIMENTS` an array `Experiment` items
- Expose experiment env variables through `Experiments` similar to how we do it with `Features`  
- Set a cookie for each experiment like this: `hedvig-experiment:f6c758d3-2f8b-4d12-94fd-b486b1b3bbec`
- `trackExperimentImpression` now takes a `experimentId` to determine what experiment to track
Support for running multiple A/B tests
=> Add support for multiple experiments

apps/store/src/appComponents/StoreLayout.tsx, packages/eslint-config-custom/eslint-config-custom.cjs
Apply eslint change we agreed on few Frontend forums ago.  When fixing type imports, eslint will now inline `type` inside the same import statement instead of splitting type imports from normal imports
This does not affect existing code that uses separate imports - we'll just stop creating more of it
=> Update eslint config to prefer inline type imports

package.json, turbo.json, yarn.lock
Reverts HedvigInsurance/racoon#4368
Linus and I thought we just needed to rename `pipeline` to `tasks` but there is a codemod you can run to adress some more changes
=> Revert "chore(deps): update dependency turbo to v2"

apps/store/src/app/[locale]/[[...slug]]/page.tsx, apps/store/src/app/api/cms/revalidate/route.ts, apps/store/src/services/storyblok/storyblok.rsc.ts
Fix CMS page revalidation:
- Introduce delays into revalidation webhook. This is a workaround for known cache invalidation issues on Vercel. I'm not 100% sure what happens, but likely hypothesis is that cache invalidation's network request looses a race with returning from our API handler and get aborted
- Fix problem where we went to check for new `cv` with old `cv` in request.  This always failed to show any changes. Problem is not new, but it got much worse recently, when Vercel reduced restart rate for serverless functions - old `cv` was kept in memory and if page handler was restarted right before invalidation, it all worked
- Reduce storyblok.cv TTL to 1 minute. Request is very cheap is we don't save anything by making it less frequently
Overall, these fixes should provide
- …
=> Fix storyblok cache revalidation

apps/store/src/blocks/HeaderBlock.tsx, apps/store/src/components/Header/NavigationContent.tsx
Second attempt for making navigations links available for SEO.
Despite being present on the markup, they should work as expected when clicking on them.
Related with #4358
=> fix(navigation): links work fine and are avaiable in the markup

apps/store/src/app/[locale]/AppTrackingTriggers.tsx, apps/store/src/services/Tracking/useReportDeviceInfo.ts
We only had deviceInfo reporting in pages router.  Restoring it to app router now
=> Restore device info reporting for app router

apps/store/src/app/[locale]/[[...slug]]/ProductCmsPage.tsx, apps/store/src/components/ProductPage/PriceIntentTrackingProvider.tsx, apps/store/src/components/ProductPage/ProductPage.tsx, apps/store/src/components/ProductPage/ProductPageViewTrack.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/components/ProductPage/PurchaseForm/useOpenPriceCalculatorQueryParam.ts, apps/store/src/services/Tracking/useTracking.ts
- Fix missing product page context in view tracking by moving reporting component inside product-specific tracking context provider
- Make `useTracker` return a stable instance so that callbacks depending on tracking context are not recreated
- Modify select_item and open_price_calculator events so that they are reported only after we know shop_session_id
Found some issues in tracking setup, fixing those before adding new events for bundle discounts
=> Fix missing shopSessionId in view_item, select_item, open_price_calculator events

apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx, apps/store/src/services/Tracking/Tracking.ts
Add `sessionData` to experiment impression event to know if it was sent from store or from a the widget
Easier to make analysis by channel
=> Add sessionData to determine if an experiment is in store or widget

apps/store/src/blocks/ButtonBlock.tsx, apps/store/src/blocks/WidgetFlowStartButtonBlock.tsx, packages/ui/src/components/Button/Button.css.ts, packages/ui/src/components/Button/Button.stories.tsx
Large `Button` has width set to 100% by default, always been a bit odd behaviour. Let's remove it an use a prop for it when needed and set a min width according to UI kit.
=> Remove default 100% width on large Button variant

apps/store/src/blocks/StoryCarouselBlock.tsx, apps/store/src/services/storyblok/commonStoryblokComponents.ts
* Added `StoryCarouselBlock` component so editors can leverage `StoryCarousel` on their stories.
Can be tested [here](https://app.storyblok.com/#/me/spaces/165473/stories/0/0/512113692)
Part of Hedvig new designs project. [Figma file](https://www.figma.com/design/vylWsbAVqZTuG8fUEIf0zs/Tiers-%26-Addons?node-id=888-18580&t=JZ49xRvbJWCNrvQj-0)
=> GEN-2254 - feat(storyblok): add StoryCarouselBlock component

apps/store/src/blocks/FooterBlock/FooterBlock.tsx, apps/store/src/blocks/HeaderBlock/ProductNavContainerBlock.tsx, apps/store/src/components/Header/Header.css.ts
Replace `Space` component with gap styles in header and footer
I hate `<Space>` in our code - it targets child elements in non-obvious and computationally expensive way. There's also a risk of layout shift if any of its children add inline style tag
gap / rowGap / columnGap is simpler idiomatic way to get the same effect
=> Remove Space component from header and footer

apps/store/src/blocks/WidgetFlowStartButtonBlock.tsx, apps/store/src/components/ButtonNextLink.tsx
* Allow UI changes via storyblok to `WidgetFlowStartButtonBlock`
With that we can change _verisure_ widget pages so they use `WidgetFlowStartButtonBlock` instead of `ButtonBlock`.
More info can be found in the [ticket](https://www.notion.so/hedviginsurance/Widget-start-flow-button-Enable-styling-customizations-9e4c2979e18541579bde581ffa422556?pvs=4).
Note: Make sure to update widget pages after this get merged.
=> GEN-2383 - feat(WidgetFlowStartButtonBlock): allow UI changes via storyblok

apps/store/src/components/ContactUs/ContactUs.css.ts, apps/store/src/components/ContactUs/ContactUs.tsx
* Fix buttons alignment in _contact us_ chat
* Migrate it to vanilla extract css
It was misaligned before:
=> fix(contactus): center alignement + vanilla extract migraton

apps/store/src/components/Header/Header.css.ts
Add back space to navigation product list (as specified in FIgma) and remove unused styles
Space had disappeared, reported by Peter
=> Adjust space in navigation product list

apps/store/src/components/ForeverPage/ForeverPage.css.ts, apps/store/src/components/ForeverPage/ForeverPage.tsx, apps/store/src/components/ShopBreakdown/AddCampaignForm/AddCampaignForm.css.ts, apps/store/src/components/ShopBreakdown/AddCampaignForm/AddCampaignForm.tsx, apps/store/src/components/ShopBreakdown/DiscountField.tsx, apps/store/src/components/TextField/TextField.css.ts, apps/store/src/components/TextField/TextField.tsx
Refactor from emotion and added a uppercase prop to target input to make it more explicit. Previously the css was added on TextFIeld but then applied to the input element which was less obvious.
=> Add uppercase option for TextField

apps/store/public/mockServiceWorker.js, apps/store/src/components/ProductPage/PriceIntentContext.tsx, apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx, apps/store/src/graphql/ProductOfferFragment.graphql
Reimplement logic for clearing priceIntent after it was used for adding item to cart
Old solution did not work reliably since product -> checkout navigation crossed app router -> pages router barrier and was a full page reload
=> Reliably handle Offer -> Checkout navigation scenario by creating new priceIntent if presious one was used to add offer to cart

apps/store/src/app/[locale]/[[...slug]]/ContentCmsPage.tsx, apps/store/src/app/[locale]/[[...slug]]/ContentTypeStructuredData.tsx, apps/store/src/app/[locale]/[[...slug]]/page.tsx, apps/store/src/services/storyblok/storyblok.ts
* Added support for content structured data (Article, NewsArticle, BlogPosting and ProfilePage).
=> GEN-2382 - feat: added support for content structured data

apps/store/src/appComponents/providers/ShopSessionTrackingProvider.tsx, apps/store/src/components/BankIdDialog/BankIdDialog.tsx, apps/store/src/components/CartPage/PageDebugDialog.tsx, apps/store/src/components/DebugDialog/DebugResumeSessionSection.tsx, apps/store/src/components/DebugDialog/DebugShopSessionSection.tsx, apps/store/src/components/ForeverPage/ForeverPage.tsx, apps/store/src/components/ProductPage/PriceIntentTrackingProvider.tsx, apps/store/src/components/ProductPage/ProductPageDebugDialog.tsx, apps/store/src/components/ProductPage/ProductPageViewTrack.tsx, apps/store/src/components/ProductPage/PurchaseForm/useOpenPriceCalculatorQueryParam.ts, apps/store/src/components/QuickAdd/useBonusOffer.ts, apps/store/src/features/manyPets/ManyPetsMigrationPage/ManyPetsMigrationPage.tsx, apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx, apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx, apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/switch.tsx, apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/select.tsx, apps/store/src/pages/_app.tsx, apps/store/src/services/Tracking/TrackingContext.tsx, apps/store/src/services/shopSession/ShopSessionContext.tsx
Allow to consume just `shopSessionId` via separate context
- Step towards refactoring Purchase Form state management
- New hook makes code more readable
- Less re-rendering for components who just need an ID. Before they re-rendered when, for example, cart items changed
=> Add separate context for shopSessionId

apps/store/src/components/ShopBreakdown/AddCampaignForm/AddCampaignForm.css.ts, apps/store/src/components/ShopBreakdown/AddCampaignForm/AddCampaignForm.tsx
fix: add campaign code button was too wide
Need to talk with William and see how we want the large button to behave. We want a min-width on it when it's used on a page by itself but a few cases we us it inline and shouldn't have a min-width.
Will update the button large variant when we reach a conclusion
=> fix: add campaign code button was too wide

apps/store/src/components/ChangeSsnWarningDialog/ChangeSsnWarningDialog.tsx, apps/store/src/components/FullscreenDialog/FullscreenDialog.tsx, apps/store/src/components/ProductPage/PurchaseForm/PriceCalculatorDialog.tsx, packages/ui/src/components/Dialog/Dialog.tsx
Fix accessibility warnings from radix dialogs.  Looks like they came with recent update
- Add Dialog.Title to 2 dialogs. We should continue doing this in other places where we see this warning
- Export FullscreenDialog.Title to keep everything accessible via same component bag
- Explicitly state we're not providing dialog descriptions for screen readers
Developer experience, remove warnings
=> Fix few accessibilty warnings from radix dialogs

apps/store/src/components/PersonalNumberField/PersonalNumberField.tsx
Fix annoying warning about regex in personal number field.  Turns out `[+-]` is valid way to match dash or plus in default regex, but becomes invalid in Unicode mode which is used by browser for pattern on inputs. The safe way is to always escape dash within character classes
=> Fix regex warning on PersonalNumberField

.github/workflows/download-translations.yml
* Update `download-translations.yml` so PRs created by `peter-evans/create-pull-reques` proper trigger `ci.yml` workflow.
I've noticed CI GH action get stuck for PRs created by `download-translations.yml` workflow.
That's happening because events triggered by `GITHUB_TOKEN` will not trigger the creation of a new workflow, so even tho we have configured in our `ci.yml` workflow that it should run when a new PR is opened, that's not going to happen as a side effect of `download-translations.yml` execution. One workaround is to use a Personal Access Token instead of `GITHUB_TOKEN`. More info [here](GITHUB_TOKEN)
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create …
=> GEN-2405 - fix(update-translations): make sure action triggers CI workflow

apps/store/src/components/ProductPage/PriceIntentContext.tsx, apps/store/src/components/ProductPage/ProductPageContext.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/components/ProductPage/PurchaseForm/priceTemplateAtom.ts
Subj.
Small step in purchase form state management
In next PR we will want to have priceTemplate as atom in widget flow, where `ProductPageContext` makes no sense
=> Separate priceTemplateAtom from ProductPageContext

apps/store/src/components/PriceCalculator/PriceCalculator.tsx, apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx, apps/store/src/components/PriceCalculator/SsnSeSection.tsx, apps/store/src/components/PriceCalculator/priceCalculatorAtoms.ts, apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts, apps/store/src/components/ProductPage/ProductPageContext.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/components/ProductPage/PurchaseForm/priceTemplateAtom.ts, apps/store/src/features/widget/CalculatePricePage.tsx, apps/store/src/services/shopSession/ShopSessionContext.tsx
- Moved most of `PriceCalculator` global state into atoms
- Started using existing contexts for shopSession / shopSessionId instead of prod drilling
- Use atoms instead of prop-drilling in `PriceCalculatorAccordion`. Deeper components will have separate PR(s)
Part of purchase form state rework
=> Extract parts of PriceCalculator state into jotai

apps/store/src/components/PriceCalculator/AutomaticField.tsx, apps/store/src/components/PriceCalculator/ExtraBuildingsField.tsx, apps/store/src/components/PriceCalculator/PetCatBreedsField.tsx, apps/store/src/components/PriceCalculator/PetDogBreedsField.tsx, apps/store/src/components/PriceCalculator/PriceCalculator.tsx, apps/store/src/components/PriceCalculator/PriceCalculatorSection.tsx, apps/store/src/components/PriceCalculator/priceCalculatorAtoms.ts, apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculator.ts
`isLoading` state of price calculator is now jotai atom
This allows us to call mutations from separate places (next PR), since we don't need single component to hold loading state anymore
=> Extract PriceCalculator loading state into atom

apps/store/src/components/PriceCalculator/Warning/WarningPrompt/WarningPrompt.tsx, apps/store/src/features/widget/CalculatePricePage.tsx
Fix error when PriceCalculator is used before shopSession is ready in widget flow
=> Fix unsafe shopSession access in Widget / CalculatePricePage

apps/store/src/services/shopSession/ShopSessionContext.tsx
* Proper use `initialShopSessionId` when it's provided to `ShopSessionProvider`
I've found a bug with widget where ssn was not being loaded when provided via URL. Turns out the issue was with `ShopSessionContext`. Here's is why:
1. We create a "regular" shop session and store it in a cookie when the load a page in racoon. That happens for widget landing pages as well.
2. While triggering the flow we create a partner shopsession and redirect user to calculate price page. We include partner shop session id as long as any query params in the URL
3. We pass the partner shop session id as `initialShopSessionId` to `ShopSessionProvider` but it's internal logic used to retrieve the shop session client side takes shop session id stored in a cookie into account, when present. Previous …
=> fix(widget): make sure widget load ssn when provided via URL

apps/store/src/components/PriceCalculator/FetchInsurance.tsx, apps/store/src/components/PriceCalculator/FetchInsuranceContainer.tsx, apps/store/src/components/PriceCalculator/PriceCalculator.tsx
- Use atoms instead of prop-drilling for `FetchInsuranceContainer`
- Remove render child pattern
This was the last use of non-local data access in PriceCalculator
=> Remove prop-drilling from FetchInsuranceContrainer

apps/store/src/components/PriceCalculator/ExtraBuildingsField.tsx, apps/store/src/components/PriceCalculator/PriceCalculator.tsx, apps/store/src/components/PriceCalculator/priceCalculatorAtoms.ts, apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculatorSection.ts, apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
- Use `priceCalculatorAtoms` in `OfferPresenter` instead of prop-drilling
- Move sync state hook higher into `PurchaseForm` since now we have 2 purchase form states that consume these atoms
=> Use priceCalculatorAtoms in OfferPresenter

apps/store/src/components/PriceCalculator/FormGrid/FormGrid.tsx
Make sure we reliably update purchase form fields when we get non-empty suggested data
There was a race condition between price intent and customer update and we sometimes rendered empty fields in "your home" section
=> Fix purchase form sometimes not showing suggested data

apps/store/src/app/[locale]/StoryblokLayout.tsx, apps/store/src/blocks/HeaderBlock/HeaderBlock.tsx, apps/store/src/blocks/HeaderBlockNew/HeaderBlock.tsx, apps/store/src/blocks/HeaderBlockNew/MenuItemBlock.tsx, apps/store/src/blocks/HeaderBlockNew/NestedMenuBlock.tsx, apps/store/src/blocks/HeaderBlockNew/ProductMenuBlock.tsx, apps/store/src/blocks/HeaderBlockNew/ProductNavContainerBlock.css.ts, apps/store/src/blocks/HeaderBlockNew/SubMenuBlock.tsx, apps/store/src/components/HeaderNew/Header.constants.ts, apps/store/src/components/HeaderNew/Header.css.ts, apps/store/src/components/HeaderNew/Header.tsx, apps/store/src/components/HeaderNew/HeaderMenu/HeaderMenu.tsx, apps/store/src/components/HeaderNew/HeaderMenuMobile/HeaderMenuMobile.css.ts, apps/store/src/components/HeaderNew/HeaderMenuMobile/HeaderMenuMobile.tsx, apps/store/src/components/HeaderNew/NavigationContent.tsx, apps/store/src/components/HeaderNew/NavigationLink/NavigationLink.css.ts, apps/store/src/components/HeaderNew/NavigationLink/NavigationLink.tsx, apps/store/src/components/HeaderNew/NavigationTrigger.tsx, apps/store/src/components/HeaderNew/ShoppingCartMenuItem/ShoppingBagIcon.tsx, apps/store/src/components/HeaderNew/ShoppingCartMenuItem/ShoppingCartMenuItem.css.ts, apps/store/src/components/HeaderNew/ShoppingCartMenuItem/ShoppingCartMenuItem.tsx, apps/store/src/services/storyblok/storyblok.ts, apps/store/src/utils/Features.ts
First step of the new header and menu
To simplify replacing the menu, I made a copy of the current `HeaderBlock` and `Header` and started modifying them. I'll summarise the updates since some parts of the code is still the same.
- Update schema in Storyblock with new blocks with more logical names `headerMenu` with new child blocks `productMenu`, `subMenu` and `menuItem`
- Add feature flag for the new HeaderBlock
- Change layout in Header and put the logo in the center
- Update `ShoppingCartMenuItem` with new design
- Update mobile menu trigger with new design
https://github.com/HedvigInsurance/racoon/assets/6661511/b63474a2-db73-4810-a5a6-ae68d91e8941
New header and menu for Hedvig.com
=> Add block and component for the new header and menu

apps/store/src/components/HeaderNew/ShoppingCartMenuItem/ShoppingBagIcon.tsx, apps/store/src/components/HeaderNew/ShoppingCartMenuItem/ShoppingCartMenuItem.tsx
Don't show cart count until shopSession is loaded
https://github.com/HedvigInsurance/racoon/assets/6661511/f2d7d541-32d9-42a5-8c61-d3d787e147be
https://github.com/HedvigInsurance/racoon/assets/6661511/d20a2bf3-0623-4d79-8ce4-bc5a809bf655
Less UI shift, we don't want to show a 0 and then number of cart items once shopsession has loaded
=> Don't show cart count until shopSession is loaded

apps/store/src/components/PriceCalculator/CurrentInsuranceField/CurrentInsuranceField.tsx, apps/store/src/components/PriceCalculator/FetchInsuranceContainer.tsx, apps/store/src/components/PriceCalculator/PriceIntentWarningDialog/PriceIntentWarningDialog.tsx, apps/store/src/components/ProductPage/PriceIntentTrackingProvider.tsx, apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx, apps/store/src/components/ProductPage/PurchaseForm/priceIntentAtoms.ts
Made `priceIntentAtom` null-unsafe and moved definitely-non-null assertion to new `usePriceIntent()` hook
- Better developer experience for common case
- Easier to check for null priceIntent in one use case we had (tracking)
=> Replace most usages of priceIntentAtom with usePriceIntent hook

apps/store/src/blocks/HeaderBlockNew/HeaderBlock.tsx, apps/store/src/blocks/HeaderBlockNew/NestedMenuBlock.tsx, apps/store/src/components/HeaderNew/HeaderMenu/HeaderMenu.tsx
Small optimization for mobile menu
- pass down `variant` into mobile menu elements so that we don't get `initial` when opening the menu
- skip rendering elements when variant is still `initial` - this prevents double renders when we guess default variant and miss
Original issue in React DevTools (variant changed, but why should it?)
Less scripting when opening the menu, saves 20-30%
Before
After
=> Prop-drill responsive variant of HeaderMenu to prevent rendering 'initial' then discarding it

apps/store/src/app/[locale]/new/confirmation/[shopSessionId]/page.tsx, apps/store/src/components/ConfirmationPage/ConfirmationPage.stories.tsx, apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx, apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts, apps/store/src/features/sas/SasEurobonusSection.stories.tsx, apps/store/src/pages/[locale]/car-buyer/confirmation/[contractId].tsx, apps/store/src/pages/[locale]/confirmation/[shopSessionId].tsx
Foundation changes for migrating _Confirmation_ page into _app router_:
* Create the _app router_ counterpart page. Right now it just handles metadata (page's title).
* Update `ConfirmationPage` API. Before it was depending on `globalStory` which was being used by nextjs page component. By removing that dependency I can use the same component for the _app router_ counterpart.
* Code scout changes on storybook file.
The idea is to get my hands dirty with Nextjs app router migration by migrating _ConfirmationPage_: `pages/[locale]/confirmation/[shopSessionId]` --> `app/[locale]/new/confirmation/[shopSessionId]` (`page.tsx` file)
=> GEN-2421 - refact(confirmation-page): better split props dependencies between UI component and nextjs page

apps/store/src/app/[locale]/new/confirmation/[shopSessionId]/page.tsx, apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx, apps/store/src/components/ConfirmationPage/SwitchingAssistantSection/fetchSwitchingData.ts, apps/store/src/components/ConfirmationPage/fetchMemberPartnerData.ts, apps/store/src/graphql/ShopSessionOutcomeId.graphql, apps/store/src/pages/[locale]/confirmation/[shopSessionId].tsx
Renders `ConfirmationPage` UI inside app router's new confirmation page. Right now I'm only supporting fetching `shopSession`. Switching and member partner data will be handle in the future as we'd need to make changes on apollo client instance used by RSC (next PR).
The idea is to get my hands dirty with Nextjs app router migration by migrating _ConfirmationPage_: `pages/[locale]/confirmation/[shopSessionId]` --> `app/[locale]/new/confirmation/[shopSessionId]` (`page.tsx` file)
=> GEN-2421 - feat(app router confirmation page): handle story and cart data

apps/store/src/app/[locale]/[[...slug]]/ProductCmsPage.tsx, apps/store/src/app/[locale]/new/confirmation/[shopSessionId]/page.tsx, apps/store/src/app/[locale]/test/page.tsx, apps/store/src/app/debugger/actions.ts, apps/store/src/app/switcher/[id]/page.tsx, apps/store/src/app/switcher/[id]/submitSwitchConfirmation.ts, apps/store/src/appComponents/StoreLayout.tsx, apps/store/src/components/ConfirmationPage/SuccessAnimation/SuccessAnimation.tsx, apps/store/src/services/apollo/app-router/rscClient.ts, apps/store/src/services/apollo/app-router/serverDynamicHeadersLink.ts, apps/store/src/services/authApi/app-router/persist.ts, apps/store/src/services/authApi/fetchJson.ts, apps/store/src/services/authApi/login.ts, apps/store/src/services/bankId/useBankIdLogin.ts, apps/store/src/services/shopSession/app-router/ShopSession.utils.ts, apps/store/src/utils/types.ts
Seems like a lot of changes but a bunch of them are just small updates due API changes. Here is what changed:
* Update `getApolloClient` function. Now server components can instantiate apollo client with `cookies()`. That will be used by adding links that handle shop session id and authorization headers (serverDynamicHeadersLink). Observe that I had to update `app-router/persit.ts` - before nextjs `cookies()` were being imported and used directly there. The issue with it is that we don't want those dynamic functions for every instance. Adding them for CMS pages, for example, makes the app break as we have a we don't want CMS pages being rendered dynamically and by using dynamic functions during their rendering process (headers() or cookies()) we'd end up making the whole route be rendered …
=> GEN-2421 - feat(app router confirmation page): support swiching and member partner data

apps/store/src/services/shopSession/ShopSessionContext.tsx
It was introduced [here](https://github.com/HedvigInsurance/racoon/commit/6b81a429d2a0a1160fbc9f7acc128469c24eaf98)
`shopSessionId` state get's initialize with a an id server side but with `null` client side, which causes the hydration issue.
I've noticed a hydration error started to occur in the checkout page.
=> fix(checkout): hydration error

apps/store/src/services/storyblok/Storyblok.helpers.test.ts, apps/store/src/services/storyblok/Storyblok.helpers.ts
- Fix issue with trailing slash for links to root folder pages is back that causes redirects.
- Add a test since this bug has been coming back
Bug reported by Peter https://hedviginsurance.slack.com/archives/C041SD67G82/p1720447038841489
=> fix: bug where links for folder pages have trailing slash

apps/store/src/components/ProductItemV2/ProductItem.css.ts, apps/store/src/components/ProductItemV2/ProductItem.tsx
* Changed markup by removing button > button
Noticed the following error when delete button was rendered:
=> GEN-2432 - fix(ProductItem): clearn warning of button being descendant of button

apps/store/src/components/ProductPage/PurchaseForm/priceIntentAtoms.ts, apps/store/src/features/priceCalculator/InsuranceDataForm.tsx, apps/store/src/features/priceCalculator/PurchaseFormNew.tsx, apps/store/src/features/priceCalculator/SectionPreview.tsx, apps/store/src/features/priceCalculator/priceCalculatorAtoms.ts, apps/store/src/utils/jotaiUtils.ts
- Convert Price Calculator step into jotai atom to simplify using from components nested several levels deep.  For example, confirming price intent is now fully done inside `InsuranceDataSetion`
- Show preview of every form section in `viewOffers` and allow getting back to it with "Edit" button
- Extract `getAtomValueOrThrow` to `utils/jotaiUtils`
=> Support going back to specific InsuranceForm section from offers

apps/store/src/app/[locale]/[[...slug]]/page.tsx, apps/store/src/app/not-found.tsx, apps/store/src/components/ProductPage/PurchaseForm/ProductHero/ProductHero.tsx, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.tsx
Properly return 404 instead of crashing on invalid locale
Trying to access something like `/admin.php` which site scanners routinely try to do led to HTTP 500 and an error in datadog. Now it's 404 and regular message (see below)
1.
2.
Should reduce number of error alerts from Datadog
=> Fix global 404 page crash by wrapping into RootLayout

apps/store/src/components/HeaderNew/Header.css.ts, apps/store/src/components/HeaderNew/NavigationLink/NavigationLink.css.ts
The secondary nav item links where not full height and width of the the nav item. Put he padding and size properties on link instead of the item
=> Make secondary nav items area fully clickable

apps/store/src/components/HeaderNew/Header.css.ts, apps/store/src/components/HeaderNew/NavigationLink/NavigationLink.css.ts, apps/store/src/components/Pillow/Pillow.tsx
Add active state to ProductMenuItems
<a href="https://app.graphite.dev/media/video/nv8d5VeBPARA7ezh3Od3/99138941-fea2-42d0-bab3-818b5c15b3c0.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/nv8d5VeBPARA7ezh3Od3/99138941-fea2-42d0-bab3-818b5c15b3c0.mov">Screen Recording 2024-07-17 at 14.54.03.mov</video>
Mobile menu feedback
=> Add active state to ProductMenuItems

apps/store/src/blocks/HeaderBlockNew/ProductMenuBlock.tsx, apps/store/src/blocks/HeaderBlockNew/SubMenuBlock.tsx
Remove link from sub and product menu main items
We decided to test removing the main menu items to be a link. The hypothesis being that users might accidentally navigate when they want to open the submenu
=> Remove link from sub and product menu main items

apps/store/public/locales/en/purchase-form.json, apps/store/public/locales/sv-se/purchase-form.json, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.tsx, apps/store/src/features/priceCalculator/priceTemplates/SE_ACCIDENT_V2.ts, apps/store/src/features/priceCalculator/priceTemplates/SE_PET_DOG_V2.ts, apps/store/src/services/PriceCalculator/PriceCalculator.types.ts, apps/store/src/services/PriceCalculator/formFragments.ts, apps/store/src/services/storyblok/storyblok.ts
Add configuration for Accident Price Calculator page
- specify priceTemplate name in Storyblok and load that template in the code
- 2-section Accident configuration with address and coInsured + email combined into single section
- add `/se-en/insurances/accident/price-calculator` storyblok page
=> Add SE_ACCIDENT_V2 price template for new Price Calculator page

apps/store/src/components/ProductItem/EditActionButton.tsx, apps/store/src/components/ProductItem/RemoveActionButton.tsx
Subj. We had accessibility warnings in confirmation dialogs on cart item
Would be nice to get standard confirmation dialogs in new design. Currently we're using `FullscreenDialog`, which might be too low-level abstraction
=> Fix accessibility warning in cart item action dialogs (edit and remove confirmations)

apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx, apps/store/src/services/shopSession/ShopSessionContext.tsx
Ok, we were having an issue before where widget's price calcuator page was not pre-populating 'your address' form section. It was solved by this [PR](https://github.com/HedvigInsurance/racoon/pull/4435), which introduced another couple of issues:
1. When completing a purchase in Hedvig-dot-com, one could still see the number of items you have purchased in the header
2. When completing a purchase in widget and opening a tab with hedvig-dot-com, one would have it loaded with widget's shop session
This is the second attempt, which solves all of them. Here's the reasoning behind it:
We have two possible sources for shop session id in our app (and while debugging I think it makes sense to have 2): the URL and/or a cookie. The cookie option is the fallback one. If provided in the URL we should …
=> fix(widget): form auto completion with suggested data

apps/store/src/blocks/HeaderBlockNew/ProductMenuBlock.tsx, apps/store/src/blocks/HeaderBlockNew/SubMenuBlock.tsx
Reverts HedvigInsurance/racoon#4499
We tested and weren't satisfied with the functionality. Revert back to main items being linkable. Let's eavalute if we should change behaviour after vacations
=> Revert "Remove link from sub and product menu main items"

apps/store/src/features/widget/StartFlow.helpers.ts, apps/store/src/features/widget/createPartnerShopSession.ts, apps/store/src/pages/[locale]/widget/flows/[...slug].tsx, apps/store/src/services/storyblok/storyblok.ts
Make widget flow type explicit. Options are `Regular` and `HomeTrialExtension`.  Only send `externalMemberId` to `shopSessionCreatePartner` for trial extension flow type
Avy is sending `externalMemberId` to us if person ever had a trial or is a returning members. We expected to only get it for extension flow and failed in other cases
=> Use explicit WidgetFlowType to create partner session the right way (only pass externalMemberId to trial extensions)

apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/CheckoutPaymentTrustlyPage.css.ts, apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/CheckoutPaymentTrustlyPage.tsx, apps/store/src/components/PaymentConnectPage/IdleState.tsx, apps/store/src/pages/[locale]/payment/connect/start.tsx, apps/store/src/pages/[locale]/payment/connect/success.tsx, apps/store/src/services/trustly/TrustlyIframe.css.ts, apps/store/src/services/trustly/TrustlyIframe.tsx
* chore(TrustlyIframe): migrate to vanilla extract css
* refact(CheckoutPaymentTrustlyPage): update Trustly iframe styles via CSS class instead of style object
Subj.
=> GEN-2432 - refact(TrustlyIframe): migrate to vanilla extract css

apps/store/public/locales/en/purchase-form.json, apps/store/public/locales/sv-se/purchase-form.json, apps/store/public/mockServiceWorker.js, apps/store/src/features/priceCalculator/priceTemplates/SE_APARTMENT_BRF_V2.ts, apps/store/src/features/priceCalculator/priceTemplates/SE_APARTMENT_RENT_V2.ts, apps/store/src/services/PriceCalculator/formFragments.ts
Add Price Calculator pages for SE_APARTMENT_RENT and SE_APARTMENT_BRF
Apartment and co-insured info grouped into single form section
To be followed by PR for "use your registration address?" field
=> Add new forms for SE_APARTMENT_RENT and _BRF

apps/store/next.config.mjs, apps/store/src/utils/patchServerConsole.mjs
Ignore warnings from Datadog SDK that turn into server-side errors in monitoring
Less monitoring noise, this error is non-actionable and we cannot fix it
=> Ignore Datadog browser SDK multiload warnins in server-side code

apps/store/src/blocks/ProductGridBlock.tsx, apps/store/src/components/ProductCard/ProductCard.tsx, apps/store/src/components/ProductGrid/ProductGrid.stories.tsx, apps/store/src/components/ProductGrid/ProductGrid.tsx
1. Fix warnings like 
```
warn-once.js:16 Image with src "https://assets.hedvig.com/f/165473/1500x1500/f9fb8e014a/bil-bmw-hedvig-1500.jpg" has "fill" prop and "sizes" prop of "100vw", but image is not rendered at full viewport width. Please adjust "sizes" to improve page performance. Read more: https://nextjs.org/docs/api-reference/next/image#sizes
```
originating from `ProductGrid` component
2. Stop using render child pattern in ProductGrid and just pass children instead
Reduces total  size of images on home page from ~1300 KB to ~1000 KB compressed (opened with cache disabled in 920px wide window and scrolled to footer)
=> Optimize image sizes in ProductGrid

apps/store/src/components/AppErrorDialog.tsx, apps/store/src/features/priceCalculator/InsuranceDataForm.tsx, apps/store/src/features/priceCalculator/useConfirmPriceIntent.tsx
Use default app error handler when we fail to confirm price intent in Price Calculator page. Since we don't need custom actions ('try again' kept price calculator open, 'close' closed it), we no longer need custom error dialog
=> Show error when confirmPriceIntent fails

apps/store/src/features/bundleDiscount/BundleDiscountCartSummary.tsx
Remove `Array.toSorted()` call that led to rendering errors
This fixes Vercel-only error where `toSorted()` is not available in server environment. Vercel still runs node 18
=> Fix rendering bundle discount with different start dates on Vercel

.github/renovate.json5, apps/store/public/mockServiceWorker.js
- Revert `toSorted()` removal since we're using node 20.x on vercel right now
- Configure Renovate to not auto-update NodeJs to major versions, we should do it manually when vercel support them
=> Disable Renovate for major version updates of NodeJs

apps/store/public/locales/en/purchase-form.json, apps/store/public/locales/sv-se/purchase-form.json, apps/store/src/components/InputSelect/InputSelect.css.ts, apps/store/src/components/InputSelect/InputSelect.stories.tsx, apps/store/src/components/InputSelect/InputSelect.tsx, apps/store/src/components/PriceCalculator/CarMileageField.tsx, apps/store/src/components/PriceCalculator/ExtraBuildingsField.tsx
Apply new design for select input. It's used in
- Car Mileage field
- Extract building dialog (type field)
- Product Variant Selector CMS block
What has changed
- Field supports label
- 3 size variants (small/medium/large) instead of small/large before
- It's possible to use `placeholder=""` if you want empty default option, but don't have good display text for it
- Placeholder text uses secondary color (other options still use primary)
Styling implementation is cruel and unusual, extensively commented how it works and why it's so complicated
Screenshots:
1.
2. 
3.
Step towards upgrading all input designs. Looks somewhat inconsistent due to smaller height, but close enough. It's probably easier to merge such PRs one by one instead of waiting until we're fully done
=> New design for InputSelect

apps/store/src/components/PriceCalculator/SsnSeSection.tsx, apps/store/src/components/ProductPage/PurchaseForm/priceIntentAtoms.ts, apps/store/src/features/priceCalculator/InsuranceDataForm.tsx
Fix a bug when "Edit" button on price intent warning dialog did not prevent form switching to the next section
This was caused by never explicitly setting underlying atom on default forward transitions. Fixed this for SSN section. Tested in both new and old price calculators
=> Fix PriceIntentWarningDialog -> Edit not keeping previous form section active

apps/store/src/components/InputSelect/InputSelect.css.ts, apps/store/src/components/StepperInput/StepperInput.css.ts, apps/store/src/components/TextField/TextField.css.ts, packages/ui/src/theme/colors/colors.ts
- Highlight currently focused input with gray border
- Add explicitly named design token for focused border color
- Applied to inputs that already have new design (select, text, stepper)
UX/Accessibility - focus highlight is essential for keyboard navigation
=> Add focus border to redesigned inputs (text, select, stepper)

apps/store/src/app/[locale]/new/checkout/BonusOffer.tsx, apps/store/src/app/[locale]/new/checkout/CartEntries.tsx, apps/store/src/app/[locale]/new/checkout/CheckoutForm.tsx, apps/store/src/app/[locale]/new/checkout/CheckoutPage.tsx, apps/store/src/app/[locale]/new/checkout/loading.tsx, apps/store/src/app/[locale]/new/checkout/page.tsx, apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx, apps/store/src/services/shopSession/app-router/useShopSessionSuspense.ts
* Restructure how _Checkout_ page v2 is rendered so we don't have issues with caching
**The issues**
We have a couple of caching issues that comes from how _CheckoutPage_ is being rendered until now.
1. Recently added offers might not get shown in the _Checkout Page_
https://github.com/user-attachments/assets/b5c59f40-b53d-4421-9cbe-38f1536182f7
2. Checkout page _empty cart_ UI doesn't get shown when removing the last item from the cart
https://github.com/user-attachments/assets/39c59dff-3078-4ba0-9839-a3a8eabb4fe0
**Why they happen**
Current implementation of _CheckoutPage V2_ decides at the server level (via RSC) if we should show the _Empty cart UI_ or the _Shop breakdown_ based on the size of the cart entries. That works fine when browser navigating to checkout page but since Nextjs …
=> GEN-2432 - fix(checkout-v2): invalidate router cache for checkout page

apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/page.tsx, apps/store/src/blocks/ConnectPaymentBlock.tsx, apps/store/src/services/storyblok/commonStoryblokComponents.ts, apps/store/src/services/storyblok/storyblok.ts
* Enable the addition of CMS content for the _Connect Payment_ page.
How it works:
* I have added a new content type: `Connect Payment`
* Connect payment page reads from that (when present) and renders the content bellow the _insurely_ iframe.
As requested for new Checkout+Cart page [designs](https://www.figma.com/design/p1TEzLLVqJB9gKDNTDVGU4/Hedvig.com?node-id=470-2211&t=0VO3PWzvNqc6CqL7-4).
=> GEN-2432-feat(checkout-v2): enable CMS content for connect payment page

apps/store/src/components/ProductItem/ProductItemContainer.tsx, apps/store/src/components/ProductItem/useOfferDetails.ts, apps/store/src/components/ProductItemV2/ProductDetails.tsx, apps/store/src/components/ProductPage/PurchaseForm/useSelectedOffer.ts, apps/store/src/features/priceCalculator/OfferPresenterV2.tsx
- Add details section (display items and documents) to Offer Summary
- Extract `useOfferDetails` hook to avoid duplicating that code
- Provide fake documents as a temp placeholder until terms-hub is ready to return real data in staging
=> Add offer details to Price Calculator page

apps/store/src/features/priceCalculator/DeductibleSelectorV2.css.ts, apps/store/src/features/priceCalculator/DeductibleSelectorV2.tsx, apps/store/src/features/priceCalculator/OfferPriceDetails.tsx, apps/store/src/features/priceCalculator/ProductTierSelectorV2.tsx, packages/ui/src/components/Badge/Badge.css.ts, packages/ui/src/components/Badge/Badge.stories.tsx, packages/ui/src/components/Badge/Badge.tsx
- Use Badge component in OfferPresenterV2
- Add CSS var for badge font color
- Allow overriding style on badge
- Add tiny badge variant as seen in price breakdown
All changed badges can be seen on screenshot below
=> Use Badge component instead of one-off substitutes in OfferPresenterV2

apps/store/src/app/[locale]/new/checkout/CartEntries.tsx, apps/store/src/components/ProductItem/useEditProductOffer.ts, apps/store/src/components/ProductPage/PurchaseForm/priceIntentAtoms.ts, apps/store/src/components/ProductPage/useCartEntryToReplace.tsx, apps/store/src/features/priceCalculator/InsuranceDataForm.tsx, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2.tsx, apps/store/src/features/priceCalculator/priceCalculatorAtoms.ts, apps/store/src/graphql/ProductOfferFragment.graphql, apps/store/src/utils/Features.ts
- Covert `FEATURE_PRICE_CALCULATOR_PAGE` env variable into feature flag since we need it on client side as well now
- Add 'Edit information' button to new checkout page, that goes either to product page (default) or price calculator page (feature flag enabled and page linked to product metadata)
Limitations
- no confirmation dialog (easy to add, let's wait for designers to be back to discuss)
- editing bonus offers not supported, redirect will crash if offer.priceIntentId is not defined
Edit button:
=> Edit cart item mode for Price Calculator page

apps/store/src/app/debugger/car-trial/CarTrialDebuggerForm.tsx, apps/store/src/app/debugger/trial/components/TrialContractForm.tsx, apps/store/src/components/InputRadio/InputRadio.css.ts, apps/store/src/components/InputRadio/InputRadio.stories.tsx, apps/store/src/components/InputRadio/InputRadio.tsx, apps/store/src/components/PriceCalculator/AutomaticField.tsx, apps/store/src/components/PriceCalculator/CurrentInsuranceField/InputCurrentInsurance.tsx, apps/store/src/components/PriceCalculator/ExtraBuildingsField.tsx, apps/store/src/components/PriceCalculator/UseRegistrationAddressField.tsx, apps/store/src/services/PriceCalculator/Field.types.ts, apps/store/src/services/PriceCalculator/data/SE_PET_CAT.ts, apps/store/src/services/PriceCalculator/data/SE_PET_DOG.ts
* Refact: Update `InputRadio` API so it receives options as props.
It's subjective. I think it's easier to work with that way and will ease the addition of vertical layout in the future:
With that's said this is not required. We can drop it if we think it's not worth it.
=> GEN-2463 - refact(InputRadio): update API - receive options via props

apps/store/src/components/ProductCard/ProductCard.css.ts, apps/store/src/components/ProductCard/ProductCard.tsx
Background:
Google reported 0.32 layout shift (CLS) on https://www.hedvig.com/se/forsakringar/djurforsakring page
One obvious thing I've found is that product grid jumps when page is loaded. This was caused by dreaded `Space` component. Replacing with div+yStack fixes the issue
To be followed by full conversion to vanilla-extract
=> Fix layout shift in ProductGrid caused by Space component

apps/store/src/app/[locale]/new/checkout/page.tsx
- Display "Empty Cart" UI when `customer` info is not present (meaning user hasn't insert any data yet)
On such cases we still want to show "Empty Cart" UI for _Checkout Page_.
=> fix(checkout-v2): enable empty cart state when customer data is not provided

apps/store/public/mockServiceWorker.js, apps/store/src/middleware.ts
Fix a bug where changing language from English to Swedish had no effect
Root cause: / -> /en-se redirect was cached on the client
This PR adds "Vary: cookie" header to redirect to prevent this from happening
=> Fix English -> Swedish locale change on home page

apps/store/src/components/Combobox/Combobox.css.ts, apps/store/src/components/Combobox/Combobox.stories.tsx, apps/store/src/components/Combobox/Combobox.tsx
* Combobox: support size variants: 'small', 'medium' and 'large'
With that change, Breed Selector now has the same sizing styles and other inputs on new Price Calculator pages:
Some of the changes included in Breed Selector [redesign](https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=15404-12523).
=> GEN-2470 - styles(combobox): support size variants (small, medium, large)

apps/store/src/blocks/FooterBlock/LanguageSelectForm.tsx, apps/store/src/blocks/ProductVariantSelectorBlock.tsx, apps/store/src/components/InputSelect/InputSelect.css.ts, apps/store/src/components/InputSelect/InputSelect.tsx, apps/store/src/components/ProductVariantSelector/ProductVariantSelector.tsx
Product variant selector had double backgrounds and outer one showed under rounded corners
Improved `backgroundColor` prop implementation in `InputSelect` and use it instead of custom styles to make it right
Rejected options:
- `contain: 'paint'` on outer container (only solves half)
- move background and border-radius to outer div (non-obvious API where `InputSelect` behaves as div in regard to styling)
Before
After
=> Fix product variant selector backgroung being visible under rounded corners

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx
Replace hard reload with client side navigation when going from product page to price calculator page
Known issue: developer warnings about `setState()` calls during render, caused by jotai hydration of shared atoms. To be addressed in another PR
We're probably going to A/B test price calculator page or to soft launch for subset of products first. So, good navigation experience will matter to real users and client-side navigation is both faster and better-looking
=> Use client-side navigation to go from product page to price calculator page

apps/store/src/app/[locale]/StoryblokLayout.css.ts
* make sure footer is always at the bottom of the page
For large screens, footer might not be at very bottom of the page as expected, depending on the size of the content.
=> GEN-2432 - styles(StoryblokLayout): make sure footer is always at the bottom of the page

apps/store/src/app/[locale]/StoryblokLayout.css.ts
Reverts "sticky at the bottom footer" styles since it causes other responsive issues
=> Revert "styles(StoryblokLayout): make sure footer is always at the bottom of the page (#4594)"

apps/store/src/components/BankIdDialog/BankIdDialog.tsx, apps/store/src/components/StepperInput/StepperInput.tsx, apps/store/src/features/priceCalculator/OfferPresenterV2.tsx, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.tsx, apps/store/src/features/priceCalculator/ProductCardSmall.tsx, apps/store/src/features/priceCalculator/ProductTierSelectorV2.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2.tsx, packages/ui/src/patterns/stack.ts, packages/ui/src/theme/sprinkles.css.ts
* Update xStack/yStack apis so parameters became optional. Then `yStack()` would mean the same as `yStack({})` without the necessity of an empty object.
* Make `gap` opt in to `stack` by removing default `gap`. Then `yStack()` would be the same gapwise as `yStack({gap:'none'})`
Subjective. I think that API is easier to work with. Let me know what you think.
=> refact(yStack/xStack): make arguments optional

apps/store/src/app/[locale]/new/checkout/CartEntries.tsx, apps/store/src/app/[locale]/new/checkout/CheckoutForm.tsx, apps/store/src/appComponents/useAsyncRouterPush.tsx, apps/store/src/components/CartPage/CartPage.tsx, apps/store/src/components/CheckoutPage/CheckoutPage.tsx, apps/store/src/components/ProductItem/EditActionButton.tsx, apps/store/src/components/ProductItem/useEditProductOffer.ts
* New checkout page: render the same product item card we already use on checkout/cart pages today. With that we'll:
* Include the confirmation dialog for deletion
* Solves an issue where it's not possible to edit
* Add exposure + start date information
Requested during a testing session.
=> GEN-2432 - fix(checkoutv2): display product item form checkout/cart page

apps/store/src/app/[locale]/new/checkout/CartEntries.tsx, apps/store/src/app/[locale]/new/checkout/CheckoutPage.css.ts
* Display bundle offers in new checkout page.
Logic for showing bundle offers were copied from `CartPage` meaning we have it twice. But when this get's released and `CartPage` deleted, we'll have a single copy.
Part of the merge between checkout and cart page.
=> GEN-2432 - fix(checkoutv2): added bundle offers

apps/store/src/components/Perils/Perils.tsx, apps/store/src/utils/useElementSize.ts
- Refactor how `Perils` component implements responsive number of column
- Commented why current solution uses JS responsive logic instead of usual CSS solutions
New solution uses container size instead of window size. This works better in terms debugger where we have 2 perils blocks size by size and window-based size is way off
**Performance effect**
~5% reduction in product page scripting time
=> Optimize responsive layout in Perils grid with ResizeObserver instead of window-based media queries

apps/store/src/components/Accordion/Accordion.css.ts, apps/store/src/components/Accordion/Accordion.tsx
Pretty basic conversion, trying to use stacks where appropriate to reduce size of produced CSS
Only non-trivial change is how we add background to full item when trigger is hovered in open state - commented why it looks like it does
=> Convert Accordion styles to vanilla-extract

apps/store/src/components/ProductItem/useEditProductOffer.ts
Fix an issue with editing Accident Insurance added via accident x-sell card.
**Before**
https://github.com/user-attachments/assets/73dd29c5-a10e-4523-a1ee-502cae105720
**After**
https://github.com/user-attachments/assets/266ab156-d61c-487d-abad-01adf7207409
That happened because we used to throw an error in case you're trying to edit an offer which we couldn't retrieve the price intent. That piece of code was removed because that scenario is covered elsewhere.
=> GEN-2432 - fix(useEditProductOffer): cover the scenario where there's no price intent for a product offer

apps/store/src/features/priceCalculator/InsuranceDataForm.tsx
Fixed price calculator not transitioning to next section
Problem was caused by assumption that values read with `useStore().get(atom)` trigger rerenders on store change. They don't
=> Fix missed step transition in price calculator page (broken when adding edit card item)

apps/store/src/app/[locale]/new/checkout/CheckoutPage.css.ts, apps/store/src/app/[locale]/new/checkout/CheckoutPage.tsx
* Bring back Checkout/Cart headings into new Checkout page
=> GEN-2432 - fix(checkoutv2): bring back headings

apps/store/src/features/memberArea/components/MemberAreaLayout.css.ts, apps/store/src/features/memberArea/components/Menu/Menu.css.ts
Add wrapping to member area menu. This replaces horizontal scrolling with multiline layout, items are always visible. Does not affect wide variant where menu goes on the left
Before
After
=> Wrap member area menu on small screens

apps/store/src/components/ProductData/ProductDataProvider.tsx, apps/store/src/components/ProductVariantSelector/ProductVariantSelector.tsx, apps/store/src/features/widget/ProductItemContainer.tsx
Demo of 2nd alternative approach to scoping jotai atoms to React subtree. Original problem and 1st solution can be seen in https://github.com/HedvigInsurance/racoon/pull/4581
Used in next following PR to show multiple product variants next to each other
=> Use atomFamily to keep product-specific atoms scoped

apps/store/src/app/debugger/DebuggerMenu.tsx, apps/store/src/app/debugger/layout.tsx, apps/store/src/app/debugger/terms/[productName]/page.tsx, apps/store/src/app/debugger/terms/page.tsx, apps/store/src/components/ProductData/ProductData.graphql, apps/store/src/components/ProductData/ProductDataProvider.tsx, apps/store/src/services/apollo/app-router/rscClient.ts
Prototype of internal tool for showing terms data in both languages side-by-side
Allows manual verification of imported PCMS data. We foresee some risks related to matching texts between languages. This representation should make it easier to check compared to viewing product pages in multiple tabs
=> Initial version of terms-hub debugger

apps/store/src/blocks/QuickPurchaseBlock.tsx, apps/store/src/components/QuickPurchaseV2/QuickPurchase.css.ts, apps/store/src/components/QuickPurchaseV2/QuickPurchase.tsx, apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/ProductSelector.tsx, apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/QuickPurchaseForm.css.ts, apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/QuickPurchaseForm.tsx, apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/SsnField.tsx
Create QuickPurchaseV2 component
Copied and modified the QuickPurchase component to use on the new ProductPage since the functionality is very similar. So using a feature flag we can change what QuickPurchase component that is rendered.
In the new version of the component it navigates to PriceCalculatorPage, the other logic is the same as the current implemented component.
If it turns out to have different use cases we can just create a new block for the component on ProductPage.
What should be modified is that we want to have an insurance pre-selected in the dropdown.
https://github.com/user-attachments/assets/cc47fe08-14ea-41e6-a224-1e9e68e35679
Going from ProductPage to PriceCalculatorPage
=> Create QuickPurchaseV2 component

apps/store/src/app/debugger/DebuggerMenu.tsx, apps/store/src/app/debugger/layout.tsx, apps/store/src/app/debugger/page.tsx, apps/store/src/app/debugger/session/page.tsx
Replaced store menu based version of debug tools navigation with simple menu that behaves well on small screens
Original debugger menu (see https://dev.hedvigit.com/debugger) breaks on smaller widths because it assumes it's only used inside full store menu with mobile and desktop versions, etc. Using leaf components from it without full thing was never going to work well
Before
After
=> Simple navigation menu for debug tools

apps/store/src/features/priceCalculator/DeductibleSelectorV2.tsx, apps/store/src/features/priceCalculator/OfferPresenterV2.tsx, apps/store/src/features/priceCalculator/OfferPriceDetails.tsx, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.tsx, apps/store/src/features/priceCalculator/ProductTierSelectorV2.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2.tsx, apps/store/src/features/priceCalculator/SectionPreview.tsx
We used to have default gap of 'md' in `xStack / yStack`. It became 'none' after recent refactoring, so I'm adding it explicitly to make price calculator page look like it's supposed to
Before
After
=> Explicitly specify gap in price calculator page styles

apps/store/src/app/[locale]/confirmation/[shopSessionId]/page.tsx, apps/store/src/components/ConfirmationPage/ConfirmationPage.tsx, apps/store/src/components/ConfirmationPage/ConfirmationPage.types.ts, apps/store/src/pages/[locale]/car-buyer/confirmation/[contractId].tsx
Subj.
We might get some errors while fetching confirmation story in the context of confirmation page from time to time due to storyblok not being initialized correctly 🤷‍♂️. That makes the whole confirmation page to crash. Couldn't find the reason why that happens as this is not easy to reproduce. At least now we don't crash the whole page.
=> RND-856 - fix(confirmation page): avoid crashing confirmation page if confimation story wasn't fetched

apps/store/src/components/Pillow/Pillow.css.ts, apps/store/src/components/Pillow/Pillow.tsx, apps/store/src/components/ProductReviews/PillowHeader.tsx, apps/store/src/components/QuickAdd/QuickAddBundleView.tsx, apps/store/src/components/QuickAdd/QuickAddEditableView.tsx, apps/store/src/components/RadioOptionList/RadioOptionList.tsx, apps/store/src/components/SelectInsuranceGrid/ProductItem.tsx, apps/store/src/features/retargeting/RetargetingPage.tsx, packages/ui/src/theme/media.ts
Subj. Var-based size is needed for next PR where price calculator page has responsive pillow size
=> Convert Pillow styles to vanilla-extract, allow to override size via CSS var

packages/ui/src/icons/ArrowIcon.tsx, packages/ui/src/icons/Root.tsx
Subj. We currently cannot use SVG icons as server components, but it's probably not a big deal
=> Mark IconRoot as client component as assignInlineVars does not work on <svg> in RSC

apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/page.tsx
Update slug for getting Connect Payment CMS page to match changes on storyblok.
I understand both need to be in sync and that could be a pain but so far we have a couple of cases and I don't expect that changing so often. If that chagnes then we can think on an alternative way.
As part of new designs for checkout page, CMS content was added to connect payment page
=> feat(connect payment): load content from CMS

apps/store/src/features/priceCalculator/SectionPreview.css.ts, apps/store/src/features/priceCalculator/SectionPreview.tsx
- Tweak styles for insurance form section preview to match Figma
- Get rid of inline styles used in first section
Before
After
=> Update price calculator section preview design to match Figma

apps/store/src/blocks/ProductPageBlockV2/ProductPageBlockV2.css.ts, apps/store/src/blocks/ProductPageBlockV2/ProductPageBlockV2.tsx, apps/store/src/blocks/QuickPurchaseBlock.tsx, apps/store/src/components/Pillow/Pillow.tsx, apps/store/src/components/QuickPurchaseV2/QuickPurchase.tsx, apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/QuickPurchaseForm.css.ts, apps/store/src/components/QuickPurchaseV2/QuickPurchaseForm/QuickPurchaseForm.tsx
- Updated design for showing a single Product in QuickPurchase component.
- Added a field for `productByline` in storyblok
- Update type for Pillow size so we can use the `responsiveVariants`
[Figma](https://www.figma.com/design/p1TEzLLVqJB9gKDNTDVGU4/Hedvig.com?node-id=1141-15438&m=dev)
Updated design
=> Add display for single product option in QuickPurchase

apps/store/src/features/priceCalculator/OfferPresenterV2.tsx
We used to show temporary static data instead of product documents in price calculator page. This workaround is no longer needed
=> Remove productDocuments placeholders from price calculator page, terms-hub returns proper documents now

apps/store/next.config.mjs
- Make sure we redirect cart --> checkout
So old links to cart page don't break.
=> fix(checkoutv2): make sure we redirect cart --> checkout

apps/store/src/components/Cancellation/CancellationForm.tsx, apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx, apps/store/src/features/priceCalculator/OfferPresenterV2.tsx, apps/store/src/graphql/PriceIntentFragment.graphql, packages/ui/src/components/Alert/Alert.css.ts
Show notification messages sent by storefront when presenting offers
For now, this is needed to inform buyer about switching process for Car since we're removing BankSignering. In the future it will also cover "car not owned / decomissioned" notice and switching info for other products
=> Show priceIntent.notifications when presenting offer in price calculator

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/components/ProductPage/PurchaseForm/priceIntentAtoms.ts, apps/store/src/features/widget/CalculatePricePage.tsx
Fixes an issue with `priceIntentAtoms` where a new price intent was being created whenever we have an offer for a product related with an existing price intent in the cart. We want that behaviour for old price calculator but not for the new one.
=> GEN-2430 - fix(sync-price-intent): create new price intent when using priceIntentAtoms in the context of old price calculator

apps/store/src/components/LayoutWithMenu/fetchProductMetadata.ts, apps/store/src/components/ProductData/fetchProductData.ts, apps/store/src/services/apollo/productDataFetchOptions.ts
Add caching for product data (availableProduct and productData queries). 10m TTL in production, 1m otherwise
This should simplify testing terms-hub changes on product pages. Sometimes debug tool is not enough
=> Set product metadata cache TTL to 10m in production and 1m in preview

apps/store/src/app/debugger/seb-leads/CreateSebLeadsForm.tsx, apps/store/src/app/debugger/seb-leads/FormResults.tsx, apps/store/src/app/debugger/seb-leads/ImportSebLeadForm.tsx, apps/store/src/app/debugger/seb-leads/constants.ts, apps/store/src/app/debugger/seb-leads/createSebLead.tsx, apps/store/src/app/debugger/seb-leads/importSebLead.ts, apps/store/src/app/debugger/seb-leads/page.tsx, apps/store/src/app/debugger/seb-leads/types.ts, apps/store/src/app/debugger/trial/debuggerTrial.utils.ts, apps/store/src/utils/getFormValueOrTrrow.ts
Manual import tool for SEB leads debugger
Imports single lead by external ID, returned by previous debugger step
Also, some refactorings
- Extract `getFormValueOrThrow(formData, name)` function
- Extract `<FormResults formState={formState} />` component for rendering errors and success messages
=> Seb lead debugger - import by ID

apps/store/src/pages/[locale]/widget/flows/[...slug].tsx
Subj
SEB lead API pre-creates shopSession and priceIntent based on lead info and then uses new widget flow params to provide entry point for a user
=> Support entering widget flow with pre-create shopSession and priceIntent

apps/store/src/components/Perils/PerilsTable/PerilsTable.tsx
Add support for single tier products like accident
In mobile we show Perils component and in desktop we show a table 
Request from design (Nils)
=> Add single tiers support for PerilsTable

apps/store/src/app/debugger/seb-leads/createSebLead.tsx
Enhanced product handling for SEB lead creation, specifically for condo insurance types.
- Modified the `createSebLead` function to handle specific condo insurance products.
- Introduced logic to differentiate between 'condoInsuranceBrf' and 'condoInsuranceRent' products.
- Added a new `productSubType` field to the metadata for more precise product categorization.
- After discussing with SEB/Insurly we figured out that we  are creating the leads incorrectly
=> Add product subtype handling for condo insurance in SEB lead creation

apps/store/src/app/debugger/seb-leads/createWidgetSession.ts, apps/store/src/app/debugger/seb-leads/generateAndSendOffer.ts, apps/store/src/app/debugger/seb-leads/importSebLead.ts
Updated API endpoints for SEB leads debugger functionality.
Modified API endpoint paths in three files:
- `createWidgetSession.ts`: Changed to `/debug/leads/${leadId}/widgetSession`
- `generateAndSendOffer.ts`: Changed to `/debug/generate-and-send-offer`
- `importSebLead.ts`: Changed to `/debug/leads/${sebInsurelyId}`
This change adds a `/debug` prefix to the API endpoints used in the SEB leads debugger. This modification aims to clearly separate debugging-related API calls from production endpoints.
=> changed endpoints path to reflect its debugging purpose

apps/store/public/mockServiceWorker.js, apps/store/src/features/memberReviews/memberReviews.ts
Use `unstable_cache` from `next/cache` to cache product and company review requests used in store layout
Checkout page has longer response time according to site speed reports and one of root causes seems to be forced cache miss when fetching review metadata in store layout. Adding data cache remediates this
=> Cache commonly used company/product review requests

apps/store/src/app/debugger/seb-leads/createSebLead.tsx
- Updated the environment variable names for SEB Leads API in the `createSebLeadStaging` function:
- Changed `SEB_LEADS_API_URL` to `SEB_LEADS_INSURELY_API_URL`
- Changed `SEB_LEADS_API_KEY` to `SEB_LEADS_INSURELY_API_KEY`
When refactoring to use the function `getEnvOrThrow` I used the wrong name for the env variables
=> rename seb leads env vars

apps/store/src/app/debugger/seb-leads/createSebLead.tsx
- Modified the type definition of `maybeProductSubType` variable in the `createSebLead` function
- Changed from `null` -> `string | undefined = undefined`
SEB api does not except null values for `productSubType` , so if not initialized do not include it.
=> Update product subtype initialization in SEB lead creation

apps/store/src/components/CartNotification/CartToast.tsx
Update Cart toast so we send 'begin_checkout' when "see your cart" button get's clicked
When _Checkout_ and _Cart_ page was merged and old _Cart_ we didn't cover where we should send 'begin_checkout' event:
* User add a quote to the cart
* Cart toast get's displayed
* User clicks on "see your cart"
That scenario was being covered before because cart toast would redirect _Cart_ page which then had buttons that send that event. Since _Cart_ page is now gone and Cart toast redirects directly to _Checkout_ page, we need to send that event in the context of Cart toast.
=> fix(cart-toast): send 'being_checkout' event

apps/store/src/blocks/CardLinkBlock.tsx, apps/store/src/blocks/CardLinkListBlock.tsx, packages/eslint-config-custom/eslint-config-custom.cjs, packages/ui/src/components/Badge/Badge.css.ts, packages/ui/src/theme/sprinkles.css.ts
Subj. Import loops can be confusing for build system, so why not prevent them
Made a few fixes to avoid existing loops
- ui: don't import from package root
- store: convert one circular dependency into unidirectional by moving one component around
No measurable difference in build speed right now
=> Forbid import loops with eslint import/no-cycle rule

apps/store/src/appComponents/RootLayout/RootLayout.tsx, apps/store/src/components/InsurableLimits/InsurableLimits.tsx, apps/store/src/components/ProductItem/EditActionButton.tsx, apps/store/src/components/ProductPage/PurchaseForm/PurchaseFormErrorDialog.tsx, apps/store/src/pages/_app.tsx, packages/ui/src/components/Heading/Heading.tsx, packages/ui/src/components/Text/Text.css.ts, packages/ui/src/components/Text/Text.tsx
Use native CSS text balancer instead of package. The one thing I though was nice with the package was that you could specify a ratio for how much to balance. But as the say in their docs:
> Note that if the native CSS balance ([text-wrap: balance](https://developer.chrome.com/blog/css-text-wrap-balance/)) is available, React Wrap Balancer will use it instead. And the `ratio` option will be ignored in that case. 
So we should just use native CSS rule instead
Improve builds and bundle by using native css solution
=> Remove react-wrap-balancer and use native css rule instead

packages/ui/src/components/Heading/Heading.css.ts, packages/ui/src/components/Heading/Heading.tsx, packages/ui/src/components/Text/Text.css.ts
Make sure text-wrap balance rule isn't being overridden. 
- Unset white space rule we have for base styling as recommended [here](https://developer.chrome.com/docs/css-ui/css-text-wrap-balance#interactions_with_the_white-space_property)
- Create specific styling for Heading component since the CSS order caused the balance rule from Text component to be applied before base Heading styles
Bug reported by Peter for Headings not having balance in prod due to CSS order
=> Fix issue with text-wrap balance being overriden by white space rule

packages/ui/package.json, packages/ui/src/components/Card/Card.css.ts, packages/ui/src/components/Card/Card.stories.tsx, packages/ui/src/components/Card/Card.tsx, packages/ui/src/theme/theme.ts, yarn.lock
Building block for ProductCards and other type of cards
https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=16269-14623&t=EyGtApoX5yoK0pGI-1
=> tech: Initial Card UI component

packages/ui/src/components/Button/Button.css.ts, packages/ui/src/components/Button/Button.helpers.ts, packages/ui/src/components/Button/Button.stories.tsx, packages/ui/src/components/Button/Button.tsx, packages/ui/src/components/Button/IconButton.tsx, packages/ui/src/index.ts
Small wrapper around the `Button` component for icon only buttons similar to the one we have in Hope.
Reuse styles needed for icon buttons.
=> tech: Add IconButton component

packages/ui/src/components/Card/Card.css.ts, packages/ui/src/components/Card/Card.stories.tsx, packages/ui/src/components/Card/Card.tsx
- Add the secondary card variant
- Move the Card aside from header level to card level
Align with Figma
=> tech: add secondary Card variant

apps/store/src/components/ProductCard/DetailsList/DetailsList.stories.tsx, apps/store/src/components/ProductCard/Divider.tsx, apps/store/src/components/ProductCard/ProductCard.stories.tsx, apps/store/src/components/ProductCard/ProductCardDetails.tsx
Compose the default `ProductCard` component out of different building blocks
<a href="https://app.graphite.dev/media/video/RV4Oucd6mLf2QBBMAjRa/d92a9534-6d2d-4fd3-8ff2-3e40ea334d1f.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/RV4Oucd6mLf2QBBMAjRa/d92a9534-6d2d-4fd3-8ff2-3e40ea334d1f.mov">Screen Recording 2024-09-16 at 14.41.09.mov</video>
New `ProductCard` components
https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=16269-14623&t=KfZGhlcQELqgimtF-1
=> tech: Create Default ProductCard story

packages/ui/src/components/Card/Card.css.ts, packages/ui/src/components/Card/Card.stories.tsx, packages/ui/src/components/Card/Card.tsx
Set Card sizes variants to medium and large. Medium cards have smaller padding, radius, and gap.
Match designs
=> tech: Update Card component size variants

apps/store/src/app/[locale]/[[...slug]]/ProductCmsPage.tsx, apps/store/src/app/[locale]/[[...slug]]/ProductCmsPageV2.tsx, apps/store/src/appComponents/providers/StorePageProviders.tsx, apps/store/src/components/ProductData/ProductDataProvider.tsx, apps/store/src/components/ProductPage/ProductPageDataProvider.tsx, apps/store/src/components/ProductPage/PurchaseForm/priceIntentAtoms.ts, apps/store/src/components/ProductPage/PurchaseForm/priceTemplateAtom.ts, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.tsx, apps/store/src/features/priceCalculator/PriceCalculatorStoryProvider.tsx
This is new, simpler solution to "how do we sync jotai atom values with current page?"
It wraps every page that needs page-specific atoms into `JotaiProvider`. When new page is rendered inside such provider, it gets brand new copies of every atom it uses
We still keep `JotaiProvider` at root of out app layout to handle truly global atoms such as cookie consent state and `availableProducts` metadata
Removed older solutions that are no longer needed
- cleanup effect for `currentPriceIntentIdAtom`
- `dangerouslyForceHydrate: true` on providers that injected page-specific initial data
=> Wrap store pages into JotaiProvider to solve atom<->page sync problem. Remove previous solutions like dangerouslyForceHydrate

apps/store/src/app/debugger/seb-leads/ImportAndStoreLeadsForm.tsx, apps/store/src/app/debugger/seb-leads/constants.ts, apps/store/src/app/debugger/seb-leads/importAndStoreLeads.ts, apps/store/src/app/debugger/seb-leads/page.tsx
TLDR;
- Added debugger tool to simulate our own importing leads cron job, which ability to choose `lower/upper` date range
- Added a new `ImportAndStoreLeadsForm` component for importing SEB leads within a specified date range
- Created `importAnsSendLeads` server action to handle the form submission and API request
- Updated `constants.ts` to include new form elements for date range selection
- Integrated the new form into the SEB Leads Debugger page
=> Add import and store SEB leads functionality to debugger

apps/store/src/pages/[locale]/widget/[[...slug]].tsx, apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/calculate-price.tsx, apps/store/src/pages/[locale]/widget/run/[flow]/[shopSessionId]/[priceIntentId]/sign.tsx
- Remove the code that converted server errors in widget flows into 404 pages
This is now regular HTTP 500 that gives more useful info in development and generic error page in production (screenshot below)
Should make it easier to see backend errors in Datadog
=> Stop wrapping widget server errors into 404

apps/store/src/blocks/RichTextBlock/richTextReactRenderer.tsx
Fix regressions from rich text renderer upgrade
- Don't escape `'` and `"` characters in text. Also, explain why it's safe
- Convert styled text into child span with styles. Fixes things like preamble styles
=> Fix richText embedded styling and quote escaping

apps/store/src/components/PriceCalculator/FetchInsurance.css.ts, apps/store/src/components/PriceCalculator/FetchInsurance.tsx
Adds a "cancel" button for Insurely dialog
After they release the new header, we can go ahead and remove some code that relies on `APP_CLOSE`
_Insurely_ is deprecating `APP_CLOSE` event. More information on this [slack thread](https://hedviginsurance.slack.com/archives/C02JPS466NS/p1727243625825469)
=> chore(insurely): added cancel button

apps/store/src/components/PriceCalculator/FetchInsurance.tsx, apps/store/src/services/Insurely/InsurelyIframe.tsx
Removed deprecated event `APP_CLOSE`
_Insurely_ doesn't send those anymore.
relates with #4781
=> chore(insurely): remove deprecated APP_CLOSE event

apps/store/src/app/LayoutJotaiProvider.tsx, apps/store/src/app/layout.tsx, apps/store/src/components/LayoutWithMenu/productMetadataHooks.tsx, apps/store/src/features/memberReviews/CompanyReviewsMetadataProvider.tsx
Explicitly specify `layoutJotaiStore` in cases where we publish atom values in layout and consume them in pages. This is unusual, most atoms are fully contained on one of the sides
Solves the issue with missing values of `productMetadataAtom` in product pages
=> Add layoutJotaiStore to explicitly pass atoms across layout / page boundary

apps/store/src/blocks/HeaderBlock/HeaderBlock.tsx, apps/store/src/components/Header/HeaderMenu/HeaderMenu.css.ts, apps/store/src/components/Header/HeaderMenu/HeaderMenu.tsx, apps/store/src/components/Header/ShoppingCartMenuItem/ShoppingCartMenuItem.css.ts
Make sure we hide shopping cart menu item in mobile view on PriceCalculatorPage
=> Hide shopping cart menu item in mobile (PriceCalculatorPage only)

apps/store/src/components/Header/HeaderMenu/HeaderMenu.css.ts, apps/store/src/components/ProductPage/ScrollPast/ScrollPast.tsx, apps/store/src/components/ProductPage/ScrollPast/useHasScrolledPast.ts, apps/store/src/features/priceCalculator/ProductHeroV2.css.ts, apps/store/src/features/priceCalculator/ProductHeroV2.tsx, apps/store/src/utils/zIndex.tsx
- Refactor `ScrollPast` to export hook for reuse
- Animate a slide in for the sticky header with a CSS animation
https://github.com/user-attachments/assets/1a3a5e35-cba9-4fcf-b0a4-e11ddd940036
When scrolling past the product hero in mobile, we want to show a fixed header with tier and price info
=> Add ProductHero sticky header for mobile

apps/store/src/services/appErrors/appErrorAtom.ts
Fix app error dialogs not appearing
Since app error atom is read from layout and written from pages, it needs explicit store assigned
=> Place appErrorAtom explicitly into layout jotai store. Fixes error dialogs

apps/store/src/blocks/RichTextBlock/richTextReactRenderer.tsx
Resolve rich text anchors into `<span id="$id"> </span>` as it was with previous library (https://github.com/claus/storyblok-rich-text-react-renderer/blob/62e45e9e865376a93989c81d3e24ce1f3f604346/src/index.js#L175)
Fixed delayed and incorrect scrolling to anchors. By default there we rendered as `<a href id="$id"> </a>` and I'm surprised this worked badly instead of not working at all
=> Fix anchor rendering in rich text blocks

apps/store/src/features/priceCalculator/InsuranceDataForm.tsx, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage.tsx, apps/store/src/features/priceCalculator/PriceCalculatorCmsPageContent.css.ts, apps/store/src/features/priceCalculator/PriceCalculatorCmsPageContent.tsx
* Added a inner client as part of `PriceCalculatorCmsPage`:  need to toggle on/off some things based on screen size and step you are in the `PriceCalculator`
* Don't mount _Price calculator's_ `CartToast` on mobile
`ShoppingCartMenuItem` get's visually hidden on mobile but it's still mounted. That causes the notification being shown which is not intended:
https://github.com/user-attachments/assets/72f39558-cb1a-4eed-ac9f-4dcd46d244a8
With that said, the solution is not render `CartToast` on mobile.
The addition of `PriceCalculatorCmsPage` might sound too much but I'm also using it for hiding `PurchaseHero` on mobile when finishing the purchase on the next PR.
=> GEN-2651 - refact(price-calculator-cms-page): mount CartToast only for desktop

apps/store/src/features/priceCalculator/PriceCalculatorCmsPageContent.tsx
* Hides `ProductHero` if on mobile _and_ you've reached the end of the purchasing flow.
Part of the design
=> GEN-2651 - styles(price-calculator): conditionally render product hero

apps/store/src/components/ProductPage/PurchaseForm/PurchaseForm.tsx, apps/store/src/features/priceCalculator/CardRadioGroup.css.ts, apps/store/src/features/priceCalculator/CardRadioGroup.tsx, apps/store/src/features/priceCalculator/DeductibleSelectorV2.tsx, apps/store/src/features/priceCalculator/ProductTierSelectorV2.css.ts, apps/store/src/features/priceCalculator/ProductTierSelectorV2.tsx, packages/ui/src/theme/transitions.ts
Animate product tier and deductible selectors
- background color
- height of "Compare coverage" button on selected tier
Mostly based on @gustaveen's work
**Upd**
- made it smooth without vertical jumps when tier change
- remove initial, on-render animations
- extracted constant for animation duration
New video:
<a href="https://app.graphite.dev/media/video/GLY3tSM85RFBvAf6lFNA/97cef7bf-1f1c-4ddf-a766-04e60f083d32.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/GLY3tSM85RFBvAf6lFNA/97cef7bf-1f1c-4ddf-a766-04e60f083d32.mov">Screen Recording 2024-10-02 at 09.39.43.mov</video>
=> Add animation to CardRadioGroup

apps/store/src/features/widget/SignPage.tsx, apps/store/src/utils/Features.ts
* Condition Home insurance tiers for widget flow to a feature flag.
Sonny wanted that for a couple of [reasons](https://hedviginsurance.slack.com/archives/C02JPS466NS/p1727773070196999)
=> chore(widget): hide tiers under a featue flag

apps/store/src/blocks/RichTextBlock/richTextReactRenderer.tsx
Escaping text manually lead to double-escaping. So, we're not explicitly using escape bypass and rely on React to do escaping
Screenshow showing that richtext stays XSS-safe even when we use `renderToString` with `dangerouslySetInnerHtml` (Content block)
Fixes remaining formatting issues
=> Stop escaping any text elements when rendering rich text

apps/store/src/features/priceCalculator/InsuranceDataForm.css.ts, apps/store/src/features/priceCalculator/InsuranceDataForm.tsx, apps/store/src/features/priceCalculator/PriceCalculatorCmsPageContent.css.ts
Adjust PriceCalculator layout 
Saw that you adjusted some layout @guilhermespopolin and I have an open PR https://github.com/HedvigInsurance/racoon/pull/4806 from earlier that caused a few conflicts so I closed that one and created a new one
- Make sure layout is visually centered in desktop
- Make sure view is not more than 100vh (should not scroll when content isn't taller than viewport)
- Adjust SSN section position in mobile
- Replace inline styles with classnames
https://github.com/user-attachments/assets/6f888b66-d5fc-45e4-851c-4b41b5d929b9
https://github.com/user-attachments/assets/d352ecea-0f3c-4101-a9ab-72f9f3e2054f
Fix layout
=> Fix PriceCalculator layout

apps/store/src/features/priceCalculator/InsuranceDataForm.css.ts, apps/store/src/features/priceCalculator/PriceCalculatorCmsPageContent.css.ts, apps/store/src/features/priceCalculator/PurchaseFormV2.css.ts, apps/store/src/features/priceCalculator/PurchaseFormV2.tsx, packages/ui/src/theme/theme.ts
Align Price Calculator layout page to the 14-col grid to match Figma
=> Align Price Calculator layout page to the grid

apps/store/public/locales/en/purchase-form.json, apps/store/public/locales/sv-se/purchase-form.json, apps/store/src/components/ProductPage/PurchaseForm/priceIntentAtoms.ts, apps/store/src/features/priceCalculator/PurchaseFormV2.css.ts, apps/store/src/features/priceCalculator/PurchaseSummary.css.ts, apps/store/src/features/priceCalculator/PurchaseSummary.tsx, apps/store/src/features/priceCalculator/priceTemplates/SE_PET_CAT_V2.ts, apps/store/src/features/priceCalculator/priceTemplates/SE_PET_DOG_V2.ts, apps/store/src/graphql/ProductOfferFragment.graphql, apps/store/src/services/PriceCalculator/PriceCalculator.types.ts, apps/store/src/services/priceIntent/PriceIntentService.ts
Enable the addition of multi products (E.g: Pet and Car).
https://github.com/user-attachments/assets/699e1535-50d4-42a1-ba0a-4739024b9ef6
We can now from storefront if a particular product is a multi-product or not via `Product.multiple` field. However we also want to control we user should be presented with "Add another" button on the FE side. For that I'm using the price template (`TemplateV2`) so at the end, before presenting that option we check: `Product.multiple && priceTemplate.addMutliple`.
This is a first attempt which requires a full page refresh for new price calculator. Will be investigating a better way to implement this that doesn't require a full page refresh. 
Make it easier to add multiple products when enabled.
=> GEN-2651 - feat(price-calculator): enable addition of multiple products in purchase summary

apps/store/src/features/priceCalculator/PurchaseFormV2.css.ts, apps/store/src/features/priceCalculator/PurchaseFormV2.tsx, apps/store/src/features/priceCalculator/PurchaseSummary.css.ts
Solves a UI bug where cta were not being centralize on _purchase summary_
**Before**
**After**
=> fix(purchase-summary): centralize cta

apps/store/src/components/InputDay/InputDay.css.ts, apps/store/src/components/InputDay/InputDay.tsx, apps/store/src/components/InputDay/InputStartDay.tsx
Adjust disabled styles for InputDay and a disable it when loading.
<a href="https://app.graphite.dev/media/video/RV4Oucd6mLf2QBBMAjRa/71b3daea-24b9-4469-84d5-c99c127e0a65.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/RV4Oucd6mLf2QBBMAjRa/71b3daea-24b9-4469-84d5-c99c127e0a65.mov">Screen Recording 2024-09-27 at 09.45.07.mov</video>
Improved UX for disabled and loading day inputs
=> feat: [GEN-2609] Day input disabled state

packages/ui/src/patterns/grid.ts, packages/ui/src/patterns/index.ts
I wanted a `grid` utility similar to the `stack` one we have, but the problem with grid and vanilla-extract is that we can't have sprinkles with arbitrary values so we need to set `gridTemplateRows` and `gridTemplateColumns` some other way.
I tried different approaches and ended up with this one, it outputs the `className` and `style` attributes so we can spread them in the required element.
It also accepts `className` and merges it with internal classes through `clsx`
Usage:
```
<div {...grid({columns: 3, gap: 'md', className: 'customClassName', ...otherSprinklesCanGoHere})}
```
Grid is a recurring pattern and I wanted to prevent creating `.css.ts` files to add just one property.
=> tech: [GEN-2609] Create grid CSS util

apps/store/src/components/ProductPage/ScrollPast/useHasScrolledPast.ts, apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.tsx
Add offset option to scrolled past hook
It's common that you want to have some offset on when to trigger scrolled past state. In the Product Header instance we want the sticky header to appear before we have scrolled past the full hero. 
https://github.com/user-attachments/assets/262cd845-e1cb-482e-8069-c891565125cf
Avoid sticky header disappearing when page is somewhat shorter
=> Add offset option to scrolled past hook

apps/store/src/app/LayoutJotaiProvider.tsx, apps/store/src/components/Banner/PageBannerTriggers.tsx, apps/store/src/components/GlobalBanner/GlobalBanner.tsx, apps/store/src/components/GlobalBanner/globalBannerState.ts, apps/store/src/components/LayoutWithMenu/productMetadataHooks.tsx, apps/store/src/features/carDealership/CarTrialExtensionBlock.tsx, apps/store/src/features/carDealership/PayForTrial.tsx, apps/store/src/features/carDealership/TrialExtensionForm/useAcceptExtension.ts, apps/store/src/features/memberReviews/CompanyReviewsMetadataProvider.tsx, apps/store/src/globalStore.ts, apps/store/src/pages/_app.tsx, apps/store/src/services/appErrors/appErrorAtom.ts, apps/store/src/utils/useDebugShopSessionId.ts
* Extract a `globalStore` and update `globalBannerState` so it refers to that `globalStore`
GlobalBanner needs to populate jotai's global store, as other features in the app. Though it makes more sense to import that global store from the src folder instead of app router related files like LayoutJotaiProvider.
=> GEN-2728 - refact(global-store): extract a jotai global store

apps/store/src/appComponents/RootLayout/RootLayout.tsx, apps/store/src/appComponents/providers/InternalReporterProvider.tsx, apps/store/src/components/PriceCalculator/useHandleSubmitPriceCalculatorSection.ts, apps/store/src/services/Tracking/InternalEventReporter.ts, apps/store/src/services/Tracking/Tracking.ts, apps/store/src/services/Tracking/TrackingEvent.ts, apps/store/src/services/Tracking/useReportDeviceInfo.ts, apps/store/src/services/Tracking/useTracking.ts, apps/store/src/services/gtm.tsx, apps/store/src/utils/Features.ts
Next step towards new behavior-driven pricing
- Add `InternalEventReporter` and use it behind `Tracking` facade for internal events
- Accumulate internal events in the queue and flush it when submitting any section of price calculator
The goal right now is to do early end-to-end integration. Flushing on price calculator section submit may not be early enough for latency purposes - we'll check this
=> Send new internal events when price calculator is submitted

apps/store/src/components/PriceCalculator/SsnSeSection.tsx, apps/store/src/features/priceCalculator/FormGridNew.css.ts, apps/store/src/features/priceCalculator/FormGridNew.tsx
Make section buttons fixed in mobile with a blurred background
<a href="https://app.graphite.dev/media/video/nv8d5VeBPARA7ezh3Od3/19802524-0d03-41e9-b9e5-291f730c857a.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/nv8d5VeBPARA7ezh3Od3/19802524-0d03-41e9-b9e5-291f730c857a.mov">Screen Recording 2024-10-09 at 11.18.54.mov</video>
=> Make section buttons fixed in mobile

apps/store/src/features/priceCalculator/PriceCalculatorCmsPage/PriceCalculatorCmsPageContent/PriceCalculatorCmsPageContent.css.ts, apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/FormGridNew/FormGridNew.css.ts, apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/InsuranceDataForm.css.ts, apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/InsuranceDataForm.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/OfferPresenterV2.css.ts, apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/OfferPresenterV2.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/PurchaseFormV2.css.ts
Adjust layout to new design. Went over all states and viewports. 
- Make sure layout takes into account the sticky footer in mobile
- Male sure there's no overflow scroll in desktop by removing rows on `pageGrid`
- Add gap between sections on offer presenter
Request from Niles and Peter
=> Adjust layout price calculator

apps/store/src/features/priceCalculator/PurchaseFormV2/PurchaseSummary/PurchaseSummary.tsx
- Shows _bundle discount banners_ only during _purchase summary_ step
Requested by Peter. The motivation is to avoid scenarios where the banner doesn't make sense to be displayed. E.g: You get the banner displayed and then empty your cart. Unless you clear it, the banner saying that you have a discount price will still be there.
=> fix(purchase-summary): show bundle discount banner only during 'purchase summary' step

apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/OfferPresenterV2.tsx
Make sure we set the last form section as active when clicking "Edit information". 
https://github.com/user-attachments/assets/dc344f1e-a15f-4226-a9f0-84d545e0f1c1
Fix issue where last section of purchase form was not reachable.
If you get an offer, go back an edit step 2 of 3, click next section (which goes to offer presenter), then go back to edit you would end up on step 2 instead of step 3
More info in thread https://hedviginsurance.slack.com/archives/C041SD67G82/p1728990672902109
=> fix: v2 Make sure last section is always reachable in purchase form

apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/OfferPresenterV2.tsx
See title
Since it was white without border it wasn't clear it is a button
=> fix: Make show details button into outline variant

apps/store/src/app/[locale]/session/[shopSessionId]/route.ts, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage/PriceCalculatorCmsPage.helpers.ts, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage/PriceCalculatorCmsPage.tsx, apps/store/src/graphql/PriceIntentFragment.graphql, apps/store/src/services/PriceCalculator/PriceCalculator.helpers.ts
Subj.
While using re-targeting links one should be redirected to new price calculator if:
1. _New price calculator_ feature flag is enabled
2. It's a pet insurance. This condition is important; otherwise redirect wouldn't work for non pet insurances in prod.
=> fix(new-price-calculator): enable re-targeting links to new price calculator for pet insurances only

apps/store/src/components/ProductPage/PurchaseForm/OfferPresenter.tsx, apps/store/src/components/ProductPage/PurchaseForm/priceIntentAtoms.ts, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage/PriceCalculatorCmsPageContent/PriceCalculatorCmsPageContent.css.ts, apps/store/src/features/priceCalculator/PriceCalculatorCmsPage/PriceCalculatorCmsPageContent/PriceCalculatorCmsPageContent.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/OfferPresenterV2.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/PurchaseFormV2.css.ts, apps/store/src/features/priceCalculator/PurchaseFormV2/PurchaseFormV2.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/PurchaseSummary/PurchaseSummary.tsx, apps/store/src/features/priceCalculator/priceCalculatorAtoms.ts
_Reset_ new price calculator after adding offer to cart
As can be seen in the following video, when you navigate back to price calculator page after adding an offer to the cart you end up in a misleading state of price calculator which might make you add multiple insurances for the same dog. Observe that for being able to add multiple products to the same dog, the user would need to take some actions that would make a **different** offer to be added to the cart like changing deductible for example. Changing _start date_ doesn't causes that, that's why you can still see only one offer in your cart when _add to cart_ button get's clicked:
https://github.com/user-attachments/assets/3df963db-ccf4-48bc-a344-88d32489ca8e
The same occurs for non multi products as well - like rent. The difference …
=> fix(new-price-calculator): proper reset after adding offer to cart

apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.css.ts, apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.tsx, apps/store/src/features/priceCalculator/ProductHeroV2/StickyProductHeader/StickyProductHeader.tsx, apps/store/src/features/priceCalculator/ProductHeroV2/useCondensedProductHero.ts, apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/InsuranceDataForm.css.ts, apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/InsuranceDataForm.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/SectionNavigation/SectionNavigation.css.ts, apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/SectionNavigation/SectionNavigation.tsx
For the price calculator steps where you fill in your details, the large product hero and pillow should be hidden and instead we show the sticky product header.
- Add a hook to check if product hero should be condensed
- Both `StickyProductHeader` and `ProductHeroPillow` needs to be wrapped with `isReady` state to make sure atoms are populated.
- Reset scrolls position to top between steps to always start at the top
https://github.com/user-attachments/assets/78f860d5-f838-44a3-93c6-35e7fb5d2654
Match the intended design, details find in Figma file https://www.figma.com/design/p1TEzLLVqJB9gKDNTDVGU4/Hedvig.com?node-id=3388-61000&m=dev
=> Conditionally show producthero and sticky header in mobile

apps/store/src/features/priceCalculator/ProductHeroV2/ProgressBar/ProgressBar.tsx
- Hide progress bar for price calculation on view offers step
- Adjust calculation to match number of sections
Hide progress bar for price calculation on view offers step since it only should indicate the progress of getting a price
=> Hide progress bar for price calculation on view offers step

apps/store/src/features/priceCalculator/PriceCalculatorCmsPage/PriceCalculatorCmsPageContent/PriceCalculatorCmsPageContent.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/OfferPresenterV2.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/PurchaseFormV2.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/PurchaseSummary/PurchaseSummary.tsx, apps/store/src/features/priceCalculator/priceCalculatorAtoms.ts
* We need to keep an active query for `PriceIntent` for all price calculator context. So I'm moving `useSyncPriceIntentState` call from `PurchaseFormV2` to `PriceCalculatorCmsPageContent`
* Stop getting offer data used by `PurchaseSummary` form `selectedOfferAtom`. That one should be in sync with price intent changes to avoid unexpected behaviors.
* It's hard to know which offer was just added to the cart while reseting price intent whenever something get's added. We do need to reset price intent whenever something get's added to the cart so I'm replacing _show purchase summary_ state with an _added offer_ state which `PurchaseSummary` can use for its UI. Showing/hiding `PurchaseSummary` now is about changing that state. 
With that said this is how it works now:
* Price calculator get's …
=> fix(new-price-calculator): stop deriving purchase summary state from selected offer

apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.tsx, apps/store/src/features/priceCalculator/ProductHeroV2/StickyProductHeader/StickyProductHeader.tsx
Since we hide the product pillow when `isCondensedProductHero` is true, the behaviour became inconsistent when using a ref to check if you had scrolled past the pillow since the height would be 0 of that empty div. 
We can rather simplify it by just checking scroll position in StickyHeader instead.
StickyHeader is visible when user hasn't scrolled
=> Fix issue where ref to hidden product pillow would cause sticky header to be visible

packages/ui/package.json, packages/ui/src/components/Dialog/Dialog.stories.tsx, packages/ui/src/components/Dialog/LargeDialog.css.ts, packages/ui/src/components/Dialog/LargeDialog.stories.tsx, packages/ui/src/components/Dialog/LargeDialog.tsx, yarn.lock
Animated modal, full-screen on mobile, large and centered on desktop
<a href="https://app.graphite.dev/media/video/GLY3tSM85RFBvAf6lFNA/b36a3a76-0742-48a9-9f7f-f96dd29cf667.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/GLY3tSM85RFBvAf6lFNA/b36a3a76-0742-48a9-9f7f-f96dd29cf667.mov">Screen Recording 2024-10-18 at 13.43.11.mov</video>
Better than current `FullscreenModal` for most use cases
=> Add LargeDialog component and story

apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/ProductTierSelectorV2/ProductTierSelectorV2.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/TierComparisonDialog/TierComparisonDialogContent.tsx
Use `LargeDialog` from previous PR to show tier comparison dialog instead of `FullscreenDialog`
Adjustments compared to Figma:
- Min vertical margin reduced from unknown value to 1rem, this matches min horizontal margin
- Close icon uses current `IconButton` styles, it's 28x28 compared to 24x24 in Figma
- Max width changed from 954px to 960px (40rem exactly)
<a href="https://app.graphite.dev/media/video/GLY3tSM85RFBvAf6lFNA/0545b571-c55d-400c-aa2f-f1ac182f44a4.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/GLY3tSM85RFBvAf6lFNA/0545b571-c55d-400c-aa2f-f1ac182f44a4.mov">Screen Recording 2024-10-23 at 13.04.39.mov</video>
=> Use LargeDialog to compare coverage on Price Calculator Page

apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.css.ts, apps/store/src/features/priceCalculator/ProductHeroV2/ProductHeroV2.tsx
Add close button to sticky header in ProductHeroV2
<a href="https://app.graphite.dev/media/video/nv8d5VeBPARA7ezh3Od3/fe4b636b-951c-4b4d-839a-f29f353c37a6.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/nv8d5VeBPARA7ezh3Od3/fe4b636b-951c-4b4d-839a-f29f353c37a6.mov">Screen Recording 2024-10-24 at 09.38.41.mov</video>
Allow user to close down the price calculator in mobile
=> Add close button to sticky header in ProductHeroV2

apps/store/src/features/priceCalculator/ProductHeroV2/StickyProductHeader/StickyProductHeader.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/InsuranceDataForm.tsx, apps/store/src/features/priceCalculator/PurchaseFormV2/OfferPresenterV2/OfferPresenterV2.tsx
Fix scroll issue in mobile price calculator
Only scroll to top once submitting a section or going back to edit
The form scrolled to top unexpectedly when editing form
=> Fix scroll issue in mobile price calculator

apps/store/src/features/priceCalculator/PurchaseFormV2/InsuranceDataForm/SsnSeSectionV2.tsx
Make sure we scroll to top when completing SSN step
<a href="https://app.graphite.dev/media/video/nv8d5VeBPARA7ezh3Od3/d51b7020-9326-425a-8305-85ec4df0557d.MP4">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/nv8d5VeBPARA7ezh3Od3/d51b7020-9326-425a-8305-85ec4df0557d.MP4">ScreenRecording_10-24-2024 11-40-51_1.MP4</video>
Information gets hidden
=> Add scroll to top when completing ssn step
